Repository filamentphp/filament, pull requests merged in 2021-04, with the labels that each got.

#338 chore: Upgrade Blade Heroicons
  composer.json
  composer.lock
Labels: chore

#339 fix: Page authorization with record
  src/Pages/Page.php
  src/Resources/Pages/CreateRecord.php
  src/Resources/Pages/EditRecord.php
  src/Resources/Pages/ListRecords.php
  src/Resources/RelationManager/EditRecord.php
Labels: bug

#340 fix: Empty select options
  dist/css/filament.css
  dist/js/filament.js
  dist/mix-manifest.json
  packages/forms/resources/views/components/select.blade.php
Labels: bug, ui

#341 fix: Dependable field record caching
  packages/forms/src/HasForm.php
  packages/tables/src/HasTable.php
  src/Resources/Forms/HasForm.php
  src/Resources/Tables/HasTable.php
Labels: bug

#299 Fix new Card component missing col span classes.
  packages/forms/resources/views/components/card.blade.php
Labels: bug

#300 Feature: Add the ability to define a post logout route
  config/filament.php
  src/Http/Livewire/Auth/Logout.php
  tests/Feature/Auth/LogoutTest.php
Labels: enhancement

#298 addRecordActions method in Table
  packages/tables/resources/views/components/table.blade.php
  packages/tables/src/Table.php
Labels: enhancement, pending review

#344 Fix hour, minute, seconds in date-time-picker
  packages/forms/resources/views/components/date-time-picker.blade.php
Labels: bug

#347 fix: Exceeding range with time picker
  packages/forms/resources/views/components/date-time-picker.blade.php
Labels: bug

#372 ui: Text input prefix wrapping
  packages/forms/resources/views/components/text-input.blade.php
Labels: ui

#356 Fix bug when create related item for 2nd time in a row
  src/Resources/RelationManager/CreateRecord.php
Labels: bug

#354 Added two missing german translations
  resources/lang/de/resources/pages/create-record.php
  resources/lang/de/resources/pages/edit-record.php
Labels: i18n

#361 Add Toggle form field
  dist/css/filament.css
  dist/css/filament.css.map
  dist/mix-manifest.json
  packages/forms/resources/views/components/field-group.blade.php
  packages/forms/resources/views/components/toggle.blade.php
  packages/forms/src/Components/Toggle.php
  src/Resources/Forms/Components/Toggle.php
  src/Resources/UserResource.php
Labels: enhancement, pending review

#389 Add missing Spanish translations
  packages/forms/resources/lang/es/fields.php
  resources/lang/es/auth/login.php
  resources/lang/es/resources/pages/create-record.php
  resources/lang/es/resources/pages/edit-record.php
Labels: i18n

#388 Fix translation string from create-record resource page
  src/Resources/Pages/CreateRecord.php
Labels: bug

#382 Fix bug when applying multiple column search and filter
  packages/tables/src/Concerns/CanSearchRecords.php
Labels: bug

#383 [Feature] Allow the checkbox and toggle to render as column fields
  packages/forms/resources/views/components/checkbox.blade.php
  packages/forms/resources/views/components/toggle.blade.php
  packages/forms/src/Components/Checkbox.php
  packages/forms/src/Components/Concerns/CanBeInline.php
  packages/forms/src/Components/Toggle.php
  src/Resources/Forms/Components/Concerns/CanBeInline.php
Labels: enhancement, ui

#401 Set name function protected
  .github/pull_request_template.md
  packages/forms/src/Components/Field.php
  packages/tables/src/Columns/Column.php
  packages/tables/src/Filter.php
  packages/tables/src/RecordActions/Action.php
  src/Pages/Route.php
  src/Resources/Route.php
Labels: bug
