Repository filamentphp/filament, pull requests merged in 2021-09, with the labels that each got.

#565 fix: __get fallthrough when caching forms
  packages/forms/src/Concerns/InteractsWithForms.php
Labels: bug

#567 fix: wire ignore masked inputs
  packages/forms/resources/views/components/text-input.blade.php
Labels: bug

#566 feature: add meta to fields
  packages/forms/src/Components/Component.php
  packages/forms/src/Components/Concerns/HasMeta.php
  tests/Unit/Forms/ComponentTest.php
Labels: enhancement

#568 feature: get fields from container by name or callback
  packages/forms/src/Concerns/HasComponents.php
  tests/Unit/Forms/ComponentContainerTest.php
Labels: enhancement

#573 feature: `Mask::money`
  packages/forms/src/Components/TextInput/Mask.php
Labels: enhancement

#572 feature: `Component::whenTruthy` and `Component::whenFalsy`
  packages/forms/src/Components/Concerns/CanBeHidden.php
  tests/Unit/Forms/HiddenComponentsTest.php
Labels: enhancement

#574 2.x
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/repeater.blade.php
Labels: enhancement

#575 feature: `Select::boolean()`
  packages/forms/src/Components/Select.php
Labels: enhancement

#577 Added Kurdish locale
  packages/forms/resources/lang/ku/fields.php
  packages/tables/resources/lang/ku/pagination.php
  packages/tables/resources/lang/ku/table.php
  resources/lang/ku/auth/login.php
  resources/lang/ku/auth/logout.php
  resources/lang/ku/auth/request-password.php
  resources/lang/ku/auth/reset-password.php
  resources/lang/ku/dashboard.php
  resources/lang/ku/edit-account.php
  resources/lang/ku/layout.php
  resources/lang/ku/nav.php
  resources/lang/ku/resources/pages/create-record.php
  resources/lang/ku/resources/pages/edit-record.php
  resources/lang/ku/resources/pages/list-records.php
  resources/lang/ku/resources/relation-manager.php
  resources/lang/ku/resources/user-resource.php
Labels: enhancement, i18n

#580 feature: `Component::getFlatComponents()` and `Component::getFlatFields()`
  packages/forms/src/Concerns/HasComponents.php
  tests/Unit/Forms/ComponentContainerTest.php
Labels: enhancement

#581 refactor: getComponent using getFlatFields
  packages/forms/src/Concerns/HasComponents.php
Labels: enhancement

#582 feature: support passing array to whenTruthy and whenFalsy
  packages/forms/src/Components/Concerns/CanBeHidden.php
  tests/Unit/Forms/HiddenComponentsTest.php
Labels: enhancement

#583 fix: dont set default value for date pickers
  packages/forms/resources/js/components/date-time-picker.js
Labels: bug

#584 fix: dont init date picker with default date in init
  packages/forms/resources/js/components/date-time-picker.js
  packages/forms/resources/views/components/date-time-picker.blade.php
Labels: bug

#594 fix: dont cache evaluation results
  packages/forms/src/Components/Concerns/EvaluatesCallbacks.php
Labels: bug

#596 feature: Arrayable select options
  packages/forms/src/Components/MultiSelect.php
  packages/forms/src/Components/Select.php
Labels: enhancement

#595 feature: support reactive/lazy modifiers on container components
  packages/forms/src/ComponentContainer.php
  packages/forms/src/Components/Component.php
  packages/forms/src/Components/Field.php
  packages/forms/src/Concerns/HasStateBindingModifiers.php
  tests/Unit/Forms/ComponentTest.php
  tests/Unit/Forms/GridTest.php
  tests/Unit/Forms/StateBindingModifiersTest.php
Labels: enhancement

#609 Action buttons are now more responsive
  dist/css/filament.css
  dist/css/filament.css.map
  dist/mix-manifest.json
  package-lock.json
  resources/views/components/resources/forms/actions.blade.php
Labels: bug, ui

#606 Fix password reset with laravel users
  docs/01-getting-started.md
  src/Http/Livewire/Auth/RequestPassword.php
  src/Http/Livewire/Auth/ResetPassword.php
  src/Models/Concerns/SendsFilamentPasswordResetNotification.php
  src/Models/User.php
  tests/Feature/Auth/RequestPasswordTest.php
  tests/Feature/Auth/ResetPasswordTest.php
Labels: bug
