Repository filamentphp/filament, pull requests merged in 2021-03, with the labels that each got.

#38 feature: new `RichEditor::disableAllToolbarButtons` method
  packages/forms/src/Components/RichEditor.php
Labels: enhancement

#50 Allow for restricted domains
  config/filament.php
  src/Providers/RouteServiceProvider.php
Labels: enhancement

#77 Add extraAttributes to textArea
  .github/ISSUE_TEMPLATE/bug_report.md
  dist/css/filament.css
  dist/css/filament.css.map
  dist/mix-manifest.json
  packages/forms/resources/views/components/textarea.blade.php
  packages/forms/src/Components/Textarea.php
  resources/views/components/branding/auth.blade.php
  tailwind.config.js
Labels: enhancement

#78 like query case sensitive issue fixed
  packages/tables/src/HasTable.php
  src/Resources/Forms/Components/BelongsToSelect.php
Labels: bug

#71 feature: added config option to show / hide default widgets
  config/filament.php
  resources/views/dashboard.blade.php
Labels: enhancement

#90 feature: allow adding existing records in relation managers
  packages/forms/resources/views/components/select.blade.php
  resources/lang/en/resources/relation-manager.php
  resources/views/components/modal.blade.php
  resources/views/relation-manager.blade.php
  resources/views/resources/relation-manager/attach-record.blade.php
  src/Resources/RelationManager.php
  src/Resources/RelationManager/AttachRecord.php
Labels: enhancement

#93 Fix attach modal buttons on mobile
  dist/css/filament.css
  dist/css/filament.css.map
  dist/mix-manifest.json
  resources/views/components/modal.blade.php
  resources/views/relation-manager.blade.php
  resources/views/resources/relation-manager/attach-record.blade.php
Labels: bug

#97 Reduce select component dependence on Livewire
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/resources/views/components/file-upload.blade.php
  packages/forms/resources/views/components/multi-select.blade.php
  packages/forms/resources/views/components/select.blade.php
  packages/forms/resources/views/components/tags-input.blade.php
  packages/forms/src/HasForm.php
  src/Resources/RelationManager/AttachRecord.php
Labels: bug

#105 Small tweaks to the checkboxes and misc. links to use primary color color combos
  dist/css/filament.css
  dist/css/filament.css.map
  dist/mix-manifest.json
  packages/forms/resources/views/components/checkbox.blade.php
  packages/tables/resources/views/cells/text.blade.php
  packages/tables/resources/views/components/table.blade.php
Labels: design

#89 Feature: Add "image" column
  packages/tables/resources/views/cells/image.blade.php
  packages/tables/resources/views/cells/text.blade.php
  packages/tables/resources/views/components/table.blade.php
  packages/tables/src/Columns/Image.php
  src/Resources/Tables/Columns/Image.php
Labels: enhancement

#109 Updated Relationship Manager to include a check for Morph Many and stop the attach/detach panels showing if so.
  resources/views/relation-manager.blade.php
  src/Resources/RelationManager.php
Labels: bug, changes requested

#113 Adding the ability to overrride the default layout
  resources/views/components/app-header.blade.php
  src/Pages/Page.php
Labels: enhancement

#117 fix: support URLs in image column
  packages/tables/src/Columns/Image.php
Labels: bug

#118 feature: View column
  packages/tables/src/Columns/Column.php
  packages/tables/src/Columns/View.php
  src/Resources/Tables/Columns/View.php
Labels: enhancement

#119 Feature: Add external url capability for a text column URL
  packages/tables/resources/views/cells/text.blade.php
  packages/tables/src/Columns/Text.php
Labels: enhancement

#116 feature: add new Icon and Boolean column
  packages/tables/resources/views/cells/boolean.blade.php
  packages/tables/resources/views/cells/icon.blade.php
  packages/tables/resources/views/cells/image.blade.php
  packages/tables/src/Columns/Boolean.php
  packages/tables/src/Columns/Concerns/CanCallAction.php
  packages/tables/src/Columns/Concerns/CanOpenUrl.php
  packages/tables/src/Columns/Icon.php
  packages/tables/src/Columns/Image.php
  packages/tables/src/Columns/Text.php
  resources/views/components/button.blade.php
  src/Resources/Tables/Columns/Boolean.php
  src/Resources/Tables/Columns/Icon.php
Labels: enhancement

#127 Conditional form component modification
  packages/forms/src/Components/Component.php
  packages/forms/src/Form.php
  src/Resources/Pages/CreateRecord.php
Labels: enhancement

#134 Fix extra image column semicolons
  packages/tables/resources/views/cells/image.blade.php
Labels: bug

#128 Dependable fields
  packages/forms/src/Components/Field.php
Labels: enhancement

#130 Form groups
  packages/forms/resources/views/components/group.blade.php
  packages/forms/src/Components/Group.php
  src/Resources/Forms/Components/Group.php
Labels: enhancement

#129 Page hooks
  src/Resources/Pages/CreateRecord.php
  src/Resources/Pages/EditRecord.php
  src/Resources/Pages/Page.php
Labels: enhancement

#137 [i18n] Italian translation
  packages/forms/resources/lang/it/fields.php
  packages/tables/resources/lang/it/pagination.php
  packages/tables/resources/lang/it/table.php
  resources/lang/it/auth/login.php
  resources/lang/it/auth/logout.php
  resources/lang/it/auth/request-password.php
  resources/lang/it/auth/reset-password.php
  resources/lang/it/dashboard.php
  resources/lang/it/edit-account.php
  resources/lang/it/nav.php
  resources/lang/it/resources/pages/create-record.php
  resources/lang/it/resources/pages/edit-record.php
  resources/lang/it/resources/pages/list-records.php
  resources/lang/it/resources/relation-manager.php
  resources/lang/it/resources/user-resource.php
Labels: i18n

#141 Add spanish translation
  packages/forms/resources/lang/es/fields.php
  packages/tables/resources/lang/es/pagination.php
  packages/tables/resources/lang/es/table.php
  resources/lang/es/auth/login.php
  resources/lang/es/auth/logout.php
  resources/lang/es/auth/request-password.php
  resources/lang/es/auth/reset-password.php
  resources/lang/es/dashboard.php
  resources/lang/es/edit-account.php
  resources/lang/es/nav.php
  resources/lang/es/resources/pages/create-record.php
  resources/lang/es/resources/pages/edit-record.php
  resources/lang/es/resources/pages/list-records.php
  resources/lang/es/resources/relation-manager.php
  resources/lang/es/resources/user-resource.php
Labels: i18n

#139 Add german i18n
  packages/forms/resources/lang/de/fields.php
  packages/tables/resources/lang/de/pagination.php
  packages/tables/resources/lang/de/table.php
  resources/lang/de/auth/login.php
  resources/lang/de/auth/logout.php
  resources/lang/de/auth/request-password.php
  resources/lang/de/auth/reset-password.php
  resources/lang/de/dashboard.php
  resources/lang/de/edit-account.php
  resources/lang/de/nav.php
  resources/lang/de/resources/pages/create-record.php
  resources/lang/de/resources/pages/edit-record.php
  resources/lang/de/resources/pages/list-records.php
  resources/lang/de/resources/relation-manager.php
  resources/lang/de/resources/user-resource.php
Labels: i18n

#143 multiple resource relationships layout issue fixed
  resources/views/components/resources/relations.blade.php
Labels: bug

#153 Allow when() modification callback to access record details
  packages/forms/src/Components/Component.php
Labels: enhancement

#152 Added trim functionality to Text Column
  packages/tables/src/Columns/Text.php
Labels: enhancement

#106 Implement advanced authorization checks using roles and policies
  packages/tables/resources/lang/de/table.php
  packages/tables/resources/lang/en/table.php
  packages/tables/resources/lang/es/table.php
  packages/tables/resources/lang/fr/table.php
  packages/tables/resources/lang/it/table.php
  packages/tables/resources/lang/nl/table.php
  packages/tables/resources/lang/pt-br/table.php
  packages/tables/resources/views/components/container.blade.php
  packages/tables/resources/views/components/delete-selected.blade.php
  packages/tables/resources/views/components/table.blade.php
  packages/tables/resources/views/record-actions/link.blade.php
  packages/tables/src/Columns/Column.php
  packages/tables/src/RecordActions/Action.php
  packages/tables/src/RecordActions/Concerns/CanCallAction.php
  packages/tables/src/RecordActions/Concerns/CanOpenUrl.php
  packages/tables/src/RecordActions/Link.php
  packages/tables/src/Table.php
  resources/lang/de/resources/pages/list-records.php
  resources/lang/en/resources/pages/list-records.php
  resources/lang/es/resources/pages/list-records.php
  resources/lang/fr/resources/pages/list-records.php
  resources/lang/it/resources/pages/list-records.php
  resources/lang/nl/resources/pages/list-records.php
  resources/lang/pt-br/resources/pages/list-records.php
  resources/views/components/resources/relations.blade.php
  resources/views/relation-manager.blade.php
  resources/views/resources/pages/edit-record.blade.php
  resources/views/resources/pages/list-records.blade.php
  src/AuthorizationManager.php
  src/Filament.php
  src/FilamentManager.php
  src/Pages/Page.php
  src/Resources/Pages/CreateRecord.php
  src/Resources/Pages/EditRecord.php
  src/Resources/Pages/ListRecords.php
  src/Resources/Pages/Page.php
  src/Resources/RelationManager.php
  src/Resources/RelationManager/EditRecord.php
  src/Resources/Resource.php
  src/Resources/Tables/RecordActions/Link.php
  src/Roles/Authorization.php
  src/View/Components/Nav.php
Labels: enhancement

#147 Added Indonesian translation file
  packages/forms/resources/lang/id/fields.php
  packages/tables/resources/lang/id/pagination.php
  packages/tables/resources/lang/id/table.php
  resources/lang/id/auth/login.php
  resources/lang/id/auth/logout.php
  resources/lang/id/auth/request-password.php
  resources/lang/id/auth/reset-password.php
  resources/lang/id/dashboard.php
  resources/lang/id/edit-account.php
  resources/lang/id/nav.php
  resources/lang/id/resources/pages/create-record.php
  resources/lang/id/resources/pages/edit-record.php
  resources/lang/id/resources/pages/list-records.php
  resources/lang/id/resources/relation-manager.php
  resources/lang/id/resources/user-resource.php
Labels: i18n

#155 Publish package translations
  src/FilamentServiceProvider.php
Labels: enhancement

#148 feature: basic theming support
  dist/css/filament.css
  dist/css/filament.css.map
  dist/mix-manifest.json
  resources/css/base.css
  resources/views/components/layouts/base.blade.php
  resources/views/dashboard.blade.php
  src/Commands/Aliases/MakeThemeCommand.php
  src/Commands/MakeThemeCommand.php
  src/Events/ServingFilament.php
  src/Filament.php
  src/FilamentManager.php
  src/FilamentServiceProvider.php
  src/Http/Middleware/DispatchServingFilamentEvent.php
  src/Providers/RouteServiceProvider.php
  stubs/Theme.stub
  tailwind.config.js
Labels: enhancement

#157 fix: allow uploaded images to s3 with private visibility to load
  packages/forms/src/HasForm.php
  packages/tables/src/Columns/Image.php
Labels: bug

#164 feature: implement new avatar providers
  config/filament.php
  src/AvatarProviders/Contracts/AvatarProvider.php
  src/AvatarProviders/GravatarProvider.php
  src/AvatarProviders/UiAvatarProvider.php
  src/Filament.php
  src/FilamentManager.php
  src/FilamentServiceProvider.php
  src/View/Components/Avatar.php
Labels: enhancement

#163 feature: create basic Plugin API
  src/PluginServiceProvider.php
Labels: enhancement

#167 Custom route key names
  src/Resources/Pages/EditRecord.php
Labels: bug

#159 feature: class based filters
  packages/tables/src/Filter.php
  packages/tables/src/HasTable.php
  src/Commands/Aliases/MakeFilterCommand.php
  src/Commands/MakeFieldCommand.php
  src/Commands/MakeFilterCommand.php
  src/FilamentServiceProvider.php
  stubs/Filter.stub
  stubs/ResourceFilter.stub
Labels: enhancement

#177 fix: undefined method URL on view columns
  packages/tables/src/Table.php
Labels: bug

#170 add georgian(ka) language translations
  packages/forms/resources/lang/ka/fields.php
  packages/tables/resources/lang/ka/pagination.php
  packages/tables/resources/lang/ka/table.php
  resources/lang/ka/auth/login.php
  resources/lang/ka/auth/logout.php
  resources/lang/ka/auth/request-password.php
  resources/lang/ka/auth/reset-password.php
  resources/lang/ka/dashboard.php
  resources/lang/ka/edit-account.php
  resources/lang/ka/nav.php
  resources/lang/ka/resources/pages/create-record.php
  resources/lang/ka/resources/pages/edit-record.php
  resources/lang/ka/resources/pages/list-records.php
  resources/lang/ka/resources/relation-manager.php
  resources/lang/ka/resources/user-resource.php
Labels: i18n

#178 fix: add view prop to resource page stub
  stubs/ResourcePage.stub
Labels: bug

#175 Allow additional recordActions
  packages/tables/src/Table.php
Labels: enhancement

#179 fix: file upload field in tab firing requests like a machine gun
  dist/css/filament.css
  dist/css/filament.css.map
  dist/js/filament.js
  dist/js/filament.js.map
  dist/mix-manifest.json
  packages/forms/resources/views/components/file-upload.blade.php
  resources/js/alpine.js
  resources/js/filament.js
Labels: bug

#173 Feature : Ability to preload options for belongsTo field
  src/Resources/Forms/Components/BelongsToSelect.php
Labels: enhancement

#169 Catalan I8n
  packages/forms/resources/lang/ca/fields.php
  packages/tables/resources/lang/ca/pagination.php
  packages/tables/resources/lang/ca/table.php
  resources/lang/ca/auth/login.php
  resources/lang/ca/auth/logout.php
  resources/lang/ca/auth/request-password.php
  resources/lang/ca/auth/reset-password.php
  resources/lang/ca/dashboard.php
  resources/lang/ca/edit-account.php
  resources/lang/ca/nav.php
  resources/lang/ca/resources/pages/create-record.php
  resources/lang/ca/resources/pages/edit-record.php
  resources/lang/ca/resources/pages/list-records.php
  resources/lang/ca/resources/relation-manager.php
  resources/lang/ca/resources/user-resource.php
  src/Resources/UserResource.php
Labels: i18n, pending changes

#181 feature: allow customising (primary) record actions
  src/Resources/RelationManager.php
Labels: enhancement

#182 feature: add plugin service provider hooks for register
  src/PluginServiceProvider.php
Labels: enhancement

#183 Custom form component and column construction commands
  src/Commands/Aliases/MakeColumnCommand.php
  src/Commands/Aliases/MakeFilterCommand.php
  src/Commands/Aliases/MakeFormComponentCommand.php
  src/Commands/Aliases/MakeThemeCommand.php
  src/Commands/MakeColumnCommand.php
  src/Commands/MakeFormComponentCommand.php
  src/FilamentServiceProvider.php
  src/Resources/Forms/Components/Component.php
  src/Resources/Forms/Components/Field.php
  src/Resources/Tables/Columns/Column.php
  stubs/CellView.stub
  stubs/Column.stub
  stubs/FormComponent.stub
  stubs/FormComponentView.stub
  stubs/ResourceColumn.stub
  stubs/ResourceField.stub
  stubs/ResourceFormComponent.stub
Labels: enhancement

#184 add Arabic(ar) language translations
  packages/forms/resources/lang/ar/fields.php
  packages/tables/resources/lang/ar/pagination.php
  packages/tables/resources/lang/ar/table.php
  resources/lang/ar/auth/login.php
  resources/lang/ar/auth/logout.php
  resources/lang/ar/auth/request-password.php
  resources/lang/ar/auth/reset-password.php
  resources/lang/ar/dashboard.php
  resources/lang/ar/edit-account.php
  resources/lang/ar/nav.php
  resources/lang/ar/resources/pages/create-record.php
  resources/lang/ar/resources/pages/edit-record.php
  resources/lang/ar/resources/pages/list-records.php
  resources/lang/ar/resources/relation-manager.php
  resources/lang/ar/resources/user-resource.php
Labels: i18n, pending changes

#187 feature: EditRecord fill hooks
  src/Resources/Pages/EditRecord.php
Labels: enhancement

#191 Register Plugin Resources with Livewire
  routes/web.php
  src/PluginServiceProvider.php
  src/Providers/RouteServiceProvider.php
Labels: bug

#197 Fix Bug: Multiple BelongsToSelect fields. When trying to change value of one will reset the value of the other one
  packages/forms/resources/views/components/select.blade.php
  src/Commands/MakeResourceCommand.php
  stubs/DefaultResourcePage.stub
Labels: bug

#200 Fix multiple file upload fields on one page
  packages/forms/resources/views/components/file-upload.blade.php
Labels: bug

#203 Record action icons
  dist/css/filament.css
  dist/css/filament.css.map
  dist/js/filament.js.map
  dist/mix-manifest.json
  packages/tables/resources/views/record-actions/icon.blade.php
  packages/tables/resources/views/record-actions/link.blade.php
  packages/tables/src/RecordActions/Action.php
  packages/tables/src/RecordActions/Icon.php
  packages/tables/src/RecordActions/Link.php
  src/Resources/Pages/ListRecords.php
  src/Resources/Tables/RecordActions/Icon.php
Labels: enhancement

#212 Cannot read property 'split' of null issue fixed
  packages/tables/resources/views/components/table.blade.php
Labels: bug

#214 chore: php-cs-fixer workflow
  .github/workflows/php-cs-fixer.yml
  .php_cs.dist
Labels: chore

#210 Allow Title Property on RecordAction Links and Icons
  packages/tables/resources/views/record-actions/icon.blade.php
  packages/tables/resources/views/record-actions/link.blade.php
  packages/tables/src/RecordActions/Action.php
  packages/tables/src/RecordActions/Link.php
Labels: enhancement

#223 fix: Filter name generated by command
  src/Commands/MakeFilterCommand.php
Labels: bug

#219 fix: dont merge middleware config
  src/FilamentServiceProvider.php
Labels: bug

#220 fix: auto register widget component
  src/PluginServiceProvider.php
Labels: bug

#228 don't show img tag if path is null
  packages/tables/resources/views/cells/image.blade.php
Labels: bug

#221 feature: generate resourceUrls in columns
  src/Resources/Tables/Columns/Boolean.php
  src/Resources/Tables/Columns/Column.php
  src/Resources/Tables/Columns/Concerns/InteractsWithResource.php
  src/Resources/Tables/Columns/Icon.php
  src/Resources/Tables/Columns/Image.php
  src/Resources/Tables/Columns/Text.php
Labels: enhancement

#222 feature: add new Hidden field
  packages/forms/resources/views/components/hidden.blade.php
  packages/forms/src/Components/Hidden.php
  src/Resources/Forms/Components/Hidden.php
Labels: enhancement

#241 fix: Class newlines
  .php_cs.dist
Labels: bug

#243 allow absolute URL as avatar
  src/helpers.php
Labels: bug, pending changes

#245 use resolveRouteBinding method to resolve model
  src/Resources/Pages/EditRecord.php
Labels: bug, pending changes

#248 hotfix: style registration in service provider
  src/PluginServiceProvider.php
Labels: bug

#246 value should be casted to string
  packages/forms/src/Components/Select.php
Labels: bug, needs more info

#251 feature: Markdown field v1
  dist/css/filament.css
  dist/css/filament.css.map
  dist/mix-manifest.json
  packages/forms/resources/lang/en/fields.php
  packages/forms/resources/views/components/field-group.blade.php
  packages/forms/resources/views/components/markdown-editor.blade.php
  packages/forms/resources/views/components/textarea.blade.php
  packages/forms/src/Components/MarkdownEditor.php
  src/Resources/Forms/Components/MarkdownEditor.php
Labels: enhancement

#254 feature: add image uploads to MD editor
  dist/css/filament.css
  dist/css/filament.css.map
  dist/mix-manifest.json
  packages/forms/config/forms.php
  packages/forms/resources/views/components/markdown-editor.blade.php
  packages/forms/src/Components/Concerns/HasAttachments.php
  packages/forms/src/Components/MarkdownEditor.php
  packages/forms/src/Components/RichEditor.php
  packages/forms/src/Http/Controllers/FormAttachmentController.php
  routes/web.php
  src/FilamentServiceProvider.php
Labels: enhancement

#255 Clean up Key-value field translations
  packages/forms/resources/lang/en/fields.php
  packages/forms/src/Components/KeyValue.php
Labels: chore

#263 fix: Markdown field highlight
  dist/css/filament.css
  dist/css/filament.css.map
  dist/mix-manifest.json
  packages/forms/resources/views/components/markdown-editor.blade.php
  tailwind.config.js
Labels: bug

#264 feature: mod+s keyboard shortcut for save
  resources/views/components/layouts/base.blade.php
  resources/views/resources/pages/create-record.blade.php
  resources/views/resources/pages/edit-record.blade.php
Labels: enhancement

#250 Fix dependent field for relation manager in record creation form
  src/Resources/RelationManager/CreateRecord.php
Labels: bug

#267 Update markdown-editor.blade.php
  packages/forms/resources/views/components/markdown-editor.blade.php
Labels: bug, ui

#215 New section form component features
  dist/css/filament.css
  dist/css/filament.css.map
  dist/mix-manifest.json
  package-lock.json
  package.json
  packages/forms/resources/views/components/section.blade.php
  packages/forms/resources/views/components/tab.blade.php
  packages/forms/resources/views/components/tabs.blade.php
  packages/forms/src/Components/Concerns/CanConcealFields.php
  packages/forms/src/Components/Section.php
  packages/forms/src/Components/Tab.php
  packages/forms/src/Components/Tabs.php
  packages/forms/src/HasForm.php
Labels: enhancement, pending changes

#268 fix: Preloaded select by default
  src/Resources/Forms/Components/BelongsToSelect.php
Labels: bug

#272 fix: Remove route consumption from service provider
  packages/forms/config/forms.php
  packages/forms/src/Components/MarkdownEditor.php
  packages/forms/src/Components/RichEditor.php
  routes/web.php
  src/FilamentServiceProvider.php
  src/Providers/RouteServiceProvider.php
Labels: bug

#291 fix: Str class not found on relation manager
  src/Resources/RelationManager.php
Labels: bug

#294 fix: Sorting
  packages/tables/src/Concerns/CanSortRecords.php
Labels: bug
