Repository filamentphp/filament, pull requests merged in 2021-10, with the labels that each got.

#622 Dutch translations improvements
  resources/lang/nl/auth/request-password.php
  resources/lang/nl/resources/user-resource.php
Labels: enhancement, i18n

#623 Get redirect url for resource pages
  src/Resources/Pages/CreateRecord.php
  src/Resources/Pages/EditRecord.php
Labels: enhancement

#624 Document resource page redirects
  docs/02-resources.md
Labels: documentation, enhancement

#629 document resource page code snippet updated
  docs/02-resources.md
Labels: documentation

#634 Fix for labels not working for relationship fields (select and multiselect)
  packages/forms/src/Components/BelongsToManyMultiSelect.php
  packages/forms/src/Components/BelongsToSelect.php
Labels: bug

#635 fixing collapsed states
  packages/forms/src/Components/Section.php
Labels: bug

#630 Form Layout Example Fixes (docs)
  packages/forms/docs/03-fields.md
  packages/forms/docs/04-layout.md
Labels: bug, documentation, enhancement
