Repository filamentphp/filament, pull requests merged in 2021-11, with the labels that each got.

#666 Add docs on how to register an action.
  docs/02-resources.md
Labels: documentation, enhancement

#673 fix: masked inputs not reflecting server changes
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/text-input.js
Labels: bug

#675 Update variable names to work with intended example
  packages/forms/docs/03-fields.md
Labels: documentation

#676 Don't load collapsable alpine when section is not collapsable
  packages/forms/resources/views/components/section.blade.php
Labels: bug

#677 Animate the show hide button and make it cooler
  packages/forms/resources/views/components/section.blade.php
Labels: ui

#679 Allows pattern definition to work
  packages/forms/src/Components/TextInput/Mask.php
Labels: bug

#681 style: add width to action column
  packages/tables/resources/views/index.blade.php
Labels: ui

#684 Add autocapitalize attribute to maintained concerns
  packages/forms/resources/views/components/text-input.blade.php
  packages/forms/resources/views/components/textarea.blade.php
  packages/forms/src/Components/Concerns/CanBeAutocapitalized.php
  packages/forms/src/Components/TextInput.php
  packages/forms/src/Components/Textarea.php
Labels: enhancement

#687 remove laravel/ui
  packages/forms/composer.json
  packages/forms/composer.lock
  packages/forms/src/Commands/InstallCommand.php
  packages/forms/src/FormsPreset.php
  packages/forms/src/FormsServiceProvider.php
  packages/tables/composer.json
  packages/tables/composer.lock
  packages/tables/src/Commands/InstallCommand.php
  packages/tables/src/TablesPreset.php
  packages/tables/src/TablesServiceProvider.php
Labels: enhancement

#697 (fix) Fix type hinting for sortable()
  packages/tables/src/Columns/Concerns/CanBeSortable.php
Labels: bug

#702 Change method cache from boot to booted Trait
  packages/tables/src/Concerns/InteractsWithTable.php
Labels: bug

#704 Form getState method named argument only and except option added
  packages/forms/src/Concerns/HasState.php
Labels: enhancement

#705 Update getState method to return collection instead of array
  packages/forms/src/Concerns/HasState.php
Labels: enhancement

#707 (fix) Use extraAttributes in Card component
  packages/admin/dist/app.js
  packages/admin/dist/mix-manifest.json
  packages/forms/resources/views/components/card.blade.php
Labels: bug

#710 getStateOnly and getStateExcept method added
  packages/forms/src/Concerns/HasState.php
Labels: enhancement

#711 Update helper-text.blade.php
  packages/forms/resources/views/components/field-wrapper/helper-text.blade.php
Labels: bug

#712 Update 03-fields.md
  packages/forms/docs/03-fields.md
Labels: documentation, enhancement

#716 Add getTableContentFooter() functionality
  packages/tables/resources/views/components/table.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Concerns/HasContentFooter.php
  packages/tables/src/Concerns/InteractsWithTable.php
  packages/tables/src/Table.php
Labels: enhancement

#727 fix SpatieTagsInput error
  packages/spatie-laravel-tags-plugin/src/Forms/Components/SpatieTagsInput.php
Labels: bug

#730 fix: filters resetting when the component is booted
  packages/tables/src/Concerns/HasFilters.php
  packages/tables/src/Concerns/InteractsWithTable.php
Labels: bug

#728 Update forms documentation with additional search options
  packages/forms/docs/03-fields.md
Labels: documentation, enhancement

#722 Make Markdown editor controls wrap on smaller devices
  packages/forms/resources/views/components/markdown-editor.blade.php
Labels: bug, ui

#719 Allow unescaping labels
  packages/forms/resources/views/components/field-wrapper/index.blade.php
Labels: enhancement

#738 SelectFilter - Fix bug with falsy values
  packages/tables/src/Filters/SelectFilter.php
Labels: bug

#741 feature(tables): support static select filters
  packages/tables/src/Filters/SelectFilter.php
Labels: enhancement
