Repository filamentphp/filament, pull requests merged in 2021-06, with the labels that each got.

#419 add Simplified Chinese lang
  packages/forms/resources/lang/zh-CN/fields.php
  packages/tables/resources/lang/zh-CN/pagination.php
  packages/tables/resources/lang/zh-CN/table.php
  resources/lang/zh-CN/auth/login.php
  resources/lang/zh-CN/auth/logout.php
  resources/lang/zh-CN/auth/request-password.php
  resources/lang/zh-CN/auth/reset-password.php
  resources/lang/zh-CN/dashboard.php
  resources/lang/zh-CN/edit-account.php
  resources/lang/zh-CN/layout.php
  resources/lang/zh-CN/nav.php
  resources/lang/zh-CN/resources/pages/create-record.php
  resources/lang/zh-CN/resources/pages/edit-record.php
  resources/lang/zh-CN/resources/pages/list-records.php
  resources/lang/zh-CN/resources/relation-manager.php
  resources/lang/zh-CN/resources/user-resource.php
Labels: i18n

#415 Allow to use html in prefixes plus add postfix method
  packages/forms/resources/views/components/text-input.blade.php
  packages/forms/src/Components/Concerns/HasPostfix.php
  packages/forms/src/Components/TextInput.php
Labels: enhancement, ui

#429 fix file upload isn't cleared after create
  packages/forms/resources/views/components/file-upload.blade.php
  packages/forms/resources/views/components/select.blade.php
Labels: bug

#409 DatePicker set first day of week and remove manual translation files
  packages/forms/config/forms.php
  packages/forms/resources/lang/ar/fields.php
  packages/forms/resources/lang/ca/fields.php
  packages/forms/resources/lang/da/fields.php
  packages/forms/resources/lang/de/fields.php
  packages/forms/resources/lang/en/fields.php
  packages/forms/resources/lang/es/fields.php
  packages/forms/resources/lang/fa/fields.php
  packages/forms/resources/lang/fr/fields.php
  packages/forms/resources/lang/id/fields.php
  packages/forms/resources/lang/it/fields.php
  packages/forms/resources/lang/ka/fields.php
  packages/forms/resources/lang/nl/fields.php
  packages/forms/resources/lang/pt-br/fields.php
  packages/forms/resources/lang/ru/fields.php
  packages/forms/resources/lang/sv/fields.php
  packages/forms/resources/lang/zh-CN/fields.php
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/src/Components/DatePicker.php
  packages/forms/src/Components/DateTimePicker.php
Labels: enhancement, i18n
