Repository filamentphp/filament, pull requests merged in 2021-08, with the labels that each got.

#514 feature: support hiding tabs conditionally
  packages/forms/src/Components/Tabs.php
Labels: enhancement

#524 fix: URL generation for custom resource pages
  src/Resources/Pages/Page.php
  src/Resources/Resource.php
Labels: bug

#526 Fix date column always shown in english
  packages/tables/src/Columns/Text.php
Labels: bug

#529 Fix unique validation rule for custom primary keys
  src/Resources/Forms/Components/Concerns/CanBeUnique.php
Labels: bug

#553 Add "Cancel" to create-record (de)
  resources/lang/de/resources/pages/create-record.php
Labels: enhancement, i18n

#554 Fix typo in Getting Started - Stubs
  docs/01-getting-started.md
Labels: documentation

#544 Allow specifying file name for uploaded files
  packages/forms/src/Concerns/CanUploadFiles.php
Labels: enhancement
