Repository filamentphp/filament, pull requests merged in 2021-12, with the labels that each got.

#745 Add ability to sort widgets
  src/FilamentManager.php
  src/Widgets/Widget.php
Labels: enhancement, pending changes

#749 Add ability to hide widgets
  src/FilamentManager.php
  src/Widgets/Widget.php
Labels: enhancement

#750 Add additional comparison & validation rules
  packages/forms/src/Components/Concerns/CanBeValidated.php
Labels: enhancement

#751 Fix for TimePicker asking for date rule
  packages/forms/src/Components/DateTimePicker.php
Labels: bug

#736 Add default filter
  composer.lock
  docs/04-tables.md
  packages/tables/src/Concerns/CanFilterRecords.php
  packages/tables/src/Table.php
Labels: enhancement, pending review

#688 Added an object override for direct access to imask configuration
  packages/forms/src/Components/TextInput/Mask.php
Labels: enhancement, pending review

#729 Radio field
  packages/forms/docs/03-fields.md
  packages/forms/resources/views/components/radio.blade.php
  packages/forms/src/Components/Radio.php
Labels: enhancement

#758 Fixes #757
  packages/admin/docs/02-resources.md
Labels: bug, documentation

#760 Update recordTitleTttribute doc section
  packages/admin/docs/02-resources.md
Labels: bug, documentation

#766 fix: Encode image column path
  packages/tables/resources/views/columns/image-column.blade.php
Labels: bug

#767 fix: Date time picker null focused date
  packages/admin/dist/app.css.map
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/admin/dist/module.esm.js
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/date-time-picker.js
Labels: bug

#780 Remove extra bracket Forms doc Select example
  packages/forms/docs/03-fields.md
Labels: bug, documentation

#779 Update 02-resources.md
  packages/admin/docs/02-resources.md
Labels: bug, documentation

#781 feature: Morph many relation managers
  packages/admin/docs/02-resources.md
  packages/admin/docs/09-upgrade-guide.md
  packages/admin/src/Commands/Aliases/MakeMorphManyCommand.php
  packages/admin/src/Commands/MakeMorphManyCommand.php
  packages/admin/src/FilamentServiceProvider.php
  packages/admin/src/Resources/RelationManagers/MorphManyRelationManager.php
  packages/admin/stubs/MorphManyRelationManager.stub
Labels: enhancement

#762 SelectFilter using whereRelation in related columns
  packages/admin/docs/03-pages.md
  packages/tables/docs/04-filters.md
  packages/tables/src/Concerns/HasRecords.php
  packages/tables/src/Concerns/InteractsWithTable.php
  packages/tables/src/Contracts/HasTable.php
  packages/tables/src/Filters/SelectFilter.php
  packages/tables/src/Table.php
Labels: enhancement

#792 document command to publish language files
  packages/admin/docs/01-installation.md
  packages/forms/docs/01-installation.md
  packages/tables/docs/01-installation.md
Labels: documentation, enhancement

#807 Fix typo for Tailwind CSS init command
  packages/admin/docs/07-appearance.md
Labels: bug, documentation

#790 Use ISO 15897 standard for languages that differ by territory
  packages/forms/resources/lang/pt_BR/components.php
  packages/forms/resources/lang/zh_CN/components.php
  packages/tables/resources/lang/pt_BR/table.php
  packages/tables/resources/lang/zh_CN/table.php
Labels: bug, pending review

#811 Allow to display a conversion
  packages/spatie-laravel-media-library-plugin/docs/03-table-columns.md
  packages/spatie-laravel-media-library-plugin/src/Tables/Columns/SpatieMediaLibraryImageColumn.php
Labels: enhancement

#804 Disable registering certain resources to navigation
  packages/admin/docs/02-resources.md
  packages/admin/docs/05-navigation.md
  packages/admin/src/Pages/Page.php
  packages/admin/src/Resources/Resource.php
Labels: enhancement, pending changes

#824 Polish translation
  packages/admin/resources/lang/pl/global-search.php
  packages/admin/resources/lang/pl/layout.php
  packages/admin/resources/lang/pl/login.php
  packages/admin/resources/lang/pl/pages/dashboard.php
  packages/admin/resources/lang/pl/resources/pages/create-record.php
  packages/admin/resources/lang/pl/resources/pages/edit-record.php
  packages/admin/resources/lang/pl/resources/pages/list-records.php
  packages/admin/resources/lang/pl/resources/pages/view-record.php
  packages/admin/resources/lang/pl/resources/relation-managers/attach.php
  packages/admin/resources/lang/pl/resources/relation-managers/create.php
  packages/admin/resources/lang/pl/resources/relation-managers/delete.php
  packages/admin/resources/lang/pl/resources/relation-managers/detach.php
  packages/admin/resources/lang/pl/resources/relation-managers/edit.php
  packages/admin/resources/lang/pl/widgets/account-widget.php
  packages/admin/resources/lang/pl/widgets/filament-info-widget.php
  packages/forms/resources/lang/pl/components.php
  packages/tables/resources/lang/pl/table.php
Labels: enhancement, i18n

#819 Document the createItemButtonLabel() function
  packages/forms/docs/03-fields.md
Labels: documentation, enhancement

#828 feature: HasManyRepeater
  packages/forms/docs/03-fields.md
  packages/forms/src/Components/Builder.php
  packages/forms/src/Components/HasManyRepeater.php
  packages/forms/src/Components/MultipleFileUpload.php
  packages/forms/src/Components/Repeater.php
Labels: enhancement

#832 add Arabic translations
  packages/admin/resources/lang/ar/global-search.php
  packages/admin/resources/lang/ar/layout.php
  packages/admin/resources/lang/ar/login.php
  packages/admin/resources/lang/ar/pages/dashboard.php
  packages/admin/resources/lang/ar/resources/pages/create-record.php
  packages/admin/resources/lang/ar/resources/pages/edit-record.php
  packages/admin/resources/lang/ar/resources/pages/list-records.php
  packages/admin/resources/lang/ar/resources/pages/view-record.php
  packages/admin/resources/lang/ar/resources/relation-managers/attach.php
  packages/admin/resources/lang/ar/resources/relation-managers/create.php
  packages/admin/resources/lang/ar/resources/relation-managers/delete.php
  packages/admin/resources/lang/ar/resources/relation-managers/detach.php
  packages/admin/resources/lang/ar/resources/relation-managers/edit.php
  packages/admin/resources/lang/ar/widgets/account-widget.php
  packages/admin/resources/lang/ar/widgets/filament-info-widget.php
Labels: enhancement, i18n

#833 fix: Flipped KeyVal
  packages/admin/dist/app.css.map
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/admin/dist/module.esm.js
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/key-value.js
Labels: bug

#834 fix: Relationship query callback injection
  packages/forms/src/Components/BelongsToManyMultiSelect.php
  packages/forms/src/Components/BelongsToSelect.php
Labels: bug

#830 Fix the signed number mask
  packages/forms/src/Components/TextInput/Mask.php
Labels: bug

#836 feature: Key value placeholders
  packages/forms/docs/03-fields.md
  packages/forms/resources/views/components/key-value.blade.php
  packages/forms/src/Components/KeyValue.php
Labels: enhancement

#838 Simplified Chinese Translation
  packages/admin/resources/lang/zh_CN/global-search.php
  packages/admin/resources/lang/zh_CN/layout.php
  packages/admin/resources/lang/zh_CN/login.php
  packages/admin/resources/lang/zh_CN/pages/dashboard.php
  packages/admin/resources/lang/zh_CN/resources/pages/create-record.php
  packages/admin/resources/lang/zh_CN/resources/pages/edit-record.php
  packages/admin/resources/lang/zh_CN/resources/pages/list-records.php
  packages/admin/resources/lang/zh_CN/resources/pages/view-record.php
  packages/admin/resources/lang/zh_CN/resources/relation-managers/attach.php
  packages/admin/resources/lang/zh_CN/resources/relation-managers/create.php
  packages/admin/resources/lang/zh_CN/resources/relation-managers/delete.php
  packages/admin/resources/lang/zh_CN/resources/relation-managers/detach.php
  packages/admin/resources/lang/zh_CN/resources/relation-managers/edit.php
  packages/admin/resources/lang/zh_CN/widgets/account-widget.php
  packages/admin/resources/lang/zh_CN/widgets/filament-info-widget.php
  packages/tables/resources/lang/zh_CN/table.php
Labels: enhancement, i18n

#839 Dutch translations
  packages/admin/resources/lang/nl/global-search.php
  packages/admin/resources/lang/nl/layout.php
  packages/admin/resources/lang/nl/login.php
  packages/admin/resources/lang/nl/pages/dashboard.php
  packages/admin/resources/lang/nl/resources/pages/create-record.php
  packages/admin/resources/lang/nl/resources/pages/edit-record.php
  packages/admin/resources/lang/nl/resources/pages/list-records.php
  packages/admin/resources/lang/nl/resources/pages/view-record.php
  packages/admin/resources/lang/nl/resources/relation-managers/attach.php
  packages/admin/resources/lang/nl/resources/relation-managers/create.php
  packages/admin/resources/lang/nl/resources/relation-managers/delete.php
  packages/admin/resources/lang/nl/resources/relation-managers/detach.php
  packages/admin/resources/lang/nl/resources/relation-managers/edit.php
  packages/admin/resources/lang/nl/widgets/account-widget.php
  packages/admin/resources/lang/nl/widgets/filament-info-widget.php
Labels: enhancement, i18n

#818 Keep a consistent approach using locale in lang tag
  packages/forms/docs/01-installation.md
  packages/forms/stubs/scaffolding/resources/views/layouts/app.blade.php
  packages/tables/docs/01-installation.md
  packages/tables/stubs/scaffolding/resources/views/layouts/app.blade.php
Labels: enhancement

#855 feature: Dynamic form schemas
  packages/admin/src/Resources/Form.php
  packages/forms/src/ComponentContainer.php
  packages/forms/src/Components/Component.php
  packages/forms/src/Components/Concerns/EvaluatesClosures.php
  packages/forms/src/Components/Concerns/HasChildComponents.php
  packages/forms/src/Concerns/EvaluatesClosures.php
  packages/forms/src/Concerns/HasComponents.php
  tests/src/Forms/ComponentContainerTest.php
Labels: enhancement

#859 feature: Tags input suggestions
  packages/forms/docs/03-fields.md
  packages/forms/resources/views/components/tags-input.blade.php
  packages/forms/src/Components/TagsInput.php
  packages/spatie-laravel-tags-plugin/src/Forms/Components/SpatieTagsInput.php
Labels: enhancement

#858 Update german translations for tables
  packages/tables/resources/lang/de/table.php
Labels: enhancement, i18n

#861 Vietnamese translations
  packages/admin/resources/lang/vi/global-search.php
  packages/admin/resources/lang/vi/layout.php
  packages/admin/resources/lang/vi/login.php
  packages/admin/resources/lang/vi/pages/dashboard.php
  packages/admin/resources/lang/vi/resources/pages/create-record.php
  packages/admin/resources/lang/vi/resources/pages/edit-record.php
  packages/admin/resources/lang/vi/resources/pages/list-records.php
  packages/admin/resources/lang/vi/resources/pages/view-record.php
  packages/admin/resources/lang/vi/resources/relation-managers/attach.php
  packages/admin/resources/lang/vi/resources/relation-managers/create.php
  packages/admin/resources/lang/vi/resources/relation-managers/delete.php
  packages/admin/resources/lang/vi/resources/relation-managers/detach.php
  packages/admin/resources/lang/vi/resources/relation-managers/edit.php
  packages/admin/resources/lang/vi/widgets/account-widget.php
  packages/admin/resources/lang/vi/widgets/filament-info-widget.php
  packages/forms/resources/lang/vi/components.php
  packages/tables/resources/lang/vi/table.php
Labels: enhancement, i18n

#862 feature: Dynamically save relationships
  packages/forms/src/Components/BelongsToManyMultiSelect.php
  packages/forms/src/Components/BelongsToSelect.php
  packages/forms/src/Components/Concerns/BelongsToModel.php
  packages/forms/src/Components/HasManyRepeater.php
  packages/spatie-laravel-media-library-plugin/src/Forms/Components/SpatieMediaLibraryFileUpload.php
  packages/spatie-laravel-tags-plugin/src/Forms/Components/SpatieTagsInput.php
Labels: enhancement

#865 Update CanRequireConfirmation.php
  packages/tables/src/Actions/Concerns/CanRequireConfirmation.php
Labels: bug

#866 feature: Resource generation
  packages/admin/docs/02-resources.md
  packages/admin/src/Commands/Aliases/MakeResourceCommand.php
  packages/admin/src/Commands/Concerns/CanGenerateResources.php
  packages/admin/src/Commands/MakeResourceCommand.php
  packages/admin/stubs/Resource.stub
Labels: enhancement

#868 Badge column rendering issue fixed
  packages/tables/docs/03-columns.md
  packages/tables/resources/views/columns/badge-column.blade.php
Labels: bug

#878 enhance Arabic translation
  packages/admin/resources/lang/ar/resources/pages/edit-record.php
  packages/admin/resources/lang/ar/resources/relation-managers/create.php
  packages/spatie-laravel-translatable-plugin/resources/lang/ar/actions.php
  packages/spatie-laravel-translatable-plugin/resources/lang/en/actions.php
  packages/tables/resources/lang/ar/table.php
Labels: bug, enhancement, i18n

#879 chore: add openUrlInNewTab to docs
  packages/tables/docs/05-actions.md
Labels: documentation, enhancement

#881 HasManyRepeater component defaultItems issue fixed
  packages/forms/src/Components/HasManyRepeater.php
Labels: bug

#885 Add fully support for rtl languages
  packages/admin/dist/app.css
  packages/admin/dist/mix-manifest.json
  packages/admin/resources/views/components/layouts/app.blade.php
  packages/admin/resources/views/components/layouts/app/sidebar/index.blade.php
  packages/admin/resources/views/widgets/filament-info-widget.blade.php
  packages/forms/resources/views/components/field-wrapper/label.blade.php
  packages/tables/resources/views/components/filters/index.blade.php
  packages/tables/resources/views/components/header-cell.blade.php
  packages/tables/resources/views/components/pagination/item.blade.php
  packages/tables/resources/views/components/table.blade.php
Labels: bug, enhancement, ui

#886 fix some issues with rtl UI and enhancement Arabic translations
  packages/admin/dist/app.css
  packages/admin/dist/mix-manifest.json
  packages/admin/resources/lang/ar/resources/pages/list-records.php
  packages/admin/resources/lang/ar/resources/relation-managers/create.php
  packages/admin/resources/lang/ar/resources/relation-managers/delete.php
  packages/admin/resources/lang/ar/resources/relation-managers/detach.php
  packages/admin/resources/views/components/button.blade.php
  packages/forms/resources/lang/ar/components.php
  packages/tables/resources/lang/ar/table.php
  packages/tables/resources/views/components/button.blade.php
  packages/tables/resources/views/components/dropdown/item.blade.php
Labels: ui, i18n

#890 fix: Placeholder field state callback loop
  packages/forms/src/Components/Concerns/EvaluatesClosures.php
  packages/forms/src/Components/Placeholder.php
  packages/forms/src/Concerns/EvaluatesClosures.php
Labels: bug

#857 Brazilian portuguese translations
  packages/admin/resources/lang/pt_BR/global-search.php
  packages/admin/resources/lang/pt_BR/layout.php
  packages/admin/resources/lang/pt_BR/login.php
  packages/admin/resources/lang/pt_BR/pages/dashboard.php
  packages/admin/resources/lang/pt_BR/resources/pages/create-record.php
  packages/admin/resources/lang/pt_BR/resources/pages/edit-record.php
  packages/admin/resources/lang/pt_BR/resources/pages/list-records.php
  packages/admin/resources/lang/pt_BR/resources/pages/view-record.php
  packages/admin/resources/lang/pt_BR/resources/relation-managers/attach.php
  packages/admin/resources/lang/pt_BR/resources/relation-managers/create.php
  packages/admin/resources/lang/pt_BR/resources/relation-managers/delete.php
  packages/admin/resources/lang/pt_BR/resources/relation-managers/detach.php
  packages/admin/resources/lang/pt_BR/resources/relation-managers/edit.php
  packages/admin/resources/lang/pt_BR/widgets/account-widget.php
  packages/admin/resources/lang/pt_BR/widgets/filament-info-widget.php
Labels: enhancement, i18n

#817 Use slug syntax for dayjs locale files
  packages/forms/resources/views/components/date-time-picker.blade.php
Labels: bug

#809 Bootstraps filament/spatie-laravel-settings-plugin settings creations
  packages/spatie-laravel-settings-plugin/docs/02-getting-started.md
Labels: enhancement

#909 feature: set mountedTableActionRecord
  packages/admin/src/Resources/RelationManagers/Concerns/CanCreateRecords.php
Labels: enhancement

#897 Tailwind config docs update for admin
  packages/admin/docs/07-appearance.md
  packages/admin/tailwind.config.js
  packages/forms/docs/01-installation.md
  packages/forms/stubs/scaffolding/tailwind.config.js
  packages/tables/docs/01-installation.md
  packages/tables/stubs/scaffolding/tailwind.config.js
Labels: documentation, enhancement

#884 Add selected records indicator
  packages/admin/dist/app.css.map
  packages/tables/resources/lang/ar/table.php
  packages/tables/resources/lang/ca/table.php
  packages/tables/resources/lang/da/table.php
  packages/tables/resources/lang/de/table.php
  packages/tables/resources/lang/en/table.php
  packages/tables/resources/lang/es/table.php
  packages/tables/resources/lang/fa/table.php
  packages/tables/resources/lang/fr/table.php
  packages/tables/resources/lang/id/table.php
  packages/tables/resources/lang/it/table.php
  packages/tables/resources/lang/ka/table.php
  packages/tables/resources/lang/ku/table.php
  packages/tables/resources/lang/nl/table.php
  packages/tables/resources/lang/pl/table.php
  packages/tables/resources/lang/pt_BR/table.php
  packages/tables/resources/lang/ru/table.php
  packages/tables/resources/lang/sv/table.php
  packages/tables/resources/lang/vi/table.php
  packages/tables/resources/lang/zh_CN/table.php
  packages/tables/resources/views/components/bulk-actions/index.blade.php
  packages/tables/resources/views/components/selection-indicator.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Concerns/CanSelectRecords.php
  packages/tables/src/Contracts/HasTable.php
  packages/tables/src/Table.php
Labels: enhancement, pending changes

#914 fix: Spatie tags custom suggestions
  packages/forms/src/Components/TagsInput.php
  packages/spatie-laravel-tags-plugin/src/Forms/Components/SpatieTagsInput.php
Labels: bug

#915 [1.x] fix: User resource password confirmation
  src/Resources/UserResource.php
Labels: bug

#928 fix: Table action modal clashes
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Concerns/HasActions.php
  packages/tables/src/Concerns/HasBulkActions.php
Labels: bug

#929 [2.x] GitHub Workflow for `npm build`
  .github/workflows/npm-build.yml
Labels: enhancement

#927 Not working when used other directory structure
  packages/admin/config/filament.php
  packages/admin/src/FilamentServiceProvider.php
Labels: enhancement

#932 fix: Date picker infinite loop
  packages/admin/dist/app.css.map
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/admin/dist/module.esm.js
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/date-time-picker.js
Labels: bug

#934 feature: Translatable page titles
  packages/admin/resources/lang/en/login.php
  packages/admin/resources/lang/en/resources/pages/create-record.php
  packages/admin/src/Http/Livewire/Auth/Login.php
  packages/admin/src/Resources/Pages/CreateRecord.php
  packages/admin/src/Resources/Pages/EditRecord.php
  packages/admin/src/Resources/Pages/ViewRecord.php
Labels: enhancement

#935 Enhanced extra attributes
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/builder/block.blade.php
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/resources/views/components/file-upload.blade.php
  packages/forms/resources/views/components/file-upload/input.blade.php
  packages/forms/resources/views/components/key-value.blade.php
  packages/forms/resources/views/components/markdown-editor.blade.php
  packages/forms/resources/views/components/multi-select.blade.php
  packages/forms/resources/views/components/multiple-file-upload.blade.php
  packages/forms/resources/views/components/placeholder.blade.php
  packages/forms/resources/views/components/radio.blade.php
  packages/forms/resources/views/components/repeater.blade.php
  packages/forms/resources/views/components/rich-editor.blade.php
  packages/forms/resources/views/components/section.blade.php
  packages/forms/resources/views/components/select.blade.php
  packages/forms/resources/views/components/tabs.blade.php
  packages/forms/resources/views/components/tabs/tab.blade.php
  packages/forms/resources/views/components/tags-input.blade.php
  packages/forms/resources/views/components/text-input.blade.php
  packages/forms/resources/views/components/textarea.blade.php
  packages/forms/resources/views/components/toggle.blade.php
  packages/forms/src/Components/Concerns/HasExtraAlpineAttributes.php
  packages/forms/src/Components/DateTimePicker.php
  packages/forms/src/Components/FileUpload.php
  packages/forms/src/Components/KeyValue.php
  packages/forms/src/Components/MarkdownEditor.php
  packages/forms/src/Components/MultiSelect.php
  packages/forms/src/Components/RichEditor.php
  packages/forms/src/Components/Section.php
  packages/forms/src/Components/Select.php
  packages/forms/src/Components/Tabs.php
  packages/forms/src/Components/TagsInput.php
  packages/forms/src/Components/TextInput.php
  packages/forms/src/Components/Textarea.php
  packages/forms/src/Components/Toggle.php
Labels: enhancement

#937 feature: Tags column
  packages/spatie-laravel-tags-plugin/docs/01-installation.md
  packages/spatie-laravel-tags-plugin/docs/03-table-columns.md
  packages/spatie-laravel-tags-plugin/src/Tables/Columns/SpatieTagsColumn.php
  packages/tables/docs/03-columns.md
  packages/tables/resources/views/columns/tags-column.blade.php
  packages/tables/src/Columns/TagsColumn.php
Labels: enhancement

#939 fix: Vapor migrate
  packages/admin/src/FilamentServiceProvider.php
Labels: bug

#943 Add czech lang
  packages/admin/resources/lang/cs/global-search.php
  packages/admin/resources/lang/cs/layout.php
  packages/admin/resources/lang/cs/login.php
  packages/admin/resources/lang/cs/pages/dashboard.php
  packages/admin/resources/lang/cs/resources/pages/create-record.php
  packages/admin/resources/lang/cs/resources/pages/edit-record.php
  packages/admin/resources/lang/cs/resources/pages/list-records.php
  packages/admin/resources/lang/cs/resources/pages/view-record.php
  packages/admin/resources/lang/cs/resources/relation-managers/attach.php
  packages/admin/resources/lang/cs/resources/relation-managers/create.php
  packages/admin/resources/lang/cs/resources/relation-managers/delete.php
  packages/admin/resources/lang/cs/resources/relation-managers/detach.php
  packages/admin/resources/lang/cs/resources/relation-managers/edit.php
  packages/admin/resources/lang/cs/widgets/account-widget.php
  packages/admin/resources/lang/cs/widgets/filament-info-widget.php
  packages/forms/resources/lang/cs/components.php
  packages/tables/resources/lang/cs/table.php
Labels: enhancement, i18n

#944 Translation files to French added
  packages/admin/resources/lang/fr/global-search.php
  packages/admin/resources/lang/fr/layout.php
  packages/admin/resources/lang/fr/login.php
  packages/admin/resources/lang/fr/pages/dashboard.php
  packages/admin/resources/lang/fr/resources/pages/create-record.php
  packages/admin/resources/lang/fr/resources/pages/edit-record.php
  packages/admin/resources/lang/fr/resources/pages/list-records.php
  packages/admin/resources/lang/fr/resources/pages/view-record.php
  packages/admin/resources/lang/fr/resources/relation-managers/attach.php
  packages/admin/resources/lang/fr/resources/relation-managers/create.php
  packages/admin/resources/lang/fr/resources/relation-managers/delete.php
  packages/admin/resources/lang/fr/resources/relation-managers/detach.php
  packages/admin/resources/lang/fr/resources/relation-managers/edit.php
  packages/admin/resources/lang/fr/widgets/account-widget.php
  packages/admin/resources/lang/fr/widgets/filament-info-widget.php
Labels: enhancement, i18n

#949 fix select input loading spinner display
  packages/forms/resources/views/components/multi-select.blade.php
  packages/forms/resources/views/components/select.blade.php
Labels: bug, ui

#954 fix: Escape select placeholder quotes
  packages/forms/resources/views/components/select.blade.php
Labels: bug

#961 Minor RTL enhancements
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/mix-manifest.json
  packages/admin/resources/css/app.css
  packages/admin/resources/views/components/layouts/app.blade.php
Labels: bug, enhancement, ui, i18n

#957 Adds Filtering ability to chart widgets
  packages/admin/docs/04-dashboard.md
  packages/admin/resources/views/widgets/chart-widget.blade.php
  packages/admin/src/Widgets/ChartWidget.php
Labels: enhancement

#970 fix: Repeater evaluation negation
  packages/forms/src/Components/Concerns/CanBeHidden.php
  packages/forms/src/Components/DateTimePicker.php
  packages/forms/src/Components/KeyValue.php
  packages/forms/src/Concerns/Cloneable.php
Labels: bug

#974 fix: Dashboard navigation label
  packages/admin/src/Pages/Dashboard.php
Labels: bug, ui, i18n

#978 disable autocomplete in global search and table search inputs
  packages/admin/resources/views/components/global-search/input.blade.php
  packages/tables/resources/views/components/search-input.blade.php
Labels: bug

#983 Fix syntax error in toggle field example
  packages/forms/docs/03-fields.md
Labels: bug, documentation

#986 Update simplified Chinese translation files
  packages/admin/resources/lang/zh_CN/login.php
  packages/admin/resources/lang/zh_CN/resources/pages/create-record.php
  packages/forms/resources/lang/zh_CN/components.php
  packages/spatie-laravel-translatable-plugin/resources/lang/zh_CN/actions.php
Labels: enhancement, i18n

#989 fix: Markdown editor uploads
  packages/forms/resources/views/components/markdown-editor.blade.php
Labels: bug

#990 feature: Evaluate table closures
  packages/admin/dist/app.css.map
  packages/tables/src/Actions/Action.php
  packages/tables/src/Actions/BulkAction.php
  packages/tables/src/Actions/Concerns/EvaluatesClosures.php
  packages/tables/src/Columns/Column.php
  packages/tables/src/Columns/Concerns/CanBeHidden.php
  packages/tables/src/Columns/Concerns/EvaluatesClosures.php
  packages/tables/src/Filters/Concerns/EvaluatesClosures.php
  packages/tables/src/Filters/Filter.php
Labels: enhancement

#992 Translation files to Khmer added
  packages/admin/resources/lang/kh/global-search.php
  packages/admin/resources/lang/kh/layout.php
  packages/admin/resources/lang/kh/login.php
  packages/admin/resources/lang/kh/pages/dashboard.php
  packages/admin/resources/lang/kh/resources/pages/create-record.php
  packages/admin/resources/lang/kh/resources/pages/edit-record.php
  packages/admin/resources/lang/kh/resources/pages/list-records.php
  packages/admin/resources/lang/kh/resources/pages/view-record.php
  packages/admin/resources/lang/kh/resources/relation-managers/attach.php
  packages/admin/resources/lang/kh/resources/relation-managers/create.php
  packages/admin/resources/lang/kh/resources/relation-managers/delete.php
  packages/admin/resources/lang/kh/resources/relation-managers/detach.php
  packages/admin/resources/lang/kh/resources/relation-managers/edit.php
  packages/admin/resources/lang/kh/widgets/account-widget.php
  packages/admin/resources/lang/kh/widgets/filament-info-widget.php
Labels: enhancement, i18n

#998 chore: remove transition class
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/admin/resources/views/components/actions/select-action.blade.php
  packages/admin/resources/views/components/button.blade.php
  packages/admin/resources/views/components/global-search/input.blade.php
  packages/admin/resources/views/components/global-search/result.blade.php
  packages/admin/resources/views/components/layouts/app.blade.php
  packages/admin/resources/views/components/layouts/app/sidebar/footer.blade.php
  packages/admin/resources/views/components/layouts/app/sidebar/index.blade.php
  packages/admin/resources/views/components/modal/index.blade.php
  packages/admin/resources/views/components/resources/relation-managers/index.blade.php
  packages/admin/resources/views/components/tabs/item.blade.php
  packages/admin/resources/views/widgets/account-widget.blade.php
  packages/admin/resources/views/widgets/chart-widget.blade.php
  packages/admin/resources/views/widgets/filament-info-widget.blade.php
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/checkbox.blade.php
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/resources/views/components/markdown-editor.blade.php
  packages/forms/resources/views/components/markdown-editor/toolbar-button.blade.php
  packages/forms/resources/views/components/multi-select.blade.php
  packages/forms/resources/views/components/repeater.blade.php
  packages/forms/resources/views/components/rich-editor.blade.php
  packages/forms/resources/views/components/section.blade.php
  packages/forms/resources/views/components/select.blade.php
  packages/forms/resources/views/components/tags-input.blade.php
  packages/forms/resources/views/components/text-input.blade.php
  packages/forms/resources/views/components/textarea.blade.php
  packages/forms/resources/views/components/toggle.blade.php
  packages/tables/resources/views/components/button.blade.php
  packages/tables/resources/views/components/filters/index.blade.php
  packages/tables/resources/views/components/icon-button.blade.php
  packages/tables/resources/views/components/link.blade.php
  packages/tables/resources/views/components/modal/index.blade.php
  packages/tables/resources/views/components/pagination/records-per-page-selector.blade.php
  packages/tables/resources/views/components/search-input.blade.php
Labels: ui, chore

#1002 feature: Override page form
  packages/admin/src/Resources/Pages/Concerns/UsesResourceForm.php
  packages/admin/src/Resources/Pages/ListRecords.php
Labels: enhancement

#995 feature: Integrated multiple file uploads
  packages/admin/dist/app.css.map
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/admin/dist/module.esm.js
  packages/admin/routes/web.php
  packages/admin/src/Resources/Pages/EditRecord.php
  packages/forms/dist/module.esm.js
  packages/forms/docs/03-fields.md
  packages/forms/docs/06-advanced.md
  packages/forms/resources/js/components/file-upload.js
  packages/forms/resources/js/components/multi-select.js
  packages/forms/resources/js/components/select.js
  packages/forms/resources/views/components/file-upload.blade.php
  packages/forms/resources/views/components/multiple-file-upload.blade.php
  packages/forms/src/Components/BaseFileUpload.php
  packages/forms/src/Components/Concerns/CanBeValidated.php
  packages/forms/src/Components/Concerns/CanLimitItemsLength.php
  packages/forms/src/Components/Concerns/HasFileAttachments.php
  packages/forms/src/Components/Concerns/HasState.php
  packages/forms/src/Components/Contracts/HasFileAttachments.php
  packages/forms/src/Components/DateTimePicker.php
  packages/forms/src/Components/MultipleFileUpload.php
  packages/forms/src/Concerns/InteractsWithForms.php
  packages/forms/src/Concerns/SupportsFileUploadFields.php
  packages/forms/src/Contracts/HasForms.php
  packages/spatie-laravel-media-library-plugin/docs/02-form-components.md
  packages/spatie-laravel-media-library-plugin/src/Forms/Components/SpatieMediaLibraryFileUpload.php
  packages/spatie-laravel-media-library-plugin/src/Forms/Components/SpatieMediaLibraryMultipleFileUpload.php
Labels: enhancement

#1008 fix: Repeater & builder keys
  packages/forms/src/Components/Builder.php
  packages/forms/src/Components/Concerns/HasState.php
  packages/forms/src/Components/HasManyRepeater.php
  packages/forms/src/Components/MultiSelect.php
  packages/forms/src/Components/Repeater.php
  packages/forms/src/Components/TagsInput.php
  packages/forms/src/Concerns/Cloneable.php
  packages/forms/src/Concerns/HasComponents.php
  packages/forms/src/Concerns/HasState.php
  tests/src/Forms/StateTest.php
Labels: bug

#1013 [AR] Translate missing phrases + Fix Typo
  packages/admin/resources/lang/ar/login.php
  packages/admin/resources/lang/ar/resources/pages/create-record.php
  packages/admin/resources/lang/ar/resources/pages/edit-record.php
  packages/admin/resources/lang/ar/resources/pages/list-records.php
  packages/admin/resources/lang/ar/resources/relation-managers/attach.php
  packages/admin/resources/lang/ar/resources/relation-managers/create.php
  packages/forms/resources/lang/ar/components.php
  packages/tables/resources/lang/ar/table.php
Labels: bug, enhancement, i18n

#1015 fix: Nullable repeater & builder initial state
  packages/forms/src/Components/Builder.php
  packages/forms/src/Components/Repeater.php
Labels: bug

#1024 FileUpload - Delete tmp file on revert and save
  packages/forms/src/Components/BaseFileUpload.php
Labels: enhancement

#1025 fix: Repeater 0 default items
  packages/forms/src/Components/Repeater.php
Labels: bug

#1028 Added Kurdish locale
  packages/admin/resources/lang/ku/global-search.php
  packages/admin/resources/lang/ku/layout.php
  packages/admin/resources/lang/ku/login.php
  packages/admin/resources/lang/ku/pages/dashboard.php
  packages/admin/resources/lang/ku/resources/pages/create-record.php
  packages/admin/resources/lang/ku/resources/pages/edit-record.php
  packages/admin/resources/lang/ku/resources/pages/list-records.php
  packages/admin/resources/lang/ku/resources/pages/view-record.php
  packages/admin/resources/lang/ku/resources/relation-managers/attach.php
  packages/admin/resources/lang/ku/resources/relation-managers/create.php
  packages/admin/resources/lang/ku/resources/relation-managers/delete.php
  packages/admin/resources/lang/ku/resources/relation-managers/detach.php
  packages/admin/resources/lang/ku/resources/relation-managers/edit.php
  packages/admin/resources/lang/ku/widgets/account-widget.php
  packages/admin/resources/lang/ku/widgets/filament-info-widget.php
Labels: enhancement, i18n

#1033 Minor fix on RTL layout
  packages/admin/resources/views/components/layouts/app/sidebar/index.blade.php
  packages/admin/resources/views/widgets/filament-info-widget.blade.php
  packages/forms/resources/views/components/multi-select.blade.php
Labels: bug, ui

#1038 FileUpload - Check state on save
  packages/forms/src/Components/BaseFileUpload.php
Labels: bug

#1039 feature: Merge extra input attributes
  packages/forms/resources/views/components/checkbox.blade.php
  packages/forms/resources/views/components/file-upload.blade.php
  packages/forms/resources/views/components/radio.blade.php
  packages/forms/resources/views/components/tags-input.blade.php
  packages/forms/resources/views/components/text-input.blade.php
  packages/forms/resources/views/components/textarea.blade.php
  packages/forms/src/Components/Checkbox.php
  packages/forms/src/Components/Concerns/HasExtraInputAttributes.php
  packages/forms/src/Components/FileUpload.php
  packages/forms/src/Components/Radio.php
  packages/forms/src/Components/TagsInput.php
  packages/forms/src/Components/TextInput.php
  packages/forms/src/Components/Textarea.php
Labels: enhancement

#1031 feature: Builder component: ability to disable add / delete button [Forms]
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/builder/block-picker.blade.php
  packages/forms/resources/views/components/repeater.blade.php
  packages/forms/src/Components/Builder.php
  packages/forms/src/Components/Repeater.php
Labels: enhancement

#1041 Set default locale when all translatable fields are blank
  packages/spatie-laravel-translatable-plugin/src/Resources/Pages/EditRecord/Concerns/Translatable.php
Labels: bug

#1042 feature: Table count columns
  packages/tables/docs/03-columns.md
  packages/tables/src/Columns/Column.php
  packages/tables/src/Columns/Concerns/CanCountRelatedModels.php
  packages/tables/src/Columns/Concerns/InteractsWithTableQuery.php
  packages/tables/src/Concerns/HasRecords.php
Labels: enhancement

#1058 Update plugin.md
  packages/admin/docs/08-plugins.md
Labels: bug, documentation

#1061 fix: Fill new repeater and builder items with defaults
  packages/forms/src/Components/Builder.php
  packages/forms/src/Components/Repeater.php
Labels: bug

#1062 feature: Overwrite mask option
  packages/forms/src/Components/TextInput/Mask.php
Labels: enhancement

#1063 fix: Set uploaded file to array
  packages/forms/src/Components/BaseFileUpload.php
Labels: bug

#1064 fix: Update key value after remote state change
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/admin/dist/module.esm.js
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/key-value.js
  packages/forms/resources/views/components/key-value.blade.php
  packages/forms/src/Components/KeyValue.php
Labels: bug

#1065 feature: Disable placeholder selection
  packages/forms/docs/03-fields.md
  packages/forms/resources/views/components/select.blade.php
  packages/forms/src/Components/Select.php
Labels: enhancement

#1060 Possible hide of the select placeholder option
  packages/forms/docs/03-fields.md
  packages/forms/resources/views/components/select.blade.php
  packages/forms/src/Components/Select.php
Labels: enhancement

#1066 fix: Only register existing views and translations directories
  packages/admin/src/PluginServiceProvider.php
Labels: bug

#1068 fix: Translate record title
  packages/spatie-laravel-translatable-plugin/src/Resources/Pages/Concerns/HasActiveFormLocaleSelect.php
Labels: bug

#1069 feature: Inline radio
  packages/forms/docs/03-fields.md
  packages/forms/resources/views/components/field-wrapper/index.blade.php
  packages/forms/resources/views/components/field-wrapper/label.blade.php
  packages/forms/resources/views/components/radio.blade.php
  packages/forms/src/Components/Radio.php
Labels: enhancement

#1071 Add support for enum casts in PHP 8.1
  packages/tables/src/Columns/Concerns/HasState.php
Labels: enhancement

#1075 fixed some translations in Kurdish locale
  packages/admin/resources/lang/ku/resources/pages/create-record.php
  packages/admin/resources/lang/ku/resources/pages/list-records.php
Labels: bug, i18n

#1076 fix minor issue for sidebar on large screens `RTL` direction
  packages/admin/dist/app.css
  packages/admin/dist/mix-manifest.json
  packages/admin/resources/views/components/layouts/app/sidebar/index.blade.php
Labels: bug, ui

#1079 fix: Disabled key value
  packages/forms/resources/views/components/key-value.blade.php
Labels: bug

#1077 Fix toggle appearance on RTL layout
  packages/forms/resources/views/components/toggle.blade.php
Labels: bug, ui

#1081 feature: Register plugin config and relation managers
  packages/admin/src/PluginServiceProvider.php
Labels: enhancement

#1085 feature: Simple pagination
  packages/tables/resources/views/components/button.blade.php
  packages/tables/resources/views/components/pagination/index.blade.php
  packages/tables/src/Concerns/CanPaginateRecords.php
  packages/tables/src/Concerns/HasRecords.php
  packages/tables/src/Table.php
Labels: enhancement

#1084 Russian translation files added
  packages/admin/resources/lang/ru/global-search.php
  packages/admin/resources/lang/ru/layout.php
  packages/admin/resources/lang/ru/login.php
  packages/admin/resources/lang/ru/pages/dashboard.php
  packages/admin/resources/lang/ru/resources/pages/create-record.php
  packages/admin/resources/lang/ru/resources/pages/edit-record.php
  packages/admin/resources/lang/ru/resources/pages/list-records.php
  packages/admin/resources/lang/ru/resources/pages/view-record.php
  packages/admin/resources/lang/ru/resources/relation-managers/attach.php
  packages/admin/resources/lang/ru/resources/relation-managers/create.php
  packages/admin/resources/lang/ru/resources/relation-managers/delete.php
  packages/admin/resources/lang/ru/resources/relation-managers/detach.php
  packages/admin/resources/lang/ru/resources/relation-managers/edit.php
  packages/admin/resources/lang/ru/widgets/account-widget.php
  packages/admin/resources/lang/ru/widgets/filament-info-widget.php
Labels: enhancement, i18n
