Repository filamentphp/filament, pull requests merged in 2022-12, with the labels that each got.

#5115 Remove unnecessary use directive
  packages/spatie-laravel-media-library-plugin/src/Forms/Components/SpatieMediaLibraryFileUpload.php
Labels: code quality

#5122 Add Latvian translations for admin panel and tables
  packages/admin/resources/lang/lv/global-search.php
  packages/admin/resources/lang/lv/layout.php
  packages/admin/resources/lang/lv/login.php
  packages/admin/resources/lang/lv/pages/dashboard.php
  packages/admin/resources/lang/lv/resources/pages/create-record.php
  packages/admin/resources/lang/lv/resources/pages/edit-record.php
  packages/admin/resources/lang/lv/resources/pages/list-records.php
  packages/admin/resources/lang/lv/resources/pages/view-record.php
  packages/admin/resources/lang/lv/widgets/account-widget.php
  packages/admin/resources/lang/lv/widgets/filament-info-widget.php
  packages/support/resources/lang/lv/actions/edit.php
  packages/tables/resources/lang/lv/table.php
Labels: i18n

#5021 feat: Add class for table-cell name
  packages/tables/resources/views/index.blade.php
Labels: enhancement

#5124 Update default font
  packages/app/src/Context.php
Labels: ui

#5040 Support custom color and size
  packages/actions/resources/views/button-action.blade.php
  packages/actions/resources/views/link-action.blade.php
  packages/actions/resources/views/modal/actions/button-action.blade.php
  packages/actions/src/Concerns/HasIcon.php
  packages/app/dist/theme.css
  packages/app/resources/views/components/layouts/app/topbar/database-notifications-trigger.blade.php
  packages/app/resources/views/components/layouts/card.blade.php
  packages/forms/dist/components/date-time-picker.js
  packages/forms/dist/components/file-upload.js
  packages/forms/dist/index.css
  packages/forms/resources/views/component-container.blade.php
  packages/forms/resources/views/components/field-wrapper/hint.blade.php
  packages/forms/resources/views/components/toggle.blade.php
  packages/notifications/resources/views/components/icon.blade.php
  packages/notifications/src/Actions/Action.php
  packages/notifications/src/Actions/ActionGroup.php
  packages/notifications/src/Concerns/HasIcon.php
  packages/support/resources/views/components/button.blade.php
  packages/support/resources/views/components/dropdown/index.blade.php
  packages/support/resources/views/components/dropdown/list/item.blade.php
  packages/support/resources/views/components/icon-button.blade.php
  packages/support/resources/views/components/link.blade.php
  packages/tables/resources/views/columns/badge-column.blade.php
  packages/tables/resources/views/columns/icon-column.blade.php
  packages/tables/resources/views/columns/layout/stack.blade.php
  packages/tables/resources/views/columns/summaries/icon-count.blade.php
  packages/tables/resources/views/columns/text-column.blade.php
  packages/tables/resources/views/columns/text-input-column.blade.php
  packages/tables/resources/views/columns/toggle-column.blade.php
  packages/tables/resources/views/components/columns/column.blade.php
  packages/tables/resources/views/components/header-cell.blade.php
  packages/tables/src/Columns/Concerns/HasSpace.php
  packages/widgets/resources/views/stats-overview-widget/card.blade.php
Labels: enhancement

#5132 Feat: Add action color methods
  packages/support/src/Actions/Concerns/HasColor.php
Labels: enhancement

#5138 revert #5132 additional color functions
  packages/support/src/Actions/Concerns/HasColor.php
Labels: chore

#5130 Switch to Bunny Fonts Provider by default
  packages/app/src/Context.php
Labels: enhancement

#5087 Include aggregated summarized columns in filter query
  packages/tables/.stubs.php
  packages/tables/src/Concerns/HasRecords.php
Labels: bug

#5107 feat: formatStateUsing alias for form fields.
  packages/forms/src/Components/Concerns/HasState.php
Labels: enhancement

#5111 Make options structure more explicit
  packages/forms/docs/03-fields.md
Labels: documentation

#5108 Adding CanWrapHeader trait for columns
  packages/tables/resources/views/components/header-cell.blade.php
  packages/tables/resources/views/components/summary/index.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Columns/Column.php
  packages/tables/src/Columns/Concerns/CanWrapHeader.php
Labels: enhancement

#5113 Improved style handling for summary rows
  packages/tables/resources/views/columns/summaries/icon-count.blade.php
  packages/tables/resources/views/columns/summaries/range.blade.php
  packages/tables/resources/views/columns/summaries/text.blade.php
  packages/tables/resources/views/components/summary/index.blade.php
  packages/tables/resources/views/components/summary/row.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Columns/Summarizers/Summarizer.php
Labels: enhancement

#5165 Add icon alias to all icon buttons
  packages/actions/resources/views/group.blade.php
  packages/app/resources/views/components/layouts/app/topbar/database-notifications-trigger.blade.php
  packages/app/resources/views/pages/tenancy/register-tenant.blade.php
  packages/forms/resources/views/components/builder.blade.php
  packages/tables/resources/views/components/bulk-actions/trigger.blade.php
  packages/tables/resources/views/components/filters/trigger.blade.php
  packages/tables/resources/views/components/groups.blade.php
  packages/tables/resources/views/components/pagination/index.blade.php
  packages/tables/resources/views/components/reorder/trigger.blade.php
  packages/tables/resources/views/components/toggleable/trigger.blade.php
  packages/tables/resources/views/index.blade.php
Labels: enhancement

#5173 Fix admin docs plugins typo
  packages/admin/docs/09-plugins.md
Labels: documentation

#5172 Update section heading to accept Html
  packages/forms/src/Components/Section.php
Labels: enhancement

#5186 feature: Generate forms and tables
  packages/admin/src/Commands/Concerns/CanGenerateResources.php
  packages/admin/src/Commands/MakeResourceCommand.php
  packages/forms/src/Commands/Concerns/CanGenerateForms.php
  packages/forms/src/Commands/MakeFormCommand.php
  packages/forms/src/FormsServiceProvider.php
  packages/forms/stubs/CreateForm.stub
  packages/forms/stubs/EditForm.stub
  packages/forms/stubs/Form.stub
  packages/forms/stubs/FormView.stub
  packages/support/src/Commands/Concerns/CanReadModelSchemas.php
  packages/tables/src/Commands/Concerns/CanGenerateTables.php
  packages/tables/src/Commands/MakeTableCommand.php
  packages/tables/src/TablesServiceProvider.php
  packages/tables/stubs/Table.stub
  packages/tables/stubs/TableView.stub
Labels: enhancement

#5185 fix: Brand name wrapping when expanding sidebar
  packages/admin/resources/views/components/layouts/app/sidebar/index.blade.php
Labels: bug

#5191 Add trigger db notifications sent event to notification class
  packages/notifications/src/Notification.php
Labels: enhancement

#5193 Update 10-text-input.md
  packages/tables/docs/03-columns/10-text-input.md
Labels: documentation

#5216 Fix: Rich editor dialog styles
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/echo.js
  packages/admin/dist/echo.js.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.css
  packages/forms/dist/module.esm.js
  packages/forms/resources/css/components/rich-editor.css
Labels: bug

#5225 fix: disabled state dehydration with clashing state path
  packages/forms/src/Components/Concerns/HasState.php
Labels: bug

#5234 Fix: Replace deprecated ${...} syntax in TestsForms.php
  packages/forms/src/Testing/TestsForms.php
Labels: bug

#5232 stats overview card: add description icon position
  packages/admin/resources/views/components/stats/card.blade.php
  packages/admin/resources/views/widgets/stats-overview-widget/card.blade.php
  packages/admin/src/Widgets/StatsOverviewWidget/Card.php
Labels: enhancement

#5236 Fix assets issue
  packages/support/src/Assets/AssetManager.php
Labels: bug

#5241 Fix: Set component inside getAction for repeatable fields
  packages/forms/src/Components/Concerns/HasActions.php
Labels: bug

#5248 Fix two typos in LT translations
  packages/forms/resources/lang/lt/components.php
Labels: i18n

#5239 Rework Alpine assets
  bin/build.js
  package-lock.json
  package.json
  packages/actions/docs/01-installation.md
  packages/app/dist/echo.js
  packages/app/dist/index.js
  packages/app/dist/theme.css
  packages/app/resources/js/index.js
  packages/app/resources/views/components/layouts/base.blade.php
  packages/forms/dist/components/date-time-picker.js
  packages/forms/dist/components/file-upload.js
  packages/forms/dist/components/markdown-editor.js
  packages/forms/dist/components/select.js
  packages/forms/docs/01-installation.md
  packages/forms/src/FormsServiceProvider.php
  packages/notifications/docs/01-installation.md
  packages/support/dist/async-alpine.js
  packages/support/dist/index.js
  packages/support/resources/js/async-alpine.js
  packages/support/resources/js/index.js
  packages/support/src/SupportServiceProvider.php
  packages/support/stubs/scaffolding/resources/views/layouts/app.blade.php
  packages/tables/dist/index.js
  packages/tables/docs/01-installation.md
  packages/tables/resources/js/index.js
  packages/tables/src/TablesServiceProvider.php
  packages/widgets/docs/01-installation.md
Labels: chore

#5223 fix searchable query doesn't handle or when is not first searchable
  packages/tables/src/Columns/Concerns/InteractsWithTableQuery.php
Labels: bug

#5114 Update MakeUserCommand to make it inline fillable
  packages/admin/src/Commands/MakeUserCommand.php
  packages/support/src/Commands/Concerns/CanValidateInput.php
Labels: enhancement

#5126 Fix bug, bulk toggleable CheckboxList, with dynamic options
  packages/forms/resources/views/components/checkbox-list.blade.php
Labels: bug

#5242 Move uploaded file if disk remote matches
  packages/forms/src/Components/BaseFileUpload.php
Labels: enhancement

#5174 Exclude rows from bulk selection
  packages/tables/docs/05-actions.md
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Concerns/CanSelectRecords.php
  packages/tables/src/Concerns/HasBulkActions.php
  packages/tables/src/Table.php
Labels: enhancement

#5252 Feat: Add conditional to trigger modal visibility on actions.
  packages/admin/docs/03-pages/02-actions.md
  packages/support/src/Actions/Concerns/CanOpenModal.php
Labels: enhancement

#5266 Improve description icon position code
  packages/admin/resources/views/components/stats/card.blade.php
Labels: code quality

#5274 Update 10-testing.md
  packages/admin/docs/10-testing.md
Labels: documentation

#5278 Fix: Global search hidden action
  packages/admin/resources/views/components/global-search/actions/index.blade.php
Labels: bug

#5283 Add Exif Orientation Plugin settings
  packages/forms/resources/js/components/file-upload.js
  packages/forms/resources/views/components/file-upload.blade.php
  packages/forms/src/Components/FileUpload.php
Labels: enhancement

#5277 Add Closure type to the Tabs::tabs method parameter
  packages/forms/src/Components/Tabs.php
Labels: enhancement

#5294 Updated GH workflows for PHP 8.2 support
  .github/workflows/phpstan.yml
  .github/workflows/tests.yml
Labels: code quality

#5295 fix: only try to render active manager if visible
  packages/admin/resources/views/components/resources/relation-managers/index.blade.php
Labels: bug

#5300 Fix Repeater clone button hit collapsible event (bubbling effect from header)
  packages/forms/resources/views/components/repeater.blade.php
Labels: bug

#5315 Feature / Tabs Component - Active tab in browser's query string
  packages/forms/resources/views/components/tabs.blade.php
  packages/forms/src/Components/Tabs.php
Labels: enhancement

#5296 Add tooltip documentation to `TextColumn` field
  packages/tables/docs/03-columns/02-text.md
Labels: documentation

#5354 tweak sidebar and breadcrumbs
  packages/app/dist/echo.js
  packages/app/dist/theme.css
  packages/app/resources/views/components/layouts/app/sidebar/badge.blade.php
  packages/app/resources/views/components/layouts/app/sidebar/group.blade.php
  packages/app/resources/views/components/layouts/app/sidebar/index.blade.php
  packages/app/resources/views/components/layouts/app/topbar/breadcrumbs.blade.php
  packages/app/src/Context.php
  packages/forms/dist/components/date-time-picker.js
  packages/forms/dist/components/file-upload.js
  packages/forms/dist/components/markdown-editor.js
  packages/forms/dist/components/select.js
Labels: enhancement

#5299 Fix pre-collapsed nav group feature
  packages/admin/resources/js/app.js
  packages/admin/resources/views/components/layouts/app/sidebar/index.blade.php
Labels: bug

#4990 feat: Add saveStateUsing() method for editable columns
  packages/tables/resources/views/columns/checkbox-column.blade.php
  packages/tables/resources/views/columns/select-column.blade.php
  packages/tables/resources/views/columns/text-input-column.blade.php
  packages/tables/resources/views/columns/toggle-column.blade.php
  packages/tables/src/Columns/CheckboxColumn.php
  packages/tables/src/Columns/Concerns/CanUpdateState.php
  packages/tables/src/Columns/Contracts/Editable.php
  packages/tables/src/Columns/SelectColumn.php
  packages/tables/src/Columns/TextInputColumn.php
  packages/tables/src/Columns/ToggleColumn.php
  packages/tables/src/Concerns/HasColumns.php
Labels: enhancement

#5083 Rules for each item in array fields
  packages/forms/resources/views/components/field-wrapper/index.blade.php
  packages/forms/resources/views/components/field-wrapper/inline.blade.php
  packages/forms/src/Components/CheckboxList.php
  packages/forms/src/Components/Concerns/CanBeValidated.php
  packages/forms/src/Components/Concerns/HasNestedRecursiveValidationRules.php
  packages/forms/src/Components/Contracts/HasNestedRecursiveValidationRules.php
  packages/forms/src/Components/Select.php
  packages/forms/src/Components/TagsInput.php
Labels: enhancement

#5370 Fix: `AssociateAction` for `MorphMany`
  packages/tables/src/Actions/AssociateAction.php
Labels: bug

#5329 Feature: Page Actions renderHooks
  packages/admin/docs/08-appearance.md
  packages/admin/resources/views/components/pages/actions/index.blade.php
Labels: enhancement

#5343 fix: Lowercase search column to allow searches inside json columns when attaching
  packages/admin/src/Resources/Resource.php
  packages/tables/src/Actions/AssociateAction.php
  packages/tables/src/Actions/AttachAction.php
Labels: bug

#5208 Set side of bulk actions
  packages/admin/docs/02-resources/02-listing-records.md
  packages/admin/src/Resources/Pages/ListRecords.php
  packages/admin/src/Resources/RelationManagers/RelationManager.php
  packages/admin/src/Resources/Table.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Actions/Position.php
  packages/tables/src/Actions/RecordCheckboxPosition.php
  packages/tables/src/Concerns/CanSelectRecords.php
  packages/tables/src/Contracts/HasTable.php
  packages/tables/src/Table.php
Labels: enhancement
