Repository filamentphp/filament, pull requests merged in 2022-01, with the labels that each got.

#1090 Fixed button ui issue
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/mix-manifest.json
  packages/admin/resources/views/components/button.blade.php
Labels: bug, ui

#1092 Update action in pages docs
  packages/admin/docs/03-pages.md
Labels: bug, documentation

#1094 fix: Initially hidden repeater
  packages/forms/src/Components/Concerns/HasChildComponents.php
Labels: bug

#1096 fix issue in datatime picker component with `RTL` direction
  packages/forms/resources/views/components/date-time-picker.blade.php
Labels: bug, ui

#1101 fix: Select search results
  packages/forms/resources/views/components/multi-select.blade.php
  packages/forms/resources/views/components/select.blade.php
Labels: bug

#1104 fix: Has many repeater delete multiple
  packages/forms/src/Components/HasManyRepeater.php
Labels: bug

#1105 feature: Reset table filters
  packages/tables/resources/lang/en/table.php
  packages/tables/resources/views/components/filters/index.blade.php
  packages/tables/src/Concerns/HasFilters.php
Labels: enhancement

#1108 [RU] Translations for tables and forms
  packages/forms/resources/lang/ru/components.php
  packages/tables/resources/lang/ru/table.php
Labels: enhancement, i18n

#1109 Fixed typo in Query string section
  packages/tables/docs/02-getting-started.md
Labels: documentation

#1110 feature: Access record inside resource widget
  packages/admin/docs/02-resources.md
  packages/admin/resources/views/components/page.blade.php
  packages/admin/resources/views/resources/pages/edit-record.blade.php
  packages/admin/resources/views/resources/pages/view-record.blade.php
  tests/src/Forms/StateTest.php
Labels: enhancement

#1112 fix: Cast checkbox list and multiselect state to array
  packages/forms/src/Components/CheckboxList.php
  packages/forms/src/Components/MultiSelect.php
Labels: bug

#1113 fix: Duplicate key value keys removed while typing
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/admin/dist/module.esm.js
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/key-value.js
Labels: bug

#1114 fix: Deselect belongs to many checkbox list string casting
  packages/forms/src/Components/BelongsToManyCheckboxList.php
Labels: bug

#1116 DRAFT: German translation
  packages/admin/resources/lang/de/global-search.php
  packages/admin/resources/lang/de/layout.php
  packages/admin/resources/lang/de/login.php
  packages/admin/resources/lang/de/pages/dashboard.php
  packages/admin/resources/lang/de/resources/pages/create-record.php
  packages/admin/resources/lang/de/resources/pages/edit-record.php
  packages/admin/resources/lang/de/resources/pages/list-records.php
  packages/admin/resources/lang/de/resources/pages/view-record.php
  packages/admin/resources/lang/de/resources/relation-managers/attach.php
  packages/admin/resources/lang/de/resources/relation-managers/create.php
  packages/admin/resources/lang/de/resources/relation-managers/delete.php
  packages/admin/resources/lang/de/resources/relation-managers/detach.php
  packages/admin/resources/lang/de/resources/relation-managers/edit.php
  packages/admin/resources/lang/de/widgets/account-widget.php
  packages/admin/resources/lang/de/widgets/filament-info-widget.php
Labels: enhancement, i18n

#1120 fix: Header action strings
  packages/tables/src/Actions/Concerns/HasAction.php
  packages/tables/src/Columns/Concerns/CanCallAction.php
Labels: bug

#1124 Fix input flickering problem
  packages/admin/resources/views/components/actions/select-action.blade.php
  packages/admin/resources/views/components/global-search/input.blade.php
  packages/admin/resources/views/components/layouts/app/sidebar/index.blade.php
  packages/admin/resources/views/components/modal/index.blade.php
  packages/admin/resources/views/widgets/chart-widget.blade.php
  packages/forms/resources/views/components/checkbox-list.blade.php
  packages/forms/resources/views/components/checkbox.blade.php
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/resources/views/components/markdown-editor.blade.php
  packages/forms/resources/views/components/markdown-editor/toolbar-button.blade.php
  packages/forms/resources/views/components/multi-select.blade.php
  packages/forms/resources/views/components/rich-editor.blade.php
  packages/forms/resources/views/components/select.blade.php
  packages/forms/resources/views/components/tags-input.blade.php
  packages/forms/resources/views/components/text-input.blade.php
  packages/forms/resources/views/components/textarea.blade.php
  packages/forms/resources/views/components/toggle.blade.php
  packages/tables/resources/views/components/filters/index.blade.php
  packages/tables/resources/views/components/modal/index.blade.php
  packages/tables/resources/views/components/pagination/records-per-page-selector.blade.php
  packages/tables/resources/views/components/search-input.blade.php
Labels: bug, ui

#1127 Adjust german translations
  packages/admin/resources/lang/de/login.php
  packages/admin/resources/lang/de/resources/pages/create-record.php
  packages/admin/resources/lang/de/resources/pages/list-records.php
  packages/admin/resources/lang/de/resources/relation-managers/attach.php
  packages/admin/resources/lang/de/resources/relation-managers/create.php
Labels: enhancement, i18n

#1128 fix: BelongsToManyMultiSelect key casting
  packages/forms/src/Components/BelongsToManyMultiSelect.php
Labels: bug

#1125 feature: configuring and configured hooks for PluginServiceProvider
  packages/admin/src/PluginServiceProvider.php
Labels: enhancement

#1129 feature: Add config option for default tables date format
  packages/tables/config/tables.php
  packages/tables/src/Columns/Concerns/CanFormatState.php
Labels: enhancement

#1130 feature: Customize admin panel logo & url
  packages/admin/config/filament.php
  packages/admin/docs/07-appearance.md
  packages/admin/resources/views/components/layouts/app/sidebar/index.blade.php
Labels: enhancement

#1134 feature: Expand table closure capabilities
  packages/tables/resources/views/components/header/index.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Actions/Action.php
  packages/tables/src/Actions/BulkAction.php
  packages/tables/src/Actions/ButtonAction.php
  packages/tables/src/Actions/Concerns/CanBeHidden.php
  packages/tables/src/Actions/Concerns/CanDeselectRecordsAfterCompletion.php
  packages/tables/src/Actions/Concerns/CanOpenModal.php
  packages/tables/src/Actions/Concerns/CanOpenUrl.php
  packages/tables/src/Actions/Concerns/CanRequireConfirmation.php
  packages/tables/src/Actions/Concerns/EvaluatesClosures.php
  packages/tables/src/Actions/Concerns/HasColor.php
  packages/tables/src/Actions/Concerns/HasFormSchema.php
  packages/tables/src/Actions/Concerns/HasIcon.php
  packages/tables/src/Actions/Concerns/HasLabel.php
  packages/tables/src/Columns/BooleanColumn.php
  packages/tables/src/Columns/Concerns/CanBeHidden.php
  packages/tables/src/Columns/Concerns/CanCallAction.php
  packages/tables/src/Columns/Concerns/CanCountRelatedModels.php
  packages/tables/src/Columns/Concerns/CanFormatState.php
  packages/tables/src/Columns/Concerns/CanOpenUrl.php
  packages/tables/src/Columns/Concerns/EvaluatesClosures.php
  packages/tables/src/Columns/Concerns/HasColors.php
  packages/tables/src/Columns/Concerns/HasExtraAttributes.php
  packages/tables/src/Columns/Concerns/HasLabel.php
  packages/tables/src/Columns/Concerns/HasState.php
  packages/tables/src/Columns/IconColumn.php
  packages/tables/src/Columns/ImageColumn.php
  packages/tables/src/Columns/TagsColumn.php
  packages/tables/src/Columns/TextColumn.php
  packages/tables/src/Concerns/HasActions.php
  packages/tables/src/Concerns/HasBulkActions.php
  packages/tables/src/Concerns/HasColumns.php
  packages/tables/src/Concerns/HasEmptyState.php
  packages/tables/src/Concerns/HasFilters.php
  packages/tables/src/Concerns/HasHeader.php
  packages/tables/src/Filters/Concerns/CanBeDefault.php
  packages/tables/src/Filters/Concerns/CanBeHidden.php
  packages/tables/src/Filters/Concerns/HasFormSchema.php
  packages/tables/src/Filters/Concerns/HasLabel.php
  packages/tables/src/Filters/MultiSelectFilter.php
  packages/tables/src/Filters/SelectFilter.php
Labels: enhancement

#1136 fix: Clearing Filepond's state
  packages/forms/resources/js/components/file-upload.js
  packages/forms/resources/views/components/file-upload.blade.php
Labels: bug

#1139 feature: Conditionally hidden widgets
  packages/admin/docs/04-dashboard.md
  packages/admin/resources/views/components/page.blade.php
  packages/admin/resources/views/pages/dashboard.blade.php
  packages/admin/src/Widgets/Widget.php
Labels: enhancement

#1144 fix: Widget keys
  packages/admin/resources/views/components/page.blade.php
  packages/admin/resources/views/components/widgets.blade.php
  packages/admin/resources/views/pages/dashboard.blade.php
Labels: bug

#1152 Small typo fix 'Eagre'
  packages/spatie-laravel-media-library-plugin/src/Tables/Columns/SpatieMediaLibraryImageColumn.php
  packages/tables/src/Columns/Concerns/InteractsWithTableQuery.php
  packages/tables/src/Concerns/HasRecords.php
Labels: chore

#1148 fix: HasAction: Pass all data to actions created from string
  packages/tables/src/Actions/BulkAction.php
  packages/tables/src/Actions/Concerns/HasAction.php
Labels: bug

#1150 Update Mask.php
  packages/forms/src/Components/TextInput/Mask.php
Labels: enhancement

#1156 Update grid layout docs
  packages/forms/docs/04-layout.md
Labels: documentation, enhancement

#1185 added code by @DanHarrin to fix the problem with limit() on TextColumns
  packages/tables/src/Columns/Concerns/CanFormatState.php
Labels: bug

#1186 removed z-10 from paginated item
  packages/tables/resources/views/components/pagination/item.blade.php
Labels: bug, ui

#1181 Adds placeholder function to SelectFilter and MultiSelectFilter
  packages/tables/resources/lang/en/table.php
  packages/tables/resources/lang/sv/table.php
  packages/tables/src/Filters/Concerns/HasPlaceholder.php
  packages/tables/src/Filters/MultiSelectFilter.php
  packages/tables/src/Filters/SelectFilter.php
Labels: enhancement

#1166 File Upload - Keep original filename
  packages/forms/docs/03-fields.md
  packages/forms/src/Components/BaseFileUpload.php
  packages/spatie-laravel-media-library-plugin/src/Forms/Components/SpatieMediaLibraryFileUpload.php
Labels: enhancement

#1190 fix: Clear relationship fields after create another
  packages/admin/src/Resources/Pages/CreateRecord.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanCreateRecords.php
  packages/spatie-laravel-translatable-plugin/src/Resources/Pages/CreateRecord/Concerns/Translatable.php
Labels: bug

#1193 Eager load tags for the SpatieTagsColumn
  packages/spatie-laravel-tags-plugin/src/Tables/Columns/SpatieTagsColumn.php
Labels: bug

#1194 Spanish translation
  packages/admin/resources/lang/es/global-search.php
  packages/admin/resources/lang/es/layout.php
  packages/admin/resources/lang/es/login.php
  packages/admin/resources/lang/es/pages/dashboard.php
  packages/admin/resources/lang/es/resources/pages/create-record.php
  packages/admin/resources/lang/es/resources/pages/edit-record.php
  packages/admin/resources/lang/es/resources/pages/list-records.php
  packages/admin/resources/lang/es/resources/pages/view-record.php
  packages/admin/resources/lang/es/resources/relation-managers/attach.php
  packages/admin/resources/lang/es/resources/relation-managers/create.php
  packages/admin/resources/lang/es/resources/relation-managers/delete.php
  packages/admin/resources/lang/es/resources/relation-managers/detach.php
  packages/admin/resources/lang/es/resources/relation-managers/edit.php
  packages/admin/resources/lang/es/widgets/account-widget.php
  packages/admin/resources/lang/es/widgets/filament-info-widget.php
  packages/forms/resources/lang/es/components.php
  packages/spatie-laravel-translatable-plugin/resources/lang/es/actions.php
  packages/tables/resources/lang/es/table.php
Labels: enhancement, i18n

#1199 feature: Add extra hidden action protection
  packages/tables/src/Concerns/HasActions.php
  packages/tables/src/Concerns/HasBulkActions.php
  packages/tables/src/Concerns/HasColumns.php
Labels: enhancement

#1201 fix: Uploaded images reloaded when form updated
  packages/admin/dist/app.css.map
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/admin/dist/module.esm.js
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/file-upload.js
Labels: bug

#1202 fix: MAJOR searchable select and multi select performance improvements 🎉
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/admin/dist/module.esm.js
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/file-upload.js
  packages/forms/resources/js/components/multi-select.js
  packages/forms/resources/js/components/select.js
Labels: enhancement

#1203 fix: Nested has many repeater relationships
  packages/forms/src/Components/Builder.php
  packages/forms/src/Components/Concerns/BelongsToModel.php
  packages/forms/src/Components/HasManyRepeater.php
  packages/forms/src/Components/Repeater.php
  packages/forms/src/Concerns/BelongsToModel.php
Labels: bug

#1206 fix: Czech translation
  packages/admin/resources/lang/cs/widgets/account-widget.php
  packages/admin/resources/lang/cs/widgets/filament-info-widget.php
  packages/forms/resources/lang/cs/components.php
Labels: i18n

#1207 Fix typo
  packages/forms/docs/06-advanced.md
Labels: bug, documentation

#1215 Update german translation files
  packages/tables/resources/lang/de/table.php
Labels: enhancement, i18n

#1214 Fixed typo and misunderstanding in README
  README.md
Labels: documentation

#1217 Fixes an error when saving empty $pivotColumns
  packages/admin/src/Resources/RelationManagers/BelongsToManyRelationManager.php
Labels: bug

#1216 Add forUser to the Gate check in can function
  packages/admin/src/Resources/RelationManagers/RelationManager.php
  packages/admin/src/Resources/Resource.php
Labels: bug

#1219 fix: Call relation manager mutation hooks
  packages/admin/src/Resources/Pages/CreateRecord.php
  packages/admin/src/Resources/Pages/EditRecord.php
  packages/admin/src/Resources/RelationManagers/BelongsToManyRelationManager.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanCreateRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanEditRecords.php
  packages/spatie-laravel-translatable-plugin/src/Resources/Pages/CreateRecord/Concerns/Translatable.php
  packages/spatie-laravel-translatable-plugin/src/Resources/Pages/EditRecord/Concerns/Translatable.php
Labels: bug

#1226 fix: Undefined multiselect option
  packages/admin/dist/module.esm.js
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/multi-select.js
Labels: bug

#1228 Docs: Explain how to conditionally hide pages
  packages/admin/docs/03-pages.md
Labels: documentation, enhancement

#1230 Include hidden component containers when hydrating a form
  packages/forms/src/Components/Builder.php
  packages/forms/src/Components/Concerns/HasChildComponents.php
  packages/forms/src/Components/HasManyRepeater.php
  packages/forms/src/Components/Repeater.php
  packages/forms/src/Concerns/HasState.php
Labels: enhancement

#1236 feature: Multi-relationship columns
  packages/tables/src/Columns/Concerns/HasState.php
  packages/tables/src/Columns/Concerns/InteractsWithTableQuery.php
  packages/tables/src/Columns/TextColumn.php
Labels: enhancement

#1239 fix: Indonesian translations
  packages/tables/resources/lang/id/table.php
Labels: enhancement, i18n

#1248 fix: Optimize HasManyRepeater queries and fix Postgres key issue
  packages/forms/src/Components/HasManyRepeater.php
Labels: bug

#1249 fix: Attach hook name
  packages/admin/src/Resources/RelationManagers/Concerns/CanAttachRecords.php
Labels: bug

#1250 fix: Hidden relation managers
  packages/admin/src/Resources/Pages/Concerns/HasRelationManagers.php
  packages/admin/src/Resources/Pages/EditRecord.php
  packages/admin/src/Resources/Pages/ViewRecord.php
Labels: bug

#1233 Field - Icon
  packages/forms/docs/03-fields.md
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/checkbox-list.blade.php
  packages/forms/resources/views/components/checkbox.blade.php
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/resources/views/components/field-wrapper/hint.blade.php
  packages/forms/resources/views/components/field-wrapper/index.blade.php
  packages/forms/resources/views/components/file-upload.blade.php
  packages/forms/resources/views/components/key-value.blade.php
  packages/forms/resources/views/components/markdown-editor.blade.php
  packages/forms/resources/views/components/multi-select.blade.php
  packages/forms/resources/views/components/placeholder.blade.php
  packages/forms/resources/views/components/radio.blade.php
  packages/forms/resources/views/components/repeater.blade.php
  packages/forms/resources/views/components/rich-editor.blade.php
  packages/forms/resources/views/components/select.blade.php
  packages/forms/resources/views/components/tags-input.blade.php
  packages/forms/resources/views/components/text-input.blade.php
  packages/forms/resources/views/components/textarea.blade.php
  packages/forms/resources/views/components/toggle.blade.php
  packages/forms/src/Components/Concerns/HasHint.php
  packages/forms/stubs/FieldView.stub
Labels: enhancement

#1254 feature: Page action modals
  packages/admin/docs/03-pages.md
  packages/admin/resources/lang/ar/resources/pages/edit-record.php
  packages/admin/resources/lang/cs/resources/pages/edit-record.php
  packages/admin/resources/lang/de/resources/pages/edit-record.php
  packages/admin/resources/lang/en/pages/actions.php
  packages/admin/resources/lang/en/resources/pages/edit-record.php
  packages/admin/resources/lang/es/resources/pages/edit-record.php
  packages/admin/resources/lang/fr/resources/pages/edit-record.php
  packages/admin/resources/lang/kh/resources/pages/edit-record.php
  packages/admin/resources/lang/ku/resources/pages/edit-record.php
  packages/admin/resources/lang/nl/resources/pages/edit-record.php
  packages/admin/resources/lang/pl/resources/pages/edit-record.php
  packages/admin/resources/lang/pt_BR/resources/pages/edit-record.php
  packages/admin/resources/lang/ru/resources/pages/edit-record.php
  packages/admin/resources/lang/sv/resources/pages/edit-record.php
  packages/admin/resources/lang/vi/resources/pages/edit-record.php
  packages/admin/resources/lang/zh_CN/resources/pages/edit-record.php
  packages/admin/resources/views/components/actions/button-action.blade.php
  packages/admin/resources/views/components/page.blade.php
  packages/admin/src/Pages/Actions/Action.php
  packages/admin/src/Pages/Actions/ButtonAction.php
  packages/admin/src/Pages/Actions/Concerns/BelongsToLivewire.php
  packages/admin/src/Pages/Actions/Concerns/CanBeMounted.php
  packages/admin/src/Pages/Actions/Concerns/CanOpenModal.php
  packages/admin/src/Pages/Actions/Concerns/CanRequireConfirmation.php
  packages/admin/src/Pages/Actions/Concerns/HasAction.php
  packages/admin/src/Pages/Actions/Concerns/HasFormSchema.php
  packages/admin/src/Pages/Concerns/HasActions.php
  packages/admin/src/Pages/Page.php
  packages/admin/src/Resources/Pages/CreateRecord.php
  packages/admin/src/Resources/Pages/EditRecord.php
  packages/admin/src/Resources/Pages/ViewRecord.php
  packages/spatie-laravel-settings-plugin/src/Pages/SettingsPage.php
Labels: enhancement

#1258 feature: Widget column span
  packages/admin/docs/04-dashboard.md
  packages/admin/resources/views/components/widget.blade.php
  packages/admin/resources/views/widgets/account-widget.blade.php
  packages/admin/resources/views/widgets/chart-widget.blade.php
  packages/admin/resources/views/widgets/filament-info-widget.blade.php
  packages/admin/resources/views/widgets/stats-overview-widget.blade.php
  packages/admin/src/Widgets/StatsOverviewWidget.php
  packages/admin/src/Widgets/Widget.php
  packages/admin/stubs/WidgetView.stub
Labels: enhancement

#1259 feature: Extra column header attributes
  packages/tables/resources/views/components/header-cell.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Columns/Column.php
  packages/tables/src/Columns/Concerns/HasExtraHeaderAttributes.php
Labels: enhancement

#1243 Review and add new key to Brazilian Portuguese at Forms and Tables.
  packages/admin/resources/lang/pt_BR/login.php
  packages/admin/resources/lang/pt_BR/resources/pages/create-record.php
  packages/forms/resources/lang/pt_BR/components.php
  packages/tables/resources/lang/pt_BR/table.php
Labels: enhancement, pending changes, i18n

#1246 Adds rows / keys / values editing to KeyValue form component
  packages/forms/resources/views/components/key-value.blade.php
  packages/forms/src/Components/KeyValue.php
Labels: bug, enhancement, pending changes

#1267 fix: Modal overlap
  packages/admin/resources/views/components/page.blade.php
  packages/admin/src/Pages/Concerns/HasActions.php
Labels: bug

#1270 Fix modal translation
  packages/admin/src/Pages/Actions/Concerns/CanOpenModal.php
Labels: bug

#1274 Added missing strings to french translation
  packages/forms/resources/lang/fr/components.php
  packages/tables/resources/lang/fr/table.php
Labels: enhancement, i18n

#1275 Feature/prevent duplicate register
  packages/admin/src/FilamentManager.php
Labels: bug

#1277 creation of pt_PT locales
  packages/admin/resources/lang/pt_PT/global-search.php
  packages/admin/resources/lang/pt_PT/layout.php
  packages/admin/resources/lang/pt_PT/login.php
  packages/admin/resources/lang/pt_PT/pages/dashboard.php
  packages/admin/resources/lang/pt_PT/resources/pages/create-record.php
  packages/admin/resources/lang/pt_PT/resources/pages/edit-record.php
  packages/admin/resources/lang/pt_PT/resources/pages/list-records.php
  packages/admin/resources/lang/pt_PT/resources/pages/view-record.php
  packages/admin/resources/lang/pt_PT/resources/relation-managers/attach.php
  packages/admin/resources/lang/pt_PT/resources/relation-managers/create.php
  packages/admin/resources/lang/pt_PT/resources/relation-managers/delete.php
  packages/admin/resources/lang/pt_PT/resources/relation-managers/detach.php
  packages/admin/resources/lang/pt_PT/resources/relation-managers/edit.php
  packages/admin/resources/lang/pt_PT/widgets/account-widget.php
  packages/admin/resources/lang/pt_PT/widgets/filament-info-widget.php
  packages/forms/resources/lang/pt_PT/components.php
  packages/tables/resources/lang/pt_PT/table.php
Labels: enhancement, i18n

#1278 Edit Arabic Label
  packages/admin/resources/lang/ar/resources/relation-managers/edit.php
Labels: i18n

#1282 [ar] Translate new table phrases
  packages/tables/resources/lang/ar/table.php
Labels: enhancement, i18n

#1297 Bump akaunting/laravel-money version
  composer.json
Labels: chore

#1311 add missing Arabic translations for components
  packages/forms/resources/lang/ar/components.php
Labels: enhancement, i18n

#1313 chore: make `Page::notify()` public
  packages/admin/src/Pages/Page.php
Labels: enhancement, chore

#1312 Missing actions.php file
  packages/admin/resources/lang/pl/pages/actions.php
Labels: enhancement, i18n

#1318 feature: MorphManyRepeater
  packages/forms/docs/03-fields.md
  packages/forms/src/Components/HasManyRepeater.php
  packages/forms/src/Components/MorphManyRepeater.php
  packages/forms/src/Components/RelationshipRepeater.php
Labels: enhancement

#1319 fix: Disabled pagination buttons
  packages/tables/resources/views/components/pagination/index.blade.php
Labels: bug

#1320 fix: Preserved record after create another
  packages/admin/src/Resources/Pages/CreateRecord.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanCreateRecords.php
Labels: bug

#1279 Allow searching multiple columns on BelongsToSelect relationships
  packages/forms/src/Components/BelongsToSelect.php
  packages/forms/src/Components/Select.php
  packages/tables/src/Columns/Concerns/CanBeSearchable.php
Labels: enhancement

#1332 Allow string roles()
  packages/forms/src/Components/Concerns/CanBeValidated.php
Labels: enhancement

#1337 feature: Alpine.js table row selection
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/mix-manifest.json
  packages/forms/resources/views/components/multi-select.blade.php
  packages/forms/resources/views/components/select.blade.php
  packages/tables/resources/views/components/bulk-actions/index.blade.php
  packages/tables/resources/views/components/checkbox-cell.blade.php
  packages/tables/resources/views/components/filters/index.blade.php
  packages/tables/resources/views/components/selection-indicator.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Columns/Concerns/HasState.php
  packages/tables/src/Concerns/CanSelectRecords.php
  packages/tables/src/Concerns/HasBulkActions.php
  packages/tables/src/Contracts/HasTable.php
  packages/tables/src/Table.php
Labels: enhancement

#1351 feature: advanced (isolated) navigation API
  packages/admin/src/Facades/Filament.php
  packages/admin/src/FilamentManager.php
  packages/admin/src/Navigation/NavigationBuilder.php
  packages/admin/src/Pages/Page.php
  packages/admin/src/Resources/Resource.php
Labels: enhancement

#1340 Added docs for 'extraInputAttributes'
  packages/forms/docs/03-fields.md
Labels: documentation, enhancement

#1362 feature: configurable brand
  packages/admin/config/filament.php
  packages/admin/resources/views/components/brand.blade.php
Labels: enhancement

#1385 Another small update to the docs
  packages/admin/docs/02-resources.md
Labels: bug, documentation

#1391 fix: List page actions
  packages/admin/src/Resources/Pages/ListRecords.php
Labels: bug

#1392 fix: Multi-relationship column n+1
  packages/tables/src/Columns/Concerns/HasState.php
  packages/tables/src/Concerns/HasRecords.php
Labels: bug

#1393 fix: code snippet for adding actions
  packages/admin/docs/02-resources.md
Labels: bug, documentation

#1394 fix: Attach select searchable columns
  packages/admin/src/Resources/RelationManagers/Concerns/CanAttachRecords.php
  packages/forms/src/Components/Select.php
Labels: bug

#1383 Update CanBeHidden traits for a more consistent implementation everywhere
  packages/admin/src/Pages/Actions/Concerns/CanBeHidden.php
  packages/tables/src/Actions/Concerns/CanBeHidden.php
  packages/tables/src/Columns/Concerns/CanBeHidden.php
Labels: enhancement
