Repository filamentphp/filament, pull requests merged in 2022-06, with the labels that each got.

#2627 Set anchor in sidebar to width full
  packages/admin/resources/views/components/layouts/app/sidebar/index.blade.php
Labels: enhancement

#2630 Only dispatch notifications via LW on Livewire requests
  packages/admin/src/NotificationManager.php
  tests/src/Admin/NotificationManager/NotificationManagerTest.php
Labels: bug

#2625 fix: file upload statePath mismatch at afterStateUpdated call
  packages/forms/src/Components/BaseFileUpload.php
  packages/forms/src/Concerns/HasState.php
Labels: bug

#2636 fix: Grouped relation manager keys
  packages/admin/resources/views/components/resources/relation-managers/index.blade.php
Labels: bug

#2638 fix: Undefined date picker state
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/date-time-picker.js
Labels: bug

#2649 Fixed search in JSON columns for PostgreSQL.
  packages/tables/src/Columns/Concerns/InteractsWithTableQuery.php
Labels: bug

#2655 Add RTL and Persian Lang for Wizard Component
  packages/forms/resources/lang/fa/components.php
  packages/forms/resources/views/components/wizard.blade.php
Labels: enhancement, i18n

#2656 change calendar width for persian languade
  packages/forms/resources/views/components/date-time-picker.blade.php
Labels: bug, ui

#2637 Prefix session keys
  packages/admin/resources/views/components/notification-manager.blade.php
  packages/admin/src/NotificationManager.php
  packages/tables/src/Concerns/CanPaginateRecords.php
  packages/tables/src/Concerns/CanToggleColumns.php
  tests/src/Admin/NotificationManager/NotificationManagerTest.php
Labels: enhancement

#2642 Use placeholder for ImageColumn when empty
  packages/tables/resources/views/columns/image-column.blade.php
Labels: enhancement

#2647 Add temporary url support for SpatieMediaLibraryImageColumn
  packages/spatie-laravel-media-library-plugin/src/Tables/Columns/SpatieMediaLibraryImageColumn.php
  packages/tables/docs/03-columns.md
  packages/tables/src/Columns/ImageColumn.php
Labels: enhancement

#2652 Add GridRepeater component
  packages/forms/docs/03-fields.md
  packages/forms/resources/views/component-container.blade.php
  packages/forms/resources/views/components/checkbox-list.blade.php
  packages/forms/resources/views/components/radio.blade.php
  packages/forms/resources/views/components/repeater.blade.php
  packages/forms/src/Components/Concerns/HasContainerGridLayout.php
  packages/forms/src/Components/Repeater.php
  packages/support/resources/views/components/grid.blade.php
Labels: enhancement

#2663 fix: Mobile modal position
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/mix-manifest.json
  packages/support/resources/views/components/modal/index.blade.php
Labels: bug, ui

#2664 fix: Generating custom resource page parent class
  packages/admin/src/Commands/MakePageCommand.php
Labels: bug

#2665 fix: Button loading state before Alpine init
  packages/support/resources/views/components/button.blade.php
Labels: bug

#2683 fix: accept Closure for Wizard steps
  packages/forms/src/Components/Wizard.php
Labels: bug

#2688 Dutch translation for upload button
  packages/support/resources/lang/nl/components/button.php
Labels: enhancement, i18n

#2689 Dutch translations for form components
  packages/forms/resources/lang/nl/components.php
Labels: enhancement, i18n

#2692 feature: Modify RelationshipRepeater query
  packages/forms/src/Components/RelationshipRepeater.php
Labels: enhancement

#2691 [2.X] Add Docs
  packages/admin/docs/02-resources/01-getting-started.md
  packages/admin/docs/03-pages/02-actions.md
  packages/admin/docs/04-dashboard/02-stats.md
  packages/forms/docs/03-fields.md
  packages/tables/docs/03-columns.md
Labels: documentation, enhancement

#2697 fix: x-cloak Blade components
  packages/admin/resources/views/components/layouts/base.blade.php
Labels: bug

#2699 fix: Grouped plugin RM
  packages/admin/src/PluginServiceProvider.php
  packages/admin/src/Resources/RelationManagers/RelationGroup.php
Labels: bug

#2704 fix opacity
  packages/support/resources/views/components/button.blade.php
Labels: bug

#2709 use getter for button isDisabled
  packages/support/resources/views/components/button.blade.php
Labels: bug

#2714 Added Spanish missing translations
  packages/forms/resources/lang/es/components.php
Labels: enhancement, i18n

#2718 Spanish wizard translations
  packages/forms/resources/lang/es/components.php
Labels: enhancement, i18n

#2716 FIX: Missing closure param type
  packages/tables/src/Columns/Concerns/CanOpenUrl.php
Labels: bug

#2720 Fix section component flicker
  packages/forms/resources/views/components/section.blade.php
Labels: bug, ui

#2735 [ar] Translate phrases
  packages/support/resources/lang/ar/actions/force-delete.php
  packages/support/resources/lang/ar/actions/group.php
  packages/support/resources/lang/ar/actions/replicate.php
  packages/support/resources/lang/ar/actions/restore.php
  packages/support/resources/lang/ar/actions/view.php
  packages/support/resources/lang/ar/components/button.php
Labels: enhancement, i18n

#2750 feature: Wizard step afterValidated() hook
  packages/forms/src/Components/Wizard.php
  packages/forms/src/Components/Wizard/Step.php
Labels: enhancement

#2752 Check Update Gate only once per row in table list
  packages/tables/resources/views/index.blade.php
Labels: enhancement

#2754 chore: Deprecations
  packages/admin/config/filament.php
  packages/admin/resources/views/components/global-search/input.blade.php
  packages/admin/src/Http/Livewire/GlobalSearch.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanAssociateRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanAttachRecords.php
  packages/admin/src/Resources/Table.php
  packages/forms/docs/03-fields.md
  packages/forms/src/Components/BelongsToSelect.php
  packages/forms/src/Components/Builder.php
  packages/forms/src/Components/Select.php
  packages/forms/src/Concerns/InteractsWithForms.php
  packages/forms/src/Concerns/SupportsSelectFields.php
  packages/forms/src/Contracts/HasForms.php
  packages/tables/resources/views/components/search-input.blade.php
  tests/src/Admin/GlobalSearch/GlobalSearchTest.php
Labels: chore

#2767 Update wizard arabic translations
  packages/forms/resources/lang/ar/components.php
Labels: enhancement, i18n

#2774 Fix Spatie translatable plugin getRecordTitle() error
  packages/spatie-laravel-translatable-plugin/src/Resources/Pages/Concerns/HasActiveFormLocaleSwitcher.php
Labels: bug

#2765 Prepare Polish language for v2.13
  packages/admin/resources/lang/pl/resources/pages/create-record.php
  packages/admin/resources/lang/pl/resources/pages/edit-record.php
  packages/forms/resources/lang/pl/components.php
  packages/support/resources/lang/pl/actions/associate.php
  packages/support/resources/lang/pl/actions/edit.php
  packages/support/resources/lang/pl/actions/force-delete.php
  packages/support/resources/lang/pl/actions/group.php
  packages/support/resources/lang/pl/actions/replicate.php
  packages/support/resources/lang/pl/actions/restore.php
  packages/support/resources/lang/pl/actions/view.php
  packages/support/resources/lang/pl/components/button.php
  packages/tables/resources/lang/pl/table.php
Labels: enhancement, i18n

#2777 Fix BulkDelete notificaton message
  packages/admin/src/Resources/Pages/ListRecords.php
Labels: bug, i18n

#2778 chore: add some more filament-* classes to section
  packages/forms/resources/views/components/section.blade.php
Labels: chore

#2780 fix: just add rtl group action dropdown position
  packages/support/resources/views/components/actions/group.blade.php
Labels: bug, ui

#2782 why import app.css to app.js?
  packages/admin/dist/app.js.map
  packages/admin/resources/js/app.js
Labels: chore

#2787 fix: Page action groups with records
  packages/support/src/Actions/ActionGroup.php
  packages/tables/src/Actions/ActionGroup.php
Labels: bug

#2803 fix: only register user menu items on Filament::serving
  packages/admin/src/PluginServiceProvider.php
Labels: bug

#2816 fix: add modal trigger slot to captureSlots
  packages/admin/resources/views/components/modal/index.blade.php
  packages/forms/resources/views/components/modal/index.blade.php
  packages/support/resources/lang/fa/actions/create.php
  packages/support/resources/lang/fa/actions/dissociate.php
  packages/support/resources/lang/fa/actions/force-delete.php
  packages/support/resources/lang/fa/actions/restore.php
  packages/tables/resources/views/components/modal/index.blade.php
Labels: bug

#2820 fix: Bulk action selected record sort
  packages/tables/src/Concerns/CanSelectRecords.php
Labels: chore

#2821 fix: Inline radio
  packages/forms/resources/views/components/radio.blade.php
  packages/support/resources/views/components/grid.blade.php
Labels: bug, ui

#2822 feature: Full width form actions
  packages/admin/resources/views/components/form/actions.blade.php
  packages/admin/resources/views/components/pages/actions/index.blade.php
  packages/admin/resources/views/resources/pages/create-record.blade.php
  packages/admin/resources/views/resources/pages/edit-record.blade.php
  packages/admin/src/Pages/Concerns/HasFormActions.php
Labels: enhancement

#2794 Allow mutate view record data before fill form
  packages/admin/src/Resources/Pages/ViewRecord.php
Labels: enhancement

#2788 feature: Select / Repeater ->relationship() modifier
  packages/admin/docs/02-resources/01-getting-started.md
  packages/forms/docs/02-getting-started.md
  packages/forms/docs/03-fields.md
  packages/forms/src/Components/BelongsToManyMultiSelect.php
  packages/forms/src/Components/BelongsToSelect.php
  packages/forms/src/Components/HasManyRepeater.php
  packages/forms/src/Components/MorphManyRepeater.php
  packages/forms/src/Components/RelationshipRepeater.php
  packages/forms/src/Components/Repeater.php
  packages/forms/src/Components/Select.php
Labels: enhancement

#2828 Fix: cannot edit pivot data in belongs to many relationships unless they allow duplicates
  packages/tables/src/Concerns/HasRecords.php
Labels: bug

#2833 Spanish translation update
  packages/support/resources/lang/es/actions/create.php
  packages/support/resources/lang/es/actions/force-delete.php
  packages/support/resources/lang/es/actions/group.php
  packages/support/resources/lang/es/actions/restore.php
  packages/support/resources/lang/es/actions/view.php
  packages/tables/resources/lang/es/table.php
Labels: enhancement, i18n

#2839 fix: Page action default icon
  packages/admin/resources/views/components/pages/actions/action.blade.php
  packages/admin/resources/views/pages/actions/grouped-action.blade.php
  packages/admin/src/Pages/Actions/Action.php
  packages/admin/src/Pages/Actions/CreateAction.php
  packages/admin/src/Pages/Actions/DeleteAction.php
  packages/admin/src/Pages/Actions/EditAction.php
  packages/admin/src/Pages/Actions/ForceDeleteAction.php
  packages/admin/src/Pages/Actions/ReplicateAction.php
  packages/admin/src/Pages/Actions/RestoreAction.php
  packages/admin/src/Pages/Actions/ViewAction.php
  packages/support/src/Actions/Concerns/CanReplicateRecords.php
  packages/support/src/Actions/Concerns/HasGroupedIcon.php
  packages/tables/resources/views/actions/grouped-action.blade.php
  packages/tables/resources/views/components/actions/action.blade.php
  packages/tables/src/Actions/Action.php
  packages/tables/src/Actions/ReplicateAction.php
Labels: bug

#2843 Update sortable.js
  packages/forms/resources/js/sortable.js
Labels: chore

#2776 Allow HTML for notification messages
  packages/admin/resources/views/components/notification.blade.php
  packages/admin/src/NotificationManager.php
  packages/forms/src/Components/Concerns/CanBeValidated.php
  packages/tables/src/Concerns/CanSelectRecords.php
  packages/tables/src/Concerns/HasRecords.php
  tests/src/Admin/NotificationManager/NotificationManagerTest.php
Labels: enhancement

#2845 feature: Important configurations
  packages/forms/src/Components/Card.php
  packages/forms/src/Components/Field.php
  packages/forms/src/Components/Fieldset.php
  packages/forms/src/Components/Grid.php
  packages/forms/src/Components/Group.php
  packages/forms/src/Components/Placeholder.php
  packages/forms/src/Components/Section.php
  packages/forms/src/Components/Tabs.php
  packages/forms/src/Components/Tabs/Tab.php
  packages/forms/src/Components/Wizard.php
  packages/forms/src/Components/Wizard/Step.php
  packages/support/src/Actions/BaseAction.php
  packages/support/src/Concerns/Configurable.php
  packages/tables/resources/views/components/header-cell.blade.php
  packages/tables/src/Columns/Column.php
  packages/tables/src/Filters/BaseFilter.php
Labels: enhancement

#2849 Feature: makes sidebar width configurable
  packages/admin/config/filament.php
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/admin/resources/views/components/layouts/app.blade.php
  packages/admin/resources/views/components/layouts/app/sidebar/index.blade.php
  packages/admin/resources/views/components/layouts/base.blade.php
  packages/forms/dist/module.esm.js
Labels: enhancement

#2857 Revert getQualifiedKeyName on records and pivots
  packages/forms/src/Components/Concerns/CanBeValidated.php
  packages/tables/src/Concerns/CanSelectRecords.php
  packages/tables/src/Concerns/HasRecords.php
Labels: bug

#2854 Fix: Disable tap highlight on WebKit browsers
  packages/admin/resources/css/app.css
Labels: bug, ui

#2872 Fix: require recordId in Attach and Associate actions
  packages/admin/src/Resources/RelationManagers/Concerns/CanAssociateRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanAttachRecords.php
  packages/tables/src/Actions/AssociateAction.php
  packages/tables/src/Actions/AttachAction.php
Labels: bug

#2871 refactor: replace `Str::title` with `Str::headline`
  packages/admin/src/Resources/Pages/Concerns/InteractsWithRecord.php
  packages/admin/src/Resources/Pages/ListRecords.php
  packages/admin/src/Resources/RelationManagers/RelationManager.php
  packages/admin/src/Resources/Resource.php
Labels: bug

#2887 Update 05-actions.md
  packages/tables/docs/05-actions.md
Labels: documentation, enhancement

#2899 Hungarian translation
  packages/admin/resources/lang/hu/global-search.php
  packages/admin/resources/lang/hu/layout.php
  packages/admin/resources/lang/hu/login.php
  packages/admin/resources/lang/hu/pages/dashboard.php
  packages/admin/resources/lang/hu/resources/pages/create-record.php
  packages/admin/resources/lang/hu/resources/pages/edit-record.php
  packages/admin/resources/lang/hu/resources/pages/list-records.php
  packages/admin/resources/lang/hu/resources/pages/view-record.php
  packages/admin/resources/lang/hu/widgets/account-widget.php
  packages/admin/resources/lang/hu/widgets/filament-info-widget.php
  packages/forms/resources/lang/hu/components.php
  packages/spatie-laravel-settings-plugin/resources/lang/hu/pages/settings-page.php
  packages/spatie-laravel-translatable-plugin/resources/lang/hu/actions.php
  packages/support/resources/lang/hu/actions/associate.php
  packages/support/resources/lang/hu/actions/attach.php
  packages/support/resources/lang/hu/actions/create.php
  packages/support/resources/lang/hu/actions/delete.php
  packages/support/resources/lang/hu/actions/detach.php
  packages/support/resources/lang/hu/actions/dissociate.php
  packages/support/resources/lang/hu/actions/edit.php
  packages/support/resources/lang/hu/actions/force-delete.php
  packages/support/resources/lang/hu/actions/group.php
  packages/support/resources/lang/hu/actions/modal.php
  packages/support/resources/lang/hu/actions/replicate.php
  packages/support/resources/lang/hu/actions/restore.php
  packages/support/resources/lang/hu/actions/view.php
  packages/support/resources/lang/hu/components/button.php
  packages/tables/resources/lang/hu/table.php
Labels: enhancement, i18n

#2900 Romanian translation
  packages/admin/resources/lang/ro/global-search.php
  packages/admin/resources/lang/ro/layout.php
  packages/admin/resources/lang/ro/login.php
  packages/admin/resources/lang/ro/pages/dashboard.php
  packages/admin/resources/lang/ro/resources/pages/create-record.php
  packages/admin/resources/lang/ro/resources/pages/edit-record.php
  packages/admin/resources/lang/ro/resources/pages/list-records.php
  packages/admin/resources/lang/ro/resources/pages/view-record.php
  packages/admin/resources/lang/ro/widgets/account-widget.php
  packages/admin/resources/lang/ro/widgets/filament-info-widget.php
  packages/forms/resources/lang/ro/components.php
  packages/spatie-laravel-settings-plugin/resources/lang/ro/pages/settings-page.php
  packages/spatie-laravel-translatable-plugin/resources/lang/ro/actions.php
  packages/support/resources/lang/ro/actions/associate.php
  packages/support/resources/lang/ro/actions/attach.php
  packages/support/resources/lang/ro/actions/create.php
  packages/support/resources/lang/ro/actions/delete.php
  packages/support/resources/lang/ro/actions/detach.php
  packages/support/resources/lang/ro/actions/dissociate.php
  packages/support/resources/lang/ro/actions/edit.php
  packages/support/resources/lang/ro/actions/force-delete.php
  packages/support/resources/lang/ro/actions/group.php
  packages/support/resources/lang/ro/actions/modal.php
  packages/support/resources/lang/ro/actions/replicate.php
  packages/support/resources/lang/ro/actions/restore.php
  packages/support/resources/lang/ro/actions/view.php
  packages/support/resources/lang/ro/components/button.php
  packages/tables/resources/lang/ro/table.php
Labels: enhancement, i18n

#2901 fix: Retrieve initial ancestor state from closure
  packages/forms/src/Components/Concerns/HasState.php
  tests/src/Forms/StateTest.php
Labels: bug

#2903 Modularize Composer scripts
  composer.json
Labels: enhancement

#2908 Fix FR Translations
  packages/forms/resources/lang/fr/components.php
  packages/support/resources/lang/fr/actions/force-delete.php
  packages/support/resources/lang/fr/actions/group.php
  packages/support/resources/lang/fr/actions/replicate.php
  packages/support/resources/lang/fr/actions/restore.php
  packages/support/resources/lang/fr/components/button.php
Labels: enhancement, i18n

#2918 Fixes typo in FA translations.
  packages/forms/resources/lang/fa/components.php
Labels: enhancement, i18n

#2919 removed inert modifier from x-trap for modals
  packages/support/resources/views/components/modal/index.blade.php
Labels: bug

#2924 Added Armenian translation
  packages/admin/resources/lang/hy/global-search.php
  packages/admin/resources/lang/hy/layout.php
  packages/admin/resources/lang/hy/login.php
  packages/admin/resources/lang/hy/pages/dashboard.php
  packages/admin/resources/lang/hy/resources/pages/create-record.php
  packages/admin/resources/lang/hy/resources/pages/edit-record.php
  packages/admin/resources/lang/hy/resources/pages/list-records.php
  packages/admin/resources/lang/hy/resources/pages/view-record.php
  packages/admin/resources/lang/hy/widgets/account-widget.php
  packages/admin/resources/lang/hy/widgets/filament-info-widget.php
  packages/forms/resources/lang/hy/components.php
  packages/spatie-laravel-settings-plugin/resources/lang/hy/pages/settings-page.php
  packages/spatie-laravel-translatable-plugin/resources/lang/hy/actions.php
  packages/support/resources/lang/hy/actions/associate.php
  packages/support/resources/lang/hy/actions/attach.php
  packages/support/resources/lang/hy/actions/create.php
  packages/support/resources/lang/hy/actions/delete.php
  packages/support/resources/lang/hy/actions/detach.php
  packages/support/resources/lang/hy/actions/dissociate.php
  packages/support/resources/lang/hy/actions/edit.php
  packages/support/resources/lang/hy/actions/force-delete.php
  packages/support/resources/lang/hy/actions/group.php
  packages/support/resources/lang/hy/actions/modal.php
  packages/support/resources/lang/hy/actions/replicate.php
  packages/support/resources/lang/hy/actions/restore.php
  packages/support/resources/lang/hy/actions/view.php
  packages/support/resources/lang/hy/components/button.php
  packages/tables/resources/lang/hy/table.php
Labels: enhancement, i18n

#2925 Bosnian Translation
  packages/admin/resources/lang/bs/global-search.php
  packages/admin/resources/lang/bs/layout.php
  packages/admin/resources/lang/bs/login.php
  packages/admin/resources/lang/bs/pages/dashboard.php
  packages/admin/resources/lang/bs/resources/pages/create-record.php
  packages/admin/resources/lang/bs/resources/pages/edit-record.php
  packages/admin/resources/lang/bs/resources/pages/list-records.php
  packages/admin/resources/lang/bs/resources/pages/view-record.php
  packages/admin/resources/lang/bs/widgets/account-widget.php
  packages/admin/resources/lang/bs/widgets/filament-info-widget.php
  packages/forms/resources/lang/bs/components.php
  packages/tables/resources/lang/bs/table.php
Labels: enhancement, i18n

#2928 Check if state has changed in file upload watcher
  packages/forms/resources/js/components/file-upload.js
Labels: bug

#2930 Missing turkish translations
  packages/spatie-laravel-settings-plugin/resources/lang/tr/pages/settings-page.php
  packages/tables/resources/lang/tr/table.php
Labels: enhancement, i18n

#2878 Use create() instead of save() for BelongsTo relationships whev saving.
  packages/forms/src/Components/Concerns/EntanglesStateWithSingularRelationship.php
Labels: bug

#2868 Add CSS Class to Filters
  packages/tables/resources/views/components/filters/index.blade.php
Labels: enhancement

#2940 Allow Dependency injection in $table->query()
  packages/tables/src/Filters/Concerns/InteractsWithTableQuery.php
Labels: enhancement

#2955 zh_TW translations
  packages/admin/resources/lang/zh_TW/global-search.php
  packages/admin/resources/lang/zh_TW/layout.php
  packages/admin/resources/lang/zh_TW/login.php
  packages/admin/resources/lang/zh_TW/pages/dashboard.php
  packages/admin/resources/lang/zh_TW/resources/pages/create-record.php
  packages/admin/resources/lang/zh_TW/resources/pages/list-records.php
  packages/admin/resources/lang/zh_TW/resources/pages/view-record.php
  packages/admin/resources/lang/zh_TW/widgets/account-widget.php
  packages/admin/resources/lang/zh_TW/widgets/filament-info-widget.php
  packages/forms/resources/lang/zh_TW/components.php
  packages/spatie-laravel-settings-plugin/resources/lang/zh_TW/pages/settings-page.php
  packages/spatie-laravel-translatable-plugin/resources/lang/zh_TW/actions.php
  packages/support/resources/lang/zh_TW/actions/associate.php
  packages/support/resources/lang/zh_TW/actions/attach.php
  packages/support/resources/lang/zh_TW/actions/create.php
  packages/support/resources/lang/zh_TW/actions/delete.php
  packages/support/resources/lang/zh_TW/actions/detach.php
  packages/support/resources/lang/zh_TW/actions/dissociate.php
  packages/support/resources/lang/zh_TW/actions/edit.php
  packages/support/resources/lang/zh_TW/actions/force-delete.php
  packages/support/resources/lang/zh_TW/actions/group.php
  packages/support/resources/lang/zh_TW/actions/modal.php
  packages/support/resources/lang/zh_TW/actions/replicate.php
  packages/support/resources/lang/zh_TW/actions/restore.php
  packages/support/resources/lang/zh_TW/actions/view.php
  packages/support/resources/lang/zh_TW/components/button.php
  packages/tables/resources/lang/zh_TW/table.php
Labels: enhancement, i18n

#2959 improve RTL admin panel sidebar
  packages/admin/resources/views/components/layouts/app/sidebar/index.blade.php
Labels: ui, i18n

#2973 feature: allow passing array of classes to `visibleOn` and `hiddenOn`
  packages/forms/src/Components/Concerns/CanBeHidden.php
  tests/src/Forms/HiddenComponentsTest.php
Labels: enhancement

#2974 fix: disabled state Textarea
  packages/forms/resources/views/components/textarea.blade.php
Labels: bug

#2713 Determine plural label based on locale
  packages/admin/src/Resources/RelationManagers/RelationManager.php
  packages/admin/src/Resources/Resource.php
  packages/admin/src/helpers.php
  packages/support/src/Actions/Concerns/InteractsWithRecord.php
  packages/tables/src/Concerns/HasRecords.php
  tests/src/Admin/Resources/ResourceTest.php
Labels: bug

#2945 faking livewire entangle.lazy
  packages/forms/resources/views/components/text-input.blade.php
  packages/forms/src/Concerns/HasStateBindingModifiers.php
Labels: bug

#2958 fix date time picker min max value
  packages/forms/resources/js/components/date-time-picker.js
Labels: bug

#2729 Allows refreshing chart in widget after data changes
  packages/admin/resources/views/components/stats/card.blade.php
Labels: enhancement

#2738 Update Repeater.php to work with BelongsToMany relationships
  packages/forms/src/Components/Repeater.php
Labels: enhancement

#2980 Change UiAvatarProvider logic
  packages/admin/src/AvatarProviders/UiAvatarsProvider.php
Labels: bug

#2741 feat:mutate relationship data before create or save
  packages/forms/src/Components/Repeater.php
Labels: enhancement

#2981 fix: UiAvatars substring non ascii name
  packages/admin/src/AvatarProviders/UiAvatarsProvider.php
Labels: bug

#2983 fix mutateRelationshipDataBeforeCreate
  packages/forms/src/Components/Repeater.php
Labels: bug

#2946 refactor(generate): Allow partial model namespaces during resource generation
  packages/admin/src/Commands/Concerns/CanGenerateResources.php
Labels: bug

#2985 Change `data` parameter to `state`
  packages/tables/src/Filters/Concerns/InteractsWithTableQuery.php
Labels: bug

#2991 Fix bug faked entangle
  packages/forms/resources/views/components/text-input.blade.php
  packages/forms/src/Concerns/HasStateBindingModifiers.php
Labels: bug
