Repository filamentphp/filament, pull requests merged in 2022-08, with the labels that each got.

#3326 fix: Dropdown item icon size
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/mix-manifest.json
  packages/support/resources/views/components/dropdown/item.blade.php
Labels: bug

#3328 chore: Check repro repo for org
  .github/workflows/manage-issue.yml
Labels: chore

#3324 fix: Admin panel registration Livewire boot
  packages/admin/src/FilamentServiceProvider.php
  packages/admin/src/PluginServiceProvider.php
Labels: bug

#3276 Auto register prefix/suffix actions
  packages/forms/src/Components/Concerns/HasActions.php
  packages/forms/src/Components/Concerns/HasAffixes.php
  tests/src/Forms/ActionsTest.php
  tests/src/Forms/FieldTest.php
Labels: enhancement

#3330 Fix: Correct abnormal breakpoint in Filepond style
  packages/forms/resources/css/components/file-upload.css
Labels: bug, ui

#3314 Add support for descriptions to Text Columns
  packages/tables/docs/03-columns.md
  packages/tables/resources/views/columns/text-column.blade.php
  packages/tables/src/Columns/Concerns/HasDescription.php
  packages/tables/src/Columns/TextColumn.php
Labels: enhancement

#3299 feature: Active tab and badge
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/mix-manifest.json
  packages/forms/docs/04-layout.md
  packages/forms/resources/views/components/tabs.blade.php
  packages/forms/src/Components/Tabs.php
  packages/forms/src/Components/Tabs/Tab.php
Labels: enhancement

#3331 chore: Optimize array handling (and remove simple collections)
  packages/admin/src/FilamentManager.php
  packages/admin/src/FilamentServiceProvider.php
  packages/admin/src/Navigation/NavigationBuilder.php
  packages/admin/src/Pages/Concerns/HasActions.php
  packages/admin/src/Pages/Concerns/HasFormActions.php
  packages/admin/src/Testing/TestsPages.php
  packages/forms/src/Components/BaseFileUpload.php
  packages/forms/src/Components/Builder.php
  packages/forms/src/Components/Concerns/InteractsWithToolbarButtons.php
  packages/forms/src/Components/KeyValue.php
  packages/forms/src/Components/Repeater.php
  packages/forms/src/Components/Select.php
  packages/notifications/resources/views/components/actions/action.blade.php
  packages/spatie-laravel-translatable-plugin/src/Pages/Actions/LocaleSwitcher.php
  packages/support/src/Actions/ActionGroup.php
  packages/support/src/SupportServiceProvider.php
  packages/support/src/helpers.php
  packages/tables/src/Actions/ActionGroup.php
  packages/tables/src/Concerns/HasActions.php
  packages/tables/src/Concerns/HasBulkActions.php
  packages/tables/src/Concerns/HasColumns.php
  packages/tables/src/Concerns/HasEmptyState.php
  packages/tables/src/Concerns/HasFilters.php
  packages/tables/src/Concerns/HasHeader.php
  packages/tables/src/Testing/TestsActions.php
Labels: chore

#3335 add configuration for default select options
  packages/tables/config/tables.php
  packages/tables/src/Concerns/CanPaginateRecords.php
Labels: enhancement

#3339 Add .gitattributes, exclude tests from archive
  .gitattributes
Labels: chore

#3338 fix production error on environments with Composer version 1
  packages/support/src/SupportServiceProvider.php
Labels: bug

#3336 chore: Upgrade command in support
  composer.lock
  packages/admin/docs/01-installation.md
  packages/admin/src/Commands/Concerns/CanManipulateFiles.php
  packages/admin/src/Commands/MakePageCommand.php
  packages/admin/src/Commands/MakeRelationManagerCommand.php
  packages/admin/src/Commands/MakeResourceCommand.php
  packages/admin/src/Commands/MakeWidgetCommand.php
  packages/admin/src/FilamentServiceProvider.php
  packages/forms/docs/01-installation.md
  packages/forms/src/Commands/Concerns/CanManipulateFiles.php
  packages/forms/src/Commands/MakeFieldCommand.php
  packages/forms/src/Commands/MakeLayoutComponentCommand.php
  packages/notifications/docs/01-installation.md
  packages/spatie-laravel-media-library-plugin/docs/01-installation.md
  packages/spatie-laravel-settings-plugin/docs/01-installation.md
  packages/spatie-laravel-settings-plugin/src/Commands/MakeSettingsPageCommand.php
  packages/spatie-laravel-tags-plugin/docs/01-installation.md
  packages/spatie-laravel-translatable-plugin/docs/01-installation.md
  packages/support/composer.json
  packages/support/composer.lock
  packages/support/src/Commands/Concerns/CanManipulateFiles.php
  packages/support/src/Commands/UpgradeCommand.php
  packages/support/src/SupportServiceProvider.php
  packages/tables/docs/01-installation.md
  packages/tables/src/Commands/MakeColumnCommand.php
Labels: chore

#3342 feature: Select options limit
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/select.js
  packages/forms/resources/views/components/select.blade.php
  packages/forms/src/Components/Select.php
Labels: enhancement

#3355 Add disabled:opacity-70 to checkbox and radio
  packages/forms/resources/views/components/checkbox-list.blade.php
  packages/forms/resources/views/components/checkbox.blade.php
  packages/forms/resources/views/components/radio.blade.php
Labels: ui

#3345 hiddenOn() / visibleOn() for actions
  packages/admin/docs/02-resources/01-getting-started.md
  packages/admin/src/Pages/Concerns/HasActions.php
  packages/admin/src/Resources/Pages/CreateRecord.php
  packages/admin/src/Resources/Pages/EditRecord.php
  packages/admin/src/Resources/Pages/ViewRecord.php
  packages/forms/src/ComponentContainer.php
  packages/forms/src/Components/Component.php
  packages/forms/src/Components/Concerns/CanBeHidden.php
  packages/forms/src/Concerns/HasContext.php
  packages/forms/src/Concerns/HasFormComponentActions.php
  packages/tables/src/Concerns/HasActions.php
  packages/tables/src/Concerns/HasBulkActions.php
Labels: bug

#2808 Feature: support icon-only buttons
  packages/admin/resources/views/components/pages/actions/action.blade.php
  packages/support/resources/views/components/button.blade.php
  packages/support/src/Actions/Concerns/HasLabel.php
Labels: enhancement

#3362 fix: Builder null state
  packages/forms/src/Components/Builder.php
Labels: bug

#3363 chore: Null coalescing
  packages/admin/src/FilamentServiceProvider.php
  packages/forms/src/Concerns/HasState.php
  packages/notifications/src/Http/Livewire/Notifications.php
  packages/notifications/src/NotificationsServiceProvider.php
  packages/spatie-laravel-translatable-plugin/src/SpatieLaravelTranslatablePluginServiceProvider.php
Labels: chore, code quality

#3366 Fix `visibleOn` / `hiddenOn` context check
  packages/forms/src/Components/Concerns/CanBeHidden.php
Labels: bug

#3365 Added content hooks to footer.blade.php
  packages/admin/docs/07-appearance.md
  packages/admin/resources/views/components/footer.blade.php
Labels: enhancement

#3368 Use Filament auth middleware for LW requests.
  packages/admin/src/FilamentServiceProvider.php
Labels: bug

#3373 fix: Don't XSS sanitize HtmlString objects
  packages/forms/resources/views/components/field-wrapper/index.blade.php
  packages/forms/resources/views/components/field-wrapper/inline.blade.php
  packages/forms/src/Components/Concerns/HasHelperText.php
  packages/forms/src/Components/Concerns/HasHint.php
  packages/notifications/resources/views/notification.blade.php
  packages/tables/resources/views/columns/text-column.blade.php
  packages/tables/src/Columns/Concerns/CanFormatState.php
Labels: bug

#3374 feature: Customize translatable locale label
  bootstrap/app.php
  packages/spatie-laravel-translatable-plugin/src/Facades/SpatieLaravelTranslatablePlugin.php
  packages/spatie-laravel-translatable-plugin/src/Pages/Actions/LocaleSwitcher.php
  packages/spatie-laravel-translatable-plugin/src/SpatieLaravelTranslatablePluginManager.php
  packages/spatie-laravel-translatable-plugin/src/SpatieLaravelTranslatablePluginServiceProvider.php
Labels: enhancement

#3380 translate actions view.php in italian
  packages/support/resources/lang/it/actions/view.php
Labels: enhancement, i18n

#3391 Break words in rich editor
  packages/forms/resources/views/components/rich-editor.blade.php
Labels: bug

#3378 Check if a relation actually exists in a table column, otherwise assume an array should be accessed
  packages/tables/src/Columns/Concerns/HasLabel.php
  packages/tables/src/Columns/Concerns/HasState.php
  packages/tables/src/Columns/Concerns/InteractsWithTableQuery.php
Labels: enhancement

#3393 fix: Nested relationship names typo
  packages/tables/src/Columns/Concerns/InteractsWithTableQuery.php
Labels: bug

#3394 Separate user-avatar
  packages/admin/resources/views/components/layouts/app/topbar/user-menu.blade.php
  packages/admin/resources/views/components/user-avatar.blade.php
  packages/admin/resources/views/widgets/account-widget.blade.php
Labels: enhancement

#3400 chore: Solidify issue bot
  .github/workflows/manage-issue.yml
Labels: chore

#3385 fixes date time picker disappearing when set to reactive
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/src/Concerns/HasStateBindingModifiers.php
Labels: bug

#3402 ColorPicker fixes
  packages/forms/resources/views/components/color-picker.blade.php
Labels: bug

#3379 Add title and alt attributes for iconbutton
  packages/support/resources/views/components/icon-button.blade.php
Labels: enhancement

#3396 Add table filter relationship option query
  packages/forms/src/Components/CheckboxList.php
  packages/forms/src/Components/Repeater.php
  packages/forms/src/Components/Select.php
  packages/tables/docs/04-filters.md
  packages/tables/src/Filters/Concerns/HasRelationship.php
Labels: enhancement

#3403 fix: Text files in Filament autodiscovery directory
  packages/admin/src/FilamentServiceProvider.php
Labels: bug

#3408 fix: Initially set KeyVal
  packages/forms/resources/js/components/key-value.js
Labels: bug

#3413 fix: Form component actions in repeater
  packages/forms/src/Concerns/HasComponents.php
Labels: bug

#3410 fix: wire:key consistency
  packages/forms/resources/views/component-container.blade.php
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/color-picker.blade.php
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/resources/views/components/repeater.blade.php
  packages/notifications/resources/views/components/notification.blade.php
  packages/tables/resources/views/components/filters/popover.blade.php
  packages/tables/resources/views/components/pagination/index.blade.php
  packages/tables/resources/views/components/reorder/indicator.blade.php
  packages/tables/resources/views/components/selection-indicator.blade.php
  packages/tables/resources/views/components/toggleable/index.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Testing/TestsRecords.php
Labels: bug

#3423 fix: Add wire:keys to action modals
  packages/admin/resources/views/components/page.blade.php
  packages/forms/resources/views/components/actions/modal/index.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Concerns/HasActions.php
  packages/tables/src/Contracts/HasTable.php
  packages/tables/src/Table.php
Labels: bug

#3435 Move filesystem component registration to boot process in app lifecycle
  packages/admin/src/FilamentServiceProvider.php
Labels: bug

#3437 feature: More action testing helpers
  packages/admin/.stubs.php
  packages/admin/docs/03-pages/02-actions.md
  packages/admin/docs/09-testing.md
  packages/admin/src/FilamentServiceProvider.php
  packages/admin/src/Testing/TestsPageActions.php
  packages/admin/src/Testing/TestsPages.php
  packages/tables/.stubs.php
  packages/tables/docs/05-actions.md
  packages/tables/docs/06-testing.md
  packages/tables/src/TablesServiceProvider.php
  packages/tables/src/Testing/TestsActions.php
  packages/tables/src/Testing/TestsBulkActions.php
  tests/src/Admin/Fixtures/Pages/PageActions.php
  tests/src/Admin/Pages/ActionTest.php
  tests/src/Tables/ActionTest.php
  tests/src/Tables/BulkActionTest.php
  tests/src/Tables/Fixtures/PostsTable.php
Labels: enhancement

#3407 feature: Store file names from FileUpload
  packages/forms/docs/03-fields.md
  packages/forms/src/Components/BaseFileUpload.php
  packages/forms/src/Components/Concerns/CanBeValidated.php
  packages/forms/src/Components/Concerns/HasState.php
  packages/forms/src/Components/Contracts/HasValidationRules.php
  packages/forms/src/Concerns/CanBeValidated.php
  packages/forms/src/Concerns/HasState.php
Labels: enhancement

#3430 Repeater - Access parent field value inside
  packages/forms/docs/03-fields.md
Labels: documentation, enhancement

#3440 chore: fix docs typo
  packages/forms/docs/03-fields.md
Labels: bug, documentation

#3439 fix: Swap toArray() with attributesToArray()
  packages/admin/src/Resources/Pages/EditRecord.php
  packages/admin/src/Resources/Pages/ListRecords/Concerns/CanEditRecords.php
  packages/admin/src/Resources/Pages/ListRecords/Concerns/CanViewRecords.php
  packages/admin/src/Resources/Pages/ViewRecord.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanEditRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanViewRecords.php
  packages/forms/src/Components/Concerns/EntanglesStateWithSingularRelationship.php
  packages/forms/src/Components/Repeater.php
  packages/spatie-laravel-translatable-plugin/src/Resources/Pages/EditRecord/Concerns/Translatable.php
  packages/spatie-laravel-translatable-plugin/src/Resources/Pages/ViewRecord/Concerns/Translatable.php
  packages/support/src/Actions/Concerns/CanReplicateRecords.php
  packages/tables/src/Actions/EditAction.php
  packages/tables/src/Actions/ViewAction.php
Labels: bug

#3441 fix: Mask watcher
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/text-input.js
Labels: bug

#3452 fix: Use Livewire ID in action modal ID
  packages/forms/resources/views/components/actions/modal/index.blade.php
  packages/forms/src/Concerns/HasFormComponentActions.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Concerns/HasActions.php
  packages/tables/src/Concerns/HasBulkActions.php
  packages/tables/src/Testing/TestsActions.php
  packages/tables/src/Testing/TestsBulkActions.php
Labels: bug

#3453 fix: Hydrate state after loading from relationship
  packages/forms/src/Components/Concerns/BelongsToModel.php
  packages/forms/src/Concerns/BelongsToModel.php
  packages/forms/src/Concerns/HasState.php
Labels: bug

#3455 CHG: Add Arrayable return type to repeater
  packages/forms/src/Concerns/HasState.php
Labels: bug

#3457 Fix multi select style
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.css
  packages/forms/resources/css/components/select.css
Labels: bug

#3466 Improve vi translations
  packages/forms/resources/lang/vi/components.php
Labels: enhancement, i18n

#3468 Add new debounce test to StateBindingModifiersTest
  tests/src/Forms/StateBindingModifiersTest.php
Labels: enhancement

#3473 feature: Modal action URLs
  packages/admin/resources/views/pages/actions/modal/actions/button-action.blade.php
  packages/forms/resources/views/components/actions/modal/actions/button-action.blade.php
  packages/support/src/Actions/Modal/Actions/Action.php
  packages/tables/resources/views/actions/modal/actions/button-action.blade.php
Labels: enhancement

#3458 Feature: enabled and disabled assertions for table actions
  packages/admin/.stubs.php
  packages/admin/src/Testing/TestsPageActions.php
  packages/tables/.stubs.php
  packages/tables/src/Testing/TestsActions.php
  packages/tables/src/Testing/TestsBulkActions.php
  tests/src/Admin/Fixtures/Pages/PageActions.php
  tests/src/Admin/Pages/ActionTest.php
  tests/src/Tables/ActionTest.php
  tests/src/Tables/BulkActionTest.php
  tests/src/Tables/Fixtures/PostsTable.php
Labels: enhancement

#3475 fix: Eagre load locales
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/date-time-picker.js
  packages/forms/resources/js/components/file-upload.js
  packages/forms/resources/lang/da/components.php
  packages/forms/resources/lang/fa/components.php
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/resources/views/components/file-upload.blade.php
Labels: bug

#3476 add note for Enum column in resource --generate
  packages/admin/docs/02-resources/01-getting-started.md
Labels: documentation

#3491 Added reorder_indicator for DE/German translation
  packages/tables/resources/lang/de/table.php
Labels: enhancement, i18n

#3485 Add support for custom table row classes based on the record
  packages/tables/docs/02-getting-started.md
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Concerns/HasRecordClasses.php
  packages/tables/src/Concerns/InteractsWithTable.php
  packages/tables/src/Table.php
Labels: enhancement

#3459 feature: make position of actions configurable
  packages/tables/docs/05-actions.md
  packages/tables/resources/views/components/actions-cell.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Actions/Position.php
  packages/tables/src/Concerns/HasActions.php
  packages/tables/src/Concerns/InteractsWithTable.php
  packages/tables/src/Table.php
Labels: enhancement

#3502 feature: Table row actions
  packages/admin/src/Resources/Pages/ListRecords.php
  packages/admin/src/Resources/RelationManagers/RelationManager.php
  packages/tables/resources/views/components/cell.blade.php
  packages/tables/resources/views/components/row.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Concerns/HasRecordAction.php
  packages/tables/src/Concerns/InteractsWithTable.php
  packages/tables/src/Table.php
Labels: enhancement

#3495 fix: Refactor hydration process
  packages/forms/src/Components/Concerns/BelongsToModel.php
  packages/forms/src/Components/Concerns/HasState.php
  packages/forms/src/Concerns/HasState.php
  tests/src/Forms/StateTest.php
Labels: bug

#3510 Add notifications package to bug report template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: chore

#3522 Fixed secondary button in dark mode
  packages/support/resources/views/components/button.blade.php
Labels: bug

#3524 fix: Save new BelongsTo relationship
  packages/forms/src/Components/Concerns/EntanglesStateWithSingularRelationship.php
Labels: bug

#3526 fix: RTL markdown wrapping
  packages/forms/resources/views/components/markdown-editor.blade.php
Labels: bug

#3535 fix: remove padding when sidebar is collapsed
  packages/admin/resources/views/components/layouts/app.blade.php
Labels: bug

#3537 add rtl support to cell button
  packages/tables/resources/views/components/cell.blade.php
Labels: i18n

#3541 Docs: Fix code in Advanced Navigation Customization section
  packages/admin/docs/05-navigation.md
Labels: bug, documentation

#3504 Adding further table and page action assertions
  packages/admin/.stubs.php
  packages/admin/src/Testing/TestsPageActions.php
  packages/tables/.stubs.php
  packages/tables/src/Testing/TestsActions.php
  tests/src/Admin/Fixtures/Pages/PageActions.php
  tests/src/Admin/Pages/ActionTest.php
  tests/src/Tables/ActionTest.php
  tests/src/Tables/Fixtures/PostsTable.php
Labels: enhancement

#3540 Allow Toggle Field to have different onColor & offColor
  packages/forms/docs/03-fields.md
  packages/forms/resources/views/components/toggle.blade.php
  packages/forms/src/Components/Toggle.php
Labels: enhancement

#3525 fix resetting tabs and wizard when closing modal
  packages/admin/resources/views/components/page.blade.php
  packages/forms/resources/views/components/actions/modal/index.blade.php
  packages/tables/resources/views/index.blade.php
Labels: bug

#3555 docs: Use `getUrl()` from resource for global search example.
  packages/admin/docs/02-resources/07-global-search.md
Labels: documentation, enhancement

#3562 fix: Select suffix action
  packages/forms/src/Components/Select.php
Labels: bug

#3547 Fix attach/associate action select translation
  packages/support/resources/lang/ar/actions/associate.php
  packages/support/resources/lang/ar/actions/attach.php
  packages/support/resources/lang/cs/actions/associate.php
  packages/support/resources/lang/cs/actions/attach.php
  packages/support/resources/lang/de/actions/associate.php
  packages/support/resources/lang/de/actions/attach.php
  packages/support/resources/lang/en/actions/associate.php
  packages/support/resources/lang/en/actions/attach.php
  packages/support/resources/lang/es/actions/associate.php
  packages/support/resources/lang/es/actions/attach.php
  packages/support/resources/lang/fa/actions/associate.php
  packages/support/resources/lang/fa/actions/attach.php
  packages/support/resources/lang/fr/actions/associate.php
  packages/support/resources/lang/fr/actions/attach.php
  packages/support/resources/lang/hi/actions/attach.php
  packages/support/resources/lang/hu/actions/associate.php
  packages/support/resources/lang/hu/actions/attach.php
  packages/support/resources/lang/hy/actions/associate.php
  packages/support/resources/lang/hy/actions/attach.php
  packages/support/resources/lang/id/actions/associate.php
  packages/support/resources/lang/id/actions/attach.php
  packages/support/resources/lang/it/actions/associate.php
  packages/support/resources/lang/it/actions/attach.php
  packages/support/resources/lang/ja/actions/associate.php
  packages/support/resources/lang/ja/actions/attach.php
  packages/support/resources/lang/kh/actions/attach.php
  packages/support/resources/lang/ko/actions/attach.php
  packages/support/resources/lang/ku/actions/attach.php
  packages/support/resources/lang/ms/actions/attach.php
  packages/support/resources/lang/my/actions/associate.php
  packages/support/resources/lang/my/actions/attach.php
  packages/support/resources/lang/nl/actions/associate.php
  packages/support/resources/lang/nl/actions/attach.php
  packages/support/resources/lang/pl/actions/associate.php
  packages/support/resources/lang/pl/actions/attach.php
  packages/support/resources/lang/pt_BR/actions/attach.php
  packages/support/resources/lang/pt_PT/actions/attach.php
  packages/support/resources/lang/ro/actions/associate.php
  packages/support/resources/lang/ro/actions/attach.php
  packages/support/resources/lang/ru/actions/associate.php
  packages/support/resources/lang/ru/actions/attach.php
  packages/support/resources/lang/sv/actions/associate.php
  packages/support/resources/lang/sv/actions/attach.php
  packages/support/resources/lang/tr/actions/associate.php
  packages/support/resources/lang/tr/actions/attach.php
  packages/support/resources/lang/uk/actions/associate.php
  packages/support/resources/lang/uk/actions/attach.php
  packages/support/resources/lang/vi/actions/associate.php
  packages/support/resources/lang/vi/actions/attach.php
  packages/support/resources/lang/zh_CN/actions/associate.php
  packages/support/resources/lang/zh_CN/actions/attach.php
  packages/support/resources/lang/zh_TW/actions/associate.php
  packages/support/resources/lang/zh_TW/actions/attach.php
Labels: bug

#3565 fix: Load state from existing relationships
  packages/forms/src/Components/Concerns/BelongsToModel.php
  packages/forms/src/Concerns/BelongsToModel.php
Labels: bug

#3564 update fa language
  packages/support/resources/lang/fa/actions/associate.php
  packages/support/resources/lang/fa/actions/attach.php
  packages/support/resources/lang/fa/actions/edit.php
Labels: i18n

#3563 fixes misunderstood fa translation.
  packages/admin/resources/lang/fa/resources/pages/create-record.php
Labels: i18n

#3572 Fixes missing ms translations.
  packages/forms/resources/lang/ms/components.php
  packages/spatie-laravel-settings-plugin/resources/lang/ms/pages/settings-page.php
  packages/support/resources/lang/ms/actions/associate.php
  packages/support/resources/lang/ms/actions/dissociate.php
  packages/support/resources/lang/ms/actions/force-delete.php
  packages/support/resources/lang/ms/actions/group.php
  packages/support/resources/lang/ms/actions/replicate.php
  packages/support/resources/lang/ms/actions/restore.php
  packages/support/resources/lang/ms/actions/view.php
  packages/support/resources/lang/ms/components/button.php
  packages/tables/resources/lang/ms/table.php
Labels: enhancement, i18n

#3571 `break-words` for markdown editor preview
  packages/forms/resources/views/components/markdown-editor.blade.php
Labels: enhancement

#3553 Improve notifications transition implementation
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/resources/views/components/layouts/app.blade.php
  packages/forms/dist/module.esm.js
  packages/notifications/dist/module.esm.js
  packages/notifications/resources/js/components/notification.js
  packages/notifications/resources/views/components/notification.blade.php
  packages/notifications/src/Http/Livewire/Notifications.php
Labels: enhancement

#3579 Set up Prettier
  .editorconfig
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/fix-code-style.yml
  .github/workflows/manage-issue.yml
  .github/workflows/monorepo-split.yml
  .github/workflows/npm-build.yml
  .github/workflows/phpstan.yml
  .github/workflows/pint.yml
  .github/workflows/tests.yml
  .prettierrc
  package-lock.json
  package.json
  packages/admin/resources/js/app.js
  packages/forms/resources/css/components/color-picker.css
  packages/forms/resources/css/components/select.css
  packages/forms/resources/js/components/color-picker.js
  packages/forms/resources/js/components/date-time-picker.js
  packages/forms/resources/js/components/file-upload.js
  packages/forms/resources/js/components/key-value.js
  packages/forms/resources/js/components/markdown-editor.js
  packages/forms/resources/js/components/rich-editor.js
  packages/forms/resources/js/components/select.js
  packages/forms/resources/js/components/tags-input.js
  packages/forms/resources/js/components/text-input.js
  packages/forms/resources/js/components/textarea.js
  packages/forms/resources/js/sortable.js
  packages/forms/stubs/scaffolding/tailwind.config.js
  packages/forms/stubs/scaffolding/vite.config.js
  packages/notifications/resources/js/components/notification.js
  packages/notifications/stubs/scaffolding/tailwind.config.js
  packages/notifications/stubs/scaffolding/vite.config.js
  packages/tables/stubs/scaffolding/tailwind.config.js
  packages/tables/stubs/scaffolding/vite.config.js
  tests/src/Notifications/NotificationTest.php
  webpack.mix.js
Labels: chore, code quality

#3584 Simplify contributing instructions
  README.md
Labels: chore

#3587 fix: Null record action
  packages/admin/src/Pages/Actions/CreateAction.php
  packages/admin/src/Pages/Concerns/HasActions.php
Labels: bug

#3589 fix: non-centered modal subheadings
  packages/admin/resources/views/components/page.blade.php
  packages/forms/resources/views/components/actions/modal/index.blade.php
  packages/tables/resources/views/index.blade.php
Labels: bug

#3590 feature: Modify select options query
  packages/tables/src/Actions/AssociateAction.php
  packages/tables/src/Actions/AttachAction.php
Labels: enhancement

#3444 Fix link icon
  packages/support/resources/views/components/button.blade.php
  packages/support/resources/views/components/link.blade.php
Labels: bug

#3544 Feature: `TagsInput` Handle paste
  packages/forms/resources/views/components/tags-input.blade.php
Labels: enhancement

#3580 Adding table bulk assertions for icon, label and color
  packages/tables/.stubs.php
  packages/tables/src/Testing/TestsBulkActions.php
  tests/src/Tables/BulkActionTest.php
  tests/src/Tables/Fixtures/PostsTable.php
Labels: enhancement

#3592 fix: Excessive table action queries
  packages/tables/src/Concerns/HasRecords.php
Labels: bug

#3593 fix: Revert file upload
  packages/forms/src/Components/BaseFileUpload.php
Labels: bug

#3595 Update Spanish translation
  packages/forms/resources/lang/es/components.php
  packages/tables/resources/lang/es/table.php
Labels: enhancement, i18n

#3545 add relation support to spatie media library table column
  packages/spatie-laravel-media-library-plugin/src/Tables/Columns/SpatieMediaLibraryImageColumn.php
  packages/spatie-laravel-tags-plugin/src/Tables/Columns/SpatieTagsColumn.php
Labels: enhancement

#3598 feature: Reorderable KeyValue
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.js
  packages/forms/docs/03-fields.md
  packages/forms/resources/js/components/key-value.js
  packages/forms/resources/js/index.js
  packages/forms/resources/js/sortable.js
  packages/forms/resources/views/components/key-value.blade.php
  packages/forms/src/Components/KeyValue.php
Labels: enhancement

#3602 chore: General UI tweaks based on @LarsKlopstra feedback
  packages/admin/resources/lang/en/resources/pages/edit-record.php
  packages/admin/resources/views/components/layouts/app.blade.php
  packages/spatie-laravel-settings-plugin/resources/lang/en/pages/settings-page.php
  packages/support/resources/lang/en/actions/edit.php
Labels: ui, chore

#3603 feature: Custom max width class
  packages/admin/resources/views/components/layouts/app.blade.php
Labels: enhancement

#3600 feature: Table content polling
  packages/admin/docs/02-resources/02-listing-records.md
  packages/admin/src/Resources/Pages/ListRecords.php
  packages/admin/src/Resources/RelationManagers/RelationManager.php
  packages/admin/src/Resources/Table.php
  packages/tables/docs/02-getting-started.md
  packages/tables/resources/views/components/table.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Concerns/CanPollRecords.php
  packages/tables/src/Concerns/InteractsWithTable.php
  packages/tables/src/Table.php
Labels: enhancement

#3604 fix broken tabbing navigation in modal
  packages/support/resources/views/components/modal/index.blade.php
Labels: bug

#3616 chore: tables performance
  composer.json
  composer.lock
  packages/admin/.gitignore
  packages/admin/composer.lock
  packages/admin/src/Resources/Pages/ListRecords.php
  packages/admin/src/Resources/RelationManagers/RelationManager.php
  packages/forms/.gitignore
  packages/forms/composer.lock
  packages/notifications/.gitignore
  packages/notifications/composer.lock
  packages/spatie-laravel-media-library-plugin/.gitignore
  packages/spatie-laravel-media-library-plugin/composer.lock
  packages/spatie-laravel-settings-plugin/.gitignore
  packages/spatie-laravel-settings-plugin/composer.lock
  packages/spatie-laravel-tags-plugin/.gitignore
  packages/spatie-laravel-tags-plugin/composer.lock
  packages/spatie-laravel-translatable-plugin/.gitignore
  packages/spatie-laravel-translatable-plugin/composer.lock
  packages/support/.gitignore
  packages/support/composer.lock
  packages/tables/.gitignore
  packages/tables/composer.json
  packages/tables/composer.lock
  packages/tables/src/Concerns/CanToggleColumns.php
  packages/tables/src/Concerns/InteractsWithTable.php
  packages/tables/src/Table.php
Labels: chore

#3610 Improve documentation on publishing translations
  packages/admin/docs/01-installation.md
  packages/forms/docs/01-installation.md
  packages/tables/docs/01-installation.md
Labels: documentation, enhancement

#3599 feature: Filter indicators
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/mix-manifest.json
  packages/forms/src/Components/Concerns/HasState.php
  packages/tables/docs/04-filters.md
  packages/tables/resources/lang/en/table.php
  packages/tables/resources/views/components/filters/index.blade.php
  packages/tables/resources/views/components/filters/indicators.blade.php
  packages/tables/resources/views/components/reorder/indicator.blade.php
  packages/tables/resources/views/components/selection-indicator.blade.php
  packages/tables/resources/views/components/table.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Concerns/HasFilters.php
  packages/tables/src/Filters/BaseFilter.php
  packages/tables/src/Filters/Concerns/BelongsToTable.php
  packages/tables/src/Filters/Concerns/HasIndicators.php
  packages/tables/src/Filters/Filter.php
  packages/tables/src/Filters/MultiSelectFilter.php
  packages/tables/src/Filters/SelectFilter.php
  packages/tables/src/Filters/TernaryFilter.php
Labels: enhancement

#3617 Prevent lazy and debounce modifiers on entangled fields
  packages/forms/resources/views/components/text-input.blade.php
  packages/forms/src/Concerns/HasStateBindingModifiers.php
Labels: bug

#3623 add missing nl table translations
  packages/tables/resources/lang/nl/table.php
Labels: enhancement, i18n

#3624 Table : update French translation
  packages/tables/resources/lang/fr/table.php
Labels: enhancement, i18n

#3622 Add 'id' translation: filter indicator
  packages/tables/resources/lang/id/table.php
Labels: enhancement, i18n

#3626 Sort Prettier rules
  .prettierrc
Labels: chore

#3634 Added ms translation for filter indicators.
  packages/tables/resources/lang/ms/table.php
Labels: enhancement, i18n

#3631 Make collapsible repeater headers clickable
  packages/forms/resources/views/components/repeater.blade.php
Labels: enhancement, i18n

#3639 Table filter indicator ar translation,RTL fix
  packages/tables/resources/lang/ar/table.php
  packages/tables/resources/views/components/filters/indicators.blade.php
Labels: i18n

#3644 Improve vi translations
  packages/admin/resources/lang/vi/resources/pages/edit-record.php
  packages/support/resources/lang/vi/actions/create.php
  packages/support/resources/lang/vi/actions/delete.php
  packages/support/resources/lang/vi/actions/edit.php
  packages/support/resources/lang/vi/actions/force-delete.php
  packages/support/resources/lang/vi/actions/restore.php
  packages/tables/resources/lang/vi/table.php
Labels: enhancement, i18n

#3646 fix translation
  packages/tables/resources/lang/nl/table.php
Labels: enhancement, i18n

#3645 Improve vi translations
  packages/forms/resources/lang/vi/components.php
Labels: enhancement, i18n

#3640 Removed extraneous close div
  packages/admin/resources/views/components/layouts/app.blade.php
Labels: bug

#3649 Fix wire:ignore fields: Change border colors, and expand Sections on validation errors
  packages/forms/resources/views/components/markdown-editor.blade.php
  packages/forms/resources/views/components/rich-editor.blade.php
  packages/forms/resources/views/components/section.blade.php
  packages/forms/resources/views/components/text-input.blade.php
Labels: bug

#3651 Italian translations update
  packages/admin/resources/lang/it/layout.php
  packages/forms/resources/lang/it/components.php
  packages/support/resources/lang/it/actions/force-delete.php
  packages/support/resources/lang/it/actions/group.php
  packages/support/resources/lang/it/actions/restore.php
  packages/tables/resources/lang/it/table.php
Labels: i18n

#3659 Add documentation for the Form Wizard startOnStep() method
  packages/forms/docs/04-layout.md
Labels: documentation

#3669 fix: Removing filters with default values
  packages/tables/resources/lang/en/table.php
  packages/tables/resources/views/components/filters/indicators.blade.php
  packages/tables/src/Concerns/HasFilters.php
Labels: bug

#3664 chore(lang): update pl translations
  packages/forms/resources/lang/pl/components.php
  packages/tables/resources/lang/pl/table.php
Labels: i18n

#3670 fix: Image column classes
  packages/tables/resources/views/columns/image-column.blade.php
Labels: bug

#3633 Add table actions column label helper
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Concerns/HasActions.php
  packages/tables/src/Table.php
Labels: enhancement

#3663 Swap filter trigger and column toggle icons position
  packages/tables/resources/views/index.blade.php
Labels: enhancement

#3675 fix visibility notification
  packages/notifications/resources/js/components/notification.js
Labels: bug

#3679 Fixes example snippets in RM docs.
  packages/admin/docs/02-resources/06-relation-managers.md
Labels: bug, documentation

#3678 Fix getFlatComponents doesn't return all hidden components
  packages/forms/src/Concerns/HasComponents.php
  tests/src/Forms/ComponentContainerTest.php
Labels: bug

#3680 Fixes ms translation.
  packages/tables/resources/lang/ms/table.php
Labels: i18n

#3682 Feat: multi field based validations
  packages/forms/docs/05-validation.md
  packages/forms/src/Components/Concerns/CanBeValidated.php
Labels: enhancement

#3683 fix: Lazily entangled modifiers
  packages/forms/resources/views/components/text-input.blade.php
  packages/forms/src/Concerns/HasStateBindingModifiers.php
Labels: bug

#3685 fix: `multiFieldComparisonRule` handle spaces in $statePaths
  packages/forms/src/Components/Concerns/CanBeValidated.php
Labels: bug

#3684 Fix issue to remove table filters.
  packages/forms/src/Concerns/HasComponents.php
  packages/tables/src/Concerns/HasFilters.php
  tests/src/Forms/ComponentContainerTest.php
Labels: bug

#3688 Fix CSS class on edit page
  packages/admin/resources/views/resources/pages/edit-record.blade.php
Labels: bug

#3691 support debounce on masked text-input
  packages/forms/resources/views/components/text-input.blade.php
  packages/forms/src/Concerns/HasStateBindingModifiers.php
Labels: enhancement

#3693 fix: Showing multiple notifications
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.js
  packages/notifications/dist/module.esm.js
  packages/notifications/resources/js/components/notification.js
  packages/notifications/resources/views/components/notification.blade.php
Labels: bug

#3696 Added missing value
  packages/tables/resources/lang/es/table.php
Labels: i18n

#3666 Feature/per page all option
  packages/tables/config/tables.php
  packages/tables/resources/lang/ar/table.php
  packages/tables/resources/lang/en/table.php
  packages/tables/resources/lang/nl/table.php
  packages/tables/resources/views/components/pagination/records-per-page-selector.blade.php
  packages/tables/src/Concerns/CanPaginateRecords.php
Labels: enhancement

#3701 Fixed empty check on filter indication
  packages/tables/src/Filters/MultiSelectFilter.php
  packages/tables/src/Filters/SelectFilter.php
Labels: bug

#3699 change whitespace to nowrap instead of normal
  packages/tables/resources/views/columns/badge-column.blade.php
Labels: ui

#3706 Update German/DE translations
  packages/admin/resources/lang/de/layout.php
  packages/admin/resources/lang/de/login.php
  packages/forms/resources/lang/de/components.php
  packages/spatie-laravel-settings-plugin/resources/lang/de/pages/settings-page.php
  packages/spatie-laravel-translatable-plugin/resources/lang/de/actions.php
  packages/support/resources/lang/de/actions/attach.php
  packages/support/resources/lang/de/actions/create.php
  packages/support/resources/lang/de/actions/delete.php
  packages/support/resources/lang/de/actions/detach.php
  packages/support/resources/lang/de/actions/edit.php
  packages/support/resources/lang/de/actions/modal.php
  packages/tables/resources/lang/de/table.php
Labels: enhancement, i18n

#3712 Fix: Load registered stylesheets after Filament theme
  packages/admin/resources/views/components/layouts/base.blade.php
Labels: bug

#3715 chore(lang): update pl translations
  packages/tables/resources/lang/pl/table.php
Labels: enhancement, i18n

#3716 Added Japanese translation
  packages/support/resources/lang/ja/actions/attach.php
Labels: enhancement, i18n

#3718 update ja translations
  packages/support/resources/lang/ja/actions/dissociate.php
Labels: enhancement, i18n

#3717 update ja translations
  packages/support/resources/lang/ja/actions/detach.php
Labels: enhancement, i18n

#3719 Support Turbo navigation
  packages/admin/resources/views/components/layouts/app/sidebar/index.blade.php
Labels: enhancement

#3714 fix: Notifications js directive
  composer.lock
  packages/admin/composer.json
  packages/forms/composer.json
  packages/notifications/composer.json
  packages/tables/composer.json
Labels: bug

#3720 Show loading state when sorting table
  packages/tables/src/Table.php
Labels: enhancement

#3709 Check for hidden when counting bulk actions in isTableSelectionEnabled
  packages/tables/src/Concerns/CanSelectRecords.php
Labels: bug

#3711 Filters below table content
  packages/admin/docs/02-resources/02-listing-records.md
  packages/tables/docs/04-filters.md
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Concerns/HasFilters.php
  packages/tables/src/Filters/Layout.php
Labels: enhancement

#3698 feature: Add some form testing helpers
  packages/forms/.stubs.php
  packages/forms/docs/07-testing.md
  packages/forms/src/FormsServiceProvider.php
  packages/forms/src/Testing/TestsForms.php
  tests/resources/views/forms/fixtures/form.blade.php
  tests/src/Forms/FormsTest.php
Labels: enhancement

#3738 Table spanish translations
  packages/tables/resources/lang/es/table.php
Labels: enhancement, i18n

#3732 Add class to tab buttons
  packages/forms/resources/views/components/tabs.blade.php
Labels: enhancement

#3739 Improve translateLabel() coverage
  packages/forms/src/Components/Field.php
  packages/support/src/Actions/ActionGroup.php
Labels: bug

#3746 Add missing pt_BR translations
  packages/forms/resources/lang/pt_BR/components.php
  packages/spatie-laravel-translatable-plugin/resources/lang/pt_BR/actions.php
  packages/support/resources/lang/pt_BR/actions/associate.php
  packages/support/resources/lang/pt_BR/actions/dissociate.php
  packages/support/resources/lang/pt_BR/actions/force-delete.php
  packages/support/resources/lang/pt_BR/actions/replicate.php
  packages/support/resources/lang/pt_BR/actions/restore.php
  packages/support/resources/lang/pt_BR/actions/view.php
  packages/support/resources/lang/pt_BR/components/button.php
  packages/tables/resources/lang/pt_BR/table.php
Labels: enhancement, i18n
