Repository filamentphp/filament, pull requests merged in 2022-05, with the labels that each got.

#2253 refactor: move `HasExtraXAttributes` concerns into support package
  packages/forms/src/Components/ColorPicker.php
  packages/forms/src/Components/Component.php
  packages/forms/src/Components/Concerns/HasExtraAlpineAttributes.php
  packages/forms/src/Components/Concerns/HasExtraAttributes.php
  packages/forms/src/Components/DateTimePicker.php
  packages/forms/src/Components/FileUpload.php
  packages/forms/src/Components/KeyValue.php
  packages/forms/src/Components/MarkdownEditor.php
  packages/forms/src/Components/MultiSelect.php
  packages/forms/src/Components/RichEditor.php
  packages/forms/src/Components/Section.php
  packages/forms/src/Components/Select.php
  packages/forms/src/Components/Tabs.php
  packages/forms/src/Components/TagsInput.php
  packages/forms/src/Components/TextInput.php
  packages/forms/src/Components/Textarea.php
  packages/forms/src/Components/Toggle.php
  packages/support/src/Concerns/HasExtraAlpineAttributes.php
  packages/support/src/Concerns/HasExtraAttributes.php
  packages/tables/src/Columns/Column.php
  packages/tables/src/Columns/Concerns/HasExtraAttributes.php
Labels: chore

#2274 feature: support calling `hidden()`/`visible()` with FQN class name
  packages/admin/docs/02-resources.md
  packages/forms/src/Components/Concerns/CanBeHidden.php
Labels: enhancement

#2290 Updates Akaunting dependency.
  composer.json
  composer.lock
  packages/tables/composer.json
  packages/tables/composer.lock
Labels: enhancement

#2289 feat: Glassy Auth
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/admin/dist/module.esm.js
  packages/admin/resources/css/app.css
  packages/admin/resources/views/login.blade.php
  packages/forms/dist/module.esm.js
Labels: enhancement

#2257 Feature: Show filters on top of the table
  packages/tables/docs/04-filters.md
  packages/tables/resources/views/components/filters/index.blade.php
  packages/tables/resources/views/components/filters/popover.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Concerns/HasFilters.php
  packages/tables/src/Concerns/InteractsWithTable.php
  packages/tables/src/Filters/Layout.php
  packages/tables/src/Table.php
Labels: enhancement

#2297 feature: Custom table content
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Concerns/HasContent.php
  packages/tables/src/Concerns/InteractsWithTable.php
  packages/tables/src/Table.php
Labels: enhancement

#2300 fix: Anonymous column sort
  packages/tables/src/Concerns/CanSortRecords.php
Labels: bug

#2302 Fix issue with id not being prefixed
  packages/tables/src/Filters/Concerns/HasRelationship.php
Labels: bug

#2310 fix: Make resource ResourceResource
  packages/admin/src/Commands/MakeResourceCommand.php
Labels: bug

#2314 fix: Dynamic min/max date picker
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/admin/dist/module.esm.js
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/date-time-picker.js
  packages/forms/resources/views/components/date-time-picker.blade.php
Labels: bug

#2320 fix: Focus concealed components when validation error occurs
  packages/forms/resources/views/components/checkbox.blade.php
  packages/forms/resources/views/components/color-picker.blade.php
  packages/forms/resources/views/components/markdown-editor.blade.php
  packages/forms/resources/views/components/select.blade.php
  packages/forms/resources/views/components/text-input.blade.php
  packages/forms/resources/views/components/textarea.blade.php
  packages/forms/src/Components/Concerns/CanBeConcealed.php
  packages/forms/src/Components/Contracts/CanConcealComponents.php
  packages/forms/src/Components/Section.php
  packages/forms/src/Components/Tabs/Tab.php
Labels: bug

#2322 fix: Filters offscreen with toggleable columns
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/admin/dist/module.esm.js
  packages/forms/dist/module.esm.js
  packages/tables/resources/views/components/toggleable/index.blade.php
  packages/tables/resources/views/index.blade.php
Labels: bug, ui

#2334 fix: File upload loading indicator with prefilled files
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/admin/docs/02-resources/01-getting-started.md
  packages/admin/docs/02-resources/02-forms.md
  packages/admin/docs/11-resources2.md
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/file-upload.js
  packages/support/resources/views/components/button.blade.php
  packages/support/resources/views/components/loading-indicator.blade.php
  packages/tables/resources/views/components/selection-indicator.blade.php
Labels: bug

#2340 fix: Submit button after uploading more files
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/file-upload.js
Labels: bug

#2341 fix: Duplicate notifications
  packages/admin/resources/views/components/notification-manager.blade.php
  packages/admin/src/NotificationManager.php
  tests/src/Admin/Fixtures/Pages/Settings.php
  tests/src/Admin/NotificationManager/NotificationManagerTest.php
Labels: bug

#2346 Update select component to work with BelongsToMany
  packages/forms/src/Components/Select.php
Labels: bug

#2349 Raise z-index for select dropdown
  packages/forms/resources/css/components/select.css
Labels: bug, ui

#2351 fix: File upload temporary urls
  packages/forms/src/Components/BaseFileUpload.php
  packages/forms/src/Components/Concerns/HasFileAttachments.php
  packages/spatie-laravel-media-library-plugin/src/Forms/Components/SpatieMediaLibraryFileUpload.php
  packages/tables/src/Columns/ImageColumn.php
Labels: bug

#2354 feature: Translatable relationship fields
  packages/forms/src/Components/Concerns/EntanglesStateWithSingularRelationship.php
  packages/forms/src/Components/Contracts/CanEntangleWithSingularRelationships.php
  packages/forms/src/Components/Field.php
  packages/forms/src/Components/RelationshipRepeater.php
  packages/forms/src/Concerns/HasState.php
  packages/forms/src/Concerns/InteractsWithForms.php
  packages/forms/src/Contracts/HasForms.php
  packages/spatie-laravel-translatable-plugin/src/Resources/Pages/Concerns/HasActiveFormLocaleSelect.php
  packages/spatie-laravel-translatable-plugin/src/Resources/Pages/ListRecords/Concerns/Translatable.php
  packages/tables/src/Columns/Concerns/InteractsWithTableQuery.php
  packages/tables/src/Concerns/InteractsWithTable.php
  packages/tables/src/Contracts/HasTable.php
Labels: enhancement

#2362 fix: add space-x-reverse class for RTL
  packages/forms/dist/module.esm.css
  packages/forms/resources/css/components/select.css
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/field-wrapper/inline.blade.php
  packages/forms/resources/views/components/repeater.blade.php
  packages/forms/resources/views/components/select.blade.php
  packages/tables/resources/views/columns/badge-column.blade.php
Labels: bug, ui, i18n

#2355 add toggle to Filter
  packages/tables/docs/04-filters.md
  packages/tables/src/Concerns/HasFilters.php
  packages/tables/src/Filters/BaseFilter.php
  packages/tables/src/Filters/Filter.php
  packages/tables/src/Filters/MultiSelectFilter.php
  packages/tables/src/Filters/SelectFilter.php
Labels: enhancement

#2368 Add view record to Simple (modal ) Resources
  packages/admin/resources/lang/en/resources/pages/list-records.php
  packages/admin/src/Resources/Form.php
  packages/admin/src/Resources/Pages/Concerns/UsesResourceForm.php
  packages/admin/src/Resources/Pages/ListRecords/Concerns/CanViewRecords.php
Labels: enhancement

#2370 fix app layout scrollbar
  packages/admin/resources/views/components/layouts/app.blade.php
Labels: bug, ui

#2373 Fix French Translations
  packages/admin/resources/lang/fr/resources/pages/list-records.php
Labels: i18n

#2376 FA translation update after v2.12
  packages/admin/resources/lang/fa/resources/pages/edit-record.php
  packages/admin/resources/lang/fa/resources/pages/list-records.php
  packages/admin/resources/lang/fa/resources/relation-managers/attach.php
  packages/admin/resources/lang/fa/resources/relation-managers/delete.php
  packages/admin/resources/lang/fa/resources/relation-managers/detach.php
  packages/admin/resources/lang/fa/resources/relation-managers/dissociate.php
  packages/forms/resources/lang/fa/components.php
  packages/spatie-laravel-settings-plugin/resources/lang/fa/pages/settings-page.php
  packages/spatie-laravel-translatable-plugin/resources/lang/fa/actions.php
  packages/support/resources/lang/fa/components/button.php
  packages/support/resources/lang/fa/components/icon-button.php
  packages/support/resources/lang/fa/components/link.php
  packages/tables/resources/lang/fa/table.php
Labels: i18n

#2378 add missing Arabic translation phrases
  packages/support/resources/lang/ar/components/button.php
  packages/support/resources/lang/ar/components/icon-button.php
  packages/support/resources/lang/ar/components/link.php
Labels: i18n

#2336 fix: update pl translation for v2.12
  packages/admin/resources/lang/pl/login.php
  packages/admin/resources/lang/pl/pages/dashboard.php
  packages/admin/resources/lang/pl/resources/pages/create-record.php
  packages/admin/resources/lang/pl/resources/pages/edit-record.php
  packages/admin/resources/lang/pl/resources/pages/list-records.php
  packages/admin/resources/lang/pl/resources/relation-managers/associate.php
  packages/admin/resources/lang/pl/resources/relation-managers/attach.php
  packages/admin/resources/lang/pl/resources/relation-managers/create.php
  packages/admin/resources/lang/pl/resources/relation-managers/dissociate.php
  packages/admin/resources/lang/pl/resources/relation-managers/edit.php
  packages/forms/resources/lang/pl/components.php
  packages/support/resources/lang/pl/components/button.php
  packages/support/resources/lang/pl/components/icon-button.php
  packages/support/resources/lang/pl/components/link.php
  packages/tables/resources/lang/pl/table.php
Labels: enhancement, i18n

#2384 fix: Disable select create option
  packages/admin/src/Pages/Actions/Action.php
  packages/forms/resources/views/components/color-picker.blade.php
  packages/forms/resources/views/components/select.blade.php
  packages/forms/resources/views/components/text-input.blade.php
  packages/forms/src/Components/Select.php
  packages/support/src/Actions/Action.php
  packages/support/src/Actions/BaseAction.php
  packages/support/src/Actions/Concerns/CanBeDisabled.php
Labels: bug

#2385 fix: Action translations
  packages/forms/resources/lang/en/components.php
  packages/forms/resources/lang/fa/components.php
  packages/forms/resources/lang/pl/components.php
  packages/support/resources/lang/ar/actions.php
  packages/support/resources/lang/cs/actions.php
  packages/support/resources/lang/de/actions.php
  packages/support/resources/lang/en/actions.php
  packages/support/resources/lang/es/actions.php
  packages/support/resources/lang/fa/actions.php
  packages/support/resources/lang/fr/actions.php
  packages/support/resources/lang/hi/actions.php
  packages/support/resources/lang/id/actions.php
  packages/support/resources/lang/it/actions.php
  packages/support/resources/lang/ja/actions.php
  packages/support/resources/lang/kh/actions.php
  packages/support/resources/lang/ko/actions.php
  packages/support/resources/lang/ku/actions.php
  packages/support/resources/lang/ms/actions.php
  packages/support/resources/lang/my/actions.php
  packages/support/resources/lang/nl/actions.php
  packages/support/resources/lang/pl/actions.php
  packages/support/resources/lang/pt_BR/actions.php
  packages/support/resources/lang/pt_PT/actions.php
  packages/support/resources/lang/ru/actions.php
  packages/support/resources/lang/sv/actions.php
  packages/support/resources/lang/tr/actions.php
  packages/support/resources/lang/vi/actions.php
  packages/support/resources/lang/zh_CN/actions.php
  packages/support/src/Actions/Concerns/CanOpenModal.php
  packages/tables/resources/lang/ar/table.php
  packages/tables/resources/lang/ca/table.php
  packages/tables/resources/lang/cs/table.php
  packages/tables/resources/lang/da/table.php
  packages/tables/resources/lang/de/table.php
  packages/tables/resources/lang/en/table.php
  packages/tables/resources/lang/es/table.php
  packages/tables/resources/lang/fa/table.php
  packages/tables/resources/lang/fr/table.php
  packages/tables/resources/lang/hi/table.php
  packages/tables/resources/lang/id/table.php
  packages/tables/resources/lang/it/table.php
  packages/tables/resources/lang/ja/table.php
  packages/tables/resources/lang/ka/table.php
  packages/tables/resources/lang/ku/table.php
  packages/tables/resources/lang/ms/table.php
  packages/tables/resources/lang/nl/table.php
  packages/tables/resources/lang/pl/table.php
  packages/tables/resources/lang/pt_BR/table.php
  packages/tables/resources/lang/pt_PT/table.php
  packages/tables/resources/lang/ru/table.php
  packages/tables/resources/lang/sv/table.php
  packages/tables/resources/lang/tr/table.php
  packages/tables/resources/lang/vi/table.php
  packages/tables/resources/lang/zh_CN/table.php
Labels: bug, i18n

#2387 feature: get/set relative path
  packages/forms/src/Components/Concerns/HasState.php
Labels: enhancement

#2391 fix: missed labels from PR #2385
  packages/admin/src/Resources/Pages/ListRecords/Concerns/CanCreateRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanAssociateRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanAttachRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanCreateRecords.php
Labels: bug

#2375 fix modal component taking empty space
  packages/admin/resources/views/components/dropdown/item.blade.php
  packages/admin/resources/views/components/modal/index.blade.php
  packages/forms/resources/views/components/dropdown/item.blade.php
  packages/forms/resources/views/components/modal/index.blade.php
  packages/tables/resources/views/components/dropdown/item.blade.php
  packages/tables/resources/views/components/modal/index.blade.php
Labels: bug

#2392 fix: [forms] block builder when block non-existant
  packages/forms/src/Components/Builder.php
Labels: bug

#2403 [ar] Update translations - Translate new phrases - Revert missing phrase
  packages/admin/resources/lang/ar/resources/pages/list-records.php
  packages/forms/resources/lang/ar/components.php
  packages/tables/resources/lang/ar/table.php
Labels: i18n

#2408 Add missing FR translations for forms and tables
  packages/forms/resources/lang/fr/components.php
  packages/tables/resources/lang/fr/table.php
Labels: i18n

#2415 fix: Modal form action alignment
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/mix-manifest.json
  packages/admin/resources/views/components/modal/actions.blade.php
  packages/admin/resources/views/components/pages/actions/index.blade.php
  packages/admin/src/Http/Middleware/MirrorConfigToSubpackages.php
  packages/forms/config/forms.php
  packages/forms/resources/views/components/modal/actions.blade.php
  packages/support/resources/views/components/modal/actions.blade.php
  packages/tables/config/tables.php
  packages/tables/docs/05-actions.md
  packages/tables/resources/views/components/actions-cell.blade.php
  packages/tables/resources/views/components/modal/actions.blade.php
Labels: bug

#2410 fix: Cache form component action form
  packages/admin/src/Pages/Concerns/HasActions.php
  packages/forms/src/Concerns/HasFormComponentActions.php
  packages/forms/src/Concerns/InteractsWithForms.php
  packages/tables/src/Concerns/CanToggleColumns.php
  packages/tables/src/Concerns/HasActions.php
  packages/tables/src/Concerns/HasBulkActions.php
  packages/tables/src/Concerns/HasFilters.php
  packages/tables/src/Concerns/InteractsWithTable.php
  packages/tables/src/Contracts/HasTable.php
  packages/tables/src/Table.php
Labels: bug

#2377 fix: Duplicate BelongsToMany pivot records
  packages/admin/docs/02-resources.md
  packages/admin/src/Resources/RelationManagers/BelongsToManyRelationManager.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanAssociateRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanAttachRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanDetachRecords.php
  packages/admin/src/Resources/RelationManagers/RelationManager.php
  packages/forms/src/Components/BelongsToSelect.php
  packages/tables/resources/views/components/actions/action.blade.php
  packages/tables/resources/views/components/cell.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Concerns/HasRecords.php
  packages/tables/src/Contracts/HasTable.php
Labels: bug

#2439 Add NL translated searching message to components.php
  packages/forms/resources/lang/nl/components.php
Labels: i18n

#2443 Added missing Spanish translations
  packages/admin/resources/lang/es/resources/pages/list-records.php
  packages/forms/resources/lang/es/components.php
  packages/support/resources/lang/es/components/button.php
  packages/support/resources/lang/es/components/icon-button.php
  packages/support/resources/lang/es/components/link.php
  packages/tables/resources/lang/es/table.php
Labels: enhancement

#2451 Initial/anonymize name passed to ui-avatars
  packages/admin/src/AvatarProviders/UiAvatarsProvider.php
Labels: enhancement

#2456 New render hook before and after main content
  packages/admin/docs/07-appearance.md
  packages/admin/resources/views/components/layouts/app.blade.php
Labels: enhancement

#2432 feature: Wizard component
  packages/admin/docs/02-resources.md
  packages/admin/resources/views/components/page.blade.php
  packages/admin/src/Resources/Form.php
  packages/admin/src/Resources/Pages/Concerns/HasWizard.php
  packages/admin/src/Resources/Pages/Concerns/UsesResourceForm.php
  packages/admin/src/Resources/Pages/CreateRecord.php
  packages/admin/src/Resources/Pages/CreateRecord/Concerns/HasWizard.php
  packages/admin/src/Resources/Pages/EditRecord.php
  packages/admin/src/Resources/Pages/EditRecord/Concerns/HasWizard.php
  packages/admin/src/Resources/Pages/ListRecords/Concerns/CanCreateRecords.php
  packages/admin/src/Resources/Pages/ListRecords/Concerns/CanViewRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanAssociateRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanAttachRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanCreateRecords.php
  packages/admin/src/Widgets/StatsOverviewWidget/Card.php
  packages/forms/docs/04-layout.md
  packages/forms/resources/lang/en/components.php
  packages/forms/resources/views/components/actions/modal/index.blade.php
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/repeater.blade.php
  packages/forms/resources/views/components/tabs.blade.php
  packages/forms/resources/views/components/wizard.blade.php
  packages/forms/resources/views/components/wizard/step.blade.php
  packages/forms/src/Components/Builder/Block.php
  packages/forms/src/Components/Concerns/HasLabel.php
  packages/forms/src/Components/Field.php
  packages/forms/src/Components/Placeholder.php
  packages/forms/src/Components/Section.php
  packages/forms/src/Components/Select.php
  packages/forms/src/Components/Tabs.php
  packages/forms/src/Components/Tabs/Tab.php
  packages/forms/src/Components/Wizard.php
  packages/forms/src/Components/Wizard/Step.php
  packages/forms/src/Concerns/HasColumns.php
  packages/support/resources/views/components/button.blade.php
  packages/support/src/Actions/Action.php
  packages/support/src/Actions/Concerns/CanOpenModal.php
  packages/support/src/Actions/Concerns/HasFormSchema.php
  packages/support/src/Actions/Concerns/HasWizard.php
  packages/tables/docs/05-actions.md
  packages/tables/resources/views/index.blade.php
Labels: enhancement

#2453 fix: disable filepond transform
  packages/forms/resources/js/components/file-upload.js
  packages/forms/resources/views/components/file-upload.blade.php
Labels: bug

#2467 Feature: add `extraAttributes` to StatsOverView Widget Card
  packages/admin/resources/views/components/stats/card.blade.php
  packages/admin/resources/views/widgets/stats-overview-widget/card.blade.php
  packages/admin/src/Widgets/StatsOverviewWidget/Card.php
Labels: enhancement

#2469 Adds support for `extraImgAttributes()` on ImageColumn
  packages/tables/resources/views/columns/image-column.blade.php
  packages/tables/src/Columns/ImageColumn.php
Labels: enhancement

#2481 Update dutch translations for form components
  packages/forms/resources/lang/nl/components.php
Labels: i18n

#2484 Tables Textcolumn : add since() format capacity
  packages/tables/src/Columns/Concerns/CanFormatState.php
Labels: enhancement

#2483 [2.X] Add Limit to property
  packages/tables/src/Columns/Concerns/CanFormatState.php
Labels: enhancement

#2477 fix: Filling null repeater values
  packages/forms/src/Components/Concerns/HasState.php
  packages/forms/src/Concerns/HasState.php
  tests/src/Forms/StateTest.php
Labels: bug

#2486 Add support to HasOneThrough in filters
  packages/tables/src/Filters/Concerns/HasRelationship.php
Labels: enhancement

#2487 fix: Invalid file upload path
  packages/forms/src/Components/BaseFileUpload.php
Labels: bug

#2488 fix: nullable select
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/select.js
Labels: bug

#2489 fix: Focus date picker min date
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/date-time-picker.js
Labels: bug

#2502 fix: Date picker formatting when used with validation
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/date-time-picker.js
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/src/Components/DateTimePicker.php
Labels: bug

#2504 fix: Date picker autofocus
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/date-time-picker.js
  packages/forms/src/Components/DateTimePicker.php
Labels: bug

#2491 Add loading state and styles to table and global search
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/mix-manifest.json
  packages/admin/resources/views/components/global-search/input.blade.php
  packages/forms/resources/views/components/wizard.blade.php
  packages/support/resources/views/components/button.blade.php
  packages/support/resources/views/components/loading-indicator.blade.php
  packages/tables/resources/views/components/actions-cell.blade.php
  packages/tables/resources/views/components/cell.blade.php
  packages/tables/resources/views/components/checkbox-cell.blade.php
  packages/tables/resources/views/components/empty-state/index.blade.php
  packages/tables/resources/views/components/loading-cell.blade.php
  packages/tables/resources/views/components/search-input.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Table.php
Labels: enhancement

#2508 fix: Scroll to concealing component when validation fails
  packages/forms/resources/views/components/section.blade.php
  packages/forms/resources/views/components/tabs.blade.php
  packages/forms/resources/views/components/wizard.blade.php
Labels: bug

#2519 fix: Multi-relationship field loads results from collection
  packages/forms/src/Components/BelongsToManyCheckboxList.php
  packages/forms/src/Components/BelongsToManyMultiSelect.php
Labels: bug

#2521 Make sidebar group collapsing configurable
  packages/admin/config/filament.php
  packages/admin/src/FilamentManager.php
Labels: enhancement

#2526 feature: Customize RM title based on owner record
  packages/admin/resources/views/components/resources/relation-managers/index.blade.php
  packages/admin/src/Resources/RelationManagers/RelationManager.php
Labels: enhancement

#2525 Added missing translations and fixed few translation strings
  packages/admin/resources/lang/cs/global-search.php
  packages/admin/resources/lang/cs/layout.php
  packages/admin/resources/lang/cs/login.php
  packages/admin/resources/lang/cs/pages/dashboard.php
  packages/admin/resources/lang/cs/resources/pages/edit-record.php
  packages/admin/resources/lang/cs/resources/relation-managers/associate.php
  packages/admin/resources/lang/cs/resources/relation-managers/dissociate.php
  packages/forms/resources/lang/cs/components.php
  packages/support/resources/lang/cs/actions.php
  packages/support/resources/lang/cs/components/button.php
  packages/support/resources/lang/cs/components/icon-button.php
  packages/support/resources/lang/cs/components/link.php
  packages/tables/resources/lang/cs/table.php
Labels: enhancement, i18n

#2534 Use brand config for base layout title
  packages/admin/resources/views/components/layouts/base.blade.php
Labels: enhancement

#2541 fix: !important CSS classes
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.css
  packages/forms/resources/css/components/select.css
Labels: bug

#2543 fix: Move important classes into plain CSS
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.css
  packages/forms/resources/css/components/select.css
Labels: bug

#2545 close modal in response to dynamic event fired when modal backdrop clicked or escape key is pressed
  packages/support/resources/views/components/modal/index.blade.php
Labels: enhancement

#2532 chore: use `$this` instead of `static` calls to instance methods
  packages/admin/src/Resources/RelationManagers/Concerns/CanDeleteRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanDetachRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanDissociateRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanEditRecords.php
Labels: chore

#2548 added custom event to open/close/toggle section
  packages/forms/resources/views/components/section.blade.php
Labels: enhancement

#2551 Fix facade phpdocblock
  packages/admin/src/Facades/Filament.php
Labels: bug

#2540 fix: Action attributes not being merged with component attributes
  packages/admin/resources/views/components/pages/actions/action.blade.php
  packages/forms/resources/views/components/actions/action.blade.php
  packages/support/src/helpers.php
  packages/tables/resources/views/components/actions/action.blade.php
Labels: bug

#2537 fix: avoiding repeated queries on table
  packages/tables/src/Concerns/CanSelectRecords.php
Labels: enhancement

#2538 fix: removing repeated queries on edit action
  packages/tables/src/Concerns/HasActions.php
Labels: enhancement

#2555 feat: Option to disable outputting the default DM Sans font
  packages/admin/config/filament.php
  packages/admin/docs/07-appearance.md
  packages/admin/resources/views/components/layouts/base.blade.php
Labels: enhancement

#2562 feature: set color-scheme dark when dark mode enabled
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/mix-manifest.json
  packages/admin/resources/css/app.css
Labels: enhancement, ui

#2558 fix: Loading state from relationships overwrites default
  packages/forms/src/Components/BelongsToManyCheckboxList.php
  packages/forms/src/Components/BelongsToManyMultiSelect.php
  packages/forms/src/Components/BelongsToSelect.php
  packages/spatie-laravel-media-library-plugin/src/Forms/Components/SpatieMediaLibraryFileUpload.php
  packages/spatie-laravel-tags-plugin/src/Forms/Components/SpatieTagsInput.php
Labels: bug

#2529 Fix: RichEditor spacing when no buttons
  packages/forms/resources/views/component-container.blade.php
  packages/forms/resources/views/components/checkbox-list.blade.php
  packages/forms/resources/views/components/radio.blade.php
  packages/forms/resources/views/components/rich-editor.blade.php
Labels: bug

#2565 Extract design of login-page to a reusable Card layout
  packages/admin/resources/views/components/layouts/card.blade.php
  packages/admin/resources/views/login.blade.php
  packages/admin/src/Http/Livewire/Auth/Login.php
Labels: enhancement

#2566 Add support for overriding the maximum content width on a page
  packages/admin/docs/07-appearance.md
  packages/admin/resources/views/components/layouts/app.blade.php
  packages/admin/src/Pages/Page.php
Labels: enhancement

#2567 Add support for setting the 'defaultTableRecordsPerPageSelectOption' via a config file
  packages/tables/config/tables.php
  packages/tables/src/Concerns/CanPaginateRecords.php
Labels: enhancement

#2455 Feature: add date time to config for DateTime and DateTimePicker
  packages/forms/config/forms.php
  packages/forms/src/Components/DateTimePicker.php
Labels: enhancement

#2573 fix: Hidden components diffing issues
  packages/forms/resources/views/component-container.blade.php
Labels: bug

#2575 Proper fix for default media name
  packages/spatie-laravel-media-library-plugin/src/Forms/Components/SpatieMediaLibraryFileUpload.php
Labels: bug

#2577 feature: Generate media name from $file
  packages/spatie-laravel-media-library-plugin/src/Forms/Components/SpatieMediaLibraryFileUpload.php
Labels: enhancement

#2578 Fix redundant focus event on modals
  packages/support/resources/views/components/modal/index.blade.php
Labels: bug

#2592 shortcut to set table filter layout in Resource class
  packages/admin/docs/02-resources/02-listing-records.md
  packages/admin/src/Resources/Pages/ListRecords.php
  packages/admin/src/Resources/Table.php
Labels: enhancement

#2593 Fix typo in 07-appearance.md
  packages/admin/docs/07-appearance.md
Labels: bug, documentation

#2588 Make sidebar group toggle animated
  packages/admin/resources/views/components/layouts/app/sidebar/group.blade.php
Labels: enhancement, ui

#2581 fix: bind NotificationManager as Facade for Octane
  packages/admin/src/Facades/FilamentNotification.php
  packages/admin/src/FilamentManager.php
  packages/admin/src/FilamentServiceProvider.php
  packages/admin/src/NotificationManager.php
Labels: bug

#2596 fix: RM notifications
  packages/admin/src/NotificationManager.php
Labels: bug

#2597 Added missing Turkish (tr) translations.
  packages/admin/resources/lang/tr/resources/pages/edit-record.php
  packages/admin/resources/lang/tr/resources/pages/list-records.php
  packages/admin/resources/lang/tr/resources/relation-managers/associate.php
  packages/admin/resources/lang/tr/resources/relation-managers/dissociate.php
  packages/admin/resources/lang/tr/resources/relation-managers/view.php
  packages/forms/resources/lang/tr/components.php
  packages/tables/resources/lang/tr/table.php
Labels: enhancement, i18n

#2599 fix: Form component action modals in table modals
  packages/forms/src/Concerns/InteractsWithForms.php
  packages/tables/resources/views/index.blade.php
Labels: bug

#2598 Added 500ms debounce to key value field inputs
  packages/forms/resources/views/components/key-value.blade.php
Labels: bug

#2606 Prevent markdown editor form submission
  packages/forms/resources/views/components/markdown-editor.blade.php
Labels: bug

#2607 fix: pass an array to the Spatie TagInput state like taginput
  packages/spatie-laravel-tags-plugin/src/Forms/Components/SpatieTagsInput.php
Labels: bug

#2611 Added Ukrainian (uk) locale.
  packages/admin/resources/lang/uk/global-search.php
  packages/admin/resources/lang/uk/layout.php
  packages/admin/resources/lang/uk/login.php
  packages/admin/resources/lang/uk/pages/dashboard.php
  packages/admin/resources/lang/uk/resources/pages/create-record.php
  packages/admin/resources/lang/uk/resources/pages/edit-record.php
  packages/admin/resources/lang/uk/resources/pages/list-records.php
  packages/admin/resources/lang/uk/resources/pages/view-record.php
  packages/admin/resources/lang/uk/resources/relation-managers/associate.php
  packages/admin/resources/lang/uk/resources/relation-managers/attach.php
  packages/admin/resources/lang/uk/resources/relation-managers/create.php
  packages/admin/resources/lang/uk/resources/relation-managers/delete.php
  packages/admin/resources/lang/uk/resources/relation-managers/detach.php
  packages/admin/resources/lang/uk/resources/relation-managers/dissociate.php
  packages/admin/resources/lang/uk/resources/relation-managers/edit.php
  packages/admin/resources/lang/uk/resources/relation-managers/view.php
  packages/admin/resources/lang/uk/widgets/account-widget.php
  packages/admin/resources/lang/uk/widgets/filament-info-widget.php
  packages/forms/resources/lang/uk/components.php
  packages/support/resources/lang/uk/actions.php
  packages/support/resources/lang/uk/components/button.php
  packages/tables/resources/lang/uk/table.php
Labels: enhancement, i18n

#2618 fix: Dynamically hide wizard steps and tabs
  packages/forms/resources/views/components/tabs.blade.php
  packages/forms/resources/views/components/wizard.blade.php
  packages/forms/src/Components/Tabs.php
  packages/forms/src/Components/Wizard.php
Labels: bug

#2613 Add prefix and suffix icons to text-input field
  packages/forms/resources/views/components/color-picker.blade.php
  packages/forms/resources/views/components/select.blade.php
  packages/forms/resources/views/components/text-input.blade.php
  packages/forms/src/Components/Concerns/HasAffixes.php
Labels: enhancement
