Repository filamentphp/filament, pull requests merged in 2022-11, with the labels that each got.

#4774 lang(pl): update translation
  packages/forms/resources/lang/pl/components.php
Labels: i18n

#4775 Updated and added Bosnian translations
  packages/admin/resources/lang/bs/layout.php
  packages/admin/resources/lang/bs/resources/pages/edit-record.php
  packages/admin/resources/lang/bs/resources/pages/view-record.php
  packages/forms/resources/lang/bs/components.php
  packages/tables/resources/lang/bs/table.php
Labels: i18n

#4781 RTL small ui fixes on table loading indicator
  packages/tables/resources/views/components/filters/indicators.blade.php
  packages/tables/resources/views/components/reorder/indicator.blade.php
  packages/tables/resources/views/components/selection-indicator.blade.php
Labels: i18n

#4790 fix searchable first column
  packages/tables/src/Columns/Concerns/InteractsWithTableQuery.php
Labels: bug

#4787 Allow resource manager buttons to be navigable via keyboard
  packages/admin/resources/views/components/resources/relation-managers/index.blade.php
Labels: bug

#4784 Added $default to askRequired in CanValidateInput
  packages/support/src/Commands/Concerns/CanValidateInput.php
Labels: enhancement

#4793 Suggesting to change the "Nuevo" text by "Crear" in spanish and disabledOn functionality
  packages/forms/src/Components/Concerns/CanBeDisabled.php
  packages/support/resources/lang/es/actions/create.php
Labels: enhancement, i18n

#4506 Fix: image and markdown persisting state
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/file-upload.js
  packages/forms/resources/js/components/markdown-editor.js
Labels: bug

#4681 Fix dark mode layout for sorting in table layout
  packages/tables/resources/lang/de/table.php
  packages/tables/resources/views/index.blade.php
Labels: bug

#4688 feature: Navigation active icons
  packages/admin/docs/05-navigation.md
  packages/admin/resources/views/components/layouts/app/sidebar/badge.blade.php
  packages/admin/resources/views/components/layouts/app/sidebar/index.blade.php
  packages/admin/resources/views/components/layouts/app/sidebar/item.blade.php
  packages/admin/src/Navigation/NavigationItem.php
  packages/admin/src/Pages/Page.php
  packages/admin/src/Resources/Resource.php
Labels: enhancement

#4749 Fix components registration in subdirectory when using wildcard
  packages/admin/src/FilamentServiceProvider.php
Labels: bug

#4795 Add aria label to sidebar expand and collapse buttons
  packages/admin/resources/lang/en/layout.php
  packages/admin/resources/views/components/layouts/app/sidebar/index.blade.php
Labels: enhancement

#4782 [2.x] feature: allow ignoring policies in authorization checks
  packages/admin/src/Resources/RelationManagers/RelationManager.php
  packages/admin/src/Resources/Resource.php
Labels: enhancement

#4797 Append missing Korean translation
  packages/support/resources/lang/ko/actions/associate.php
  packages/support/resources/lang/ko/actions/dissociate.php
  packages/support/resources/lang/ko/actions/force-delete.php
  packages/support/resources/lang/ko/actions/group.php
  packages/support/resources/lang/ko/actions/replicate.php
  packages/support/resources/lang/ko/actions/restore.php
  packages/support/resources/lang/ko/actions/view.php
  packages/support/resources/lang/ko/components/button.php
  packages/support/resources/lang/ko/components/modal.php
Labels: i18n

#4798 Adds FA translations for layout buttons.
  packages/admin/resources/lang/fa/layout.php
Labels: i18n

#4799 remove pointer-events-none in section.blade.php to allow clickable links in description.
  packages/forms/resources/views/components/section.blade.php
Labels: bug

#4801 Update layout translations
  packages/admin/resources/lang/en/layout.php
  packages/admin/resources/lang/nl/layout.php
Labels: i18n

#4802 Use x syntax for Alpine
  packages/admin/resources/views/components/layouts/app/sidebar/index.blade.php
Labels: code quality

#4766 Feature: Add select/deselect all to CheckboxList
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/mix-manifest.json
  packages/forms/docs/03-fields.md
  packages/forms/resources/lang/en/components.php
  packages/forms/resources/lang/nl/components.php
  packages/forms/resources/views/components/checkbox-list.blade.php
  packages/forms/src/Components/CheckboxList.php
Labels: enhancement

#4804 Make JS formatting consistent with Prettier
  packages/forms/resources/views/components/checkbox-list.blade.php
Labels: code quality

#4803 Add toggle sidebar label on mobile
  packages/admin/resources/views/components/topbar.blade.php
Labels: enhancement

#4792 Feature: Add expand/collapse all events to collapsible rows
  packages/tables/resources/views/index.blade.php
Labels: enhancement

#4805 translations: update French
  packages/admin/resources/lang/fr/layout.php
  packages/forms/resources/lang/fr/components.php
Labels: i18n

#4808 Secondary color
  packages/actions/src/Concerns/CanOpenModal.php
  packages/actions/src/RestoreAction.php
  packages/actions/src/ViewAction.php
  packages/app/dist/index.css
  packages/app/docs/03-pages/02-actions.md
  packages/app/docs/08-appearance.md
  packages/app/resources/views/components/layouts/app/sidebar/badge.blade.php
  packages/app/resources/views/components/layouts/app/topbar/database-notifications-trigger.blade.php
  packages/app/resources/views/components/tenant-menu.blade.php
  packages/app/resources/views/components/user-menu.blade.php
  packages/app/src/Resources/Pages/CreateRecord.php
  packages/app/src/Resources/Pages/EditRecord.php
  packages/app/tailwind.config.js
  packages/forms/dist/components/file-upload.js
  packages/forms/dist/components/markdown-editor.js
  packages/forms/docs/01-installation.md
  packages/forms/resources/views/components/field-wrapper/hint.blade.php
  packages/forms/resources/views/components/toggle.blade.php
  packages/forms/resources/views/components/wizard.blade.php
  packages/forms/stubs/scaffolding/tailwind.config.js
  packages/notifications/docs/01-installation.md
  packages/notifications/docs/02-sending-notifications.md
  packages/notifications/resources/views/components/database/modal/actions.blade.php
  packages/notifications/resources/views/components/icon.blade.php
  packages/notifications/src/Concerns/HasIcon.php
  packages/notifications/stubs/scaffolding/tailwind.config.js
  packages/support/resources/views/components/button.blade.php
  packages/support/resources/views/components/dropdown/header.blade.php
  packages/support/resources/views/components/dropdown/list/item.blade.php
  packages/support/resources/views/components/icon-button.blade.php
  packages/support/resources/views/components/link.blade.php
  packages/tables/docs/01-installation.md
  packages/tables/docs/03-columns/03-icon.md
  packages/tables/docs/03-columns/05-badge.md
  packages/tables/resources/views/columns/badge-column.blade.php
  packages/tables/resources/views/columns/icon-column.blade.php
  packages/tables/resources/views/columns/text-column.blade.php
  packages/tables/resources/views/columns/toggle-column.blade.php
  packages/tables/resources/views/components/pagination/index.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Actions/AssociateAction.php
  packages/tables/src/Actions/AttachAction.php
  packages/tables/src/Actions/RestoreAction.php
  packages/tables/src/Actions/RestoreBulkAction.php
  packages/tables/src/Actions/ViewAction.php
  packages/tables/stubs/scaffolding/tailwind.config.js
  packages/widgets/resources/views/components/stats/card.blade.php
  tests/src/Actions/ActionTest.php
  tests/src/Notifications/NotificationTest.php
  tests/src/Tables/ActionTest.php
  tests/src/Tables/BulkActionTest.php
Labels: ui

#4764 Normalize wire:keys in table mount action forms
  packages/tables/resources/views/index.blade.php
Labels: bug

#4816 fix: Query string being overwritten by session
  packages/tables/src/Concerns/InteractsWithTable.php
Labels: bug

#4818 lang(pt-br): added translation checkbox_list
  packages/forms/resources/lang/pt_BR/components.php
Labels: i18n

#4824 Adds select/deselect all FA translations.
  packages/forms/resources/lang/fa/components.php
Labels: i18n

#4825 Doc - Markdown php tag
  packages/tables/docs/05-actions.md
Labels: documentation

#4834 Update finnish translation
  packages/admin/resources/lang/fi/layout.php
  packages/forms/resources/lang/fi/components.php
Labels: i18n

#4835 fix: Skip render for form component methods
  packages/forms/src/Concerns/InteractsWithForms.php
Labels: bug

#4618 Feat: Add Support For BelongsToRelationship
  packages/admin/src/Commands/Concerns/CanGenerateResources.php
  packages/admin/src/Commands/MakeResourceCommand.php
Labels: enhancement

#4823 Add hidden method
  packages/forms/docs/03-fields.md
Labels: documentation

#4831 make global search case-insensitive, and allow the search to run on all locales
  packages/admin/src/Resources/Resource.php
Labels: enhancement

#4813 Copyable in TextColumn
  packages/tables/docs/03-columns/02-text.md
  packages/tables/resources/lang/ar/table.php
  packages/tables/resources/lang/bn/table.php
  packages/tables/resources/lang/bs/table.php
  packages/tables/resources/lang/cs/table.php
  packages/tables/resources/lang/da/table.php
  packages/tables/resources/lang/en/table.php
  packages/tables/resources/lang/es/table.php
  packages/tables/resources/lang/fa/table.php
  packages/tables/resources/lang/fi/table.php
  packages/tables/resources/lang/fr/table.php
  packages/tables/resources/lang/he/table.php
  packages/tables/resources/lang/hu/table.php
  packages/tables/resources/lang/id/table.php
  packages/tables/resources/lang/it/table.php
  packages/tables/resources/lang/ja/table.php
  packages/tables/resources/lang/lt/table.php
  packages/tables/resources/lang/ms/table.php
  packages/tables/resources/lang/nl/table.php
  packages/tables/resources/lang/pl/table.php
  packages/tables/resources/lang/pt_BR/table.php
  packages/tables/resources/lang/ro/table.php
  packages/tables/resources/lang/ru/table.php
  packages/tables/resources/lang/sv/table.php
  packages/tables/resources/lang/sw/table.php
  packages/tables/resources/lang/uk/table.php
  packages/tables/resources/lang/vi/table.php
  packages/tables/resources/views/columns/color-column.blade.php
  packages/tables/resources/views/columns/text-column.blade.php
  packages/tables/src/Columns/ColorColumn.php
  packages/tables/src/Columns/Concerns/CanBeCopied.php
  packages/tables/src/Columns/TextColumn.php
Labels: enhancement

#4839 Bangla Language Support Updated.
  packages/forms/resources/lang/bn/components.php
  packages/tables/resources/lang/bn/table.php
Labels: i18n

#4844 Enhancement: default to action model in HasActions trait
  packages/admin/src/Pages/Concerns/HasActions.php
Labels: enhancement

#4809 Support Column text alignment of the text-start, text-end and text-justify
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/resources/views/components/key-value.blade.php
  packages/forms/resources/views/components/tags-input.blade.php
  packages/forms/resources/views/components/wizard.blade.php
  packages/support/resources/views/components/dropdown/list/item.blade.php
  packages/tables/resources/views/components/columns/column.blade.php
  packages/tables/resources/views/components/filters/index.blade.php
  packages/tables/resources/views/components/table.blade.php
  packages/tables/src/Columns/Concerns/HasAlignment.php
Labels: enhancement

#4847 Add missing Arabic translations
  packages/admin/resources/lang/ar/layout.php
  packages/forms/resources/lang/ar/components.php
Labels: i18n

#4849 Rich Editor support for trix-active
  packages/forms/resources/css/components/rich-editor.css
Labels: ui

#4848 Update ms translations.
  packages/admin/resources/lang/ms/layout.php
  packages/forms/resources/lang/ms/components.php
Labels: i18n

#4859 Fix checkbox list without bulk toggleable
  packages/forms/resources/views/components/checkbox-list.blade.php
Labels: bug

#4863 added missing german translations
  packages/admin/resources/lang/de/layout.php
  packages/forms/resources/lang/de/components.php
  packages/tables/resources/lang/de/table.php
Labels: i18n

#4866 Update id translations
  packages/admin/resources/lang/id/layout.php
  packages/forms/resources/lang/id/components.php
Labels: i18n

#4875 Fix date time picker duplicate space
  packages/forms/resources/views/components/date-time-picker.blade.php
Labels: code quality

#4881 Fix: undefined $refs.textarea when component tries to render
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/markdown-editor.js
Labels: bug

#4857 Expose Laravel Loop Object To Column
  packages/tables/docs/03-columns/02-text.md
  packages/tables/resources/views/columns/layout/split.blade.php
  packages/tables/resources/views/columns/layout/stack.blade.php
  packages/tables/resources/views/components/columns/layout.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Columns/Column.php
  packages/tables/src/Columns/Concerns/HasRowLoopObject.php
  packages/tables/src/Columns/Layout/Component.php
  packages/tables/src/Columns/TextColumn.php
Labels: enhancement

#4893 Updated and added Bosnian translations
  packages/admin/resources/lang/bs/resources/pages/create-record.php
  packages/forms/resources/lang/bs/components.php
  packages/notifications/resources/lang/bs/database.php
  packages/tables/resources/lang/bs/table.php
Labels: i18n

#4891 feat: add `registerViteTheme`
  packages/admin/docs/08-appearance.md
  packages/admin/src/Facades/Filament.php
  packages/admin/src/FilamentManager.php
Labels: enhancement

#4899 Add HasFontFamily in TextColumn
  packages/tables/docs/03-columns/02-text.md
  packages/tables/resources/views/columns/text-column.blade.php
  packages/tables/src/Columns/Concerns/HasFontFamily.php
  packages/tables/src/Columns/TextColumn.php
Labels: enhancement

#4914 Feat: Form Components `columnSpanFull`
  packages/forms/src/Components/Concerns/CanSpanColumns.php
Labels: enhancement

#4878 Allow add header & footer for custom content modal
  packages/admin/docs/03-pages/02-actions.md
  packages/admin/resources/views/components/page.blade.php
  packages/forms/resources/views/components/actions/modal/index.blade.php
  packages/support/src/Actions/Concerns/CanOpenModal.php
  packages/tables/docs/05-actions.md
  packages/tables/resources/views/index.blade.php
Labels: enhancement

#4869 Fix/form builder testing helpers
  composer.lock
  packages/forms/src/Testing/TestsForms.php
  tests/src/Forms/FormsTest.php
Labels: bug

#4916 fix: Wizard submit validation
  composer.lock
  packages/forms/resources/views/components/wizard.blade.php
  packages/forms/resources/views/components/wizard/step.blade.php
Labels: bug

#4923 Fix docs typo
  packages/admin/docs/03-pages/02-actions.md
  packages/tables/docs/05-actions.md
Labels: documentation

#4924 vi: update missing translations
  packages/admin/resources/lang/vi/layout.php
  packages/forms/resources/lang/vi/components.php
Labels: i18n

#4918 Move text input affixes inside border
  composer.lock
  packages/app/dist/index.css
  packages/forms/dist/index.css
  packages/forms/resources/css/components/select.css
  packages/forms/resources/views/components/color-picker.blade.php
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/resources/views/components/select.blade.php
  packages/forms/resources/views/components/text-input.blade.php
  packages/forms/src/Components/DateTimePicker.php
  packages/support/resources/views/components/input/affixes.blade.php
  packages/support/resources/views/components/input/select.blade.php
Labels: ui

#4928 Make slideover actions stick to the bottom
  packages/support/resources/views/components/modal/index.blade.php
Labels: ui

#4934 fix: Nav item badge component color
  packages/admin/resources/views/components/layouts/app/sidebar/item.blade.php
Labels: bug

#4926 Fix: Validation error color for dark mode
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.css
  packages/forms/resources/css/components/select.css
  packages/forms/resources/views/components/checkbox-list.blade.php
  packages/forms/resources/views/components/checkbox.blade.php
  packages/forms/resources/views/components/color-picker.blade.php
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/resources/views/components/field-wrapper/error-message.blade.php
  packages/forms/resources/views/components/field-wrapper/label.blade.php
  packages/forms/resources/views/components/markdown-editor.blade.php
  packages/forms/resources/views/components/radio.blade.php
  packages/forms/resources/views/components/rich-editor.blade.php
  packages/forms/resources/views/components/select.blade.php
  packages/forms/resources/views/components/tags-input.blade.php
  packages/forms/resources/views/components/text-input.blade.php
  packages/forms/resources/views/components/textarea.blade.php
Labels: ui

#4935 Remove extra brackets
  packages/tables/docs/07-testing.md
Labels: documentation

#4936 Fix: Nested modal
  packages/support/resources/views/components/modal/index.blade.php
Labels: bug

#4953 Adding position into select field
  packages/forms/resources/js/components/select.js
  packages/forms/resources/views/components/select.blade.php
  packages/forms/src/Components/Select.php
Labels: enhancement

#4959 Revert Nested Modals
  packages/support/resources/views/components/modal/index.blade.php
Labels: bug

#4965 Add Latvian translations for support, forms and notifications
  packages/forms/resources/lang/lv/components.php
  packages/notifications/resources/lang/lv/database.php
  packages/support/resources/lang/lv/actions/associate.php
  packages/support/resources/lang/lv/actions/attach.php
  packages/support/resources/lang/lv/actions/create.php
  packages/support/resources/lang/lv/actions/delete.php
  packages/support/resources/lang/lv/actions/detach.php
  packages/support/resources/lang/lv/actions/dissociate.php
  packages/support/resources/lang/lv/actions/edit.php
  packages/support/resources/lang/lv/actions/force-delete.php
  packages/support/resources/lang/lv/actions/group.php
  packages/support/resources/lang/lv/actions/modal.php
  packages/support/resources/lang/lv/actions/replicate.php
  packages/support/resources/lang/lv/actions/restore.php
  packages/support/resources/lang/lv/actions/view.php
  packages/support/resources/lang/lv/components/button.php
  packages/support/resources/lang/lv/components/modal.php
Labels: i18n

#4969 [3.x] feature: add `filament-user-menu` class to user menu
  packages/app/resources/views/components/user-menu.blade.php
Labels: enhancement

#4958 Additional column assertions
  composer.lock
  packages/tables/.stubs.php
  packages/tables/src/Testing/TestsColumns.php
  tests/src/Tables/ColumnTest.php
  tests/src/Tables/Fixtures/PostsTable.php
Labels: enhancement

#4955 Document individual search query string
  packages/tables/docs/02-getting-started.md
  packages/tables/docs/03-columns/01-getting-started.md
Labels: documentation

#4967 [3.x] feature: add back footer logo toggling
  packages/app/resources/views/components/footer.blade.php
Labels: enhancement

#4970 Add class to record wire click action button so it can easily be targeted for custom CSS
  packages/tables/resources/views/index.blade.php
Labels: enhancement

#4968 fix: exclude double tabindex in DateTimePicker
  packages/forms/resources/views/components/date-time-picker.blade.php
Labels: bug

#4980 Fix deprecation comments style
  packages/forms/src/Components/BelongsToManyCheckboxList.php
  packages/forms/src/Components/RelationshipRepeater.php
Labels: chore

#4982 feature: add filament classes to sidebar group dividers
  packages/app/resources/views/components/layouts/app/sidebar/index.blade.php
Labels: enhancement

#4981 Updated RU translations & added hoursStep(), minutesStep(), secondsStep() to DateTimePicker.php
  packages/admin/resources/lang/ru/layout.php
  packages/forms/docs/03-fields.md
  packages/forms/resources/lang/ru/components.php
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/src/Components/DateTimePicker.php
Labels: enhancement, i18n

#4788 Wizard: Expose step value to querystring
  packages/forms/resources/views/components/wizard.blade.php
  packages/forms/src/Components/Wizard.php
Labels: enhancement

#4984 [3.x] feature: allow non-LW auth routes to be used
  packages/app/src/Context.php
Labels: enhancement

#4988 Translated to Romanian
  packages/admin/resources/lang/ro/layout.php
  packages/forms/resources/lang/ro/components.php
  packages/notifications/resources/lang/ro/database.php
  packages/support/resources/lang/ro/actions/delete.php
  packages/tables/resources/lang/ro/table.php
Labels: i18n

#4992 fix: Make TextInput and SelectColumn respect alignment
  packages/tables/resources/views/columns/select-column.blade.php
  packages/tables/resources/views/columns/text-input-column.blade.php
Labels: bug

#5000 Remove blank line
  packages/tables/resources/views/columns/text-input-column.blade.php
Labels: code quality

#5004 Update Heroicons links in docs
  packages/admin/docs/02-resources/01-getting-started.md
  packages/admin/docs/03-pages/02-actions.md
  packages/admin/docs/05-navigation.md
  packages/notifications/docs/02-sending-notifications.md
  packages/tables/docs/03-columns/03-icon.md
Labels: documentation

#4995 Decouple notification test helper from livewire
  packages/notifications/composer.json
  packages/notifications/docs/06-testing.md
  packages/notifications/src/Notification.php
  packages/notifications/src/Testing/Autoload.php
  packages/notifications/src/Testing/TestsNotifications.php
Labels: enhancement

#4989 [3.x] feature: add support for `readonly` input fields
  packages/forms/resources/views/components/text-input.blade.php
  packages/forms/resources/views/components/textarea.blade.php
  packages/forms/src/Components/Concerns/CanBeReadonly.php
  packages/forms/src/Components/TextInput.php
  packages/forms/src/Components/Textarea.php
  packages/forms/src/Testing/TestsForms.php
Labels: enhancement

#5003 Select column option assertions
  packages/tables/.stubs.php
  packages/tables/src/Testing/TestsColumns.php
  tests/src/Tables/ColumnTest.php
  tests/src/Tables/Fixtures/PostsTable.php
Labels: enhancement

#5012 Fix: colors in preset to use tailwind 3.2 format for rgba color strings
  packages/app/dist/theme.css
  packages/app/filament-preset.js
Labels: code quality

#5014 fix: Diffing issues when toggling columns (TextInputColumn)
  packages/tables/resources/views/index.blade.php
Labels: bug

#5039 Clarify documentation on MarkdownEditor file upload functionality
  packages/forms/docs/03-fields.md
Labels: documentation

#5050 Improve Arabic table filters translations
  packages/tables/resources/lang/ar/table.php
Labels: i18n

#5053 ListRecords use closures to set form schema on actions
  packages/admin/src/Resources/Pages/ListRecords.php
Labels: bug

#4999 Remove markup when modal heading is empty
  packages/admin/resources/views/components/page.blade.php
  packages/forms/resources/views/components/actions/modal/index.blade.php
  packages/tables/resources/views/index.blade.php
Labels: bug

#4998 Allow empty modal subheading
  packages/support/src/Actions/Concerns/CanOpenModal.php
  packages/support/src/Actions/Concerns/CanRequireConfirmation.php
Labels: bug

#5074 Font size tweaks
  packages/app/dist/theme.css
  packages/app/resources/views/components/layouts/app/topbar/breadcrumbs.blade.php
  packages/forms/dist/index.css
  packages/forms/resources/css/components/select.css
  packages/forms/resources/views/components/color-picker.blade.php
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/resources/views/components/placeholder.blade.php
  packages/forms/resources/views/components/section.blade.php
  packages/forms/resources/views/components/tags-input.blade.php
  packages/forms/resources/views/components/text-input.blade.php
  packages/forms/resources/views/components/textarea.blade.php
  packages/support/resources/views/components/input/index.blade.php
  packages/support/resources/views/components/input/select.blade.php
  packages/tables/resources/views/columns/badge-column.blade.php
  packages/tables/resources/views/columns/checkbox-column.blade.php
  packages/tables/resources/views/columns/select-column.blade.php
  packages/tables/resources/views/columns/text-input-column.blade.php
  packages/tables/resources/views/components/search-input.blade.php
Labels: ui

#5070 Fix icon size and color
  packages/app/resources/views/components/layouts/app/sidebar/item.blade.php
  packages/app/resources/views/components/layouts/app/topbar/database-notifications-trigger.blade.php
  packages/support/resources/views/components/modal/index.blade.php
  packages/tables/resources/views/components/filters/trigger.blade.php
  packages/tables/resources/views/components/header-cell.blade.php
  packages/tables/resources/views/components/toggleable/trigger.blade.php
Labels: ui

#5052 Enable Customizing imageResizeUpscale
  packages/forms/resources/js/components/file-upload.js
  packages/forms/resources/views/components/file-upload.blade.php
  packages/forms/src/Components/FileUpload.php
Labels: enhancement

#5078 Fix: js issues with datepicker and toggle form components
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/date-time-picker.js
  packages/forms/resources/views/components/toggle.blade.php
Labels: bug, confirmed

#5093 Add Pint types spaces rule
  pint.json
Labels: code quality

#5097 fix: Non-inline radio button spacing
  packages/forms/resources/views/components/radio.blade.php
Labels: bug
