Repository filamentphp/filament, pull requests merged in 2022-10, with the labels that each got.

#4305 Add missing Spanish translations
  packages/forms/resources/lang/es/components.php
  packages/support/resources/lang/es/actions/replicate.php
  packages/tables/resources/lang/es/table.php
Labels: i18n

#4322 Document missing supported badge colour
  packages/tables/docs/03-columns/06-badge.md
Labels: documentation

#4332 Clarify bug report template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: chore

#4334 Add renderHooks to user-menu dropdown
  packages/admin/docs/08-appearance.md
  packages/admin/resources/views/components/layouts/app/topbar/user-menu.blade.php
Labels: enhancement

#4351 feature: refresh form data
  packages/admin/docs/03-pages/02-actions.md
  packages/admin/src/Resources/Pages/EditRecord.php
  packages/admin/src/Resources/Pages/ViewRecord.php
  tests/src/Admin/Fixtures/Resources/PostResource/Pages/EditPost.php
  tests/src/Admin/Fixtures/Resources/PostResource/Pages/ViewPost.php
  tests/src/Admin/Resources/Pages/EditRecordTest.php
  tests/src/Admin/Resources/Pages/ViewRecordTest.php
Labels: enhancement

#4347 Update italian translation
  packages/admin/resources/lang/it/layout.php
  packages/admin/resources/lang/it/resources/pages/edit-record.php
  packages/admin/resources/lang/it/resources/pages/view-record.php
  packages/tables/resources/lang/it/table.php
Labels: i18n

#4356 Update hungarian translation
  packages/admin/resources/lang/hu/layout.php
  packages/admin/resources/lang/hu/resources/pages/edit-record.php
  packages/forms/resources/lang/hu/components.php
  packages/tables/resources/lang/hu/table.php
Labels: i18n

#4360 fix: Markdown newlines
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/markdown-editor.js
Labels: bug

#4354 Docs: Chart Configuration Options
  packages/admin/docs/04-dashboard/03-charts.md
Labels: documentation

#4371 Docs: Fix spelling error on Validation page
  packages/forms/docs/05-validation.md
Labels: documentation

#4377 Feat: Adds glowing divider to sidebar header
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/mix-manifest.json
  packages/admin/resources/css/app.css
  packages/admin/resources/views/components/layouts/app/sidebar/index.blade.php
Labels: ui

#4376 Add prohibited validation rule
  packages/forms/docs/05-validation.md
  packages/forms/src/Components/Concerns/CanBeValidated.php
Labels: enhancement

#4366 Adding Hebrew translation
  packages/admin/resources/lang/he/global-search.php
  packages/admin/resources/lang/he/layout.php
  packages/admin/resources/lang/he/login.php
  packages/admin/resources/lang/he/pages/dashboard.php
  packages/admin/resources/lang/he/resources/pages/create-record.php
  packages/admin/resources/lang/he/resources/pages/edit-record.php
  packages/admin/resources/lang/he/resources/pages/list-records.php
  packages/admin/resources/lang/he/resources/pages/view-record.php
  packages/admin/resources/lang/he/widgets/account-widget.php
  packages/admin/resources/lang/he/widgets/filament-info-widget.php
  packages/forms/resources/lang/he/components.php
  packages/notifications/resources/lang/he/database.php
  packages/spatie-laravel-settings-plugin/resources/lang/he/pages/settings-page.php
  packages/spatie-laravel-translatable-plugin/resources/lang/he/actions.php
  packages/support/resources/lang/he/actions/associate.php
  packages/support/resources/lang/he/actions/attach.php
  packages/support/resources/lang/he/actions/create.php
  packages/support/resources/lang/he/actions/delete.php
  packages/support/resources/lang/he/actions/detach.php
  packages/support/resources/lang/he/actions/dissociate.php
  packages/support/resources/lang/he/actions/edit.php
  packages/support/resources/lang/he/actions/force-delete.php
  packages/support/resources/lang/he/actions/group.php
  packages/support/resources/lang/he/actions/modal.php
  packages/support/resources/lang/he/actions/replicate.php
  packages/support/resources/lang/he/actions/restore.php
  packages/support/resources/lang/he/actions/view.php
  packages/support/resources/lang/he/components/button.php
  packages/support/resources/lang/he/components/modal.php
  packages/tables/resources/lang/he/table.php
Labels: enhancement, i18n

#4378 Font weights
  packages/tables/resources/views/columns/text-column.blade.php
Labels: enhancement

#4341 chore: Add translation bot
  .github/workflows/translation-update.yml
Labels: chore

#4306 Fix: s3 private/public temporaryUrl generation
  packages/forms/src/Components/BaseFileUpload.php
  packages/tables/src/Columns/ImageColumn.php
Labels: bug

#4396 Fix: Dark mode styling for table stacks and grids
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/mix-manifest.json
  packages/tables/resources/views/index.blade.php
Labels: ui

#4395 Fix Grow Table Columns
  packages/tables/resources/views/components/columns/layout.blade.php
Labels: bug

#4393 Move topbar into component
  packages/admin/resources/views/components/layouts/app.blade.php
  packages/admin/resources/views/components/topbar.blade.php
Labels: chore

#4402 [docs] fix typo
  packages/forms/docs/05-validation.md
Labels: documentation

#4404 fix: Tags input suggestion
  packages/forms/resources/views/components/tags-input.blade.php
Labels: bug

#4405 Remove unused import from color picker JS
  packages/forms/resources/js/components/color-picker.js
Labels: code quality

#4406 fix: Escape inputs without closing modal
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/color-picker.js
  packages/forms/resources/views/components/color-picker.blade.php
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/resources/views/components/select.blade.php
Labels: bug

#4407 fix: Empty state hides column search
  packages/tables/resources/views/index.blade.php
Labels: bug

#4408 fix: Autofocus wizard step fields
  packages/forms/resources/views/components/wizard.blade.php
  packages/forms/resources/views/components/wizard/step.blade.php
Labels: bug

#4307 Added Htmlable Support For TableHeader.
  packages/admin/src/Resources/RelationManagers/RelationManager.php
  packages/tables/src/Concerns/HasHeader.php
  packages/tables/src/Table.php
Labels: enhancement

#4409 fix: Database notifications dup query
  packages/notifications/resources/views/components/database/index.blade.php
Labels: bug

#4283 feature: configure global search results limit in a resource
  packages/admin/src/Resources/Resource.php
  tests/src/Admin/Fixtures/Resources/PostResource.php
  tests/src/Admin/GlobalSearch/GlobalSearchTest.php
Labels: enhancement

#4355 Docs: Document Action size() Method
  packages/admin/docs/03-pages/02-actions.md
  packages/tables/docs/05-actions.md
Labels: documentation

#4410 Fix code example to match text body in the documentation
  packages/tables/docs/03-columns/06-badge.md
Labels: documentation

#4348 Allow Hint Color Specification for Fields
  packages/forms/docs/03-fields.md
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/checkbox-list.blade.php
  packages/forms/resources/views/components/checkbox.blade.php
  packages/forms/resources/views/components/color-picker.blade.php
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/resources/views/components/field-wrapper/hint.blade.php
  packages/forms/resources/views/components/field-wrapper/index.blade.php
  packages/forms/resources/views/components/field-wrapper/inline.blade.php
  packages/forms/resources/views/components/file-upload.blade.php
  packages/forms/resources/views/components/key-value.blade.php
  packages/forms/resources/views/components/markdown-editor.blade.php
  packages/forms/resources/views/components/placeholder.blade.php
  packages/forms/resources/views/components/radio.blade.php
  packages/forms/resources/views/components/repeater.blade.php
  packages/forms/resources/views/components/rich-editor.blade.php
  packages/forms/resources/views/components/select.blade.php
  packages/forms/resources/views/components/tags-input.blade.php
  packages/forms/resources/views/components/text-input.blade.php
  packages/forms/resources/views/components/textarea.blade.php
  packages/forms/resources/views/components/toggle.blade.php
  packages/forms/src/Components/Concerns/HasHint.php
Labels: enhancement

#4353 Document recordSelectOptionsQuery() method
  packages/admin/docs/02-resources/01-getting-started.md
  packages/admin/docs/02-resources/06-relation-managers.md
Labels: documentation

#4372 Added reorder table code for relation managers
  packages/admin/src/Resources/RelationManagers/RelationManager.php
Labels: bug

#4325 Allow disabling date time picker dates
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.js
  packages/forms/docs/03-fields.md
  packages/forms/resources/js/components/date-time-picker.js
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/src/Components/DateTimePicker.php
Labels: enhancement

#4215 feature: Hint actions
  packages/forms/docs/03-fields.md
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/checkbox-list.blade.php
  packages/forms/resources/views/components/checkbox.blade.php
  packages/forms/resources/views/components/color-picker.blade.php
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/resources/views/components/field-wrapper/hint.blade.php
  packages/forms/resources/views/components/field-wrapper/index.blade.php
  packages/forms/resources/views/components/field-wrapper/inline.blade.php
  packages/forms/resources/views/components/file-upload.blade.php
  packages/forms/resources/views/components/key-value.blade.php
  packages/forms/resources/views/components/markdown-editor.blade.php
  packages/forms/resources/views/components/placeholder.blade.php
  packages/forms/resources/views/components/radio.blade.php
  packages/forms/resources/views/components/repeater.blade.php
  packages/forms/resources/views/components/rich-editor.blade.php
  packages/forms/resources/views/components/select.blade.php
  packages/forms/resources/views/components/tags-input.blade.php
  packages/forms/resources/views/components/text-input.blade.php
  packages/forms/resources/views/components/textarea.blade.php
  packages/forms/resources/views/components/toggle.blade.php
  packages/forms/src/Components/Concerns/HasHint.php
  packages/forms/stubs/FieldView.stub
Labels: enhancement

#4416 fix: Hide reordering handles
  packages/tables/resources/views/index.blade.php
Labels: bug

#4417 fix: Conditional date picker disabled
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/date-time-picker.js
  packages/forms/resources/views/components/date-time-picker.blade.php
Labels: bug

#4419 Fix/bosnian translations
  packages/admin/resources/lang/bs/global-search.php
  packages/admin/resources/lang/bs/layout.php
  packages/admin/resources/lang/bs/login.php
  packages/admin/resources/lang/bs/pages/dashboard.php
  packages/admin/resources/lang/bs/resources/pages/create-record.php
  packages/admin/resources/lang/bs/resources/pages/edit-record.php
  packages/admin/resources/lang/bs/widgets/account-widget.php
  packages/forms/resources/lang/bs/components.php
  packages/notifications/resources/lang/bs/database.php
  packages/support/resources/lang/bs/actions/associate.php
  packages/support/resources/lang/bs/actions/attach.php
  packages/support/resources/lang/bs/actions/create.php
  packages/support/resources/lang/bs/actions/delete.php
  packages/support/resources/lang/bs/actions/detach.php
  packages/support/resources/lang/bs/actions/dissociate.php
  packages/support/resources/lang/bs/actions/edit.php
  packages/support/resources/lang/bs/actions/force-delete.php
  packages/support/resources/lang/bs/actions/group.php
  packages/support/resources/lang/bs/actions/modal.php
  packages/support/resources/lang/bs/actions/replicate.php
  packages/support/resources/lang/bs/actions/restore.php
  packages/support/resources/lang/bs/actions/view.php
  packages/support/resources/lang/bs/components/button.php
  packages/support/resources/lang/bs/components/modal.php
  packages/tables/resources/lang/bs/table.php
Labels: i18n

#4420 Add support for the before method in policy
  packages/admin/src/Resources/RelationManagers/RelationManager.php
  packages/admin/src/Resources/Resource.php
Labels: bug

#4422 fix: Filter column spans
  packages/tables/src/Concerns/HasFilters.php
  packages/tables/src/Filters/BaseFilter.php
  packages/tables/src/Filters/Concerns/HasColumns.php
  packages/tables/src/Filters/Filter.php
  packages/tables/src/Filters/MultiSelectFilter.php
  packages/tables/src/Filters/SelectFilter.php
Labels: bug

#4423 improve vietnamese translation
  packages/support/resources/lang/vi/actions/delete.php
Labels: i18n

#4424 feature: Mutate layout relationship data
  packages/forms/src/Components/Concerns/EntanglesStateWithSingularRelationship.php
  packages/forms/src/Components/Contracts/CanEntangleWithSingularRelationships.php
Labels: enhancement

#4429 chore: Deprecate MultiSelectFilter
  packages/tables/docs/04-filters.md
  packages/tables/src/Filters/MultiSelectFilter.php
  packages/tables/src/Filters/SelectFilter.php
  packages/tables/src/Testing/TestsFilters.php
Labels: chore

#4431 chore: Deprecate BooleanColumn
  packages/admin/docs/02-resources/02-listing-records.md
  packages/admin/src/Commands/Concerns/CanGenerateResources.php
  packages/tables/docs/02-getting-started.md
  packages/tables/docs/03-columns/01-getting-started.md
  packages/tables/docs/03-columns/03-boolean.md
  packages/tables/docs/03-columns/03-icon.md
  packages/tables/docs/03-columns/05-badge.md
  packages/tables/docs/03-columns/06-tags.md
  packages/tables/docs/03-columns/07-color.md
  packages/tables/docs/03-columns/08-select.md
  packages/tables/docs/03-columns/09-toggle.md
  packages/tables/docs/03-columns/10-text-input.md
  packages/tables/docs/03-columns/11-checkbox.md
  packages/tables/docs/03-columns/12-custom.md
  packages/tables/docs/03-columns/13-relationships.md
  packages/tables/resources/views/columns/boolean-column.blade.php
  packages/tables/src/Columns/BooleanColumn.php
  packages/tables/src/Columns/IconColumn.php
  tests/src/Tables/Fixtures/PostsTable.php
Labels: chore

#4433 feature: Halt
  packages/admin/.stubs.php
  packages/admin/docs/02-resources/02-listing-records.md
  packages/admin/docs/02-resources/03-creating-records.md
  packages/admin/docs/02-resources/04-editing-records.md
  packages/admin/docs/02-resources/06-relation-managers.md
  packages/admin/src/Pages/Actions/CreateAction.php
  packages/admin/src/Pages/Concerns/HasActions.php
  packages/admin/src/Pages/Page.php
  packages/admin/src/Resources/Pages/CreateRecord.php
  packages/admin/src/Resources/Pages/EditRecord.php
  packages/admin/src/Resources/Pages/ListRecords/Concerns/CanCreateRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanAssociateRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanAttachRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanCreateRecords.php
  packages/admin/src/Testing/TestsPageActions.php
  packages/forms/src/Concerns/HasFormComponentActions.php
  packages/support/src/Actions/Action.php
  packages/support/src/Actions/Exceptions/Hold.php
  packages/support/src/Exceptions/Halt.php
  packages/tables/.stubs.php
  packages/tables/src/Actions/AssociateAction.php
  packages/tables/src/Actions/AttachAction.php
  packages/tables/src/Actions/CreateAction.php
  packages/tables/src/Concerns/HasActions.php
  packages/tables/src/Concerns/HasBulkActions.php
  packages/tables/src/Testing/TestsActions.php
  packages/tables/src/Testing/TestsBulkActions.php
  tests/src/Admin/Fixtures/Pages/PageActions.php
  tests/src/Admin/Fixtures/Resources/ProductResource/Pages/CreateProduct.php
  tests/src/Admin/Pages/ActionTest.php
  tests/src/Tables/ActionTest.php
  tests/src/Tables/BulkActionTest.php
  tests/src/Tables/Fixtures/PostsTable.php
Labels: enhancement

#4434 fix: Grid layout docs
  packages/tables/docs/06-layout.md
Labels: documentation

#4436 fix: Icon column boolean docs
  packages/tables/docs/03-columns/03-icon.md
Labels: documentation

#4437 Add french translations
  packages/forms/resources/lang/fr/components.php
  packages/tables/resources/lang/fr/table.php
Labels: i18n

#4438 feature: Access record from repeater mutate save
  packages/forms/src/Components/Repeater.php
Labels: enhancement

#4439 fix: Toggle column indentation
  packages/tables/resources/views/columns/toggle-column.blade.php
Labels: code quality

#4428 Allow customizing IconColumn size
  packages/tables/docs/03-columns/03-icon.md
  packages/tables/resources/views/columns/icon-column.blade.php
  packages/tables/src/Columns/IconColumn.php
Labels: enhancement

#4430 Cancel on edit/create page redirects to previous page.
  packages/admin/docs/02-resources/03-creating-records.md
  packages/admin/docs/02-resources/04-editing-records.md
  packages/admin/src/Resources/Pages/CreateRecord.php
  packages/admin/src/Resources/Pages/EditRecord.php
Labels: enhancement

#4441 feature: Cancel actions
  packages/admin/docs/02-resources/02-listing-records.md
  packages/admin/docs/02-resources/06-relation-managers.md
  packages/admin/src/Pages/Concerns/HasActions.php
  packages/forms/src/Concerns/HasFormComponentActions.php
  packages/support/src/Actions/Action.php
  packages/support/src/Exceptions/Cancel.php
  packages/tables/src/Concerns/HasActions.php
  packages/tables/src/Concerns/HasBulkActions.php
Labels: enhancement

#4440 feature: MorphToSelect
  packages/admin/docs/02-resources/01-getting-started.md
  packages/forms/docs/03-fields.md
  packages/forms/src/Components/Concerns/CanAllowHtml.php
  packages/forms/src/Components/Concerns/CanBePreloaded.php
  packages/forms/src/Components/Concerns/CanBeSearchable.php
  packages/forms/src/Components/Concerns/HasLabel.php
  packages/forms/src/Components/Concerns/HasLoadingMessage.php
  packages/forms/src/Components/Concerns/HasOptions.php
  packages/forms/src/Components/Field.php
  packages/forms/src/Components/MorphToSelect.php
  packages/forms/src/Components/MorphToSelect/Type.php
  packages/forms/src/Components/Select.php
Labels: enhancement

#4443 fix: Slide over backdrop padding
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/mix-manifest.json
  packages/support/resources/views/components/modal/index.blade.php
Labels: bug

#4445 fix: Action forms for column action
  packages/admin/src/Resources/Pages/ListRecords.php
  packages/tables/src/Concerns/HasColumns.php
Labels: bug

#4448 Fix link target in column
  packages/tables/resources/views/components/columns/column.blade.php
Labels: bug

#4444 feature: Send notifications from JavaScript
  package-lock.json
  package.json
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/notifications/dist/module.esm.js
  packages/notifications/docs/02-sending-notifications.md
  packages/notifications/resources/js/Notification.js
  packages/notifications/resources/js/components/notification.js
  packages/notifications/resources/js/index.js
  packages/notifications/src/Actions/Action.php
  packages/notifications/src/Actions/ActionGroup.php
  packages/notifications/src/Concerns/HasDuration.php
  packages/notifications/src/Http/Livewire/Notifications.php
  packages/notifications/src/Notification.php
Labels: enhancement

#4453 fix: Select validation border
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.css
  packages/forms/resources/css/components/select.css
  packages/forms/resources/views/components/select.blade.php
Labels: bug

#4454 fix: Duplicate column action objects
  packages/tables/src/Concerns/HasActions.php
Labels: bug

#4466 Add calculated values column to docs
  packages/tables/docs/03-columns/01-getting-started.md
Labels: documentation

#4473 Adding Swahili Translation
  packages/admin/resources/lang/sw/global-search.php
  packages/admin/resources/lang/sw/layout.php
  packages/admin/resources/lang/sw/login.php
  packages/admin/resources/lang/sw/pages/dashboard.php
  packages/admin/resources/lang/sw/resources/pages/create-record.php
  packages/admin/resources/lang/sw/resources/pages/edit-record.php
  packages/admin/resources/lang/sw/resources/pages/list-records.php
  packages/admin/resources/lang/sw/resources/pages/view-record.php
  packages/admin/resources/lang/sw/widgets/account-widget.php
  packages/admin/resources/lang/sw/widgets/filament-info-widget.php
  packages/forms/resources/lang/sw/components.php
  packages/notifications/resources/lang/sw/database.php
  packages/support/resources/lang/sw/actions/associate.php
  packages/support/resources/lang/sw/actions/attach.php
  packages/support/resources/lang/sw/actions/create.php
  packages/support/resources/lang/sw/actions/delete.php
  packages/support/resources/lang/sw/actions/detach.php
  packages/support/resources/lang/sw/actions/dissociate.php
  packages/support/resources/lang/sw/actions/edit.php
  packages/support/resources/lang/sw/actions/force-delete.php
  packages/support/resources/lang/sw/actions/group.php
  packages/support/resources/lang/sw/actions/modal.php
  packages/support/resources/lang/sw/actions/replicate.php
  packages/support/resources/lang/sw/actions/restore.php
  packages/support/resources/lang/sw/actions/view.php
  packages/support/resources/lang/sw/components/button.php
  packages/support/resources/lang/sw/components/modal.php
  packages/tables/resources/lang/sw/table.php
Labels: i18n

#4470 Update chart-widget.blade.php
  packages/admin/resources/views/widgets/chart-widget.blade.php
Labels: enhancement

#4474 Change env filesystem driver to disk
  packages/admin/config/filament.php
  packages/forms/config/forms.php
  packages/tables/config/tables.php
Labels: chore

#4478 Rename filters layout popover to dropdown
  packages/admin/docs/02-resources/02-listing-records.md
  packages/tables/docs/04-filters.md
  packages/tables/resources/views/components/filters/dropdown.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Filters/Layout.php
  packages/tables/src/Table.php
Labels: chore

#4481 Allow customizing entire notification
  packages/admin/docs/02-resources/03-creating-records.md
  packages/admin/docs/02-resources/04-editing-records.md
  packages/admin/docs/02-resources/07-relation-managers.md
  packages/admin/src/Pages/Actions/CreateAction.php
  packages/admin/src/Pages/Actions/DeleteAction.php
  packages/admin/src/Pages/Actions/RestoreAction.php
  packages/admin/src/Resources/Pages/CreateRecord.php
  packages/admin/src/Resources/Pages/EditRecord.php
  packages/admin/src/Resources/Pages/ListRecords.php
  packages/admin/src/Resources/Pages/ListRecords/Concerns/CanCreateRecords.php
  packages/admin/src/Resources/Pages/ListRecords/Concerns/CanDeleteRecords.php
  packages/admin/src/Resources/Pages/ListRecords/Concerns/CanEditRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanAttachRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanCreateRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanDeleteRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanDetachRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanDissociateRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanEditRecords.php
  packages/spatie-laravel-settings-plugin/src/Pages/SettingsPage.php
  packages/support/src/Actions/Action.php
  packages/support/src/Actions/Concerns/CanNotify.php
  packages/support/src/Actions/Concerns/CanReplicateRecords.php
  packages/tables/src/Actions/AssociateAction.php
  packages/tables/src/Actions/AttachAction.php
  packages/tables/src/Actions/CreateAction.php
  packages/tables/src/Actions/DeleteAction.php
  packages/tables/src/Actions/DeleteBulkAction.php
  packages/tables/src/Actions/DetachAction.php
  packages/tables/src/Actions/DetachBulkAction.php
  packages/tables/src/Actions/DissociateAction.php
  packages/tables/src/Actions/DissociateBulkAction.php
  packages/tables/src/Actions/EditAction.php
  packages/tables/src/Actions/ForceDeleteAction.php
  packages/tables/src/Actions/ForceDeleteBulkAction.php
  packages/tables/src/Actions/RestoreAction.php
  packages/tables/src/Actions/RestoreBulkAction.php
Labels: enhancement

#4487 Fix save notification docs
  packages/admin/docs/02-resources/03-creating-records.md
Labels: documentation

#4488 Fix edit page saved notification title
  packages/admin/src/Resources/Pages/EditRecord.php
Labels: chore

#4489 Revert "small avatar image, bg-primary background"
  packages/admin/resources/views/components/user-avatar.blade.php
  packages/admin/src/AvatarProviders/UiAvatarsProvider.php
Labels: bug

#4494 Add `fa` translation for notification package
  packages/notifications/resources/lang/fa/database.php
Labels: i18n

#4495 Fix wrong method name used in docs
  packages/admin/docs/02-resources/02-listing-records.md
Labels: bug, documentation

#4498 Fix builder create button z-index
  packages/forms/resources/views/components/builder.blade.php
Labels: bug

#4500 🤏 small typo under authorizing soft deletes
  packages/admin/docs/02-resources/06-deleting-records.md
Labels: documentation

#4465 fix: View components
  packages/support/src/Actions/BaseAction.php
  packages/support/src/Components/ViewComponent.php
Labels: bug

#4503 Remove dropdown item Blade component
  packages/admin/resources/views/components/dropdown/item.blade.php
  packages/forms/resources/views/components/dropdown/item.blade.php
  packages/notifications/resources/views/components/dropdown/item.blade.php
  packages/support/resources/views/components/dropdown/item.blade.php
  packages/support/resources/views/components/dropdown/list/item.blade.php
  packages/tables/resources/views/components/dropdown/item.blade.php
Labels: chore

#4504 Remove call to `before` in `Resource::can`
  packages/admin/src/Resources/RelationManagers/RelationManager.php
  packages/admin/src/Resources/Resource.php
Labels: bug

#4510 Update Type.php
  packages/forms/src/Components/MorphToSelect/Type.php
Labels: bug

#4514 Use Blade svg helper instead of components for icons
  packages/admin/resources/views/components/global-search/input.blade.php
  packages/admin/resources/views/components/layouts/app/sidebar/group.blade.php
  packages/admin/resources/views/components/layouts/app/sidebar/index.blade.php
  packages/admin/resources/views/components/layouts/app/sidebar/item.blade.php
  packages/admin/resources/views/components/stats/card.blade.php
  packages/admin/resources/views/components/topbar.blade.php
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/color-picker.blade.php
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/resources/views/components/field-wrapper/hint.blade.php
  packages/forms/resources/views/components/key-value.blade.php
  packages/forms/resources/views/components/repeater.blade.php
  packages/forms/resources/views/components/section.blade.php
  packages/forms/resources/views/components/select.blade.php
  packages/forms/resources/views/components/tabs.blade.php
  packages/forms/resources/views/components/tags-input.blade.php
  packages/forms/resources/views/components/text-input.blade.php
  packages/forms/resources/views/components/toggle.blade.php
  packages/forms/resources/views/components/wizard.blade.php
  packages/notifications/resources/views/components/close-button.blade.php
  packages/notifications/resources/views/components/database/modal/empty-state.blade.php
  packages/notifications/resources/views/components/icon.blade.php
  packages/support/resources/views/components/button.blade.php
  packages/support/resources/views/components/dropdown/header.blade.php
  packages/support/resources/views/components/dropdown/list/item.blade.php
  packages/support/resources/views/components/icon-button.blade.php
  packages/support/resources/views/components/link.blade.php
  packages/support/resources/views/components/modal/index.blade.php
  packages/tables/resources/views/columns/badge-column.blade.php
  packages/tables/resources/views/columns/icon-column.blade.php
  packages/tables/resources/views/columns/text-column.blade.php
  packages/tables/resources/views/columns/toggle-column.blade.php
  packages/tables/resources/views/components/empty-state/index.blade.php
  packages/tables/resources/views/components/filters/indicators.blade.php
  packages/tables/resources/views/components/header-cell.blade.php
  packages/tables/resources/views/components/pagination/item.blade.php
  packages/tables/resources/views/components/reorder/handle.blade.php
  packages/tables/resources/views/components/search-input.blade.php
Labels: bug

#4520 fix: give computed properties a higher precedence than forms
  packages/forms/src/Concerns/InteractsWithForms.php
  tests/src/Forms/ComputedPropertyTest.php
Labels: bug

#4505 Make Resource Macroable
  packages/admin/src/Resources/Resource.php
Labels: enhancement

#4517 Allow the tel regex to be overridden.
  packages/forms/docs/03-fields.md
  packages/forms/src/Components/TextInput.php
Labels: enhancement

#4538 add greek language to admin
  packages/admin/resources/lang/el/global-search.php
  packages/admin/resources/lang/el/layout.php
  packages/admin/resources/lang/el/login.php
  packages/admin/resources/lang/el/pages/dashboard.php
  packages/admin/resources/lang/el/resources/pages/create-record.php
  packages/admin/resources/lang/el/resources/pages/edit-record.php
  packages/admin/resources/lang/el/resources/pages/list-records.php
  packages/admin/resources/lang/el/resources/pages/view-record.php
  packages/admin/resources/lang/el/widgets/account-widget.php
  packages/admin/resources/lang/el/widgets/filament-info-widget.php
Labels: i18n

#4542 Add hint action to inline field wrapper props
  packages/forms/resources/views/components/field-wrapper/inline.blade.php
Labels: bug

#4530 new Section::make()->aside() to align Heading & Description
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.js
  packages/forms/docs/04-layout.md
  packages/forms/resources/views/components/section.blade.php
  packages/forms/src/Components/Section.php
Labels: enhancement

#4551 Danish translations for the Admin and Notification package
  packages/admin/resources/lang/da/global-search.php
  packages/admin/resources/lang/da/layout.php
  packages/admin/resources/lang/da/login.php
  packages/admin/resources/lang/da/pages/dashboard.php
  packages/admin/resources/lang/da/resources/pages/create-record.php
  packages/admin/resources/lang/da/resources/pages/edit-record.php
  packages/admin/resources/lang/da/resources/pages/list-records.php
  packages/admin/resources/lang/da/resources/pages/view-record.php
  packages/admin/resources/lang/da/widgets/account-widget.php
  packages/admin/resources/lang/da/widgets/filament-info-widget.php
  packages/notifications/resources/lang/da/database.php
Labels: i18n

#4552 Fix minor typo
  packages/forms/docs/03-fields.md
Labels: documentation

#4554 Add Danish translations
  packages/spatie-laravel-settings-plugin/resources/lang/da/pages/settings-page.php
  packages/spatie-laravel-translatable-plugin/resources/lang/da/actions.php
  packages/tables/resources/lang/da/table.php
Labels: i18n

#4555 Add missing imports to navigation docs
  packages/admin/docs/05-navigation.md
Labels: documentation

#4558 Add lithuanian language
  packages/admin/resources/lang/lt/global-search.php
  packages/admin/resources/lang/lt/layout.php
  packages/admin/resources/lang/lt/login.php
  packages/admin/resources/lang/lt/pages/dashboard.php
  packages/admin/resources/lang/lt/resources/pages/create-record.php
  packages/admin/resources/lang/lt/resources/pages/edit-record.php
  packages/admin/resources/lang/lt/resources/pages/list-records.php
  packages/admin/resources/lang/lt/resources/pages/view-record.php
  packages/admin/resources/lang/lt/widgets/account-widget.php
  packages/admin/resources/lang/lt/widgets/filament-info-widget.php
  packages/forms/resources/lang/lt/components.php
  packages/spatie-laravel-settings-plugin/resources/lang/lt/pages/settings-page.php
  packages/spatie-laravel-translatable-plugin/resources/lang/lt/actions.php
  packages/support/resources/lang/lt/actions/associate.php
  packages/support/resources/lang/lt/actions/attach.php
  packages/support/resources/lang/lt/actions/create.php
  packages/support/resources/lang/lt/actions/delete.php
  packages/support/resources/lang/lt/actions/detach.php
  packages/support/resources/lang/lt/actions/dissociate.php
  packages/support/resources/lang/lt/actions/edit.php
  packages/support/resources/lang/lt/actions/force-delete.php
  packages/support/resources/lang/lt/actions/group.php
  packages/support/resources/lang/lt/actions/modal.php
  packages/support/resources/lang/lt/actions/replicate.php
  packages/support/resources/lang/lt/actions/restore.php
  packages/support/resources/lang/lt/actions/view.php
  packages/support/resources/lang/lt/components/button.php
  packages/support/resources/lang/lt/components/modal.php
  packages/tables/resources/lang/lt/table.php
Labels: i18n

#4560 fix modal slide over with RTL direction
  packages/support/resources/views/components/modal/index.blade.php
Labels: i18n

#4564 fix: Forms docs view field highlighting
  packages/forms/docs/03-fields.md
Labels: bug, documentation

#4562 fix: Hide chart widget divider if it has no header
  packages/admin/resources/views/widgets/chart-widget.blade.php
Labels: bug

#4565 Use dynamic field wrapper for fields
  packages/forms/docs/03-fields.md
  packages/forms/stubs/FieldView.stub
Labels: bug

#4581 add new DE translations
  packages/forms/resources/lang/de/components.php
Labels: i18n

#4592 Fix: German translation strings
  packages/forms/resources/lang/de/components.php
Labels: i18n

#4594 Fix order of German translations
  packages/forms/resources/lang/de/components.php
Labels: i18n

#4598 Fix imports in docs
  packages/app/docs/02-resources/01-getting-started.md
  packages/app/docs/02-resources/02-listing-records.md
  packages/app/docs/02-resources/05-viewing-records.md
  packages/app/docs/02-resources/06-deleting-records.md
  packages/app/docs/02-resources/07-relation-managers.md
Labels: documentation

#4557 Allow controlling if a field is marked as required
  packages/forms/docs/03-fields.md
  packages/forms/resources/views/components/field-wrapper/index.blade.php
  packages/forms/resources/views/components/field-wrapper/inline.blade.php
  packages/forms/resources/views/components/field-wrapper/label.blade.php
  packages/forms/src/Components/Concerns/CanBeMarkedAsRequired.php
  packages/forms/src/Components/Field.php
Labels: enhancement

#4584 fix: Allow disabling icon button using Alpine.js
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.js
  packages/support/resources/views/components/icon-button.blade.php
Labels: bug

#4603 Fix actions typos
  packages/actions/resources/views/button-action.blade.php
  packages/actions/resources/views/grouped-action.blade.php
  packages/actions/resources/views/icon-button-action.blade.php
  packages/actions/resources/views/link-action.blade.php
  packages/actions/src/Action.php
  packages/actions/src/ActionGroup.php
  packages/actions/src/SelectAction.php
Labels: bug

#4604 Fix double return typo in navigation docs
  packages/admin/docs/02-resources/01-getting-started.md
Labels: documentation

#4611 Update Dusk selectors
  packages/actions/resources/views/components/action.blade.php
  packages/forms/resources/views/components/actions/action.blade.php
Labels: chore

#4622 Add reorder button label to key-value form field
  packages/forms/resources/lang/en/components.php
  packages/forms/resources/lang/nl/components.php
  packages/forms/resources/views/components/key-value.blade.php
  packages/forms/src/Components/KeyValue.php
Labels: bug

#4624 lang: update pl translation
  packages/forms/resources/lang/pl/components.php
Labels: i18n

#4626 update french translation
  packages/forms/resources/lang/fr/components.php
Labels: i18n

#4627 Update spanish translations
  packages/forms/resources/lang/es/components.php
Labels: i18n

#4631 lang(cs): added missing translations
  packages/admin/resources/lang/cs/layout.php
  packages/admin/resources/lang/cs/resources/pages/edit-record.php
  packages/admin/resources/lang/cs/resources/pages/view-record.php
  packages/forms/resources/lang/cs/components.php
  packages/support/resources/lang/cs/actions/replicate.php
  packages/tables/resources/lang/cs/table.php
Labels: i18n

#4630 Finnish translation
  packages/admin/resources/lang/fi/global-search.php
  packages/admin/resources/lang/fi/layout.php
  packages/admin/resources/lang/fi/login.php
  packages/admin/resources/lang/fi/pages/dashboard.php
  packages/admin/resources/lang/fi/resources/pages/create-record.php
  packages/admin/resources/lang/fi/resources/pages/edit-record.php
  packages/admin/resources/lang/fi/resources/pages/list-records.php
  packages/admin/resources/lang/fi/resources/pages/view-record.php
  packages/admin/resources/lang/fi/widgets/account-widget.php
  packages/admin/resources/lang/fi/widgets/filament-info-widget.php
  packages/forms/resources/js/components/date-time-picker.js
  packages/forms/resources/js/components/file-upload.js
  packages/forms/resources/lang/fi/components.php
  packages/notifications/resources/lang/fi/database.php
  packages/spatie-laravel-settings-plugin/resources/lang/fi/pages/settings-page.php
  packages/spatie-laravel-translatable-plugin/resources/lang/fi/actions.php
  packages/support/resources/lang/fi/actions/associate.php
  packages/support/resources/lang/fi/actions/attach.php
  packages/support/resources/lang/fi/actions/create.php
  packages/support/resources/lang/fi/actions/delete.php
  packages/support/resources/lang/fi/actions/detach.php
  packages/support/resources/lang/fi/actions/dissociate.php
  packages/support/resources/lang/fi/actions/edit.php
  packages/support/resources/lang/fi/actions/force-delete.php
  packages/support/resources/lang/fi/actions/group.php
  packages/support/resources/lang/fi/actions/modal.php
  packages/support/resources/lang/fi/actions/replicate.php
  packages/support/resources/lang/fi/actions/restore.php
  packages/support/resources/lang/fi/actions/view.php
  packages/support/resources/lang/fi/components/button.php
  packages/tables/resources/lang/fi/table.php
Labels: i18n

#4612 Icon manager
  packages/app/resources/views/components/global-search/input.blade.php
  packages/app/resources/views/components/layouts/app/sidebar/group.blade.php
  packages/app/resources/views/components/layouts/app/sidebar/index.blade.php
  packages/app/resources/views/components/layouts/app/sidebar/item.blade.php
  packages/app/resources/views/components/stats/card.blade.php
  packages/app/resources/views/components/topbar.blade.php
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/color-picker.blade.php
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/resources/views/components/field-wrapper/hint.blade.php
  packages/forms/resources/views/components/key-value.blade.php
  packages/forms/resources/views/components/repeater.blade.php
  packages/forms/resources/views/components/section.blade.php
  packages/forms/resources/views/components/tabs.blade.php
  packages/forms/resources/views/components/tags-input.blade.php
  packages/forms/resources/views/components/toggle.blade.php
  packages/forms/resources/views/components/wizard.blade.php
  packages/notifications/resources/views/components/close-button.blade.php
  packages/notifications/resources/views/components/database/modal/empty-state.blade.php
  packages/notifications/resources/views/components/icon.blade.php
  packages/support/composer.json
  packages/support/resources/views/components/button.blade.php
  packages/support/resources/views/components/dropdown/header.blade.php
  packages/support/resources/views/components/dropdown/list/item.blade.php
  packages/support/resources/views/components/icon-button.blade.php
  packages/support/resources/views/components/icon.blade.php
  packages/support/resources/views/components/input/affixes.blade.php
  packages/support/resources/views/components/link.blade.php
  packages/support/resources/views/components/modal/index.blade.php
  packages/support/src/Facades/Icon.php
  packages/support/src/Icons/Icon.php
  packages/support/src/Icons/IconManager.php
  packages/support/src/SupportServiceProvider.php
  packages/tables/resources/views/columns/badge-column.blade.php
  packages/tables/resources/views/columns/icon-column.blade.php
  packages/tables/resources/views/columns/text-column.blade.php
  packages/tables/resources/views/columns/toggle-column.blade.php
  packages/tables/resources/views/components/empty-state/index.blade.php
  packages/tables/resources/views/components/filters/indicators.blade.php
  packages/tables/resources/views/components/header-cell.blade.php
  packages/tables/resources/views/components/pagination/item.blade.php
  packages/tables/resources/views/components/reorder/handle.blade.php
  packages/tables/resources/views/components/search-input.blade.php
Labels: enhancement

#4632 Fix/pluralization
  packages/forms/src/Components/Select.php
Labels: enhancement

#4633 lang(cs): added pluralization
  packages/forms/resources/lang/cs/components.php
  packages/tables/resources/lang/cs/table.php
Labels: i18n

#4634 update `pt_BR` translations
  packages/forms/resources/lang/pt_BR/components.php
Labels: i18n

#4641 Add missing Arabic translations
  packages/forms/resources/lang/ar/components.php
  packages/forms/resources/views/components/key-value.blade.php
Labels: i18n

#4668 Update id translation
  packages/forms/resources/lang/id/components.php
Labels: i18n

#4665 Remove required asterisk for disabled field
  packages/forms/resources/views/components/field-wrapper/index.blade.php
  packages/forms/resources/views/components/field-wrapper/inline.blade.php
  packages/forms/resources/views/components/field-wrapper/label.blade.php
Labels: bug

#4569 Replaced load with loadMissing to reduce queries
  packages/spatie-laravel-tags-plugin/src/Forms/Components/SpatieTagsInput.php
Labels: bug

#4568 Replaced load with loadMissing
  packages/spatie-laravel-media-library-plugin/src/Forms/Components/SpatieMediaLibraryFileUpload.php
Labels: bug

#4672 Show a failure message if (soft)delete / restore isn't successful
  packages/admin/src/Pages/Actions/DeleteAction.php
  packages/admin/src/Pages/Actions/ForceDeleteAction.php
  packages/admin/src/Pages/Actions/RestoreAction.php
  packages/tables/src/Actions/DeleteAction.php
  packages/tables/src/Actions/ForceDeleteAction.php
  packages/tables/src/Actions/RestoreAction.php
Labels: bug

#4649 Add page subtitle
  packages/admin/resources/views/components/header/heading.blade.php
  packages/admin/resources/views/components/header/index.blade.php
  packages/admin/resources/views/components/header/subheading.blade.php
  packages/admin/resources/views/components/page.blade.php
  packages/admin/src/Pages/Page.php
Labels: enhancement

#4677 update danharrin / date-format-converter to v0.3
  packages/forms/composer.json
Labels: chore

#4679 [ms] Add reorder button label
  packages/forms/resources/lang/ms/components.php
Labels: i18n

#4674 Fix: padding when action is set to slideover
  packages/support/resources/views/components/modal/index.blade.php
Labels: bug

#4675 Fix dropdown item label from truncating too early
  packages/support/resources/views/components/dropdown/list/item.blade.php
Labels: bug

#4693 Require `doctrine/dbal` as development dependency
  packages/admin/docs/02-resources/01-getting-started.md
Labels: documentation

#4695 Update Romanian translations
  packages/admin/resources/lang/ro/layout.php
  packages/admin/resources/lang/ro/resources/pages/create-record.php
  packages/admin/resources/lang/ro/resources/pages/edit-record.php
  packages/admin/resources/lang/ro/resources/pages/view-record.php
  packages/forms/resources/lang/ro/components.php
  packages/tables/resources/lang/ro/table.php
Labels: i18n

#4690 Only render visible widgets
  packages/admin/resources/views/components/page.blade.php
  packages/admin/src/Pages/Page.php
Labels: bug

#4700 Move validation attributes to validation docs
  packages/forms/docs/03-fields.md
  packages/forms/docs/05-validation.md
Labels: documentation

#4661 Improve accessibility around the user menu avatar
  packages/admin/resources/lang/ar/layout.php
  packages/admin/resources/lang/bn/layout.php
  packages/admin/resources/lang/bs/layout.php
  packages/admin/resources/lang/cs/layout.php
  packages/admin/resources/lang/da/layout.php
  packages/admin/resources/lang/de/layout.php
  packages/admin/resources/lang/el/layout.php
  packages/admin/resources/lang/en/layout.php
  packages/admin/resources/lang/es/layout.php
  packages/admin/resources/lang/fa/layout.php
  packages/admin/resources/lang/fi/layout.php
  packages/admin/resources/lang/fr/layout.php
  packages/admin/resources/lang/he/layout.php
  packages/admin/resources/lang/hi/layout.php
  packages/admin/resources/lang/hu/layout.php
  packages/admin/resources/lang/hy/layout.php
  packages/admin/resources/lang/id/layout.php
  packages/admin/resources/lang/it/layout.php
  packages/admin/resources/lang/ja/layout.php
  packages/admin/resources/lang/km/layout.php
  packages/admin/resources/lang/ko/layout.php
  packages/admin/resources/lang/ku/layout.php
  packages/admin/resources/lang/lt/layout.php
  packages/admin/resources/lang/ms/layout.php
  packages/admin/resources/lang/my/layout.php
  packages/admin/resources/lang/nl/layout.php
  packages/admin/resources/lang/pl/layout.php
  packages/admin/resources/lang/pt_BR/layout.php
  packages/admin/resources/lang/pt_PT/layout.php
  packages/admin/resources/lang/ro/layout.php
  packages/admin/resources/lang/ru/layout.php
  packages/admin/resources/lang/sv/layout.php
  packages/admin/resources/lang/sw/layout.php
  packages/admin/resources/lang/tr/layout.php
  packages/admin/resources/lang/uk/layout.php
  packages/admin/resources/lang/vi/layout.php
  packages/admin/resources/lang/zh_CN/layout.php
  packages/admin/resources/lang/zh_TW/layout.php
  packages/admin/resources/views/components/layouts/app/topbar/user-menu.blade.php
Labels: enhancement

#4715 feature: form builder testing helpers
  composer.lock
  packages/admin/.stubs.php
  packages/admin/src/FilamentServiceProvider.php
  packages/admin/src/Testing/TestsPages.php
  packages/forms/.stubs.php
  packages/forms/docs/07-testing.md
  packages/forms/src/Testing/TestsForms.php
Labels: enhancement

#4718 Update Swedish translations
  packages/admin/resources/lang/sv/layout.php
  packages/admin/resources/lang/sv/resources/pages/edit-record.php
  packages/admin/resources/lang/sv/resources/pages/view-record.php
  packages/forms/resources/lang/sv/components.php
  packages/notifications/resources/lang/sv/database.php
  packages/spatie-laravel-settings-plugin/resources/lang/sv/pages/settings-page.php
  packages/support/resources/lang/sv/actions/edit.php
  packages/support/resources/lang/sv/components/modal.php
  packages/tables/resources/lang/sv/table.php
Labels: i18n

#4723 Add missing builder create item between translation
  packages/forms/resources/lang/en/components.php
  packages/forms/resources/lang/nl/components.php
Labels: i18n

#4724 Add missing spanish translation
  packages/forms/resources/lang/es/components.php
Labels: i18n

#4725 Adds missing FA translations
  packages/forms/resources/lang/fa/components.php
Labels: i18n

#4731 Adds all missing FA translations across all filament packages.
  packages/admin/resources/lang/fa/layout.php
  packages/admin/resources/lang/fa/resources/pages/edit-record.php
  packages/admin/resources/lang/fa/resources/pages/view-record.php
  packages/forms/resources/lang/fa/components.php
  packages/tables/resources/lang/fa/table.php
Labels: i18n

#4732 add missing pt_BR translations
  packages/forms/resources/lang/pt_BR/components.php
Labels: i18n

#4571 Use config path for make commands
  packages/admin/src/Commands/MakePageCommand.php
  packages/admin/src/Commands/MakeResourceCommand.php
  packages/admin/src/Commands/MakeWidgetCommand.php
  packages/admin/stubs/CustomResourcePage.stub
  packages/admin/stubs/Resource.stub
  packages/admin/stubs/ResourceEditPage.stub
  packages/admin/stubs/ResourceListPage.stub
  packages/admin/stubs/ResourceManagePage.stub
  packages/admin/stubs/ResourcePage.stub
  packages/admin/stubs/ResourceViewPage.stub
Labels: bug

#4736 Update fi translation
  packages/forms/resources/lang/fi/components.php
  packages/support/resources/lang/fi/components/modal.php
Labels: i18n

#4738 Add missing builder create item between swahili translation
  packages/forms/resources/lang/sw/components.php
Labels: i18n

#4740 Fix subheading element
  packages/admin/resources/views/components/header/subheading.blade.php
  packages/support/resources/views/components/modal/subheading.blade.php
Labels: bug

#4741 Accept HtmlString for page headings
  packages/admin/src/Pages/Page.php
Labels: enhancement

#4753 UI tweaks
  packages/app/resources/views/components/card/index.blade.php
  packages/app/resources/views/components/global-search/results-container.blade.php
  packages/app/resources/views/components/layouts/app/sidebar/item.blade.php
  packages/app/resources/views/components/layouts/card.blade.php
  packages/app/resources/views/widgets/account-widget.blade.php
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/card.blade.php
  packages/forms/resources/views/components/repeater.blade.php
  packages/forms/resources/views/components/section.blade.php
  packages/notifications/resources/views/notification.blade.php
  packages/support/resources/views/components/dropdown/index.blade.php
  packages/tables/resources/views/columns/text-column.blade.php
  packages/tables/resources/views/components/container.blade.php
  packages/tables/resources/views/components/header/heading.blade.php
  packages/widgets/resources/views/chart-widget.blade.php
  packages/widgets/resources/views/components/card/index.blade.php
  packages/widgets/resources/views/components/stats/card.blade.php
Labels: ui

#4750 Fix: Add id for dom diff
  packages/tables/resources/views/components/selection-indicator.blade.php
Labels: bug

#4762 Add missing translations for Arabic
  packages/forms/resources/lang/ar/components.php
Labels: i18n

#4756 Add square column option
  packages/tables/docs/02-getting-started.md
  packages/tables/docs/03-columns/04-image.md
  packages/tables/resources/views/columns/image-column.blade.php
  packages/tables/src/Columns/ImageColumn.php
Labels: enhancement

#4765 Add ";"
  packages/tables/docs/03-columns/07-color.md
Labels: documentation

#4468 Fix session fixation when using multiguard
  packages/admin/src/Http/Livewire/Auth/Login.php
Labels: bug
