Repository filamentphp/filament, pull requests merged in 2022-04, with the labels that each got.

#2084 View Page Title Improvement
  packages/admin/resources/lang/ar/resources/pages/view-record.php
  packages/admin/resources/lang/cs/resources/pages/view-record.php
  packages/admin/resources/lang/de/resources/pages/view-record.php
  packages/admin/resources/lang/en/resources/pages/view-record.php
  packages/admin/resources/lang/es/resources/pages/view-record.php
  packages/admin/resources/lang/fa/resources/pages/view-record.php
  packages/admin/resources/lang/fr/resources/pages/view-record.php
  packages/admin/resources/lang/hi/resources/pages/view-record.php
  packages/admin/resources/lang/id/resources/pages/view-record.php
  packages/admin/resources/lang/it/resources/pages/view-record.php
  packages/admin/resources/lang/kh/resources/pages/view-record.php
  packages/admin/resources/lang/ko/resources/pages/view-record.php
  packages/admin/resources/lang/ku/resources/pages/view-record.php
  packages/admin/resources/lang/ms/resources/pages/view-record.php
  packages/admin/resources/lang/nl/resources/pages/view-record.php
  packages/admin/resources/lang/pl/resources/pages/view-record.php
  packages/admin/resources/lang/pt_BR/resources/pages/view-record.php
  packages/admin/resources/lang/pt_PT/resources/pages/view-record.php
  packages/admin/resources/lang/ru/resources/pages/view-record.php
  packages/admin/resources/lang/sv/resources/pages/view-record.php
  packages/admin/resources/lang/tr/resources/pages/edit-record.php
  packages/admin/resources/lang/tr/resources/pages/view-record.php
  packages/admin/resources/lang/vi/resources/pages/view-record.php
  packages/admin/resources/lang/zh_CN/resources/pages/view-record.php
  packages/admin/src/Resources/Pages/ViewRecord.php
Labels: enhancement

#2075 Improve editor preview when using ViewRecord
  packages/forms/resources/views/components/markdown-editor.blade.php
  packages/forms/resources/views/components/rich-editor.blade.php
Labels: enhancement, ui

#2091 Update burmese translation
  packages/admin/resources/lang/my/global-search.php
  packages/admin/resources/lang/my/layout.php
  packages/admin/resources/lang/my/login.php
  packages/admin/resources/lang/my/pages/actions.php
  packages/admin/resources/lang/my/pages/dashboard.php
  packages/admin/resources/lang/my/resources/pages/create-record.php
  packages/admin/resources/lang/my/resources/pages/edit-record.php
  packages/admin/resources/lang/my/resources/pages/list-records.php
  packages/admin/resources/lang/my/resources/pages/view-record.php
  packages/admin/resources/lang/my/resources/relation-managers/associate.php
  packages/admin/resources/lang/my/resources/relation-managers/attach.php
  packages/admin/resources/lang/my/resources/relation-managers/create.php
  packages/admin/resources/lang/my/resources/relation-managers/delete.php
  packages/admin/resources/lang/my/resources/relation-managers/detach.php
  packages/admin/resources/lang/my/resources/relation-managers/dissociate.php
  packages/admin/resources/lang/my/resources/relation-managers/edit.php
  packages/admin/resources/lang/my/widgets/account-widget.php
  packages/admin/resources/lang/my/widgets/filament-info-widget.php
  packages/forms/resources/lang/my/components.php
Labels: enhancement, i18n

#2094 Fix typos in Table documentation
  packages/tables/docs/02-getting-started.md
Labels: bug, documentation

#2086 feature: support prefixing/suffixing text columns
  packages/tables/src/Columns/Concerns/CanFormatState.php
Labels: enhancement

#2090 feature: allow disabling collapsible nav groups
  packages/admin/resources/views/components/layouts/app/sidebar/group.blade.php
  packages/admin/resources/views/components/layouts/app/sidebar/index.blade.php
  packages/admin/src/FilamentManager.php
  packages/admin/src/Navigation/NavigationBuilder.php
Labels: enhancement

#2089 Remove Unused Method Arguments
  packages/forms/resources/views/components/multi-select.blade.php
  packages/forms/resources/views/components/select.blade.php
Labels: chore

#2087 Expand Available Aggregate Methods for Table Columns
  packages/tables/docs/03-columns.md
  packages/tables/src/Columns/Column.php
  packages/tables/src/Columns/Concerns/CanAggregateRelatedModels.php
  packages/tables/src/Columns/Concerns/CanCountRelatedModels.php
  packages/tables/src/Columns/Concerns/InteractsWithTableQuery.php
  packages/tables/src/Concerns/HasRecords.php
  tests/database/factories/PostFactory.php
  tests/database/migrations/create_posts_table.php
  tests/src/Admin/Fixtures/Resources/PostResource.php
  tests/src/Admin/Fixtures/Resources/UserResource.php
  tests/src/Admin/Fixtures/Resources/UserResource/Pages/CreateUser.php
  tests/src/Admin/Fixtures/Resources/UserResource/Pages/EditUser.php
  tests/src/Admin/Fixtures/Resources/UserResource/Pages/ListUsers.php
  tests/src/Admin/Fixtures/Resources/UserResource/Pages/ViewUser.php
  tests/src/Admin/Resources/Pages/CreateRecordTest.php
  tests/src/Admin/Resources/Pages/ListRecordsTest.php
  tests/src/Admin/Resources/ResourcesServiceProvider.php
  tests/src/Models/User.php
Labels: enhancement

#2096 fix: use `resolveRouteBinding` to resolve model
  packages/admin/src/Resources/Resource.php
Labels: bug

#2018 Clarify Tippy CSS as dependency for collapsible sidebar
  packages/admin/docs/07-appearance.md
Labels: documentation, enhancement

#2088 Improved search variable name for selects
  packages/admin/src/Resources/RelationManagers/Concerns/CanAssociateRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanAttachRecords.php
  packages/forms/docs/03-fields.md
  packages/forms/resources/views/components/multi-select.blade.php
  packages/forms/resources/views/components/select.blade.php
  packages/forms/src/Components/BelongsToManyMultiSelect.php
  packages/forms/src/Components/BelongsToSelect.php
  packages/forms/src/Components/MultiSelect.php
  packages/forms/src/Components/Select.php
  packages/forms/src/Concerns/InteractsWithForms.php
  packages/forms/src/Concerns/SupportsMultiSelectFields.php
  packages/forms/src/Concerns/SupportsSelectFields.php
  packages/forms/src/Contracts/HasForms.php
Labels: enhancement

#2069 set TagsInput webkit-calendar-picker icon to 0 opacity
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/admin/dist/module.esm.css
  packages/admin/dist/module.esm.js
  packages/forms/dist/module.esm.css
  packages/forms/dist/module.esm.js
  packages/forms/resources/css/components/tags-input.css
  packages/forms/resources/js/components/tags-input.js
  packages/forms/resources/views/components/tags-input.blade.php
Labels: bug, ui

#2062 TextInput field tel() method to have basic phone number validation
  packages/forms/src/Components/Concerns/CanBeValidated.php
  packages/forms/src/Components/TextInput.php
Labels: enhancement

#2099 feature: Filter column span
  packages/tables/src/Filters/Concerns/CanSpanColumns.php
  packages/tables/src/Filters/Concerns/HasFormSchema.php
  packages/tables/src/Filters/Filter.php
  packages/tables/src/Filters/MultiSelectFilter.php
  packages/tables/src/Filters/SelectFilter.php
Labels: enhancement

#2027 fix issue #1985 - FileUpload locale not work correctly
  packages/forms/resources/lang/da/components.php
  packages/forms/resources/lang/fa/components.php
  packages/forms/resources/lang/sv/components.php
  packages/forms/resources/views/components/file-upload.blade.php
Labels: bug, i18n

#2100 fix: Don't dehydrate disabled fields
  packages/forms/src/Components/Concerns/CanBeDisabled.php
Labels: bug

#2132 Update simplified Chinese translation files.
  packages/admin/resources/lang/zh_CN/layout.php
  packages/admin/resources/lang/zh_CN/pages/actions.php
  packages/admin/resources/lang/zh_CN/resources/pages/edit-record.php
  packages/admin/resources/lang/zh_CN/resources/pages/list-records.php
  packages/admin/resources/lang/zh_CN/resources/pages/view-record.php
  packages/admin/resources/lang/zh_CN/resources/relation-managers/associate.php
  packages/admin/resources/lang/zh_CN/resources/relation-managers/dissociate.php
  packages/forms/resources/lang/zh_CN/components.php
  packages/spatie-laravel-settings-plugin/resources/lang/zh_CN/pages/settings-page.php
  packages/tables/resources/lang/zh_CN/table.php
Labels: enhancement, i18n

#2137 Feature: Add visible method to Table Filters
  packages/tables/src/Filters/Concerns/CanBeHidden.php
Labels: enhancement

#2130 Merge form rules with Component rules
  packages/forms/src/Concerns/InteractsWithForms.php
Labels: enhancement

#2146 Allow HtmlString for placeholder label
  packages/forms/src/Components/Placeholder.php
Labels: enhancement

#2147 fix: withoutDate() validation
  packages/forms/src/Components/DateTimePicker.php
Labels: bug

#2155 Fix: Add missing disabled classes to toggle.blade.php
  packages/forms/resources/views/components/toggle.blade.php
Labels: enhancement, ui

#2163 Add french translation for associate and dissociate
  packages/admin/resources/lang/fr/resources/relation-managers/associate.php
  packages/admin/resources/lang/fr/resources/relation-managers/dissociate.php
Labels: enhancement, i18n

#2164 fix: Sortable end events bubbling up to parent containers
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/repeater.blade.php
Labels: bug

#2167 Add Spanish translation for associate and dissociate
  packages/admin/resources/lang/es/resources/relation-managers/associate.php
  packages/admin/resources/lang/es/resources/relation-managers/dissociate.php
Labels: enhancement, i18n

#2174 feature: support statically setting nav options
  packages/admin/src/Resources/Resource.php
Labels: enhancement

#2169 Extract user command methods
  packages/admin/src/Commands/MakeUserCommand.php
Labels: enhancement

#1868 Auto detect redirect from Livewire response
  packages/admin/docs/03-pages.md
  packages/admin/resources/views/components/notification-manager.blade.php
  packages/admin/src/FilamentManager.php
  packages/admin/src/FilamentServiceProvider.php
  packages/admin/src/Http/Livewire/Concerns/CanNotify.php
  packages/admin/src/NotificationManager.php
  tests/src/Admin/Fixtures/Pages/Settings.php
  tests/src/Admin/NotificationManager/NotificationManagerServiceProvider.php
  tests/src/Admin/NotificationManager/NotificationManagerTest.php
  tests/src/Admin/NotificationManager/TestCase.php
Labels: enhancement

#2157 fix: Private file temporary URLs
  packages/forms/src/Components/BaseFileUpload.php
  packages/forms/src/Components/Concerns/HasFileAttachments.php
  packages/spatie-laravel-media-library-plugin/src/Forms/Components/SpatieMediaLibraryFileUpload.php
  packages/tables/src/Columns/ImageColumn.php
Labels: bug

#1693 feature: selectable table columns
  composer.lock
  package-lock.json
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/mix-manifest.json
  packages/tables/docs/03-columns.md
  packages/tables/resources/lang/en/table.php
  packages/tables/resources/views/components/toggleable/index.blade.php
  packages/tables/resources/views/components/toggleable/trigger.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Columns/Column.php
  packages/tables/src/Columns/Concerns/CanBeToggled.php
  packages/tables/src/Concerns/CanToggleColumns.php
  packages/tables/src/Concerns/InteractsWithTable.php
  packages/tables/src/Contracts/HasTable.php
  packages/tables/src/Table.php
Labels: enhancement

#2181 feature: render hooks
  packages/admin/src/Facades/Filament.php
  packages/admin/src/FilamentManager.php
  tests/resources/views/fixtures/pages/render-hooks/foo.blade.php
  tests/src/Admin/RenderHooks/RenderHooksServiceProvider.php
  tests/src/Admin/RenderHooks/RenderHooksTest.php
  tests/src/Admin/RenderHooks/TestCase.php
Labels: enhancement

#2184 feature: Add basic render hooks to layout
  packages/admin/docs/07-appearance.md
  packages/admin/resources/views/components/global-search/index.blade.php
  packages/admin/resources/views/components/layouts/app/sidebar/footer.blade.php
  packages/admin/resources/views/components/layouts/app/sidebar/index.blade.php
  packages/admin/resources/views/components/layouts/base.blade.php
Labels: enhancement

#2187 fix: toggleable table columns for nested data
  packages/tables/src/Concerns/CanToggleColumns.php
Labels: bug

#2183 Update InteractsWithTableQuery.php
  packages/tables/src/Columns/Concerns/InteractsWithTableQuery.php
Labels: bug

#2197 Add Japanese translation
  packages/admin/resources/lang/ja/global-search.php
  packages/admin/resources/lang/ja/layout.php
  packages/admin/resources/lang/ja/login.php
  packages/admin/resources/lang/ja/pages/actions.php
  packages/admin/resources/lang/ja/pages/dashboard.php
  packages/admin/resources/lang/ja/resources/pages/create-record.php
  packages/admin/resources/lang/ja/resources/pages/edit-record.php
  packages/admin/resources/lang/ja/resources/pages/list-records.php
  packages/admin/resources/lang/ja/resources/pages/view-record.php
  packages/admin/resources/lang/ja/resources/relation-managers/associate.php
  packages/admin/resources/lang/ja/resources/relation-managers/attach.php
  packages/admin/resources/lang/ja/resources/relation-managers/create.php
  packages/admin/resources/lang/ja/resources/relation-managers/delete.php
  packages/admin/resources/lang/ja/resources/relation-managers/detach.php
  packages/admin/resources/lang/ja/resources/relation-managers/dissociate.php
  packages/admin/resources/lang/ja/resources/relation-managers/edit.php
  packages/admin/resources/lang/ja/widgets/account-widget.php
  packages/admin/resources/lang/ja/widgets/filament-info-widget.php
  packages/forms/resources/lang/ja/components.php
  packages/tables/resources/lang/ja/table.php
Labels: enhancement, ui

#2206 fix: Translatable search
  packages/tables/src/Columns/Concerns/InteractsWithTableQuery.php
Labels: bug

#2210 Multiple image grid layout
  packages/forms/resources/css/components/file-upload.css
Labels: enhancement, ui

#2214 fix: Collapsible groups
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/admin/dist/module.esm.css
  packages/admin/resources/js/app.js
  packages/admin/resources/views/components/layouts/app/sidebar/group.blade.php
  packages/forms/dist/module.esm.css
Labels: bug, ui

#2221 fix: unable to close modal when click on the empty side
  packages/admin/resources/views/components/modal/index.blade.php
  packages/tables/resources/views/components/modal/index.blade.php
Labels: bug

#2223 fix: Resolve route binding through model
  packages/admin/src/Resources/Resource.php
Labels: enhancement

#2225 FIX: SpatieMediaLibraryFileUpload should use existing `getUploadedFil…
  packages/spatie-laravel-media-library-plugin/src/Forms/Components/SpatieMediaLibraryFileUpload.php
Labels: bug

#2216 fix: Nested relationships
  packages/admin/src/Resources/RelationManagers/Concerns/CanAssociateRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanAttachRecords.php
  packages/forms/src/Components/BaseFileUpload.php
  packages/forms/src/Components/BelongsToManyCheckboxList.php
  packages/forms/src/Components/Builder.php
  packages/forms/src/Components/Checkbox.php
  packages/forms/src/Components/CheckboxList.php
  packages/forms/src/Components/Concerns/BelongsToModel.php
  packages/forms/src/Components/Concerns/CanBeAutocapitalized.php
  packages/forms/src/Components/Concerns/CanBeAutocompleted.php
  packages/forms/src/Components/Concerns/CanBeHidden.php
  packages/forms/src/Components/Concerns/CanBeLengthConstrained.php
  packages/forms/src/Components/Concerns/CanBeValidated.php
  packages/forms/src/Components/Concerns/CanLimitItemsLength.php
  packages/forms/src/Components/Contracts/CanBeLengthConstrained.php
  packages/forms/src/Components/DateTimePicker.php
  packages/forms/src/Components/KeyValue.php
  packages/forms/src/Components/MarkdownEditor.php
  packages/forms/src/Components/MultiSelect.php
  packages/forms/src/Components/MultipleFileUpload.php
  packages/forms/src/Components/RelationshipRepeater.php
  packages/forms/src/Components/Repeater.php
  packages/forms/src/Components/RichEditor.php
  packages/forms/src/Components/Select.php
  packages/forms/src/Components/TagsInput.php
  packages/forms/src/Components/TextInput.php
  packages/forms/src/Components/Textarea.php
  packages/forms/src/Components/Toggle.php
  packages/forms/src/Concerns/BelongsToModel.php
  packages/forms/src/Concerns/HasState.php
  packages/spatie-laravel-media-library-plugin/src/Forms/Components/SpatieMediaLibraryFileUpload.php
  packages/spatie-laravel-tags-plugin/src/Forms/Components/SpatieTagsInput.php
  packages/tables/src/Columns/Concerns/CanFormatState.php
  packages/tables/src/Columns/Concerns/HasAlignment.php
  tests/src/Forms/StateTest.php
Labels: bug

#2235 fix: border contrast
  packages/tables/resources/views/components/pagination/records-per-page-selector.blade.php
  packages/tables/resources/views/components/search-input.blade.php
Labels: ui

#2237 fix: Uploaded file URL retrieval with null values
  packages/forms/src/Components/BaseFileUpload.php
Labels: bug

#2246 fix: Custom action views
  packages/admin/src/Pages/Actions/Action.php
  packages/admin/src/Pages/Actions/Modal/Actions/Action.php
  packages/tables/src/Actions/Action.php
  packages/tables/src/Actions/Modal/Actions/Action.php
Labels: bug

#2251 fix: tab.blade.php padding
  packages/forms/resources/views/components/tabs/tab.blade.php
Labels: bug, ui

#2252 fix: Fill ReplicateAction form
  packages/tables/src/Actions/ReplicateAction.php
Labels: bug

#2255 fix: Notifications not showing after redirect.
  packages/admin/resources/views/components/notification-manager.blade.php
Labels: bug

#2262 feature: Customise column query
  packages/tables/docs/03-columns.md
  packages/tables/src/Columns/Concerns/CanBeSearchable.php
  packages/tables/src/Columns/Concerns/CanBeSortable.php
  packages/tables/src/Columns/Concerns/InteractsWithTableQuery.php
Labels: enhancement
