Repository filamentphp/filament, pull requests merged in 2022-09, with the labels that each got.

#3796 fix: Tables empty state description wrap
  packages/tables/resources/views/components/empty-state/description.blade.php
Labels: bug

#3799 fix: Tables empty state max width
  packages/tables/resources/views/components/empty-state/index.blade.php
Labels: bug

#3806 Dev: Allow watch command to watch package scripts too
  package-lock.json
  package.json
Labels: enhancement

#3811 fix: Use of Pest in assertNotified()
  packages/notifications/src/Testing/TestsNotifications.php
Labels: bug

#3805 fix: using record key instead of routeKey
  packages/admin/src/Resources/Pages/EditRecord.php
Labels: bug

#3812 fix: Cloak bulk actions trigger
  packages/tables/resources/views/components/bulk-actions/trigger.blade.php
Labels: bug

#3813 chore: Reorder custom CSS classes
  packages/tables/resources/views/components/filters/indicators.blade.php
  packages/tables/resources/views/components/header/index.blade.php
Labels: chore

#3801 Make tables sort icon stylable
  packages/tables/resources/views/components/header-cell.blade.php
Labels: enhancement

#3789 add pivot property to a record when a relationship is present
  packages/tables/src/Concerns/CanSelectRecords.php
  packages/tables/src/Concerns/HasRecords.php
  packages/tables/src/Concerns/InteractsWithTable.php
Labels: bug

#3792 Document using `wire:model` in view fields
  packages/forms/docs/03-fields.md
Labels: documentation

#3742 Fix/per page option issue
  packages/tables/config/tables.php
  packages/tables/resources/views/components/pagination/records-per-page-selector.blade.php
  packages/tables/src/Concerns/CanPaginateRecords.php
Labels: bug

#3822 Fix: Resource generation apply `maxLength` only on `TextInput` & `Textarea`
  packages/admin/src/Commands/Concerns/CanGenerateResources.php
Labels: bug

#3824 feature: start on wizard step
  packages/admin/src/Resources/Pages/Concerns/HasWizard.php
  packages/support/src/Actions/Concerns/HasForm.php
  packages/support/src/Actions/Concerns/HasWizard.php
Labels: enhancement

#3830 fix: Build commands naming
  package.json
Labels: bug

#3722 Use amber as primary color for Filament admin
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/mix-manifest.json
  packages/admin/resources/views/components/global-search/input.blade.php
  packages/admin/resources/views/components/tabs/item.blade.php
  packages/admin/resources/views/pages/actions/select-action.blade.php
  packages/admin/resources/views/widgets/chart-widget.blade.php
  packages/admin/tailwind.config.js
  packages/forms/dist/module.esm.css
  packages/forms/resources/css/components/select.css
  packages/forms/resources/views/components/color-picker.blade.php
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/resources/views/components/markdown-editor.blade.php
  packages/forms/resources/views/components/rich-editor.blade.php
  packages/forms/resources/views/components/select.blade.php
  packages/forms/resources/views/components/tags-input.blade.php
  packages/forms/resources/views/components/text-input.blade.php
  packages/forms/resources/views/components/textarea.blade.php
  packages/forms/resources/views/components/wizard.blade.php
  packages/tables/resources/views/components/checkbox-cell.blade.php
  packages/tables/resources/views/components/pagination/records-per-page-selector.blade.php
  packages/tables/resources/views/components/reorder/indicator.blade.php
  packages/tables/resources/views/components/search-input.blade.php
  packages/tables/resources/views/components/selection-indicator.blade.php
Labels: ui

#3832 fix: Filter dropdown width
  packages/tables/resources/views/components/filters/popover.blade.php
  packages/tables/resources/views/components/toggleable/index.blade.php
Labels: bug

#3827 fix: Check if allows duplicates before hydrating pivot relation
  packages/tables/src/Concerns/HasRecords.php
  packages/tables/src/Concerns/InteractsWithTable.php
Labels: bug

#3835 Fix: changed from array_merge to array_replace to avoid reindexing in…
  packages/admin/resources/views/components/resources/relation-managers/index.blade.php
Labels: bug

#3740 Make global search case insensitive for translatable json fields
  packages/admin/src/Resources/Resource.php
Labels: enhancement

#3843 chore(lang/pl): translate combined tabs
  packages/admin/resources/lang/pl/resources/pages/edit-record.php
  packages/admin/resources/lang/pl/resources/pages/view-record.php
Labels: i18n

#3844 Add combined form ms translation.
  packages/admin/resources/lang/ms/resources/pages/edit-record.php
  packages/admin/resources/lang/ms/resources/pages/view-record.php
  packages/tables/resources/lang/ms/table.php
Labels: i18n

#3823 New navigation menu button design
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/mix-manifest.json
  packages/admin/resources/views/components/layouts/app.blade.php
  packages/admin/resources/views/components/layouts/app/topbar/collapse-sidebar-button.blade.php
  packages/admin/resources/views/components/layouts/app/topbar/nav-menu-button.blade.php
Labels: ui

#3857 Assertions to confirm that an action does not exist
  packages/admin/.stubs.php
  packages/admin/src/Testing/TestsPageActions.php
  packages/tables/.stubs.php
  packages/tables/src/Testing/TestsActions.php
  packages/tables/src/Testing/TestsBulkActions.php
  tests/src/Admin/Fixtures/Pages/PageActions.php
  tests/src/Admin/Pages/ActionTest.php
  tests/src/Tables/ActionTest.php
  tests/src/Tables/BulkActionTest.php
  tests/src/Tables/Fixtures/PostsTable.php
Labels: enhancement

#3866 fix: Form docs registering a model link
  packages/forms/docs/05-validation.md
Labels: bug, documentation

#3864 fix per page all option issue in table widget
  packages/admin/src/Widgets/TableWidget.php
Labels: bug

#3855 Enhancement: Sidebar open/close classes
  packages/admin/resources/views/components/layouts/app.blade.php
  packages/admin/resources/views/components/layouts/app/sidebar/index.blade.php
Labels: enhancement

#3871 Update Dutch translations
  packages/admin/resources/lang/nl/login.php
  packages/admin/resources/lang/nl/resources/pages/edit-record.php
  packages/admin/resources/lang/nl/resources/pages/view-record.php
  packages/spatie-laravel-settings-plugin/resources/lang/nl/pages/settings-page.php
  packages/support/resources/lang/nl/actions/create.php
  packages/support/resources/lang/nl/actions/edit.php
  packages/tables/resources/lang/nl/table.php
Labels: i18n

#3849 Fixed broken table header layout while reordering when table has header actions.
  packages/tables/resources/views/index.blade.php
Labels: bug

#3884 fix: Docs widgets typo
  packages/admin/docs/08-plugins.md
Labels: bug, documentation

#3873 Fix casing inconsistency between resource titles
  packages/admin/src/Resources/Pages/CreateRecord.php
Labels: bug

#3886 fix direction of wizard steps description for rtl
  packages/forms/resources/views/components/wizard.blade.php
Labels: i18n

#3887 Update Hungarian translation
  packages/admin/resources/lang/hu/resources/pages/view-record.php
  packages/admin/resources/lang/hu/widgets/account-widget.php
  packages/admin/resources/lang/hu/widgets/filament-info-widget.php
  packages/tables/resources/lang/hu/table.php
Labels: i18n

#3872 Absolute option possible for Resource::getUrl()
  packages/admin/src/Pages/Page.php
  packages/admin/src/Resources/Resource.php
Labels: enhancement

#3897 [fix] Toggle dark / light mode translation for pt_PT
  packages/admin/resources/lang/pt_PT/layout.php
Labels: i18n

#3898 [DOCS] [TABLE] Fix simplePaginate code sample
  packages/tables/docs/02-getting-started.md
Labels: documentation

#3899 Fix "Malformed UTF-8 characters, possibly incorrectly encoded" error …
  packages/forms/src/Components/Concerns/CanBeValidated.php
Labels: bug

#3879 Chore: Refactor Command Traits to Support Package
  packages/admin/src/Commands/Concerns/CanIndentStrings.php
  packages/admin/src/Commands/Concerns/CanManipulateFiles.php
  packages/admin/src/Commands/Concerns/CanValidateInput.php
  packages/admin/src/Commands/MakePageCommand.php
  packages/admin/src/Commands/MakeRelationManagerCommand.php
  packages/admin/src/Commands/MakeResourceCommand.php
  packages/admin/src/Commands/MakeUserCommand.php
  packages/admin/src/Commands/MakeWidgetCommand.php
  packages/admin/src/FilamentServiceProvider.php
  packages/forms/src/Commands/Concerns/CanManipulateFiles.php
  packages/forms/src/Commands/Concerns/CanValidateInput.php
  packages/forms/src/Commands/MakeFieldCommand.php
  packages/forms/src/Commands/MakeLayoutComponentCommand.php
  packages/forms/src/FormsServiceProvider.php
  packages/spatie-laravel-settings-plugin/src/Commands/MakeSettingsPageCommand.php
  packages/spatie-laravel-settings-plugin/src/SpatieLaravelSettingsPluginServiceProvider.php
  packages/spatie-laravel-translatable-plugin/stubs/SettingsPage.stub
  packages/support/src/Commands/Concerns/CanIndentStrings.php
  packages/support/src/Commands/Concerns/CanManipulateFiles.php
  packages/support/src/Commands/Concerns/CanValidateInput.php
  packages/tables/src/Commands/Concerns/CanManipulateFiles.php
  packages/tables/src/Commands/Concerns/CanValidateInput.php
  packages/tables/src/Commands/MakeColumnCommand.php
  packages/tables/src/TablesServiceProvider.php
Labels: code quality

#3921 [feat] View Action translation for pt_PT
  packages/support/resources/lang/pt_PT/actions/view.php
Labels: i18n

#3923 Active filters text dark mode color adjustment
  packages/tables/resources/views/components/filters/indicators.blade.php
Labels: bug

#3924 Update id translation
  packages/admin/resources/lang/id/resources/pages/edit-record.php
  packages/admin/resources/lang/id/resources/pages/view-record.php
Labels: i18n

#3836 Add optionsLimit to SelectFilter
  packages/tables/src/Filters/SelectFilter.php
Labels: enhancement

#3882 Enhancement: make filament-main-topbar sticky
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/mix-manifest.json
  packages/admin/docs/07-appearance.md
  packages/admin/resources/views/components/layouts/app.blade.php
Labels: enhancement

#3931 fix: Ternary filter indicator
  packages/tables/src/Filters/TernaryFilter.php
  packages/tables/src/Filters/TrashedFilter.php
Labels: bug

#3932 fix: Nested column individual search
  packages/tables/src/Concerns/CanSearchRecords.php
Labels: bug

#3933 fix: Hide trashed bulk actions intelligently
  packages/tables/src/Actions/DeleteBulkAction.php
  packages/tables/src/Actions/ForceDeleteBulkAction.php
  packages/tables/src/Actions/RestoreBulkAction.php
  packages/tables/src/Concerns/HasFilters.php
  packages/tables/src/Contracts/HasTable.php
  packages/tables/src/Filters/Concerns/BelongsToTable.php
  packages/tables/src/Testing/TestsFilters.php
Labels: enhancement

#3935 add Arabic translation for notifications
  packages/notifications/resources/lang/ar/database.php
Labels: i18n

#3937 feature: Table column action modals
  packages/tables/.stubs.php
  packages/tables/docs/03-columns.md
  packages/tables/resources/views/components/cell.blade.php
  packages/tables/src/Columns/Concerns/CanCallAction.php
  packages/tables/src/Concerns/HasActions.php
  packages/tables/src/Concerns/HasColumns.php
  packages/tables/src/Concerns/InteractsWithTable.php
  packages/tables/src/Testing/TestsColumns.php
  tests/src/Tables/ColumnTest.php
  tests/src/Tables/Fixtures/PostsTable.php
Labels: enhancement

#3938 Translate pl database notifications
  packages/notifications/resources/lang/pl/database.php
Labels: i18n

#3939 Fix notification button tooltip.
  packages/admin/resources/views/components/layouts/app/topbar/database-notifications-trigger.blade.php
Labels: bug

#3941 Translate ms database notifications.
  packages/admin/resources/lang/ms/layout.php
  packages/notifications/resources/lang/ms/database.php
  packages/support/resources/lang/ms/components/modal.php
Labels: i18n

#3948 Ru & Ua Notifications lang
  packages/admin/resources/lang/ru/resources/pages/edit-record.php
  packages/admin/resources/lang/ru/resources/pages/view-record.php
  packages/forms/resources/lang/ru/components.php
  packages/notifications/resources/lang/ru/database.php
  packages/notifications/resources/lang/uk/database.php
Labels: i18n

#3951 add French translation for notifications
  packages/notifications/resources/lang/fr/database.php
Labels: i18n

#3955 Fix toBroadcast() issue not working.
  packages/notifications/src/Notification.php
Labels: bug

#3956 Add & update id translations
  packages/admin/resources/lang/id/layout.php
  packages/notifications/resources/lang/id/database.php
  packages/support/resources/lang/id/components/modal.php
Labels: i18n

#3889 Font size tweaks
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/mix-manifest.json
  packages/admin/resources/views/components/global-search/input.blade.php
  packages/forms/dist/module.esm.css
  packages/forms/resources/css/components/select.css
  packages/forms/resources/views/components/color-picker.blade.php
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/resources/views/components/key-value.blade.php
  packages/forms/resources/views/components/markdown-editor.blade.php
  packages/forms/resources/views/components/rich-editor.blade.php
  packages/forms/resources/views/components/select.blade.php
  packages/forms/resources/views/components/tags-input.blade.php
  packages/forms/resources/views/components/text-input.blade.php
  packages/forms/resources/views/components/textarea.blade.php
  packages/tables/resources/views/columns/text-column.blade.php
  packages/tables/resources/views/components/search-input.blade.php
Labels: enhancement

#3952 fix: Database notifications docs
  packages/notifications/docs/03-database-notifications.md
Labels: bug, documentation

#3946 fix(notifications): misaligned trigger icon
  packages/notifications/resources/views/components/database/index.blade.php
Labels: bug

#3968 UUIDs changes to notifications table
  packages/notifications/docs/03-database-notifications.md
Labels: documentation

#3977 fix: MultiSelect font size
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.css
  packages/forms/resources/css/components/select.css
Labels: bug

#3974 feature: Editable table columns
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/mix-manifest.json
  packages/forms/docs/03-fields.md
  packages/forms/resources/views/components/markdown-editor.blade.php
  packages/forms/resources/views/components/radio.blade.php
  packages/forms/resources/views/components/tags-input.blade.php
  packages/forms/resources/views/components/toggle.blade.php
  packages/forms/src/Components/Concerns/CanDisableOptions.php
  packages/forms/src/Components/Concerns/CanDisablePlaceholderSelection.php
  packages/forms/src/Components/Concerns/HasInputMode.php
  packages/forms/src/Components/Concerns/HasStep.php
  packages/forms/src/Components/Concerns/HasToggleColors.php
  packages/forms/src/Components/Concerns/HasToggleIcons.php
  packages/forms/src/Components/Select.php
  packages/forms/src/Components/TextInput.php
  packages/forms/src/Components/Toggle.php
  packages/support/src/Components/ViewComponent.php
  packages/tables/docs/03-columns.md
  packages/tables/resources/views/columns/checkbox-column.blade.php
  packages/tables/resources/views/columns/select-column.blade.php
  packages/tables/resources/views/columns/text-column.blade.php
  packages/tables/resources/views/columns/text-input-column.blade.php
  packages/tables/resources/views/columns/toggle-column.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Columns/CheckboxColumn.php
  packages/tables/src/Columns/Concerns/CanBeDisabled.php
  packages/tables/src/Columns/Concerns/CanBeValidated.php
  packages/tables/src/Columns/Concerns/InteractsWithTableQuery.php
  packages/tables/src/Columns/Contracts/Editable.php
  packages/tables/src/Columns/SelectColumn.php
  packages/tables/src/Columns/TextInputColumn.php
  packages/tables/src/Columns/ToggleColumn.php
  packages/tables/src/Concerns/HasColumns.php
Labels: enhancement

#3984 fix: CheckboxList and Radio form column direction
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/mix-manifest.json
  packages/forms/resources/views/components/checkbox-list.blade.php
  packages/forms/resources/views/components/radio.blade.php
  packages/support/resources/views/components/grid.blade.php
Labels: bug

#3954 Visual tidyup of table header during reorder when no heading / description set
  packages/tables/resources/views/index.blade.php
Labels: bug

#3986 Add label to create single label
  packages/support/resources/lang/pt_BR/actions/create.php
Labels: i18n

#4007 Add Dutch notifications translations
  packages/notifications/resources/lang/nl/database.php
Labels: i18n

#4008 Notifications pt-BR
  packages/notifications/resources/lang/pt_BR/database.php
Labels: i18n

#3994 Consider relationship callback in select option label/s
  packages/forms/src/Components/Select.php
Labels: enhancement

#4006 Removing overflow-x when opening the modal...
  packages/support/resources/views/components/modal/index.blade.php
Labels: bug

#4013 fix: DB notification query return type
  packages/notifications/src/Http/Livewire/Notifications.php
Labels: bug

#3987 Argument for signed/unsigned in money mask
  packages/forms/docs/03-fields.md
  packages/forms/src/Components/TextInput/Mask.php
Labels: enhancement

#4016 Add missing database_notifications fr translation
  packages/admin/resources/lang/fr/layout.php
Labels: i18n

#4036 Adding reset and deselect records on individual search
  packages/tables/src/Concerns/CanSearchRecords.php
Labels: bug

#4038 [fix] Tables: Missing translations for pt_PT
  packages/tables/resources/lang/pt_PT/table.php
Labels: i18n

#4040 fix: Ternary filter indicator
  packages/tables/src/Filters/TernaryFilter.php
Labels: bug

#4043 feature: Slide over actions
  packages/admin/resources/views/components/page.blade.php
  packages/forms/resources/views/components/actions/modal/index.blade.php
  packages/support/src/Actions/Concerns/CanOpenModal.php
  packages/tables/resources/views/index.blade.php
Labels: enhancement

#4035 Add filament classes to table sections
  packages/tables/resources/views/index.blade.php
Labels: enhancement

#4022 Adding assertions to test column data
  packages/tables/.stubs.php
  packages/tables/docs/06-testing.md
  packages/tables/src/Testing/TestsColumns.php
  tests/src/Tables/ColumnTest.php
  tests/src/Tables/Fixtures/PostsTable.php
Labels: enhancement

#4044 Table : unset empty value of tableColumnSearchQueries
  packages/tables/src/Concerns/CanSearchRecords.php
Labels: bug

#4042 add attachment based on other columns
  packages/tables/src/Actions/AttachAction.php
Labels: enhancement

#4045 Persist search in session
  packages/tables/docs/03-columns.md
  packages/tables/src/Concerns/CanSearchRecords.php
  packages/tables/src/Concerns/InteractsWithTable.php
Labels: enhancement

#4049 fix
  packages/forms/resources/views/components/builder/block-picker.blade.php
Labels: bug

#4048 Add Prettier plugin for Tailwind CSS
  .prettierrc
  package-lock.json
  package.json
  packages/admin/dist/app.css.map
  packages/admin/resources/css/app.css
  packages/forms/dist/module.esm.css
  packages/forms/resources/css/components/file-upload.css
  packages/forms/resources/css/components/rich-editor.css
  packages/forms/resources/css/components/select.css
Labels: code quality

#4056 [fix] Actions/Modal: Missing translations for pt_PT
  packages/support/resources/lang/pt_PT/actions/modal.php
Labels: i18n

#3350 fix: Refactor select component to use array of objects for options
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/select.js
  packages/forms/resources/views/components/select.blade.php
  packages/forms/src/Components/Select.php
  packages/forms/src/Concerns/SupportsSelectFields.php
Labels: bug

#4011 Adding ColorColumn (companion for ColorPicker form field)
  packages/tables/docs/03-columns.md
  packages/tables/resources/lang/en/table.php
  packages/tables/resources/views/columns/color-column.blade.php
  packages/tables/src/Columns/ColorColumn.php
Labels: enhancement

#4054 🐛 Use appropriate can* method when check for resource pages
  packages/admin/src/Resources/Pages/ListRecords.php
Labels: bug

#3881 feat: check missing translations command
  README.md
  packages/support/src/Commands/CheckTranslationsCommand.php
  packages/support/src/SupportServiceProvider.php
Labels: enhancement

#4059 ✨ Add notifications in card layout
  packages/admin/resources/views/components/layouts/card.blade.php
Labels: enhancement

#3655 feature: Expand and scroll to validation errors
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/field-wrapper/error-message.blade.php
  packages/forms/resources/views/components/repeater.blade.php
  packages/forms/resources/views/components/section.blade.php
  packages/forms/resources/views/components/tabs.blade.php
  packages/forms/resources/views/components/tabs/tab.blade.php
  packages/forms/src/Components/Builder.php
  packages/forms/src/Components/Repeater.php
  packages/forms/src/Concerns/CanBeValidated.php
  packages/forms/src/Concerns/InteractsWithForms.php
  tests/src/Forms/ValidationTest.php
Labels: enhancement

#4060 fix: Color column docs
  packages/tables/docs/03-columns.md
Labels: documentation

#4061 fix: Check translations command pluralization
  packages/support/src/Commands/CheckTranslationsCommand.php
Labels: bug

#4062 Clean up table columns translations
  packages/tables/resources/lang/en/table.php
Labels: code quality

#4063 Add missing Dutch translations
  packages/admin/resources/lang/nl/layout.php
  packages/tables/resources/lang/nl/table.php
Labels: i18n

#4064 add Spanish translation for notifications
  packages/notifications/resources/lang/es/database.php
Labels: i18n

#3890 Feat: Validation Rule Methods
  packages/forms/docs/05-validation.md
  packages/forms/src/Components/Concerns/CanBeAccepted.php
  packages/forms/src/Components/Concerns/CanBeValidated.php
Labels: enhancement

#3888 More generic translation for drag and drop repeater field & tooltips …
  packages/forms/resources/lang/en/components.php
  packages/forms/resources/lang/nl/components.php
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/repeater.blade.php
Labels: enhancement, i18n

#4021 Adding alias for table filter method `column`
  packages/tables/docs/04-filters.md
  packages/tables/src/Filters/Concerns/HasRelationship.php
  packages/tables/src/Filters/MultiSelectFilter.php
  packages/tables/src/Filters/SelectFilter.php
  packages/tables/src/Filters/TernaryFilter.php
  tests/src/Tables/FilterTest.php
  tests/src/Tables/Fixtures/PostsTable.php
Labels: enhancement

#4076 feature: Action loading indicators
  composer.lock
  packages/support/resources/views/components/button.blade.php
  packages/support/resources/views/components/dropdown/list/item.blade.php
  packages/support/resources/views/components/icon-button.blade.php
  packages/support/resources/views/components/link.blade.php
Labels: enhancement

#4077 add missing translations for pt_BR
  packages/admin/resources/lang/pt_BR/layout.php
  packages/admin/resources/lang/pt_BR/resources/pages/edit-record.php
  packages/admin/resources/lang/pt_BR/resources/pages/view-record.php
  packages/tables/resources/lang/pt_BR/table.php
Labels: i18n

#4082 Cleaning up faulty turbo link tags
  packages/admin/resources/views/components/layouts/app/sidebar/index.blade.php
Labels: bug

#4083 Spanish translation update
  packages/admin/resources/lang/es/layout.php
  packages/admin/resources/lang/es/resources/pages/edit-record.php
  packages/admin/resources/lang/es/resources/pages/view-record.php
  packages/forms/resources/lang/es/components.php
  packages/support/resources/lang/es/actions/edit.php
  packages/support/resources/lang/es/components/modal.php
  packages/tables/resources/lang/es/table.php
Labels: i18n

#4084 update vi translation
  packages/admin/resources/lang/vi/layout.php
  packages/forms/resources/lang/vi/components.php
  packages/notifications/resources/lang/vi/database.php
  packages/support/resources/lang/vi/components/modal.php
  packages/tables/resources/lang/vi/table.php
Labels: i18n

#4091 Add missing Ukrainian translations
  packages/admin/resources/lang/uk/layout.php
  packages/admin/resources/lang/uk/resources/pages/edit-record.php
  packages/admin/resources/lang/uk/resources/pages/view-record.php
  packages/forms/resources/lang/uk/components.php
  packages/support/resources/lang/uk/actions/replicate.php
  packages/tables/resources/lang/uk/table.php
Labels: i18n

#4092 fixed markdown-editor list ident
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/mix-manifest.json
  packages/forms/resources/views/components/markdown-editor.blade.php
Labels: bug

#4103 Add missing id translations
  packages/forms/resources/lang/en/components.php
  packages/forms/resources/lang/id/components.php
  packages/tables/resources/lang/id/table.php
Labels: i18n

#4106 Fix missing ms 🇲🇾 translation.
  packages/forms/resources/lang/ms/components.php
  packages/tables/resources/lang/ms/table.php
Labels: i18n

#4126 feature: Focus wizard error step
  packages/forms/resources/views/components/wizard/step.blade.php
  packages/forms/src/Components/Wizard.php
Labels: enhancement

#4124 vi translation: add missing translations
  packages/admin/resources/lang/vi/resources/pages/edit-record.php
  packages/admin/resources/lang/vi/resources/pages/view-record.php
Labels: i18n

#4110 Support BelongsToThrough Relationship
  composer.json
  packages/tables/src/Filters/Concerns/HasRelationship.php
Labels: enhancement

#4136 [ar]: Translate missing keys
  packages/admin/resources/lang/ar/layout.php
  packages/admin/resources/lang/ar/resources/pages/edit-record.php
  packages/admin/resources/lang/ar/resources/pages/view-record.php
  packages/forms/resources/lang/ar/components.php
  packages/tables/resources/lang/ar/table.php
Labels: i18n

#4138 Fix Select/Multiselect relationship BelongsToThrough
  packages/forms/src/Components/Select.php
Labels: bug

#4140 fix Type Error on return type
  packages/forms/src/Components/Select.php
Labels: bug

#4097 [Docs]: Validation Error Notification
  packages/forms/docs/05-validation.md
Labels: documentation

#4098 add uuid to parameters
  packages/forms/src/Components/Repeater.php
Labels: enhancement

#4108 Adding getContext() shortcut for form builde
  packages/forms/docs/06-advanced.md
  packages/forms/src/Concerns/InteractsWithForms.php
Labels: documentation

#4105 Records selection on current page only
  packages/tables/resources/views/components/selection-indicator.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Concerns/CanSelectRecords.php
Labels: enhancement

#4148 fix: toggle component icons not respecting on/off colors
  packages/forms/resources/views/components/toggle.blade.php
  packages/tables/resources/views/columns/toggle-column.blade.php
Labels: bug

#4150 Add sorting fr translation
  packages/tables/resources/lang/fr/table.php
Labels: i18n

#4151 add sorting ar translation
  packages/tables/resources/lang/ar/table.php
Labels: i18n

#4152 Add missing Japanese translations
  packages/tables/resources/lang/ja/table.php
Labels: i18n

#4153 Add missing Japanese translation
  packages/forms/resources/lang/ja/components.php
Labels: i18n

#4159 Increase accessibility for new notifications
  packages/notifications/resources/views/components/database/modal/index.blade.php
Labels: ui

#4154 Add missing Japanese translation
  packages/tables/resources/lang/ja/table.php
Labels: i18n

#4160 fix: Translate multi select validation message
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/select.js
  packages/forms/resources/js/index.js
  packages/forms/resources/lang/en/components.php
  packages/forms/resources/views/components/select.blade.php
  packages/forms/src/Components/Select.php
  packages/tables/resources/views/components/selection-indicator.blade.php
  packages/tables/resources/views/index.blade.php
Labels: bug, i18n

#4161 feature: More media library file upload customization methods
  packages/spatie-laravel-media-library-plugin/docs/02-form-components.md
  packages/spatie-laravel-media-library-plugin/docs/03-table-columns.md
  packages/spatie-laravel-media-library-plugin/src/Forms/Components/SpatieMediaLibraryFileUpload.php
Labels: enhancement

#4162 feature: Max chart height
  packages/admin/docs/04-dashboard/03-charts.md
  packages/admin/resources/views/widgets/chart-widget.blade.php
  packages/admin/src/Widgets/ChartWidget.php
Labels: enhancement

#4163 feature: Responsive widgets layout customization
  packages/admin/docs/02-resources/08-widgets.md
  packages/admin/docs/03-pages/03-widgets.md
  packages/admin/docs/04-dashboard/01-getting-started.md
  packages/admin/resources/views/components/page.blade.php
  packages/admin/resources/views/components/widget.blade.php
  packages/admin/resources/views/components/widgets.blade.php
  packages/admin/resources/views/pages/dashboard.blade.php
  packages/admin/src/Pages/Dashboard.php
  packages/admin/src/Pages/Page.php
  packages/admin/src/Widgets/Widget.php
Labels: enhancement

#4166 Update Dutch translations
  packages/admin/src/Widgets/Widget.php
  packages/forms/resources/lang/nl/components.php
  packages/tables/resources/lang/nl/table.php
Labels: i18n

#4171 Update Ukrainian translations
  packages/admin/resources/lang/uk/login.php
  packages/forms/resources/lang/uk/components.php
  packages/support/resources/lang/uk/actions/associate.php
  packages/support/resources/lang/uk/actions/attach.php
  packages/support/resources/lang/uk/actions/replicate.php
  packages/tables/resources/lang/uk/table.php
Labels: i18n

#4179 fix: Dutch translations
  packages/forms/resources/lang/nl/components.php
Labels: bug, i18n

#4180 [2.x] Make `Builder` blocks cloneable
  packages/forms/resources/lang/en/components.php
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/src/Components/Builder.php
  packages/forms/src/Components/Concerns/CanBeCloned.php
  packages/forms/src/Components/Repeater.php
Labels: enhancement

#4187 fix: Text column description styling
  packages/tables/resources/views/columns/text-column.blade.php
Labels: bug, ui

#4183 Merge extra attributes in layout components
  packages/tables/resources/views/columns/layout/panel.blade.php
  packages/tables/resources/views/columns/layout/split.blade.php
  packages/tables/resources/views/columns/layout/stack.blade.php
Labels: enhancement

#4174 Mitigate multiple network requests
  packages/forms/resources/views/components/checkbox-list.blade.php
  packages/forms/resources/views/components/checkbox.blade.php
  packages/forms/resources/views/components/radio.blade.php
  packages/forms/resources/views/components/toggle.blade.php
Labels: enhancement

#4146 Add forceSaveRelationships method
  packages/forms/docs/02-getting-started.md
  packages/forms/src/Components/Concerns/BelongsToModel.php
  packages/forms/src/Concerns/BelongsToModel.php
  tests/src/Forms/StateTest.php
Labels: enhancement

#4087 [spatie-laravel-tags-plugin] Support custom tag model
  packages/spatie-laravel-tags-plugin/src/Forms/Components/SpatieTagsInput.php
Labels: enhancement

#4127 Apply scopes to relationship
  packages/tables/src/Columns/Concerns/InteractsWithTableQuery.php
Labels: bug

#4189 Update id translations
  packages/forms/resources/lang/id/components.php
  packages/tables/resources/lang/id/table.php
Labels: i18n

#4191 [ar]: Translate new phrases
  packages/forms/resources/lang/ar/components.php
Labels: i18n

#4193 Fix/IconButton method missing in GlobalSearch Action
  packages/admin/src/GlobalSearch/Actions/Action.php
Labels: enhancement

#4195 fix: Duplicate select options
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/select.js
Labels: bug

#4196 fix: Toggleable columns loading recursion
  packages/tables/resources/views/index.blade.php
Labels: bug

#4197 fix: Date picker set null
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/date-time-picker.js
Labels: bug

#4199 fixing incorrect closing div location
  packages/tables/resources/views/index.blade.php
Labels: bug

#4202 Add missing Japanese translation
  packages/admin/resources/lang/ja/layout.php
Labels: i18n

#4203 Add missing Japanese translation
  packages/admin/resources/lang/ja/resources/pages/edit-record.php
Labels: i18n

#4210 fix: evaluate Closures passed to getIcon()
  packages/tables/src/Columns/Concerns/HasIcon.php
Labels: bug

#4213 Fix: wrap more methods in evaluate()
  packages/tables/src/Columns/Concerns/HasColor.php
  packages/tables/src/Columns/Concerns/HasSize.php
  packages/tables/src/Columns/Concerns/HasWeight.php
Labels: bug

#4217 add missing pt_BR translations
  packages/forms/resources/lang/pt_BR/components.php
  packages/tables/resources/lang/pt_BR/table.php
Labels: i18n

#4212 chore: update pl translations
  packages/admin/resources/lang/pl/layout.php
  packages/forms/resources/lang/pl/components.php
  packages/tables/resources/lang/pl/table.php
Labels: i18n

#4221 Add missing Japanese translation
  packages/forms/resources/lang/ja/components.php
Labels: i18n
