Repository filamentphp/filament, pull requests merged in 2022-02, with the labels that each got.

#1406 Locale DatePicker and DateTimePicker
  packages/forms/resources/views/components/date-time-picker.blade.php
Labels: bug

#1426 Fix date time field height
  packages/forms/resources/views/components/date-time-picker.blade.php
Labels: bug, ui

#1427 Fix table checkbox alignment
  packages/tables/resources/views/components/checkbox-cell.blade.php
Labels: bug, ui

#1428 Fix inline radio item alignment
  packages/forms/resources/views/components/radio.blade.php
Labels: bug, ui

#1422 Add time() method to CanFormatState
  packages/tables/config/tables.php
  packages/tables/src/Columns/Concerns/CanFormatState.php
Labels: enhancement

#1435 Allow dynamically changing the settings property.
  packages/spatie-laravel-settings-plugin/src/Pages/SettingsPage.php
Labels: enhancement

#1437 Fix sidebar flash
  packages/admin/resources/views/components/layouts/app/sidebar/index.blade.php
  packages/admin/resources/views/components/layouts/base.blade.php
Labels: bug, ui

#1441 Fix contribution guide
  README.md
Labels: bug

#1449 fix dayjs localization
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/admin/dist/module.esm.js
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/date-time-picker.js
  packages/forms/resources/views/components/date-time-picker.blade.php
Labels: bug

#1443 Allow file extensions restriction on FilePond
  packages/forms/docs/03-fields.md
  packages/forms/resources/js/components/file-upload.js
Labels: enhancement

#1405 Add extra classes to the main layout and sidebar components
  packages/admin/resources/views/components/layouts/app.blade.php
  packages/admin/resources/views/components/layouts/app/sidebar/index.blade.php
Labels: enhancement, ui

#1450 fix datetime picker again
  packages/forms/resources/js/components/date-time-picker.js
  packages/forms/resources/views/components/date-time-picker.blade.php
Labels: bug

#1452 [2.x] Add some disabled styles
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/admin/dist/module.esm.js
  packages/forms/dist/module.esm.js
  packages/forms/resources/views/components/select.blade.php
  packages/forms/resources/views/components/text-input.blade.php
Labels: enhancement, ui

#1446 Dont output actions column if there aren't any actions
  packages/tables/resources/views/index.blade.php
Labels: bug, ui

#1400 [2.x] Add enum support for Select and Select Filters
  packages/forms/src/Components/Concerns/HasOptions.php
  packages/forms/src/Components/MultiSelect.php
  packages/forms/src/Components/Select.php
  packages/tables/src/Filters/Concerns/HasOptions.php
  packages/tables/src/Filters/MultiSelectFilter.php
  packages/tables/src/Filters/SelectFilter.php
Labels: enhancement

#1471 Correct duplicate `minValue()` reference to be `maxValue()`
  packages/forms/docs/03-fields.md
Labels: bug, documentation

#1467 fix(date-time-picker): missing html closing caret
  packages/forms/resources/views/components/date-time-picker.blade.php
Labels: bug

#1466 :sparkles: Get a resource by his model FQCN
  packages/admin/src/Facades/Filament.php
  packages/admin/src/FilamentManager.php
Labels: enhancement

#1463 Fix dropdown wrapping issue on larger labels
  packages/tables/resources/views/components/dropdown/item.blade.php
Labels: bug, ui

#1465 Add scripts before core
  packages/admin/docs/08-plugins.md
  packages/admin/src/Facades/Filament.php
  packages/admin/src/Http/Controllers/AssetController.php
  packages/admin/src/PluginServiceProvider.php
Labels: documentation, enhancement

#1484 Fix badge column height
  packages/tables/resources/views/columns/badge-column.blade.php
Labels: bug, ui

#1482 fix(hydrate-issue): missing child component check
  packages/forms/src/Concerns/HasState.php
Labels: bug

#1488 fix: Flysystem v3 AWS check
  packages/forms/src/Components/BaseFileUpload.php
  packages/forms/src/Components/Concerns/HasFileAttachments.php
  packages/spatie-laravel-media-library-plugin/src/Forms/Components/SpatieMediaLibraryFileUpload.php
  packages/tables/src/Columns/ImageColumn.php
Labels: bug

#1487 fix: get phpstan working (again)
  bootstrap/app.php
Labels: bug

#1489 chore: display full PHP version in workflow
  .github/workflows/tests.yml
Labels: chore

#1492 ux improvement
  packages/admin/resources/views/components/layouts/app/topbar/user-menu.blade.php
Labels: ui

#1496 Fix rtl for user menu
  packages/admin/resources/lang/ar/layout.php
  packages/admin/resources/views/components/layouts/app/topbar/user-menu.blade.php
Labels: ui

#1494 Add force option to console command
  packages/admin/src/Commands/Aliases/MakeBelongsToManyCommand.php
  packages/admin/src/Commands/Aliases/MakeHasManyCommand.php
  packages/admin/src/Commands/Aliases/MakeHasManyThroughCommand.php
  packages/admin/src/Commands/Aliases/MakeMorphManyCommand.php
  packages/admin/src/Commands/Aliases/MakePageCommand.php
  packages/admin/src/Commands/Aliases/MakeResourceCommand.php
  packages/admin/src/Commands/Aliases/MakeWidgetCommand.php
  packages/admin/src/Commands/MakeBelongsToManyCommand.php
  packages/admin/src/Commands/MakeHasManyCommand.php
  packages/admin/src/Commands/MakeHasManyThroughCommand.php
  packages/admin/src/Commands/MakeMorphManyCommand.php
  packages/admin/src/Commands/MakePageCommand.php
  packages/admin/src/Commands/MakeResourceCommand.php
  packages/admin/src/Commands/MakeWidgetCommand.php
  packages/forms/src/Commands/Aliases/MakeFieldCommand.php
  packages/forms/src/Commands/Aliases/MakeLayoutComponentCommand.php
  packages/forms/src/Commands/MakeFieldCommand.php
  packages/forms/src/Commands/MakeLayoutComponentCommand.php
  packages/tables/src/Commands/Aliases/MakeColumnCommand.php
  packages/tables/src/Commands/MakeColumnCommand.php
Labels: enhancement

#1486 Reduce uninitialised UI flashes and reflows
  packages/admin/resources/views/components/layouts/app/sidebar/group.blade.php
  packages/admin/resources/views/components/layouts/base.blade.php
  packages/forms/resources/js/components/textarea.js
  packages/forms/resources/views/components/checkbox-list.blade.php
  packages/forms/resources/views/components/checkbox.blade.php
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/resources/views/components/file-upload.blade.php
  packages/forms/resources/views/components/markdown-editor.blade.php
  packages/forms/resources/views/components/multi-select.blade.php
  packages/forms/resources/views/components/radio.blade.php
  packages/forms/resources/views/components/rich-editor.blade.php
  packages/forms/resources/views/components/select.blade.php
  packages/forms/resources/views/components/tags-input.blade.php
  packages/forms/resources/views/components/text-input.blade.php
  packages/forms/resources/views/components/textarea.blade.php
  packages/forms/resources/views/components/toggle.blade.php
  packages/tables/resources/views/components/filters/index.blade.php
  packages/tables/resources/views/index.blade.php
Labels: bug, ui

#1501 Correct all single line field heights
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/resources/views/components/multi-select.blade.php
  packages/forms/resources/views/components/select.blade.php
  packages/forms/resources/views/components/text-input.blade.php
Labels: bug, ui

#1504 Added Hindi translations
  packages/admin/resources/lang/hi/global-search.php
  packages/admin/resources/lang/hi/layout.php
  packages/admin/resources/lang/hi/login.php
  packages/admin/resources/lang/hi/pages/actions.php
  packages/admin/resources/lang/hi/pages/dashboard.php
  packages/admin/resources/lang/hi/resources/pages/create-record.php
  packages/admin/resources/lang/hi/resources/pages/edit-record.php
  packages/admin/resources/lang/hi/resources/pages/list-records.php
  packages/admin/resources/lang/hi/resources/pages/view-record.php
  packages/admin/resources/lang/hi/resources/relation-managers/attach.php
  packages/admin/resources/lang/hi/resources/relation-managers/create.php
  packages/admin/resources/lang/hi/resources/relation-managers/delete.php
  packages/admin/resources/lang/hi/resources/relation-managers/detach.php
  packages/admin/resources/lang/hi/resources/relation-managers/edit.php
  packages/admin/resources/lang/hi/widgets/account-widget.php
  packages/admin/resources/lang/hi/widgets/filament-info-widget.php
  packages/forms/resources/lang/hi/components.php
  packages/tables/resources/lang/hi/table.php
Labels: enhancement, i18n

#1509 Add missing french translations
  packages/admin/resources/lang/fr/layout.php
  packages/admin/resources/lang/fr/resources/pages/list-records.php
Labels: enhancement, i18n

#1508 Add method to easily override initial table records per page
  packages/tables/src/Concerns/CanPaginateRecords.php
Labels: enhancement

#1511 fix: Remove initial field values
  packages/forms/resources/views/components/checkbox-list.blade.php
  packages/forms/resources/views/components/checkbox.blade.php
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/resources/views/components/markdown-editor.blade.php
  packages/forms/resources/views/components/radio.blade.php
  packages/forms/resources/views/components/rich-editor.blade.php
  packages/forms/resources/views/components/select.blade.php
  packages/forms/resources/views/components/text-input.blade.php
  packages/forms/resources/views/components/textarea.blade.php
  packages/forms/resources/views/components/toggle.blade.php
Labels: bug

#1518 Fix french translations
  packages/admin/resources/lang/fr/resources/pages/list-records.php
Labels: bug, i18n

#1519 added method to use customized route key name in record route binding.
  packages/admin/src/Resources/Resource.php
Labels: enhancement

#1529 Fixes issue #1396
  packages/forms/src/Components/BaseFileUpload.php
Labels: bug

#1533 fix: Reset masked input
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/admin/dist/module.esm.js
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/text-input.js
Labels: bug

#1534 fix: 0 min/max
  packages/forms/resources/views/components/text-input.blade.php
  packages/forms/resources/views/components/textarea.blade.php
Labels: bug

#1538 Restore `filament-main` class
  packages/admin/resources/views/components/layouts/app.blade.php
Labels: bug, ui

#1542 fix: Filter options
  packages/tables/src/Filters/Concerns/HasOptions.php
Labels: bug

#1541 Added defer keyword in dayjs locale
  packages/forms/resources/views/components/date-time-picker.blade.php
Labels: bug

#1526 add sort indicator for all sortable columns
  packages/tables/resources/views/components/header-cell.blade.php
Labels: enhancement, ui

#1536 feature: global notification api
  composer.json
  composer.lock
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/mix-manifest.json
  packages/admin/docs/03-pages.md
  packages/admin/resources/lang/en/resources/pages/edit-record.php
  packages/admin/resources/lang/en/resources/pages/list-records.php
  packages/admin/resources/views/components/notification-manager.blade.php
  packages/admin/resources/views/components/notification.blade.php
  packages/admin/resources/views/components/page.blade.php
  packages/admin/src/Facades/Filament.php
  packages/admin/src/FilamentManager.php
  packages/admin/src/FilamentServiceProvider.php
  packages/admin/src/Http/Livewire/Concerns/CanNotify.php
  packages/admin/src/Pages/Page.php
  packages/admin/src/Resources/Pages/CreateRecord.php
  packages/admin/src/Resources/Pages/EditRecord.php
  packages/admin/src/Resources/Pages/ListRecords.php
  packages/admin/src/Resources/Pages/ListRecords/Concerns/CanCreateRecords.php
  packages/admin/src/Resources/Pages/ListRecords/Concerns/CanDeleteRecords.php
  packages/admin/src/Resources/Pages/ListRecords/Concerns/CanEditRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanAttachRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanCreateRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanDeleteRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanDetachRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanEditRecords.php
  packages/admin/src/Resources/RelationManagers/RelationManager.php
  packages/tables/resources/views/components/header-cell.blade.php
Labels: enhancement

#1549 Turkish (tr) translation corrections
  packages/admin/resources/lang/tr/global-search.php
  packages/admin/resources/lang/tr/resources/relation-managers/delete.php
  packages/admin/resources/lang/tr/resources/relation-managers/detach.php
Labels: bug, i18n

#1559 fix `key-value` field header direction with RTL
  packages/forms/resources/views/components/key-value.blade.php
Labels: bug, ui, i18n

#1562 add Indonesian translations
  packages/admin/resources/lang/id/global-search.php
  packages/admin/resources/lang/id/layout.php
  packages/admin/resources/lang/id/login.php
  packages/admin/resources/lang/id/pages/actions.php
  packages/admin/resources/lang/id/pages/dashboard.php
  packages/admin/resources/lang/id/resources/pages/create-record.php
  packages/admin/resources/lang/id/resources/pages/edit-record.php
  packages/admin/resources/lang/id/resources/pages/list-records.php
  packages/admin/resources/lang/id/resources/pages/view-record.php
  packages/admin/resources/lang/id/resources/relation-managers/attach.php
  packages/admin/resources/lang/id/resources/relation-managers/create.php
  packages/admin/resources/lang/id/resources/relation-managers/delete.php
  packages/admin/resources/lang/id/resources/relation-managers/detach.php
  packages/admin/resources/lang/id/resources/relation-managers/edit.php
  packages/admin/resources/lang/id/widgets/account-widget.php
  packages/admin/resources/lang/id/widgets/filament-info-widget.php
Labels: enhancement, i18n

#1566 Update french translations
  packages/admin/resources/lang/fr/global-search.php
  packages/admin/resources/lang/fr/layout.php
  packages/admin/resources/lang/fr/resources/pages/edit-record.php
Labels: bug, i18n

#1567 [ar] Translate new phrases
  packages/admin/resources/lang/ar/pages/actions.php
  packages/admin/resources/lang/ar/resources/pages/edit-record.php
  packages/admin/resources/lang/ar/resources/pages/list-records.php
Labels: enhancement, i18n

#1568 Flip logout icon
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/mix-manifest.json
  packages/admin/resources/views/components/dropdown/item.blade.php
Labels: ui

#1565 Add Missing Documentation for FileUpload
  packages/forms/docs/03-fields.md
Labels: documentation, enhancement

#1558 add missing documentation for repeater field
  packages/forms/docs/03-fields.md
Labels: documentation, enhancement

#1551 Add extra classes to the modal elements
  packages/admin/resources/views/components/modal/index.blade.php
  packages/tables/resources/views/components/modal/index.blade.php
Labels: enhancement, ui

#1574 fix: New relationship repeater items have the wrong $record
  packages/forms/src/Components/Concerns/BelongsToModel.php
  packages/forms/src/Concerns/BelongsToModel.php
  tests/src/Forms/ModelTest.php
Labels: bug

#1577 Add missing vietnamese translations
  packages/admin/resources/lang/vi/layout.php
  packages/admin/resources/lang/vi/pages/actions.php
  packages/admin/resources/lang/vi/resources/pages/create-record.php
  packages/admin/resources/lang/vi/resources/pages/edit-record.php
  packages/admin/resources/lang/vi/resources/pages/list-records.php
  packages/admin/resources/lang/vi/widgets/account-widget.php
Labels: enhancement, i18n

#1576 Add pt_BR New Translations Keys
  packages/admin/resources/lang/pt_BR/layout.php
  packages/admin/resources/lang/pt_BR/pages/actions.php
  packages/admin/resources/lang/pt_BR/resources/pages/edit-record.php
  packages/admin/resources/lang/pt_BR/resources/pages/list-records.php
Labels: enhancement, i18n

#1587 Add malay translation (ms)
  packages/admin/resources/lang/ms/global-search.php
  packages/admin/resources/lang/ms/layout.php
  packages/admin/resources/lang/ms/login.php
  packages/admin/resources/lang/ms/pages/actions.php
  packages/admin/resources/lang/ms/pages/dashboard.php
  packages/admin/resources/lang/ms/resources/pages/create-record.php
  packages/admin/resources/lang/ms/resources/pages/edit-record.php
  packages/admin/resources/lang/ms/resources/pages/list-records.php
  packages/admin/resources/lang/ms/resources/pages/view-record.php
  packages/admin/resources/lang/ms/resources/relation-managers/attach.php
  packages/admin/resources/lang/ms/resources/relation-managers/create.php
  packages/admin/resources/lang/ms/resources/relation-managers/delete.php
  packages/admin/resources/lang/ms/resources/relation-managers/detach.php
  packages/admin/resources/lang/ms/resources/relation-managers/edit.php
  packages/admin/resources/lang/ms/widgets/account-widget.php
  packages/admin/resources/lang/ms/widgets/filament-info-widget.php
  packages/forms/resources/lang/ms/components.php
  packages/spatie-laravel-translatable-plugin/resources/lang/ms/actions.php
  packages/tables/resources/lang/ms/table.php
Labels: enhancement, i18n

#1588 fix: Default filter state
  packages/tables/src/Filters/Concerns/CanBeDefault.php
  packages/tables/src/Filters/Concerns/HasDefaultState.php
  packages/tables/src/Filters/Concerns/HasFormSchema.php
  packages/tables/src/Filters/Filter.php
  packages/tables/src/Filters/MultiSelectFilter.php
  packages/tables/src/Filters/SelectFilter.php
Labels: bug

#1557 fix issue in repeater icons with rtl
  packages/forms/resources/views/components/repeater.blade.php
Labels: bug, ui

#1561 Fix toolbar's height wrongly when scrollbar appears
  packages/forms/resources/views/components/markdown-editor.blade.php
  packages/forms/resources/views/components/rich-editor.blade.php
Labels: bug, ui, needs more info

#1581 Change to generate paragaphs when hitting return in RichEditor
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/admin/dist/module.esm.js
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/rich-editor.js
Labels: enhancement

#1582 Added ability to specify name when uploading using SpatieMediaLibraryFileUpload
  packages/spatie-laravel-media-library-plugin/src/Forms/Components/SpatieMediaLibraryFileUpload.php
Labels: enhancement

#1595 fix: Dark mode toggle icon
  packages/forms/resources/views/components/toggle.blade.php
Labels: bug, ui

#1598 fix: S3 private files
  packages/forms/src/Components/BaseFileUpload.php
  packages/forms/src/Components/Concerns/HasFileAttachments.php
  packages/spatie-laravel-media-library-plugin/src/Forms/Components/SpatieMediaLibraryFileUpload.php
  packages/tables/src/Columns/ImageColumn.php
Labels: bug

#1612 feature: support favicons in admin
  packages/admin/config/filament.php
  packages/admin/resources/views/components/layouts/base.blade.php
Labels: enhancement

#1619 Add persian translations
  packages/admin/resources/lang/fa/global-search.php
  packages/admin/resources/lang/fa/layout.php
  packages/admin/resources/lang/fa/login.php
  packages/admin/resources/lang/fa/pages/actions.php
  packages/admin/resources/lang/fa/pages/dashboard.php
  packages/admin/resources/lang/fa/resources/pages/create-record.php
  packages/admin/resources/lang/fa/resources/pages/edit-record.php
  packages/admin/resources/lang/fa/resources/pages/list-records.php
  packages/admin/resources/lang/fa/resources/pages/view-record.php
  packages/admin/resources/lang/fa/resources/relation-managers/attach.php
  packages/admin/resources/lang/fa/resources/relation-managers/create.php
  packages/admin/resources/lang/fa/resources/relation-managers/delete.php
  packages/admin/resources/lang/fa/resources/relation-managers/detach.php
  packages/admin/resources/lang/fa/resources/relation-managers/edit.php
  packages/admin/resources/lang/fa/widgets/account-widget.php
  packages/admin/resources/lang/fa/widgets/filament-info-widget.php
  packages/tables/resources/lang/fa/table.php
Labels: enhancement, i18n

#1609 fix: badge/tags column alignment, header cell alignment
  packages/tables/resources/views/columns/badge-column.blade.php
  packages/tables/resources/views/columns/tags-column.blade.php
  packages/tables/resources/views/components/header-cell.blade.php
  packages/tables/resources/views/index.blade.php
Labels: ui

#1617 Fix belongstoselect styles
  packages/forms/resources/views/components/select.blade.php
Labels: bug, ui

#1637 fix: Nested repeaters
  packages/forms/src/Components/Builder.php
  packages/forms/src/Components/Repeater.php
Labels: bug

#1639 feature: Table cell loading indicators
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/mix-manifest.json
  packages/admin/resources/views/components/button.blade.php
  packages/admin/resources/views/components/modal/index.blade.php
  packages/forms/resources/views/components/markdown-editor.blade.php
  packages/tables/resources/views/components/button.blade.php
  packages/tables/resources/views/components/cell.blade.php
  packages/tables/resources/views/components/pagination/item.blade.php
  packages/tables/src/Actions/Action.php
  packages/tables/src/Actions/BulkAction.php
  packages/tables/src/Actions/Concerns/CanOpenModal.php
Labels: enhancement, ui

#1649 Fix Dutch translations
  packages/admin/resources/lang/nl/layout.php
  packages/admin/resources/lang/nl/login.php
  packages/admin/resources/lang/nl/pages/actions.php
  packages/admin/resources/lang/nl/resources/pages/create-record.php
  packages/admin/resources/lang/nl/resources/pages/edit-record.php
  packages/admin/resources/lang/nl/resources/pages/list-records.php
Labels: enhancement, i18n

#1644 [rtl] Minor fix
  packages/forms/resources/views/components/text-input.blade.php
Labels: bug, ui, i18n

#1652 docs: Add note to `minLength()`/`maxLength()`
  packages/forms/docs/03-fields.md
Labels: documentation, enhancement

#1642 fix: year input allowing more or less than 4 chars
  packages/forms/resources/js/components/date-time-picker.js
  packages/forms/resources/views/components/date-time-picker.blade.php
Labels: bug

#1517 Support custom admin panel paths with other parameters
  composer.json
  composer.lock
  packages/admin/config/filament.php
  packages/admin/routes/web.php
  tests/src/Admin/Http/Controllers/AssetControllerTest.php
Labels: bug

#1656 Review space-x-reverse in RTL direction
  packages/admin/resources/views/components/card/index.blade.php
  packages/admin/resources/views/components/global-search/result.blade.php
  packages/admin/resources/views/components/header/index.blade.php
  packages/admin/resources/views/components/modal/actions.blade.php
  packages/admin/resources/views/components/stats/card.blade.php
  packages/admin/resources/views/components/tabs/index.blade.php
  packages/admin/resources/views/widgets/filament-info-widget.blade.php
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/field-wrapper/hint.blade.php
  packages/forms/resources/views/components/key-value.blade.php
  packages/forms/resources/views/components/markdown-editor.blade.php
  packages/forms/resources/views/components/repeater.blade.php
  packages/forms/resources/views/components/rich-editor.blade.php
  packages/forms/resources/views/components/section.blade.php
  packages/forms/resources/views/components/tags-input.blade.php
Labels: ui, i18n

#1675 Fix typo in Dashboard docs
  packages/admin/docs/04-dashboard.md
Labels: documentation

#1679 Docs: Add missing word
  packages/admin/docs/03-pages.md
Labels: documentation

#1681 fix: disabled radio
  packages/forms/resources/views/components/checkbox-list.blade.php
  packages/forms/resources/views/components/radio.blade.php
Labels: bug

#1554 Enable modal on submit buttonAction
  composer.lock
  packages/admin/resources/views/resources/pages/create-record.blade.php
  packages/admin/resources/views/resources/pages/edit-record.blade.php
  packages/admin/src/Pages/Concerns/HasActions.php
  packages/admin/src/Pages/Concerns/HasFormActions.php
  packages/admin/src/Pages/Contracts/HasFormActions.php
  packages/admin/src/Resources/Pages/Concerns/UsesResourceForm.php
  packages/admin/src/Resources/Pages/CreateRecord.php
  packages/admin/src/Resources/Pages/EditRecord.php
Labels: enhancement, needs more info

#1638 Adds flags to `make:filament-widget` command
  packages/admin/src/Commands/Aliases/MakeWidgetCommand.php
  packages/admin/src/Commands/MakeWidgetCommand.php
  packages/admin/stubs/ChartWidget.stub
  packages/admin/stubs/StatsOverviewWidget.stub
Labels: enhancement

#1686 Add korean translations
  packages/admin/resources/lang/ko/global-search.php
  packages/admin/resources/lang/ko/layout.php
  packages/admin/resources/lang/ko/login.php
  packages/admin/resources/lang/ko/pages/actions.php
  packages/admin/resources/lang/ko/pages/dashboard.php
  packages/admin/resources/lang/ko/resources/pages/create-record.php
  packages/admin/resources/lang/ko/resources/pages/edit-record.php
  packages/admin/resources/lang/ko/resources/pages/list-records.php
  packages/admin/resources/lang/ko/resources/pages/view-record.php
  packages/admin/resources/lang/ko/resources/relation-managers/attach.php
  packages/admin/resources/lang/ko/resources/relation-managers/create.php
  packages/admin/resources/lang/ko/resources/relation-managers/delete.php
  packages/admin/resources/lang/ko/resources/relation-managers/detach.php
  packages/admin/resources/lang/ko/resources/relation-managers/edit.php
  packages/admin/resources/lang/ko/widgets/account-widget.php
  packages/admin/resources/lang/ko/widgets/filament-info-widget.php
Labels: enhancement, i18n

#1684 Cache chart data and stats cards to prevent multiple executions
  packages/admin/resources/views/widgets/chart-widget.blade.php
  packages/admin/resources/views/widgets/stats-overview-widget.blade.php
  packages/admin/src/Widgets/ChartWidget.php
  packages/admin/src/Widgets/StatsOverviewWidget.php
Labels: enhancement

#1704 Support closures in page action hidden method
  packages/admin/src/Pages/Actions/Concerns/CanBeHidden.php
Labels: enhancement

#1696 Fixed z-index of block picker when using child Builders
  packages/forms/resources/views/components/builder/block-picker.blade.php
Labels: bug, ui

#1654 Update SpatieMediaLibraryFileUpload.php
  packages/spatie-laravel-media-library-plugin/src/Forms/Components/SpatieMediaLibraryFileUpload.php
Labels: enhancement

#1626 Tweak file upload layout, add filepond-plugin-media-preview, add disable preview option
  package.json
  packages/forms/resources/css/components/file-upload.css
  packages/forms/resources/js/components/file-upload.js
  packages/forms/resources/views/components/file-upload.blade.php
  packages/forms/src/Components/BaseFileUpload.php
  packages/forms/src/Components/FileUpload.php
Labels: enhancement, ui

#1689 Locale filepond
  packages/forms/resources/views/components/file-upload.blade.php
Labels: enhancement, i18n

#1717 Added new missing Spanish translations.
  packages/admin/resources/lang/es/layout.php
  packages/admin/resources/lang/es/login.php
  packages/admin/resources/lang/es/pages/actions.php
  packages/admin/resources/lang/es/resources/pages/edit-record.php
  packages/admin/resources/lang/es/resources/pages/list-records.php
  packages/admin/resources/lang/es/resources/relation-managers/attach.php
  packages/admin/resources/lang/es/resources/relation-managers/create.php
  packages/admin/resources/lang/es/widgets/account-widget.php
Labels: i18n

#1718 Add missing Exception class
  packages/spatie-laravel-translatable-plugin/src/Resources/Concerns/Translatable.php
Labels: bug

#1721 docs: return navigation builder
  packages/admin/docs/05-navigation.md
Labels: documentation

#1725 [2.x] Fix simple resources not respecting policy methods
  packages/admin/src/Resources/Pages/ListRecords/Concerns/CanDeleteRecords.php
  packages/admin/src/Resources/Pages/ListRecords/Concerns/CanEditRecords.php
Labels: bug

#1659 Added alignment config to table row actions.
  packages/tables/config/tables.php
  packages/tables/docs/05-actions.md
  packages/tables/resources/views/components/actions-cell.blade.php
Labels: enhancement, ui

#1605 feature: support custom global search providers
  packages/admin/resources/views/components/global-search/result-group.blade.php
  packages/admin/resources/views/components/global-search/results-container.blade.php
  packages/admin/src/Facades/Filament.php
  packages/admin/src/FilamentManager.php
  packages/admin/src/GlobalSearch/Contracts/GlobalSearchProvider.php
  packages/admin/src/GlobalSearch/DefaultGlobalSearchProvider.php
  packages/admin/src/GlobalSearch/GlobalSearchResult.php
  packages/admin/src/GlobalSearch/GlobalSearchResults.php
  packages/admin/src/Http/Livewire/GlobalSearch.php
  packages/admin/src/Resources/Resource.php
  tests/src/Admin/GlobalSearch/GlobalSearchServiceProvider.php
  tests/src/Admin/GlobalSearch/GlobalSearchTest.php
  tests/src/Admin/GlobalSearch/TestCase.php
Labels: enhancement

#1711 [2.x] Show notification if only available
  packages/admin/src/Resources/Pages/CreateRecord.php
  packages/admin/src/Resources/Pages/EditRecord.php
  packages/admin/src/Resources/Pages/ListRecords.php
  packages/admin/src/Resources/Pages/ListRecords/Concerns/CanCreateRecords.php
  packages/admin/src/Resources/Pages/ListRecords/Concerns/CanDeleteRecords.php
  packages/admin/src/Resources/Pages/ListRecords/Concerns/CanEditRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanAttachRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanCreateRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanDeleteRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanDetachRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanEditRecords.php
  packages/spatie-laravel-settings-plugin/src/Pages/SettingsPage.php
Labels: enhancement
