Repository filamentphp/filament, pull requests merged in 2022-03, with the labels that each got.

#1738 Add pt_BR translations - Settings plugin
  packages/spatie-laravel-settings-plugin/resources/lang/pt_BR/pages/settings-page.php
Labels: enhancement, i18n

#1741 Fix bug #1740
  packages/admin/src/Resources/Pages/ListRecords/Concerns/CanCreateRecords.php
Labels: bug

#1744 Add Dutch translations for settings and translatable plugins
  packages/spatie-laravel-settings-plugin/resources/lang/nl/pages/settings-page.php
  packages/spatie-laravel-translatable-plugin/resources/lang/nl/actions.php
Labels: enhancement, i18n

#1750 add middlewares to page and resource
  packages/admin/src/Pages/Page.php
  packages/admin/src/Resources/Resource.php
Labels: enhancement

#1743 fix: responsive compatibility problem on table filters
  packages/tables/resources/views/index.blade.php
Labels: bug, pending changes, ui

#1749 Refactors to enable PHPStan
  bootstrap/app.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanCreateRecords.php
  packages/admin/src/Resources/RelationManagers/RelationManager.php
  packages/forms/src/Components/HasManyRepeater.php
  packages/forms/src/Components/MorphManyRepeater.php
  packages/spatie-laravel-tags-plugin/src/Forms/Components/SpatieTagsInput.php
  packages/tables/src/Columns/Concerns/InteractsWithTableQuery.php
Labels: bug

#1722 feat: Add ability to add custom tags to the head
  packages/admin/docs/07-appearance.md
  packages/admin/resources/views/components/layouts/base.blade.php
  packages/admin/src/FilamentManager.php
Labels: enhancement, pending changes

#1759 fix: wrong slug generation on pages
  packages/admin/src/Pages/Page.php
  packages/admin/src/Resources/Resource.php
Labels: bug

#1751 Update section background-color to white
  packages/forms/resources/views/components/card.blade.php
  packages/forms/resources/views/components/section.blade.php
Labels: ui

#1763 chore: Switch 404 misconfigured admin panel to 403
  packages/admin/docs/01-installation.md
  packages/admin/src/Http/Middleware/Authenticate.php
Labels: chore

#1764 fix: Bulk actions firing twice
  packages/admin/resources/views/components/dropdown/item.blade.php
  packages/tables/resources/views/components/dropdown/item.blade.php
Labels: bug

#1765 fix: Select value type
  packages/admin/dist/app.css.map
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/admin/dist/module.esm.js
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/multi-select.js
  packages/forms/resources/js/components/select.js
  packages/forms/resources/views/components/select.blade.php
Labels: bug

#1769 Fix searchable select width
  packages/forms/resources/views/components/select.blade.php
Labels: bug, ui

#1771 Allow stat cards to be linked, allow `HtmlString` objects in stat card labels and descriptions
  packages/admin/resources/views/components/stats/card.blade.php
  packages/admin/resources/views/widgets/stats-overview-widget/card.blade.php
  packages/admin/src/Widgets/StatsOverviewWidget/Card.php
Labels: enhancement

#1772 feature: Indicate selected table rows
  packages/tables/resources/views/components/checkbox-cell.blade.php
  packages/tables/resources/views/components/header-cell.blade.php
  packages/tables/resources/views/components/table.blade.php
  packages/tables/resources/views/index.blade.php
Labels: enhancement, ui

#1780 Add close button to filter popover
  packages/tables/resources/lang/en/table.php
  packages/tables/resources/lang/nl/table.php
  packages/tables/resources/views/components/filters/index.blade.php
  packages/tables/resources/views/components/icon-button.blade.php
Labels: enhancement

#1783 Fix table header color in light mode
  packages/tables/resources/views/components/table.blade.php
Labels: bug, ui

#1787 Remove event and use FilePond directly to update locale and prevent race condition
  packages/forms/resources/js/components/file-upload.js
  packages/forms/resources/views/components/file-upload.blade.php
Labels: bug

#1784 Update card borders
  packages/admin/resources/views/components/card/index.blade.php
  packages/admin/resources/views/components/stats/card.blade.php
  packages/forms/resources/views/components/card.blade.php
  packages/forms/resources/views/components/section.blade.php
Labels: enhancement, ui

#1779 Change type of min/max value from int to float
  packages/forms/src/Components/TextInput/Mask.php
Labels: enhancement

#1788 fix: Push ungrouped navigation items first
  packages/admin/docs/05-navigation.md
  packages/admin/src/FilamentManager.php
  packages/admin/src/Navigation/NavigationBuilder.php
Labels: bug

#1789 feature: User menu items
  packages/admin/docs/05-navigation.md
  packages/admin/docs/08-plugins.md
  packages/admin/resources/views/components/dropdown/item.blade.php
  packages/admin/resources/views/components/layouts/app/topbar/user-menu.blade.php
  packages/admin/src/Facades/Filament.php
  packages/admin/src/FilamentManager.php
  packages/admin/src/Navigation/UserMenuItem.php
  packages/admin/src/PluginServiceProvider.php
  packages/tables/resources/views/components/dropdown/item.blade.php
Labels: enhancement

#1799 add missing Arabic translations
  packages/tables/resources/lang/ar/table.php
Labels: enhancement, i18n

#1798 fix table filter card RTL
  packages/tables/resources/views/components/filters/index.blade.php
Labels: bug, ui, i18n

#1796 Specify pluralization intervals
  packages/tables/resources/lang/ms/table.php
  packages/tables/resources/lang/tr/table.php
Labels: bug, i18n

#1797 fix selected items count in Arabic translation
  packages/tables/resources/lang/ar/table.php
Labels: bug, i18n

#1802 fix: Default sort with anonymous column
  packages/tables/src/Concerns/CanSortRecords.php
Labels: enhancement

#1803 fix: Disable rich editor drag attachments
  packages/forms/resources/views/components/rich-editor.blade.php
Labels: bug

#1819 feature: make `NavigationBuilder` `Conditionable`
  packages/admin/src/Navigation/NavigationBuilder.php
Labels: enhancement

#1832 Fix issue with from() method in Input Mask
  packages/forms/src/Components/TextInput/Mask.php
Labels: bug

#1827 change wire:ignore
  packages/forms/resources/views/components/rich-editor.blade.php
Labels: bug

#1813 Add a new table widget type
  packages/admin/docs/04-dashboard.md
  packages/admin/resources/views/widgets/chart-widget.blade.php
  packages/admin/resources/views/widgets/table-widget.blade.php
  packages/admin/src/Commands/MakeWidgetCommand.php
  packages/admin/src/Widgets/TableWidget.php
  packages/admin/stubs/TableWidget.stub
Labels: enhancement

#1842 Update MakeBelongsToManyCommand.php
  packages/admin/src/Commands/Aliases/MakeBelongsToManyCommand.php
Labels: bug

#1861 Fix file upload spacing
  packages/forms/resources/css/components/file-upload.css
Labels: bug, ui

#1865 Adjust tailwind.config.js to make it work with mix watch.
  packages/admin/tailwind.config.js
Labels: bug

#1866 Allow customization of notification position
  packages/admin/config/filament.php
  packages/admin/docs/07-appearance.md
  packages/admin/resources/views/components/notification-manager.blade.php
  packages/admin/resources/views/components/notification.blade.php
Labels: enhancement

#1869 Badges for navigation items
  packages/admin/docs/05-navigation.md
  packages/admin/resources/views/components/layouts/app/sidebar/index.blade.php
  packages/admin/resources/views/components/layouts/app/sidebar/item.blade.php
  packages/admin/src/Navigation/NavigationItem.php
  packages/admin/src/Pages/Page.php
  packages/admin/src/Resources/Resource.php
Labels: enhancement

#1849 add ItemBetweenCreationDisabled
  packages/forms/resources/views/components/builder.blade.php
Labels: enhancement

#1854 [Feature] Ability to display icon on widget
  packages/admin/resources/views/components/stats/card.blade.php
  packages/admin/resources/views/widgets/stats-overview-widget/card.blade.php
  packages/admin/src/Widgets/StatsOverviewWidget/Card.php
Labels: enhancement

#1874 [BUG] focusedYear null value
  packages/forms/resources/js/components/date-time-picker.js
Labels: bug

#1860 Can format date/datetime/time column with tz
  packages/tables/src/Columns/Concerns/CanFormatState.php
Labels: enhancement

#1870 Improve the logout flow
  packages/admin/resources/views/components/dropdown/item.blade.php
  packages/admin/resources/views/components/layouts/app/topbar/user-menu.blade.php
  packages/admin/routes/web.php
  packages/admin/src/FilamentServiceProvider.php
  packages/admin/src/Http/Responses/Auth/Contracts/LogoutResponse.php
  packages/admin/src/Http/Responses/Auth/LogoutResponse.php
  packages/tables/resources/views/components/dropdown/item.blade.php
  tests/src/Admin/Auth/LogoutTest.php
Labels: enhancement

#1817 Fix custom order in HasManyRepeater
  packages/forms/src/Components/RelationshipRepeater.php
Labels: bug

#1883 feature: Inline field labels / custom field wrappers
  packages/admin/config/filament.php
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/admin/dist/module.esm.css
  packages/admin/dist/module.esm.js
  packages/admin/src/Resources/Pages/Concerns/UsesResourceForm.php
  packages/admin/src/Resources/Pages/CreateRecord.php
  packages/admin/src/Resources/Pages/EditRecord.php
  packages/admin/src/Resources/Pages/ListRecords/Concerns/CanCreateRecords.php
  packages/admin/src/Resources/Pages/ListRecords/Concerns/CanEditRecords.php
  packages/admin/src/Resources/Pages/ViewRecord.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanCreateRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanEditRecords.php
  packages/admin/src/Resources/RelationManagers/RelationManager.php
  packages/forms/dist/module.esm.css
  packages/forms/dist/module.esm.js
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/checkbox-list.blade.php
  packages/forms/resources/views/components/checkbox.blade.php
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/resources/views/components/field-wrapper/inline.blade.php
  packages/forms/resources/views/components/file-upload.blade.php
  packages/forms/resources/views/components/key-value.blade.php
  packages/forms/resources/views/components/markdown-editor.blade.php
  packages/forms/resources/views/components/multi-select.blade.php
  packages/forms/resources/views/components/placeholder.blade.php
  packages/forms/resources/views/components/radio.blade.php
  packages/forms/resources/views/components/repeater.blade.php
  packages/forms/resources/views/components/rich-editor.blade.php
  packages/forms/resources/views/components/select.blade.php
  packages/forms/resources/views/components/tags-input.blade.php
  packages/forms/resources/views/components/text-input.blade.php
  packages/forms/resources/views/components/textarea.blade.php
  packages/forms/resources/views/components/toggle.blade.php
  packages/forms/src/ComponentContainer.php
  packages/forms/src/Components/Builder.php
  packages/forms/src/Components/Component.php
  packages/forms/src/Components/Concerns/CanBeInline.php
  packages/forms/src/Components/Concerns/CanSpanColumns.php
  packages/forms/src/Components/Concerns/HasFieldWrapper.php
  packages/forms/src/Components/Concerns/HasInlineLabel.php
  packages/forms/src/Components/RelationshipRepeater.php
  packages/forms/src/Components/Repeater.php
  packages/forms/src/Concerns/HasFieldWrapper.php
  packages/forms/src/Concerns/HasInlineLabels.php
  packages/spatie-laravel-settings-plugin/src/Pages/SettingsPage.php
Labels: enhancement

#1886 Update MakeMorphManyCommand.php
  packages/admin/src/Commands/Aliases/MakeMorphManyCommand.php
Labels: bug

#1892 Fixes MakeWidgetCommand Alias
  packages/admin/src/Commands/Aliases/MakeWidgetCommand.php
Labels: bug

#1896 fix localization of datetime pickers
  packages/forms/resources/js/components/date-time-picker.js
Labels: bug

#1908 fix: default to simple pagination in table widget
  packages/admin/src/Widgets/TableWidget.php
Labels: enhancement

#1903 Custom modals stack
  packages/admin/resources/views/components/page.blade.php
Labels: enhancement

#1794 Add dusk selectors to form components
  packages/forms/resources/views/components/checkbox-list.blade.php
  packages/forms/resources/views/components/checkbox.blade.php
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/resources/views/components/file-upload.blade.php
  packages/forms/resources/views/components/hidden.blade.php
  packages/forms/resources/views/components/markdown-editor.blade.php
  packages/forms/resources/views/components/multi-select.blade.php
  packages/forms/resources/views/components/radio.blade.php
  packages/forms/resources/views/components/rich-editor.blade.php
  packages/forms/resources/views/components/select.blade.php
  packages/forms/resources/views/components/tags-input.blade.php
  packages/forms/resources/views/components/text-input.blade.php
  packages/forms/resources/views/components/textarea.blade.php
  packages/forms/resources/views/components/toggle.blade.php
Labels: enhancement

#1839 label for translation dropdown
  composer.json
  composer.lock
  packages/spatie-laravel-translatable-plugin/composer.json
  packages/spatie-laravel-translatable-plugin/composer.lock
  packages/spatie-laravel-translatable-plugin/src/Resources/Pages/Concerns/HasActiveFormLocaleSelect.php
Labels: enhancement

#1923 Fix dynamic dusk selectors
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/resources/views/components/tags-input.blade.php
Labels: bug

#1925 feature: allow `Closure` values for stats cards
  packages/admin/src/Widgets/StatsOverviewWidget/Card.php
Labels: enhancement

#1926 Fix issue when dynamically hiding file upload.
  packages/forms/resources/views/components/file-upload.blade.php
Labels: bug

#1934 fix time box direction in RTL
  packages/forms/resources/views/components/date-time-picker.blade.php
Labels: bug, ui, i18n

#1916 Fix stats widget spacing
  packages/admin/resources/views/components/stats/index.blade.php
Labels: bug, ui

#1944 feature: HasManyRelationManager associate and dissociate
  packages/admin/docs/02-resources.md
  packages/admin/resources/lang/en/resources/relation-managers/associate.php
  packages/admin/resources/lang/en/resources/relation-managers/dissociate.php
  packages/admin/src/Resources/Pages/CreateRecord.php
  packages/admin/src/Resources/Pages/EditRecord.php
  packages/admin/src/Resources/Pages/ListRecords.php
  packages/admin/src/Resources/Pages/ListRecords/Concerns/CanCreateRecords.php
  packages/admin/src/Resources/Pages/ViewRecord.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanAssociateRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanAttachRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanCreateRecords.php
  packages/admin/src/Resources/RelationManagers/Concerns/CanDissociateRecords.php
  packages/admin/src/Resources/RelationManagers/HasManyRelationManager.php
  packages/admin/src/Resources/RelationManagers/RelationManager.php
Labels: enhancement

#1828 File naming increment
  packages/forms/docs/03-fields.md
  packages/forms/src/Components/BaseFileUpload.php
Labels: enhancement

#1879 Added length() function for inputs
  packages/forms/docs/03-fields.md
  packages/forms/src/Components/Concerns/CanBeLengthConstrained.php
  packages/forms/src/Components/Contracts/CanHaveNumericState.php
  packages/forms/src/Components/TextInput.php
Labels: enhancement

#1885 Collapsible navigation sidebar
  packages/admin/config/filament.php
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/admin/docs/07-appearance.md
  packages/admin/resources/js/app.js
  packages/admin/resources/views/components/layouts/app.blade.php
  packages/admin/resources/views/components/layouts/app/sidebar/group.blade.php
  packages/admin/resources/views/components/layouts/app/sidebar/index.blade.php
  packages/admin/resources/views/components/layouts/app/sidebar/item.blade.php
Labels: enhancement, ui

#1907 Changes logout on the account-widget to POST
  packages/admin/resources/views/widgets/account-widget.blade.php
Labels: bug, pending changes

#1946 [ar] Translate new Assciate & Dissociate phrases
  packages/admin/resources/lang/ar/resources/relation-managers/associate.php
  packages/admin/resources/lang/ar/resources/relation-managers/dissociate.php
Labels: enhancement, i18n

#1930 Allow null date
  packages/forms/resources/js/components/date-time-picker.js
Labels: bug

#1928 Added $record parameter to colors callback
  packages/tables/src/Columns/Concerns/HasColors.php
Labels: enhancement

#1933 Fix inline radio field not appear with disable label.
  packages/forms/resources/views/components/field-wrapper/index.blade.php
  packages/forms/resources/views/components/field-wrapper/inline.blade.php
Labels: bug

#1948 Reset simple resource modal error message
  packages/admin/src/Pages/Concerns/HasActions.php
  packages/tables/src/Concerns/HasActions.php
  packages/tables/src/Concerns/HasBulkActions.php
Labels: bug

#1917 Update dynamically the locale's selector in Edit, Create, View record
  packages/spatie-laravel-translatable-plugin/src/Resources/Pages/Concerns/HasActiveFormLocaleSelect.php
  packages/spatie-laravel-translatable-plugin/src/Resources/Pages/EditRecord/Concerns/Translatable.php
  packages/spatie-laravel-translatable-plugin/src/Resources/Pages/ViewRecord/Concerns/Translatable.php
Labels: enhancement

#1951 feature: Dynamic searchable select/multiselect options
  packages/admin/dist/app.css.map
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/admin/dist/module.esm.js
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/multi-select.js
  packages/forms/resources/js/components/select.js
  packages/forms/resources/views/components/multi-select.blade.php
  packages/forms/resources/views/components/select.blade.php
  packages/forms/src/Components/BelongsToManyMultiSelect.php
  packages/forms/src/Components/BelongsToSelect.php
  packages/forms/src/Components/Concerns/HasOptions.php
  packages/forms/src/Concerns/InteractsWithForms.php
  packages/forms/src/Concerns/SupportsMultiSelectFields.php
  packages/forms/src/Concerns/SupportsSelectFields.php
  packages/forms/src/Contracts/HasForms.php
Labels: bug

#1952 fix: Select and multiselect debounce
  packages/admin/dist/app.css.map
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/admin/dist/module.esm.js
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/multi-select.js
  packages/forms/resources/js/components/select.js
  packages/forms/resources/views/components/multi-select.blade.php
  packages/forms/resources/views/components/select.blade.php
Labels: bug

#1954 fix: Multiselect empty options
  packages/admin/dist/app.css.map
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/admin/dist/module.esm.js
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/multi-select.js
  packages/forms/src/Components/MultiSelect.php
Labels: bug

#1958 Fix collapsed sidebar width with scrollbars
  packages/admin/resources/views/components/layouts/app.blade.php
  packages/admin/resources/views/components/layouts/app/sidebar/index.blade.php
  packages/admin/resources/views/components/layouts/app/sidebar/item.blade.php
Labels: bug, ui

#1971 Tooltips for collapsed navigation
  package-lock.json
  package.json
  packages/admin/resources/css/app.css
  packages/admin/resources/js/app.js
  packages/admin/resources/views/components/layouts/app/sidebar/item.blade.php
Labels: enhancement, ui

#1970 fix TextColumn enum not able to return null
  packages/tables/src/Columns/Concerns/CanFormatState.php
Labels: bug

#1975 fix: user toggle not working with theme changing tooltips
  packages/admin/dist/app.css.map
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/admin/resources/js/app.js
Labels: bug

#1927 fix: table search problem when use translatable package
  packages/tables/src/Columns/Concerns/InteractsWithTableQuery.php
Labels: bug

#1982 Only show navigation tooltips on when collapsable navigation is active.
  packages/admin/resources/views/components/layouts/app/sidebar/item.blade.php
Labels: bug

#1986 Add beforeCoreScripts stack
  packages/admin/resources/views/components/layouts/base.blade.php
Labels: enhancement

#1935 Fix simple pagination arrows in RTL
  packages/tables/resources/views/components/pagination/index.blade.php
Labels: bug, ui, i18n

#1964 Feature: ActiveRelationManager keys
  packages/admin/resources/views/components/resources/relation-managers/index.blade.php
  packages/admin/src/Resources/Pages/Concerns/HasRelationManagers.php
Labels: enhancement

#1987 Add brand-icon for collapsed navigation
  packages/admin/docs/07-appearance.md
  packages/admin/resources/views/components/brand-icon.blade.php
  packages/admin/resources/views/components/layouts/app/sidebar/index.blade.php
Labels: enhancement

#1978 Allow ordering of RelationshipRepeater
  packages/forms/docs/03-fields.md
  packages/forms/src/Components/RelationshipRepeater.php
Labels: enhancement

#1990 Fix: str() helper not compatible with L8
  packages/admin/resources/views/components/brand-icon.blade.php
Labels: bug

#1993 feature: show icons in link actions
  packages/admin/dist/app.css.map
  packages/tables/resources/views/actions/link-action.blade.php
  packages/tables/resources/views/components/link.blade.php
Labels: enhancement

#1994 fix select action of pages with dark mode
  packages/admin/resources/views/pages/actions/select-action.blade.php
Labels: bug, ui

#1995 Check of View before Edit
  packages/admin/src/Resources/Pages/Concerns/HasRecordBreadcrumb.php
  packages/admin/src/Resources/Pages/CreateRecord.php
  packages/admin/src/Resources/Pages/ListRecords.php
Labels: enhancement

#1998 Fix simple pagination arrows in RTL
  packages/tables/resources/views/components/button.blade.php
  packages/tables/resources/views/components/icon-button.blade.php
  packages/tables/resources/views/components/pagination/item.blade.php
Labels: bug, ui

#1991 Slight hover effect for table rows
  packages/tables/resources/views/components/row.blade.php
  packages/tables/resources/views/index.blade.php
Labels: enhancement, ui

#2014 Improve fa translation
  packages/admin/resources/lang/fa/resources/pages/edit-record.php
  packages/admin/resources/lang/fa/resources/pages/list-records.php
  packages/admin/resources/lang/fa/resources/relation-managers/associate.php
  packages/admin/resources/lang/fa/resources/relation-managers/create.php
  packages/admin/resources/lang/fa/resources/relation-managers/detach.php
  packages/admin/resources/lang/fa/resources/relation-managers/dissociate.php
Labels: enhancement, i18n

#2020 Clear icon mirroring class
  packages/admin/resources/views/components/dropdown/item.blade.php
  packages/tables/resources/views/components/dropdown/item.blade.php
Labels: bug, ui, i18n

#2026 Improved fa translation
  packages/admin/resources/lang/fa/global-search.php
Labels: enhancement, i18n

#2016 Added the ability to pass HtmlString to field label
  packages/forms/src/Components/Concerns/HasLabel.php
  packages/forms/src/Components/Field.php
Labels: enhancement

#2008 📚 Docs: Mention `ServingFilament`
  packages/admin/docs/08-plugins.md
Labels: documentation, enhancement

#2006 Add login response
  packages/admin/src/FilamentServiceProvider.php
  packages/admin/src/Http/Livewire/Auth/Login.php
  packages/admin/src/Http/Responses/Auth/Contracts/LoginResponse.php
  packages/admin/src/Http/Responses/Auth/LoginResponse.php
Labels: enhancement

#2036 Bind tooltip to table cell instead of action.
  packages/tables/resources/views/components/cell.blade.php
Labels: bug

#2017 feature: repeater and builder item drag and drop ordering
  package.json
  packages/forms/resources/js/index.js
  packages/forms/resources/js/sortable.js
  packages/forms/resources/lang/en/components.php
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/repeater.blade.php
  packages/forms/src/Components/Builder.php
  packages/forms/src/Components/Repeater.php
  packages/forms/src/helpers.php
Labels: enhancement

#2043 Fix FileUpload field overlaps buttons
  packages/forms/resources/css/components/file-upload.css
Labels: bug, ui

#2042 Docs: Fix widget polling examples
  packages/admin/docs/04-dashboard.md
Labels: bug, documentation

#2032 Fix error in global search when user can not view or edit record.
  packages/admin/src/Resources/Resource.php
Labels: bug

#2044 Update TextColumn.php
  packages/tables/docs/03-columns.md
  packages/tables/src/Columns/Concerns/CanFormatState.php
Labels: enhancement

#2051 feature: MorphToManyRelationManager
  packages/admin/docs/02-resources.md
  packages/admin/src/Commands/Aliases/MakeMorphToManyCommand.php
  packages/admin/src/Commands/MakeMorphToManyCommand.php
  packages/admin/src/FilamentServiceProvider.php
  packages/admin/src/Resources/RelationManagers/MorphToManyRelationManager.php
  packages/admin/stubs/MorphToManyRelationManager.stub
Labels: enhancement

#2055 Laravel Octane Support: Scoped service binding
  packages/admin/src/FilamentServiceProvider.php
Labels: bug

#2061 📚 Add notice to use dedicated validation methods
  packages/forms/docs/05-validation.md
Labels: documentation, enhancement
