Repository filamentphp/filament, pull requests merged in 2022-07, with the labels that each got.

#2956 Make Card Width configurable
  packages/admin/resources/views/components/layouts/card.blade.php
Labels: enhancement

#2922 fix: Dynamic select options
  packages/forms/src/Components/Select.php
Labels: bug

#2999 fix: Stale Spatie tags
  packages/spatie-laravel-tags-plugin/src/Forms/Components/SpatieTagsInput.php
Labels: bug

#3008 Add a little padding to the Card.blade.php to prevent headbutting the browser
  packages/admin/resources/views/components/layouts/card.blade.php
Labels: ui

#3017 [Enhance] move Khmer language code to standard ISO-639
  packages/admin/resources/lang/km/global-search.php
  packages/admin/resources/lang/km/layout.php
  packages/admin/resources/lang/km/login.php
  packages/admin/resources/lang/km/pages/dashboard.php
  packages/admin/resources/lang/km/resources/pages/create-record.php
  packages/admin/resources/lang/km/resources/pages/edit-record.php
  packages/admin/resources/lang/km/resources/pages/list-records.php
  packages/admin/resources/lang/km/resources/pages/view-record.php
  packages/admin/resources/lang/km/widgets/account-widget.php
  packages/admin/resources/lang/km/widgets/filament-info-widget.php
Labels: enhancement, i18n

#3012 Add Russian Language for support
  packages/admin/resources/lang/ru/layout.php
  packages/forms/resources/lang/ru/components.php
  packages/support/resources/lang/ru/actions/associate.php
  packages/support/resources/lang/ru/actions/attach.php
  packages/support/resources/lang/ru/actions/create.php
  packages/support/resources/lang/ru/actions/delete.php
  packages/support/resources/lang/ru/actions/detach.php
  packages/support/resources/lang/ru/actions/dissociate.php
  packages/support/resources/lang/ru/actions/edit.php
  packages/support/resources/lang/ru/actions/modal.php
  packages/support/resources/lang/ru/actions/replicate.php
  packages/support/resources/lang/ru/actions/view.php
  packages/support/resources/lang/ru/components/button.php
  packages/tables/resources/lang/ru/table.php
Labels: enhancement, i18n

#3019 fix: Sanitise markdown
  composer.json
  composer.lock
  package-lock.json
  package.json
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/admin/src/NotificationManager.php
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/markdown-editor.js
  packages/forms/resources/views/components/field-wrapper/index.blade.php
  packages/forms/resources/views/components/field-wrapper/inline.blade.php
  packages/support/composer.json
  packages/support/composer.lock
  packages/support/src/SupportServiceProvider.php
  packages/support/src/helpers.php
Labels: bug

#3024 Update doc CreateAction in RelationManager
  packages/admin/docs/02-resources/06-relation-managers.md
Labels: bug, documentation

#3039 fix: Alpine keybindings invalid +
  package-lock.json
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.js
  packages/support/resources/views/components/button.blade.php
  packages/support/resources/views/components/icon-button.blade.php
  packages/support/resources/views/components/link.blade.php
Labels: bug

#3041 fix/2896 Fix saving pivot values in CreateAction
  packages/tables/src/Actions/CreateAction.php
Labels: bug

#3050 Pass old state to form field callback
  packages/forms/src/Components/Concerns/HasState.php
Labels: enhancement

#3061 Sidebar Item active class
  packages/admin/resources/views/components/layouts/app/sidebar/item.blade.php
Labels: enhancement

#3057 Docs: Fix renderHook names
  packages/admin/resources/views/components/layouts/base.blade.php
Labels: bug

#3072 Add pt-BR translation to Repeater component
  packages/forms/resources/lang/pt_BR/components.php
Labels: enhancement, i18n

#3082 Support BelongsToMany in HasRelationship
  packages/tables/src/Filters/Concerns/HasRelationship.php
Labels: enhancement

#3087 Ability to set step start
  packages/forms/resources/views/components/wizard.blade.php
  packages/forms/src/Components/Wizard.php
Labels: enhancement

#2769 Feature: Disable URL on table column
  packages/tables/docs/03-columns.md
  packages/tables/resources/views/components/cell.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Columns/Column.php
  packages/tables/src/Columns/Concerns/CanBeDisabled.php
Labels: enhancement

#2853 Feature: limit on Tables\TagsColumn
  packages/tables/resources/lang/en/table.php
  packages/tables/resources/lang/it/table.php
  packages/tables/resources/views/columns/tags-column.blade.php
  packages/tables/src/Columns/TagsColumn.php
Labels: enhancement

#3099 Change to use contract
  packages/admin/src/Commands/MakeUserCommand.php
Labels: bug

#3104 PageClass property in RelationManager
  packages/admin/resources/views/components/resources/relation-managers/index.blade.php
  packages/admin/resources/views/resources/pages/edit-record.blade.php
  packages/admin/resources/views/resources/pages/view-record.blade.php
  packages/admin/src/Resources/RelationManagers/RelationManager.php
Labels: enhancement

#3107 fix: Button text wrapping
  packages/support/resources/views/components/button.blade.php
Labels: bug, ui

#3102 CHG: Make filament app.js defer
  packages/admin/resources/views/components/layouts/base.blade.php
Labels: bug

#3131 Update turkish translations
  packages/admin/resources/lang/tr/global-search.php
  packages/admin/resources/lang/tr/layout.php
  packages/admin/resources/lang/tr/login.php
  packages/admin/resources/lang/tr/resources/pages/create-record.php
  packages/admin/resources/lang/tr/resources/pages/edit-record.php
  packages/admin/resources/lang/tr/resources/pages/view-record.php
  packages/admin/resources/lang/tr/widgets/filament-info-widget.php
  packages/forms/resources/lang/tr/components.php
  packages/support/resources/lang/tr/actions/associate.php
  packages/support/resources/lang/tr/actions/attach.php
  packages/support/resources/lang/tr/actions/create.php
  packages/support/resources/lang/tr/actions/delete.php
  packages/support/resources/lang/tr/actions/detach.php
  packages/support/resources/lang/tr/actions/dissociate.php
  packages/support/resources/lang/tr/actions/edit.php
  packages/support/resources/lang/tr/actions/force-delete.php
  packages/support/resources/lang/tr/actions/group.php
  packages/support/resources/lang/tr/actions/replicate.php
  packages/support/resources/lang/tr/actions/restore.php
  packages/support/resources/lang/tr/actions/view.php
  packages/tables/resources/lang/tr/table.php
Labels: enhancement, i18n

#3126 Use Laravel Pint for code style
  .github/workflows/pint.yml
  .gitignore
  .php-cs-fixer.dist.php
  bootstrap/app.php
  composer.json
  composer.lock
  monorepo-builder.php
  packages/admin/config/filament.php
  packages/admin/resources/lang/ru/layout.php
  packages/admin/src/Http/Livewire/Auth/Login.php
  packages/admin/src/Navigation/NavigationBuilder.php
  packages/forms/resources/lang/pt_BR/components.php
  packages/forms/resources/lang/ru/components.php
  packages/forms/src/Commands/InstallCommand.php
  packages/forms/src/ComponentContainer.php
  packages/forms/src/Components/Concerns/CanBeHidden.php
  packages/forms/src/Components/Concerns/CanLimitItemsLength.php
  packages/forms/src/Components/Select.php
  packages/forms/src/helpers.php
  packages/spatie-laravel-media-library-plugin/src/Forms/Components/SpatieMediaLibraryFileUpload.php
  packages/support/resources/lang/ru/actions/associate.php
  packages/support/resources/lang/ru/actions/attach.php
  packages/support/resources/lang/ru/actions/create.php
  packages/support/resources/lang/ru/actions/delete.php
  packages/support/resources/lang/ru/actions/detach.php
  packages/support/resources/lang/ru/actions/dissociate.php
  packages/support/resources/lang/ru/actions/edit.php
  packages/support/resources/lang/ru/actions/modal.php
  packages/support/resources/lang/ru/actions/replicate.php
  packages/support/resources/lang/ru/actions/view.php
  packages/support/resources/lang/ru/components/button.php
  packages/support/src/Actions/BaseAction.php
  packages/tables/resources/lang/de/table.php
  packages/tables/resources/lang/es/table.php
  packages/tables/resources/lang/nl/table.php
  packages/tables/src/Columns/Column.php
  packages/tables/src/Columns/Concerns/CanFormatState.php
  packages/tables/src/Columns/ImageColumn.php
  packages/tables/src/Commands/InstallCommand.php
  packages/tables/src/Concerns/HasActions.php
  packages/tables/src/Concerns/HasRecords.php
  packages/tables/src/Concerns/InteractsWithTable.php
  packages/tables/src/Filters/Layout.php
  pint.json
  tests/database/migrations/create_posts_table.php
  tests/database/migrations/create_users_table.php
  tests/src/Admin/Auth/LogoutTest.php
  tests/src/Admin/Http/Controllers/AssetControllerTest.php
  tests/src/Admin/RenderHooks/RenderHooksTest.php
Labels: chore, code quality

#2952 FIX: Respect action align setting
  packages/admin/config/filament.php
  packages/admin/resources/views/components/modal/actions.blade.php
  packages/admin/src/Http/Middleware/MirrorConfigToSubpackages.php
Labels: bug

#2885 Normalize English actions translations
  packages/support/resources/lang/en/actions/detach.php
  packages/support/resources/lang/en/actions/dissociate.php
  packages/support/resources/lang/en/actions/force-delete.php
  packages/support/resources/lang/en/actions/replicate.php
  packages/support/resources/lang/en/actions/restore.php
  packages/support/resources/lang/it/actions/replicate.php
Labels: i18n

#2965 Feature: allow storing filters in session
  packages/tables/docs/04-filters.md
  packages/tables/src/Concerns/HasFilters.php
  packages/tables/src/Concerns/InteractsWithTable.php
  tests/src/Tables/FilterTest.php
  tests/src/Tables/Fixtures/PostsTable.php
Labels: enhancement

#2986 Add `enableOpen` to FileUpload field
  packages/forms/docs/03-fields.md
  packages/forms/resources/css/components/file-upload.css
  packages/forms/resources/js/components/file-upload.js
  packages/forms/resources/views/components/file-upload.blade.php
  packages/forms/src/Components/BaseFileUpload.php
Labels: enhancement

#3021 Add Dusk selectors to actions and notification
  packages/admin/resources/views/components/notification.blade.php
  packages/admin/resources/views/components/pages/actions/action.blade.php
  packages/forms/resources/views/components/actions/action.blade.php
  packages/tables/resources/views/components/actions/action.blade.php
Labels: enhancement

#3137 fix: capitalized sorting order not working on table
  packages/admin/src/Resources/Table.php
Labels: bug

#3097 feature: allow configuring "close on backdrop click" for modals
  packages/support/config/filament-support.php
  packages/support/resources/views/components/modal/index.blade.php
  packages/support/src/SupportServiceProvider.php
Labels: enhancement

#3139 Fix broken filterTable testing helper
  packages/tables/.stubs.php
  packages/tables/src/Concerns/HasFilters.php
  packages/tables/src/Testing/TestsFilters.php
  tests/src/Tables/FilterTest.php
  tests/src/Tables/Fixtures/PostsTable.php
Labels: bug

#3054 Update getRules() to stay compatible with future v. of Livewire
  packages/forms/src/Concerns/InteractsWithForms.php
Labels: chore

#3058 Fixing idea #3053
  packages/forms/docs/04-layout.md
  packages/forms/resources/views/components/tabs.blade.php
  packages/forms/src/Components/Tabs/Tab.php
Labels: enhancement

#3062 Added repeater item label option
  packages/forms/docs/03-fields.md
  packages/forms/resources/views/components/repeater.blade.php
  packages/forms/src/Components/Concerns/EntanglesStateWithSingularRelationship.php
  packages/forms/src/Components/Concerns/HasChildComponents.php
  packages/forms/src/Components/Repeater.php
Labels: enhancement

#3144 German translations
  packages/support/resources/lang/de/actions/associate.php
  packages/support/resources/lang/de/actions/dissociate.php
  packages/support/resources/lang/de/actions/force-delete.php
  packages/support/resources/lang/de/actions/group.php
  packages/support/resources/lang/de/actions/replicate.php
  packages/support/resources/lang/de/actions/restore.php
  packages/support/resources/lang/de/actions/view.php
  packages/support/resources/lang/de/components/button.php
Labels: enhancement, i18n

#3143 Add CSS classes to resource pages
  packages/admin/resources/views/resources/pages/create-record.blade.php
  packages/admin/resources/views/resources/pages/edit-record.blade.php
  packages/admin/resources/views/resources/pages/list-records.blade.php
  packages/admin/resources/views/resources/pages/view-record.blade.php
Labels: enhancement

#3145 fix event listeners in floating ui for livewire dom diffing
  package-lock.json
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.js
Labels: bug

#3065 Make collapsible Section header clickable + scrollIntoView onClick
  packages/forms/resources/views/components/section.blade.php
Labels: enhancement

#3148 fix: Conditional wire:click
  packages/admin/resources/views/components/pages/actions/action.blade.php
  packages/forms/resources/views/components/actions/action.blade.php
  packages/tables/resources/views/components/actions/action.blade.php
Labels: bug

#3155 fix: Always pluralize resource slug
  packages/admin/src/Resources/Resource.php
  tests/src/Admin/Resources/ResourceTest.php
Labels: bug

#3150 Adds closeOnDateSelection() to date time picker
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/date-time-picker.js
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/src/Components/DateTimePicker.php
Labels: enhancement

#3156 fix: Login throttle message
  packages/admin/src/Http/Livewire/Auth/Login.php
Labels: bug

#3154 Support action groups in table header actions array
  packages/admin/src/Resources/Table.php
  packages/tables/src/Concerns/HasHeader.php
Labels: enhancement

#3157 fix getOptionLabelFromRecordUsing() in document
  packages/forms/docs/03-fields.md
Labels: bug, documentation

#3158 fix broken link in doc
  packages/forms/docs/04-layout.md
Labels: bug, documentation

#3161 fix: Skipping wizard steps
  packages/forms/resources/views/components/wizard.blade.php
  packages/support/resources/views/components/button.blade.php
  packages/tables/resources/views/components/cell.blade.php
  packages/tables/resources/views/components/checkbox-cell.blade.php
Labels: bug

#3162 chore: Streamline reporting
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  README.md
Labels: chore

#3167 fix: Bug report template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: bug, chore

#3166 fix: PageClass property nullable by default
  packages/admin/src/Resources/RelationManagers/RelationManager.php
Labels: bug

#3197 Translation correction
  packages/support/resources/lang/ru/actions/force-delete.php
Labels: i18n

#3206 fix: relation manager table description colour
  packages/tables/resources/views/components/header/description.blade.php
Labels: bug

#3204 Fix: Inability to mutate form data when using Translatable package
  packages/spatie-laravel-translatable-plugin/src/Resources/Pages/EditRecord/Concerns/Translatable.php
  packages/spatie-laravel-translatable-plugin/src/Resources/Pages/ViewRecord/Concerns/Translatable.php
Labels: bug

#3212 fix: Select search columns
  packages/forms/src/Components/Select.php
Labels: bug

#3176 feature: add useful info to new `about` command
  .github/workflows/phpstan.yml
  .github/workflows/tests.yml
  composer.json
  composer.lock
  packages/support/src/SupportServiceProvider.php
Labels: enhancement

#3218 Feature: Add color choices to NavigationItem badges
  packages/admin/docs/05-navigation.md
  packages/admin/resources/views/components/layouts/app/sidebar/index.blade.php
  packages/admin/resources/views/components/layouts/app/sidebar/item.blade.php
  packages/admin/src/Navigation/NavigationItem.php
  packages/admin/src/Pages/Page.php
  packages/admin/src/Resources/Resource.php
Labels: enhancement

#3184 Fix: Floating UI Table Panels Issues
  package-lock.json
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/tables/resources/views/components/filters/index.blade.php
  packages/tables/resources/views/components/filters/popover.blade.php
  packages/tables/resources/views/components/filters/trigger.blade.php
  packages/tables/resources/views/components/toggleable/index.blade.php
  packages/tables/resources/views/components/toggleable/trigger.blade.php
Labels: bug

#3216 feature: Navigation group objects
  packages/admin/docs/05-navigation.md
  packages/admin/resources/js/app.js
  packages/admin/resources/views/components/layouts/app/sidebar/group.blade.php
  packages/admin/resources/views/components/layouts/app/sidebar/index.blade.php
  packages/admin/resources/views/components/layouts/app/sidebar/item.blade.php
  packages/admin/src/FilamentManager.php
  packages/admin/src/Navigation/NavigationBuilder.php
  packages/admin/src/Navigation/NavigationGroup.php
  packages/admin/src/Navigation/NavigationItem.php
  packages/admin/src/Pages/Page.php
  packages/admin/src/Resources/Resource.php
  tests/src/Admin/Fixtures/Pages/Settings.php
  tests/src/Admin/Fixtures/Resources/PostCategoryResource.php
  tests/src/Admin/Fixtures/Resources/PostCategoryResource/Pages/CreatePostCategory.php
  tests/src/Admin/Fixtures/Resources/PostCategoryResource/Pages/EditPostCategory.php
  tests/src/Admin/Fixtures/Resources/PostCategoryResource/Pages/ListPostCategories.php
  tests/src/Admin/Fixtures/Resources/PostCategoryResource/Pages/ViewPostCategory.php
  tests/src/Admin/Fixtures/Resources/PostResource.php
  tests/src/Admin/Fixtures/Resources/ProductResource.php
  tests/src/Admin/Fixtures/Resources/ProductResource/Pages/CreateProduct.php
  tests/src/Admin/Fixtures/Resources/ProductResource/Pages/EditProduct.php
  tests/src/Admin/Fixtures/Resources/ProductResource/Pages/ListProducts.php
  tests/src/Admin/Fixtures/Resources/ProductResource/Pages/ViewProduct.php
  tests/src/Admin/Fixtures/Resources/UserResource.php
  tests/src/Admin/Navigation/NavigationBuilderTest.php
  tests/src/Admin/Navigation/NavigationServiceProvider.php
  tests/src/Admin/Navigation/NavigationTest.php
  tests/src/Admin/Navigation/TestCase.php
Labels: enhancement

#3228 Fixed translated direction problem
  packages/admin/resources/lang/tr/layout.php
Labels: bug, i18n

#3231 chore: Remove unnecessary highlight
  packages/notifications/docs/02-sending-notifications.md
Labels: documentation

#3234 Update Readme
  README.md
Labels: enhancement

#3235 Add FR translation for the reorder_indicator
  packages/tables/resources/lang/fr/table.php
Labels: enhancement, i18n

#3236 Typo in Table Docs: reordering section
  packages/tables/docs/02-getting-started.md
Labels: documentation

#3243 Add screenshots to notifications docs
  packages/notifications/docs/02-sending-notifications.md
Labels: documentation, enhancement

#3248 [LANG][AR] table translations
  packages/tables/resources/lang/ar/table.php
Labels: enhancement, i18n

#3252 Add pagination methods to table LOADING_TARGETS
  packages/tables/src/Table.php
Labels: bug

#3251 Add table orderable FA translation
  packages/tables/resources/lang/fa/table.php
Labels: enhancement, i18n

#3253 fix: @js attribute binding
  packages/tables/resources/views/index.blade.php
Labels: bug

#3229 Add documentation for default sort methods
  packages/tables/docs/03-columns.md
Labels: documentation

#3242 Added translations for ordening
  packages/tables/resources/lang/nl/table.php
Labels: enhancement, i18n

#3277 [Docs][Spatie-Translatable] Fix Docs get Actions
  packages/spatie-laravel-translatable-plugin/docs/02-getting-started.md
Labels: bug, documentation

#3281 Require issue reproduction
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: chore

#3284 Give default items an uuid
  packages/forms/src/Components/Repeater.php
Labels: bug

#3289 chore: Update manage issue
  .github/workflows/manage-issue.yml
Labels: chore

#3295 chore: Close issues as not planned
  .github/workflows/manage-issue.yml
Labels: chore

#3298 Table: vi translations
  packages/tables/resources/lang/vi/table.php
Labels: enhancement, i18n

#3305 admin: vi translations
  packages/admin/resources/lang/vi/layout.php
  packages/admin/resources/lang/vi/login.php
Labels: enhancement, i18n

#3300 forms: vi translations
  packages/forms/resources/lang/vi/components.php
Labels: enhancement, i18n

#3297 RU & UA translation update
  packages/forms/resources/lang/ru/components.php
  packages/spatie-laravel-settings-plugin/resources/lang/ru/pages/settings-page.php
  packages/spatie-laravel-settings-plugin/resources/lang/uk/pages/settings-page.php
  packages/spatie-laravel-translatable-plugin/resources/lang/ru/actions.php
  packages/spatie-laravel-translatable-plugin/resources/lang/uk/actions.php
  packages/tables/resources/lang/ru/table.php
  packages/tables/resources/lang/uk/table.php
Labels: enhancement, i18n

#3301 spatie-laravel-translatable-plugin: vi translations
  packages/spatie-laravel-translatable-plugin/resources/lang/vi/actions.php
Labels: enhancement, i18n

#3303 spatie-laravel-settings-plugin: vi translations
  packages/spatie-laravel-settings-plugin/resources/lang/vi/pages/settings-page.php
Labels: enhancement, i18n

#3309 Improve id lang
  packages/tables/resources/lang/id/table.php
Labels: enhancement, i18n

#3022 Support Debounce
  packages/forms/resources/views/components/key-value.blade.php
  packages/forms/src/Components/CheckboxList.php
  packages/forms/src/Concerns/HasStateBindingModifiers.php
Labels: enhancement

#3129 Add not exists testing helpers for action, bulk action, and columns
  packages/admin/.stubs.php
  packages/admin/docs/09-testing.md
  packages/admin/src/Testing/TestsPages.php
  packages/tables/.stubs.php
  packages/tables/docs/06-testing.md
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Concerns/CanReorderRecords.php
  packages/tables/src/Concerns/HasActions.php
  packages/tables/src/Concerns/HasBulkActions.php
  packages/tables/src/Concerns/HasColumns.php
  packages/tables/src/Concerns/HasRecords.php
  packages/tables/src/Concerns/InteractsWithTable.php
  packages/tables/src/Contracts/HasTable.php
  packages/tables/src/Table.php
  packages/tables/src/Testing/TestsActions.php
  packages/tables/src/Testing/TestsColumns.php
  packages/tables/src/Testing/TestsFilters.php
  tests/src/Admin/Fixtures/Pages/PageActions.php
  tests/src/Admin/Pages/ActionTest.php
  tests/src/Tables/ActionTest.php
  tests/src/Tables/ColumnTest.php
  tests/src/Tables/Fixtures/PostsTable.php
Labels: enhancement

#3308 Update CreateAction.php - Reset Record After Creation
  packages/admin/src/Pages/Concerns/HasActions.php
  packages/tables/src/Concerns/HasActions.php
Labels: bug

#3322 fix: Allow class sanitization
  packages/support/config/html-sanitizer.php
  packages/support/src/SupportServiceProvider.php
Labels: bug

#3323 fix: Results not found select
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/select.js
Labels: bug
