Repository filamentphp/filament, pull requests merged in 2023-04, with the labels that each got.

#6092 fix: Nested BelongsTo layout component
  packages/forms/src/Components/Concerns/BelongsToModel.php
  packages/forms/src/Components/Concerns/EntanglesStateWithSingularRelationship.php
  packages/forms/src/Concerns/BelongsToModel.php
Labels: bug

#6094 Update 10-testing.md
  packages/admin/docs/10-testing.md
Labels: bug, documentation

#6102 Fix: markdown disappearing in modal and light/dark mode
  docs-assets/screenshots/images/dark/actions/modal/wizard.jpg
  docs-assets/screenshots/images/dark/app/dashboard.jpg
  docs-assets/screenshots/images/light/app/dashboard.jpg
  package-lock.json
  packages/app/dist/theme.css
  packages/forms/dist/index.css
  packages/forms/resources/css/components/markdown-editor.css
  packages/support/resources/views/components/modal/index.blade.php
Labels: bug, ui

#6115 Update relation manager nav button duplicate class index.blade.php
  packages/admin/resources/views/components/resources/relation-managers/index.blade.php
Labels: chore

#6126 Catalan (Català) translations
  packages/admin/resources/lang/ca/global-search.php
  packages/admin/resources/lang/ca/layout.php
  packages/admin/resources/lang/ca/login.php
  packages/admin/resources/lang/ca/pages/dashboard.php
  packages/admin/resources/lang/ca/resources/pages/create-record.php
  packages/admin/resources/lang/ca/resources/pages/edit-record.php
  packages/admin/resources/lang/ca/resources/pages/list-records.php
  packages/admin/resources/lang/ca/resources/pages/view-record.php
  packages/admin/resources/lang/ca/widgets/account-widget.php
  packages/admin/resources/lang/ca/widgets/filament-info-widget.php
  packages/spatie-laravel-translatable-plugin/resources/lang/ca/actions.php
  packages/support/resources/lang/ca/actions/associate.php
  packages/support/resources/lang/ca/actions/attach.php
  packages/support/resources/lang/ca/actions/create.php
  packages/support/resources/lang/ca/actions/delete.php
  packages/support/resources/lang/ca/actions/detach.php
  packages/support/resources/lang/ca/actions/dissociate.php
  packages/support/resources/lang/ca/actions/edit.php
  packages/support/resources/lang/ca/actions/force-delete.php
  packages/support/resources/lang/ca/actions/group.php
  packages/support/resources/lang/ca/actions/modal.php
  packages/support/resources/lang/ca/actions/replicate.php
  packages/support/resources/lang/ca/actions/restore.php
  packages/support/resources/lang/ca/actions/view.php
  packages/support/resources/lang/ca/components/button.php
  packages/support/resources/lang/ca/components/modal.php
Labels: i18n

#6131 Improve composer.json snippet in README
  README.md
Labels: chore

#6142 Accept closure for builder blocks
  packages/forms/src/Components/Builder.php
Labels: enhancement

#6141 fix: Delete media library file for single upload
  packages/spatie-laravel-media-library-plugin/src/Forms/Components/SpatieMediaLibraryFileUpload.php
Labels: bug

#6153 Fix issue with repeater loading
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/repeater.blade.php
Labels: bug

#6151 Fix dropdown button loading indicator to work with livewire event modifiers
  packages/support/resources/views/components/button.blade.php
  packages/support/resources/views/components/dropdown/list/item.blade.php
  packages/support/resources/views/components/icon-button.blade.php
  packages/support/resources/views/components/link.blade.php
Labels: bug

#6150 Improve Spanish translations
  packages/admin/resources/lang/es/resources/pages/create-record.php
  packages/admin/resources/lang/es/resources/pages/edit-record.php
  packages/forms/resources/lang/es/components.php
  packages/notifications/resources/lang/es/database.php
  packages/support/resources/lang/es/actions/delete.php
  packages/support/resources/lang/es/actions/detach.php
  packages/support/resources/lang/es/actions/dissociate.php
  packages/tables/resources/lang/es/table.php
Labels: i18n

#6161 Update zh_CN translation
  packages/admin/resources/lang/zh_CN/layout.php
  packages/admin/resources/lang/zh_CN/resources/pages/edit-record.php
  packages/admin/resources/lang/zh_CN/resources/pages/view-record.php
Labels: i18n

#6140 Add placeholder to search input in Select component
  packages/forms/resources/css/components/select.css
  packages/forms/resources/js/components/select.js
  packages/forms/resources/lang/pt_BR/components.php
Labels: enhancement

#6160 Update Georgian translations
  packages/tables/resources/lang/ka/table.php
Labels: i18n

#6166 Show key-value component delete button for single row
  packages/forms/resources/views/components/key-value.blade.php
Labels: bug

#6173 Backport notifications animation fix
  packages/notifications/resources/js/components/notification.js
  packages/notifications/src/Http/Livewire/Notifications.php
Labels: bug

#6201 Update Polish translations
  packages/admin/resources/lang/pl/layout.php
  packages/forms/resources/lang/pl/components.php
  packages/tables/resources/lang/pl/table.php
Labels: i18n

#6211 Updates forms/layout#saving-data-to-relationships documentation.
  packages/forms/docs/04-layout.md
Labels: documentation

#6213 Filament\Widgets\StatsOverviewWidget\Card fix types
  packages/admin/src/Widgets/StatsOverviewWidget/Card.php
  packages/forms/src/Components/Fieldset.php
Labels: bug

#6216 Optimisation for file upload form component in spatie media library
  packages/spatie-laravel-media-library-plugin/src/Forms/Components/SpatieMediaLibraryFileUpload.php
Labels: enhancement

#6182 Improved handling of file-upload-started/finished events for FileUpload
  packages/forms/resources/js/components/file-upload.js
Labels: bug

#6205 Allow usage of table alias in reorderable
  packages/tables/src/Concerns/CanReorderRecords.php
Labels: bug

#6196 Add `Filament::isServingFilament()`
  packages/admin/src/Facades/Filament.php
  packages/admin/src/FilamentManager.php
  packages/admin/src/FilamentServiceProvider.php
Labels: enhancement

#6207 Add class to identify repeater item
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/repeater.blade.php
Labels: enhancement

#6103 Add placeholder property to `TextColumn`s and `BadgeColumn`s
  packages/tables/docs/03-columns/02-text.md
  packages/tables/src/Columns/Concerns/CanFormatState.php
Labels: enhancement

#6192 Docs: Mention Livewire default 12MB file size upload maximum
  packages/forms/docs/03-fields.md
Labels: documentation

#6198 Fix for toggle-column console error
  packages/tables/resources/views/columns/toggle-column.blade.php
Labels: bug

#6121 Add "InOrder" Table & Page Action assertions
  packages/admin/.stubs.php
  packages/admin/docs/10-testing.md
  packages/admin/src/Pages/Concerns/HasActions.php
  packages/admin/src/Testing/TestsPageActions.php
  packages/support/src/Testing/TestsActions.php
  packages/tables/.stubs.php
  packages/tables/docs/07-testing.md
  packages/tables/src/Testing/TestsActions.php
  packages/tables/src/Testing/TestsBulkActions.php
  tests/src/Admin/Fixtures/Pages/PageActions.php
  tests/src/Admin/Pages/ActionTest.php
  tests/src/Tables/ActionTest.php
  tests/src/Tables/BulkActionTest.php
  tests/src/Tables/Fixtures/PostsTable.php
Labels: enhancement

#6222 Euskera (Basque) translations
  packages/admin/resources/lang/eu/global-search.php
  packages/admin/resources/lang/eu/layout.php
  packages/admin/resources/lang/eu/login.php
  packages/admin/resources/lang/eu/pages/dashboard.php
  packages/admin/resources/lang/eu/resources/pages/create-record.php
  packages/admin/resources/lang/eu/resources/pages/edit-record.php
  packages/admin/resources/lang/eu/resources/pages/list-records.php
  packages/admin/resources/lang/eu/resources/pages/view-record.php
  packages/admin/resources/lang/eu/widgets/account-widget.php
  packages/admin/resources/lang/eu/widgets/filament-info-widget.php
  packages/forms/resources/lang/eu/components.php
  packages/notifications/resources/lang/eu/database.php
  packages/spatie-laravel-settings-plugin/resources/lang/eu/pages/settings-page.php
  packages/spatie-laravel-translatable-plugin/resources/lang/eu/actions.php
  packages/support/resources/lang/eu/actions/associate.php
  packages/support/resources/lang/eu/actions/attach.php
  packages/support/resources/lang/eu/actions/create.php
  packages/support/resources/lang/eu/actions/delete.php
  packages/support/resources/lang/eu/actions/detach.php
  packages/support/resources/lang/eu/actions/dissociate.php
  packages/support/resources/lang/eu/actions/edit.php
  packages/support/resources/lang/eu/actions/force-delete.php
  packages/support/resources/lang/eu/actions/group.php
  packages/support/resources/lang/eu/actions/modal.php
  packages/support/resources/lang/eu/actions/replicate.php
  packages/support/resources/lang/eu/actions/restore.php
  packages/support/resources/lang/eu/actions/view.php
  packages/support/resources/lang/eu/components/button.php
  packages/support/resources/lang/eu/components/modal.php
  packages/tables/resources/lang/eu/table.php
Labels: enhancement, i18n

#6224 Update vi translation
  packages/tables/resources/lang/vi/table.php
Labels: i18n

#6235 Normalize colors order
  packages/app/src/Context/Concerns/HasColors.php
Labels: code quality

#6236 Support 950 color shade
  packages/actions/docs/01-installation.md
  packages/app/docs/11-themes.md
  packages/app/src/Context/Concerns/HasColors.php
  packages/app/src/Facades/Filament.php
  packages/app/src/FilamentManager.php
  packages/app/tailwind.config.preset.js
  packages/forms/docs/01-installation.md
  packages/notifications/docs/01-installation.md
  packages/support/src/Color.php
  packages/tables/docs/01-installation.md
  packages/widgets/docs/01-installation.md
Labels: enhancement

#6238 feature: Support storeFiles() method
  packages/forms/src/Components/BaseFileUpload.php
Labels: enhancement

#6237 Upgrade to Tailwind CSS v3.3
  package-lock.json
  package.json
  packages/app/dist/theme.css
  packages/app/resources/views/components/global-search/index.blade.php
  packages/app/resources/views/components/global-search/input.blade.php
  packages/app/resources/views/components/global-search/results-container.blade.php
  packages/app/resources/views/components/layouts/app.blade.php
  packages/app/resources/views/components/layouts/app/sidebar/badge.blade.php
  packages/app/resources/views/components/layouts/app/sidebar/group.blade.php
  packages/app/resources/views/components/layouts/app/sidebar/index.blade.php
  packages/app/resources/views/components/layouts/app/topbar/badge.blade.php
  packages/app/resources/views/components/layouts/app/topbar/breadcrumbs.blade.php
  packages/app/resources/views/components/layouts/app/topbar/database-notifications-trigger.blade.php
  packages/app/resources/views/components/layouts/app/topbar/index.blade.php
  packages/app/resources/views/components/layouts/card.blade.php
  packages/app/resources/views/components/user-menu.blade.php
  packages/app/resources/views/widgets/filament-info-widget.blade.php
  packages/forms/dist/components/text-input.js
  packages/forms/dist/index.css
  packages/forms/resources/css/components/file-upload.css
  packages/forms/resources/css/components/rich-editor.css
  packages/forms/resources/css/components/select.css
  packages/forms/resources/views/components/color-picker.blade.php
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/resources/views/components/fieldset.blade.php
  packages/forms/resources/views/components/text-input.blade.php
  packages/forms/resources/views/components/wizard.blade.php
  packages/infolists/resources/views/components/fieldset.blade.php
  packages/notifications/resources/views/components/database/modal/heading.blade.php
  packages/notifications/resources/views/components/database/modal/index.blade.php
  packages/support/resources/views/components/button.blade.php
  packages/support/resources/views/components/dropdown/list/item.blade.php
  packages/support/resources/views/components/dropdown/list/separator.blade.php
  packages/support/resources/views/components/grid/column.blade.php
  packages/support/resources/views/components/grid/index.blade.php
  packages/support/resources/views/components/icon-button.blade.php
  packages/support/resources/views/components/input/affixes.blade.php
  packages/support/resources/views/components/input/select.blade.php
  packages/support/resources/views/components/link.blade.php
  packages/support/resources/views/components/modal/index.blade.php
  packages/support/resources/views/components/section.blade.php
  packages/tables/docs/09-advanced.md
  packages/tables/resources/views/columns/checkbox-column.blade.php
  packages/tables/resources/views/columns/select-column.blade.php
  packages/tables/resources/views/columns/text-input-column.blade.php
  packages/tables/resources/views/columns/toggle-column.blade.php
  packages/tables/resources/views/components/filters/indicators.blade.php
  packages/tables/resources/views/components/header/index.blade.php
  packages/tables/resources/views/components/pagination/index.blade.php
  packages/tables/resources/views/components/pagination/records-per-page-selector.blade.php
  packages/tables/resources/views/components/reorder/indicator.blade.php
  packages/tables/resources/views/components/search-input.blade.php
  packages/tables/resources/views/components/selection-indicator.blade.php
  packages/tables/resources/views/index.blade.php
Labels: enhancement

#6241 Add missing import to docs
  packages/app/docs/10-tenancy.md
Labels: documentation

#6243 Add missing German translation
  packages/tables/resources/lang/de/table.php
Labels: i18n

#6253 Add Italian translations for notifications
  packages/notifications/resources/lang/it/database.php
Labels: i18n

#6257 Revert "Map uuid to id from already loaded relationship in spatie media library"
  packages/spatie-laravel-media-library-plugin/src/Forms/Components/SpatieMediaLibraryFileUpload.php
Labels: bug

#6278 Use Laravel's generated column key name instead of relationship qualified key name
  packages/tables/src/Actions/AssociateAction.php
  packages/tables/src/Actions/AttachAction.php
Labels: bug

#6282 Documentation Admin publishing translations fix
  packages/admin/docs/01-installation.md
Labels: documentation

#6280 Improve auth pages extensibility
  packages/app/resources/views/pages/auth/login.blade.php
  packages/app/resources/views/pages/auth/register.blade.php
  packages/app/src/Pages/Auth/Login.php
  packages/app/src/Pages/Auth/Register.php
  tests/src/App/Auth/LoginTest.php
  tests/src/App/Auth/RegisterTest.php
Labels: enhancement

#6289 Improve vi translation
  packages/tables/resources/lang/vi/table.php
Labels: i18n

#6291 Add "signed" middleware to email verification route.
  packages/app/routes/web.php
Labels: bug

#6296 Add minimum-stability "dev" to contribute guide
  README.md
Labels: documentation

#6269 Add classes to wizard component
  packages/forms/resources/views/components/wizard.blade.php
Labels: enhancement

#6284 Fixes markdown editor character overlapping in RTL
  packages/forms/resources/views/components/markdown-editor.blade.php
Labels: bug

#6321 Support `HtmlString` in repeater and builder `itemLabel`
  packages/forms/src/Components/Builder/Block.php
  packages/forms/src/Components/Repeater.php
Labels: enhancement

#6333 Fix infolists enum state
  packages/infolists/src/Components/Concerns/HasState.php
Labels: bug, pending review

#6326 Add support for copying badge column
  packages/tables/docs/03-columns/05-badge.md
  packages/tables/resources/views/columns/badge-column.blade.php
  packages/tables/src/Columns/BadgeColumn.php
Labels: enhancement, pending review

#6332 Fix tenant menu in collapsed sidebar
  packages/app/resources/views/components/layouts/app/sidebar/index.blade.php
  packages/app/resources/views/components/tenant-menu.blade.php
  packages/support/resources/views/components/dropdown/index.blade.php
Labels: bug, pending review

#6266 Support custom columns for form grid
  packages/admin/src/Pages/Dashboard.php
  packages/admin/src/Pages/Page.php
  packages/admin/src/Resources/Form.php
  packages/forms/src/Components/Concerns/HasContainerGridLayout.php
  packages/forms/src/Components/Grid.php
  packages/forms/src/Concerns/HasColumns.php
  packages/tables/src/Columns/Layout/Grid.php
  packages/tables/src/Filters/Concerns/HasColumns.php
Labels: enhancement, pending review

#6288 Use actions for buttons and links
  packages/app/resources/views/pages/auth/email-verification/email-verification-prompt.blade.php
  packages/app/resources/views/pages/auth/login.blade.php
  packages/app/resources/views/pages/auth/password-reset/request-password-reset.blade.php
  packages/app/resources/views/pages/auth/password-reset/reset-password.blade.php
  packages/app/resources/views/pages/auth/register.blade.php
  packages/app/resources/views/pages/tenancy/register-tenant.blade.php
  packages/app/src/Pages/Auth/EmailVerification/EmailVerificationPrompt.php
  packages/app/src/Pages/Auth/Login.php
  packages/app/src/Pages/Auth/PasswordReset/RequestPasswordReset.php
  packages/app/src/Pages/Auth/PasswordReset/ResetPassword.php
  packages/app/src/Pages/Auth/Register.php
  packages/app/src/Pages/Tenancy/RegisterTenant.php
  tests/src/App/Auth/EmailVerification/EmailVerificationPromptTest.php
Labels: enhancement

#6317 Add render hooks to relation managers
  packages/admin/docs/08-appearance.md
  packages/admin/resources/views/resources/relation-manager.blade.php
Labels: enhancement, pending review

#6324 Add class to identify fields
  packages/forms/resources/views/components/checkbox.blade.php
  packages/forms/resources/views/components/color-picker.blade.php
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/resources/views/components/select.blade.php
  packages/forms/resources/views/components/text-input.blade.php
  packages/forms/resources/views/components/textarea.blade.php
Labels: enhancement, pending review

#6299 Persist table filters from request in session
  packages/tables/src/Concerns/InteractsWithTable.php
Labels: bug, pending review

#6336 Fix Text Input Error Focus
  packages/forms/resources/views/components/text-input.blade.php
Labels: bug, ui

#6341 Revert toggle columns
  packages/tables/src/Concerns/InteractsWithTable.php
Labels: bug

#6347 Fix billing provider type annotation
  packages/app/src/Billing/Providers/Contracts/Provider.php
Labels: bug

#6356 Add missing Malaysian translations
  packages/tables/resources/lang/ms/table.php
Labels: i18n

#6340 Remove sidebar shadow on mobile when closed
  packages/admin/resources/views/components/layouts/app/sidebar/index.blade.php
Labels: bug

#6357 Fieldset optional legend
  packages/forms/resources/views/components/fieldset.blade.php
  packages/forms/src/Components/Fieldset.php
Labels: enhancement

#6221 Fix all toggle column issues
  packages/tables/resources/views/columns/toggle-column.blade.php
Labels: bug

#6359 Fix broken link for theme (#building-themes)
  packages/admin/docs/08-appearance.md
Labels: bug, documentation

#6352 Add cell attributes to table columns
  packages/admin/resources/views/pages/actions/modal/actions/button-action.blade.php
  packages/forms/resources/views/components/actions/modal/actions/button-action.blade.php
  packages/forms/resources/views/components/checkbox-list.blade.php
  packages/forms/resources/views/components/radio.blade.php
  packages/tables/resources/views/actions/modal/actions/button-action.blade.php
  packages/tables/resources/views/components/cell.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Columns/Column.php
  packages/tables/src/Columns/Concerns/HasExtraCellAttributes.php
Labels: enhancement

#6262 Document undocumented admin test helpers
  packages/admin/.stubs.php
  packages/admin/docs/10-testing.md
Labels: documentation

#6263 Document undocumented table test helpers
  packages/admin/docs/10-testing.md
  packages/tables/.stubs.php
  packages/tables/docs/07-testing.md
Labels: documentation

#6351 Decrease width of open sidebar on mobile
  packages/admin/resources/views/components/layouts/app/sidebar/index.blade.php
Labels: enhancement, ui

#6129 Add more options for section aside
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/echo.js.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.js
  packages/forms/resources/views/components/section.blade.php
  packages/forms/src/Components/Section.php
Labels: enhancement

#5969 Fix sticky form actions with custom footer
  packages/admin/resources/views/components/form/actions.blade.php
Labels: bug

#6303 Support dropdown max height
  packages/support/resources/views/components/dropdown/index.blade.php
  packages/tables/resources/views/components/filters/popover.blade.php
  packages/tables/resources/views/components/toggleable/index.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Concerns/CanToggleColumns.php
  packages/tables/src/Concerns/HasFilters.php
  packages/tables/src/Table.php
Labels: enhancement

#6361 fix: Wizard scroll into view
  packages/forms/resources/views/components/wizard.blade.php
Labels: bug

#6358 fix: consistent error state
  packages/app/dist/theme.css
  packages/forms/dist/components/text-input.js
  packages/forms/dist/index.css
  packages/forms/resources/css/components/select.css
  packages/forms/resources/views/components/checkbox-list.blade.php
  packages/forms/resources/views/components/checkbox.blade.php
  packages/forms/resources/views/components/color-picker.blade.php
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/resources/views/components/radio.blade.php
  packages/forms/resources/views/components/rich-editor.blade.php
  packages/forms/resources/views/components/select.blade.php
  packages/forms/resources/views/components/tags-input.blade.php
  packages/forms/resources/views/components/text-input.blade.php
  packages/forms/resources/views/components/textarea.blade.php
  packages/support/resources/views/components/input/index.blade.php
  packages/support/resources/views/components/input/select.blade.php
Labels: ui

#6362 Revert "fix: Duplicate queries with relationship layout component"
  packages/forms/src/Components/Concerns/EntanglesStateWithSingularRelationship.php
Labels: bug

#6363 fix: Double validation on layout components
  packages/forms/src/Components/Concerns/EntanglesStateWithSingularRelationship.php
Labels: bug
