Repository filamentphp/filament, pull requests merged in 2023-01, with the labels that each got.

#5374 Fix: renderhook
  packages/admin/resources/views/components/pages/actions/index.blade.php
Labels: bug

#5383 User Menu RTL aligment fix.
  packages/admin/resources/views/components/layouts/app/topbar/user-menu.blade.php
Labels: i18n

#5390 Section description compact
  packages/forms/resources/views/components/section.blade.php
Labels: ui

#5399 Hail Mary check in getInverseRelation for mirrored naming
  packages/tables/src/Columns/Concerns/InteractsWithTableQuery.php
Labels: enhancement

#5403 3.x Docs: Add missing indentation
  packages/tables/docs/08-adding-a-table-to-a-livewire-component.md
Labels: documentation

#5407 Fix spelling mistake in docs
  packages/notifications/docs/06-testing.md
Labels: documentation

#5409 User Menu / RTL Fix
  packages/admin/resources/views/components/layouts/app/topbar/user-menu.blade.php
Labels: ui, i18n

#5423 Fully collapsible sidebar
  packages/app/resources/views/components/layouts/app.blade.php
  packages/app/resources/views/components/layouts/app/sidebar/index.blade.php
  packages/app/resources/views/components/topbar.blade.php
Labels: chore

#5425 Fix flash of collapsable columns
  packages/tables/resources/views/index.blade.php
Labels: ui

#5455 Fix sidebar group collapse icon size
  packages/app/resources/views/components/layouts/app/sidebar/group.blade.php
Labels: bug

#5462 Fixed typo in Romanian
  packages/admin/resources/lang/ro/widgets/account-widget.php
Labels: i18n

#5475 Builder collapse add click to header
  packages/forms/resources/views/components/builder.blade.php
Labels: enhancement

#5458 spatie translatable plugin - add support for Repeater and Builder components
  packages/spatie-laravel-translatable-plugin/src/Resources/Pages/CreateRecord/Concerns/Translatable.php
  packages/spatie-laravel-translatable-plugin/src/Resources/Pages/EditRecord/Concerns/Translatable.php
Labels: bug

#5480 feature: Extract block picker
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/builder/block-picker.blade.php
Labels: enhancement

#5483 Change schema to columns
  packages/tables/docs/02-getting-started.md
Labels: documentation

#5487 it localization dashboard name
  packages/admin/resources/lang/it/pages/dashboard.php
Labels: i18n

#5456 Fix table header sort icon direction
  packages/tables/resources/views/components/header-cell.blade.php
Labels: bug

#5494 fix rtl for database notification icon
  packages/admin/resources/views/components/layouts/app/topbar/database-notifications-trigger.blade.php
Labels: i18n

#5498 Fix return type annotation
  packages/app/src/Resources/Resource.php
Labels: bug

#5476 Builder Containers reduce spacing between elements
  packages/forms/resources/views/components/builder.blade.php
Labels: ui

#5428 Fix table alignment with action button
  packages/tables/resources/views/components/columns/column.blade.php
Labels: bug

#5509 Updates 08-appearance.md
  packages/admin/docs/08-appearance.md
Labels: documentation

#5508 remove semicolon
  packages/forms/docs/06-adding-a-form-to-a-livewire-component.md
Labels: documentation

#5036 Add searchable trait to checkbox list component
  packages/forms/resources/views/components/checkbox-list.blade.php
  packages/forms/src/Components/CheckboxList.php
Labels: enhancement

#5156 Add ability to merge extra (alpine/input/trigger/img/header) attributes instead of overwriting them
  packages/forms/src/Components/Concerns/HasExtraInputAttributes.php
  packages/forms/src/Components/DateTimePicker.php
  packages/support/src/Concerns/HasExtraAlpineAttributes.php
  packages/support/src/Concerns/HasExtraAttributes.php
  packages/tables/src/Columns/Concerns/HasExtraHeaderAttributes.php
  packages/tables/src/Columns/ImageColumn.php
Labels: enhancement

#5520 Fix link button icon size
  packages/support/resources/views/components/button.blade.php
Labels: bug

#5523 Fix empty table header actions
  packages/tables/resources/views/index.blade.php
Labels: bug

#5525 Fix showing table header children and spacing
  packages/tables/resources/views/components/header/index.blade.php
  packages/tables/resources/views/index.blade.php
Labels: bug, ui

#5526 Fix `support::button` loading indicator when using action params
  packages/support/resources/views/components/button.blade.php
Labels: bug

#5533 Add missing Swedish translations
  packages/admin/resources/lang/sv/layout.php
  packages/forms/resources/lang/sv/components.php
Labels: i18n

#5530 Add split keys support to tags input
  packages/forms/resources/views/components/tags-input.blade.php
  packages/forms/src/Components/TagsInput.php
Labels: enhancement

#5541 Missing tr translates
  packages/admin/resources/lang/tr/layout.php
  packages/admin/resources/lang/tr/resources/pages/edit-record.php
  packages/admin/resources/lang/tr/resources/pages/view-record.php
  packages/forms/resources/lang/tr/components.php
  packages/tables/resources/lang/tr/table.php
Labels: i18n

#5539 Account for unauthenticated users in action authorization
  packages/actions/src/Concerns/CanBeHidden.php
Labels: bug

#5554 Fix docs access $this and protected property
  packages/admin/docs/02-resources/06-deleting-records.md
Labels: documentation

#5555 Add isVisible getter
  packages/actions/src/Concerns/CanBeHidden.php
Labels: enhancement

#5556 AttachAction - use the specified related key names
  packages/tables/src/Actions/AttachAction.php
Labels: bug

#5557 Use isVisible where suitable
  packages/actions/resources/views/components/actions.blade.php
  packages/actions/resources/views/components/group.blade.php
  packages/actions/src/Concerns/CanOpenModal.php
  packages/app/resources/views/components/global-search/actions.blade.php
  packages/forms/resources/views/components/field-wrapper/hint.blade.php
  packages/forms/resources/views/components/tabs.blade.php
  packages/forms/resources/views/components/wizard.blade.php
  packages/forms/src/Components/Concerns/CanBeHidden.php
  packages/forms/src/Concerns/CanBeHidden.php
  packages/forms/src/Concerns/HasComponents.php
  packages/infolists/resources/views/components/tabs.blade.php
  packages/infolists/src/Components/Concerns/CanBeHidden.php
  packages/infolists/src/Concerns/CanBeHidden.php
  packages/infolists/src/Concerns/HasComponents.php
  packages/support/resources/views/components/input/affixes.blade.php
  packages/tables/resources/views/components/actions/index.blade.php
  packages/tables/resources/views/components/columns/layout.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Columns/Concerns/CanBeHidden.php
  packages/tables/src/Filters/Concerns/CanBeHidden.php
  packages/tables/src/Table.php
Labels: code quality

#5558 Improved TR translations
  packages/admin/resources/lang/tr/layout.php
  packages/admin/resources/lang/tr/resources/pages/create-record.php
  packages/notifications/resources/lang/tr/database.php
  packages/tables/resources/lang/tr/table.php
Labels: i18n

#5563 Revamp buttons
  packages/app/dist/theme.css
  packages/support/resources/views/components/button.blade.php
Labels: ui

#5460 Use record id instead of relationship local name when associating records
  packages/tables/src/Actions/AssociateAction.php
Labels: bug

#5569 Add missing Japanese translations
  packages/admin/resources/lang/ja/layout.php
  packages/forms/resources/lang/ja/components.php
  packages/notifications/resources/lang/ja/database.php
  packages/spatie-laravel-settings-plugin/resources/lang/ja/pages/settings-page.php
  packages/spatie-laravel-translatable-plugin/resources/lang/ja/actions.php
  packages/support/resources/lang/ja/actions/force-delete.php
  packages/support/resources/lang/ja/actions/group.php
  packages/support/resources/lang/ja/actions/replicate.php
  packages/support/resources/lang/ja/actions/restore.php
  packages/support/resources/lang/ja/actions/view.php
  packages/support/resources/lang/ja/components/button.php
  packages/support/resources/lang/ja/components/modal.php
Labels: i18n

#5447 feat(modal): add `closeByClickingAway`
  packages/admin/resources/views/components/page.blade.php
  packages/forms/resources/views/components/actions/modal/index.blade.php
  packages/support/resources/views/components/modal/index.blade.php
  packages/support/src/Actions/Concerns/CanOpenModal.php
  packages/tables/resources/views/index.blade.php
Labels: enhancement

#5574 Change escaping of $getState on TextInputColumn
  packages/tables/resources/views/columns/text-input-column.blade.php
Labels: bug

#5576 Update Dutch translations
  packages/app/resources/lang/nl/layout.php
  packages/app/resources/lang/nl/pages/auth/login.php
  packages/tables/resources/lang/nl/table.php
Labels: i18n

#5577 Add all packages to check translations command
  packages/support/src/Commands/CheckTranslationsCommand.php
Labels: bug

#5575 Revamp dropdown item
  packages/app/dist/theme.css
  packages/support/resources/views/components/dropdown/header.blade.php
  packages/support/resources/views/components/dropdown/list/item.blade.php
Labels: ui

#5586 Fix wrong if condition
  packages/actions/resources/views/components/modals.blade.php
Labels: bug
