Repository filamentphp/filament, pull requests merged in 2023-07, with the labels that each got.

#6810 Add slot to selection indicator
  packages/tables/resources/views/components/selection-indicator.blade.php
Labels: enhancement

#6903 Add component attributes tables pagination
  packages/tables/resources/views/components/pagination/index.blade.php
Labels: enhancement

#6904 Fix modal hr border dark mode
  packages/support/resources/views/components/modal/index.blade.php
Labels: bug

#6808 Add CSS hook class to user menu
  packages/admin/resources/views/components/layouts/app/topbar/user-menu.blade.php
Labels: enhancement

#6901 Add scrollContent to modal
  packages/support/resources/views/components/modal/index.blade.php
Labels: enhancement

#6809 Added support for before policy filter
  packages/admin/src/Resources/Resource.php
Labels: enhancement

#6815 Add `Closure` support to NavigationItem
  composer.lock
  packages/admin/docs/05-navigation.md
  packages/admin/src/Navigation/NavigationItem.php
Labels: enhancement

#6914 Global search result scroll bar visibility
  packages/admin/resources/views/components/global-search/results-container.blade.php
Labels: bug

#6935 Should display dynamic options for checkbox list
  packages/forms/resources/views/components/checkbox-list.blade.php
Labels: bug

#6937 introduced without Middleware in pages and Resource .
  packages/admin/src/Pages/Page.php
  packages/admin/src/Resources/Resource.php
Labels: enhancement

#6959 Allow string to be passed to hiddenOn & visibleOn
  packages/tables/src/Columns/Concerns/CanBeHidden.php
  packages/tables/src/Filters/Concerns/CanBeHidden.php
Labels: bug

#6973 Add hook class for modal slideover
  packages/support/resources/views/components/modal/index.blade.php
Labels: ui, chore

#6944 Fix updating chart
  packages/admin/resources/views/components/stats/card.blade.php
Labels: bug

#6971 Docs: Render the filters in a collapsible panel
  packages/admin/docs/02-resources/02-listing-records.md
Labels: documentation

#7011 add copyableState docs in text, color and badge columns
  packages/tables/docs/03-columns/02-text.md
  packages/tables/docs/03-columns/05-badge.md
  packages/tables/docs/03-columns/07-color.md
Labels: documentation

#7020 Fix: Chart styling on theme switch
  packages/panels/dist/index.js
  packages/panels/resources/js/index.js
  packages/panels/resources/views/components/layouts/base.blade.php
  packages/panels/resources/views/components/user-menu.blade.php
  packages/widgets/dist/components/chart.js
  packages/widgets/dist/components/stats-overview/card/chart.js
  packages/widgets/resources/js/components/chart.js
  packages/widgets/resources/js/components/stats-overview/card/chart.js
  packages/widgets/resources/views/chart-widget.blade.php
  packages/widgets/resources/views/stats-overview-widget/card.blade.php
  packages/widgets/src/ChartWidget.php
Labels: bug, ui

#7018 Fix: markdown styles on mobile and collapse/expand builder rotation
  packages/forms/dist/index.css
  packages/forms/resources/css/components/markdown-editor.css
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/markdown-editor.blade.php
  packages/panels/dist/theme.css
  packages/support/resources/views/components/section.blade.php
  packages/widgets/resources/views/chart-widget.blade.php
Labels: bug, ui

#7030 Fix wrong operator in docs example
  packages/forms/docs/06-advanced.md
Labels: documentation

#7035 Update spanish translations
  packages/forms/resources/lang/es/components.php
  packages/infolists/resources/lang/es/components.php
  packages/notifications/resources/lang/es/database.php
  packages/panels/resources/lang/es/layout.php
  packages/panels/resources/lang/es/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/es/pages/auth/login.php
  packages/panels/resources/lang/es/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/es/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/es/pages/auth/register.php
  packages/tables/resources/lang/es/table.php
Labels: i18n

#6730 Support CheckboxList descriptions
  docs-assets/app/app/Livewire/Forms/FieldsDemo.php
  docs-assets/app/composer.json
  docs-assets/app/composer.lock
  docs-assets/app/public/css/filament/filament/app.css
  docs-assets/app/public/css/filament/forms/forms.css
  docs-assets/app/public/css/filament/support/support.css
  docs-assets/app/public/js/filament/filament/app.js
  docs-assets/app/public/js/filament/filament/echo.js
  docs-assets/app/public/js/filament/forms/components/color-picker.js
  docs-assets/app/public/js/filament/forms/components/markdown-editor.js
  docs-assets/app/public/js/filament/forms/components/select.js
  docs-assets/app/public/js/filament/forms/components/tags-input.js
  docs-assets/app/public/js/filament/forms/components/textarea.js
  docs-assets/app/public/js/filament/notifications/notifications.js
  docs-assets/app/public/js/filament/support/support.js
  docs-assets/app/public/js/filament/tables/tables.js
  docs-assets/app/public/js/filament/widgets/components/chart.js
  docs-assets/app/public/js/filament/widgets/components/stats-overview/card/chart.js
  docs-assets/app/resources/css/app.css
  docs-assets/app/resources/views/components/layouts/app.blade.php
  docs-assets/screenshots/images/dark/forms/fields/checkbox-list/option-descriptions.jpg
  docs-assets/screenshots/images/light/forms/fields/checkbox-list/option-descriptions.jpg
  docs-assets/screenshots/schema.js
  packages/forms/docs/03-fields/06-checkbox-list.md
  packages/forms/resources/views/components/checkbox-list.blade.php
  packages/forms/src/Components/CheckboxList.php
Labels: enhancement, ui

#7070 Update pl translations
  packages/forms/resources/lang/pl/components.php
  packages/notifications/resources/lang/pl/database.php
  packages/panels/resources/lang/pl/layout.php
  packages/panels/resources/lang/pl/pages/auth/login.php
  packages/tables/resources/lang/pl/table.php
Labels: i18n

#7085 Fix searchable selects
  packages/forms/dist/components/select.js
  packages/forms/resources/js/components/select.js
Labels: bug

#7089 Translate new keys to Arabic
  packages/forms/resources/lang/ar/components.php
  packages/infolists/resources/lang/ar/components.php
  packages/notifications/resources/lang/ar/database.php
  packages/panels/resources/lang/ar/layout.php
  packages/panels/resources/lang/ar/pages/auth/edit-profile.php
  packages/panels/resources/lang/ar/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/ar/pages/auth/login.php
  packages/panels/resources/lang/ar/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/ar/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/ar/pages/auth/register.php
  packages/panels/resources/lang/ar/pages/tenancy/edit-tenant-profile.php
  packages/support/resources/lang/ar/components/modal.php
  packages/tables/resources/lang/ar/table.php
Labels: i18n

#7097 Fix EditProfile saving issue without password
  packages/panels/src/Pages/Auth/EditProfile.php
Labels: bug

#7068 fix: databaseNotificationsPollingInterval when it should be databaseN…
  packages/upgrade/bin/create-filament-v3-panel-provider.php
Labels: bug

#7140 [v2] Adds missing FA translation.
  packages/forms/resources/lang/fa/components.php
Labels: i18n

#7132 Add missing pt_BR translations
  packages/actions/resources/lang/pt_BR/associate.php
  packages/actions/resources/lang/pt_BR/attach.php
  packages/actions/resources/lang/pt_BR/create.php
  packages/actions/resources/lang/pt_BR/delete.php
  packages/actions/resources/lang/pt_BR/detach.php
  packages/actions/resources/lang/pt_BR/dissociate.php
  packages/actions/resources/lang/pt_BR/edit.php
  packages/actions/resources/lang/pt_BR/force-delete.php
  packages/actions/resources/lang/pt_BR/group.php
  packages/actions/resources/lang/pt_BR/restore.php
  packages/forms/resources/lang/pt_BR/components.php
  packages/infolists/resources/lang/pt_BR/components.php
  packages/notifications/resources/lang/pt_BR/database.php
  packages/panels/resources/lang/pt_BR/global-search.php
  packages/panels/resources/lang/pt_BR/layout.php
  packages/panels/resources/lang/pt_BR/pages/auth/edit-profile.php
  packages/panels/resources/lang/pt_BR/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/pt_BR/pages/auth/login.php
  packages/panels/resources/lang/pt_BR/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/pt_BR/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/pt_BR/pages/auth/register.php
  packages/panels/resources/lang/pt_BR/pages/tenancy/edit-tenant-profile.php
  packages/panels/resources/lang/pt_BR/resources/pages/create-record.php
  packages/panels/resources/lang/pt_BR/resources/pages/edit-record.php
  packages/support/resources/lang/pt_BR/components/modal.php
  packages/tables/resources/lang/pt_BR/table.php
Labels: i18n

#7130 Dynamic fields based on a select option - example
  packages/forms/docs/07-advanced.md
Labels: documentation

#7147 [3.x] docs: Update method name in relation manager example
  packages/panels/docs/03-resources/07-relation-managers.md
Labels: documentation

#7040 Add note to documentation regarding route order of pages
  packages/admin/docs/02-resources/10-custom-pages.md
Labels: documentation

#7100 Document text and badge column `enum()` deprecation
  packages/tables/docs/13-upgrade-guide.md
Labels: documentation

#7138 Fix issue to edit record with combined relation manager tabs
  packages/panels/resources/views/components/resources/relation-managers.blade.php
Labels: bug

#7164 [3.x] Adds missing FA translations.
  packages/forms/resources/lang/fa/components.php
  packages/notifications/resources/lang/fa/database.php
  packages/panels/resources/lang/fa/layout.php
  packages/panels/resources/lang/fa/pages/auth/login.php
  packages/tables/resources/lang/fa/table.php
Labels: i18n

#7162 Directory separator fix for Windows
  packages/upgrade/bin/filament-v3
Labels: bug

#7169 Fix label translation, add :label, remove spaces
  packages/actions/resources/lang/zh_CN/create.php
Labels: i18n

#7173 Fix passing stats overview widget description icon
  packages/widgets/resources/views/stats-overview-widget/card.blade.php
Labels: bug

#7176 Fix select option keys retrieving with getOptionLabelFromRecordUsing
  packages/forms/src/Components/Select.php
Labels: bug

#7185 Update 10-tenancy.md
  packages/panels/docs/10-tenancy.md
Labels: documentation

#7194 add new method `hasPlugin`
  packages/panels/src/Facades/Filament.php
  packages/panels/src/FilamentManager.php
  packages/panels/src/Panel/Concerns/HasPlugins.php
Labels: enhancement

#7189 Handle password reset
  packages/panels/src/Pages/Auth/PasswordReset/RequestPasswordReset.php
Labels: enhancement

#7193 Fix updating charts on dispatched event
  packages/widgets/resources/js/components/chart.js
Labels: bug

#7210 feature: add script to quickly setup demo/playground
  bin/setup-playground.sh
Labels: enhancement

#7216 heroicon links
  packages/infolists/docs/03-entries/03-icon.md
  packages/panels/docs/03-resources/01-getting-started.md
  packages/tables/docs/03-columns/03-icon.md
Labels: documentation

#7215 Check if editor exists before destroying it in file-upload
  packages/forms/resources/js/components/file-upload.js
Labels: bug

#7219 Fill translated values in ViewAction modal form
  packages/tables/src/Actions/ViewAction.php
Labels: bug

#7222 Fix phpdoc for table pagination options
  packages/tables/src/Table/Concerns/CanPaginateRecords.php
Labels: bug

#7234 Update 03-build-a-standalone-plugin.md
  packages/support/docs/06-plugins/03-build-a-standalone-plugin.md
Labels: documentation

#7225 Add conditionable trait to `Panel` class
  packages/forms/src/Components/Concerns/CanBeHidden.php
  packages/infolists/src/Components/Concerns/CanBeHidden.php
  packages/panels/src/Panel.php
  packages/support/src/Components/Component.php
  tests/src/Forms/HiddenComponentsTest.php
Labels: enhancement

#7240 Add badge to dropdown and navigation
  packages/panels/resources/views/components/topbar/index.blade.php
  packages/support/resources/views/components/dropdown/list/item.blade.php
Labels: bug, ui

#7242 Fixed typo in `alignFormActionsEnd` method
  packages/panels/src/Pages/BasePage.php
Labels: bug

#7237 Editing for consistency, flow, and terseness.
  packages/panels/docs/02-getting-started.md
Labels: documentation, enhancement

#7229 Add support for customizing password broker
  packages/panels/docs/08-users.md
  packages/panels/src/Facades/Filament.php
  packages/panels/src/FilamentManager.php
  packages/panels/src/Pages/Auth/PasswordReset/RequestPasswordReset.php
  packages/panels/src/Pages/Auth/PasswordReset/ResetPassword.php
  packages/panels/src/Panel/Concerns/HasAuth.php
Labels: enhancement

#7246 Support custom font weights
  packages/panels/dist/theme.css
  packages/panels/resources/views/components/layout/base.blade.php
  packages/panels/src/Facades/Filament.php
  packages/panels/src/FilamentManager.php
  packages/panels/src/FontProviders/BunnyFontProvider.php
  packages/panels/src/FontProviders/Contracts/FontProvider.php
  packages/panels/src/FontProviders/GoogleFontProvider.php
  packages/panels/src/FontProviders/LocalFontProvider.php
  packages/panels/src/Panel/Concerns/HasFont.php
  packages/panels/tailwind.config.preset.js
Labels: enhancement

#7257 Added missing preload() to SelectFilter form field
  packages/tables/src/Filters/SelectFilter.php
Labels: bug

#7267 Typo
  packages/actions/docs/02-overview.md
Labels: documentation

#7270 Since the ->disablePlaceHolder() method is deprecated and its suggest…
  packages/forms/docs/03-fields/03-select.md
  packages/tables/docs/03-columns/06-select.md
Labels: documentation

#7272 Update card.blade.php
  packages/widgets/resources/views/stats-overview-widget/card.blade.php
Labels: enhancement

#7273 widgets[feature]: separates chart-widget backgroundColor and borderColor
  packages/widgets/resources/js/components/chart.js
  packages/widgets/resources/views/chart-widget.blade.php
Labels: enhancement

#7274 Update 02-getting-started.md
  packages/panels/docs/02-getting-started.md
Labels: documentation

#7263 Fix issue with refresh after DatabaseNotificationsSent event
  packages/notifications/resources/views/components/database/echo.blade.php
Labels: bug

#7278 fix: forgot password label trans key
  packages/panels/src/Pages/Auth/Login.php
Labels: bug

#7281 add/update translations missing for French
  packages/actions/resources/lang/fr/modal.php
  packages/actions/resources/lang/fr/view.php
  packages/forms/resources/lang/fr/components.php
  packages/infolists/resources/lang/fr/components.php
  packages/panels/resources/lang/fr/layout.php
  packages/panels/resources/lang/fr/pages/auth/edit-profile.php
  packages/panels/resources/lang/fr/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/fr/pages/auth/login.php
  packages/panels/resources/lang/fr/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/fr/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/fr/pages/auth/register.php
  packages/panels/resources/lang/fr/pages/tenancy/edit-tenant-profile.php
  packages/spatie-laravel-settings-plugin/resources/lang/fr/pages/settings-page.php
  packages/spatie-laravel-translatable-plugin/resources/lang/fr/actions.php
  packages/support/resources/lang/fr/components/modal.php
  packages/support/resources/lang/fr/components/pagination.php
  packages/tables/resources/lang/fr/table.php
Labels: i18n

#7280 Text column wrap
  packages/tables/resources/views/columns/text-column.blade.php
Labels: bug, ui

#7285 Fix search input element
  packages/panels/resources/views/components/global-search/field.blade.php
  packages/tables/resources/views/components/search-field.blade.php
Labels: bug

#7282 Allow us to go a little deeper in relations for Spatie Media Library Table Column
  packages/spatie-laravel-media-library-plugin/src/Tables/Columns/SpatieMediaLibraryImageColumn.php
Labels: bug

#7287 Fix table content overflow
  packages/tables/resources/views/index.blade.php
Labels: bug, ui, pending review

#7289 Update Status Widget section of Getting Started
  packages/panels/docs/02-getting-started.md
Labels: documentation

#7297 Fix deselect records after completion
  packages/tables/resources/views/index.blade.php
Labels: bug

#7298 Add missing translation keys for Arabic
  packages/actions/resources/lang/ar/associate.php
  packages/forms/resources/lang/ar/components.php
  packages/panels/resources/lang/ar/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/ar/pages/auth/login.php
  packages/panels/resources/lang/ar/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/ar/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/ar/pages/auth/register.php
  packages/tables/resources/lang/ar/table.php
Labels: i18n

#7305 Filter tabs render hooks
  packages/panels/resources/views/resources/pages/list-records.blade.php
  packages/support/docs/06-render-hooks.md
Labels: enhancement

#7303 adds `gap-4` for to adjust global search's render hooks
  packages/panels/resources/views/components/global-search/index.blade.php
Labels: bug, ui

#7317 Increase HtmlSanitizer MaxInputLength
  packages/support/src/SupportServiceProvider.php
Labels: enhancement

#7321 Docs - input mask with RawJs
  packages/forms/docs/03-fields/02-text-input.md
Labels: bug
