Repository filamentphp/filament, pull requests merged in 2023-03, with the labels that each got.

#5814 Fix unique validation docs link
  packages/forms/docs/05-validation.md
Labels: bug, documentation

#5819 Fixed import
  packages/notifications/src/Notification.php
Labels: bug

#5813 how to access ownerRecord in RelationManagers
  packages/admin/docs/02-resources/07-relation-managers.md
Labels: documentation

#5818 Improve table grouping
  packages/tables/resources/views/components/groups.blade.php
  packages/tables/resources/views/components/summary/row.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Grouping/Group.php
Labels: enhancement, ui

#5825 fix: Nested repeater actions
  packages/forms/src/Components/Concerns/Cloneable.php
Labels: bug

#5832 Support custom dropdown offset
  packages/support/resources/views/components/dropdown/index.blade.php
Labels: enhancement

#5843 Fix composer.json formatting after install command
  packages/support/src/Commands/InstallCommand.php
Labels: bug

#5845 fix: Cloning form component containers
  packages/forms/src/Components/Builder.php
  packages/forms/src/Components/Repeater.php
Labels: bug

#5850 fix: Don't clone dynamic schemas
  packages/forms/src/Components/Concerns/Cloneable.php
  packages/forms/src/Concerns/Cloneable.php
Labels: bug

#5849 Handle JSON columns in form select component relationships (updated)
  packages/forms/src/Components/Select.php
Labels: bug

#5829 Add row layout to checkbox list
  packages/forms/resources/views/components/checkbox-list.blade.php
  packages/forms/src/Components/CheckboxList.php
  packages/forms/src/Components/Concerns/HasGridDirection.php
Labels: enhancement

#5824 Add loading feedback to repeater/builder item
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/repeater.blade.php
Labels: enhancement

#5863 Update datetimepicker to support Khmer language
  packages/forms/resources/js/components/date-time-picker.js
Labels: enhancement, i18n

#5866 docs: Add warning for Placeholder field
  packages/forms/docs/04-layout.md
Labels: documentation

#5867 Update 02-actions.md
  packages/admin/docs/03-pages/02-actions.md
Labels: documentation

#5868 Ensuring that notification actions from Notifications have full event information
  packages/notifications/src/Actions/Action.php
  packages/support/src/Actions/Concerns/CanEmitEvent.php
  tests/src/Notifications/NotificationTest.php
Labels: enhancement

#5871 Use translateLabel() when relationship()
  packages/forms/src/Components/CheckboxList.php
  packages/forms/src/Components/Repeater.php
  packages/forms/src/Components/Select.php
Labels: enhancement

#5875 Fix for breaking change to createOptionAction on Select field
  packages/forms/src/Components/Select.php
Labels: bug

#5893 #5891 disable fetch cache on file-upload
  packages/forms/resources/js/components/file-upload.js
Labels: bug

#5894 add hooks for pagination states
  packages/tables/resources/views/components/pagination/item.blade.php
Labels: enhancement

#5896 add createOptionFormLabelUsing
  packages/forms/src/Components/Select.php
Labels: enhancement

#5810 Make form actions sticky
  packages/admin/config/filament.php
  packages/admin/resources/views/components/form/actions.blade.php
Labels: ui

#5847 fix: tabs not updating in Builder #5639
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/repeater.blade.php
  packages/forms/resources/views/components/tabs.blade.php
  packages/forms/resources/views/components/tabs/tab.blade.php
Labels: bug

#5858 fix-v3/sidebar flicker on refresh
  packages/app/resources/views/components/layouts/app/sidebar/group.blade.php
  packages/app/resources/views/components/layouts/app/sidebar/index.blade.php
  packages/app/resources/views/components/layouts/app/sidebar/item.blade.php
Labels: bug

#5865 Pass item component to isCollapsed
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/repeater.blade.php
  packages/forms/src/Components/Concerns/CanBeCollapsed.php
Labels: enhancement

#5870 feat-v3/maxContentWidth
  packages/app/resources/views/components/layouts/app.blade.php
  packages/app/src/Context.php
  packages/app/src/Context/Concerns/HasMaxContentWidth.php
  packages/app/src/FilamentManager.php
  packages/app/src/Pages/BasePage.php
Labels: enhancement

#5888 Fixes alpine error with deferred loading and selection indicator
  packages/tables/resources/views/index.blade.php
Labels: bug

#5900 add Select::getLabel() return types
  packages/forms/src/Components/Select.php
Labels: bug

#5897 Add support for relationships to Infolists
  packages/infolists/src/Components/Concerns/CanGetStateFromRelationships.php
  packages/infolists/src/Components/Concerns/HasState.php
Labels: enhancement

#5909 fix: Persist tab
  packages/forms/src/Components/Tabs.php
Labels: bug

#5917 Fix bug when saving a reorderable field w/ custom table name
  packages/spatie-laravel-media-library-plugin/src/Forms/Components/SpatieMediaLibraryFileUpload.php
Labels: bug

#5918 Starts translate-y after in stick header :md breakpoint
  packages/admin/resources/views/components/form/actions.blade.php
Labels: bug

#5920 add method to add unauthenticated tenant routes to context
  packages/app/routes/web.php
  packages/app/src/Context/Concerns/HasRoutes.php
Labels: enhancement

#5930 Use attributesToArray() in getStateFromRecord()
  packages/infolists/src/Components/Concerns/HasState.php
  packages/tables/src/Columns/Concerns/HasState.php
Labels: bug

#5925 Qualify the field name for sorting.
  packages/tables/src/Grouping/Group.php
Labels: bug

#5932 add missing translation key for fa
  packages/tables/resources/lang/fa/table.php
Labels: i18n

#5940 Fix for getEditOptionAction() checking for the wrong schema
  packages/forms/src/Components/Select.php
Labels: bug

#5939 Add icon to section class and template
  packages/forms/resources/views/components/section.blade.php
  packages/forms/src/Components/Section.php
Labels: enhancement

#5944 Center items
  packages/tables/resources/views/index.blade.php
Labels: bug, ui

#5938 Fix icon column alignment
  packages/tables/resources/views/components/columns/column.blade.php
Labels: bug

#5952 Adjust German label translations
  packages/forms/resources/lang/de/components.php
Labels: enhancement, i18n

#5957 feature: allow form component actions to have arguments on mount
  packages/forms/src/Concerns/HasFormComponentActions.php
Labels: enhancement

#5961 Fix bug when saving a reorderable field w/ custom table name
  packages/spatie-laravel-media-library-plugin/src/Forms/Components/SpatieMediaLibraryFileUpload.php
Labels: bug

#5962 Copy Value Correction
  packages/tables/resources/views/columns/text-column.blade.php
Labels: bug

#5954 Feature/persist sort in session
  packages/tables/docs/03-columns/01-getting-started.md
  packages/tables/src/Concerns/CanSortRecords.php
  packages/tables/src/Concerns/InteractsWithTable.php
Labels: enhancement

#5965 make required-asterisk stick to label
  packages/forms/resources/views/components/field-wrapper/label.blade.php
Labels: ui, needs more info

#5968 Update finnish translation
  packages/tables/resources/lang/fi/table.php
Labels: i18n

#5977 fix/hide extra element in table when empty
  packages/tables/resources/views/index.blade.php
Labels: bug, ui

#5979 Visually distinguish disabled options
  packages/forms/resources/views/components/radio.blade.php
Labels: enhancement, ui

#6010 Call configure on ActionGroup after making it.
  packages/support/src/Actions/ActionGroup.php
Labels: bug

#5986 Refactor `Filament\locale_has_pluralization` to `Filament\Support\locale_has_pluralization`
  packages/admin/src/Resources/RelationManagers/RelationManager.php
  packages/admin/src/Resources/Resource.php
  packages/admin/src/helpers.php
  packages/support/src/Actions/Concerns/InteractsWithRecord.php
  packages/support/src/helpers.php
  packages/tables/src/Concerns/HasRecords.php
Labels: bug

#5991 Update 09-configuration.md
  packages/app/docs/09-configuration.md
Labels: documentation

#5992 Allow hasManyDeep relationships in TagsColumn
  composer.json
  composer.lock
  packages/tables/src/Columns/Concerns/HasState.php
Labels: enhancement

#5994 Notification - center notifications vertically
  packages/notifications/resources/views/notification.blade.php
  packages/notifications/resources/views/notifications.blade.php
Labels: enhancement

#6022 Fixes error display of nestedRecurrsiveValidationRules
  packages/forms/resources/views/components/field-wrapper/index.blade.php
Labels: bug

#5981 fix: s3 bucket where file missing
  packages/forms/src/Components/BaseFileUpload.php
  packages/forms/src/Components/Concerns/HasFileAttachments.php
  packages/spatie-laravel-media-library-plugin/src/Forms/Components/SpatieMediaLibraryFileUpload.php
  packages/tables/src/Columns/ImageColumn.php
Labels: bug

#6016 Update default position for descriptionIcon to be after
  packages/widgets/src/StatsOverviewWidget/Card.php
Labels: bug

#6028 Update docs: `07-testing.md`
  packages/forms/docs/07-testing.md
Labels: documentation

#6068 fix: Markdown editor list insertion
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/markdown-editor.js
Labels: bug

#6041 Add isReactive method
  packages/forms/src/Concerns/HasStateBindingModifiers.php
Labels: enhancement

#6051 Fixed the collapsedGroups value check adding support for the json representation of the null value
  packages/admin/resources/views/components/layouts/app/sidebar/index.blade.php
Labels: bug

#6057 Fix test examples to use getRouteKey() for custom route key names in documentation
  packages/admin/docs/10-testing.md
Labels: bug, documentation

#6026 fix: resolves error regarding canvas already being used when updating
  packages/admin/resources/views/components/stats/card.blade.php
Labels: bug

#6030 Describe filepond domain and cors headers
  packages/forms/docs/03-fields.md
Labels: documentation, enhancement

#6040 Allow testing fields via callbacks
  packages/forms/.stubs.php
  packages/forms/docs/07-testing.md
  packages/forms/src/Testing/TestsForms.php
  tests/src/Forms/FormsTest.php
Labels: enhancement

#6074 fix: BelongsToMany with Repeater
  packages/forms/src/Components/Repeater.php
Labels: bug

#6075 fix: Parse action names when testing
  packages/admin/src/Testing/TestsPageActions.php
  packages/tables/src/Testing/TestsActions.php
  packages/tables/src/Testing/TestsBulkActions.php
Labels: bug

#6077 fix: Duplicate queries with relationship layout component
  packages/forms/src/Components/Concerns/EntanglesStateWithSingularRelationship.php
Labels: bug

#6078 fix: Bulk actions duplicate queries
  packages/tables/src/Concerns/CanSelectRecords.php
Labels: bug

#6081 Add French translation for column search reset button
  packages/tables/resources/lang/fr/table.php
Labels: i18n
