Repository filamentphp/filament, pull requests merged in 2023-12, with the labels that each got.

#9974 Make action group dropdown offset customizable
  packages/actions/docs/05-grouping-actions.md
  packages/actions/resources/views/components/group.blade.php
  packages/actions/src/Concerns/HasDropdown.php
  packages/notifications/src/Actions/ActionGroup.php
Labels: enhancement

#9983 Documentaion: `layouts` → `layout`
  packages/admin/docs/08-appearance.md
Labels: documentation

#9984 Fix deprecated enum::tryFrom(null) in PHP 8.3
  packages/actions/resources/views/components/actions.blade.php
  packages/forms/resources/views/components/actions.blade.php
  packages/forms/resources/views/components/file-upload.blade.php
  packages/infolists/resources/views/components/actions.blade.php
  packages/infolists/resources/views/components/entry-wrapper/index.blade.php
  packages/support/resources/views/components/badge.blade.php
  packages/support/resources/views/components/button/index.blade.php
  packages/support/resources/views/components/icon-button.blade.php
  packages/support/resources/views/components/link.blade.php
  packages/support/resources/views/components/modal/index.blade.php
  packages/support/resources/views/components/tabs/item.blade.php
  packages/tables/resources/views/columns/layout/stack.blade.php
  packages/tables/resources/views/columns/text-input-column.blade.php
  packages/tables/resources/views/components/actions.blade.php
  packages/tables/resources/views/components/columns/column.blade.php
  packages/tables/resources/views/components/header-cell.blade.php
  packages/tables/resources/views/components/summary/index.blade.php
  packages/tables/resources/views/components/summary/row.blade.php
Labels: bug

#9985 Translate table filter query builder to Lithuanian
  packages/tables/resources/lang/lt/filters/query-builder.php
Labels: i18n

#9987 Update 16-key-value.md
  packages/forms/docs/03-fields/16-key-value.md
Labels: documentation

#10005 Update 08-grouping.md
  packages/tables/docs/08-grouping.md
Labels: documentation

#10012 Finnish translation update
  packages/actions/resources/lang/fi/import.php
  packages/forms/resources/lang/fi/components.php
  packages/forms/resources/lang/fi/validation.php
  packages/infolists/resources/lang/fi/components.php
  packages/panels/resources/lang/fi/pages/dashboard.php
  packages/tables/resources/lang/fi/filters/query-builder.php
  packages/tables/resources/lang/fi/table.php
Labels: i18n

#10010 Fix layout break in notification for long words
  packages/notifications/resources/views/components/body.blade.php
Labels: bug

#10021 Update 02-overview.md
  packages/actions/docs/02-overview.md
Labels: enhancement

#9995 Add option to remove default constraint operators'
  packages/tables/docs/04-filters/04-query-builder.md
  packages/tables/src/Filters/QueryBuilder/Constraints/Concerns/HasOperators.php
Labels: enhancement

#10024 fix: Import user
  packages/actions/docs/07-prebuilt-actions/08-import.md
  packages/actions/resources/lang/zh_CN/import.php
  packages/actions/src/Imports/Models/Import.php
  packages/forms/resources/lang/fi/components.php
Labels: bug

#10043 fix: remove failed at check
  packages/actions/src/Concerns/CanImportRecords.php
Labels: bug

#10046 fix: Simple repeater default
  packages/forms/src/Components/Repeater.php
Labels: bug

#10054 fix: Widget key
  packages/panels/resources/views/components/resources/relation-managers.blade.php
  packages/widgets/resources/views/components/widgets.blade.php
Labels: bug

#10058 Fix: Update 08-import.md
  packages/actions/docs/07-prebuilt-actions/08-import.md
Labels: documentation

#10056 Docs: Update variable name to match example
  packages/actions/docs/07-prebuilt-actions/08-import.md
Labels: documentation

#9948 Improve sticky form actions behavior
  packages/panels/resources/views/components/form/actions.blade.php
Labels: enhancement

#10060 fix: Disable file replace
  packages/forms/dist/components/file-upload.js
  packages/forms/resources/js/components/file-upload.js
Labels: bug

#10063 fix: Repeatable entry clone
  packages/forms/src/Concerns/Cloneable.php
  packages/forms/src/Concerns/HasState.php
  packages/infolists/src/Components/Concerns/Cloneable.php
  packages/infolists/src/Components/Concerns/HasState.php
  packages/infolists/src/Concerns/Cloneable.php
  packages/infolists/src/Concerns/HasState.php
Labels: bug

#10066 fix: Toggle column flicker
  packages/tables/resources/views/columns/toggle-column.blade.php
Labels: bug

#10071 Fix: FilePond TypeError when exiting modals
  packages/forms/dist/components/file-upload.js
  packages/forms/resources/js/components/file-upload.js
Labels: bug

#10074 Update 08-import.md
  packages/actions/docs/07-prebuilt-actions/08-import.md
Labels: documentation

#10075 fix: Repeater actions
  packages/forms/src/Components/Actions/ActionContainer.php
  packages/infolists/src/Components/Actions/ActionContainer.php
Labels: bug

#10077 fix: Tabs init
  packages/forms/resources/views/components/tabs.blade.php
  packages/infolists/resources/views/components/tabs.blade.php
  packages/infolists/src/Components/Tabs.php
Labels: bug

#10007 replace flip with autoPlacement in x-float
  packages/forms/resources/views/components/color-picker.blade.php
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/support/resources/views/components/dropdown/index.blade.php
Labels: bug

#10078 fix: Recursively attach relationship
  packages/tables/src/Actions/AssociateAction.php
  packages/tables/src/Actions/AttachAction.php
Labels: bug

#10079 Add down method to import migrations
  packages/actions/database/migrations/create_failed_import_rows_table.php
  packages/actions/database/migrations/create_imports_table.php
Labels: enhancement

#10082 fix broken link to themes page
  packages/support/docs/02-assets.md
Labels: documentation

#10088 fix: Form component action arguments
  packages/actions/src/Concerns/HasArguments.php
  packages/forms/src/Concerns/HasFormComponentActions.php
Labels: bug

#10089 Revert "replace flip with autoPlacement in x-float"
  packages/forms/resources/views/components/color-picker.blade.php
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/support/resources/views/components/dropdown/index.blade.php
Labels: bug

#10008 Make date time picker columns grow when label is too wide
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/panels/dist/theme.css
Labels: bug, ui

#9860 Support radio buttons and button group
  docs-assets/app/app/Livewire/Forms/FieldsDemo.php
  docs-assets/app/composer.lock
  docs-assets/app/public/css/filament/filament/app.css
  docs-assets/app/public/css/filament/forms/forms.css
  docs-assets/app/public/css/filament/support/support.css
  docs-assets/app/public/js/filament/forms/components/file-upload.js
  docs-assets/app/public/js/filament/forms/components/markdown-editor.js
  docs-assets/app/public/js/filament/support/support.js
  docs-assets/screenshots/images/dark/forms/fields/radio/boolean.jpg
  docs-assets/screenshots/images/dark/forms/fields/radio/button-group.jpg
  docs-assets/screenshots/images/dark/forms/fields/radio/buttons-inline-under-label.jpg
  docs-assets/screenshots/images/dark/forms/fields/radio/buttons.jpg
  docs-assets/screenshots/images/dark/forms/fields/radio/colors.jpg
  docs-assets/screenshots/images/dark/forms/fields/radio/disabled-option.jpg
  docs-assets/screenshots/images/dark/forms/fields/radio/icons.jpg
  docs-assets/screenshots/images/dark/forms/fields/radio/inline-under-label.jpg
  docs-assets/screenshots/images/dark/forms/fields/radio/inline.jpg
  docs-assets/screenshots/images/dark/forms/fields/radio/option-descriptions.jpg
  docs-assets/screenshots/images/dark/forms/fields/radio/simple.jpg
  docs-assets/screenshots/images/light/forms/fields/radio/boolean.jpg
  docs-assets/screenshots/images/light/forms/fields/radio/button-group.jpg
  docs-assets/screenshots/images/light/forms/fields/radio/buttons-inline-under-label.jpg
  docs-assets/screenshots/images/light/forms/fields/radio/buttons.jpg
  docs-assets/screenshots/images/light/forms/fields/radio/colors.jpg
  docs-assets/screenshots/images/light/forms/fields/radio/disabled-option.jpg
  docs-assets/screenshots/images/light/forms/fields/radio/icons.jpg
  docs-assets/screenshots/images/light/forms/fields/radio/inline-under-label.jpg
  docs-assets/screenshots/images/light/forms/fields/radio/inline.jpg
  docs-assets/screenshots/images/light/forms/fields/radio/option-descriptions.jpg
  docs-assets/screenshots/images/light/forms/fields/radio/simple.jpg
  docs-assets/screenshots/schema.js
  packages/actions/src/ActionGroup.php
  packages/actions/src/StaticAction.php
  packages/forms/docs/03-fields/07-radio.md
  packages/forms/resources/views/components/file-upload.blade.php
  packages/forms/resources/views/components/radio/button-group.blade.php
  packages/forms/resources/views/components/radio/buttons.blade.php
  packages/forms/resources/views/components/radio/index.blade.php
  packages/forms/resources/views/components/repeater/index.blade.php
  packages/forms/resources/views/components/repeater/simple.blade.php
  packages/forms/src/Components/CheckboxList.php
  packages/forms/src/Components/Concerns/HasColors.php
  packages/forms/src/Components/Concerns/HasDescriptions.php
  packages/forms/src/Components/Concerns/HasIcons.php
  packages/forms/src/Components/FileUpload.php
  packages/forms/src/Components/Radio.php
  packages/forms/src/Components/Repeater.php
  packages/panels/dist/theme.css
  packages/support/resources/views/components/badge.blade.php
  packages/support/resources/views/components/button/group.blade.php
  packages/support/resources/views/components/button/index.blade.php
Labels: enhancement

#10090 Improve breadcrumbs
  packages/support/resources/views/components/breadcrumbs.blade.php
  packages/support/src/Icons/IconManager.php
Labels: enhancement, ui

#10092 feature: Strip characters
  packages/forms/docs/03-fields/02-text-input.md
  packages/forms/src/Components/Concerns/HasState.php
  packages/forms/src/Concerns/HasState.php
  packages/forms/src/Concerns/InteractsWithForms.php
Labels: bug

#10103 Fixed 'Is Blank' operator for isFilledOperator
  packages/tables/src/Filters/QueryBuilder/Constraints/Operators/IsFilledOperator.php
Labels: bug

#10129 Return empty array if there is no more tabsdata on the refs object
  packages/forms/resources/views/components/tabs.blade.php
Labels: bug

#10134 Rename navigationParentItem variable for clarity
  packages/panels/src/Resources/Resource.php
Labels: chore

#10084 V3 docs - Position notifications with example for central aligning notifications to center top
  packages/notifications/docs/05-customizing-notifications.md
Labels: documentation

#10113 Enables autofocusing in wizard on page load
  packages/forms/resources/views/components/wizard.blade.php
Labels: bug

#10141 fix: Bulk action records out of date when cancelled
  packages/actions/resources/views/components/modals.blade.php
  packages/tables/src/Concerns/HasBulkActions.php
Labels: bug

#10142 fix: Color picker focus
  packages/forms/resources/views/components/color-picker.blade.php
Labels: bug

#10148 Update 08-import.md
  packages/actions/docs/07-prebuilt-actions/08-import.md
Labels: documentation

#10155 fix: Text entry limit
  packages/infolists/resources/views/components/text-entry.blade.php
Labels: bug

#10176 Add ability to specify ->delimiter(char) for CSV separator
  packages/actions/docs/07-prebuilt-actions/08-import.md
  packages/actions/src/Concerns/CanImportRecords.php
Labels: enhancement

#10177 Add doc note about filter indicator badge counts
  packages/tables/docs/04-filters/05-custom.md
Labels: documentation

#10173 Show or Hide the tenant menu
  packages/panels/docs/10-tenancy.md
  packages/panels/resources/views/components/sidebar/index.blade.php
  packages/panels/resources/views/components/topbar/index.blade.php
  packages/panels/src/Facades/Filament.php
  packages/panels/src/FilamentManager.php
  packages/panels/src/Panel/Concerns/HasTenancy.php
Labels: enhancement

#10180 fix: Keyval / tags input sort event
  packages/forms/resources/views/components/key-value.blade.php
  packages/forms/resources/views/components/tags-input.blade.php
Labels: bug

#10181 fix: Assert checkbox column render
  packages/tables/src/Testing/TestsColumns.php
Labels: bug

#10182 fix: Update translatable pivot
  packages/tables/src/Actions/EditAction.php
Labels: bug

#10184 fix: Key value $set()
  packages/forms/dist/components/key-value.js
  packages/forms/resources/js/components/key-value.js
Labels: bug

#10183 Add the ability to customize both nextAction and previousAction actio…
  packages/actions/src/Concerns/HasForm.php
  packages/actions/src/Concerns/HasWizard.php
Labels: enhancement

#10188 Fixed the typo in the description of using method "FillRecordUsing"
  packages/actions/docs/07-prebuilt-actions/08-import.md
Labels: documentation

#10190 fix: Move local file
  packages/forms/src/Components/BaseFileUpload.php
Labels: bug

#10191 fix: Configure reorderable on table
  packages/panels/src/Resources/Concerns/InteractsWithRelationshipTable.php
  packages/panels/src/Resources/Pages/ListRecords.php
  packages/tables/src/Table/Concerns/CanReorderRecords.php
Labels: bug

#10186 Extending the CanImportRecords trait by delimiter guessing
  packages/actions/src/Concerns/CanImportRecords.php
Labels: enhancement

#10215 Add CSS hook class to group cell
  packages/tables/resources/views/components/selection/group-cell.blade.php
Labels: enhancement

#10207 Clarify available RichEditor toolbar buttons
  packages/forms/docs/03-fields/10-rich-editor.md
Labels: documentation

#10198 Mention Sushi as an Eloquent bridge
  packages/support/docs/01-overview.md
Labels: documentation

#10218 fix: lazy color picker
  packages/forms/dist/components/color-picker.js
  packages/forms/resources/js/components/color-picker.js
  packages/forms/resources/views/components/color-picker.blade.php
  packages/panels/dist/theme.css
Labels: bug

#10220 Cross-link Authorization docs
  packages/panels/docs/08-users.md
Labels: documentation

#10229 Update README.md of Spatie Media Library package
  packages/spatie-laravel-media-library-plugin/README.md
Labels: documentation

#10237 fix: Resource label capitalisation
  packages/panels/docs/03-resources/01-getting-started.md
  packages/panels/src/Resources/Pages/Concerns/InteractsWithRecord.php
  packages/panels/src/Resources/Pages/CreateRecord.php
  packages/panels/src/Resources/Pages/ListRecords.php
  packages/panels/src/Resources/Resource.php
  packages/support/src/SupportServiceProvider.php
Labels: bug

#10241 Add missing Czech translations
  packages/actions/resources/lang/cs/force-delete.php
  packages/actions/resources/lang/cs/group.php
  packages/actions/resources/lang/cs/import.php
  packages/actions/resources/lang/cs/restore.php
  packages/forms/resources/lang/cs/components.php
  packages/forms/resources/lang/cs/validation.php
  packages/panels/resources/lang/cs/layout.php
  packages/panels/resources/lang/cs/pages/auth/edit-profile.php
  packages/panels/resources/lang/cs/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/cs/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/cs/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/cs/pages/auth/register.php
  packages/panels/resources/lang/cs/pages/dashboard.php
  packages/support/resources/lang/cs/components/modal.php
  packages/tables/resources/lang/cs/filters/query-builder.php
  packages/tables/resources/lang/cs/table.php
Labels: i18n

#10249 Fix syntax error caused from blank attribute
  packages/forms/resources/views/components/file-upload.blade.php
  packages/support/resources/views/components/section/index.blade.php
  packages/tables/resources/views/columns/checkbox-column.blade.php
  packages/tables/resources/views/columns/select-column.blade.php
  packages/tables/resources/views/columns/text-input-column.blade.php
Labels: bug

#10256 Update InteractsWithForms.php
  packages/forms/src/Concerns/InteractsWithForms.php
Labels: bug

#10259 fix: Create another
  packages/actions/src/Concerns/HasArguments.php
  packages/actions/src/Concerns/InteractsWithActions.php
  packages/forms/resources/lang/cs/components.php
  packages/panels/resources/lang/cs/pages/dashboard.php
  packages/tables/resources/lang/cs/filters/query-builder.php
  packages/tables/resources/lang/cs/table.php
  packages/tables/src/Table/Concerns/HasActions.php
Labels: bug

#10258 Add Czech translations for Spatie Settings
  packages/spatie-laravel-settings-plugin/resources/lang/cs/pages/settings-page.php
Labels: i18n

#10261 fix: Wizard next button loader
  packages/actions/src/StaticAction.php
  packages/forms/src/Components/Wizard.php
  packages/tables/src/Actions/BulkAction.php
Labels: bug

#10257 fix: Translatable losing contents of file upload
  packages/panels/src/Resources/Pages/CreateRecord.php
  packages/panels/src/Resources/Pages/EditRecord.php
  packages/spatie-laravel-translatable-plugin/src/Resources/Pages/Concerns/HasTranslatableFormWithExistingRecordData.php
  packages/spatie-laravel-translatable-plugin/src/Resources/Pages/CreateRecord/Concerns/Translatable.php
  packages/spatie-laravel-translatable-plugin/src/Resources/Pages/EditRecord/Concerns/Translatable.php
  packages/spatie-laravel-translatable-plugin/src/Resources/Pages/ListRecords/Concerns/Translatable.php
  packages/spatie-laravel-translatable-plugin/src/Resources/Pages/ViewRecord/Concerns/Translatable.php
Labels: bug

#10268 fix: Query builder related to operator
  packages/tables/src/Filters/QueryBuilder/Constraints/Constraint.php
  packages/tables/src/Filters/QueryBuilder/Constraints/RelationshipConstraint/Operators/IsRelatedToOperator.php
Labels: bug

#10276 Added Full Import Path for 'InteractsWithRecord' in Custom Page Documentation
  packages/panels/docs/03-resources/10-custom-pages.md
Labels: documentation

#10280 fix: Expand validation error
  packages/forms/resources/views/component-container.blade.php
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/repeater.blade.php
  packages/forms/resources/views/components/tabs/tab.blade.php
  packages/forms/resources/views/components/wizard.blade.php
  packages/forms/resources/views/components/wizard/step.blade.php
  packages/forms/src/Concerns/BelongsToParentComponent.php
  packages/forms/src/Concerns/InteractsWithForms.php
  packages/panels/dist/theme.css
  packages/panels/resources/css/index.css
  packages/support/resources/views/components/section/index.blade.php
Labels: bug

#9149 Fix text entry and column alignment
  packages/actions/resources/views/components/actions.blade.php
  packages/forms/resources/views/components/file-upload.blade.php
  packages/infolists/resources/views/components/entry-wrapper/index.blade.php
  packages/infolists/resources/views/components/text-entry.blade.php
  packages/notifications/resources/views/notification.blade.php
  packages/notifications/resources/views/notifications.blade.php
  packages/panels/dist/theme.css
  packages/support/src/Concerns/HasAlignment.php
  packages/tables/resources/views/columns/layout/stack.blade.php
  packages/tables/resources/views/columns/text-column.blade.php
  packages/tables/resources/views/columns/text-input-column.blade.php
  packages/tables/resources/views/components/actions.blade.php
  packages/tables/resources/views/components/columns/column.blade.php
  packages/tables/resources/views/components/header-cell.blade.php
  packages/tables/resources/views/components/summary/index.blade.php
  packages/tables/resources/views/components/summary/row.blade.php
Labels: bug

#10287 Fix DownloadImportFailureCsv duplicate file extension.
  packages/actions/src/Imports/Http/Controllers/DownloadImportFailureCsv.php
Labels: bug

#10293 Update 08-import.md
  packages/actions/docs/07-prebuilt-actions/08-import.md
Labels: documentation

#10300 Fix typo
  packages/panels/docs/08-users.md
Labels: documentation

#10299 Add and revise missing Japanese translations
  packages/actions/resources/lang/ja/associate.php
  packages/actions/resources/lang/ja/attach.php
  packages/actions/resources/lang/ja/create.php
  packages/actions/resources/lang/ja/delete.php
  packages/actions/resources/lang/ja/detach.php
  packages/actions/resources/lang/ja/dissociate.php
  packages/actions/resources/lang/ja/edit.php
  packages/actions/resources/lang/ja/force-delete.php
  packages/actions/resources/lang/ja/replicate.php
  packages/actions/resources/lang/ja/restore.php
  packages/actions/resources/lang/ja/view.php
  packages/forms/resources/lang/ja/components.php
  packages/forms/resources/lang/ja/validation.php
  packages/infolists/resources/lang/ja/components.php
  packages/panels/resources/lang/ja/pages/dashboard.php
  packages/panels/resources/lang/ja/resources/pages/create-record.php
  packages/panels/resources/lang/ja/resources/pages/edit-record.php
  packages/panels/resources/lang/ja/resources/pages/view-record.php
  packages/tables/resources/lang/ja/filters/query-builder.php
  packages/tables/resources/lang/ja/table.php
Labels: enhancement

#10321 fix: Text column and entry regressions
  packages/infolists/resources/views/components/text-entry.blade.php
  packages/tables/resources/views/columns/text-column.blade.php
Labels: bug

#10317 Make Select relationship $name argument optional
  packages/forms/src/Components/Select.php
Labels: bug

#10323 fix: Merge action arguments
  packages/infolists/src/Concerns/InteractsWithInfolists.php
  packages/tables/src/Concerns/HasActions.php
  packages/tables/src/Concerns/HasBulkActions.php
Labels: bug

#10324 fix: Simple state hydration twice
  packages/forms/src/Components/Repeater.php
Labels: bug

#10289 Panels: Add new Panel::route() helper for generating routes
  packages/panels/src/Pages/Page.php
  packages/panels/src/Panel/Concerns/HasAuth.php
  packages/panels/src/Panel/Concerns/HasRoutes.php
  packages/panels/src/Panel/Concerns/HasTenancy.php
  packages/panels/src/Resources/Resource.php
Labels: enhancement

#10325 Add relationManager explanation, and confirm import action since Filamentphp 3.1
  packages/actions/docs/07-prebuilt-actions/08-import.md
  packages/panels/docs/03-resources/07-relation-managers.md
Labels: documentation

#10326 Password reveal
  docs-assets/app/app/Livewire/Forms/FieldsDemo.php
  docs-assets/screenshots/images/dark/forms/fields/text-input/revealable-password.jpg
  docs-assets/screenshots/images/light/forms/fields/text-input/revealable-password.jpg
  docs-assets/screenshots/schema.js
  packages/forms/docs/03-fields/02-text-input.md
  packages/forms/resources/lang/en/components.php
  packages/forms/resources/views/components/text-input.blade.php
  packages/forms/src/Components/TextInput.php
  packages/forms/src/Components/TextInput/Actions/HidePasswordAction.php
  packages/forms/src/Components/TextInput/Actions/ShowPasswordAction.php
  packages/support/docs/03-icons.md
Labels: enhancement

#10290 Update index.blade.php for static positioning
  packages/tables/resources/views/index.blade.php
Labels: ui

#10330 add Media Library V11 to composer.json
  packages/spatie-laravel-media-library-plugin/composer.json
Labels: chore

#10338 Added missing Italian translations
  packages/actions/resources/lang/it/import.php
  packages/forms/resources/lang/it/components.php
  packages/forms/resources/lang/it/validation.php
  packages/panels/resources/lang/it/pages/dashboard.php
  packages/tables/resources/lang/it/filters/query-builder.php
  packages/tables/resources/lang/it/table.php
Labels: i18n

#10346 add php 8.3 to workflows
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/docs-screenshots.yml
  .github/workflows/fix-code-style.yml
  .github/workflows/phpstan.yml
  .github/workflows/tests.yml
Labels: chore

#10357 feat: add missing lv translations
  packages/actions/resources/lang/lv/associate.php
  packages/actions/resources/lang/lv/attach.php
  packages/actions/resources/lang/lv/create.php
  packages/actions/resources/lang/lv/delete.php
  packages/actions/resources/lang/lv/detach.php
  packages/actions/resources/lang/lv/dissociate.php
  packages/actions/resources/lang/lv/edit.php
  packages/actions/resources/lang/lv/force-delete.php
  packages/actions/resources/lang/lv/group.php
  packages/actions/resources/lang/lv/modal.php
  packages/actions/resources/lang/lv/replicate.php
  packages/actions/resources/lang/lv/restore.php
  packages/actions/resources/lang/lv/view.php
Labels: i18n

#10353 Added missing french translation
  packages/actions/resources/lang/fr/import.php
Labels: i18n

#10340 Improvement of translation management
  packages/spatie-laravel-translatable-plugin/src/Resources/Pages/Concerns/HasTranslatableFormWithExistingRecordData.php
  packages/spatie-laravel-translatable-plugin/src/Resources/Pages/CreateRecord/Concerns/Translatable.php
  packages/spatie-laravel-translatable-plugin/src/Resources/Pages/EditRecord/Concerns/Translatable.php
  packages/spatie-laravel-translatable-plugin/src/SpatieLaravelTranslatableContentDriver.php
Labels: bug

#10358 fix: Remove modal description
  packages/actions/src/Concerns/CanOpenModal.php
  packages/actions/src/Concerns/CanRequireConfirmation.php
  packages/actions/src/Concerns/InteractsWithActions.php
  packages/forms/src/Concerns/HasFormComponentActions.php
  packages/infolists/src/Concerns/InteractsWithInfolists.php
  packages/tables/src/Concerns/HasActions.php
  packages/tables/src/Concerns/HasBulkActions.php
Labels: bug

#10382 i18n: Translate missing Arabic translations w/ improvements
  packages/actions/resources/lang/ar/attach.php
  packages/actions/resources/lang/ar/create.php
  packages/actions/resources/lang/ar/delete.php
  packages/actions/resources/lang/ar/detach.php
  packages/actions/resources/lang/ar/dissociate.php
  packages/actions/resources/lang/ar/edit.php
  packages/actions/resources/lang/ar/force-delete.php
  packages/actions/resources/lang/ar/import.php
  packages/actions/resources/lang/ar/modal.php
  packages/actions/resources/lang/ar/replicate.php
  packages/actions/resources/lang/ar/restore.php
  packages/forms/resources/lang/ar/components.php
  packages/forms/resources/lang/ar/validation.php
  packages/infolists/resources/lang/ar/components.php
  packages/panels/resources/lang/ar/global-search.php
  packages/panels/resources/lang/ar/layout.php
  packages/panels/resources/lang/ar/pages/auth/edit-profile.php
  packages/panels/resources/lang/ar/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/ar/pages/auth/login.php
  packages/panels/resources/lang/ar/pages/auth/register.php
  packages/panels/resources/lang/ar/pages/dashboard.php
  packages/panels/resources/lang/ar/resources/pages/edit-record.php
  packages/spatie-laravel-settings-plugin/resources/lang/ar/pages/settings-page.php
  packages/tables/resources/lang/ar/filters/query-builder.php
  packages/tables/resources/lang/ar/table.php
Labels: i18n

#10371 Chore: update async-alpine dependency
  package-lock.json
  package.json
  packages/support/dist/async-alpine.js
Labels: bug in dependency, chore, high priority

#10366 docs: Add missing import
  packages/panels/docs/08-users.md
Labels: documentation

#10368 Fix to enable `data-` attributes to be parsed correctly
  packages/support/src/helpers.php
  tests/src/Support/helpersTest.php
Labels: bug

#10396 Add custom class for top bar expand and collapse buttons
  packages/panels/resources/views/components/topbar/index.blade.php
Labels: chore

#10415 Fix overflowing images
  packages/infolists/resources/views/components/image-entry.blade.php
Labels: bug

#10409 Add hooks above and below the topbar
  packages/panels/resources/views/components/layout/index.blade.php
  packages/support/docs/06-render-hooks.md
Labels: chore

#10378 feat: add ability to make default theme mode from panel provider
  packages/panels/docs/11-themes.md
  packages/panels/resources/views/components/layout/base.blade.php
  packages/panels/resources/views/components/theme-switcher/index.blade.php
  packages/panels/src/Enums/ThemeMode.php
  packages/panels/src/Facades/Filament.php
  packages/panels/src/FilamentManager.php
  packages/panels/src/Panel/Concerns/HasTheme.php
Labels: enhancement

#10388 Allow Enums in SelectAction
  packages/actions/src/Concerns/HasSelect.php
Labels: enhancement

#10420 fix summaries does not work properly when using database prefix
  packages/tables/src/Concerns/CanSummarizeRecords.php
Labels: bug

#10432 Added missing French translations
  packages/forms/resources/lang/fr/components.php
  packages/forms/resources/lang/fr/validation.php
  packages/infolists/resources/lang/fr/components.php
  packages/panels/resources/lang/fr/pages/dashboard.php
  packages/tables/resources/lang/fr/filters/query-builder.php
  packages/tables/resources/lang/fr/table.php
Labels: i18n

#10430 Fix darkest color shade index in docs
  packages/support/docs/04-colors.md
Labels: documentation

#10458 Chore: better styling for markdown editor
  package-lock.json
  packages/forms/dist/index.css
  packages/forms/resources/css/components/markdown-editor.css
  packages/panels/dist/theme.css
  packages/panels/src/Http/Controllers/Auth/EmailVerificationController.php
Labels: enhancement, chore

#10425 Honor visibility on custom navigation items
  packages/panels/src/Navigation/NavigationBuilder.php
  tests/src/Panels/Navigation/NavigationBuilderTest.php
Labels: bug

#10433 Add fix-overflowing-images support to Table ImageColumn
  packages/tables/docs/03-columns/03-icon.md
  packages/tables/docs/03-columns/04-image.md
  packages/tables/docs/03-columns/05-color.md
  packages/tables/resources/views/columns/color-column.blade.php
  packages/tables/resources/views/columns/icon-column.blade.php
  packages/tables/resources/views/columns/image-column.blade.php
  packages/tables/src/Columns/ColorColumn.php
  packages/tables/src/Columns/Concerns/CanWrap.php
  packages/tables/src/Columns/IconColumn.php
  packages/tables/src/Columns/ImageColumn.php
Labels: enhancement

#10451 Document guidance for guest-access in a panel
  packages/panels/docs/08-users.md
Labels: documentation

#10472 Add option to hide topbar
  packages/panels/docs/06-navigation.md
  packages/panels/resources/views/components/layout/index.blade.php
  packages/panels/src/FilamentManager.php
  packages/panels/src/Panel.php
  packages/panels/src/Panel/Concerns/HasTopbar.php
Labels: enhancement

#10474 fix: Invisible step
  packages/forms/resources/views/components/tabs/tab.blade.php
  packages/forms/resources/views/components/wizard/step.blade.php
Labels: bug

#10493 Update Vietnamese translations
  packages/actions/resources/lang/vi/import.php
  packages/forms/resources/lang/vi/components.php
  packages/forms/resources/lang/vi/validation.php
  packages/infolists/resources/lang/vi/components.php
  packages/panels/resources/lang/vi/pages/dashboard.php
  packages/tables/resources/lang/vi/filters/query-builder.php
  packages/tables/resources/lang/vi/table.php
Labels: i18n

#10499 Update 04-pages.md
  packages/panels/docs/04-pages.md
Labels: documentation

#10477 Use wire:navigate when redirecting
  packages/actions/src/Concerns/CanRedirect.php
  packages/panels/src/Pages/Auth/EditProfile.php
  packages/panels/src/Pages/Tenancy/EditTenantProfile.php
  packages/panels/src/Pages/Tenancy/RegisterTenant.php
  packages/panels/src/Resources/Pages/CreateRecord.php
  packages/panels/src/Resources/Pages/EditRecord.php
  packages/spatie-laravel-settings-plugin/src/Pages/SettingsPage.php
Labels: enhancement

#10503 fix: Font names with spaces
  packages/panels/resources/views/components/layout/base.blade.php
  packages/panels/src/FontProviders/BunnyFontProvider.php
  packages/panels/src/FontProviders/GoogleFontProvider.php
Labels: bug

#10507 fix: Query builder active count
  packages/tables/resources/views/components/filters/dialog.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Filters/BaseFilter.php
  packages/tables/src/Filters/QueryBuilder.php
  packages/tables/src/Filters/SelectFilter.php
  packages/tables/src/Table/Concerns/HasFilters.php
Labels: bug

#10509 feature: modifyFormFieldUsing()
  packages/tables/docs/04-filters/01-getting-started.md
  packages/tables/src/Filters/Concerns/HasFormSchema.php
Labels: enhancement

#10510 fix: Table nested action arguments
  packages/panels/resources/views/components/page/index.blade.php
  packages/tables/src/Concerns/HasActions.php
  packages/tables/src/Contracts/HasTable.php
  packages/tables/src/Table/Concerns/HasActions.php
Labels: bug

#10514 Fixed typos in European Translation
  packages/actions/resources/lang/pt_PT/create.php
  packages/actions/resources/lang/pt_PT/import.php
  packages/forms/resources/lang/pt_PT/components.php
  packages/forms/resources/lang/pt_PT/validation.php
  packages/panels/resources/lang/pt_PT/layout.php
  packages/panels/resources/lang/pt_PT/pages/auth/password-reset/request-password-reset.php
  packages/tables/resources/lang/pt_PT/table.php
Labels: i18n

#10525 Fixed typos in Arabic Translation
  packages/actions/resources/lang/ar/create.php
Labels: i18n

#10521 Prevent nested p tags
  packages/notifications/resources/views/components/body.blade.php
Labels: bug

#10530 Add HasDescription for enum and for Radio
  packages/actions/src/Concerns/HasSelect.php
  packages/forms/src/Components/Concerns/HasDescriptions.php
  packages/forms/src/Components/Concerns/HasOptions.php
  packages/support/docs/07-enums.md
  packages/support/src/Contracts/HasDescription.php
  packages/tables/src/Filters/Concerns/HasOptions.php
Labels: enhancement

#10537 fix: Prevent calling hydration hooks when loading state from relationship
  packages/forms/src/Components/Concerns/EntanglesStateWithSingularRelationship.php
  packages/forms/src/Components/Concerns/HasState.php
  packages/forms/src/Concerns/HasState.php
Labels: bug

#10546 feature: Search on blur
  packages/tables/docs/03-columns/01-getting-started.md
  packages/tables/resources/views/components/search-field.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Table/Concerns/CanSearchRecords.php
Labels: enhancement

#10548 Fix sorting indicator with wrapHeader
  packages/tables/resources/views/components/header-cell.blade.php
Labels: bug

#10531 feature: Apply table filters
  packages/panels/dist/theme.css
  packages/tables/docs/04-filters/01-getting-started.md
  packages/tables/resources/lang/en/table.php
  packages/tables/resources/views/components/filters/dialog.blade.php
  packages/tables/resources/views/components/filters/index.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Concerns/HasFilters.php
  packages/tables/src/Concerns/InteractsWithTable.php
  packages/tables/src/Filters/QueryBuilder.php
  packages/tables/src/Table/Concerns/HasFilters.php
Labels: enhancement

#10516 feature: Unsaved changes alert
  packages/panels/docs/09-configuration.md
  packages/panels/resources/views/components/page/index.blade.php
  packages/panels/resources/views/components/page/unsaved-data-changes-alert.blade.php
  packages/panels/resources/views/components/unsaved-action-changes-alert.blade.php
  packages/panels/resources/views/resources/pages/create-record.blade.php
  packages/panels/resources/views/resources/pages/edit-record.blade.php
  packages/panels/resources/views/resources/relation-manager.blade.php
  packages/panels/src/Facades/Filament.php
  packages/panels/src/FilamentManager.php
  packages/panels/src/Pages/Concerns/HasUnsavedDataChangesAlert.php
  packages/panels/src/Panel.php
  packages/panels/src/Panel/Concerns/HasUnsavedChangesAlerts.php
  packages/panels/src/Resources/Pages/CreateRecord.php
  packages/panels/src/Resources/Pages/EditRecord.php
Labels: enhancement

#10584 feature: Global search arrow key navigation
  packages/panels/dist/theme.css
  packages/panels/resources/views/components/global-search/field.blade.php
  packages/panels/resources/views/components/global-search/index.blade.php
  packages/panels/resources/views/components/global-search/result.blade.php
  packages/panels/resources/views/components/global-search/results-container.blade.php
Labels: enhancement

#10564 Updated the Hungarian translations and added the missing ones for 3.1
  packages/actions/resources/lang/hu/import.php
  packages/forms/resources/lang/hu/components.php
  packages/forms/resources/lang/hu/validation.php
  packages/infolists/resources/lang/hu/components.php
  packages/panels/resources/lang/hu/pages/dashboard.php
  packages/support/resources/lang/hu/components/pagination.php
  packages/tables/resources/lang/hu/filters/query-builder.php
  packages/tables/resources/lang/hu/table.php
Labels: i18n

#10567 Fix chartWidget property must not be accessed error
  packages/widgets/src/ChartWidget.php
Labels: bug

#10569 fix: Recursively attach relationship with pivot ID
  packages/tables/src/Actions/AssociateAction.php
  packages/tables/src/Actions/AttachAction.php
Labels: bug
