Repository filamentphp/filament, pull requests merged in 2023-11, with the labels that each got.

#9397 Updated Hungarian translations
  packages/actions/resources/lang/hu/associate.php
  packages/actions/resources/lang/hu/attach.php
  packages/actions/resources/lang/hu/create.php
  packages/actions/resources/lang/hu/dissociate.php
  packages/actions/resources/lang/hu/modal.php
  packages/forms/resources/lang/hu/components.php
  packages/notifications/resources/lang/hu/database.php
  packages/panels/resources/lang/hu/layout.php
  packages/panels/resources/lang/hu/pages/auth/edit-profile.php
  packages/panels/resources/lang/hu/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/hu/pages/auth/login.php
  packages/panels/resources/lang/hu/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/hu/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/hu/pages/auth/register.php
  packages/panels/resources/lang/hu/resources/pages/create-record.php
  packages/panels/resources/lang/hu/resources/pages/edit-record.php
  packages/panels/resources/lang/hu/widgets/account-widget.php
  packages/spatie-laravel-settings-plugin/resources/lang/hu/pages/settings-page.php
  packages/tables/resources/lang/hu/table.php
Labels: i18n

#9408 fix: Hidden relationship saving
  packages/forms/src/Components/Builder.php
  packages/forms/src/Components/Repeater.php
  packages/infolists/src/Components/RepeatableEntry.php
Labels: bug

#9410 Fix/remove hardcoded npm package
  packages/panels/docs/11-themes.md
  packages/panels/src/Commands/Aliases/MakeThemeCommand.php
  packages/panels/src/Commands/MakeThemeCommand.php
Labels: enhancement

#9433 Update ms translations
  packages/forms/resources/lang/ms/components.php
Labels: i18n

#9437 Deprecated message when passing null value to Str::lower() method
  packages/tables/src/Table/Concerns/CanSortRecords.php
Labels: bug

#9451 Update 08-users.md with missing semicolon
  packages/panels/docs/08-users.md
Labels: documentation

#9443 Improve Arabic translations
  packages/panels/resources/lang/ar/widgets/filament-info-widget.php
  packages/support/resources/lang/ar/components/pagination.php
Labels: i18n

#9446 Typo in docs 19-custom.md
  packages/forms/docs/03-fields/19-custom.md
Labels: documentation

#9449 Load `no_nb` locale from FilePond
  packages/forms/dist/components/file-upload.js
  packages/forms/resources/js/components/file-upload.js
Labels: i18n

#9455 Add stack('styles') to base.blade.php
  packages/panels/resources/views/components/layout/base.blade.php
Labels: enhancement

#9436 Allow preloading relationship options with multiple columns search
  packages/forms/src/Components/Select.php
Labels: bug

#9445 Set Inter font family to file upload
  packages/forms/dist/index.css
  packages/forms/resources/css/components/file-upload.css
Labels: bug

#9425 Adding assertions to verify that a notification was not sent
  packages/notifications/.stubs.php
  packages/notifications/docs/06-testing.md
  packages/notifications/src/Notification.php
  packages/notifications/src/Testing/TestsNotifications.php
  tests/src/Actions/ActionTest.php
Labels: enhancement

#9457 Now allowing defaultSort()'s argument to be a Closure.
  packages/tables/src/Table/Concerns/CanSortRecords.php
Labels: enhancement

#9469 Use wire:navigate for create and edit page redirects when SPA mode is enabled
  packages/panels/src/Resources/Pages/CreateRecord.php
  packages/panels/src/Resources/Pages/EditRecord.php
  packages/support/src/helpers.php
Labels: enhancement

#9467 Restore using HasOneThrough for filters
  packages/forms/src/Components/Select.php
Labels: bug

#9364 feature: Import action
  composer.json
  composer.lock
  packages/actions/composer.json
  packages/actions/database/migrations/create_failed_import_rows_table.php
  packages/actions/database/migrations/create_imports_table.php
  packages/actions/docs/07-prebuilt-actions/08-import.md
  packages/actions/resources/lang/en/import.php
  packages/actions/routes/web.php
  packages/actions/src/ActionsServiceProvider.php
  packages/actions/src/Commands/Aliases/MakeImporterCommand.php
  packages/actions/src/Commands/Concerns/CanGenerateImporterColumns.php
  packages/actions/src/Commands/MakeImporterCommand.php
  packages/actions/src/ImportAction.php
  packages/actions/src/Imports/Http/Controllers/DownloadImportFailureCsv.php
  packages/actions/src/Imports/ImportColumn.php
  packages/actions/src/Imports/Importer.php
  packages/actions/src/Imports/Jobs/ImportCsv.php
  packages/actions/src/Imports/Models/FailedImportRow.php
  packages/actions/src/Imports/Models/Import.php
  packages/actions/stubs/Importer.stub
  packages/forms/docs/05-validation.md
  packages/notifications/docs/05-customizing-notifications.md
  packages/panels/docs/03-resources/03-creating-records.md
  packages/support/docs/03-icons.md
  packages/support/src/ChunkIterator.php
  packages/tables/docs/05-actions.md
Labels: enhancement

#9481 making default widgets not lazy by default
  packages/panels/src/Widgets/AccountWidget.php
  packages/panels/src/Widgets/FilamentInfoWidget.php
Labels: enhancement

#9486 Update 03-icons.md
  packages/support/docs/03-icons.md
Labels: documentation

#9483 Update import "example" doc text
  packages/actions/docs/07-prebuilt-actions/08-import.md
Labels: documentation

#9511 Fixed typo in docs
  packages/support/docs/03-icons.md
Labels: documentation

#9519 Clarify Handling duplicates
  packages/panels/docs/03-resources/07-relation-managers.md
Labels: documentation

#9496 Correction of indentation during file creation.
  packages/support/src/Commands/Concerns/CanIndentStrings.php
Labels: bug

#9493 Improve the text size section by showing all options
  packages/tables/docs/03-columns/02-text.md
Labels: documentation

#9470 Fix: added missing old param on afterStateUpdated for upload field
  packages/forms/src/Components/BaseFileUpload.php
  packages/forms/src/Concerns/InteractsWithForms.php
Labels: bug

#9544 Add missing panel layout translation for Danish
  packages/panels/resources/lang/da/layout.php
Labels: i18n

#9540 Clean up testing examples in docs
  packages/panels/docs/13-testing.md
Labels: documentation

#9514 add luxon adapter to Chart.js
  package-lock.json
  package.json
  packages/widgets/docs/03-charts.md
  packages/widgets/resources/js/components/chart.js
Labels: bug

#9506 Amending `assertColumnExists` to accept `Closure` to test configuration
  packages/tables/.stubs.php
  packages/tables/docs/12-testing.md
  packages/tables/src/Testing/TestsColumns.php
  tests/src/Tables/ColumnTest.php
  tests/src/Tables/Fixtures/PostsTable.php
Labels: enhancement

#9552 Support custom content width in panel provider
  packages/panels/resources/views/components/layout/index.blade.php
Labels: enhancement

#9528 Customize form fields validation message
  packages/forms/docs/05-validation.md
  packages/forms/src/Components/Concerns/CanBeValidated.php
  packages/forms/src/Components/Contracts/HasValidationRules.php
  packages/forms/src/Concerns/CanBeValidated.php
Labels: enhancement

#9527 Add more missing icon aliases
  packages/actions/src/ActionGroup.php
  packages/actions/src/Concerns/CanRequireConfirmation.php
  packages/actions/src/CreateAction.php
  packages/actions/src/EditAction.php
  packages/actions/src/ViewAction.php
  packages/forms/src/Components/Builder.php
  packages/forms/src/Components/FileUpload.php
  packages/forms/src/Components/KeyValue.php
  packages/forms/src/Components/Repeater.php
  packages/forms/src/Components/Select.php
  packages/notifications/dist/index.js
  packages/notifications/resources/js/Notification.js
  packages/notifications/src/Concerns/HasIcon.php
  packages/notifications/src/Concerns/HasIconColor.php
  packages/notifications/src/Concerns/HasStatus.php
  packages/notifications/src/Notification.php
  packages/panels/resources/views/components/tenant-menu.blade.php
  packages/panels/resources/views/components/user-menu.blade.php
  packages/panels/src/Pages/Auth/PasswordReset/RequestPasswordReset.php
  packages/panels/src/Resources/Pages/EditRecord.php
  packages/panels/src/Resources/Pages/ManageRelatedRecords.php
  packages/panels/src/Resources/Pages/ViewRecord.php
  packages/support/docs/03-icons.md
  packages/tables/src/Actions/BulkActionGroup.php
  packages/tables/src/Actions/EditAction.php
  packages/tables/src/Actions/ViewAction.php
  packages/tables/src/Table/Concerns/CanGroupRecords.php
  packages/tables/src/Table/Concerns/CanReorderRecords.php
  packages/tables/src/Table/Concerns/CanToggleColumns.php
  packages/tables/src/Table/Concerns/HasFilters.php
Labels: chore

#9495 add HasLifecycleHooks for CanUpdateState
  packages/tables/docs/03-columns/06-select.md
  packages/tables/docs/03-columns/07-toggle.md
  packages/tables/docs/03-columns/08-text-input.md
  packages/tables/docs/03-columns/09-checkbox.md
  packages/tables/src/Columns/Concerns/CanUpdateState.php
Labels: enhancement

#9563 Allow infolist modal to infolist action
  packages/infolists/src/Components/Actions/Action.php
Labels: bug

#9479 feature: Query builder
  packages/forms/docs/02-getting-started.md
  packages/forms/docs/03-fields/13-builder.md
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/repeater.blade.php
  packages/forms/src/Components/Builder.php
  packages/forms/src/Components/Concerns/HasChildComponents.php
  packages/forms/src/Components/Select.php
  packages/forms/src/Components/TextInput.php
  packages/panels/docs/02-getting-started.md
  packages/support/docs/03-icons.md
  packages/support/docs/07-enums.md
  packages/tables/docs/02-getting-started.md
  packages/tables/docs/04-filters.md
  packages/tables/docs/04-filters/01-getting-started.md
  packages/tables/docs/04-filters/02-select.md
  packages/tables/docs/04-filters/03-ternary.md
  packages/tables/docs/04-filters/04-query-builder.md
  packages/tables/docs/04-filters/05-custom.md
  packages/tables/docs/04-filters/06-layout.md
  packages/tables/resources/lang/en/filters/query-builder.php
  packages/tables/src/Filters/Concerns/HasOptions.php
  packages/tables/src/Filters/QueryBuilder.php
  packages/tables/src/Filters/QueryBuilder/Concerns/HasConstraints.php
  packages/tables/src/Filters/QueryBuilder/Constraints/BooleanConstraint.php
  packages/tables/src/Filters/QueryBuilder/Constraints/BooleanConstraint/Operators/IsTrueOperator.php
  packages/tables/src/Filters/QueryBuilder/Constraints/Concerns/CanBeNullable.php
  packages/tables/src/Filters/QueryBuilder/Constraints/Concerns/HasLabel.php
  packages/tables/src/Filters/QueryBuilder/Constraints/Concerns/HasName.php
  packages/tables/src/Filters/QueryBuilder/Constraints/Concerns/HasOperators.php
  packages/tables/src/Filters/QueryBuilder/Constraints/Constraint.php
  packages/tables/src/Filters/QueryBuilder/Constraints/DateConstraint.php
  packages/tables/src/Filters/QueryBuilder/Constraints/DateConstraint/Operators/IsAfterOperator.php
  packages/tables/src/Filters/QueryBuilder/Constraints/DateConstraint/Operators/IsBeforeOperator.php
  packages/tables/src/Filters/QueryBuilder/Constraints/DateConstraint/Operators/IsDateOperator.php
  packages/tables/src/Filters/QueryBuilder/Constraints/DateConstraint/Operators/IsMonthOperator.php
  packages/tables/src/Filters/QueryBuilder/Constraints/DateConstraint/Operators/IsYearOperator.php
  packages/tables/src/Filters/QueryBuilder/Constraints/NumberConstraint.php
  packages/tables/src/Filters/QueryBuilder/Constraints/NumberConstraint/Operators/Concerns/CanAggregateRelationships.php
  packages/tables/src/Filters/QueryBuilder/Constraints/NumberConstraint/Operators/EqualsOperator.php
  packages/tables/src/Filters/QueryBuilder/Constraints/NumberConstraint/Operators/IsMaxOperator.php
  packages/tables/src/Filters/QueryBuilder/Constraints/NumberConstraint/Operators/IsMinOperator.php
  packages/tables/src/Filters/QueryBuilder/Constraints/Operators/Concerns/CanBeHidden.php
  packages/tables/src/Filters/QueryBuilder/Constraints/Operators/IsFilledOperator.php
  packages/tables/src/Filters/QueryBuilder/Constraints/Operators/Operator.php
  packages/tables/src/Filters/QueryBuilder/Constraints/RelationshipConstraint.php
  packages/tables/src/Filters/QueryBuilder/Constraints/RelationshipConstraint/Operators/EqualsOperator.php
  packages/tables/src/Filters/QueryBuilder/Constraints/RelationshipConstraint/Operators/HasMaxOperator.php
  packages/tables/src/Filters/QueryBuilder/Constraints/RelationshipConstraint/Operators/HasMinOperator.php
  packages/tables/src/Filters/QueryBuilder/Constraints/RelationshipConstraint/Operators/IsEmptyOperator.php
  packages/tables/src/Filters/QueryBuilder/Constraints/RelationshipConstraint/Operators/IsRelatedToOperator.php
  packages/tables/src/Filters/QueryBuilder/Constraints/SelectConstraint.php
  packages/tables/src/Filters/QueryBuilder/Constraints/SelectConstraint/Operators/IsOperator.php
  packages/tables/src/Filters/QueryBuilder/Constraints/TextConstraint.php
  packages/tables/src/Filters/QueryBuilder/Constraints/TextConstraint/Operators/ContainsOperator.php
  packages/tables/src/Filters/QueryBuilder/Constraints/TextConstraint/Operators/EndsWithOperator.php
  packages/tables/src/Filters/QueryBuilder/Constraints/TextConstraint/Operators/EqualsOperator.php
  packages/tables/src/Filters/QueryBuilder/Constraints/TextConstraint/Operators/StartsWithOperator.php
  packages/tables/src/Filters/QueryBuilder/Forms/Components/RuleBuilder.php
Labels: enhancement

#9584 Update 01-getting-started.md
  packages/tables/docs/03-columns/01-getting-started.md
Labels: documentation

#9592 Traslations Croatian language
  packages/actions/resources/lang/hr/associate.php
  packages/actions/resources/lang/hr/attach.php
  packages/actions/resources/lang/hr/create.php
  packages/actions/resources/lang/hr/delete.php
  packages/actions/resources/lang/hr/detach.php
  packages/actions/resources/lang/hr/dissociate.php
  packages/actions/resources/lang/hr/edit.php
  packages/actions/resources/lang/hr/force-delete.php
  packages/actions/resources/lang/hr/group.php
  packages/actions/resources/lang/hr/modal.php
  packages/actions/resources/lang/hr/replicate.php
  packages/actions/resources/lang/hr/restore.php
  packages/actions/resources/lang/hr/view.php
  packages/forms/resources/lang/hr/components.php
  packages/infolists/resources/lang/hr/components.php
  packages/notifications/resources/lang/hr/database.php
  packages/panels/resources/lang/hr/global-search.php
  packages/panels/resources/lang/hr/layout.php
  packages/panels/resources/lang/hr/pages/auth/edit-profile.php
  packages/panels/resources/lang/hr/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/hr/pages/auth/login.php
  packages/panels/resources/lang/hr/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/hr/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/hr/pages/auth/register.php
  packages/panels/resources/lang/hr/pages/dashboard.php
  packages/panels/resources/lang/hr/pages/tenancy/edit-tenant-profile.php
  packages/panels/resources/lang/hr/resources/pages/create-record.php
  packages/panels/resources/lang/hr/resources/pages/edit-record.php
  packages/panels/resources/lang/hr/resources/pages/list-records.php
  packages/panels/resources/lang/hr/resources/pages/view-record.php
  packages/panels/resources/lang/hr/widgets/account-widget.php
  packages/panels/resources/lang/hr/widgets/filament-info-widget.php
  packages/spatie-laravel-settings-plugin/resources/lang/hr/pages/settings-page.php
  packages/spatie-laravel-translatable-plugin/resources/lang/hr/actions.php
  packages/support/resources/lang/hr/components/button.php
  packages/support/resources/lang/hr/components/copyable.php
  packages/support/resources/lang/hr/components/modal.php
  packages/support/resources/lang/hr/components/pagination.php
  packages/tables/resources/lang/hr/table.php
Labels: i18n

#9587 Add Slovak (sk) translations
  packages/actions/resources/lang/sk/associate.php
  packages/actions/resources/lang/sk/attach.php
  packages/actions/resources/lang/sk/create.php
  packages/actions/resources/lang/sk/delete.php
  packages/actions/resources/lang/sk/detach.php
  packages/actions/resources/lang/sk/dissociate.php
  packages/actions/resources/lang/sk/edit.php
  packages/actions/resources/lang/sk/force-delete.php
  packages/actions/resources/lang/sk/group.php
  packages/actions/resources/lang/sk/modal.php
  packages/actions/resources/lang/sk/replicate.php
  packages/actions/resources/lang/sk/restore.php
  packages/actions/resources/lang/sk/view.php
  packages/forms/resources/lang/sk/components.php
  packages/infolists/resources/lang/sk/components.php
  packages/notifications/resources/lang/sk/database.php
  packages/panels/resources/lang/sk/global-search.php
  packages/panels/resources/lang/sk/layout.php
  packages/panels/resources/lang/sk/pages/auth/edit-profile.php
  packages/panels/resources/lang/sk/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/sk/pages/auth/login.php
  packages/panels/resources/lang/sk/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/sk/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/sk/pages/auth/register.php
  packages/panels/resources/lang/sk/pages/dashboard.php
  packages/panels/resources/lang/sk/pages/tenancy/edit-tenant-profile.php
  packages/panels/resources/lang/sk/resources/pages/create-record.php
  packages/panels/resources/lang/sk/resources/pages/edit-record.php
  packages/panels/resources/lang/sk/resources/pages/list-records.php
  packages/panels/resources/lang/sk/resources/pages/view-record.php
  packages/panels/resources/lang/sk/widgets/account-widget.php
  packages/panels/resources/lang/sk/widgets/filament-info-widget.php
  packages/spatie-laravel-settings-plugin/resources/lang/sk/pages/settings-page.php
  packages/spatie-laravel-translatable-plugin/resources/lang/sk/actions.php
  packages/support/resources/lang/sk/components/button.php
  packages/support/resources/lang/sk/components/copyable.php
  packages/support/resources/lang/sk/components/modal.php
  packages/support/resources/lang/sk/components/pagination.php
  packages/tables/resources/lang/sk/table.php
Labels: i18n

#8635 Add `distinct()` API to repeater
  packages/forms/docs/03-fields/12-repeater.md
  packages/forms/resources/lang/en/validation.php
  packages/forms/src/Components/BaseFileUpload.php
  packages/forms/src/Components/Checkbox.php
  packages/forms/src/Components/CheckboxList.php
  packages/forms/src/Components/Component.php
  packages/forms/src/Components/Concerns/CanBeRepeated.php
  packages/forms/src/Components/Concerns/CanBeValidated.php
  packages/forms/src/Components/Concerns/CanDisableOptions.php
  packages/forms/src/Components/Concerns/CanDisableOptionsWhenSelectedInSiblingRepeaterItems.php
  packages/forms/src/Components/Concerns/CanFixIndistinctState.php
  packages/forms/src/Components/Concerns/HasState.php
  packages/forms/src/Components/Contracts/CanDisableOptions.php
  packages/forms/src/Components/Radio.php
  packages/forms/src/Components/Select.php
  packages/forms/src/Components/Toggle.php
Labels: enhancement

#8028 Automatically detect boolean cast attribute in icon column and entry
  packages/infolists/docs/03-entries/03-icon.md
  packages/infolists/src/Components/IconEntry.php
  packages/tables/docs/03-columns/03-icon.md
  packages/tables/src/Columns/IconColumn.php
  tests/src/Tables/ColumnTest.php
Labels: enhancement

#9608 Update Ukrainian translations
  packages/actions/resources/lang/uk/group.php
  packages/forms/resources/lang/uk/components.php
  packages/panels/resources/lang/uk/layout.php
  packages/panels/resources/lang/uk/pages/auth/edit-profile.php
  packages/panels/resources/lang/uk/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/uk/pages/auth/login.php
  packages/panels/resources/lang/uk/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/uk/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/uk/pages/auth/register.php
  packages/panels/resources/lang/uk/pages/dashboard.php
  packages/panels/resources/lang/uk/pages/tenancy/edit-tenant-profile.php
  packages/support/resources/lang/uk/components/modal.php
  packages/tables/resources/lang/uk/table.php
Labels: i18n

#9600 Improve make command questions
  packages/panels/src/Commands/MakePageCommand.php
  packages/widgets/src/Commands/MakeWidgetCommand.php
Labels: enhancement

#9607 fix for ImageColumn to accept Base64 image `data:image`
  packages/tables/src/Columns/ImageColumn.php
Labels: enhancement

#9615 fix(lang): missing polish translations
  packages/panels/resources/lang/pl/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/pl/pages/auth/register.php
  packages/panels/resources/lang/pl/pages/dashboard.php
Labels: i18n

#9595 Enhance Dynamic Record Title Retrieval
  packages/tables/src/Table/Concerns/HasRecords.php
Labels: enhancement

#9404 feat: implement possibilty to apply or not tenant relationship on res…
  packages/panels/src/Resources/Pages/CreateRecord.php
  packages/panels/src/Resources/Pages/ListRecords.php
  packages/panels/src/Resources/Resource.php
Labels: enhancement

#9522 Support icon color for text entry and column
  docs-assets/app/app/Livewire/Infolists/EntriesDemo.php
  docs-assets/app/app/Livewire/TablesDemo.php
  docs-assets/app/composer.lock
  docs-assets/app/package-lock.json
  docs-assets/app/public/css/filament/filament/app.css
  docs-assets/app/public/css/filament/forms/forms.css
  docs-assets/app/public/css/filament/support/support.css
  docs-assets/app/public/js/filament/forms/components/date-time-picker.js
  docs-assets/app/public/js/filament/forms/components/file-upload.js
  docs-assets/app/public/js/filament/forms/components/select.js
  docs-assets/app/public/js/filament/forms/components/tags-input.js
  docs-assets/screenshots/images/dark/infolists/entries/text/icon-color.jpg
  docs-assets/screenshots/images/dark/tables/columns/text/icon-color.jpg
  docs-assets/screenshots/images/light/infolists/entries/text/icon-color.jpg
  docs-assets/screenshots/images/light/tables/columns/text/icon-color.jpg
  docs-assets/screenshots/schema.js
  packages/infolists/docs/03-entries/02-text.md
  packages/infolists/resources/views/components/text-entry.blade.php
  packages/infolists/src/Components/Concerns/HasIconColor.php
  packages/infolists/src/Components/TextEntry.php
  packages/tables/docs/03-columns/02-text.md
  packages/tables/resources/views/columns/text-column.blade.php
  packages/tables/src/Columns/Concerns/HasIconColor.php
  packages/tables/src/Columns/TextColumn.php
Labels: enhancement

#9621 feat: allow dynamically setting the card width on SimplePage
  packages/panels/resources/views/components/layout/simple.blade.php
  packages/panels/src/Pages/SimplePage.php
Labels: enhancement

#9624 Update Russian translations
  packages/forms/resources/lang/ru/components.php
  packages/panels/resources/lang/ru/pages/dashboard.php
  packages/support/resources/lang/ru/components/modal.php
  packages/tables/resources/lang/ru/table.php
Labels: i18n

#9632 Add missing closing parenthesis in scoping code example
  packages/panels/docs/03-resources/07-relation-managers.md
Labels: documentation

#9629 Added deleted_at to columns that should be hidden by default
  packages/tables/src/Commands/Concerns/CanGenerateTables.php
Labels: enhancement

#9645 Update pt_PT and pt_BR Translations
  packages/forms/resources/lang/pt_BR/components.php
  packages/forms/resources/lang/pt_PT/components.php
Labels: i18n

#9616 Fix required validation for concealed select
  packages/forms/resources/views/components/select.blade.php
Labels: bug

#9642 Update Indonesian Translations
  packages/forms/resources/lang/id/components.php
Labels: i18n

#9665 Add panel colors getter
  packages/panels/src/Panel/Concerns/HasColors.php
Labels: enhancement

#9653 ProhibitX validation rules
  packages/forms/docs/05-validation.md
  packages/forms/src/Components/Concerns/CanBeValidated.php
Labels: enhancement

#9633 Fix - Set record translations
  packages/spatie-laravel-translatable-plugin/src/SpatieLaravelTranslatableContentDriver.php
Labels: bug

#9556 Support Closures in the registration of Filament Panel Colors
  packages/panels/docs/11-themes.md
  packages/panels/src/Panel/Concerns/HasColors.php
  packages/support/docs/04-colors.md
  packages/support/src/Colors/ColorManager.php
  packages/support/src/Facades/FilamentColor.php
Labels: enhancement

#9362 Fix table groups only extra column
  packages/tables/resources/views/components/summary/index.blade.php
  packages/tables/resources/views/components/summary/row.blade.php
  packages/tables/resources/views/index.blade.php
Labels: bug

#9660 Allow spatie/invade 2.x
  packages/support/composer.json
  packages/support/src/Commands/Concerns/CanReadModelSchemas.php
Labels: chore

#9228 Add hide/show for limitList
  packages/infolists/docs/03-entries/02-text.md
  packages/infolists/resources/lang/en/components.php
  packages/infolists/resources/views/components/text-entry.blade.php
  packages/infolists/src/Components/TextEntry.php
  packages/tables/docs/03-columns/02-text.md
  packages/tables/resources/lang/en/table.php
  packages/tables/resources/views/columns/text-column.blade.php
  packages/tables/src/Columns/TextColumn.php
Labels: enhancement

#9676 [Docs] - Added closing backticks to infolist text entry docs
  packages/infolists/docs/03-entries/02-text.md
Labels: documentation

#9674 Changed edit to save to match the Blade template
  packages/forms/stubs/EditForm.stub
Labels: bug

#9689 Htmlable Form fields' affixes label
  packages/forms/src/Components/Concerns/HasAffixes.php
Labels: enhancement

#7743 Livewire component
  packages/forms/docs/07-advanced.md
  packages/forms/resources/views/components/livewire.blade.php
  packages/forms/src/Components/Livewire.php
  packages/infolists/docs/06-advanced.md
  packages/infolists/docs/07-adding-an-infolist-to-a-livewire-component.md
  packages/infolists/resources/views/components/livewire.blade.php
  packages/infolists/src/Components/Livewire.php
Labels: enhancement

#9716 Updated italian pagination strings
  packages/support/resources/lang/it/components/pagination.php
Labels: i18n

#7559 Feature/model namespacing
  packages/panels/docs/03-resources/01-getting-started.md
  packages/panels/src/Commands/Aliases/MakeResourceCommand.php
  packages/panels/src/Commands/MakeResourceCommand.php
  packages/panels/stubs/Resource.stub
Labels: enhancement, low priority

#9732 fixed backticks on query problem
  packages/support/src/helpers.php
Labels: bug

#9730 Hide group selection when needed
  packages/tables/docs/08-grouping.md
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Table/Concerns/CanGroupRecords.php
Labels: enhancement

#9728 Add 2xl icon column size
  packages/infolists/docs/03-entries/03-icon.md
  packages/infolists/resources/views/components/icon-entry.blade.php
  packages/infolists/src/Components/IconEntry/IconEntrySize.php
  packages/tables/docs/03-columns/03-icon.md
  packages/tables/resources/views/columns/icon-column.blade.php
  packages/tables/src/Columns/IconColumn/IconColumnSize.php
Labels: enhancement

#9557 Add Documentation about resource declaration within pages.
  packages/panels/docs/14-upgrade-guide.md
Labels: documentation

#8738 Support circular cropping
  packages/forms/dist/components/file-upload.js
  packages/forms/dist/index.css
  packages/forms/docs/03-fields/09-file-upload.md
  packages/forms/resources/css/components/file-upload.css
  packages/forms/resources/js/components/file-upload.js
  packages/forms/resources/views/components/file-upload.blade.php
  packages/forms/src/Components/FileUpload.php
Labels: enhancement, low priority

#9747 feature: Dashboard filters
  packages/panels/docs/05-dashboard.md
  packages/panels/resources/lang/en/pages/dashboard.php
  packages/panels/resources/views/pages/dashboard.blade.php
  packages/panels/src/Pages/Dashboard/Actions/FilterAction.php
  packages/panels/src/Pages/Dashboard/Concerns/HasFilters.php
  packages/panels/src/Pages/Dashboard/Concerns/HasFiltersAction.php
  packages/panels/src/Pages/Dashboard/Concerns/HasFiltersForm.php
  packages/panels/src/Widgets/Concerns/InteractsWithPageFilters.php
  packages/support/docs/03-icons.md
Labels: enhancement

#9161 Support section header actions
  docs-assets/app/app/Livewire/Forms/LayoutDemo.php
  docs-assets/app/app/Livewire/Infolists/LayoutDemo.php
  docs-assets/app/composer.lock
  docs-assets/app/package-lock.json
  docs-assets/app/public/css/filament/filament/app.css
  docs-assets/app/public/js/filament/notifications/notifications.js
  docs-assets/app/public/js/filament/widgets/components/chart.js
  docs-assets/screenshots/images/dark/forms/layout/section/actions.jpg
  docs-assets/screenshots/images/dark/infolists/layout/section/actions.jpg
  docs-assets/screenshots/images/light/forms/layout/section/actions.jpg
  docs-assets/screenshots/images/light/infolists/layout/section/actions.jpg
  docs-assets/screenshots/package-lock.json
  docs-assets/screenshots/schema.js
  packages/forms/docs/04-layout/06-section.md
  packages/forms/resources/views/components/section.blade.php
  packages/forms/src/Components/Actions/Action.php
  packages/forms/src/Components/Concerns/HasActions.php
  packages/forms/src/Components/Concerns/HasHeaderActions.php
  packages/forms/src/Components/Contracts/HasHeaderActions.php
  packages/forms/src/Components/Section.php
  packages/infolists/docs/04-layout/05-section.md
  packages/infolists/resources/views/components/section.blade.php
  packages/infolists/src/Components/Actions/Action.php
  packages/infolists/src/Components/Actions/Concerns/BelongsToInfolist.php
  packages/infolists/src/Components/Concerns/HasActions.php
  packages/infolists/src/Components/Concerns/HasHeaderActions.php
  packages/infolists/src/Components/Contracts/HasHeaderActions.php
  packages/infolists/src/Components/Section.php
  packages/support/resources/views/components/section/index.blade.php
Labels: enhancement

#9782 fix: pt_BR translations
  packages/actions/resources/lang/pt_BR/create.php
Labels: i18n

#9780 [3.x] Tab supports badge color
  packages/forms/docs/04-layout/04-tabs.md
  packages/forms/resources/views/components/tabs.blade.php
  packages/forms/src/Components/Tabs/Tab.php
  packages/infolists/docs/04-layout/04-tabs.md
  packages/infolists/resources/views/components/tabs.blade.php
  packages/infolists/src/Components/Tabs/Tab.php
Labels: enhancement

#9771 feat: add `FilamentAsset::registerCssVariables`
  packages/support/docs/02-assets.md
  packages/support/src/Assets/AssetManager.php
  packages/support/src/Facades/FilamentAsset.php
Labels: enhancement

#9778 Adjusting rules checking user input against a list of allowed values
  packages/forms/src/Components/Concerns/CanBeValidated.php
  tests/src/Forms/ValidationTest.php
Labels: bug

#9779 [3.x] FileUpload pdf preview
  package-lock.json
  package.json
  packages/forms/docs/03-fields/09-file-upload.md
  packages/forms/resources/js/components/file-upload.js
  packages/forms/resources/views/components/file-upload.blade.php
  packages/forms/src/Components/FileUpload.php
Labels: enhancement

#7754 Add file detection options
  packages/forms/dist/components/file-upload.js
  packages/forms/docs/03-fields/09-file-upload.md
  packages/forms/resources/js/components/file-upload.js
  packages/forms/src/Components/BaseFileUpload.php
  packages/forms/src/Components/FileUpload.php
Labels: enhancement, low priority

#8435 Update return type of getRelationshipToSum method
  packages/tables/docs/03-columns/11-relationships.md
  packages/tables/src/Columns/Concerns/CanAggregateRelatedModels.php
Labels: enhancement, low priority

#9795 Fix minor typo in docs
  packages/forms/docs/03-fields/09-file-upload.md
Labels: documentation

#9804 Update 05-viewing-records.md
  packages/panels/docs/03-resources/05-viewing-records.md
Labels: documentation

#9796 keep EasyMDE render once
  packages/forms/dist/components/markdown-editor.js
  packages/forms/resources/js/components/markdown-editor.js
Labels: bug

#9792 Update CreateRecord/.../Translatable.php
  packages/spatie-laravel-translatable-plugin/src/Resources/Pages/CreateRecord/Concerns/Translatable.php
Labels: bug

#9790 Add fetchFileExistence method to ImageEntry and ImageColumn
  packages/infolists/docs/03-entries/04-image.md
  packages/infolists/src/Components/ImageEntry.php
  packages/tables/docs/03-columns/04-image.md
  packages/tables/src/Columns/ImageColumn.php
Labels: enhancement

#9802 Fix nested Repeater Eager Loading
  packages/forms/src/Components/Repeater.php
Labels: bug

#9788 Add shade aliases
  packages/forms/resources/js/components/markdown-editor.js
  packages/forms/resources/views/components/field-wrapper/hint.blade.php
  packages/forms/resources/views/components/toggle.blade.php
  packages/forms/src/Components/Repeater.php
  packages/infolists/resources/views/components/entry-wrapper/hint.blade.php
  packages/infolists/resources/views/components/icon-entry.blade.php
  packages/infolists/resources/views/components/text-entry.blade.php
  packages/notifications/resources/views/components/icon.blade.php
  packages/notifications/resources/views/notification.blade.php
  packages/panels/dist/theme.css
  packages/support/resources/views/components/badge.blade.php
  packages/support/resources/views/components/dropdown/header.blade.php
  packages/support/resources/views/components/dropdown/list/item.blade.php
  packages/support/resources/views/components/icon-button.blade.php
  packages/support/resources/views/components/input/wrapper.blade.php
  packages/support/resources/views/components/link.blade.php
  packages/support/resources/views/components/modal/index.blade.php
  packages/support/resources/views/components/section/index.blade.php
  packages/tables/resources/views/columns/icon-column.blade.php
  packages/tables/resources/views/columns/summaries/icon-count.blade.php
  packages/tables/resources/views/columns/text-column.blade.php
  packages/tables/resources/views/columns/toggle-column.blade.php
  packages/widgets/resources/views/chart-widget.blade.php
  packages/widgets/resources/views/stats-overview-widget/stat.blade.php
Labels: chore

#9827 Update Hungarian translation
  packages/tables/resources/lang/hu/table.php
Labels: i18n

#9842 feat: add albanian language
  lang/vendor/filament-actions/sq/associate.php
  lang/vendor/filament-actions/sq/attach.php
  lang/vendor/filament-actions/sq/create.php
  lang/vendor/filament-actions/sq/delete.php
  lang/vendor/filament-actions/sq/detach.php
  lang/vendor/filament-actions/sq/dissociate.php
  lang/vendor/filament-actions/sq/edit.php
  lang/vendor/filament-actions/sq/force-delete.php
  lang/vendor/filament-actions/sq/group.php
  lang/vendor/filament-actions/sq/modal.php
  lang/vendor/filament-actions/sq/replicate.php
  lang/vendor/filament-actions/sq/restore.php
  lang/vendor/filament-actions/sq/view.php
  lang/vendor/filament-forms/sq/components.php
  lang/vendor/filament-notifications/sq/database.php
  lang/vendor/filament-panels/sq/global-search.php
  lang/vendor/filament-panels/sq/layout.php
  lang/vendor/filament-panels/sq/pages/auth/edit-profile.php
  lang/vendor/filament-panels/sq/pages/auth/email-verification/email-verification-prompt.php
  lang/vendor/filament-panels/sq/pages/auth/login.php
  lang/vendor/filament-panels/sq/pages/auth/password-reset/request-password-reset.php
  lang/vendor/filament-panels/sq/pages/auth/password-reset/reset-password.php
  lang/vendor/filament-panels/sq/pages/auth/register.php
  lang/vendor/filament-panels/sq/pages/dashboard.php
  lang/vendor/filament-panels/sq/pages/tenancy/edit-tenant-profile.php
  lang/vendor/filament-panels/sq/resources/pages/create-record.php
  lang/vendor/filament-panels/sq/resources/pages/edit-record.php
  lang/vendor/filament-panels/sq/resources/pages/list-records.php
  lang/vendor/filament-panels/sq/resources/pages/view-record.php
  lang/vendor/filament-panels/sq/widgets/account-widget.php
  lang/vendor/filament-panels/sq/widgets/filament-info-widget.php
  lang/vendor/filament-tables/sq/table.php
  lang/vendor/filament/sq/components/button.php
  lang/vendor/filament/sq/components/copyable.php
  lang/vendor/filament/sq/components/modal.php
  lang/vendor/filament/sq/components/pagination.php
Labels: i18n

#9813 Add Support for Cursor Pagination
  packages/support/docs/09-blade-components/02-pagination.md
  packages/support/resources/views/components/pagination/index.blade.php
  packages/tables/docs/10-advanced.md
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Concerns/CanPaginateRecords.php
  packages/tables/src/Concerns/HasRecords.php
  packages/tables/src/Contracts/HasTable.php
  packages/tables/src/Table/Concerns/HasRecords.php
Labels: enhancement

#9859 Improve Sub-Navigation Styling
  packages/panels/resources/views/components/page/index.blade.php
Labels: enhancement

#9864 feat: add missing lv translations
  packages/forms/resources/lang/lv/components.php
  packages/panels/resources/lang/lv/layout.php
  packages/panels/resources/lang/lv/pages/auth/edit-profile.php
  packages/panels/resources/lang/lv/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/lv/pages/auth/login.php
  packages/panels/resources/lang/lv/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/lv/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/lv/pages/auth/register.php
  packages/panels/resources/lang/lv/pages/tenancy/edit-tenant-profile.php
  packages/tables/resources/lang/lv/table.php
Labels: i18n

#9865 fix: fix syntax errors
  packages/forms/resources/lang/lv/components.php
  packages/panels/resources/lang/lv/pages/auth/login.php
Labels: bug

#9836 fix #8788 - reset activerelationmanager when selected is hidden
  packages/panels/docs/03-resources/04-editing-records.md
  packages/panels/docs/03-resources/05-viewing-records.md
  packages/panels/resources/views/resources/pages/edit-record.blade.php
  packages/panels/resources/views/resources/pages/manage-related-records.blade.php
  packages/panels/resources/views/resources/pages/view-record.blade.php
  packages/panels/src/Resources/Pages/Concerns/HasRelationManagers.php
Labels: bug

#7392 Support persisting collapsible section state
  packages/forms/docs/04-layout/06-section.md
  packages/forms/resources/views/components/section.blade.php
  packages/forms/src/Components/Concerns/CanBeCollapsed.php
  packages/infolists/docs/04-layout/05-section.md
  packages/infolists/resources/views/components/section.blade.php
  packages/infolists/src/Components/Concerns/CanBeCollapsed.php
  packages/panels/src/Resources/Pages/Concerns/HasRelationManagers.php
  packages/support/docs/09-blade-components/02-section.md
  packages/support/resources/views/components/section/index.blade.php
  packages/tables/resources/views/index.blade.php
Labels: enhancement, low priority

#7910 Introduce Modal Width Enum
  packages/actions/docs/04-modals.md
  packages/actions/docs/05-grouping-actions.md
  packages/actions/src/Concerns/CanOpenModal.php
  packages/actions/src/Concerns/CanRequireConfirmation.php
  packages/actions/src/Concerns/HasDropdown.php
  packages/forms/resources/views/component-container.blade.php
  packages/forms/src/Components/Builder.php
  packages/forms/src/Components/Concerns/HasMaxWidth.php
  packages/infolists/docs/03-entries/03-icon.md
  packages/infolists/resources/views/component-container.blade.php
  packages/infolists/resources/views/components/icon-entry.blade.php
  packages/infolists/src/Components/Concerns/HasMaxWidth.php
  packages/infolists/src/Components/IconEntry/IconEntrySize.php
  packages/panels/docs/04-pages.md
  packages/panels/docs/09-configuration.md
  packages/panels/resources/views/components/layout/index.blade.php
  packages/panels/resources/views/components/layout/simple.blade.php
  packages/panels/src/Facades/Filament.php
  packages/panels/src/FilamentManager.php
  packages/panels/src/Pages/BasePage.php
  packages/panels/src/Pages/SimplePage.php
  packages/panels/src/Panel/Concerns/HasMaxContentWidth.php
  packages/support/resources/views/components/dropdown/index.blade.php
  packages/support/resources/views/components/modal/index.blade.php
  packages/support/src/Enums/MaxWidth.php
  packages/tables/docs/03-columns/03-icon.md
  packages/tables/docs/04-filters.md
  packages/tables/resources/views/columns/icon-column.blade.php
  packages/tables/src/Actions/AssociateAction.php
  packages/tables/src/Actions/AttachAction.php
  packages/tables/src/Columns/IconColumn/IconColumnSize.php
  packages/tables/src/Table/Concerns/CanToggleColumns.php
  packages/tables/src/Table/Concerns/HasFilters.php
Labels: enhancement, low priority

#9871 Sub navigation no collapse
  packages/panels/resources/views/components/page/index.blade.php
  packages/panels/resources/views/components/sidebar/group.blade.php
  packages/panels/resources/views/components/sidebar/item.blade.php
Labels: bug

#9875 Fix Octane
  packages/panels/src/Facades/Filament.php
  packages/panels/src/Listeners/Auth/SendEmailVerificationNotification.php
  packages/panels/src/Pages/Auth/Register.php
  packages/panels/src/PanelProvider.php
  tests/src/Panels/Auth/RegisterTest.php
Labels: bug

#9869 [Docs - Field] Order of "disabled()" & "relationship()"
  packages/forms/docs/03-fields/03-select.md
  packages/forms/docs/03-fields/06-checkbox-list.md
  packages/forms/docs/03-fields/12-repeater.md
Labels: documentation

#9882 Add hex color validation rule
  packages/forms/docs/05-validation.md
  packages/forms/src/Components/Concerns/CanBeValidated.php
Labels: enhancement

#9852 Fix sidebar header ring overflow-x
  packages/panels/resources/views/components/sidebar/index.blade.php
Labels: bug, ui

#9898 Add Spanish (es) missing translations
  packages/forms/resources/lang/es/components.php
  packages/panels/resources/lang/es/pages/auth/password-reset/request-password-reset.php
  packages/tables/resources/lang/es/table.php
Labels: i18n

#9873 Support sub-navigation position end
  packages/panels/docs/03-resources/01-getting-started.md
  packages/panels/resources/views/components/page/index.blade.php
  packages/panels/resources/views/components/sidebar/sub-navigation.blade.php
  packages/panels/src/Pages/Concerns/HasSubNavigation.php
  packages/panels/src/Pages/SubNavigationPosition.php
  packages/panels/src/Resources/Pages/EditRecord.php
  packages/panels/src/Resources/Pages/ManageRelatedRecords.php
  packages/panels/src/Resources/Pages/ViewRecord.php
  packages/panels/src/Resources/Resource.php
Labels: enhancement

#9919 Update Translatable.php
  packages/spatie-laravel-translatable-plugin/src/Resources/Pages/CreateRecord/Concerns/Translatable.php
Labels: bug

#9926 `layouts.sidebar` → `layout.sidebar`
  packages/admin/docs/08-appearance.md
Labels: documentation

#9910 fixing translate error in radio component
  packages/forms/resources/lang/en/components.php
  packages/forms/resources/lang/pt_BR/components.php
  packages/forms/src/Components/Radio.php
Labels: bug

#9914 Fixing radio component translate
  packages/forms/resources/lang/en/components.php
  packages/forms/resources/lang/pt_BR/components.php
  packages/forms/src/Components/Radio.php
Labels: bug

#9893 Add extra attributes to form container
  packages/forms/resources/views/component-container.blade.php
  packages/forms/src/ComponentContainer.php
Labels: enhancement

#9928 Add extra attributes to infolist container
  packages/forms/resources/lang/en/components.php
  packages/forms/resources/lang/pt_BR/components.php
  packages/infolists/resources/views/component-container.blade.php
  packages/infolists/src/ComponentContainer.php
  packages/spatie-laravel-translatable-plugin/src/Resources/Pages/CreateRecord/Concerns/Translatable.php
Labels: enhancement

#9934 Add Spanish (es) missing translations - radio bool
  packages/forms/resources/lang/es/components.php
Labels: i18n

#9913 Update max content width options
  packages/panels/docs/04-pages.md
  packages/panels/docs/09-configuration.md
  packages/panels/resources/views/components/layout/index.blade.php
  packages/support/src/Enums/MaxWidth.php
Labels: enhancement

#9892 Fix inline fields
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/checkbox-list.blade.php
  packages/forms/resources/views/components/checkbox.blade.php
  packages/forms/resources/views/components/color-picker.blade.php
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/resources/views/components/field-wrapper/index.blade.php
  packages/forms/resources/views/components/file-upload.blade.php
  packages/forms/resources/views/components/key-value.blade.php
  packages/forms/resources/views/components/placeholder.blade.php
  packages/forms/resources/views/components/radio.blade.php
  packages/forms/resources/views/components/repeater.blade.php
  packages/forms/resources/views/components/rich-editor.blade.php
  packages/forms/resources/views/components/select.blade.php
  packages/forms/resources/views/components/simple-repeater.blade.php
  packages/forms/resources/views/components/tags-input.blade.php
  packages/forms/resources/views/components/text-input.blade.php
  packages/forms/resources/views/components/textarea.blade.php
  packages/forms/resources/views/components/toggle.blade.php
  packages/forms/src/Components/Radio.php
Labels: bug, ui

#9931 Add maxItems per block for Builder blocks
  packages/forms/docs/03-fields/13-builder.md
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/src/Components/Builder.php
  packages/forms/src/Components/Builder/Block.php
Labels: enhancement

#9936 9933 apply column grow to html column
  packages/tables/resources/views/index.blade.php
Labels: bug

#9889 Globally disable default tenancy scope in a panel
  packages/panels/docs/10-tenancy.md
  packages/panels/src/Panel/Concerns/HasTenancy.php
  packages/panels/src/Resources/Resource.php
Labels: enhancement

#8916 Enhance drag-and-drop sorting UX
  package.json
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/key-value.blade.php
  packages/forms/resources/views/components/repeater.blade.php
  packages/forms/resources/views/components/simple-repeater.blade.php
  packages/forms/src/Components/Builder.php
  packages/forms/src/Components/KeyValue.php
  packages/forms/src/Components/Repeater.php
  packages/support/dist/index.css
  packages/support/dist/index.js
  packages/support/resources/css/sortable.css
  packages/support/resources/js/index.js
  packages/support/resources/js/sortable.js
  packages/support/src/Concerns/HasReorderAnimationDuration.php
  packages/tables/resources/views/components/table.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Table/Concerns/CanReorderRecords.php
Labels: enhancement, ui

#9953 Add missing 'cs' tenancy profile page translation
  packages/panels/resources/lang/cs/pages/tenancy/edit-tenant-profile.php
Labels: i18n

#9956 Fix docs typo
  packages/infolists/docs/06-advanced.md
Labels: documentation

#9962 Fix docs typo in 02-getting-started.md
  packages/forms/docs/02-getting-started.md
Labels: documentation

#9963 Add: Translations for importing actions.
  packages/actions/resources/lang/zh_CN/import.php
Labels: i18n

#9967 Add Spanish (es) translations for v3.1.0
  packages/actions/resources/lang/es/import.php
  packages/forms/resources/lang/es/validation.php
  packages/infolists/resources/lang/es/components.php
  packages/panels/resources/lang/es/pages/dashboard.php
  packages/tables/resources/lang/es/filters/query-builder.php
  packages/tables/resources/lang/es/table.php
Labels: i18n

#9968 Fix addGlobalScope auth check closure in Update 10-tenancy.md
  packages/panels/docs/10-tenancy.md
Labels: documentation

#9976 Add missing malay (ms) translations
  packages/actions/resources/lang/ms/import.php
  packages/forms/resources/lang/ms/components.php
  packages/forms/resources/lang/ms/validation.php
  packages/panels/resources/lang/ms/pages/dashboard.php
  packages/tables/resources/lang/ms/filters/query-builder.php
  packages/tables/resources/lang/ms/table.php
Labels: i18n

#9980 Forms: Add support for re-ordering TagsInput tags
  packages/forms/dist/components/tags-input.js
  packages/forms/docs/03-fields/14-tags-input.md
  packages/forms/resources/js/components/tags-input.js
  packages/forms/resources/views/components/tags-input.blade.php
  packages/forms/src/Components/TagsInput.php
Labels: enhancement, javascript, php
