Repository filamentphp/filament, pull requests merged in 2023-05, with the labels that each got.

#5411 Add color support to notifications
  packages/app/dist/theme.css
  packages/notifications/dist/index.js
  packages/notifications/docs/02-sending-notifications.md
  packages/notifications/resources/js/Notification.js
  packages/notifications/resources/views/components/database/modal/index.blade.php
  packages/notifications/resources/views/notification.blade.php
  packages/notifications/src/Concerns/HasColor.php
  packages/notifications/src/Notification.php
Labels: enhancement

#6383 Fix mountedFormComponentActionsData state path name
  packages/forms/src/Concerns/HasFormComponentActions.php
Labels: bug

#6387 Add German auth translation
  packages/app/resources/lang/de/pages/auth/email-verification/email-verification-prompt.php
  packages/app/resources/lang/de/pages/auth/login.php
  packages/app/resources/lang/de/pages/auth/password-reset/request-password-reset.php
  packages/app/resources/lang/de/pages/auth/password-reset/reset-password.php
  packages/app/resources/lang/de/pages/auth/register.php
Labels: i18n

#6393 Update Welsh form translations to v2.12.10 standard
  packages/forms/resources/lang/cy/components.php
Labels: i18n

#6398 Add Welsh cy to tables translations
  packages/tables/resources/lang/cy/table.php
Labels: i18n

#6395 Add Welsh cy to date picker component
  packages/forms/resources/js/components/date-time-picker.js
Labels: i18n

#6386 Add focus styling to repeater buttons
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/repeater.blade.php
Labels: ui

#6392 Set validation attribute on fields
  packages/app/src/Pages/Auth/PasswordReset/ResetPassword.php
  packages/app/src/Pages/Auth/Register.php
Labels: enhancement

#6408 Lighten secondary icon-button for dark mode
  packages/support/resources/views/components/icon-button.blade.php
Labels: ui

#6410 Lighten cell description in dark mode
  packages/tables/resources/views/columns/text-column.blade.php
Labels: ui

#6409 Fix DateTimePicker evaluations
  packages/forms/src/Components/DateTimePicker.php
Labels: bug

#6413 Only reset action record when it doesn't exist
  composer.lock
  packages/actions/src/Action.php
  packages/actions/src/Concerns/InteractsWithActions.php
  packages/actions/src/CreateAction.php
Labels: bug

#6381 Respect disableForm(false) for ViewAction
  packages/admin/src/Resources/Pages/ListRecords.php
Labels: bug

#6388 Get form state before rate limiter so the form is validated
  packages/app/src/Pages/Auth/EmailVerification/EmailVerificationPrompt.php
  packages/app/src/Pages/Auth/PasswordReset/RequestPasswordReset.php
  packages/app/src/Pages/Auth/PasswordReset/ResetPassword.php
  packages/app/src/Pages/Auth/Register.php
Labels: bug

#6404 Support loading multiple relation counts
  packages/tables/src/Columns/Concerns/CanAggregateRelatedModels.php
  packages/tables/src/Columns/Concerns/InteractsWithTableQuery.php
Labels: enhancement

#6407 Do not send unnecessary headers when pretending to be a file
  packages/admin/src/Http/Controllers/AssetController.php
Labels: enhancement

#6420 Support force enabling Livewire click handler
  packages/actions/src/Concerns/HasAction.php
Labels: enhancement

#6423 Fix Latvian translations
  packages/tables/resources/lang/lv/table.php
Labels: i18n

#6425 Clean up tenant menu
  packages/app/resources/views/components/tenant-menu.blade.php
  packages/support/resources/views/components/dropdown/list/separator.blade.php
Labels: ui, code quality

#6429 Use action name best practice
  docs-assets/app/app/Http/Livewire/Actions.php
  packages/app/src/Pages/Auth/EmailVerification/EmailVerificationPrompt.php
  packages/app/src/Pages/Auth/Login.php
  packages/app/src/Pages/Auth/PasswordReset/RequestPasswordReset.php
  packages/app/src/Pages/Auth/PasswordReset/ResetPassword.php
  packages/app/src/Pages/Auth/Register.php
  packages/app/src/Pages/Tenancy/RegisterTenant.php
  tests/src/App/Auth/EmailVerification/EmailVerificationPromptTest.php
Labels: chore

#6434 Fix DateTimePicker focus outline
  packages/forms/resources/views/components/date-time-picker.blade.php
Labels: bug, ui

#6435 Allows single column condition in Searchable
  packages/tables/src/Columns/Concerns/CanBeSearchable.php
Labels: enhancement

#6437 Fix sidebar doesn't hide on large screen with topnavigation
  packages/app/dist/theme.css
  packages/app/resources/views/components/layouts/app/sidebar/index.blade.php
Labels: bug, ui

#6436 Add hover/focus to non-active tabs
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/echo.js.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.js
  packages/forms/resources/views/components/tabs.blade.php
Labels: enhancement, ui

#6447 Add render hooks before and after table
  packages/admin/docs/08-appearance.md
  packages/admin/resources/views/resources/pages/list-records.blade.php
Labels: enhancement

#6448 Load 600 font weight
  packages/app/src/FontProviders/BunnyFontProvider.php
  packages/app/src/FontProviders/GoogleFontProvider.php
Labels: enhancement

#6451 Don't require tenant to get billing url
  packages/app/resources/views/components/tenant-menu.blade.php
  packages/app/src/Facades/Filament.php
  packages/app/src/FilamentManager.php
  packages/spark-billing-provider/src/Http/Middleware/VerifySparkBillableIsSubscribed.php
Labels: enhancement

#6457 Filepond not loading correctly on collapsible form components.
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/repeater.blade.php
Labels: bug

#6475 Update background and text colors
  docs-assets/app/resources/views/layouts/app.blade.php
  packages/app/resources/views/components/layouts/base.blade.php
  packages/app/resources/views/components/layouts/card.blade.php
Labels: enhancement, ui

#6472 Improve section component
  packages/forms/resources/views/components/section.blade.php
  packages/forms/src/Components/Section.php
  packages/infolists/resources/views/components/section.blade.php
  packages/infolists/src/Components/Section.php
  packages/notifications/resources/views/components/icon.blade.php
  packages/notifications/resources/views/notification.blade.php
  packages/notifications/src/Notification.php
  packages/support/resources/views/components/icon-button.blade.php
  packages/support/resources/views/components/section.blade.php
  packages/support/src/Concerns/HasDescription.php
  packages/support/src/Concerns/HasHeading.php
  packages/support/src/Concerns/HasIcon.php
Labels: enhancement, ui

#6467 Add some classes for theming
  packages/tables/resources/views/columns/text-column.blade.php
  packages/tables/resources/views/components/empty-state/index.blade.php
  packages/tables/resources/views/components/search-input.blade.php
  packages/tables/resources/views/index.blade.php
Labels: enhancement

#6476 Normalize rings
  packages/app/resources/views/components/form/actions.blade.php
  packages/app/resources/views/components/global-search/results-container.blade.php
  packages/app/resources/views/components/layouts/card.blade.php
  packages/app/resources/views/pages/tenancy/register-tenant.blade.php
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/card.blade.php
  packages/forms/resources/views/components/repeater.blade.php
  packages/forms/resources/views/components/tabs.blade.php
  packages/infolists/resources/views/components/card.blade.php
  packages/infolists/resources/views/components/repeatable-entry.blade.php
  packages/infolists/resources/views/components/tabs.blade.php
  packages/notifications/resources/views/notification.blade.php
  packages/support/resources/views/components/card/index.blade.php
  packages/support/resources/views/components/dropdown/index.blade.php
  packages/tables/resources/views/components/container.blade.php
  packages/widgets/resources/views/stats-overview-widget/card.blade.php
Labels: enhancement, ui

#6480 Fix empty element in table header toolbar
  packages/tables/resources/views/index.blade.php
Labels: bug, ui

#6481 feature: Delete related record when condition not satisfied
  packages/forms/src/Components/Concerns/EntanglesStateWithSingularRelationship.php
Labels: enhancement

#6486 Fix home URL
  packages/app/resources/views/components/layouts/app/sidebar/index.blade.php
  packages/app/resources/views/components/layouts/app/topbar/index.blade.php
  packages/app/src/Context.php
  packages/app/src/Context/Concerns/HasRoutes.php
  packages/app/src/Facades/Filament.php
  packages/app/src/FilamentManager.php
Labels: bug

#6485 Add providers to Vite refresh paths
  docs-assets/app/vite.config.js
  packages/support/stubs/scaffolding/vite.config.js
Labels: enhancement

#6478 Update Italian create modal translations
  packages/support/resources/lang/it/actions/create.php
Labels: i18n

#6482 Support context layout configuration
  packages/app/docs/03-resources/08-global-search.md
  packages/app/docs/06-navigation.md
  packages/app/resources/views/components/layouts/app.blade.php
  packages/app/resources/views/components/layouts/app/sidebar/index.blade.php
  packages/app/resources/views/components/layouts/app/topbar/index.blade.php
  packages/app/src/Context.php
  packages/app/src/Context/Concerns/HasBreadcrumbs.php
  packages/app/src/Context/Concerns/HasGlobalSearch.php
  packages/app/src/Context/Concerns/HasNavigation.php
  packages/app/src/Facades/Filament.php
  packages/app/src/FilamentManager.php
  tests/src/App/GlobalSearch/GlobalSearchTest.php
Labels: enhancement

#6477 Fix overlapping pagination button rings
  packages/tables/resources/views/components/pagination/index.blade.php
Labels: bug, ui

#6498 Disable removeItemButton if no select placeholder
  package-lock.json
  packages/admin/dist/app.css.map
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/echo.js
  packages/admin/dist/echo.js.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.js
  packages/forms/resources/js/components/select.js
  packages/forms/resources/views/components/select.blade.php
Labels: enhancement

#6500 Tab icon position and color
  packages/forms/docs/04-layout.md
  packages/forms/resources/views/components/tabs.blade.php
  packages/forms/src/Components/Tabs/Tab.php
Labels: enhancement

#6502 Added Mongolian (mn) locale
  packages/admin/resources/lang/mn/global-search.php
  packages/admin/resources/lang/mn/layout.php
  packages/admin/resources/lang/mn/login.php
  packages/admin/resources/lang/mn/pages/dashboard.php
  packages/admin/resources/lang/mn/resources/pages/create-record.php
  packages/admin/resources/lang/mn/resources/pages/edit-record.php
  packages/admin/resources/lang/mn/resources/pages/list-records.php
  packages/admin/resources/lang/mn/resources/pages/view-record.php
  packages/admin/resources/lang/mn/widgets/account-widget.php
  packages/admin/resources/lang/mn/widgets/filament-info-widget.php
  packages/forms/resources/lang/mn/components.php
  packages/support/resources/lang/mn/actions/associate.php
  packages/support/resources/lang/mn/actions/attach.php
  packages/support/resources/lang/mn/actions/create.php
  packages/support/resources/lang/mn/actions/delete.php
  packages/support/resources/lang/mn/actions/detach.php
  packages/support/resources/lang/mn/actions/dissociate.php
  packages/support/resources/lang/mn/actions/edit.php
  packages/support/resources/lang/mn/actions/force-delete.php
  packages/support/resources/lang/mn/actions/group.php
  packages/support/resources/lang/mn/actions/modal.php
  packages/support/resources/lang/mn/actions/replicate.php
  packages/support/resources/lang/mn/actions/restore.php
  packages/support/resources/lang/mn/actions/view.php
  packages/support/resources/lang/mn/components/button.php
  packages/support/resources/lang/mn/components/modal.php
  packages/tables/resources/lang/mn/table.php
Labels: enhancement, i18n

#6431 Fix options not resetting after backspacing
  packages/forms/resources/js/components/select.js
Labels: bug

#6474 Setting time in DateTimePicker init() after defining the watchers
  packages/forms/resources/js/components/date-time-picker.js
Labels: bug

#6432 Add ability to search values in select fields
  packages/forms/resources/js/components/select.js
  packages/forms/resources/views/components/select.blade.php
  packages/forms/src/Components/Concerns/CanBeSearchable.php
Labels: enhancement

#6489 Fixed button opacity when disabled state changes
  packages/support/resources/views/components/button.blade.php
Labels: bug

#6479 Fix: Hidden Inputs taking up space in grid
  packages/support/resources/views/components/grid/column.blade.php
Labels: bug

#6493 Docs: Add section for Customizing Query String
  packages/admin/docs/02-resources/02-listing-records.md
Labels: documentation

#6504 Revert "Setting time in DateTimePicker init() after defining the watchers"
  packages/forms/resources/js/components/date-time-picker.js
Labels: bug

#6506 Clean up
  packages/forms/resources/js/components/select.js
  packages/forms/resources/views/components/tabs.blade.php
  packages/forms/src/Components/Tabs/Tab.php
  packages/support/resources/views/components/button.blade.php
Labels: code quality

#6511 Support info color
  docs-assets/app/tailwind.config.js
  packages/actions/docs/01-installation.md
  packages/actions/docs/03-trigger-button.md
  packages/app/docs/06-navigation.md
  packages/app/docs/11-themes.md
  packages/app/resources/views/components/layouts/app/sidebar/badge.blade.php
  packages/app/resources/views/components/layouts/app/topbar/badge.blade.php
  packages/app/src/Context/Concerns/HasColors.php
  packages/app/src/Facades/Filament.php
  packages/app/src/FilamentManager.php
  packages/app/tailwind.config.preset.js
  packages/forms/docs/01-installation.md
  packages/forms/docs/03-fields/01-getting-started.md
  packages/forms/docs/03-fields/05-toggle.md
  packages/forms/docs/04-layout/04-tabs.md
  packages/forms/resources/views/components/field-wrapper/hint.blade.php
  packages/forms/resources/views/components/toggle.blade.php
  packages/infolists/docs/01-installation.md
  packages/infolists/docs/03-entries/02-text.md
  packages/infolists/docs/03-entries/03-icon.md
  packages/infolists/docs/04-layout/04-tabs.md
  packages/infolists/resources/views/components/entry-wrapper/hint.blade.php
  packages/infolists/resources/views/components/icon-entry.blade.php
  packages/infolists/resources/views/components/text-entry.blade.php
  packages/notifications/docs/01-installation.md
  packages/notifications/docs/02-sending-notifications.md
  packages/notifications/resources/js/Notification.js
  packages/notifications/resources/views/components/icon.blade.php
  packages/notifications/resources/views/notification.blade.php
  packages/notifications/src/Notification.php
  packages/support/resources/views/components/button.blade.php
  packages/support/resources/views/components/dropdown/header.blade.php
  packages/support/resources/views/components/dropdown/list/item.blade.php
  packages/support/resources/views/components/icon-button.blade.php
  packages/support/resources/views/components/link.blade.php
  packages/support/resources/views/components/section.blade.php
  packages/support/resources/views/components/tabs/item.blade.php
  packages/support/stubs/scaffolding/tailwind.config.js
  packages/tables/docs/01-installation.md
  packages/tables/docs/03-columns/02-text.md
  packages/tables/docs/03-columns/03-icon.md
  packages/tables/resources/views/columns/icon-column.blade.php
  packages/tables/resources/views/columns/summaries/icon-count.blade.php
  packages/tables/resources/views/columns/text-column.blade.php
  packages/tables/resources/views/columns/toggle-column.blade.php
  packages/widgets/docs/01-installation.md
  packages/widgets/docs/02-stats-overview.md
  packages/widgets/resources/views/stats-overview-widget/card.blade.php
  tests/src/Notifications/NotificationTest.php
Labels: enhancement

#6513 Fixed translations in 01-getting-started.md
  packages/admin/docs/02-resources/01-getting-started.md
Labels: documentation

#6516 Fix button
  packages/support/resources/views/components/button.blade.php
Labels: bug

#6522 Update prettier-plugin-tailwindcss
  package.json
Labels: chore

#6524 📌 Allow `spatie/laravel-settings:^3.0`
  packages/spatie-laravel-settings-plugin/composer.json
Labels: chore

#6507 Adds the possibility of having '0' as a prefix or postfix for different form inputs
  packages/forms/resources/views/components/color-picker.blade.php
  packages/forms/resources/views/components/select.blade.php
  packages/forms/resources/views/components/text-input.blade.php
Labels: bug

#6530 Remove trailing comma from composer.json
  packages/spatie-laravel-settings-plugin/composer.json
Labels: bug

#6534 Fix code style on PRs
  .github/workflows/fix-code-style.yml
  .github/workflows/npm-build.yml
Labels: chore

#6535 Set table on empty state actions
  packages/tables/src/Table/Concerns/HasEmptyState.php
Labels: bug

#6536 Set table on all header actions
  packages/tables/src/Table/Concerns/HasHeaderActions.php
Labels: enhancement

#6537 Pass data to view as second param
  packages/support/src/Components/ViewComponent.php
Labels: enhancement

#6532 Check if relation is already eagerloaded
  packages/tables/src/Columns/Concerns/InteractsWithTableQuery.php
Labels: bug

#6550 Refactor view page authorization
  packages/app/src/Resources/Pages/ViewRecord.php
Labels: code quality

#6570 feature: Mark database notifications as read
  packages/app/dist/theme.css
  packages/notifications/dist/index.js
  packages/notifications/docs/03-database-notifications.md
  packages/notifications/resources/js/components/notification.js
  packages/notifications/resources/views/components/database/modal/index.blade.php
  packages/notifications/src/Actions/Action.php
  packages/notifications/src/Http/Livewire/DatabaseNotifications.php
Labels: enhancement

#6572 feature: Paginate database notifications
  packages/notifications/resources/lang/en/database.php
  packages/notifications/resources/views/components/database/modal/index.blade.php
  packages/notifications/src/Http/Livewire/DatabaseNotifications.php
Labels: enhancement

#6508 Preserve persisted sort order with defaultSort() set
  packages/tables/src/Concerns/CanSortRecords.php
  packages/tables/src/Concerns/InteractsWithTable.php
Labels: bug

#6554 added applyEagerLoading and applyRelationshipAggregates to get selected table records
  packages/tables/src/Concerns/CanSelectRecords.php
Labels: bug

#6568 Fix error when closing CreateOptionForm with TagsInput
  packages/forms/resources/views/components/tags-input.blade.php
Labels: bug

#6565 fix zero value not showing when using mask on text input
  packages/forms/resources/js/components/text-input.js
Labels: bug

#6494 Add ability to change datepicker icon
  packages/forms/docs/03-fields.md
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/src/Components/DateTimePicker.php
  packages/support/src/Actions/Concerns/CanEmitEvent.php
Labels: enhancement

#6195 Support dark mode system setting
  package-lock.json
  packages/app/dist/theme.css
  packages/app/resources/js/index.js
  packages/app/resources/lang/ar/layout.php
  packages/app/resources/lang/bn/layout.php
  packages/app/resources/lang/bs/layout.php
  packages/app/resources/lang/cs/layout.php
  packages/app/resources/lang/da/layout.php
  packages/app/resources/lang/de/layout.php
  packages/app/resources/lang/el/layout.php
  packages/app/resources/lang/en/layout.php
  packages/app/resources/lang/es/layout.php
  packages/app/resources/lang/fa/layout.php
  packages/app/resources/lang/fi/layout.php
  packages/app/resources/lang/fr/layout.php
  packages/app/resources/lang/he/layout.php
  packages/app/resources/lang/hi/layout.php
  packages/app/resources/lang/hu/layout.php
  packages/app/resources/lang/hy/layout.php
  packages/app/resources/lang/id/layout.php
  packages/app/resources/lang/it/layout.php
  packages/app/resources/lang/ja/layout.php
  packages/app/resources/lang/ko/layout.php
  packages/app/resources/lang/ku/layout.php
  packages/app/resources/lang/lt/layout.php
  packages/app/resources/lang/lv/layout.php
  packages/app/resources/lang/ms/layout.php
  packages/app/resources/lang/my/layout.php
  packages/app/resources/lang/nl/layout.php
  packages/app/resources/lang/pl/layout.php
  packages/app/resources/lang/pt_BR/layout.php
  packages/app/resources/lang/pt_PT/layout.php
  packages/app/resources/lang/ro/layout.php
  packages/app/resources/lang/ru/layout.php
  packages/app/resources/lang/sv/layout.php
  packages/app/resources/lang/sw/layout.php
  packages/app/resources/lang/tr/layout.php
  packages/app/resources/lang/uk/layout.php
  packages/app/resources/lang/vi/layout.php
  packages/app/resources/lang/zh_CN/layout.php
  packages/app/resources/lang/zh_TW/layout.php
  packages/app/resources/views/components/layouts/base.blade.php
  packages/app/resources/views/components/user-menu.blade.php
  packages/widgets/resources/views/stats-overview-widget/card.blade.php
Labels: enhancement

#6577 Update 04-layout.md
  packages/forms/docs/04-layout.md
Labels: documentation

#6569 Fixes divide-y line in TagsInput when no tags are present
  packages/forms/resources/views/components/tags-input.blade.php
Labels: bug

#6518 Add support for underline in RichEditor
  packages/forms/resources/js/components/rich-editor.js
  packages/forms/resources/lang/en/components.php
  packages/forms/resources/lang/nl/components.php
  packages/forms/resources/views/components/rich-editor.blade.php
  packages/forms/src/Components/RichEditor.php
Labels: enhancement

#6578 Added Default Image URL Feature
  packages/spatie-laravel-media-library-plugin/src/Tables/Columns/SpatieMediaLibraryImageColumn.php
  packages/tables/docs/03-columns/04-image.md
  packages/tables/src/Columns/ImageColumn.php
Labels: enhancement

#6579 Improvements for Mongolian Translation
  packages/admin/resources/lang/mn/resources/pages/create-record.php
  packages/admin/resources/lang/mn/resources/pages/edit-record.php
  packages/support/resources/lang/mn/actions/modal.php
  packages/tables/resources/lang/mn/table.php
Labels: i18n

#6581 Exclude non-selectable records from select all
  packages/tables/docs/05-actions.md
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Concerns/CanSelectRecords.php
  packages/tables/src/Contracts/HasTable.php
Labels: bug

#6582 fix: Extra bulk action attributes
  packages/tables/resources/views/actions/bulk-action.blade.php
Labels: bug

#6586 add applyDefaultSortingToTableQuery method to custom default sort behavior
  packages/tables/src/Concerns/CanSortRecords.php
Labels: enhancement

#6599 Update French translations
  packages/forms/resources/lang/fr/components.php
Labels: i18n

#6606 Add enabled options getter example
  packages/forms/docs/03-fields/03-select.md
  packages/forms/docs/03-fields/07-radio.md
Labels: documentation

#6607 Fix rich editor toolbar button
  packages/forms/resources/views/components/rich-editor.blade.php
Labels: bug

#6616 Fix password confirmation translation key
  packages/app/resources/lang/de/pages/auth/password-reset/reset-password.php
  packages/app/resources/lang/de/pages/auth/register.php
  packages/app/resources/lang/en/pages/auth/password-reset/reset-password.php
  packages/app/resources/lang/en/pages/auth/register.php
  packages/app/resources/lang/nl/pages/auth/register.php
  packages/app/src/Pages/Auth/PasswordReset/ResetPassword.php
  packages/app/src/Pages/Auth/Register.php
Labels: code quality

#6620 Prevent overriding authenticated routes
  packages/app/routes/web.php
Labels: bug

#6615 Improve section alignment
  packages/support/resources/views/components/section.blade.php
Labels: enhancement, ui

#6617 Support aligment in file upload field
  packages/forms/resources/css/components/file-upload.css
  packages/forms/resources/views/components/file-upload.blade.php
  packages/forms/src/Components/FileUpload.php
  packages/infolists/src/Components/Entry.php
  packages/support/src/Concerns/HasAlignment.php
  packages/tables/src/Columns/Column.php
  packages/tables/src/Columns/Concerns/HasAlignment.php
  packages/tables/src/Columns/Layout/Stack.php
Labels: enhancement

#6601 esbuild watch and auto-publish filament assets
  bin/build.mjs
Labels: enhancement

#6635 Update command descriptions
  packages/admin/src/Commands/MakePageCommand.php
  packages/admin/src/Commands/MakeRelationManagerCommand.php
  packages/admin/src/Commands/MakeResourceCommand.php
  packages/admin/src/Commands/MakeUserCommand.php
  packages/admin/src/Commands/MakeWidgetCommand.php
  packages/forms/src/Commands/InstallCommand.php
  packages/forms/src/Commands/MakeFieldCommand.php
  packages/forms/src/Commands/MakeFormCommand.php
  packages/forms/src/Commands/MakeLayoutComponentCommand.php
  packages/notifications/src/Commands/InstallCommand.php
  packages/spatie-laravel-settings-plugin/src/Commands/MakeSettingsPageCommand.php
  packages/support/src/Commands/CheckTranslationsCommand.php
  packages/support/src/Commands/UpgradeCommand.php
  packages/tables/src/Commands/InstallCommand.php
  packages/tables/src/Commands/MakeColumnCommand.php
  packages/tables/src/Commands/MakeTableCommand.php
Labels: chore

#6640 Update install command naming
  packages/panels/docs/01-installation.md
  packages/panels/docs/14-upgrade-guide.md
  packages/support/src/Commands/InstallCommand.php
  packages/upgrade/bin/create-filament-v3-panel-provider.php
  packages/upgrade/bin/filament-v3
Labels: chore

#6646 Fix: gradient highlights in theme
  packages/panels/dist/theme.css
  packages/panels/resources/css/theme.css
Labels: bug, ui

#6649 Fix facade order
  packages/panels/src/Facades/Filament.php
  packages/panels/src/FilamentManager.php
Labels: chore

#6656 Rename access check
  docs-assets/app/app/Models/User.php
  packages/panels/docs/08-users.md
  packages/panels/docs/14-upgrade-guide.md
  packages/panels/src/Http/Middleware/Authenticate.php
  packages/panels/src/Models/Contracts/FilamentUser.php
  packages/upgrade/src/rector.php
  tests/src/Models/User.php
Labels: chore
