Repository filamentphp/filament, pull requests merged in 2023-10, with the labels that each got.

#8820 Update Hungarian translations
  packages/actions/resources/lang/hu/force-delete.php
  packages/actions/resources/lang/hu/modal.php
  packages/forms/resources/lang/hu/components.php
  packages/notifications/resources/lang/hu/database.php
  packages/panels/resources/lang/hu/global-search.php
  packages/panels/resources/lang/hu/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/hu/resources/pages/create-record.php
  packages/support/resources/lang/hu/components/modal.php
  packages/support/resources/lang/hu/components/pagination.php
Labels: i18n

#8833 Update 02-getting-started.md
  packages/forms/docs/02-getting-started.md
Labels: documentation

#8848 bring v3 image-editor to alpha version
  bin/build.js
  package-lock.json
  package.json
  packages/forms/dist/components/file-upload.js
  packages/forms/dist/index.css
  packages/forms/resources/css/components/file-upload.css
  packages/forms/resources/js/components/file-upload.js
  packages/forms/resources/lang/en/components.php
  packages/forms/resources/lang/sv/components.php
  packages/forms/resources/views/components/file-upload.blade.php
  packages/forms/src/Components/FileUpload.php
  packages/panels/dist/theme.css
  packages/support/resources/views/components/badge.blade.php
  packages/support/resources/views/components/button/group.blade.php
  packages/support/resources/views/components/button/index.blade.php
  packages/support/resources/views/components/icon.blade.php
Labels: enhancement

#8840 Fix widget make command
  packages/widgets/src/Commands/MakeWidgetCommand.php
Labels: bug

#8860 Updated basque translations to fit v3
  packages/forms/resources/lang/eu/components.php
  packages/tables/resources/lang/eu/table.php
Labels: i18n

#8853 fix: add label and state to sidebar group controls (resolves #8852)
  packages/panels/resources/views/components/sidebar/group.blade.php
Labels: bug

#8858 fix: add accessible label to pagination item buttons (fixes #8856)
  packages/support/resources/views/components/pagination/item.blade.php
Labels: bug

#8883 Add Azerbaijani (az) language translations
  packages/actions/resources/lang/az/associate.php
  packages/actions/resources/lang/az/attach.php
  packages/actions/resources/lang/az/create.php
  packages/actions/resources/lang/az/delete.php
  packages/actions/resources/lang/az/detach.php
  packages/actions/resources/lang/az/dissociate.php
  packages/actions/resources/lang/az/edit.php
  packages/actions/resources/lang/az/force-delete.php
  packages/actions/resources/lang/az/group.php
  packages/actions/resources/lang/az/modal.php
  packages/actions/resources/lang/az/replicate.php
  packages/actions/resources/lang/az/restore.php
  packages/actions/resources/lang/az/view.php
  packages/forms/resources/lang/az/components.php
  packages/infolists/resources/lang/az/components.php
  packages/notifications/resources/lang/az/database.php
  packages/panels/resources/lang/az/global-search.php
  packages/panels/resources/lang/az/layout.php
  packages/panels/resources/lang/az/pages/auth/edit-profile.php
  packages/panels/resources/lang/az/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/az/pages/auth/login.php
  packages/panels/resources/lang/az/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/az/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/az/pages/auth/register.php
  packages/panels/resources/lang/az/pages/dashboard.php
  packages/panels/resources/lang/az/pages/tenancy/edit-tenant-profile.php
  packages/panels/resources/lang/az/resources/pages/create-record.php
  packages/panels/resources/lang/az/resources/pages/edit-record.php
  packages/panels/resources/lang/az/resources/pages/list-records.php
  packages/panels/resources/lang/az/resources/pages/view-record.php
  packages/panels/resources/lang/az/widgets/account-widget.php
  packages/panels/resources/lang/az/widgets/filament-info-widget.php
  packages/spatie-laravel-settings-plugin/resources/lang/az/pages/settings-page.php
  packages/spatie-laravel-translatable-plugin/resources/lang/az/actions.php
  packages/support/resources/lang/az/components/button.php
  packages/support/resources/lang/az/components/copyable.php
  packages/support/resources/lang/az/components/modal.php
  packages/support/resources/lang/az/components/pagination.php
  packages/tables/resources/lang/az/table.php
Labels: i18n

#8885 Fix typo in custom form fields docs
  packages/forms/docs/03-fields/19-custom.md
Labels: documentation

#8893 Fix collapsible section displacement and `invisible` `h-0` bug
  packages/support/resources/views/components/section/index.blade.php
Labels: bug

#8904 Disable manual resizing for autosizing textarea
  packages/forms/resources/views/components/textarea.blade.php
  packages/panels/dist/theme.css
Labels: enhancement, ui

#8902 Update 08-date-time-picker.md
  packages/forms/docs/03-fields/08-date-time-picker.md
Labels: documentation

#8918 Update 10-tenancy.md
  packages/panels/docs/10-tenancy.md
Labels: documentation

#8722 Added paths when succesfully creating components from commands
  packages/forms/src/Commands/MakeFieldCommand.php
  packages/forms/src/Commands/MakeFormCommand.php
  packages/forms/src/Commands/MakeLayoutComponentCommand.php
  packages/infolists/src/Commands/MakeEntryCommand.php
  packages/infolists/src/Commands/MakeLayoutComponentCommand.php
  packages/panels/src/Commands/MakePageCommand.php
  packages/panels/src/Commands/MakePanelCommand.php
  packages/panels/src/Commands/MakeRelationManagerCommand.php
  packages/panels/src/Commands/MakeResourceCommand.php
  packages/panels/src/Commands/MakeThemeCommand.php
  packages/spatie-laravel-settings-plugin/src/Commands/MakeSettingsPageCommand.php
  packages/tables/src/Commands/MakeColumnCommand.php
  packages/tables/src/Commands/MakeTableCommand.php
  packages/widgets/src/Commands/MakeWidgetCommand.php
Labels: enhancement

#8812 Add small guidance for controlling access to multiple panels
  packages/panels/docs/08-users.md
Labels: documentation

#8891 Register page form.before and form.after render hooks
  packages/panels/resources/views/pages/auth/register.blade.php
  packages/support/docs/06-render-hooks.md
Labels: enhancement

#8925 Fix: wrong injection parameter in TextEntry Doc
  packages/infolists/docs/03-entries/02-text.md
Labels: documentation

#8823 Throw exception when creating Filament user without panel
  packages/panels/src/Commands/MakeUserCommand.php
Labels: bug

#8952 Fix nested recursive validation rules
  packages/forms/resources/views/components/field-wrapper/index.blade.php
Labels: bug

#8948 Update 01-getting-started.md
  packages/panels/docs/03-resources/01-getting-started.md
Labels: documentation

#8884 Add column labels to table global search field
  packages/tables/docs/03-columns/01-getting-started.md
  packages/tables/resources/views/components/search-field.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Table/Concerns/CanSearchRecords.php
Labels: enhancement, low priority

#8898 Fix hydration of boolean states in Select component
  packages/forms/src/Components/Select.php
Labels: bug

#8864 Support getting media temporary URL based on user specified conversion name
  packages/spatie-laravel-media-library-plugin/src/Forms/Components/SpatieMediaLibraryFileUpload.php
Labels: bug

#8456 chore(config): Add 'assets_path' for Filament published assets
  packages/support/config/filament.php
  packages/support/src/Assets/AlpineComponent.php
  packages/support/src/Assets/Css.php
  packages/support/src/Assets/Js.php
Labels: enhancement, low priority

#8814 Update 05-dashboard.md -- add routes to avoid errors
  packages/panels/docs/05-dashboard.md
Labels: documentation

#8929 Register page.header render hook
  packages/panels/resources/views/components/header/index.blade.php
  packages/support/docs/06-render-hooks.md
Labels: enhancement

#8980 Add hook class for table header cell labels
  packages/tables/resources/views/components/header-cell.blade.php
Labels: enhancement

#8983 Add alias for color shades in button component
  packages/support/resources/views/components/button/index.blade.php
Labels: enhancement

#9024 Improve brand logo
  packages/actions/src/Concerns/HasDropdown.php
  packages/panels/resources/views/components/logo.blade.php
  packages/panels/src/Facades/Filament.php
  packages/panels/src/FilamentManager.php
  packages/panels/src/Panel/Concerns/HasBrandLogo.php
Labels: enhancement

#8990 Remove unwanted spaces in link
  packages/support/resources/views/components/link.blade.php
  packages/support/src/SupportServiceProvider.php
Labels: bug

#9023 Remove duplicate link from docs
  packages/panels/docs/03-resources/07-relation-managers.md
Labels: documentation

#9026 Support dark mode brand logo
  packages/panels/dist/theme.css
  packages/panels/docs/11-themes.md
  packages/panels/resources/views/components/logo.blade.php
  packages/panels/src/Facades/Filament.php
  packages/panels/src/FilamentManager.php
  packages/panels/src/Panel/Concerns/HasBrandLogo.php
Labels: enhancement

#9044 missing file-upload swedish translations
  packages/forms/resources/lang/sv/components.php
Labels: i18n

#9046 Change Notification object naming in Swedish
  packages/notifications/resources/lang/sv/database.php
Labels: i18n

#9031 Add non-static `authorizeAccess` to ListRecords
  packages/panels/src/Resources/Pages/ListRecords.php
Labels: enhancement

#9055 Fix typo in "Debouncing reactive fields" docs
  packages/forms/docs/07-advanced.md
Labels: documentation

#9059 Explain form's reorderable $condition parameter
  packages/tables/docs/10-advanced.md
Labels: documentation

#9058 Fix $hydratedDefaultState being populated accidentally by Select
  packages/forms/src/Components/Select.php
Labels: bug

#8921 Improve actions
  docs-assets/app/app/Livewire/ActionsDemo.php
  docs-assets/app/public/css/filament/filament/app.css
  docs-assets/app/public/css/filament/forms/forms.css
  docs-assets/app/public/js/filament/forms/components/date-time-picker.js
  docs-assets/app/public/js/filament/forms/components/file-upload.js
  docs-assets/app/public/js/filament/forms/components/key-value.js
  docs-assets/app/public/js/filament/forms/components/markdown-editor.js
  docs-assets/app/public/js/filament/forms/components/tags-input.js
  docs-assets/app/public/js/filament/forms/components/textarea.js
  docs-assets/app/public/js/filament/notifications/notifications.js
  docs-assets/app/public/js/filament/support/async-alpine.js
  docs-assets/app/public/js/filament/support/support.js
  docs-assets/app/public/js/filament/tables/components/table.js
  docs-assets/app/resources/views/livewire/actions.blade.php
  docs-assets/screenshots/images/dark/actions/trigger-button/badge.jpg
  docs-assets/screenshots/images/dark/actions/trigger-button/badged.jpg
  docs-assets/screenshots/images/dark/actions/trigger-button/success-badge.jpg
  docs-assets/screenshots/images/dark/actions/trigger-button/success-badged.jpg
  docs-assets/screenshots/images/light/actions/trigger-button/badge.jpg
  docs-assets/screenshots/images/light/actions/trigger-button/badged.jpg
  docs-assets/screenshots/images/light/actions/trigger-button/success-badge.jpg
  docs-assets/screenshots/images/light/actions/trigger-button/success-badged.jpg
  docs-assets/screenshots/schema.js
  packages/actions/docs/03-trigger-button.md
  packages/actions/resources/views/badge-action.blade.php
  packages/actions/resources/views/badge-group.blade.php
  packages/actions/resources/views/button-action.blade.php
  packages/actions/resources/views/button-group.blade.php
  packages/actions/resources/views/components/action.blade.php
  packages/actions/resources/views/components/group.blade.php
  packages/actions/resources/views/grouped-action.blade.php
  packages/actions/resources/views/grouped-group.blade.php
  packages/actions/resources/views/icon-button-action.blade.php
  packages/actions/resources/views/icon-button-group.blade.php
  packages/actions/src/ActionGroup.php
  packages/actions/src/StaticAction.php
  packages/notifications/src/Actions/Action.php
  packages/notifications/src/Actions/ActionGroup.php
  packages/support/resources/views/components/badge.blade.php
  packages/support/resources/views/components/button/index.blade.php
  packages/support/resources/views/components/link.blade.php
  packages/support/resources/views/components/tabs/item.blade.php
  packages/support/src/Concerns/HasBadge.php
  packages/support/src/Enums/IconPosition.php
  packages/support/src/Enums/IconSize.php
  tests/src/Notifications/NotificationTest.php
Labels: bug

#9062 Add github trending badge to readme file
  README.md
Labels: chore

#9087 Wrap Livewire hook code in $nextTick in CheckboxList
  packages/forms/resources/views/components/checkbox-list.blade.php
Labels: bug

#8810 Ignore UUID `id` fields in form generation
  packages/forms/src/Commands/Concerns/CanGenerateForms.php
Labels: enhancement

#9090 Fix to support nested relationship for select field
  packages/forms/src/Components/Select.php
Labels: enhancement

#9084 Wrap all expand-concealing-component event code in $nextTick
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/repeater.blade.php
  packages/forms/resources/views/components/tabs/tab.blade.php
  packages/forms/resources/views/components/wizard/step.blade.php
  packages/support/resources/views/components/section/index.blade.php
Labels: bug

#9091 Fix UI for hidden affixes action
  packages/support/resources/views/components/input/wrapper.blade.php
Labels: bug

#9101 Allow \Closure on favicon
  packages/panels/src/Panel/Concerns/HasFavicon.php
Labels: enhancement

#8792 Fix autofocus issue due to hidden main container
  packages/panels/resources/views/components/layout/index.blade.php
Labels: bug

#8831 Configurable wire loading delay
  packages/support/config/filament.php
  packages/support/resources/views/components/badge.blade.php
  packages/support/resources/views/components/button/index.blade.php
  packages/support/resources/views/components/dropdown/list/item.blade.php
  packages/support/resources/views/components/icon-button.blade.php
  packages/support/resources/views/components/input/wrapper.blade.php
  packages/support/resources/views/components/link.blade.php
  packages/tables/resources/views/components/filters/index.blade.php
  packages/tables/resources/views/components/reorder/indicator.blade.php
Labels: enhancement

#8790 Fix error with morphing toggled relation manager tabs
  packages/panels/resources/views/components/resources/relation-managers.blade.php
Labels: bug

#9060 Queue auth email notifications
  packages/panels/src/Notifications/Auth/ResetPassword.php
  packages/panels/src/Notifications/Auth/VerifyEmail.php
Labels: enhancement

#9110 Use `focus-visible` for focus states
  packages/forms/dist/index.css
  packages/forms/resources/css/components/markdown-editor.css
  packages/forms/resources/css/components/select.css
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/resources/views/components/file-upload.blade.php
  packages/forms/resources/views/components/rich-editor.blade.php
  packages/forms/resources/views/components/rich-editor/toolbar/button.blade.php
  packages/forms/resources/views/components/textarea.blade.php
  packages/infolists/resources/views/components/text-entry.blade.php
  packages/panels/dist/theme.css
  packages/panels/resources/views/components/sidebar/item.blade.php
  packages/panels/resources/views/components/tenant-menu.blade.php
  packages/panels/resources/views/components/theme-switcher/button.blade.php
  packages/panels/resources/views/components/topbar/item.blade.php
  packages/support/resources/views/components/badge.blade.php
  packages/support/resources/views/components/breadcrumbs.blade.php
  packages/support/resources/views/components/button/index.blade.php
  packages/support/resources/views/components/dropdown/list/item.blade.php
  packages/support/resources/views/components/icon-button.blade.php
  packages/support/resources/views/components/input/index.blade.php
  packages/support/resources/views/components/input/select.blade.php
  packages/support/resources/views/components/link.blade.php
  packages/support/resources/views/components/tabs/item.blade.php
  packages/tables/resources/views/columns/text-column.blade.php
  packages/tables/resources/views/components/header-cell.blade.php
Labels: bug

#9115 Add custom headers
  packages/spatie-laravel-media-library-plugin/README.md
  packages/spatie-laravel-media-library-plugin/src/Forms/Components/SpatieMediaLibraryFileUpload.php
Labels: enhancement

#9133 Add Notifications Livewire Component to Layout in Docs
  packages/notifications/docs/01-installation.md
Labels: documentation

#9140 [3.x] Add new `Markdown` helper class
  packages/support/src/Markdown.php
  tests/src/Support/MarkdownTest.php
Labels: enhancement

#9143 Added a message about the need to use an identifier.
  packages/forms/docs/03-fields/12-repeater.md
Labels: documentation

#9137 Add prompt to ask for type of widget when no type is passed in command
  packages/widgets/src/Commands/MakeWidgetCommand.php
Labels: enhancement

#9162 Fix pagination responsiveness
  packages/panels/dist/theme.css
  packages/support/dist/index.css
  packages/support/resources/css/components/pagination.css
  packages/support/resources/js/index.js
  packages/support/resources/views/components/pagination/index.blade.php
  packages/tables/src/Concerns/CanPaginateRecords.php
Labels: bug, high priority

#9163 Alias the imports for the make:filament-resource command
  packages/panels/src/Commands/MakeResourceCommand.php
  packages/panels/stubs/ResourceEditPage.stub
  packages/panels/stubs/ResourceListPage.stub
  packages/panels/stubs/ResourceManagePage.stub
  packages/panels/stubs/ResourceViewPage.stub
Labels: bug

#9164 Evaluate the conditions in the alignment shorthand methods
  packages/support/src/Concerns/HasAlignment.php
Labels: bug

#8985 Ability to send arguments to specific nested action in tests
  packages/actions/src/Testing/TestsActions.php
  tests/src/Actions/ActionTest.php
  tests/src/Actions/Fixtures/Pages/Actions.php
Labels: enhancement

#8779 Support affix icon color
  packages/forms/docs/03-fields/02-text-input.md
  packages/forms/docs/03-fields/03-select.md
  packages/forms/docs/03-fields/08-date-time-picker.md
  packages/forms/resources/views/components/color-picker.blade.php
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/resources/views/components/select.blade.php
  packages/forms/resources/views/components/text-input.blade.php
  packages/forms/src/Components/Concerns/HasAffixes.php
  packages/support/docs/09-blade-components/02-input-wrapper.md
  packages/support/resources/views/components/input/wrapper.blade.php
  packages/support/src/helpers.php
Labels: enhancement, low priority

#9131 add scale to bcdiv to fix format_money method to include decimal values when dividing
  packages/support/src/helpers.php
Labels: bug

#9170 Update ckb and ku translations
  packages/panels/resources/lang/ckb/pages/auth/login.php
  packages/panels/resources/lang/ckb/pages/auth/register.php
  packages/panels/resources/lang/ckb/resources/pages/create-record.php
  packages/panels/resources/lang/ku/pages/auth/login.php
  packages/panels/resources/lang/ku/pages/auth/register.php
  packages/panels/resources/lang/ku/resources/pages/create-record.php
  packages/tables/resources/lang/ckb/table.php
  packages/tables/resources/lang/ku/table.php
Labels: i18n

#9168 Improve Vietnamese translation
  packages/support/resources/lang/vi/components/pagination.php
Labels: i18n

#9179 Update and improve ID translations
  packages/forms/resources/lang/id/components.php
  packages/tables/resources/lang/id/table.php
Labels: i18n

#9182 Update ms translations
  packages/forms/resources/lang/ms/components.php
Labels: i18n

#9178 Fixes Summarize Query Bug on PostgreSQL #9177
  packages/tables/src/Columns/Summarizers/Summarizer.php
Labels: bug

#9175 Add brandLogo API to Upgrade Guide
  packages/panels/docs/14-upgrade-guide.md
Labels: documentation

#9157 Update CanFormatState.php
  packages/infolists/src/Components/Concerns/CanFormatState.php
  packages/tables/src/Columns/Concerns/CanFormatState.php
Labels: enhancement

#9187 Prevent GitHub from opening when installing with --no-interaction
  packages/support/src/Commands/InstallCommand.php
Labels: bug

#9151 load the table when it's visible
  packages/tables/resources/views/index.blade.php
Labels: bug

#9191 Add missing icon aliases
  packages/actions/src/DeleteAction.php
  packages/actions/src/ForceDeleteAction.php
  packages/actions/src/ReplicateAction.php
  packages/actions/src/RestoreAction.php
  packages/infolists/src/Components/IconEntry.php
  packages/panels/resources/views/components/sidebar/index.blade.php
  packages/support/docs/03-icons.md
  packages/support/resources/views/components/breadcrumbs.blade.php
  packages/support/resources/views/components/pagination/index.blade.php
  packages/support/src/Icons/IconManager.php
  packages/tables/resources/views/components/reorder/handle.blade.php
  packages/tables/src/Actions/DeleteAction.php
  packages/tables/src/Actions/DeleteBulkAction.php
  packages/tables/src/Actions/DetachAction.php
  packages/tables/src/Actions/DetachBulkAction.php
  packages/tables/src/Actions/DissociateAction.php
  packages/tables/src/Actions/DissociateBulkAction.php
  packages/tables/src/Actions/ForceDeleteAction.php
  packages/tables/src/Actions/ForceDeleteBulkAction.php
  packages/tables/src/Actions/ReplicateAction.php
  packages/tables/src/Actions/RestoreAction.php
  packages/tables/src/Actions/RestoreBulkAction.php
  packages/tables/src/Columns/IconColumn.php
  packages/tables/src/Table/Concerns/HasEmptyState.php
Labels: chore

#9211 Simplify theme CSS
  packages/panels/stubs/ThemeCss.stub
Labels: code quality

#9231 fix: Grouped default values
  packages/forms/dist/components/select.js
  packages/forms/resources/js/components/select.js
Labels: bug

#9226 Update override value in StatsOverviewWidget docs
  packages/widgets/docs/02-stats-overview.md
Labels: documentation

#9245 Fix/missing dayjs translations
  packages/forms/dist/components/date-time-picker.js
  packages/forms/resources/js/components/date-time-picker.js
Labels: enhancement

#9240 Support `Htmlable` in global search result title
  packages/panels/docs/03-resources/08-global-search.md
  packages/panels/src/GlobalSearch/GlobalSearchResult.php
  packages/panels/src/Resources/Resource.php
Labels: enhancement

#9255 Fix toggle all checkboxes
  packages/forms/resources/views/components/checkbox-list.blade.php
Labels: bug

#9253 Re-order state formatting
  packages/infolists/src/Components/Concerns/CanFormatState.php
  packages/tables/src/Columns/Concerns/CanFormatState.php
Labels: bug

#9258 Refactor avatars
  packages/panels/resources/views/components/avatar/tenant.blade.php
  packages/panels/resources/views/components/avatar/user.blade.php
  packages/panels/resources/views/components/tenant-menu.blade.php
  packages/support/docs/09-blade-components/02-avatar.md
  packages/support/resources/views/components/avatar.blade.php
Labels: enhancement

#9259 feature: Filter modal
  packages/actions/src/Concerns/CanOpenModal.php
  packages/tables/resources/views/components/filters/dialog.blade.php
  packages/tables/resources/views/components/filters/dropdown.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Enums/FiltersLayout.php
  packages/tables/src/Table/Concerns/HasFilters.php
Labels: enhancement

#9287 [3.x] Ask for panel ID when installing with `--panels`
  packages/panels/src/Commands/MakePanelCommand.php
  packages/support/src/Commands/Concerns/CanGeneratePanels.php
  packages/support/src/Commands/InstallCommand.php
Labels: enhancement

#9167 Improve actions spacing
  packages/actions/resources/views/components/actions.blade.php
  packages/forms/resources/views/components/actions.blade.php
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/field-wrapper/hint.blade.php
  packages/forms/resources/views/components/file-upload.blade.php
  packages/forms/resources/views/components/repeater.blade.php
  packages/forms/resources/views/components/select.blade.php
  packages/infolists/resources/views/components/actions.blade.php
  packages/infolists/resources/views/components/affixes.blade.php
  packages/infolists/resources/views/components/entry-wrapper/hint.blade.php
  packages/infolists/resources/views/components/entry-wrapper/index.blade.php
  packages/notifications/resources/views/components/close-button.blade.php
  packages/panels/dist/theme.css
  packages/panels/resources/views/components/sidebar/group.blade.php
  packages/panels/resources/views/components/sidebar/index.blade.php
  packages/panels/resources/views/components/topbar/index.blade.php
  packages/panels/resources/views/widgets/account-widget.blade.php
  packages/support/resources/views/components/badge.blade.php
  packages/support/resources/views/components/button/index.blade.php
  packages/support/resources/views/components/icon-button.blade.php
  packages/support/resources/views/components/input/wrapper.blade.php
  packages/support/resources/views/components/link.blade.php
  packages/support/resources/views/components/modal/index.blade.php
  packages/support/resources/views/components/section/index.blade.php
  packages/support/src/Enums/Alignment.php
  packages/support/src/Enums/VerticalAlignment.php
  packages/tables/resources/views/columns/layout/stack.blade.php
  packages/tables/resources/views/columns/text-input-column.blade.php
  packages/tables/resources/views/components/actions.blade.php
  packages/tables/resources/views/components/column-toggle/dropdown.blade.php
  packages/tables/resources/views/components/columns/column.blade.php
  packages/tables/resources/views/components/filters/dialog.blade.php
  packages/tables/resources/views/components/filters/indicators.blade.php
  packages/tables/resources/views/components/group/header.blade.php
  packages/tables/resources/views/components/groups.blade.php
  packages/tables/resources/views/components/header-cell.blade.php
  packages/tables/resources/views/components/reorder/cell.blade.php
  packages/tables/resources/views/components/summary/index.blade.php
  packages/tables/resources/views/components/summary/row.blade.php
  packages/tables/resources/views/index.blade.php
Labels: bug, ui

#9294 Optimize spatie tags table column query
  packages/spatie-laravel-tags-plugin/src/Tables/Columns/SpatieTagsColumn.php
Labels: bug

#9319 Update `km` translations
  packages/actions/resources/lang/km/associate.php
  packages/actions/resources/lang/km/attach.php
  packages/actions/resources/lang/km/create.php
  packages/actions/resources/lang/km/delete.php
  packages/actions/resources/lang/km/detach.php
  packages/actions/resources/lang/km/dissociate.php
  packages/actions/resources/lang/km/edit.php
  packages/actions/resources/lang/km/force-delete.php
  packages/actions/resources/lang/km/group.php
  packages/actions/resources/lang/km/modal.php
  packages/actions/resources/lang/km/replicate.php
  packages/actions/resources/lang/km/restore.php
  packages/actions/resources/lang/km/view.php
  packages/forms/resources/lang/km/components.php
  packages/infolists/resources/lang/km/components.php
  packages/notifications/resources/lang/km/database.php
  packages/panels/resources/lang/km/layout.php
  packages/panels/resources/lang/km/pages/auth/edit-profile.php
  packages/panels/resources/lang/km/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/km/pages/auth/login.php
  packages/panels/resources/lang/km/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/km/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/km/pages/auth/register.php
  packages/panels/resources/lang/km/pages/auth/tenancy/edit-tenant-profile.php
  packages/panels/resources/lang/km/resources/pages/edit-record.php
  packages/panels/resources/lang/km/resources/pages/view-record.php
  packages/spatie-laravel-settings-plugin/resources/lang/km/pages/settings-page.php
  packages/spatie-laravel-translatable-plugin/resources/lang/km/actions.php
  packages/support/resources/lang/km/components/button.php
  packages/support/resources/lang/km/components/copyable.php
  packages/support/resources/lang/km/components/modal.php
  packages/support/resources/lang/km/components/pagination.php
  packages/tables/resources/lang/km/table.php
Labels: i18n

#9311 Fix custom notification object
  packages/notifications/docs/05-customizing-notifications.md
  packages/notifications/src/Notification.php
  tests/src/Notifications/Fixtures/CustomNotification.php
  tests/src/Notifications/NotificationTest.php
Labels: bug

#9283 fix summerize count
  packages/tables/src/Columns/Summarizers/Count.php
Labels: bug

#9257 Fixes MorphToSelect afterStateUpdated, reactive and lazy.
  packages/forms/src/Components/MorphToSelect.php
  packages/forms/src/Concerns/HasStateBindingModifiers.php
Labels: bug

#9306 Fix empty action modal caused by validation exception
  packages/actions/src/Concerns/InteractsWithActions.php
  packages/forms/src/Concerns/HasFormComponentActions.php
  packages/infolists/src/Concerns/InteractsWithInfolists.php
  packages/tables/src/Concerns/HasActions.php
  packages/tables/src/Concerns/HasBulkActions.php
Labels: bug

#9291 feature: Allow table searches to include phrases when wrapped in doub…
  packages/tables/src/Concerns/CanSearchRecords.php
  tests/src/Tables/Concerns/CanSearchRecordsTest.php
Labels: enhancement

#9328 adding `fi-topnav` class
  packages/panels/resources/views/components/topbar/index.blade.php
Labels: enhancement

#8784 Fix issue 8487 reported in for postgresql queries on Integer and BigInteger columns
  packages/forms/src/Components/MorphToSelect/Type.php
  packages/forms/src/Components/Select.php
  packages/panels/src/Resources/Resource.php
  packages/spatie-laravel-translatable-plugin/src/SpatieLaravelTranslatableContentDriver.php
  packages/support/src/Contracts/TranslatableContentDriver.php
  packages/support/src/helpers.php
  packages/tables/src/Actions/AssociateAction.php
  packages/tables/src/Actions/AttachAction.php
  packages/tables/src/Columns/Concerns/CanBeSearchable.php
  packages/tables/src/Columns/Concerns/InteractsWithTableQuery.php
Labels: bug

#9252 Add docs on disabling lazy loading in relation managers
  packages/panels/docs/03-resources/07-relation-managers.md
  packages/panels/resources/views/components/resources/relation-managers.blade.php
  packages/panels/src/Resources/RelationManagers/RelationManager.php
  packages/widgets/resources/views/components/widgets.blade.php
Labels: enhancement

#9056 File upload improvements
  composer.lock
  packages/forms/dist/components/file-upload.js
  packages/forms/dist/index.css
  packages/forms/resources/css/components/file-upload.css
  packages/forms/resources/js/components/file-upload.js
  packages/forms/resources/lang/en/components.php
  packages/forms/resources/lang/sv/components.php
  packages/forms/resources/views/components/file-upload.blade.php
  packages/forms/src/Components/BaseFileUpload.php
  packages/forms/src/Components/FileUpload.php
  packages/panels/dist/theme.css
Labels: bug

#9332 Fixed front-end crush if title contains double quotes.
  packages/support/resources/views/components/icon-button.blade.php
Labels: bug

#9336 Update 19-custom.md entangling link
  packages/forms/docs/03-fields/19-custom.md
Labels: documentation

#9352 Make url optional for local font provider
  packages/panels/src/FontProviders/LocalFontProvider.php
Labels: enhancement

#9358 feature: Simple resource global search
  packages/actions/src/Concerns/InteractsWithActions.php
  packages/panels/resources/views/components/page/index.blade.php
  packages/panels/src/Resources/Resource.php
  packages/tables/src/Concerns/HasActions.php
Labels: enhancement

#9293 New table filters indicator API
  docs-assets/app/app/Livewire/TablesDemo.php
  packages/tables/docs/04-filters.md
  packages/tables/resources/views/components/filters/indicators.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Concerns/CanSearchRecords.php
  packages/tables/src/Contracts/HasTable.php
  packages/tables/src/Filters/Concerns/HasIndicators.php
  packages/tables/src/Filters/Filter.php
  packages/tables/src/Filters/Indicator.php
  packages/tables/src/Filters/SelectFilter.php
  packages/tables/src/Filters/TernaryFilter.php
  packages/tables/src/Filters/TrashedFilter.php
  packages/tables/src/Table.php
  packages/tables/src/Table/Concerns/CanSearchRecords.php
  packages/tables/src/Table/Concerns/HasFilterIndicators.php
Labels: documentation, enhancement

#9375 Tiny fix in pagination dropdown PR
  packages/support/resources/views/components/pagination/index.blade.php
Labels: bug

#9387 Reduce vertical space between sidebar navigation groups
  packages/panels/resources/views/components/sidebar/group.blade.php
  packages/panels/resources/views/components/sidebar/index.blade.php
Labels: enhancement, ui

#8461 Support additional repeater and builder actions
  packages/forms/docs/03-fields/12-repeater.md
  packages/forms/docs/03-fields/13-builder.md
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/repeater.blade.php
  packages/forms/src/Components/Builder.php
  packages/forms/src/Components/Concerns/HasActions.php
  packages/forms/src/Components/Concerns/HasExtraItemActions.php
  packages/forms/src/Components/Contracts/HasExtraItemActions.php
  packages/forms/src/Components/Repeater.php
  packages/support/src/Concerns/HasColor.php
Labels: enhancement, low priority
