Repository filamentphp/filament, pull requests merged in 2023-09, with the labels that each got.

#8199 Show input icons
  packages/support/resources/views/components/input/wrapper.blade.php
Labels: bug

#8167 Provide a configuration property to determine if remove uploaded file button is shown
  packages/forms/docs/03-fields/09-file-upload.md
  packages/forms/resources/js/components/file-upload.js
  packages/forms/resources/views/components/file-upload.blade.php
  packages/forms/src/Components/BaseFileUpload.php
Labels: enhancement

#8194 Allows Htmable content on Descriptions in a Checkboxlist
  docs-assets/app/app/Livewire/Forms/FieldsDemo.php
  docs-assets/app/app/Livewire/Infolists/EntriesDemo.php
  docs-assets/app/composer.lock
  docs-assets/app/package-lock.json
  docs-assets/app/public/css/filament/filament/app.css
  docs-assets/app/public/css/filament/forms/forms.css
  docs-assets/app/public/js/filament/forms/components/date-time-picker.js
  docs-assets/app/public/js/filament/notifications/notifications.js
  docs-assets/app/public/js/filament/support/support.js
  docs-assets/app/public/js/filament/widgets/components/stats-overview/stat/chart.js
  docs-assets/screenshots/images/dark/forms/fields/checkbox-list/option-descriptions.jpg
  docs-assets/screenshots/images/light/forms/fields/checkbox-list/option-descriptions.jpg
  packages/forms/docs/03-fields/01-getting-started.md
  packages/forms/docs/03-fields/06-checkbox-list.md
  packages/forms/src/Components/CheckboxList.php
  packages/forms/src/Components/Radio.php
  packages/infolists/docs/03-entries/01-getting-started.md
Labels: enhancement

#8209 non-native date-picker month dropdown dark mode
  packages/forms/resources/views/components/date-time-picker.blade.php
Labels: bug, ui

#8181 [v2.x-forms] Fixes `CheckboxList`'s `->afterStateUpdated()` lifecycle hook
  packages/forms/resources/views/components/checkbox-list.blade.php
Labels: bug

#8217 Fix `Group::configureUsing()` not working
  packages/forms/src/ComponentContainer.php
  packages/forms/src/Components/Actions.php
  packages/forms/src/Components/Actions/ActionContainer.php
  packages/forms/src/Components/View.php
  packages/infolists/src/ComponentContainer.php
  packages/infolists/src/Components/Actions.php
  packages/infolists/src/Components/Actions/ActionContainer.php
  packages/infolists/src/Components/View.php
  packages/panels/src/Navigation/MenuItem.php
  packages/panels/src/Navigation/NavigationGroup.php
  packages/panels/src/Navigation/NavigationItem.php
  packages/tables/src/Columns/Layout/View.php
  packages/tables/src/Grouping/Group.php
Labels: bug

#8220 Add Nepali language translations
  packages/actions/resources/lang/np/associate.php
  packages/actions/resources/lang/np/attach.php
  packages/actions/resources/lang/np/create.php
  packages/actions/resources/lang/np/delete.php
  packages/actions/resources/lang/np/detach.php
  packages/actions/resources/lang/np/dissociate.php
  packages/actions/resources/lang/np/edit.php
  packages/actions/resources/lang/np/force-delete.php
  packages/actions/resources/lang/np/group.php
  packages/actions/resources/lang/np/modal.php
  packages/actions/resources/lang/np/replicate.php
  packages/actions/resources/lang/np/restore.php
  packages/actions/resources/lang/np/view.php
  packages/forms/resources/lang/np/components.php
  packages/infolists/resources/lang/np/components.php
  packages/notifications/resources/lang/np/database.php
  packages/panels/resources/lang/np/global-search.php
  packages/panels/resources/lang/np/layout.php
  packages/panels/resources/lang/np/pages/auth/edit-profile.php
  packages/panels/resources/lang/np/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/np/pages/auth/login.php
  packages/panels/resources/lang/np/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/np/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/np/pages/auth/register.php
  packages/panels/resources/lang/np/pages/dashboard.php
  packages/panels/resources/lang/np/pages/tenancy/edit-tenant-profile.php
  packages/panels/resources/lang/np/resources/pages/create-record.php
  packages/panels/resources/lang/np/resources/pages/edit-record.php
  packages/panels/resources/lang/np/resources/pages/list-records.php
  packages/panels/resources/lang/np/resources/pages/view-record.php
  packages/panels/resources/lang/np/widgets/account-widget.php
  packages/panels/resources/lang/np/widgets/filament-info-widget.php
  packages/spatie-laravel-settings-plugin/resources/lang/np/pages/settings-page.php
  packages/spatie-laravel-translatable-plugin/resources/lang/np/actions.php
  packages/support/resources/lang/np/components/button.php
  packages/support/resources/lang/np/components/copyable.php
  packages/support/resources/lang/np/components/modal.php
  packages/support/resources/lang/np/components/pagination.php
  packages/tables/resources/lang/np/table.php
Labels: i18n

#8226 fix: convert column to string
  packages/tables/src/Columns/Concerns/CanBeSearchable.php
Labels: bug

#8230 [Plugin] MediaLibrary: Honor order_column sort order when media is reorderable
  packages/spatie-laravel-media-library-plugin/src/Infolists/Components/SpatieMediaLibraryImageEntry.php
  packages/spatie-laravel-media-library-plugin/src/Tables/Columns/SpatieMediaLibraryImageColumn.php
Labels: bug

#8243 Fix grouping direction being reset when called programatically
  packages/tables/resources/views/components/groups.blade.php
Labels: bug

#8266 Always register the about data
  packages/support/src/SupportServiceProvider.php
Labels: bug

#8287 Add actions to table widgets
  packages/widgets/src/TableWidget.php
Labels: enhancement

#8290 Improve vi translations
  packages/actions/resources/lang/vi/associate.php
  packages/actions/resources/lang/vi/attach.php
  packages/actions/resources/lang/vi/create.php
  packages/actions/resources/lang/vi/detach.php
  packages/actions/resources/lang/vi/edit.php
  packages/actions/resources/lang/vi/force-delete.php
  packages/actions/resources/lang/vi/modal.php
  packages/actions/resources/lang/vi/replicate.php
  packages/actions/resources/lang/vi/restore.php
  packages/forms/resources/lang/vi/components.php
  packages/infolists/resources/lang/vi/components.php
  packages/notifications/resources/lang/vi/database.php
  packages/panels/resources/lang/vi/layout.php
  packages/panels/resources/lang/vi/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/vi/pages/auth/register.php
  packages/panels/resources/lang/vi/resources/pages/create-record.php
  packages/panels/resources/lang/vi/widgets/account-widget.php
  packages/spatie-laravel-settings-plugin/resources/lang/vi/pages/settings-page.php
  packages/support/resources/lang/vi/components/pagination.php
  packages/tables/resources/lang/vi/table.php
Labels: i18n

#8297 Docs - remove the Post model
  packages/tables/docs/11-adding-a-table-to-a-livewire-component.md
Labels: documentation

#8303 update hu-HU translations
  packages/actions/resources/lang/hu/delete.php
  packages/actions/resources/lang/hu/detach.php
  packages/actions/resources/lang/hu/dissociate.php
  packages/actions/resources/lang/hu/force-delete.php
  packages/actions/resources/lang/hu/restore.php
  packages/forms/resources/lang/hu/components.php
  packages/panels/resources/lang/hu/layout.php
  packages/panels/resources/lang/hu/pages/auth/login.php
  packages/panels/resources/lang/hu/resources/pages/create-record.php
  packages/support/resources/lang/hu/components/pagination.php
  packages/tables/resources/lang/hu/table.php
Labels: i18n

#8309 Update id translations
  packages/panels/resources/lang/id/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/id/pages/auth/login.php
  packages/panels/resources/lang/id/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/id/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/id/pages/auth/register.php
  packages/tables/resources/lang/id/table.php
Labels: i18n

#8203 updade pt-BR translations
  packages/actions/resources/lang/pt_BR/create.php
  packages/forms/resources/lang/pt_BR/components.php
Labels: i18n

#8305 Fixed where clause for MariaDB compatibility
  packages/notifications/src/Livewire/DatabaseNotifications.php
Labels: bug, needs more info

#8312 Update 10-tenancy.md
  packages/panels/docs/10-tenancy.md
Labels: documentation

#8316 Fix input/select/checkbox columns state update
  packages/tables/resources/views/columns/checkbox-column.blade.php
  packages/tables/resources/views/columns/select-column.blade.php
  packages/tables/resources/views/columns/text-input-column.blade.php
Labels: bug, bug in dependency

#8335 Add missing Theme Switch Translation for Turkish
  packages/panels/resources/lang/tr/layout.php
Labels: i18n

#8343 [Spatie Media Library] fallback to original file when conversion does not exist
  packages/spatie-laravel-media-library-plugin/src/Infolists/Components/SpatieMediaLibraryImageEntry.php
  packages/spatie-laravel-media-library-plugin/src/Tables/Columns/SpatieMediaLibraryImageColumn.php
Labels: bug

#8327 Add ability to set the default active tab
  packages/panels/docs/03-resources/02-listing-records.md
  packages/panels/src/Resources/Pages/ListRecords.php
Labels: enhancement

#8334 Update 11-themes.md
  packages/panels/docs/11-themes.md
Labels: documentation

#8356 Add missing Theme Switcher Translation for German
  packages/panels/resources/lang/de/layout.php
Labels: i18n

#8235 Add ability to disable CheckboxList option
  packages/forms/docs/03-fields/06-checkbox-list.md
  packages/forms/resources/views/components/checkbox-list.blade.php
  packages/forms/src/Components/CheckboxList.php
Labels: enhancement, low priority

#8233 Handle user login attemp on unauthorized panel
  packages/panels/src/Pages/Auth/Login.php
  tests/src/CustomPanelProvider.php
  tests/src/Models/User.php
  tests/src/Panels/Auth/LoginTest.php
  tests/src/TestCase.php
Labels: enhancement

#7774 Improve profile page actions layout
  packages/actions/resources/views/components/actions.blade.php
  packages/panels/resources/lang/ar/pages/auth/edit-profile.php
  packages/panels/resources/lang/ckb/pages/auth/edit-profile.php
  packages/panels/resources/lang/en/pages/auth/edit-profile.php
  packages/panels/resources/lang/es/pages/auth/edit-profile.php
  packages/panels/resources/lang/fa/pages/auth/edit-profile.php
  packages/panels/resources/lang/fi/pages/auth/edit-profile.php
  packages/panels/resources/lang/fr/pages/auth/edit-profile.php
  packages/panels/resources/lang/he/pages/auth/edit-profile.php
  packages/panels/resources/lang/hu/pages/auth/edit-profile.php
  packages/panels/resources/lang/id/pages/auth/edit-profile.php
  packages/panels/resources/lang/it/pages/auth/edit-profile.php
  packages/panels/resources/lang/ku/pages/auth/edit-profile.php
  packages/panels/resources/lang/lt/pages/auth/edit-profile.php
  packages/panels/resources/lang/ms/pages/auth/edit-profile.php
  packages/panels/resources/lang/nl/pages/auth/edit-profile.php
  packages/panels/resources/lang/no/pages/auth/edit-profile.php
  packages/panels/resources/lang/np/pages/auth/edit-profile.php
  packages/panels/resources/lang/pl/pages/auth/edit-profile.php
  packages/panels/resources/lang/pt_BR/pages/auth/edit-profile.php
  packages/panels/resources/lang/ro/pages/auth/edit-profile.php
  packages/panels/resources/lang/ru/pages/auth/edit-profile.php
  packages/panels/resources/lang/vi/pages/auth/edit-profile.php
  packages/panels/resources/views/pages/auth/edit-profile.blade.php
  packages/panels/src/Pages/Auth/EditProfile.php
  packages/panels/src/Pages/BasePage.php
  packages/support/src/Enums/Alignment.php
  tests/src/CustomPanelProvider.php
Labels: enhancement, ui, high priority

#8144 Provide configuration to SpatieTagsInput to allow original behaviour of suggestions for tags with types
  packages/spatie-laravel-tags-plugin/src/Forms/Components/SpatieTagsInput.php
  packages/spatie-laravel-tags-plugin/src/Infolists/Components/SpatieTagsEntry.php
  packages/spatie-laravel-tags-plugin/src/SpatieLaravelTagsPlugin/Types/AllTagTypes.php
  packages/spatie-laravel-tags-plugin/src/Tables/Columns/SpatieTagsColumn.php
Labels: enhancement, high priority

#8193 Further improvements on textarea
  package-lock.json
  package.json
  packages/forms/dist/components/textarea.js
  packages/forms/dist/index.js
  packages/forms/resources/js/components/textarea.js
  packages/forms/resources/js/index.js
  packages/forms/resources/views/components/textarea.blade.php
Labels: bug

#8366 Update 05-dashboard.md
  packages/panels/docs/05-dashboard.md
Labels: documentation

#8369 Allow passing through badge color prop in `tabs.item`
  packages/support/resources/views/components/tabs/item.blade.php
Labels: enhancement

#7657 [Docs] Correct example showing the record passed in as param
  packages/actions/docs/04-modals.md
  packages/actions/docs/07-prebuilt-actions/01-create.md
  packages/actions/docs/07-prebuilt-actions/02-edit.md
  packages/actions/docs/07-prebuilt-actions/05-replicate.md
  packages/forms/docs/04-layout/07-placeholder.md
  packages/panels/docs/04-pages.md
Labels: documentation

#7439 fix: text column placeholder
  docs-assets/app/app/Livewire/Infolists/EntriesDemo.php
  docs-assets/app/app/Livewire/TablesDemo.php
  docs-assets/app/database/database.sqlite
  docs-assets/screenshots/images/dark/infolists/entries/placeholder.jpg
  docs-assets/screenshots/images/dark/tables/columns/placeholder.jpg
  docs-assets/screenshots/images/light/infolists/entries/placeholder.jpg
  docs-assets/screenshots/images/light/tables/columns/placeholder.jpg
  docs-assets/screenshots/schema.js
  packages/infolists/docs/03-entries/01-getting-started.md
  packages/infolists/docs/03-entries/02-text.md
  packages/infolists/resources/views/components/color-entry.blade.php
  packages/infolists/resources/views/components/entries/placeholder.blade.php
  packages/infolists/resources/views/components/icon-entry.blade.php
  packages/infolists/resources/views/components/image-entry.blade.php
  packages/infolists/resources/views/components/repeatable-entry.blade.php
  packages/infolists/resources/views/components/text-entry.blade.php
  packages/infolists/src/Components/Concerns/CanFormatState.php
  packages/infolists/src/Components/Concerns/HasState.php
  packages/infolists/src/Components/Entry.php
  packages/support/src/Concerns/HasPlaceholder.php
  packages/tables/docs/03-columns/01-getting-started.md
  packages/tables/docs/03-columns/02-text.md
  packages/tables/resources/views/columns/color-column.blade.php
  packages/tables/resources/views/columns/icon-column.blade.php
  packages/tables/resources/views/columns/image-column.blade.php
  packages/tables/resources/views/columns/text-column.blade.php
  packages/tables/resources/views/components/columns/placeholder.blade.php
  packages/tables/src/Columns/Column.php
  packages/tables/src/Columns/Concerns/CanFormatState.php
  packages/tables/src/Columns/Concerns/HasState.php
  packages/tables/src/Columns/SelectColumn.php
  packages/tables/src/Columns/TextInputColumn.php
Labels: bug

#8116 Fix collapsed sidebar icons when scrollbars are present
  packages/panels/resources/views/components/layout/base.blade.php
  packages/panels/resources/views/components/layout/index.blade.php
  packages/panels/resources/views/components/sidebar/index.blade.php
Labels: bug, ui

#7772 Fix double table border when no sorting or selection is enabled
  packages/tables/resources/views/index.blade.php
Labels: bug, ui

#7738 Add a new section to Tenancy docs about non-Filament tenancy
  packages/panels/docs/10-tenancy.md
Labels: documentation

#8026 Fix support for BelongsToThrough relationships in Select/SelectFilter
  packages/forms/src/Components/Select.php
  packages/tables/src/Filters/SelectFilter.php
Labels: bug

#8377 Add viewData example to docs
  packages/forms/docs/03-fields/19-custom.md
Labels: documentation

#8379 MenuItem Component allow url to be open in new Tab function
  packages/panels/resources/views/components/sidebar/group.blade.php
  packages/panels/resources/views/components/tenant-menu.blade.php
  packages/panels/resources/views/components/user-menu.blade.php
  packages/panels/src/Navigation/MenuItem.php
  packages/panels/src/Navigation/NavigationItem.php
  packages/support/resources/views/components/dropdown/list/item.blade.php
  packages/widgets/src/StatsOverviewWidget/Stat.php
Labels: enhancement

#7197 Re-introduce wire:navigate (SPA mode)
  packages/infolists/resources/views/components/entry-wrapper/index.blade.php
  packages/panels/docs/09-configuration.md
  packages/panels/resources/views/components/global-search/result.blade.php
  packages/panels/resources/views/components/layout/base.blade.php
  packages/panels/resources/views/components/sidebar/index.blade.php
  packages/panels/resources/views/components/sidebar/item.blade.php
  packages/panels/resources/views/components/tenant-menu.blade.php
  packages/panels/resources/views/components/topbar/index.blade.php
  packages/panels/resources/views/components/topbar/item.blade.php
  packages/panels/resources/views/components/user-menu.blade.php
  packages/panels/src/Panel.php
  packages/panels/src/Panel/Concerns/HasSpaMode.php
  packages/panels/src/helpers.php
  packages/support/resources/views/components/breadcrumbs.blade.php
  packages/support/resources/views/components/button/index.blade.php
  packages/support/resources/views/components/dropdown/list/item.blade.php
  packages/support/resources/views/components/icon-button.blade.php
  packages/support/resources/views/components/link.blade.php
  packages/support/resources/views/components/tabs/item.blade.php
  packages/support/src/Facades/FilamentView.php
  packages/support/src/View/ViewManager.php
  packages/support/src/helpers.php
  packages/tables/resources/views/components/columns/column.blade.php
  packages/tables/resources/views/index.blade.php
  packages/widgets/resources/views/stats-overview-widget/stat.blade.php
  tests/src/Support/SpaModeTest.php
Labels: enhancement

#8383 fix: Disabled toggle
  packages/forms/resources/views/components/toggle.blade.php
Labels: bug

#8384 Fix repeater collapse file upload
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/repeater.blade.php
Labels: bug

#8386 fix: Key value
  packages/forms/dist/components/key-value.js
  packages/forms/resources/js/components/key-value.js
Labels: bug

#8394 Bulk-select group and fix date-grouped summaries
  bin/build.js
  packages/forms/src/FormsServiceProvider.php
  packages/tables/dist/components/table.js
  packages/tables/docs/08-grouping.md
  packages/tables/resources/js/components/table.js
  packages/tables/resources/lang/en/table.php
  packages/tables/resources/views/components/group/header.blade.php
  packages/tables/resources/views/components/selection/group-cell.blade.php
  packages/tables/resources/views/components/selection/group-checkbox.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Concerns/CanSummarizeRecords.php
  packages/tables/src/Concerns/HasBulkActions.php
  packages/tables/src/Grouping/Group.php
  packages/tables/src/TablesServiceProvider.php
Labels: enhancement

#8389 chore(i18n): missing persian translation for tenancy
  packages/panels/resources/lang/fa/pages/tenancy/edit-tenant-profile.php
Labels: i18n

#8396 fix: Nested infolist actions
  packages/actions/resources/views/components/modals.blade.php
  packages/actions/src/Action.php
  packages/actions/src/Concerns/HasInfolist.php
  packages/actions/src/Concerns/InteractsWithActions.php
  packages/actions/src/MountableAction.php
  packages/forms/src/Components/Actions/Action.php
  packages/forms/src/Concerns/InteractsWithForms.php
  packages/infolists/src/Concerns/InteractsWithInfolists.php
  packages/panels/src/Pages/BasePage.php
  packages/panels/src/Resources/Pages/ListRecords.php
  packages/panels/src/Resources/Pages/ViewRecord.php
  packages/panels/src/Resources/RelationManagers/RelationManager.php
  packages/tables/resources/views/components/selection/group-checkbox.blade.php
  packages/tables/src/Actions/Action.php
  packages/tables/src/Actions/BulkAction.php
  packages/tables/src/Concerns/HasActions.php
  packages/tables/src/Concerns/HasBulkActions.php
  packages/widgets/src/TableWidget.php
Labels: bug

#8399 fix: Filter columns defaults
  packages/tables/src/Table/Concerns/HasFilters.php
Labels: bug

#8405 fix: Repeater reorder
  packages/forms/src/Components/Repeater.php
Labels: bug

#8402 [DOCS] Update livewire views in getting started
  packages/forms/docs/08-adding-a-form-to-a-livewire-component.md
  packages/tables/docs/11-adding-a-table-to-a-livewire-component.md
Labels: documentation

#8406 Fix type of tag isn't handled correctly
  packages/spatie-laravel-tags-plugin/src/Forms/Components/SpatieTagsInput.php
Labels: bug

#8409 fix: Cache list tabs
  packages/panels/resources/views/resources/pages/list-records.blade.php
  packages/panels/src/Resources/Pages/ListRecords.php
Labels: bug

#8425 fix: Spatie tags sync
  packages/spatie-laravel-tags-plugin/src/Forms/Components/SpatieTagsInput.php
Labels: bug

#8436 Fix ToggleColumn with icons
  packages/tables/resources/views/columns/toggle-column.blade.php
Labels: bug

#8446 Fixed bug in tags-input.js
  packages/forms/dist/components/tags-input.js
  packages/forms/resources/js/components/tags-input.js
Labels: bug

#8447 Fix pagination overlap
  packages/panels/dist/theme.css
  packages/support/resources/views/components/pagination/index.blade.php
Labels: bug

#8449 fix withoutRouteMiddleware in missing routes
  packages/panels/src/Pages/Auth/EditProfile.php
  packages/panels/src/Pages/Dashboard.php
  packages/panels/src/Pages/Tenancy/EditTenantProfile.php
  packages/panels/src/Pages/Tenancy/RegisterTenant.php
  packages/panels/src/Resources/Pages/Page.php
Labels: bug

#8462 [Doc] Function getDefaultTenant() need $panel argument
  packages/panels/docs/10-tenancy.md
Labels: documentation

#8432 spatie-laravel-translatable-plugin - Fix media bug
  packages/spatie-laravel-translatable-plugin/src/Resources/Pages/EditRecord/Concerns/Translatable.php
Labels: bug

#8491 feature: Register LW components from panel
  packages/panels/src/Panel/Concerns/HasComponents.php
Labels: enhancement

#8492 fix: Persistent middleware
  packages/panels/src/FilamentManager.php
  packages/panels/src/Panel.php
Labels: bug

#8494 feature: Disable read only relation managers for entire panel at once
  packages/panels/docs/03-resources/07-relation-managers.md
  packages/panels/src/Panel/Concerns/HasComponents.php
  packages/panels/src/Resources/RelationManagers/RelationManager.php
Labels: enhancement

#8495 fix: Relation manager not showing after being toggled visible
  packages/panels/resources/views/resources/pages/edit-record.blade.php
Labels: bug

#8499 Fix: misaligned page options when only one page of results
  packages/panels/resources/views/components/sidebar/index.blade.php
  packages/support/resources/views/components/pagination/index.blade.php
Labels: bug, ui

#8514 Default AboveContentCollapsible to hidden to avoid flickering
  packages/tables/resources/views/index.blade.php
Labels: bug

#8503 fix: Ensure routeMiddleware property is array before unpacking
  packages/panels/src/Pages/Auth/EditProfile.php
  packages/panels/src/Pages/Concerns/HasRoutes.php
  packages/panels/src/Pages/Tenancy/EditTenantProfile.php
  packages/panels/src/Pages/Tenancy/RegisterTenant.php
Labels: bug

#8519 fix: Combined relation managers
  packages/panels/resources/views/components/resources/relation-managers.blade.php
  packages/panels/resources/views/resources/pages/edit-record.blade.php
  packages/panels/resources/views/resources/pages/view-record.blade.php
Labels: bug

#8511 Workaround for apparent LW3/Alpine bug in section
  packages/support/resources/views/components/section.blade.php
Labels: bug

#8520 fix: Repeater defaults
  packages/forms/src/Components/Repeater.php
Labels: bug

#8531 Show how to change default "per page" pagination value
  packages/tables/docs/10-advanced.md
Labels: documentation

#8518 Fix darkmode text color
  packages/support/resources/views/components/fieldset.blade.php
  packages/tables/resources/views/components/header.blade.php
Labels: ui

#8532 Fix missing ms translation
  packages/tables/resources/lang/ms/table.php
Labels: i18n

#8535 fix: rowIndex() with all pagination
  packages/tables/src/Columns/TextColumn.php
Labels: bug

#8544 Fixed docs
  packages/panels/docs/04-pages.md
Labels: documentation, pending changes

#8551 Update zh_CN translation
  packages/infolists/resources/lang/zh_CN/components.php
  packages/notifications/resources/lang/zh_CN/database.php
  packages/panels/resources/lang/zh_CN/layout.php
  packages/panels/resources/lang/zh_CN/pages/auth/edit-profile.php
  packages/panels/resources/lang/zh_CN/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/zh_CN/pages/auth/login.php
  packages/panels/resources/lang/zh_CN/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/zh_CN/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/zh_CN/pages/auth/register.php
  packages/panels/resources/lang/zh_CN/pages/tenancy/edit-tenant-profile.php
  packages/panels/resources/lang/zh_CN/resources/pages/view-record.php
  packages/support/resources/lang/zh_CN/components/button.php
  packages/support/resources/lang/zh_CN/components/copyable.php
  packages/support/resources/lang/zh_CN/components/modal.php
  packages/support/resources/lang/zh_CN/components/pagination.php
  packages/tables/resources/lang/zh_CN/table.php
Labels: i18n

#8564 Fix type
  packages/tables/src/Table/Concerns/HasHeaderActions.php
Labels: bug

#8567 Update helpers.php
  packages/support/src/helpers.php
  tests/src/Support/SpaModeTest.php
Labels: bug

#8475 Add renderhooks to the table builder toolbar
  packages/support/docs/06-render-hooks.md
  packages/tables/resources/views/index.blade.php
Labels: enhancement

#8498 Add renderhooks before and after the table widget
  packages/support/docs/06-render-hooks.md
  packages/widgets/resources/views/table-widget.blade.php
Labels: enhancement

#8128 Shades registration
  packages/forms/resources/views/components/field-wrapper/hint.blade.php
  packages/forms/resources/views/components/toggle.blade.php
  packages/infolists/resources/views/components/entry-wrapper/hint.blade.php
  packages/infolists/resources/views/components/icon-entry.blade.php
  packages/infolists/resources/views/components/text-entry.blade.php
  packages/notifications/resources/views/components/icon.blade.php
  packages/notifications/resources/views/notification.blade.php
  packages/support/docs/08-plugins/03-build-a-standalone-plugin.md
  packages/support/resources/views/components/badge.blade.php
  packages/support/resources/views/components/button/index.blade.php
  packages/support/resources/views/components/dropdown/list/item.blade.php
  packages/support/resources/views/components/icon-button.blade.php
  packages/support/resources/views/components/link.blade.php
  packages/support/resources/views/components/modal/index.blade.php
  packages/support/resources/views/components/section.blade.php
  packages/support/src/Colors/ColorManager.php
  packages/support/src/Facades/FilamentColor.php
  packages/support/src/helpers.php
  packages/tables/resources/views/columns/icon-column.blade.php
  packages/tables/resources/views/columns/summaries/icon-count.blade.php
  packages/tables/resources/views/columns/text-column.blade.php
  packages/tables/resources/views/columns/toggle-column.blade.php
  packages/widgets/resources/views/chart-widget.blade.php
  packages/widgets/resources/views/stats-overview-widget/stat.blade.php
Labels: enhancement, ui

#8540 [3.x] Use qualified name
  packages/tables/src/Actions/AssociateAction.php
  packages/tables/src/Actions/AttachAction.php
Labels: bug

#8557 Fix live predefined actions for repeater and builder field form
  packages/forms/src/Components/Builder.php
  packages/forms/src/Components/Repeater.php
Labels: bug

#8558 Add `brandLogo` API
  packages/panels/docs/11-themes.md
  packages/panels/resources/views/components/logo.blade.php
  packages/panels/src/Facades/Filament.php
  packages/panels/src/FilamentManager.php
  packages/panels/src/Panel.php
  packages/panels/src/Panel/Concerns/HasBrandLogo.php
Labels: enhancement

#8570 Update 08-grouping.md
  packages/tables/docs/08-grouping.md
Labels: documentation

#8539 Added a badgeColor to the ListRecords Tab Component
  packages/actions/src/ActionGroup.php
  packages/actions/src/StaticAction.php
  packages/panels/docs/03-resources/02-listing-records.md
  packages/panels/resources/views/resources/pages/list-records.blade.php
  packages/panels/src/Resources/Pages/ListRecords/Tab.php
  packages/support/src/Concerns/HasBadge.php
Labels: enhancement

#8541 Doc: update widget doc to Livewire v3 format
  packages/widgets/docs/02-stats-overview.md
Labels: documentation

#8578 Update finnish translation
  packages/tables/resources/lang/fi/table.php
Labels: i18n

#8583 Fixed wrong comma in the docs
  packages/forms/docs/03-fields/13-builder.md
Labels: documentation

#8584 Docs - repeater
  packages/forms/docs/03-fields/12-repeater.md
Labels: documentation

#8588 [Docs] Fix typo in Forms hint() example
  packages/forms/docs/03-fields/01-getting-started.md
Labels: documentation

#8589 Dispatch upgraded event after update
  packages/support/src/Commands/UpgradeCommand.php
  packages/support/src/Events/FilamentUpgraded.php
Labels: enhancement

#8599 Panels: Add Dutch tenant translations
  packages/panels/resources/lang/nl/pages/tenancy/edit-tenant-profile.php
Labels: i18n

#8601 docs: correct identifier for modifyRuleUsing
  packages/forms/docs/05-validation.md
Labels: documentation

#8609 Fix pagination layout
  packages/support/resources/views/components/pagination/index.blade.php
Labels: bug, ui

#8607 Allow panels to be used for unauthenticated users.
  packages/panels/resources/views/components/topbar/index.blade.php
Labels: enhancement

#8617 Improve `ar` translation
  packages/tables/resources/lang/ar/table.php
Labels: i18n

#8623 Ignore collapsible sidebar CSS when top navigation is enabled.
  packages/panels/resources/views/components/sidebar/index.blade.php
Labels: ui

#8626 Remove toggle column start margin
  packages/tables/resources/views/columns/toggle-column.blade.php
Labels: bug, ui

#8624 Constraint order values
  packages/tables/src/Concerns/CanGroupRecords.php
Labels: bug

#8620 Translatable plugin docs: making a model translatable
  packages/spatie-laravel-translatable-plugin/README.md
Labels: documentation

#8640 Fix/make form action label translatable and add German translation for button and notification
  packages/panels/resources/lang/de/pages/tenancy/edit-tenant-profile.php
Labels: i18n

#8645 Update 04-pages.md
  packages/panels/docs/04-pages.md
Labels: documentation

#8650 Add missing `ar` translations
  packages/tables/resources/lang/ar/table.php
Labels: i18n

#8652 beta-feature: Resource sub-navigation
  packages/panels/dist/theme.css
  packages/panels/docs/03-resources/07-relation-managers.md
  packages/panels/resources/views/components/page/index.blade.php
  packages/panels/resources/views/components/resources/tabs.blade.php
  packages/panels/resources/views/resources/pages/list-records.blade.php
  packages/panels/resources/views/resources/pages/manage-related-records.blade.php
  packages/panels/resources/views/resources/relation-manager.blade.php
  packages/panels/src/Pages/Concerns/HasSubNavigation.php
  packages/panels/src/Pages/Page.php
  packages/panels/src/Resources/Components/Tab.php
  packages/panels/src/Resources/Concerns/HasTabs.php
  packages/panels/src/Resources/Concerns/InteractsWithRelationshipTable.php
  packages/panels/src/Resources/Pages/EditRecord.php
  packages/panels/src/Resources/Pages/ListRecords.php
  packages/panels/src/Resources/Pages/ListRecords/Tab.php
  packages/panels/src/Resources/Pages/ManageRelatedRecords.php
  packages/panels/src/Resources/Pages/Page.php
  packages/panels/src/Resources/Pages/ViewRecord.php
  packages/panels/src/Resources/RelationManagers/RelationManager.php
  packages/panels/src/Resources/Resource.php
  packages/support/dist/index.js
Labels: enhancement

#8591 Tables: BulkActions - Fix getSelectedTableRecords query to include filters.
  packages/tables/src/Concerns/HasBulkActions.php
Labels: bug, pending changes

#8662 Fix broken cross-links in plugin docs
  packages/support/docs/08-plugins/01-getting-started.md
  packages/support/docs/08-plugins/02-build-a-panel-plugin.md
  packages/support/docs/08-plugins/03-build-a-standalone-plugin.md
Labels: documentation

#8669 Fix docs typo
  packages/tables/docs/06-layout.md
Labels: documentation

#8676 Fix "voltar" translation case
  packages/panels/resources/lang/pt_BR/pages/auth/edit-profile.php
Labels: i18n

#8684 Rich editor underline hover title
  packages/forms/docs/03-fields/10-rich-editor.md
  packages/forms/resources/views/components/rich-editor.blade.php
Labels: bug

#8678 Fix wizard with hidden steps
  packages/forms/src/Components/Wizard.php
Labels: bug

#8683 Add advice about caching icons to Deploying section.
  packages/panels/docs/01-installation.md
Labels: documentation

#8670 Add color classes
  packages/forms/resources/views/components/field-wrapper/hint.blade.php
  packages/forms/resources/views/components/toggle.blade.php
  packages/infolists/resources/views/components/entry-wrapper/hint.blade.php
  packages/infolists/resources/views/components/icon-entry.blade.php
  packages/infolists/resources/views/components/text-entry.blade.php
  packages/notifications/resources/views/components/icon.blade.php
  packages/notifications/resources/views/notification.blade.php
  packages/panels/resources/views/components/sidebar/item.blade.php
  packages/support/resources/views/components/badge.blade.php
  packages/support/resources/views/components/button/index.blade.php
  packages/support/resources/views/components/dropdown/header.blade.php
  packages/support/resources/views/components/dropdown/list/item.blade.php
  packages/support/resources/views/components/icon-button.blade.php
  packages/support/resources/views/components/link.blade.php
  packages/support/resources/views/components/modal/index.blade.php
  packages/support/resources/views/components/section.blade.php
  packages/support/resources/views/components/tabs/item.blade.php
  packages/support/src/Enums/ActionSize.php
  packages/tables/resources/views/columns/icon-column.blade.php
  packages/tables/resources/views/columns/summaries/icon-count.blade.php
  packages/tables/resources/views/columns/text-column.blade.php
  packages/tables/resources/views/columns/toggle-column.blade.php
  packages/widgets/resources/views/chart-widget.blade.php
  packages/widgets/resources/views/stats-overview-widget/stat.blade.php
Labels: enhancement

#8709 Add missing language files (German)
  packages/infolists/resources/lang/de/components.php
  packages/panels/resources/lang/de/pages/auth/edit-profile.php
Labels: i18n

#8696 Fix getLivewireClickHandler() method not generating the parameters right
  packages/actions/src/StaticAction.php
Labels: bug

#8739 Update Norwegian translations
  packages/actions/resources/lang/no/modal.php
  packages/support/resources/lang/no/components/pagination.php
  packages/tables/resources/lang/no/table.php
Labels: i18n

#8750 Add CSS hook class to table group header
  packages/tables/resources/views/components/group/header.blade.php
Labels: enhancement

#8759 Fix link Blade component docs
  packages/support/docs/09-blade-components/02-link.md
Labels: documentation

#8768 Qualify key name in getSelectedRecordUsing()
  packages/forms/src/Components/Select.php
Labels: bug

#8786 Update 02-listing-records.md to use new Tab class
  packages/panels/docs/03-resources/02-listing-records.md
Labels: documentation

#8793 Fix docs: Update variable name to match where used
  packages/forms/docs/09-testing.md
Labels: documentation

#8777 Introduce a way to customise how the global search attributes columns are search
  packages/panels/src/Resources/Resource.php
Labels: enhancement

#8746 Support custom email verification middleware
  packages/panels/src/Panel/Concerns/HasAuth.php
Labels: enhancement

#8747 Fix for Repeater custom view
  packages/forms/src/Components/Repeater.php
Labels: bug

#8791 Add dropdown indicator to topbar items
  packages/panels/resources/views/components/topbar/item.blade.php
Labels: enhancement, ui, low priority

#8798 Improved fa translation
  packages/panels/resources/lang/fa/pages/auth/edit-profile.php
  packages/panels/resources/lang/fa/pages/auth/register.php
Labels: i18n
