Repository filamentphp/filament, pull requests merged in 2023-08, with the labels that each got.

#7332 Update 01-installation.md
  packages/actions/docs/01-installation.md
Labels: documentation

#7334 Update 01-installation.md
  packages/infolists/docs/01-installation.md
Labels: documentation

#7333 Update 01-installation.md
  packages/widgets/docs/01-installation.md
Labels: documentation

#7314 Update 01-installation.md
  packages/notifications/docs/01-installation.md
Labels: documentation

#7313 Update 01-installation.md
  packages/tables/docs/01-installation.md
Labels: documentation

#7308 Update 01-installation.md
  packages/forms/docs/01-installation.md
Labels: documentation

#7300 Update 01-installation.md
  packages/panels/docs/01-installation.md
Labels: documentation

#7330 Allow relative links in HtmlSantizer
  packages/support/src/SupportServiceProvider.php
Labels: enhancement

#7336 add/update translations missing for Russian
  packages/panels/resources/lang/ru/layout.php
  packages/panels/resources/lang/ru/pages/auth/edit-profile.php
  packages/panels/resources/lang/ru/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/ru/pages/auth/login.php
  packages/panels/resources/lang/ru/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/ru/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/ru/pages/auth/register.php
  packages/panels/resources/lang/ru/pages/tenancy/edit-tenant-profile.php
Labels: i18n

#7341 Tiny typo fix
  packages/support/docs/08-plugins/03-build-a-standalone-plugin.md
Labels: documentation

#7339 Increase maxInputLength again
  packages/support/src/SupportServiceProvider.php
Labels: enhancement

#7358 fixed link to Spatie media-library plugin
  packages/forms/docs/03-fields/09-file-upload.md
Labels: documentation

#7359 Updating Hungarian translation
  packages/forms/resources/lang/hu/components.php
  packages/infolists/resources/lang/hu/components.php
  packages/notifications/resources/lang/hu/database.php
  packages/panels/resources/lang/hu/layout.php
  packages/panels/resources/lang/hu/pages/auth/edit-profile.php
  packages/panels/resources/lang/hu/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/hu/pages/auth/login.php
  packages/panels/resources/lang/hu/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/hu/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/hu/pages/auth/register.php
  packages/panels/resources/lang/hu/pages/tenancy/edit-tenant-profile.php
  packages/support/resources/lang/hu/components/modal.php
  packages/tables/resources/lang/hu/table.php
Labels: i18n

#7343 fix new global search render hooks(before,after)
  packages/panels/resources/views/components/global-search/index.blade.php
  packages/panels/resources/views/components/topbar/index.blade.php
Labels: bug

#7352 Update outdated charts documentation
  packages/widgets/docs/03-charts.md
Labels: documentation

#7361 Fix globally configuring filters layout
  packages/tables/src/Table/Concerns/HasFilters.php
Labels: bug

#7363 update pt_BR translations
  packages/forms/resources/lang/pt_BR/components.php
  packages/panels/resources/lang/pt_BR/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/pt_BR/pages/auth/login.php
  packages/panels/resources/lang/pt_BR/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/pt_BR/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/pt_BR/pages/auth/register.php
  packages/tables/resources/lang/pt_BR/table.php
Labels: i18n

#7366 Added Norwegian language
  packages/actions/resources/lang/no/associate.php
  packages/actions/resources/lang/no/attach.php
  packages/actions/resources/lang/no/create.php
  packages/actions/resources/lang/no/delete.php
  packages/actions/resources/lang/no/detach.php
  packages/actions/resources/lang/no/dissociate.php
  packages/actions/resources/lang/no/edit.php
  packages/actions/resources/lang/no/force-delete.php
  packages/actions/resources/lang/no/group.php
  packages/actions/resources/lang/no/modal.php
  packages/actions/resources/lang/no/replicate.php
  packages/actions/resources/lang/no/restore.php
  packages/actions/resources/lang/no/view.php
  packages/forms/resources/lang/no/components.php
  packages/infolists/resources/lang/no/components.php
  packages/notifications/resources/lang/no/database.php
  packages/panels/resources/lang/no/global-search.php
  packages/panels/resources/lang/no/layout.php
  packages/panels/resources/lang/no/pages/auth/edit-profile.php
  packages/panels/resources/lang/no/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/no/pages/auth/login.php
  packages/panels/resources/lang/no/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/no/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/no/pages/auth/register.php
  packages/panels/resources/lang/no/pages/dashboard.php
  packages/panels/resources/lang/no/pages/tenancy/edit-tenant-profile.php
  packages/panels/resources/lang/no/resources/pages/create-record.php
  packages/panels/resources/lang/no/resources/pages/edit-record.php
  packages/panels/resources/lang/no/resources/pages/list-records.php
  packages/panels/resources/lang/no/resources/pages/view-record.php
  packages/panels/resources/lang/no/widgets/account-widget.php
  packages/panels/resources/lang/no/widgets/filament-info-widget.php
  packages/spatie-laravel-settings-plugin/resources/lang/no/pages/settings-page.php
  packages/spatie-laravel-translatable-plugin/resources/lang/no/actions.php
  packages/support/resources/lang/no/components/button.php
  packages/support/resources/lang/no/components/copyable.php
  packages/support/resources/lang/no/components/modal.php
  packages/support/resources/lang/no/components/pagination.php
  packages/tables/resources/lang/no/table.php
Labels: i18n

#7373 Update Dutch translations
  packages/forms/resources/lang/en/components.php
  packages/forms/resources/lang/nl/components.php
  packages/panels/resources/lang/nl/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/nl/pages/auth/login.php
  packages/panels/resources/lang/nl/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/nl/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/nl/pages/auth/register.php
  packages/tables/resources/lang/nl/table.php
Labels: i18n

#7375 Fix RTL support for sidebar and icon badge
  packages/notifications/resources/views/components/database/modal/heading.blade.php
  packages/panels/resources/views/components/sidebar/index.blade.php
  packages/support/resources/views/components/icon-button.blade.php
Labels: ui, i18n

#7380 fix: typo in docs
  packages/panels/docs/05-dashboard.md
Labels: documentation

#7387 Fix echoing pagination translation
  packages/support/resources/views/components/pagination/index.blade.php
Labels: bug

#7385 Support image URLs as icon
  packages/support/resources/views/components/icon.blade.php
Labels: enhancement

#7403 Grammar and consistency updates
  packages/actions/docs/01-installation.md
  packages/forms/docs/01-installation.md
  packages/forms/docs/10-upgrade-guide.md
  packages/infolists/docs/01-installation.md
  packages/notifications/docs/07-upgrade-guide.md
  packages/panels/docs/01-installation.md
  packages/panels/docs/14-upgrade-guide.md
  packages/tables/docs/01-installation.md
  packages/tables/docs/13-upgrade-guide.md
  packages/widgets/docs/01-installation.md
Labels: documentation

#7408 update pl translation
  packages/panels/resources/lang/pl/pages/auth/login.php
  packages/tables/resources/lang/pl/table.php
Labels: i18n

#7418 obsolete plugin docs
  packages/support/docs/08-plugins/01-getting-started.md
Labels: documentation

#7420 Fix typos and make minor language edits
  README.md
Labels: documentation

#7409 Update 10-tenancy.md
  packages/panels/docs/10-tenancy.md
Labels: documentation

#7424 Add missing translations for ms
  packages/panels/resources/lang/ms/pages/auth/edit-profile.php
  packages/panels/resources/lang/ms/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/ms/pages/auth/login.php
  packages/panels/resources/lang/ms/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/ms/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/ms/pages/auth/register.php
  packages/panels/resources/lang/ms/pages/tenancy/edit-tenant-profile.php
  packages/tables/resources/lang/ms/table.php
Labels: i18n

#7438 Update ru & ua languages
  packages/forms/resources/lang/ru/components.php
  packages/forms/resources/lang/uk/components.php
  packages/infolists/resources/lang/ru/components.php
  packages/infolists/resources/lang/uk/components.php
  packages/tables/resources/lang/ru/table.php
  packages/tables/resources/lang/uk/table.php
Labels: i18n

#7435 Translated missing items in Hebrew language file
  packages/forms/resources/lang/he/components.php
  packages/panels/resources/lang/he/layout.php
  packages/panels/resources/lang/he/pages/auth/edit-profile.php
  packages/panels/resources/lang/he/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/he/pages/auth/login.php
  packages/panels/resources/lang/he/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/he/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/he/pages/auth/register.php
  packages/panels/resources/lang/he/pages/tenancy/edit-tenant-profile.php
  packages/tables/resources/lang/he/table.php
Labels: i18n

#7430 Added missing translations for italian
  packages/actions/resources/lang/it/replicate.php
  packages/forms/resources/lang/it/components.php
  packages/panels/resources/lang/it/layout.php
  packages/panels/resources/lang/it/pages/auth/edit-profile.php
  packages/panels/resources/lang/it/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/it/pages/auth/login.php
  packages/panels/resources/lang/it/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/it/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/it/pages/auth/register.php
  packages/panels/resources/lang/it/pages/dashboard.php
  packages/tables/resources/lang/it/table.php
Labels: i18n

#7431 Dutch translations panels profile
  packages/panels/resources/lang/nl/pages/auth/edit-profile.php
  packages/panels/resources/lang/nl/pages/auth/login.php
Labels: i18n

#7434 Update Docs for conditionally showing a Nav Item
  packages/panels/docs/06-navigation.md
Labels: documentation

#7456 Fixed italian translations for actions
  packages/actions/resources/lang/it/associate.php
  packages/actions/resources/lang/it/attach.php
  packages/actions/resources/lang/it/create.php
  packages/actions/resources/lang/it/delete.php
  packages/actions/resources/lang/it/detach.php
  packages/actions/resources/lang/it/dissociate.php
  packages/actions/resources/lang/it/force-delete.php
Labels: i18n

#7417 fix render hook footer in simple layout (login,registration..) pages
  packages/panels/resources/views/components/layout/simple.blade.php
Labels: bug, ui

#7451 Fixed FileUpload `avatar` resize
  packages/forms/src/Components/FileUpload.php
Labels: bug

#7473 Update 07-summaries.md
  packages/tables/docs/07-summaries.md
Labels: documentation

#7347 Bump Rector in upgrade script to 0.17
  packages/upgrade/composer.json
Labels: chore

#7406 Update 09-configuration.md - Ensure Absence of Conflicting Route in web.php
  packages/panels/docs/09-configuration.md
Labels: documentation

#7422 Feature: show missing and removed translation files
  packages/support/src/Commands/CheckTranslationsCommand.php
Labels: enhancement

#7460 Update 04-pages.md
  packages/panels/docs/04-pages.md
Labels: documentation

#7462 fix: update default dashboard route in example
  packages/panels/docs/06-navigation.md
Labels: documentation

#7464 Improve Plugins docs
  packages/support/docs/08-plugins/01-getting-started.md
  packages/support/docs/08-plugins/02-build-a-panel-plugin.md
Labels: documentation

#7467 docs: Fix reference to `recordSelect` method
  packages/panels/docs/03-resources/07-relation-managers.md
Labels: documentation

#7468 Fix - Resolve issue with chart data not updating during polling intervals
  packages/widgets/resources/js/components/stats-overview/stat/chart.js
  packages/widgets/resources/views/stats-overview-widget/stat.blade.php
Labels: bug

#7483 update pl translation
  packages/panels/resources/lang/pl/pages/auth/edit-profile.php
  packages/panels/resources/lang/pl/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/pl/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/pl/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/pl/pages/auth/register.php
  packages/panels/resources/lang/pl/pages/tenancy/edit-tenant-profile.php
  packages/support/resources/lang/pl/components/modal.php
Labels: i18n

#7486 Missing/removed files fix for Windows
  packages/support/src/Commands/CheckTranslationsCommand.php
Labels: bug

#7488 Add validation modifyRuleUsing to 14-upgrade-guide.md
  packages/forms/docs/10-upgrade-guide.md
Labels: documentation

#7503 fix Translatable edit
  packages/spatie-laravel-translatable-plugin/src/Resources/Pages/EditRecord/Concerns/Translatable.php
Labels: bug

#7497 Update vi translations
  packages/actions/resources/lang/vi/associate.php
  packages/panels/resources/lang/vi/pages/auth/edit-profile.php
  packages/panels/resources/lang/vi/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/vi/pages/auth/login.php
  packages/panels/resources/lang/vi/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/vi/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/vi/pages/auth/register.php
  packages/panels/resources/lang/vi/pages/tenancy/edit-tenant-profile.php
  packages/tables/resources/lang/vi/table.php
Labels: i18n

#7374 Return suggestions when the $type is not set on SpatieTagsInput
  packages/spatie-laravel-tags-plugin/src/Forms/Components/SpatieTagsInput.php
Labels: bug

#7396 Fix Select with ->multiple() not firing afterStateUpdated event
  packages/forms/src/Concerns/HasState.php
Labels: bug

#7508 Add and update RO translation
  packages/forms/resources/lang/ro/components.php
  packages/panels/resources/lang/ro/layout.php
  packages/panels/resources/lang/ro/pages/auth/edit-profile.php
  packages/panels/resources/lang/ro/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/ro/pages/auth/login.php
  packages/panels/resources/lang/ro/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/ro/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/ro/pages/auth/register.php
  packages/panels/resources/lang/ro/pages/tenancy/edit-tenant-profile.php
  packages/support/resources/lang/ro/components/modal.php
  packages/support/resources/lang/ro/components/pagination.php
  packages/tables/resources/lang/ro/table.php
Labels: i18n

#7398 Multiple domains per panel
  packages/panels/routes/web.php
  packages/panels/src/Panel/Concerns/HasRoutes.php
Labels: enhancement

#7412 Improve default state handling for boolean values
  packages/forms/src/Components/Radio.php
  packages/forms/src/Components/Select.php
Labels: bug

#7449 add authorization check for tenant registration
  packages/panels/resources/views/components/tenant-menu.blade.php
  packages/panels/src/Pages/Tenancy/RegisterTenant.php
Labels: enhancement

#7490 fixed scroll issue on wizard component
  packages/forms/resources/views/components/wizard.blade.php
Labels: bug

#7477 Feature: hide menu item
  packages/panels/docs/06-navigation.md
  packages/panels/docs/10-tenancy.md
  packages/panels/src/Navigation/MenuItem.php
  packages/panels/src/Panel/Concerns/HasTenancy.php
  packages/panels/src/Panel/Concerns/HasUserMenu.php
Labels: enhancement

#7512 chore: Drop Laravel 9
  .github/workflows/phpstan.yml
  .github/workflows/tests.yml
  composer.json
  composer.lock
  packages/actions/composer.json
  packages/actions/docs/01-installation.md
  packages/forms/composer.json
  packages/forms/docs/01-installation.md
  packages/forms/docs/10-upgrade-guide.md
  packages/infolists/composer.json
  packages/infolists/docs/01-installation.md
  packages/notifications/composer.json
  packages/notifications/docs/01-installation.md
  packages/notifications/docs/07-upgrade-guide.md
  packages/panels/composer.json
  packages/panels/docs/01-installation.md
  packages/panels/docs/14-upgrade-guide.md
  packages/spatie-laravel-google-fonts-plugin/composer.json
  packages/spatie-laravel-media-library-plugin/composer.json
  packages/spatie-laravel-settings-plugin/composer.json
  packages/spatie-laravel-tags-plugin/composer.json
  packages/spatie-laravel-translatable-plugin/composer.json
  packages/support/composer.json
  packages/tables/composer.json
  packages/tables/docs/01-installation.md
  packages/tables/docs/13-upgrade-guide.md
  packages/widgets/docs/01-installation.md
Labels: chore

#7476 Using Lravel propmts in panel builder commands.
  packages/forms/src/Commands/Concerns/CanManipulateFiles.php
  packages/forms/src/Commands/Concerns/CanValidateInput.php
  packages/forms/src/Commands/MakeFieldCommand.php
  packages/forms/src/Commands/MakeFormCommand.php
  packages/forms/src/Commands/MakeLayoutComponentCommand.php
  packages/infolists/src/Commands/MakeEntryCommand.php
  packages/infolists/src/Commands/MakeLayoutComponentCommand.php
  packages/panels/src/Commands/Concerns/CanIndentStrings.php
  packages/panels/src/Commands/Concerns/CanManipulateFiles.php
  packages/panels/src/Commands/Concerns/CanValidateInput.php
  packages/panels/src/Commands/MakePageCommand.php
  packages/panels/src/Commands/MakePanelCommand.php
  packages/panels/src/Commands/MakeRelationManagerCommand.php
  packages/panels/src/Commands/MakeResourceCommand.php
  packages/panels/src/Commands/MakeThemeCommand.php
  packages/panels/src/Commands/MakeUserCommand.php
  packages/spatie-laravel-settings-plugin/src/Commands/MakeSettingsPageCommand.php
  packages/support/src/Commands/Concerns/CanValidateInput.php
  packages/support/src/Commands/InstallCommand.php
  packages/tables/src/Commands/Concerns/CanManipulateFiles.php
  packages/tables/src/Commands/Concerns/CanValidateInput.php
  packages/tables/src/Commands/MakeColumnCommand.php
  packages/tables/src/Commands/MakeTableCommand.php
  packages/widgets/src/Commands/MakeWidgetCommand.php
Labels: enhancement

#7516 fix some Farsi translations
  packages/actions/resources/lang/fa/create.php
  packages/forms/resources/lang/fa/components.php
  packages/panels/resources/lang/fa/global-search.php
  packages/panels/resources/lang/fa/layout.php
  packages/panels/resources/lang/fa/resources/pages/create-record.php
  packages/support/resources/lang/fa/components/pagination.php
  packages/tables/resources/lang/fa/table.php
Labels: i18n

#7518 Use Actions\StaticAction instead of deprecated Modal\Actions
  packages/actions/docs/04-modals.md
Labels: documentation

#7522 Set default pagination page option to null
  packages/tables/src/Table/Concerns/CanPaginateRecords.php
Labels: bug

#7521 Update README badges with Laravel v10
  README.md
Labels: chore

#7461 Add prefix and suffix for tag
  packages/forms/docs/03-fields/14-tags-input.md
  packages/forms/resources/views/components/tags-input.blade.php
  packages/forms/src/Components/TagsInput.php
Labels: enhancement

#6824 fix get tags with no types.
  packages/spatie-laravel-tags-plugin/src/Tables/Columns/SpatieTagsColumn.php
Labels: enhancement

#7531 Resolve display table filters
  packages/tables/resources/views/index.blade.php
Labels: bug

#7533 [bug] [2.x] fix upload progress indicator
  packages/forms/resources/views/components/file-upload.blade.php
Labels: bug

#7534 [bug] [3.x] fix upload progress indicator
  packages/forms/resources/views/components/file-upload.blade.php
Labels: bug

#7526 fix: EditProfile - debounce password change update requests
  packages/panels/src/Pages/Auth/EditProfile.php
Labels: enhancement

#7532 fix global search focus
  packages/panels/resources/views/components/global-search/field.blade.php
Labels: bug

#7416 Add more changes to upgrade guides: masks, panel configuration, action namespaces, action function calls
  packages/actions/docs/10-upgrade-guide.md
  packages/forms/docs/10-upgrade-guide.md
  packages/panels/docs/14-upgrade-guide.md
Labels: documentation

#7546 Tenancy setup: implement canAccessTenant required by interface
  packages/panels/docs/10-tenancy.md
Labels: documentation

#7545 fix: translatable column search
  packages/spatie-laravel-translatable-plugin/src/SpatieLaravelTranslatableContentDriver.php
Labels: bug

#7549 fix some Farsi translations
  packages/forms/resources/lang/fa/components.php
  packages/tables/resources/lang/fa/table.php
Labels: i18n

#7551 Fix icon button indicator displayed over action dropdown
  packages/support/resources/views/components/icon-button.blade.php
Labels: bug

#7553 Update 05-style-customization.md grammatical improvements
  packages/support/docs/05-style-customization.md
Labels: documentation

#7562 Feat: Allow use of WigetConfiguration on Panel dashboard
  packages/panels/resources/views/pages/dashboard.blade.php
  packages/panels/src/Panel/Concerns/HasComponents.php
Labels: bug

#7565 Update finnish translation
  packages/forms/resources/lang/fi/components.php
  packages/infolists/resources/lang/fi/components.php
  packages/panels/resources/lang/fi/layout.php
  packages/panels/resources/lang/fi/pages/auth/edit-profile.php
  packages/panels/resources/lang/fi/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/fi/pages/auth/login.php
  packages/panels/resources/lang/fi/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/fi/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/fi/pages/auth/register.php
  packages/panels/resources/lang/fi/pages/tenancy/edit-tenant-profile.php
  packages/tables/resources/lang/fi/table.php
Labels: i18n

#7579 fix: Reintroduce CanValidateInput
  packages/support/src/Commands/Concerns/CanValidateInput.php
Labels: bug

#7574 respect hiddenLabel() on wizard steps
  packages/forms/resources/views/components/wizard.blade.php
Labels: bug

#7552 Fix Octane registration
  packages/panels/src/Facades/Filament.php
  packages/panels/src/PanelProvider.php
  packages/support/src/Assets/AssetManager.php
  packages/support/src/Facades/FilamentAsset.php
  packages/support/src/Facades/FilamentColor.php
  packages/support/src/Facades/FilamentIcon.php
  packages/support/src/Facades/FilamentView.php
Labels: bug

#7433 Update fieldset styling
  packages/support/resources/views/components/fieldset.blade.php
Labels: ui

#7595 fix bug unset active filter for relations
  packages/tables/src/Concerns/CanSearchRecords.php
Labels: bug

#7566 Updating docs to fix reference to the max content width settings
  packages/panels/docs/09-configuration.md
Labels: documentation

#7558 Feature: add `all()` to `Color`
  packages/support/src/Colors/Color.php
  tests/src/Support/ColorTest.php
Labels: enhancement

#7599 Fix Action component property
  packages/forms/src/Components/Actions/Action.php
Labels: bug

#7596 Fix HasManyThrough relation for Table CreateAction
  packages/tables/src/Actions/CreateAction.php
Labels: bug

#7612 Update MakeThemeCommand.php
  packages/panels/src/Commands/MakeThemeCommand.php
Labels: enhancement

#7624 Fix: visible is not being considered for core items on Tenant menu
  packages/panels/resources/views/components/tenant-menu.blade.php
  packages/panels/src/Panel/Concerns/HasTenancy.php
Labels: bug

#7628 Add closure examples to Panel navigation docs
  packages/forms/resources/views/components/file-upload.blade.php
  packages/panels/docs/06-navigation.md
Labels: documentation

#7631 Add make-theme instructions to docs
  packages/panels/docs/11-themes.md
Labels: documentation

#7602 Apply column search when overriding applySearchToTableQuery
  packages/tables/docs/10-advanced.md
Labels: documentation

#7611 Add tooltip to hint icon
  packages/forms/docs/03-fields/01-getting-started.md
  packages/forms/resources/views/components/field-wrapper/hint.blade.php
  packages/forms/resources/views/components/field-wrapper/index.blade.php
  packages/forms/src/Components/Concerns/HasHint.php
  packages/infolists/docs/03-entries/01-getting-started.md
  packages/infolists/resources/views/components/entry-wrapper/hint.blade.php
  packages/infolists/resources/views/components/entry-wrapper/index.blade.php
  packages/infolists/src/Components/Concerns/HasHint.php
Labels: enhancement, low priority

#7643 Update hint icon tooltip with theme
  packages/forms/resources/views/components/field-wrapper/hint.blade.php
Labels: ui

#7661 fix: Delay panel registration
  packages/panels/src/Facades/Filament.php
Labels: bug

#7583 Support hidden label in fieldset
  packages/forms/resources/views/components/fieldset.blade.php
  packages/infolists/resources/views/components/fieldset.blade.php
  packages/support/resources/views/components/fieldset.blade.php
Labels: bug

#7650 Add missing german table translations
  packages/tables/resources/lang/de/table.php
Labels: i18n

#7652 Update 02-build-a-panel-plugin.md
  packages/support/docs/08-plugins/02-build-a-panel-plugin.md
Labels: documentation

#7655 [Feature] Add optional route tenant prefix
  packages/panels/docs/10-tenancy.md
  packages/panels/routes/web.php
  packages/panels/src/Panel/Concerns/HasTenancy.php
Labels: enhancement

#7660 [Docs] fix links in relation manager docs
  packages/panels/docs/03-resources/07-relation-managers.md
Labels: documentation

#7671 Update 10-tenancy.md
  packages/panels/docs/10-tenancy.md
Labels: documentation

#7681 fix: Vite theme requested on install
  packages/panels/src/Panel/Concerns/HasTheme.php
Labels: bug

#7676 Add autocomplete attribute to password field
  packages/panels/src/Pages/Auth/Login.php
Labels: enhancement

#7685 Remove disableAutocomplete() from the docs
  packages/forms/docs/03-fields/02-text-input.md
Labels: documentation

#7689 Fix duplicate renderhooks in relation managers
  packages/panels/resources/views/components/resources/relation-managers.blade.php
Labels: bug

#7675 fix missing state in disabled rich editor component
  packages/forms/resources/views/components/rich-editor.blade.php
Labels: bug

#7653 Fix issue #7635
  packages/widgets/resources/js/components/stats-overview/stat/chart.js
  packages/widgets/resources/views/stats-overview-widget/stat.blade.php
  packages/widgets/src/StatsOverviewWidget/Stat.php
Labels: bug

#7670 fix issue #7646
  packages/forms/src/Components/Concerns/InteractsWithToolbarButtons.php
Labels: bug

#7672 Docs: how to remove CreateAction button
  packages/panels/docs/03-resources/01-getting-started.md
Labels: documentation

#7686 Allow modal footerActions to be used as a slot
  packages/support/docs/09-blade-components/02-modal.md
  packages/support/resources/views/components/modal/index.blade.php
Labels: enhancement

#7692 Fix nested infolist action record injection
  packages/infolists/src/Components/Actions/Action.php
Labels: bug

#7673 Extend InstallCommand to check if PanelProvider exists if necessary
  packages/support/src/Commands/InstallCommand.php
Labels: enhancement

#7719 Update spanish translation
  packages/tables/resources/lang/es/table.php
Labels: i18n

#7721 [Docs] Add path for class Filament::getTenant()
  packages/panels/docs/10-tenancy.md
Labels: documentation

#7720 docs: update infolist simple image
  docs-assets/screenshots/images/dark/infolists/layout/fieldset/simple.jpg
  docs-assets/screenshots/images/light/infolists/layout/fieldset/simple.jpg
Labels: documentation

#7701 Use `getPrettyVersion` instead of `getVersion` in info widget
  packages/panels/resources/views/widgets/filament-info-widget.blade.php
Labels: enhancement

#7700 [Docs] fix typo in image source
  packages/infolists/docs/03-entries/02-text.md
Labels: documentation

#7707 [Docs] fix Assets documentation link in Custom field
  packages/forms/docs/03-fields/19-custom.md
Labels: documentation

#7702 [Docs] Correct image source
  packages/infolists/docs/04-layout/04-tabs.md
Labels: documentation

#7714 [Enhancement] Update Login Tab-key Order.php
  packages/panels/src/Pages/Auth/Login.php
Labels: enhancement

#7739 fix: update fn syntax in repeater docs
  packages/forms/docs/03-fields/12-repeater.md
Labels: documentation

#7734 Updated Spanish translations files.
  packages/infolists/resources/lang/es/components.php
  packages/panels/resources/lang/es/layout.php
  packages/panels/resources/lang/es/pages/auth/edit-profile.php
  packages/panels/resources/lang/es/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/es/pages/auth/login.php
  packages/panels/resources/lang/es/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/es/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/es/pages/auth/register.php
  packages/panels/resources/lang/es/pages/tenancy/edit-tenant-profile.php
Labels: i18n

#7736 [Fix] - reactivity of CheckboxList
  packages/forms/src/Concerns/HasState.php
Labels: bug

#7729 3.x alpha
  composer.json
  composer.lock
  packages/forms/src/Components/CheckboxList.php
  packages/forms/src/Components/Select.php
  packages/support/src/Services/RelationshipJoiner.php
  packages/tables/src/Actions/AttachAction.php
  packages/tables/src/Concerns/CanSummarizeRecords.php
  packages/tables/src/Filters/Concerns/HasRelationship.php
  packages/tables/src/Filters/SelectFilter.php
  packages/tables/src/Support/RelationshipJoiner.php
  tests/src/Upgrade/Fixture/page_getActions_to_getHeaderActions.php.inc
Labels: bug

#7745 fix: Tenant profile auth policy method
  packages/panels/src/Pages/Tenancy/EditTenantProfile.php
  tests/database/factories/TeamFactory.php
  tests/database/migrations/create_teams_table.php
  tests/src/Models/Team.php
  tests/src/Models/User.php
  tests/src/Panels/Pages/Tenancy/EditTenantProfileTest.php
Labels: bug

#7728 Fix global search results panel on mobile
  packages/panels/dist/theme.css
  packages/panels/resources/views/components/global-search/index.blade.php
  packages/panels/resources/views/components/global-search/results-container.blade.php
  packages/support/dist/index.js
Labels: bug, ui, high priority

#7753 [Docs] Added quotes to `x-data`
  packages/support/docs/09-blade-components/02-tabs.md
Labels: documentation

#7755 Update table.php translation
  packages/tables/resources/lang/fr/table.php
Labels: i18n

#7752 [Docs] Removed `;` from array
  packages/support/docs/04-colors.md
Labels: documentation

#7771 Danish translation for table
  packages/tables/resources/lang/da/table.php
Labels: i18n

#7762 [Docs] Adds missing hooks `panels::global-search.before` & `panels::global-search.after`
  packages/support/docs/06-render-hooks.md
Labels: documentation

#7776 feat: change strtoupper, strtolower to Str::upper, Str::lower functions
  packages/forms/src/Commands/Concerns/CanGenerateForms.php
  packages/forms/src/Components/MorphToSelect/Type.php
  packages/forms/src/Components/Select.php
  packages/panels/src/Resources/Resource.php
  packages/tables/src/Actions/AssociateAction.php
  packages/tables/src/Actions/AttachAction.php
  packages/tables/src/Columns/Summarizers/Range.php
  packages/tables/src/Commands/Concerns/CanGenerateTables.php
  packages/tables/src/Concerns/CanSearchRecords.php
  packages/tables/src/Table/Concerns/CanSortRecords.php
  tests/src/Support/ColorTest.php
Labels: chore

#7780 only discover valid classes for discoverResources/Pages/Widgets
  packages/panels/src/Panel/Concerns/HasComponents.php
Labels: enhancement

#7779 Remove `function_exists` checks for `enum_exists`
  packages/actions/src/Concerns/HasSelect.php
  packages/forms/src/Components/Concerns/HasOptions.php
  packages/tables/src/Filters/Concerns/HasOptions.php
Labels: chore

#7794 Pass additional utilities to AttachAction and AssociateAction
  packages/tables/src/Actions/AssociateAction.php
  packages/tables/src/Actions/AttachAction.php
Labels: enhancement

#7799 Prevent badges from shrinking
  packages/support/resources/views/components/badge.blade.php
Labels: ui

#7810 adjusting route priority fix #7809
  packages/panels/routes/web.php
Labels: enhancement

#7798 Add ability to discover scoped livewire component
  packages/panels/src/Panel/Concerns/HasComponents.php
Labels: enhancement

#7824 fix: Null relationship select
  packages/forms/src/Components/Select.php
Labels: bug

#7828 Support disabled option in Choices
  packages/forms/src/Components/Select.php
Labels: bug

#7832 Fix refactored prepareQueryForNoConstraints logic
  packages/support/src/Services/RelationshipJoiner.php
Labels: bug

#7835 Fix multi-tenancy documentation method typo
  packages/panels/docs/10-tenancy.md
Labels: documentation

#7838 fix: Make global search results properties readonly
  packages/panels/src/GlobalSearch/GlobalSearchResult.php
Labels: chore

#7839 Fix public component properties
  packages/actions/src/Concerns/HasWizard.php
  packages/forms/src/Components/MorphToSelect.php
  packages/forms/src/Components/Tabs.php
  packages/forms/src/Components/Wizard.php
  packages/infolists/src/Components/Tabs.php
  packages/tables/src/Filters/Concerns/HasIndicators.php
  packages/tables/src/Filters/Filter.php
Labels: chore

#7834 Add more options to maximum content width
  packages/panels/dist/theme.css
  packages/panels/docs/04-pages.md
  packages/panels/docs/09-configuration.md
  packages/panels/resources/views/components/layout/index.blade.php
Labels: enhancement

#7833 Fix filter indicator wrapping
  packages/tables/resources/views/components/filters/indicators.blade.php
Labels: bug, ui

#7849 fix: Postgres search case insensitivity
  packages/forms/docs/03-fields/03-select.md
  packages/forms/src/Components/MorphToSelect/Type.php
  packages/forms/src/Components/Select.php
  packages/panels/docs/03-resources/08-global-search.md
  packages/panels/src/Resources/Resource.php
  packages/tables/docs/03-columns/01-getting-started.md
  packages/tables/src/Actions/AssociateAction.php
  packages/tables/src/Actions/AttachAction.php
  packages/tables/src/Columns/Concerns/CanBeSearchable.php
  packages/tables/src/Columns/Concerns/InteractsWithTableQuery.php
  packages/tables/src/Concerns/CanSearchRecords.php
  packages/tables/src/Filters/SelectFilter.php
Labels: bug

#7761 Add closure to `url()` method in documentation
  packages/panels/docs/06-navigation.md
  packages/panels/docs/10-tenancy.md
Labels: documentation
