Repository filamentphp/filament, pull requests merged in 2023-02, with the labels that each got.

#5589 Support custom dropdown offset
  packages/support/resources/views/components/dropdown/index.blade.php
Labels: enhancement

#5599 Add Action suffix to action methods
  packages/actions/docs/05-adding-an-action-to-a-livewire-component.md
Labels: documentation

#5623 Fix type annotations
  packages/forms/src/Components/TextInput.php
Labels: bug

#5625 fix notifications translation in persian
  packages/notifications/resources/lang/fa/database.php
Labels: i18n

#5614 Revert "Fix `support::button` loading indicator when using action params"
  packages/support/resources/views/components/button.blade.php
Labels: bug

#5624 Update flex shrink syntax
  packages/app/dist/theme.css
  packages/app/resources/views/components/layouts/app/sidebar/group.blade.php
  packages/app/resources/views/components/layouts/app/topbar/index.blade.php
  packages/forms/resources/views/components/wizard.blade.php
  packages/support/resources/views/components/dropdown/list/item.blade.php
  packages/tables/resources/views/components/filters/indicators.blade.php
  packages/tables/resources/views/index.blade.php
Labels: code quality

#5615 Fix: stats chart color change on dark mode toggle
  packages/admin/resources/views/components/stats/card.blade.php
Labels: bug

#5630 Fix chart color dark mode toggle
  packages/admin/resources/views/components/stats/card.blade.php
Labels: bug

#5633 Add extra attributes to the section component
  packages/forms/resources/views/components/section.blade.php
  packages/infolists/resources/views/components/section.blade.php
Labels: bug

#5647 Fix: height issues on body with overflow-x-clip and min-h-full
  packages/admin/resources/views/components/layouts/base.blade.php
Labels: bug

#5649 Fix: Table TextColumn rowIndex pagination support
  packages/tables/docs/03-columns/02-text.md
Labels: bug

#5616 Fix: slideover enter animation
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/echo.js
  packages/admin/dist/echo.js.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.js
  packages/support/resources/views/components/modal/index.blade.php
Labels: bug

#5648 Fix/tables a11y
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/echo.js
  packages/admin/dist/echo.js.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.js
  packages/tables/resources/lang/en/table.php
  packages/tables/resources/views/components/checkbox/index.blade.php
  packages/tables/resources/views/components/header-cell.blade.php
  packages/tables/resources/views/components/pagination/index.blade.php
  packages/tables/resources/views/components/pagination/records-per-page-selector.blade.php
  packages/tables/resources/views/index.blade.php
Labels: bug

#5658 Fix: overflow issues on html, body with modals
  packages/admin/resources/views/components/layouts/app.blade.php
  packages/admin/resources/views/components/layouts/base.blade.php
Labels: bug

#5661 Switch from json_encode to castAsJson
  tests/src/Admin/Resources/Pages/CreateRecordTest.php
Labels: bug

#5660 Update translations
  packages/tables/resources/lang/en/table.php
  packages/tables/resources/lang/nl/table.php
Labels: i18n

#5544 Feature/sort by buttons
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/repeater.blade.php
  packages/forms/src/Components/Builder.php
  packages/forms/src/Components/Repeater.php
  packages/forms/src/helpers.php
Labels: enhancement

#5665 Add PostCSS to install commands
  packages/forms/docs/01-installation.md
  packages/forms/src/Commands/InstallCommand.php
  packages/notifications/docs/01-installation.md
  packages/notifications/src/Commands/InstallCommand.php
  packages/tables/docs/01-installation.md
  packages/tables/src/Commands/InstallCommand.php
Labels: chore

#5668 Updates FA translations.
  packages/tables/resources/lang/fa/table.php
Labels: i18n

#5669 Update PT-BR translations for a11y
  packages/tables/resources/lang/pt_BR/table.php
Labels: i18n

#5672 Update finnish translation
  packages/tables/resources/lang/fi/table.php
Labels: i18n

#5674 Update Blade capture directive package
  composer.json
  composer.lock
  packages/admin/composer.json
Labels: chore

#5673 Support Laravel 10
  .github/workflows/phpstan.yml
  .github/workflows/tests.yml
  composer.json
  composer.lock
  packages/actions/composer.json
  packages/app/composer.json
  packages/forms/composer.json
  packages/infolists/composer.json
  packages/notifications/composer.json
  packages/spatie-laravel-google-fonts-plugin/composer.json
  packages/spatie-laravel-media-library-plugin/composer.json
  packages/spatie-laravel-settings-plugin/composer.json
  packages/spatie-laravel-tags-plugin/composer.json
  packages/spatie-laravel-translatable-plugin/composer.json
  packages/support/composer.json
  packages/tables/composer.json
Labels: chore

#5591 Always Show Pagination Overview
  packages/tables/resources/lang/en/table.php
  packages/tables/resources/lang/nl/table.php
  packages/tables/resources/views/components/pagination/index.blade.php
Labels: ui

#5529 docs: How to disable clickable rows
  packages/tables/docs/02-getting-started.md
Labels: documentation

#5671 Add inlineLabel() method explenation
  packages/forms/docs/04-layout.md
Labels: documentation

#5680 Update pagination overview pt_br translations
  packages/tables/resources/lang/pt_BR/table.php
Labels: i18n

#5681 Update finnish translation
  packages/tables/resources/lang/fi/table.php
Labels: i18n

#5685 Updates AR translations.
  packages/tables/resources/lang/ar/table.php
Labels: i18n

#5687 Update Swedish translations
  packages/tables/resources/lang/sv/table.php
Labels: i18n

#5691 standardize single quotes escapes in translations
  packages/forms/resources/lang/ca/components.php
  packages/forms/resources/lang/it/components.php
  packages/tables/resources/lang/fr/table.php
Labels: i18n

#5690 Hotfix: Table search icon placement.
  packages/tables/resources/views/components/search-input.blade.php
Labels: bug

#5682 Fix Tailwind outline regression
  package-lock.json
  package.json
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/mix-manifest.json
  packages/admin/resources/views/components/global-search/input.blade.php
  packages/admin/resources/views/components/layouts/app/sidebar/index.blade.php
  packages/admin/resources/views/components/resources/relation-managers/index.blade.php
  packages/admin/resources/views/components/tabs/item.blade.php
  packages/admin/resources/views/components/topbar.blade.php
  packages/admin/resources/views/pages/actions/select-action.blade.php
  packages/admin/resources/views/widgets/account-widget.blade.php
  packages/admin/resources/views/widgets/chart-widget.blade.php
  packages/admin/resources/views/widgets/filament-info-widget.blade.php
  packages/forms/dist/module.esm.css
  packages/forms/resources/css/components/select.css
  packages/forms/resources/views/components/checkbox-list.blade.php
  packages/forms/resources/views/components/color-picker.blade.php
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/resources/views/components/markdown-editor.blade.php
  packages/forms/resources/views/components/rich-editor.blade.php
  packages/forms/resources/views/components/section.blade.php
  packages/forms/resources/views/components/select.blade.php
  packages/forms/resources/views/components/tabs/tab.blade.php
  packages/forms/resources/views/components/text-input.blade.php
  packages/forms/resources/views/components/textarea.blade.php
  packages/forms/resources/views/components/toggle.blade.php
  packages/forms/resources/views/components/wizard/step.blade.php
  packages/support/resources/views/components/button.blade.php
  packages/support/resources/views/components/dropdown/list/item.blade.php
  packages/support/resources/views/components/icon-button.blade.php
  packages/support/resources/views/components/link.blade.php
  packages/tables/resources/views/columns/select-column.blade.php
  packages/tables/resources/views/columns/text-input-column.blade.php
  packages/tables/resources/views/columns/toggle-column.blade.php
  packages/tables/resources/views/components/pagination/item.blade.php
  packages/tables/resources/views/components/pagination/records-per-page-selector.blade.php
  packages/tables/resources/views/components/search-input.blade.php
Labels: bug

#5693 Accept Htmlable for table column label
  packages/tables/src/Columns/Concerns/HasLabel.php
Labels: enhancement

#5666 Add PostCSS to install command
  packages/support/src/Commands/InstallCommand.php
Labels: chore

#5697 Add more outline-none
  packages/forms/resources/css/components/select.css
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/resources/views/components/markdown-editor.blade.php
  packages/forms/resources/views/components/radio.blade.php
  packages/forms/resources/views/components/tags-input.blade.php
  packages/support/resources/views/components/input/index.blade.php
  packages/tables/resources/views/columns/checkbox-column.blade.php
Labels: bug

#5698 Add more outline-none to v2
  packages/forms/resources/css/components/select.css
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/tables/resources/views/columns/checkbox-column.blade.php
Labels: bug

#5701 Add outline-none to tables checkbox
  packages/tables/resources/views/components/checkbox/index.blade.php
Labels: bug

#5704 Fix incorrect language tag for pagination overview
  packages/tables/resources/views/components/pagination/index.blade.php
Labels: bug, i18n

#5703 Added czech and german localization
  packages/admin/resources/lang/cs/layout.php
  packages/forms/resources/lang/cs/components.php
  packages/tables/resources/lang/cs/table.php
  packages/tables/resources/lang/de/table.php
Labels: enhancement, i18n

#5723 Fixes header cell sort icon spacing
  packages/tables/resources/views/components/header-cell.blade.php
Labels: bug, ui

#5715 Fix colors order
  docs-assets/app/app/Providers/Filament/configure.php
  docs-assets/app/composer.lock
  package.json
  packages/app/tailwind.config.preset.js
Labels: chore

#5725 Cleanup
  packages/tables/resources/views/components/header-cell.blade.php
Labels: code quality

#5679 Make tables configurable
  packages/tables/src/Table.php
Labels: enhancement

#5727 Scopes file-attachment-element event listener to component
  packages/forms/resources/views/components/markdown-editor.blade.php
Labels: bug

#5733 Support disabling enum icon and color
  docs-assets/app/app/Providers/Filament/configure.php
  packages/infolists/src/Components/Concerns/HasColor.php
  packages/infolists/src/Components/Concerns/HasIcon.php
  packages/tables/src/Columns/Concerns/HasColor.php
  packages/tables/src/Columns/Concerns/HasIcon.php
Labels: enhancement

#5734 Fix html background color
  packages/admin/resources/views/components/layouts/base.blade.php
Labels: bug

#5741 Add welsh translation
  packages/forms/resources/lang/cy/components.php
Labels: i18n

#5738 fixed - error 500 when the delete button is clicked
  composer.lock
  packages/admin/src/Pages/Concerns/HasActions.php
  packages/admin/src/Testing/TestsPageActions.php
  packages/forms/src/Concerns/HasFormComponentActions.php
  packages/tables/src/Concerns/HasActions.php
  packages/tables/src/Concerns/HasBulkActions.php
  packages/tables/src/Testing/TestsActions.php
  packages/tables/src/Testing/TestsBulkActions.php
Labels: bug

#5748 Update toggleable dropdown placement
  docs-assets/app/app/Providers/Filament/configure.php
  packages/tables/resources/views/components/toggleable/index.blade.php
Labels: enhancement

#5728 Adding ability to `emitSelf`, `emitUp` and `emitTo` for `CanEmitEvent` trait
  packages/notifications/dist/module.esm.js
  packages/notifications/docs/02-sending-notifications.md
  packages/notifications/resources/js/Notification.js
  packages/notifications/resources/views/components/actions/action.blade.php
  packages/notifications/src/Actions/Action.php
  packages/support/src/Actions/Concerns/CanEmitEvent.php
  tests/src/Notifications/NotificationTest.php
Labels: enhancement

#5751 Update 02-listing-records.md
  packages/admin/docs/02-resources/02-listing-records.md
Labels: documentation

#5750 Clean up notifications PR
  packages/notifications/resources/js/Notification.js
  packages/notifications/resources/views/components/actions/action.blade.php
  packages/notifications/src/Actions/Action.php
  packages/support/src/Actions/Concerns/CanEmitEvent.php
  tests/src/Notifications/NotificationTest.php
Labels: enhancement, code quality

#5742 Handle JSON columns in form select component relationships
  packages/forms/src/Components/Select.php
Labels: bug

#5745 Adds note on testing with deferLoading()
  packages/tables/.stubs.php
  packages/tables/docs/07-testing.md
  packages/tables/src/Testing/TestsRecords.php
Labels: documentation

#5739 feat/set notification view from ->view('view')
  packages/notifications/resources/js/Notification.js
  packages/notifications/src/Notification.php
Labels: enhancement

#5752 Update Swahili Translations
  packages/tables/resources/lang/sw/table.php
Labels: i18n

#5756 Added Bosnian translations to tables.php
  packages/tables/resources/lang/bs/table.php
Labels: enhancement, i18n

#5584 Add Chart Filter Loading Indicator
  packages/widgets/resources/views/chart-widget.blade.php
  packages/widgets/src/ChartWidget.php
Labels: enhancement

#5762 Translate support package to Danish
  packages/support/resources/lang/da/actions/associate.php
  packages/support/resources/lang/da/actions/attach.php
  packages/support/resources/lang/da/actions/create.php
  packages/support/resources/lang/da/actions/delete.php
  packages/support/resources/lang/da/actions/detach.php
  packages/support/resources/lang/da/actions/dissociate.php
  packages/support/resources/lang/da/actions/edit.php
  packages/support/resources/lang/da/actions/force-delete.php
  packages/support/resources/lang/da/actions/group.php
  packages/support/resources/lang/da/actions/modal.php
  packages/support/resources/lang/da/actions/replicate.php
  packages/support/resources/lang/da/actions/restore.php
  packages/support/resources/lang/da/actions/view.php
  packages/support/resources/lang/da/components/button.php
  packages/support/resources/lang/da/components/modal.php
Labels: i18n

#5772 Fix: Copy paste image in Markdown Editor
  packages/forms/resources/views/components/markdown-editor.blade.php
Labels: bug

#5777 Fix install command info
  docs-assets/app/app/Providers/Filament/configure.php
  packages/support/src/Commands/InstallCommand.php
Labels: bug

#5774 Fixes counting rows when defer loading
  packages/tables/resources/views/index.blade.php
Labels: bug

#5770 Adding option for adding default collapsed/expanded for Panel Layout.
  packages/tables/docs/06-layout.md
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Columns/Layout/Component.php
Labels: enhancement

#5784 Add Filament to Vite refresh paths
  docs-assets/app/app/Providers/Filament/configure.php
  docs-assets/app/vite.config.js
  packages/support/stubs/scaffolding/vite.config.js
Labels: enhancement

#5788 feature: Don't deselect records when table filtered
  packages/tables/src/Concerns/CanSearchRecords.php
  packages/tables/src/Concerns/CanSelectRecords.php
  packages/tables/src/Concerns/HasFilters.php
Labels: enhancement

#5780 TextInputColumn. Debounce numeric input
  packages/tables/resources/views/columns/text-input-column.blade.php
Labels: enhancement

#5782 Create new filter layout: AboveContentCollapsable
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Filters/Layout.php
Labels: enhancement

#5789 Fix heroicon title attribute
  packages/support/resources/views/components/modal/index.blade.php
Labels: bug

#5795 Remove duplicated alignment key
  packages/tables/resources/views/columns/badge-column.blade.php
Labels: bug

#5794 Adds a new method for testing individual search columns
  packages/tables/.stubs.php
  packages/tables/src/Testing/TestsColumns.php
  tests/src/Tables/ColumnTest.php
  tests/src/Tables/Fixtures/PostsTable.php
Labels: enhancement

#5803 fix richeditor ul & ol padding on rtl
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/app.js.map
  packages/admin/dist/echo.js.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.css
  packages/forms/resources/css/components/rich-editor.css
Labels: bug

#5809 call livewire's getValidationAttributes() in form validation
  packages/forms/src/Concerns/InteractsWithForms.php
Labels: enhancement
