Repository filamentphp/filament, pull requests merged in 2023-06, with the labels that each got.

#6652 Support `Htmlable` record titles
  packages/admin/src/Pages/Page.php
  packages/admin/src/Resources/Pages/Concerns/InteractsWithRecord.php
  packages/admin/src/Resources/Pages/EditRecord.php
  packages/admin/src/Resources/Resource.php
  packages/forms/src/Components/Concerns/HasHelperText.php
  packages/forms/src/Components/Concerns/HasHint.php
  packages/tables/src/Columns/Concerns/HasDescription.php
Labels: enhancement

#6668 Fix explode deprecation in php 8.1.
  packages/tables/src/Columns/TagsColumn.php
Labels: bug

#6672 Fix TagsInput border when disabled
  packages/forms/resources/views/components/tags-input.blade.php
Labels: bug, ui

#6665 Fix entangle state path in markdown-editor
  packages/forms/resources/views/components/markdown-editor.blade.php
Labels: bug

#6673 Fix panel routes types
  packages/panels/src/Panel/Concerns/HasRoutes.php
Labels: bug

#6676 Fix attach multiple records in Attach select
  packages/tables/src/Actions/AttachAction.php
Labels: bug

#6666 Add `requiredIf()` and `requiredUnless()` validation methods
  packages/forms/docs/05-validation.md
  packages/forms/src/Components/Concerns/CanBeValidated.php
  tests/src/Forms/ValidationTest.php
Labels: enhancement

#6686 Update dashboard.php
  packages/admin/resources/lang/he/pages/dashboard.php
Labels: i18n

#6688 Add modal cancel action label method
  packages/actions/src/Concerns/CanOpenModal.php
Labels: enhancement

#6690 Update finnish translation
  packages/forms/resources/lang/fi/components.php
Labels: enhancement, i18n

#6694 Use capture
  composer.lock
  packages/admin/composer.json
  packages/forms/resources/views/components/checkbox.blade.php
  packages/forms/resources/views/components/radio.blade.php
  packages/forms/resources/views/components/toggle.blade.php
  packages/support/composer.json
Labels: chore

#6707 Support starting on last step of Wizard
  packages/forms/resources/views/components/wizard.blade.php
Labels: enhancement

#6692 Fix issue with page scroll up to the top after change value of any Fields or Create,Save button Inside Tab Component.
  packages/forms/resources/views/components/tabs.blade.php
Labels: bug

#6712 typo in associating and dissociating records
  packages/admin/docs/02-resources/07-relation-managers.md
Labels: documentation

#6713 📝 docs(getting-started.md): update description of relation managers in Filament
  packages/admin/docs/02-resources/01-getting-started.md
Labels: documentation

#6715 Fix RegisterTenant middleware
  packages/panels/src/Pages/Tenancy/RegisterTenant.php
Labels: bug

#6723 Fix for PHP 8.2 deprecated warning for ${var} string interpolation
  packages/support/src/Concerns/EvaluatesClosures.php
Labels: bug

#6584 Tweak section header spacing
  packages/support/resources/views/components/section.blade.php
Labels: enhancement, ui

#6717 Fix Display required label in Safari
  packages/forms/resources/views/components/field-wrapper/label.blade.php
Labels: bug

#6725 Fix Wizard throwing an exception if there is a hidden step that it needs to pass
  packages/forms/src/Components/Wizard.php
Labels: bug

#6727 [Feature] Auto hide parent component when children are hidden
  packages/forms/src/Components/Concerns/CanBeHidden.php
Labels: enhancement

#6728 Feat : Add color to custom navigation items
  packages/admin/resources/views/components/layouts/app/sidebar/group.blade.php
  packages/admin/resources/views/components/layouts/app/sidebar/item.blade.php
  packages/admin/src/Navigation/NavigationItem.php
Labels: enhancement

#6734 Add data mutate to replicate action
  packages/support/src/Actions/Concerns/CanReplicateRecords.php
Labels: enhancement

#6602 Navigation item additional methods
  composer.lock
  packages/admin/docs/05-navigation.md
  packages/admin/resources/views/components/layouts/app/sidebar/group.blade.php
  packages/admin/src/Navigation/NavigationItem.php
  tests/src/Admin/Navigation/NavigationBuilderTest.php
Labels: enhancement

#6761 ci: Update to Actions V3
  .github/workflows/fix-code-style.yml
  .github/workflows/monorepo-split.yml
  .github/workflows/npm-build.yml
  .github/workflows/phpstan.yml
  .github/workflows/tests.yml
Labels: chore

#6758 Fix select placeholder not showing
  packages/forms/resources/js/components/select.js
Labels: bug

#6729 reset all (from x button) fixed
  packages/tables/src/Concerns/HasFilters.php
Labels: bug

#6756 Allow modal close button to be hidden
  packages/actions/docs/04-modals.md
  packages/actions/resources/views/components/modals.blade.php
  packages/actions/src/Concerns/CanOpenModal.php
  packages/support/resources/views/components/modal/index.blade.php
  packages/support/src/View/Components/Modal.php
Labels: enhancement

#6655 Prevent livewire poll updates from overwriting TextInputColumn alpine state during editing.
  packages/tables/resources/views/columns/text-input-column.blade.php
Labels: bug

#6793 Design review
  packages/panels/resources/views/components/layouts/app/sidebar/badge.blade.php
  packages/panels/resources/views/components/layouts/app/sidebar/group.blade.php
  packages/panels/resources/views/components/layouts/app/sidebar/index.blade.php
  packages/panels/resources/views/components/layouts/app/sidebar/item.blade.php
  packages/panels/resources/views/components/layouts/app/topbar/index.blade.php
  packages/panels/src/Panel/Concerns/HasSidebar.php
Labels: ui

#6796 Add button type to select/deselect all buttons
  packages/tables/resources/views/components/selection-indicator.blade.php
Labels: bug

#6799 Updates dropdown placement
  packages/tables/resources/views/components/filters/dropdown.blade.php
  packages/tables/resources/views/components/toggleable/dropdown.blade.php
  packages/tables/src/Table/Concerns/HasActions.php
Labels: enhancement, ui

#6805 fix: User menu item hover state
  packages/admin/resources/views/components/layouts/app/topbar/user-menu.blade.php
Labels: bug

#6801 Feat: `CanBeCopied` copyText
  packages/tables/resources/views/columns/badge-column.blade.php
  packages/tables/resources/views/columns/color-column.blade.php
  packages/tables/resources/views/columns/text-column.blade.php
  packages/tables/src/Columns/Concerns/CanBeCopied.php
Labels: enhancement

#6807 Add host and port to broadcasting
  packages/admin/config/filament.php
Labels: enhancement

#6821 Add RTL layout support to sidebar toggle button
  packages/admin/resources/views/components/layouts/app/sidebar/index.blade.php
Labels: i18n

#6836 added HasMountableArguments trait for Action consistency
  packages/tables/src/Actions/Action.php
Labels: enhancement

#6856 Docs: alignment for columns
  packages/tables/docs/03-columns/01-getting-started.md
Labels: documentation

#6854 Update relation manager docs, command, and stub
  packages/panels/docs/03-resources/07-relation-managers.md
  packages/panels/src/Commands/MakeRelationManagerCommand.php
  packages/panels/stubs/RelationManager.stub
Labels: bug

#6848 Remove secondary color
  docs-assets/app/tailwind.config.js
  packages/actions/docs/03-trigger-button.md
  packages/forms/docs/03-fields/01-getting-started.md
  packages/forms/docs/03-fields/05-toggle.md
  packages/forms/docs/04-layout/04-tabs.md
  packages/infolists/docs/03-entries/02-text.md
  packages/infolists/docs/03-entries/03-icon.md
  packages/infolists/docs/04-layout/04-tabs.md
  packages/notifications/docs/02-sending-notifications.md
  packages/panels/dist/index.css
  packages/panels/docs/06-navigation.md
  packages/panels/docs/11-themes.md
  packages/support/docs/04-colors.md
  packages/support/src/Colors/ColorManager.php
  packages/support/tailwind.config.preset.js
  packages/tables/docs/03-columns/02-text.md
  packages/tables/docs/03-columns/03-icon.md
  packages/widgets/docs/01-installation.md
  packages/widgets/docs/02-stats-overview.md
  tests/src/Notifications/NotificationTest.php
Labels: chore

#6873 Support removing repeatable entry card
  packages/infolists/docs/03-entries/06-repeatable.md
  packages/infolists/resources/views/components/repeatable-entry.blade.php
  packages/infolists/src/Components/RepeatableEntry.php
Labels: enhancement

#6872 Add missing bool casts
  packages/actions/src/Concerns/CanBeInline.php
  packages/actions/src/Concerns/CanBeOutlined.php
  packages/actions/src/Concerns/CanOpenModal.php
  packages/actions/src/Concerns/HasAction.php
  packages/forms/src/Components/Builder.php
  packages/forms/src/Components/Concerns/CanBeCloned.php
  packages/forms/src/Components/Concerns/CanBeMarkedAsRequired.php
  packages/forms/src/Components/Repeater.php
  packages/infolists/src/Components/Concerns/CanBeCollapsed.php
  packages/panels/src/Navigation/NavigationItem.php
  packages/tables/src/Columns/IconColumn.php
  packages/tables/src/Table/Concerns/HasBulkActions.php
Labels: chore

#6876 Fix infolists active tab
  packages/infolists/resources/views/components/tabs.blade.php
Labels: bug

#6874 Fix make panel command
  packages/panels/src/Commands/MakePanelCommand.php
Labels: bug

#6877 Support state
  packages/infolists/docs/03-entries/01-getting-started.md
  packages/infolists/src/Components/Concerns/HasState.php
  packages/tables/docs/03-columns/01-getting-started.md
  packages/tables/docs/03-columns/02-text.md
  packages/tables/src/Columns/Concerns/HasState.php
  packages/tables/src/Columns/TextColumn.php
  tests/src/Tables/Fixtures/PostsTable.php
Labels: enhancement
