Repository filamentphp/filament, pull requests merged in 2024-05, with the labels that each got.

#12559 Added missed Ukrainian translations
  packages/panels/resources/lang/uk/layout.php
  packages/panels/resources/lang/uk/pages/dashboard.php
  packages/panels/resources/lang/uk/unsaved-changes-alert.php
Labels: i18n

#12568 add missing zh_CN lang for table
  packages/tables/resources/lang/zh_CN/table.php
Labels: i18n

#12572 Fix documentation about read-only
  packages/forms/docs/03-fields/15-textarea.md
Labels: documentation

#12582 Fix for bug 12580
  packages/tables/resources/views/index.blade.php
Labels: bug

#12593 Make SpatieMediaLibraryFileUpload component more robust if media is null
  packages/forms/resources/lang/cs/components.php
  packages/forms/src/Components/Concerns/CanBeValidated.php
  packages/panels/resources/lang/uk/layout.php
  packages/panels/resources/lang/uk/pages/dashboard.php
  packages/spatie-laravel-media-library-plugin/src/Forms/Components/SpatieMediaLibraryFileUpload.php
  packages/support/resources/lang/cs/components/pagination.php
  packages/support/resources/views/components/button/index.blade.php
  packages/tables/resources/lang/cs/table.php
Labels: bug

#12549 feat: added global search suffix
  packages/panels/docs/03-resources/08-global-search.md
  packages/panels/resources/views/components/global-search/field.blade.php
  packages/panels/src/FilamentManager.php
  packages/panels/src/Panel/Concerns/HasGlobalSearch.php
  packages/support/resources/views/components/button/index.blade.php
  packages/support/src/Enums/Platform.php
Labels: enhancement

#12571 bugfix: stream_get_contents retrieves content in bytes, which may result in unexpected content
  packages/actions/src/Concerns/CanImportRecords.php
Labels: bug

#12601 Fix disabled state classes on icon button action
  packages/support/resources/views/components/icon-button.blade.php
Labels: bug

#12642 Slovenian translation
  packages/notifications/resources/lang/sl/database.php
  packages/panels/resources/lang/sl/global-search.php
  packages/panels/resources/lang/sl/layout.php
  packages/panels/resources/lang/sl/pages/auth/edit-profile.php
  packages/panels/resources/lang/sl/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/sl/pages/auth/login.php
  packages/panels/resources/lang/sl/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/sl/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/sl/pages/auth/register.php
  packages/panels/resources/lang/sl/pages/dashboard.php
  packages/panels/resources/lang/sl/pages/tenancy/edit-tenant-profile.php
  packages/panels/resources/lang/sl/resources/pages/create-record.php
  packages/panels/resources/lang/sl/resources/pages/edit-record.php
  packages/panels/resources/lang/sl/resources/pages/list-records.php
  packages/panels/resources/lang/sl/resources/pages/view-record.php
  packages/panels/resources/lang/sl/unsaved-changes-alert.php
  packages/panels/resources/lang/sl/widgets/account-widget.php
  packages/panels/resources/lang/sl/widgets/filament-info-widget.php
  packages/tables/resources/lang/sl/filters/query-builder.php
  packages/tables/resources/lang/sl/table.php
Labels: i18n

#12635 Improving Thai language translation add adding missing translation.
  packages/actions/resources/lang/th/associate.php
  packages/actions/resources/lang/th/attach.php
  packages/actions/resources/lang/th/create.php
  packages/actions/resources/lang/th/delete.php
  packages/actions/resources/lang/th/detach.php
  packages/actions/resources/lang/th/dissociate.php
  packages/actions/resources/lang/th/edit.php
  packages/actions/resources/lang/th/force-delete.php
  packages/actions/resources/lang/th/import.php
  packages/actions/resources/lang/th/replicate.php
  packages/actions/resources/lang/th/restore.php
  packages/forms/resources/lang/th/components.php
  packages/panels/resources/lang/th/global-search.php
  packages/panels/resources/lang/th/layout.php
  packages/panels/resources/lang/th/pages/auth/edit-profile.php
  packages/panels/resources/lang/th/pages/tenancy/edit-tenant-profile.php
  packages/panels/resources/lang/th/resources/pages/create-record.php
  packages/panels/resources/lang/th/resources/pages/edit-record.php
  packages/panels/resources/lang/th/resources/pages/view-record.php
  packages/panels/resources/lang/th/widgets/filament-info-widget.php
  packages/support/resources/lang/th/components/copyable.php
  packages/tables/resources/lang/th/table.php
Labels: i18n

#12630 Update ClearCachedComponentsCommmand Description
  packages/panels/src/Commands/ClearCachedComponentsCommand.php
Labels: bug

#12627 feat: loading section customizable height
  packages/panels/src/Resources/RelationManagers/RelationManager.php
  packages/support/resources/views/components/loading-section.blade.php
  packages/support/src/Concerns/CanBeLazy.php
  packages/widgets/src/Widget.php
Labels: enhancement

#12650 Adjust description text to the trending down arrow
  packages/widgets/docs/02-stats-overview.md
Labels: documentation

#12651 Nested resources
  packages/panels/resources/views/components/resources/relation-managers.blade.php
  packages/panels/src/Pages/Concerns/ExposesTableToWidgets.php
  packages/panels/src/Resources/Pages/Concerns/CanAuthorizeResourceAccess.php
  packages/panels/src/Resources/Pages/Concerns/InteractsWithParentRecord.php
  packages/panels/src/Resources/Pages/Concerns/InteractsWithRecord.php
  packages/panels/src/Resources/Pages/CreateRecord.php
  packages/panels/src/Resources/Pages/EditRecord.php
  packages/panels/src/Resources/Pages/ListRecords.php
  packages/panels/src/Resources/Pages/ManageRecords.php
  packages/panels/src/Resources/Pages/Page.php
  packages/panels/src/Resources/Pages/ViewRecord.php
  packages/panels/src/Resources/ParentResourceRegistration.php
  packages/panels/src/Resources/RelationManagers/RelationManager.php
  packages/panels/src/Resources/Resource.php
  packages/panels/src/Resources/Resource/Concerns/BelongsToCluster.php
  packages/panels/src/Resources/Resource/Concerns/BelongsToParent.php
  packages/panels/src/Resources/Resource/Concerns/BelongsToTenant.php
  packages/panels/src/Resources/Resource/Concerns/CanGenerateUrls.php
  packages/panels/src/Resources/Resource/Concerns/HasAuthorization.php
  packages/panels/src/Resources/Resource/Concerns/HasBreadcrumbs.php
  packages/panels/src/Resources/Resource/Concerns/HasGlobalSearch.php
  packages/panels/src/Resources/Resource/Concerns/HasLabels.php
  packages/panels/src/Resources/Resource/Concerns/HasNavigation.php
  packages/panels/src/Resources/Resource/Concerns/HasPages.php
  packages/panels/src/Resources/Resource/Concerns/HasRoutes.php
  packages/panels/src/Widgets/Concerns/InteractsWithPageTable.php
Labels: enhancement

#12653 Update 08-global-search.md
  packages/panels/docs/03-resources/08-global-search.md
Labels: documentation

#12656 Inline global search field suffix
  packages/panels/resources/views/components/global-search/field.blade.php
Labels: enhancement

#12682 Norwegian translation update and fix
  packages/forms/resources/lang/no/components.php
  packages/panels/resources/lang/no/layout.php
  packages/panels/resources/lang/no/pages/auth/edit-profile.php
  packages/panels/resources/lang/no/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/no/pages/auth/login.php
  packages/panels/resources/lang/no/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/no/pages/auth/register.php
  packages/panels/resources/lang/no/unsaved-changes-alert.php
  packages/support/resources/lang/no/components/pagination.php
  packages/tables/resources/lang/no/table.php
Labels: i18n

#12674 Add missing support for extra item actions in simple repeater
  packages/forms/resources/views/components/repeater/simple.blade.php
Labels: enhancement

#12685 Check login() method exists, punt to setUser()
  packages/actions/src/Exports/Jobs/ExportCsv.php
  packages/actions/src/Imports/Jobs/ImportCsv.php
  packages/support/resources/views/components/button/index.blade.php
Labels: bug

#12695 update: Japanese translation update and fix
  packages/actions/resources/lang/ja/export.php
  packages/actions/resources/lang/ja/import.php
  packages/forms/resources/lang/ja/components.php
  packages/infolists/resources/lang/ja/components.php
  packages/panels/resources/lang/ja/layout.php
  packages/panels/resources/lang/ja/pages/dashboard.php
  packages/panels/resources/lang/ja/unsaved-changes-alert.php
  packages/support/resources/lang/ja/components/pagination.php
  packages/tables/resources/lang/ja/table.php
Labels: i18n

#12696 document: Adding command to publish missing translation files
  packages/panels/docs/01-installation.md
Labels: documentation, i18n

#12694 Add afterInit hook
  packages/forms/dist/components/markdown-editor.js
  packages/forms/dist/index.css
  packages/forms/resources/js/components/markdown-editor.js
  packages/support/dist/index.css
  packages/support/resources/views/components/button/index.blade.php
Labels: enhancement

#12672 Fix bug #8870
  packages/support/resources/views/components/badge.blade.php
  packages/support/resources/views/components/button/index.blade.php
  packages/support/resources/views/components/dropdown/list/item.blade.php
  packages/support/resources/views/components/icon-button.blade.php
  packages/support/resources/views/components/link.blade.php
Labels: bug

#12707 update infolist documentations
  packages/infolists/docs/03-entries/01-getting-started.md
Labels: documentation

#12660 Actually hide hidden item actions
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/repeater/index.blade.php
  packages/forms/resources/views/components/repeater/simple.blade.php
Labels: bug

#12711 Feat: Add search value to Select field's relationship modifyQueryUsing
  packages/forms/docs/03-fields/03-select.md
  packages/forms/src/Components/Select.php
  packages/support/resources/views/components/button/index.blade.php
Labels: enhancement

#12712 Remove inlineLabel() call from inline() in Radio
  docs-assets/app/app/Livewire/Forms/FieldsDemo.php
  docs-assets/screenshots/images/dark/forms/fields/radio/inline-under-label.jpg
  docs-assets/screenshots/images/dark/forms/fields/radio/inline.jpg
  docs-assets/screenshots/images/light/forms/fields/radio/inline-under-label.jpg
  docs-assets/screenshots/images/light/forms/fields/radio/inline.jpg
  docs-assets/screenshots/schema.js
  packages/forms/docs/03-fields/07-radio.md
  packages/forms/docs/03-fields/18-toggle-buttons.md
  packages/forms/docs/10-upgrade-guide.md
  packages/forms/src/Components/Radio.php
Labels: chore

#12715 Trix v2 - update
  packages/forms/dist/components/rich-editor.js
  packages/forms/resources/js/components/rich-editor.js
  packages/forms/resources/views/components/rich-editor.blade.php
Labels: bug

#12720 Update vi translations
  packages/panels/resources/lang/vi/layout.php
  packages/panels/resources/lang/vi/unsaved-changes-alert.php
Labels: i18n

#12719 fix: Column still hidden when it's not toggleable anymore
  packages/tables/src/Columns/Concerns/CanBeToggled.php
Labels: bug

#12725 Update item.blade.php
  packages/support/resources/views/components/tabs/item.blade.php
Labels: bug

#12734 Fix summaries error in MSSQL Environment
  packages/tables/src/Columns/Summarizers/Summarizer.php
Labels: bug

#12738 Add download explanation to export action started language.
  packages/actions/resources/lang/en/export.php
  packages/support/resources/views/components/button/index.blade.php
  packages/tables/src/Columns/Summarizers/Summarizer.php
Labels: i18n

#12748 Added no language import for date-time-picker
  packages/forms/dist/components/date-time-picker.js
  packages/forms/resources/js/components/date-time-picker.js
Labels: i18n

#12767 Minor fixes on Catalan translations
  packages/tables/resources/lang/ca/table.php
Labels: i18n

#12770 Rich Editor - Resolving State Update Issue
  packages/forms/dist/components/rich-editor.js
  packages/forms/resources/js/components/rich-editor.js
Labels: bug

#12772 BaseFileUpload.php: No custom validation message (for mimetypes)
  packages/forms/src/Components/BaseFileUpload.php
Labels: bug

#12788 Update fi translation
  packages/actions/resources/lang/fi/export.php
  packages/panels/resources/lang/fi/layout.php
  packages/panels/resources/lang/fi/unsaved-changes-alert.php
Labels: i18n

#12797 Make refreshFormData public
  packages/panels/src/Resources/Pages/EditRecord.php
  packages/panels/src/Resources/Pages/ViewRecord.php
Labels: enhancement

#12800 fix: Pivot table sync not respecting query scopes
  packages/forms/src/Components/CheckboxList.php
  packages/forms/src/Components/Select.php
Labels: bug

#12803 Change type hint for chart data
  packages/widgets/src/StatsOverviewWidget/Stat.php
Labels: bug

#12804 add param name
  packages/widgets/src/StatsOverviewWidget/Stat.php
Labels: bug

#12805 Update Swedish translations
  packages/actions/resources/lang/sv/export.php
  packages/panels/resources/lang/sv/layout.php
  packages/panels/resources/lang/sv/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/sv/unsaved-changes-alert.php
Labels: i18n

#12813 Fix footer actions being rendered outside viewport in image editor on mobile devices
  packages/forms/resources/views/components/file-upload.blade.php
Labels: bug

#12819 fix: State overwritten without state path
  packages/forms/src/Components/Concerns/HasState.php
Labels: bug

#12821 fix: Summarize pivot column with duplicate name
  packages/tables/src/Columns/Summarizers/Summarizer.php
Labels: bug

#12687 Allow defaultSort to accept Livewire
  packages/tables/src/Concerns/CanSortRecords.php
  packages/tables/src/Table/Concerns/CanSortRecords.php
Labels: enhancement

#12782 Feat: Extra field wrapper attributes
  packages/forms/docs/03-fields/01-getting-started.md
  packages/forms/resources/views/components/field-wrapper/index.blade.php
  packages/forms/src/Components/Component.php
  packages/forms/src/Components/Concerns/HasExtraFieldWrapperAttributes.php
  packages/infolists/docs/03-entries/01-getting-started.md
  packages/infolists/resources/views/components/entry-wrapper/index.blade.php
  packages/infolists/src/Components/Component.php
  packages/infolists/src/Components/Concerns/HasExtraEntryWrapperAttributes.php
Labels: enhancement

#12835 Docs: Added `static` to example `Importer::getColumns()` method
  packages/actions/docs/07-prebuilt-actions/08-import.md
Labels: documentation

#12829 feat: add support to override media model on spatie media file upload
  packages/spatie-laravel-media-library-plugin/src/Forms/Components/SpatieMediaLibraryFileUpload.php
Labels: enhancement

#12836 Moves nepali language translations from np directory to ne
  packages/actions/resources/lang/ne/associate.php
  packages/actions/resources/lang/ne/attach.php
  packages/actions/resources/lang/ne/create.php
  packages/actions/resources/lang/ne/delete.php
  packages/actions/resources/lang/ne/detach.php
  packages/actions/resources/lang/ne/dissociate.php
  packages/actions/resources/lang/ne/edit.php
  packages/actions/resources/lang/ne/force-delete.php
  packages/actions/resources/lang/ne/group.php
  packages/actions/resources/lang/ne/modal.php
  packages/actions/resources/lang/ne/replicate.php
  packages/actions/resources/lang/ne/restore.php
  packages/actions/resources/lang/ne/view.php
  packages/forms/resources/lang/ne/components.php
  packages/infolists/resources/lang/ne/components.php
  packages/notifications/resources/lang/ne/database.php
  packages/panels/resources/lang/ne/global-search.php
  packages/panels/resources/lang/ne/layout.php
  packages/panels/resources/lang/ne/pages/auth/edit-profile.php
  packages/panels/resources/lang/ne/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/ne/pages/auth/login.php
  packages/panels/resources/lang/ne/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/ne/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/ne/pages/auth/register.php
  packages/panels/resources/lang/ne/pages/dashboard.php
  packages/panels/resources/lang/ne/pages/tenancy/edit-tenant-profile.php
  packages/panels/resources/lang/ne/resources/pages/create-record.php
  packages/panels/resources/lang/ne/resources/pages/edit-record.php
  packages/panels/resources/lang/ne/resources/pages/list-records.php
  packages/panels/resources/lang/ne/resources/pages/view-record.php
  packages/panels/resources/lang/ne/widgets/account-widget.php
  packages/panels/resources/lang/ne/widgets/filament-info-widget.php
  packages/spatie-laravel-settings-plugin/resources/lang/ne/pages/settings-page.php
  packages/spatie-laravel-translatable-plugin/resources/lang/ne/actions.php
  packages/support/resources/lang/ne/components/button.php
  packages/support/resources/lang/ne/components/copyable.php
  packages/support/resources/lang/ne/components/modal.php
  packages/support/resources/lang/ne/components/pagination.php
  packages/tables/resources/lang/ne/table.php
Labels: i18n

#12826 Feat: Adding grouping direction hidden method for the table grouping
  packages/tables/docs/08-grouping.md
  packages/tables/resources/views/components/groups.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Table/Concerns/CanGroupRecords.php
Labels: enhancement

#12832 Feature: Added the option to modals to prevent closing on escape key press
  packages/actions/docs/04-modals.md
  packages/actions/resources/views/components/modals.blade.php
  packages/actions/src/Concerns/CanOpenModal.php
  packages/support/resources/views/components/button/index.blade.php
  packages/support/resources/views/components/modal/index.blade.php
  packages/support/src/View/Components/Modal.php
Labels: enhancement

#12844 Fix: Missing Tenant Registration, Profile and User Profile page component registration
  packages/panels/src/Panel/Concerns/HasComponents.php
Labels: enhancement

#12866 lang: Add unsaved-changes-alert id translation
  packages/panels/resources/lang/id/unsaved-changes-alert.php
Labels: i18n

#12862 Improve Stats Overview Widgets documentation
  packages/widgets/docs/02-stats-overview.md
Labels: documentation

#12853 Fix: Incorrectly hiding the 'Select all X' table link
  packages/tables/resources/views/components/selection/indicator.blade.php
  packages/tables/resources/views/index.blade.php
Labels: bug

#12854 Fix: Hide toggleable hidden column in column toggle dropdown
  packages/tables/src/Columns/Concerns/CanBeToggled.php
Labels: bug

#12860 Fix: Visual bug when using selectCurrentPageOnly in combination with grouping
  packages/tables/resources/views/components/selection/group-checkbox.blade.php
  packages/tables/resources/views/index.blade.php
Labels: bug

#12873 security: File upload name preservation documentation notes
  packages/forms/docs/03-fields/09-file-upload.md
Labels: documentation

#12799 Check for Duplicate / Empty columns before attempting to submit import
  packages/actions/resources/lang/en/import.php
  packages/actions/src/Concerns/CanImportRecords.php
Labels: enhancement

#12884 add central kurdish language
  packages/forms/resources/js/components/file-upload.js
Labels: i18n

#12891 Move action lifecycle hooks
  packages/actions/src/Concerns/InteractsWithActions.php
  packages/forms/src/Concerns/HasFormComponentActions.php
  packages/infolists/src/Concerns/InteractsWithInfolists.php
  packages/tables/src/Concerns/HasActions.php
  packages/tables/src/Concerns/HasBulkActions.php
Labels: bug

#12879 Dispatch DatabaseNotificationsSent from import/export jobs
  packages/actions/src/Concerns/CanImportRecords.php
  packages/actions/src/Exports/Jobs/ExportCompletion.php
Labels: enhancement

#9431 Load `km` locale from FilePond
  packages/forms/resources/js/components/file-upload.js
Labels: i18n, blocked

#12904 Docs: Fix codeblocks
  packages/tables/docs/08-grouping.md
Labels: documentation

#12902 Docs: Fix the link in `Panel Builder` > `Getting Started`
  packages/panels/docs/02-getting-started.md
Labels: documentation

#12908 Allow table row record url to open in new tab
  packages/tables/docs/10-advanced.md
  packages/tables/resources/views/components/columns/column.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Table/Concerns/HasRecordUrl.php
Labels: enhancement

#12921 fix: Apply filters when the encoding is something other than UTF-8
  packages/actions/src/Concerns/CanImportRecords.php
Labels: bug

#12923 Allow to use html in checkboxlist labels
  packages/actions/src/Concerns/CanImportRecords.php
  packages/forms/src/Components/CheckboxList.php
  packages/support/resources/views/components/button/index.blade.php
Labels: enhancement

#12928 fixes missing default validation messages on FileUpload
  packages/forms/src/Components/BaseFileUpload.php
Labels: bug

#12933 Fix scroll to top in Wizard Form
  packages/forms/resources/views/components/wizard.blade.php
Labels: bug

#12937 Fix: import job class resolved from the container
  packages/actions/src/Concerns/CanImportRecords.php
Labels: bug

#12940 UploadedFile should be converted to TemporaryUploadedFile
  packages/forms/src/Testing/TestsForms.php
  tests/src/Forms/Components/FileUploadTest.php
Labels: bug

#12956 fix: add row wrong index after reorder
  packages/forms/resources/js/components/key-value.js
  packages/support/resources/views/components/button/index.blade.php
Labels: bug

#12958 Fix Groupable contract implementation order
  packages/actions/src/Action.php
  packages/actions/src/StaticAction.php
  packages/notifications/src/Actions/Action.php
  packages/tables/src/Actions/BulkAction.php
Labels: chore

#12966 Fix: ToggleButtons multiple empty state
  packages/forms/src/Components/ToggleButtons.php
Labels: bug

#12980 feature: Custom import file validation
  packages/actions/docs/07-prebuilt-actions/08-import.md
  packages/actions/src/Concerns/CanImportRecords.php
Labels: enhancement

#12981 Update 01-getting-started.md
  packages/infolists/docs/04-layout/01-getting-started.md
Labels: documentation

#12989 Update 03-database-notifications.md
  packages/notifications/docs/03-database-notifications.md
Labels: documentation

#12987 Add a regression test for the missing form data in the before hook
  .phpunit.cache/test-results
  packages/actions/src/Concerns/InteractsWithActions.php
  packages/forms/src/Concerns/HasFormComponentActions.php
  packages/forms/src/Concerns/HasState.php
  packages/infolists/src/Concerns/InteractsWithInfolists.php
  packages/support/resources/views/components/button/index.blade.php
  packages/tables/src/Concerns/HasActions.php
  packages/tables/src/Concerns/HasBulkActions.php
  tests/src/Actions/ActionTest.php
  tests/src/Actions/Fixtures/Pages/Actions.php
Labels: bug

#13010 fix: Select relationship BelongsToMany single
  packages/forms/src/Components/Select.php
  packages/support/resources/views/components/button/index.blade.php
Labels: bug

#13003 add `km` missing translations
  packages/actions/resources/lang/km/export.php
  packages/actions/resources/lang/km/import.php
  packages/infolists/resources/lang/km/components.php
  packages/panels/resources/lang/km/layout.php
  packages/panels/resources/lang/km/unsaved-changes-alert.php
  packages/support/resources/lang/km/components/pagination.php
Labels: i18n

#13011 Docs: Updates view page's testing description
  packages/panels/docs/14-testing.md
Labels: documentation

#12991 Add ability to disable autofocus on modals
  packages/actions/docs/04-modals.md
  packages/actions/resources/views/components/modals.blade.php
  packages/actions/src/Concerns/CanOpenModal.php
  packages/support/docs/09-blade-components/02-modal.md
  packages/support/resources/views/components/modal/index.blade.php
  packages/support/src/View/Components/Modal.php
  packages/tables/resources/views/components/filters/dialog.blade.php
Labels: enhancement

#13017 Fix: page title formatting
  packages/panels/resources/views/components/layout/base.blade.php
Labels: bug
