Repository filamentphp/filament, pull requests merged in 2024-11, with the labels that each got.

#14689 Update vi translations
  packages/actions/resources/lang/vi/import.php
  packages/tables/resources/lang/vi/table.php
Labels: i18n

#14688 Disallow EXIF data from uploads to be deleted when resizing
  packages/forms/resources/js/components/file-upload.js
Labels: bug

#14682 Add instructions for uploading large files to 09-file-upload.md
  packages/forms/docs/03-fields/09-file-upload.md
Labels: documentation

#14718 Fix/fixe missing translation for french
  packages/actions/resources/lang/fr/import.php
  packages/tables/resources/lang/fr/table.php
Labels: i18n

#14723 Use `local` instead of `public` disk for exports where available
  packages/actions/docs/01-installation.md
  packages/actions/docs/07-prebuilt-actions/09-export.md
  packages/actions/src/Exports/Exporter.php
  packages/panels/docs/01-installation.md
Labels: enhancement

#14722 Add missing Spanish translation for columns.label in table.php
  packages/tables/resources/lang/es/table.php
Labels: i18n

#14725 Fix/missing translation for arabic
  packages/actions/resources/lang/ar/import.php
  packages/tables/resources/lang/ar/table.php
Labels: i18n

#14726 Add backed enum for $abilities type
  packages/actions/src/Concerns/CanBeHidden.php
Labels: enhancement

#14717 Allow rendering HTML in CheckboxList label
  packages/forms/docs/03-fields/06-checkbox-list.md
  packages/forms/resources/views/components/checkbox-list.blade.php
  packages/forms/src/Components/CheckboxList.php
Labels: enhancement

#14739 Add missing Azeri translation
  packages/actions/resources/lang/az/import.php
  packages/forms/resources/lang/az/components.php
  packages/forms/resources/lang/az/validation.php
  packages/infolists/resources/lang/az/components.php
  packages/panels/resources/lang/az/layout.php
  packages/panels/resources/lang/az/pages/dashboard.php
  packages/panels/resources/lang/az/unsaved-changes-alert.php
  packages/support/resources/lang/az/components/pagination.php
  packages/tables/resources/lang/az/filters/query-builder.php
  packages/tables/resources/lang/az/table.php
Labels: i18n

#14710 Hide option Remove all filters
  packages/tables/resources/views/components/filters/indicators.blade.php
Labels: bug

#14752 Add missing Czech translation
  packages/actions/resources/lang/cs/import.php
  packages/tables/resources/lang/cs/table.php
Labels: i18n

#14753 Add missing German translation
  packages/actions/resources/lang/de/import.php
  packages/forms/resources/lang/de/components.php
  packages/tables/resources/lang/de/table.php
Labels: i18n

#14744 fix: global search in SPA mode when switching tenants
  packages/panels/resources/views/components/topbar/index.blade.php
  packages/tables/resources/lang/az/table.php
Labels: bug

#14756 Docs - Actions - Testing - Signature of setActionData()
  packages/actions/docs/09-testing.md
  packages/forms/docs/09-testing.md
  packages/infolists/docs/08-testing.md
Labels: documentation

#14767 Fixed bug on windows where the system puts \ instead of / while forming the s3 url (Import action).
  packages/actions/src/Concerns/CanImportRecords.php
Labels: bug

#14782 Widgets/StatsOverview: Add support for heading and description
  packages/widgets/docs/02-stats-overview.md
  packages/widgets/resources/views/stats-overview-widget.blade.php
  packages/widgets/src/StatsOverviewWidget.php
Labels: enhancement

#14790 Fix typo in 02-stats-overview.md
  packages/actions/resources/lang/ca/import.php
  packages/actions/src/Concerns/CanImportRecords.php
  packages/forms/resources/lang/ca/components.php
  packages/forms/resources/lang/de/components.php
  packages/tables/resources/lang/ca/table.php
  packages/widgets/docs/02-stats-overview.md
Labels: documentation

#14789 [Docs] Correct minor typo in widgets 02-stats-overview.md
  packages/widgets/docs/02-stats-overview.md
Labels: documentation

#14796 Add missing malay translation
  packages/actions/resources/lang/ms/import.php
  packages/forms/resources/lang/ms/components.php
  packages/panels/resources/lang/ms/layout.php
  packages/panels/resources/lang/ms/unsaved-changes-alert.php
  packages/tables/resources/lang/ms/table.php
Labels: i18n

#14795 Add missing section "Lifecycle hooks" for ViewRecord
  packages/panels/docs/03-resources/05-viewing-records.md
Labels: documentation

#14797 Improve table header cell design
  packages/tables/resources/views/index.blade.php
Labels: bug, ui

#14798 Added missing fields of Turkish language
  packages/forms/resources/lang/tr/components.php
Labels: i18n

#14799 Added missing file for Turkish language
  packages/forms/resources/lang/tr/validation.php
Labels: i18n

#14829 Fix typo in icons docs
  packages/support/docs/03-icons.md
Labels: documentation

#14815 Add nestedRecursiveRules to ToggleButtons
  packages/forms/resources/lang/tr/components.php
  packages/forms/src/Components/ToggleButtons.php
Labels: enhancement

#14834 Add missing Indonesian translations
  packages/actions/resources/lang/id/import.php
  packages/forms/resources/lang/id/components.php
  packages/tables/resources/lang/id/table.php
Labels: i18n

#14862 Fix toggle buttons CSS class
  packages/forms/resources/views/components/toggle-buttons/index.blade.php
Labels: bug

#14826 Add automatic scrolling of wizard steps
  packages/forms/resources/views/components/wizard.blade.php
Labels: enhancement, ux

#14838 Update indicator.blade.php - format $allSelectableRecordsCount
  packages/tables/resources/views/components/selection/indicator.blade.php
Labels: ui

#14854 Improve sync connection support for `ExportAction`
  packages/actions/src/Concerns/CanExportRecords.php
  packages/actions/src/Exports/Jobs/ExportCompletion.php
Labels: enhancement

#14874 Add input and affix CSS classes to input wrapper
  packages/support/resources/views/components/input/wrapper.blade.php
Labels: enhancement

#14877 Simplify color picker preview HTML
  packages/forms/resources/views/components/color-picker.blade.php
  packages/panels/dist/theme.css
Labels: enhancement

#14880 Add CSS class to tags input
  packages/forms/resources/views/components/tags-input.blade.php
Labels: enhancement

#14881 Add missing Slovak translations
  packages/actions/resources/lang/sk/import.php
  packages/tables/resources/lang/sk/table.php
Labels: i18n

#14899 Add missed UK translation
  packages/tables/resources/lang/uk/table.php
Labels: i18n

#14898 Make getLocaleLabelUsing usable in service provider
  packages/spatie-laravel-translatable-plugin/src/SpatieLaravelTranslatablePlugin.php
Labels: bug

#14878 Use Heroicons for rich editor and Markdown editor
  composer.lock
  packages/forms/dist/index.css
  packages/forms/resources/css/components/markdown-editor.css
  packages/forms/resources/views/components/rich-editor.blade.php
  packages/forms/resources/views/components/rich-editor/toolbar/button.blade.php
  packages/panels/dist/theme.css
  packages/support/composer.json
Labels: enhancement, ui

#14888 Update tabs/item.blade.php, add justify-center
  packages/support/resources/views/components/tabs/item.blade.php
Labels: bug, ui

#14896 Fix item validation
  packages/forms/src/Components/Concerns/CanLimitItemsLength.php
Labels: bug

#14906 Convert the CheckTranslationsCommand to use the new Laravel command components & Laravel Prompts
  docs-assets/app/app/Exceptions/Handler.php
  docs-assets/app/app/Http/Middleware/RedirectIfAuthenticated.php
  packages/infolists/src/Concerns/InteractsWithInfolists.php
  packages/support/src/Commands/CheckTranslationsCommand.php
Labels: enhancement

#14907 fix(i18n): adds/updates Persian (FA) translations for import/export actions
  packages/actions/resources/lang/fa/export.php
  packages/actions/resources/lang/fa/import.php
Labels: i18n

#14819 Support globally setting max simple page content width
  packages/panels/docs/09-configuration.md
  packages/panels/resources/views/components/layout/simple.blade.php
  packages/panels/src/FilamentManager.php
  packages/panels/src/Panel/Concerns/HasMaxContentWidth.php
Labels: enhancement

#14924 fix: Selection indicator large number formatting in some locales
  packages/tables/resources/views/components/selection/indicator.blade.php
Labels: bug

#14940 fix: Hash 2FA recovery codes
  packages/panels/src/MultiFactorAuthentication/GoogleTwoFactor/GoogleTwoFactorAuthentication.php
  tests/database/factories/UserFactory.php
  tests/src/Panels/Auth/MultiFactorAuthentication/EmailCode/EmailCodeAuthenticationChallengeTest.php
  tests/src/Panels/Auth/MultiFactorAuthentication/EmailCode/RemoveEmailCodeAuthenticationActionTest.php
  tests/src/Panels/Auth/MultiFactorAuthentication/EmailCode/SetUpEmailCodeAuthenticationActionTest.php
  tests/src/Panels/Auth/MultiFactorAuthentication/GoogleTwoFactor/Actions/RegenerateGoogleTwoFactorAuthenticationRecoveryCodesActionTest.php
  tests/src/Panels/Auth/MultiFactorAuthentication/GoogleTwoFactor/Actions/RemoveGoogleTwoFactorAuthenticationActionTest.php
  tests/src/Panels/Auth/MultiFactorAuthentication/GoogleTwoFactor/Actions/SetUpGoogleTwoFactorAuthenticationActionTest.php
  tests/src/Panels/Auth/MultiFactorAuthentication/GoogleTwoFactor/GoogleTwoFactorAuthenticationChallengeTest.php
Labels: bug

#14941 fix: SPA mode mobile sub navigation
  packages/panels/resources/views/components/page/sub-navigation/select.blade.php
  packages/panels/src/Pages/Auth/EditProfile.php
  packages/panels/src/Resources/Pages/CreateRecord.php
  packages/panels/src/Resources/Pages/EditRecord.php
Labels: bug

#14946 feature: Import BelongsToMany relationships
  packages/actions/docs/06-prebuilt-actions/08-import.md
  packages/actions/src/ImportAction.php
  packages/actions/src/Imports/ImportColumn.php
  packages/actions/src/Imports/Importer.php
  packages/panels/src/MultiFactorAuthentication/GoogleTwoFactor/GoogleTwoFactorAuthentication.php
Labels: enhancement
