Repository filamentphp/filament, pull requests merged in 2024-12, with the labels that each got.

#14952 feature: Table extra searchable() columns
  packages/spatie-laravel-translatable-plugin/src/SpatieLaravelTranslatableContentDriver.php
  packages/support/src/Contracts/TranslatableContentDriver.php
  packages/tables/docs/02-columns/01-overview.md
  packages/tables/src/Columns/Concerns/CanBeSearchable.php
  packages/tables/src/Concerns/CanSearchRecords.php
  packages/tables/src/Table/Concerns/CanSearchRecords.php
Labels: enhancement

#14957 fix: Import/export sync notifications
  packages/actions/src/Concerns/CanExportRecords.php
  packages/actions/src/Concerns/CanImportRecords.php
  packages/actions/src/Exports/Jobs/ExportCompletion.php
Labels: bug

#14944 fix: use app() to create a new instance of the password reset notific…
  packages/panels/src/Pages/Auth/PasswordReset/RequestPasswordReset.php
Labels: enhancement

#14958 fix: Imports exports multiple auth guard
  packages/actions/src/ActionsServiceProvider.php
  packages/actions/src/Concerns/CanExportRecords.php
  packages/actions/src/Exports/Enums/ExportFormat.php
  packages/actions/src/Exports/Http/Controllers/DownloadExport.php
  packages/actions/src/Exports/Jobs/ExportCompletion.php
  packages/actions/src/ImportAction.php
  packages/actions/src/Imports/Http/Controllers/DownloadImportFailureCsv.php
Labels: bug

#14964 feature: Schema component polling
  packages/schemas/resources/views/schema.blade.php
  packages/schemas/src/Components/Component.php
  packages/schemas/src/Components/Concerns/CanPoll.php
  packages/schemas/src/Concerns/InteractsWithSchemas.php
Labels: enhancement

#14965 feature: Disable search term splitting
  packages/panels/docs/02-resources/08-global-search.md
  packages/panels/src/Resources/Resource/Concerns/HasGlobalSearch.php
  packages/tables/docs/02-columns/01-overview.md
  packages/tables/src/Concerns/CanSearchRecords.php
  packages/tables/src/Table/Concerns/CanSearchRecords.php
Labels: enhancement

#14967 feature: Individual state tooltips
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Columns/CheckboxColumn.php
  packages/tables/src/Columns/ColorColumn.php
  packages/tables/src/Columns/Column.php
  packages/tables/src/Columns/Concerns/HasTooltip.php
  packages/tables/src/Columns/IconColumn.php
  packages/tables/src/Columns/ImageColumn.php
  packages/tables/src/Columns/SelectColumn.php
  packages/tables/src/Columns/TextColumn.php
  packages/tables/src/Columns/TextInputColumn.php
  packages/tables/src/Columns/ToggleColumn.php
Labels: enhancement

#14968 feature: Stats overview schema refactor
  docs-assets/app/public/css/filament/support/support.css
  packages/infolists/src/Components/Entry.php
  packages/panels/src/Widgets/Concerns/InteractsWithPageFilters.php
  packages/schemas/resources/views/components/section.blade.php
  packages/schemas/src/Components/Concerns/CanOpenUrl.php
  packages/schemas/src/Components/Section.php
  packages/support/dist/index.css
  packages/support/resources/css/components/section.css
  packages/support/resources/css/components/widgets/stats-overview-widget.css
  packages/support/resources/views/components/section/index.blade.php
  packages/widgets/composer.json
  packages/widgets/resources/views/stats-overview-widget.blade.php
  packages/widgets/resources/views/stats-overview-widget/stat.blade.php
  packages/widgets/src/StatsOverviewWidget.php
  packages/widgets/src/StatsOverviewWidget/Stat.php
Labels: enhancement

#14974 feature: Better relation manager tab customization
  packages/forms/src/Components/Builder.php
  packages/panels/docs/02-resources/07-relation-managers.md
  packages/panels/src/Resources/Pages/Concerns/HasRelationManagers.php
  packages/panels/src/Resources/RelationManagers/RelationGroup.php
  packages/panels/src/Resources/RelationManagers/RelationManager.php
  packages/tables/src/Filters/QueryBuilder/Forms/Components/RuleBuilder.php
Labels: enhancement

#14961 Disable cells while loadng
  packages/infolists/src/Components/Entry.php
  packages/panels/src/GlobalSearch/Providers/DefaultGlobalSearchProvider.php
  packages/tables/src/Columns/CheckboxColumn.php
  packages/tables/src/Columns/SelectColumn.php
  packages/tables/src/Columns/TextInputColumn.php
  packages/tables/src/Columns/ToggleColumn.php
  tests/src/Panels/Auth/MultiFactorAuthentication/EmailCode/EmailCodeAuthenticationChallengeTest.php
  tests/src/Panels/Auth/MultiFactorAuthentication/EmailCode/RemoveEmailCodeAuthenticationActionTest.php
  tests/src/Panels/Auth/MultiFactorAuthentication/EmailCode/SetUpEmailCodeAuthenticationActionTest.php
  tests/src/Panels/Auth/MultiFactorAuthentication/GoogleTwoFactor/Actions/RegenerateGoogleTwoFactorAuthenticationRecoveryCodesActionTest.php
  tests/src/Panels/Auth/MultiFactorAuthentication/GoogleTwoFactor/Actions/RemoveGoogleTwoFactorAuthenticationActionTest.php
  tests/src/Panels/Auth/MultiFactorAuthentication/GoogleTwoFactor/Actions/SetUpGoogleTwoFactorAuthenticationActionTest.php
  tests/src/Panels/Auth/MultiFactorAuthentication/GoogleTwoFactor/GoogleTwoFactorAuthenticationChallengeTest.php
Labels: enhancement

#14295 Allow webp upload in markdown editor
  packages/forms/resources/js/components/markdown-editor.js
Labels: enhancement, awaiting next major version

#14378 Support for custom validation messages in editable input columns
  packages/forms/resources/js/components/markdown-editor.js
  packages/tables/src/Columns/Concerns/CanBeValidated.php
Labels: enhancement, awaiting next major version

#14980 Update 01-getting-started.md Fix one typo
  packages/panels/docs/03-resources/01-getting-started.md
Labels: documentation

#14630 Updated: Repeater's `grid()` method can except closure as parameter
  packages/forms/src/Components/Builder.php
  packages/forms/src/Components/Concerns/HasContainerGridLayout.php
  packages/forms/src/Components/Repeater.php
  packages/infolists/src/Components/Concerns/HasContainerGridLayout.php
  packages/infolists/src/Components/RepeatableEntry.php
  packages/schemas/src/Components/Component.php
  packages/schemas/src/Components/Concerns/CanSpanColumns.php
  packages/schemas/src/Components/Concerns/HasContainerGridLayout.php
  packages/schemas/src/Concerns/HasColumns.php
  packages/support/src/Concerns/CanSpanColumns.php
  packages/tables/src/Columns/Column.php
  packages/tables/src/Columns/Concerns/CanSpanColumns.php
  packages/tables/src/Columns/Layout/Component.php
  packages/tables/src/Filters/QueryBuilder.php
Labels: enhancement, awaiting next major version

#14984 Add tables::header-cell.sort-button
  packages/support/docs/03-icons.md
  packages/tables/resources/views/components/header-cell.blade.php
Labels: enhancement

#14986 feature: Strict authorization mode
  packages/actions/src/Exports/Http/Controllers/DownloadExport.php
  packages/actions/src/Imports/Http/Controllers/DownloadImportFailureCsv.php
  packages/panels/docs/08-configuration.md
  packages/panels/src/Facades/Filament.php
  packages/panels/src/FilamentManager.php
  packages/panels/src/Panel/Concerns/HasAuth.php
  packages/panels/src/helpers.php
Labels: enhancement

#14998 fix: allow text-columns to read a nested array value
  packages/tables/resources/views/columns/text-column.blade.php
Labels: bug

#14962 Added sample generated image
  docs-assets/app/app/Livewire/Topbar.php
  docs-assets/app/resources/views/livewire/topbar.blade.php
  docs-assets/app/routes/web.php
  docs-assets/screenshots/images/dark/panels/navigation/user-menu.jpg
  docs-assets/screenshots/images/light/panels/navigation/user-menu.jpg
  docs-assets/screenshots/schema.js
  packages/panels/docs/06-navigation.md
Labels: documentation

#15000 Added attributes to livewire.blade file
  packages/forms/resources/views/components/livewire.blade.php
Labels: enhancement

#14993 fix: Modal heading getting too close to close button
  packages/panels/dist/theme.css
  packages/support/resources/views/components/modal/index.blade.php
Labels: bug, ui

#14978 Add labels for create and edit option actions in Select input to show label on sr-only for current local.
  packages/forms/resources/lang/ar/components.php
  packages/forms/resources/lang/en/components.php
  packages/forms/src/Components/Select.php
Labels: bug, i18n

#15004 Select table records by pivot if needed
  packages/tables/src/Concerns/HasBulkActions.php
Labels: bug

#15005 Add missing extra attributes to Livewire infolist component
  packages/infolists/resources/views/components/livewire.blade.php
Labels: enhancement

#15013 Add "flip" property to dropdown component
  packages/support/resources/views/components/dropdown/index.blade.php
Labels: enhancement

#15030 Fix padded appearance near sub-navigation select element
  packages/panels/resources/views/components/page/index.blade.php
Labels: bug, ui

#15024 Update 02-select.md
  packages/tables/docs/04-filters/02-select.md
Labels: documentation

#15046 Fix TagsInput closing filters when removing tag from list
  packages/forms/resources/views/components/tags-input.blade.php
Labels: bug

#15041 Fix `Route [login] not defined` error
  docs-assets/app/app/Http/Kernel.php
  docs-assets/app/app/Providers/Filament/AdminPanelProvider.php
  packages/panels/src/Http/Middleware/AuthenticateSession.php
  packages/support/stubs/DefaultPanelProvider.stub
  packages/support/stubs/PanelProvider.stub
  packages/upgrade/bin/create-filament-v3-panel-provider.php
  tests/src/AdminPanelProvider.php
  tests/src/CustomPanelProvider.php
  tests/src/DomainTenancyPanelProvider.php
  tests/src/MultiDomainPanel.php
  tests/src/SingleDomainPanel.php
  tests/src/SlugsPanelProvider.php
  tests/src/TenancyPanelProvider.php
Labels: bug

#15065 fix: handle tag switching for non-ASCII characters
  packages/forms/src/Components/Tabs/Tab.php
  packages/forms/src/Components/Wizard/Step.php
  packages/infolists/src/Components/Tabs/Tab.php
Labels: bug

#15074 Update Hungarian translation and fix typos
  packages/actions/resources/lang/hu/dissociate.php
  packages/actions/resources/lang/hu/export.php
  packages/actions/resources/lang/hu/import.php
  packages/forms/resources/lang/hu/components.php
  packages/panels/resources/lang/hu/global-search.php
  packages/panels/resources/lang/hu/layout.php
  packages/panels/resources/lang/hu/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/hu/pages/auth/login.php
  packages/panels/resources/lang/hu/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/hu/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/hu/pages/auth/register.php
  packages/panels/resources/lang/hu/unsaved-changes-alert.php
  packages/support/resources/lang/hu/components/pagination.php
  packages/tables/resources/lang/hu/filters/query-builder.php
  packages/tables/resources/lang/hu/table.php
Labels: i18n

#15064 DatePicker is set to readOnly(), but it still can clicked and open calendar popup
  packages/forms/resources/js/components/file-upload.js
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/panels/resources/views/components/unsaved-action-changes-alert.blade.php
Labels: bug

#15078 Refactor: To allow passing in a callback function to `assertTableActonDataSet` and `assertTableBulkActionDataSet`
  packages/tables/.stubs.php
  packages/tables/docs/12-testing.md
  packages/tables/src/TablesServiceProvider.php
  packages/tables/src/Testing/TestsActions.php
  packages/tables/src/Testing/TestsBulkActions.php
  tests/src/Tables/Actions/ActionTest.php
  tests/src/Tables/Actions/BulkActionTest.php
Labels: enhancement

#15089 Run optimize command under `filament` key in `artisan optimize`
  packages/support/src/SupportServiceProvider.php
Labels: bug

#15108 Fix table ui when all searchable colums hidden
  packages/tables/src/Table/Concerns/CanSearchRecords.php
Labels: bug

#15118 fix: Table column headers hidden on empty state
  packages/support/dist/index.css
  packages/support/resources/css/components/pagination.css
  packages/support/resources/css/components/tables/container.css
  packages/tables/dist/index.js
  packages/tables/resources/views/index.blade.php
Labels: bug

#15119 fix: Image column width method conflict
  packages/tables/docs/02-columns/04-image.md
  packages/tables/src/Columns/ImageColumn.php
Labels: bug

#15121 i18n: Switch NO language code to NB
  docs/09-upgrade-guide.md
  packages/actions/resources/lang/nb/associate.php
  packages/actions/resources/lang/nb/attach.php
  packages/actions/resources/lang/nb/create.php
  packages/actions/resources/lang/nb/delete.php
  packages/actions/resources/lang/nb/detach.php
  packages/actions/resources/lang/nb/dissociate.php
  packages/actions/resources/lang/nb/edit.php
  packages/actions/resources/lang/nb/export.php
  packages/actions/resources/lang/nb/force-delete.php
  packages/actions/resources/lang/nb/group.php
  packages/actions/resources/lang/nb/import.php
  packages/actions/resources/lang/nb/modal.php
  packages/actions/resources/lang/nb/replicate.php
  packages/actions/resources/lang/nb/restore.php
  packages/actions/resources/lang/nb/view.php
  packages/forms/dist/components/date-time-picker.js
  packages/forms/dist/components/file-upload.js
  packages/forms/resources/js/components/date-time-picker.js
  packages/forms/resources/js/components/file-upload.js
  packages/forms/resources/lang/nb/components.php
  packages/forms/resources/lang/nb/validation.php
  packages/infolists/resources/lang/nb/components.php
  packages/notifications/resources/lang/nb/database.php
  packages/panels/resources/lang/nb/global-search.php
  packages/panels/resources/lang/nb/layout.php
  packages/panels/resources/lang/nb/pages/auth/edit-profile.php
  packages/panels/resources/lang/nb/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/nb/pages/auth/login.php
  packages/panels/resources/lang/nb/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/nb/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/nb/pages/auth/register.php
  packages/panels/resources/lang/nb/pages/dashboard.php
  packages/panels/resources/lang/nb/pages/tenancy/edit-tenant-profile.php
  packages/panels/resources/lang/nb/resources/pages/create-record.php
  packages/panels/resources/lang/nb/resources/pages/edit-record.php
  packages/panels/resources/lang/nb/resources/pages/list-records.php
  packages/panels/resources/lang/nb/resources/pages/view-record.php
  packages/panels/resources/lang/nb/unsaved-changes-alert.php
  packages/panels/resources/lang/nb/widgets/account-widget.php
  packages/panels/resources/lang/nb/widgets/filament-info-widget.php
  packages/schemas/resources/lang/nb/components.php
  packages/spatie-laravel-settings-plugin/resources/lang/nb/pages/settings-page.php
  packages/spatie-laravel-translatable-plugin/resources/lang/nb/actions.php
  packages/support/resources/lang/nb/components/button.php
  packages/support/resources/lang/nb/components/copyable.php
  packages/support/resources/lang/nb/components/modal.php
  packages/support/resources/lang/nb/components/pagination.php
  packages/tables/resources/lang/nb/filters/query-builder.php
  packages/tables/resources/lang/nb/table.php
Labels: i18n

#15123 #14355 Upgrade vanilla-colorful to latest version
  package-lock.json
  package.json
  packages/forms/dist/components/color-picker.js
Labels: enhancement

#14970 fix: Disabled button tooltip
  docs-assets/app/public/css/filament/support/support.css
  packages/actions/src/Action.php
  packages/actions/src/ActionGroup.php
  packages/forms/dist/components/color-picker.js
  packages/panels/src/Pages/Concerns/InteractsWithHeaderActions.php
  packages/support/dist/index.css
  packages/support/resources/css/components/badge.css
  packages/support/resources/css/components/button.css
  packages/support/resources/css/components/dropdown/list/item.css
  packages/support/resources/css/components/icon-button.css
  packages/support/resources/css/components/link.css
  packages/support/resources/views/components/badge.blade.php
  packages/support/resources/views/components/button/index.blade.php
  packages/support/resources/views/components/dropdown/list/item.blade.php
  packages/support/resources/views/components/icon-button.blade.php
  packages/support/resources/views/components/link.blade.php
  packages/support/src/Concerns/HasBadge.php
  packages/tables/src/Table/Concerns/HasActions.php
Labels: bug, awaiting next major version

#15133 feature: Settings page edit permission
  packages/panels/src/Commands/MakeClusterCommand.php
  packages/panels/src/Commands/MakePageCommand.php
  packages/spatie-laravel-settings-plugin/src/Commands/MakeSettingsPageCommand.php
  packages/spatie-laravel-settings-plugin/src/Pages/SettingsPage.php
  packages/support/src/Commands/Concerns/CanAskForRelatedModel.php
  packages/support/src/Commands/Concerns/HasResourcesLocation.php
  packages/widgets/src/Commands/MakeWidgetCommand.php
Labels: enhancement

#15134 Improve relation manager/relation page generation
  packages/forms/src/Commands/FileGenerators/Concerns/CanGenerateModelForms.php
  packages/panels/src/Commands/FileGenerators/Resources/Concerns/CanGenerateResourceForms.php
  packages/panels/src/Commands/FileGenerators/Resources/Concerns/CanGenerateResourceTables.php
  packages/panels/src/Commands/FileGenerators/Resources/Pages/ResourceManageRelatedRecordsPageClassGenerator.php
  packages/panels/src/Commands/FileGenerators/Resources/RelationManagerClassGenerator.php
  packages/panels/src/Commands/MakePageCommand.php
  packages/panels/src/Commands/MakeRelationManagerCommand.php
  packages/panels/src/Resources/Concerns/InteractsWithRelationshipTable.php
  packages/panels/src/Resources/Pages/ManageRelatedRecords.php
  packages/panels/src/Resources/RelationManagers/RelationManager.php
  packages/tables/src/Commands/FileGenerators/Concerns/CanGenerateModelTables.php
Labels: enhancement

#15135 fix: Modal heading case consistency
  packages/actions/src/AssociateAction.php
  packages/actions/src/AttachAction.php
  packages/actions/src/Concerns/CanExportRecords.php
  packages/actions/src/Concerns/InteractsWithRecord.php
  packages/actions/src/CreateAction.php
  packages/actions/src/DeleteBulkAction.php
  packages/actions/src/DetachBulkAction.php
  packages/actions/src/DissociateBulkAction.php
  packages/actions/src/ForceDeleteBulkAction.php
  packages/actions/src/ImportAction.php
  packages/actions/src/RestoreBulkAction.php
Labels: bug

#15137 fix: Do not return default panel as current automatically
  docs-assets/app/app/Livewire/Topbar.php
  docs/09-upgrade-guide.md
  packages/panels/src/Clusters/Cluster.php
  packages/panels/src/Commands/MakeUserCommand.php
  packages/panels/src/Exceptions/NoDefaultPanelSetException.php
  packages/panels/src/Facades/Filament.php
  packages/panels/src/FilamentManager.php
  packages/panels/src/Http/Controllers/RedirectToHomeController.php
  packages/panels/src/Http/Controllers/RedirectToTenantController.php
  packages/panels/src/Http/Middleware/Authenticate.php
  packages/panels/src/Http/Middleware/IdentifyTenant.php
  packages/panels/src/Navigation/NavigationManager.php
  packages/panels/src/Pages/Auth/EditProfile.php
  packages/panels/src/Pages/Auth/Login.php
  packages/panels/src/Pages/Concerns/CanUseDatabaseTransactions.php
  packages/panels/src/Pages/Page.php
  packages/panels/src/Pages/Tenancy/EditTenantProfile.php
  packages/panels/src/PanelRegistry.php
  packages/panels/src/Resources/RelationManagers/RelationManager.php
  packages/panels/src/Resources/Resource/Concerns/BelongsToTenant.php
  packages/panels/src/Resources/Resource/Concerns/HasNavigation.php
  packages/panels/src/Resources/Resource/Concerns/HasRoutes.php
  tests/src/Panels/Auth/MultiFactorAuthentication/EmailCode/EmailCodeAuthenticationChallengeTest.php
  tests/src/Panels/Auth/MultiFactorAuthentication/EmailCode/RemoveEmailCodeAuthenticationActionTest.php
  tests/src/Panels/Auth/MultiFactorAuthentication/EmailCode/SetUpEmailCodeAuthenticationActionTest.php
  tests/src/Panels/Auth/MultiFactorAuthentication/GoogleTwoFactor/Actions/RegenerateGoogleTwoFactorAuthenticationRecoveryCodesActionTest.php
  tests/src/Panels/Auth/MultiFactorAuthentication/GoogleTwoFactor/Actions/RemoveGoogleTwoFactorAuthenticationActionTest.php
  tests/src/Panels/Auth/MultiFactorAuthentication/GoogleTwoFactor/Actions/SetUpGoogleTwoFactorAuthenticationActionTest.php
  tests/src/Panels/Auth/MultiFactorAuthentication/GoogleTwoFactor/GoogleTwoFactorAuthenticationChallengeTest.php
  tests/src/Panels/Auth/RegisterTest.php
  tests/src/Panels/Commands/Legacy/LegacyMakePageCommandTest.php
  tests/src/Panels/Commands/Legacy/LegacyMakeRelationManagerCommandTest.php
  tests/src/Panels/Commands/MakePageCommandTest.php
  tests/src/Panels/Commands/MakeRelationManagerCommandTest.php
  tests/src/Panels/Commands/MakeResourceCommandTest.php
  tests/src/Panels/GlobalSearch/GlobalSearchTest.php
  tests/src/Panels/Navigation/NavigationBuilderTest.php
  tests/src/Panels/Navigation/NavigationTest.php
  tests/src/Panels/Resources/Pages/CreateRecordTest.php
  tests/src/Panels/Resources/Pages/EditRecordTest.php
  tests/src/Panels/Resources/Pages/ListRecordsTest.php
  tests/src/Panels/Resources/Pages/ViewRecordTest.php
Labels: bug

#15154 Fix missing comma in docs
  packages/forms/docs/09-testing.md
Labels: documentation

#15161 correct wrong label in CKB and KU translation
  packages/actions/resources/lang/ckb/create.php
  packages/actions/resources/lang/ku/create.php
Labels: i18n

#15170 Add missing malay translations
  packages/actions/resources/lang/ms/import.php
  packages/forms/resources/lang/ms/components.php
Labels: i18n

#15159 Disable escaping for attribute merging
  packages/actions/src/Concerns/HasExtraModalWindowAttributes.php
  packages/forms/resources/views/components/field-wrapper/index.blade.php
  packages/forms/src/Components/Concerns/HasExtraFieldWrapperAttributes.php
  packages/forms/src/Components/Concerns/HasExtraInputAttributes.php
  packages/forms/src/Components/DateTimePicker.php
  packages/forms/src/Components/Repeater.php
  packages/infolists/resources/views/components/entry-wrapper/index.blade.php
  packages/infolists/src/Components/Concerns/HasExtraEntryWrapperAttributes.php
  packages/panels/src/Navigation/Concerns/HasExtraSidebarAttributes.php
  packages/panels/src/Navigation/Concerns/HasExtraTopbarAttributes.php
  packages/support/src/Concerns/HasExtraAlpineAttributes.php
  packages/support/src/Concerns/HasExtraAttributes.php
  packages/tables/resources/views/components/search-field.blade.php
  packages/tables/src/Columns/Column.php
  packages/tables/src/Columns/Concerns/HasExtraCellAttributes.php
  packages/tables/src/Columns/Concerns/HasExtraHeaderAttributes.php
  packages/tables/src/Columns/ImageColumn.php
  packages/tables/src/Columns/TextColumn.php
  packages/widgets/resources/views/stats-overview-widget.blade.php
  tests/src/Fixtures/Resources/PostCategories/PostCategoryResource.php
  tests/src/Fixtures/Resources/Posts/PostResource.php
  tests/src/Fixtures/Resources/Shop/Products/ProductResource.php
  tests/src/Fixtures/Resources/Users/UserResource.php
Labels: bug

#15178 Upgrade to Choices.js v11
  composer.lock
  package-lock.json
  package.json
  packages/forms/dist/components/select.js
  packages/forms/resources/js/components/select.js
  packages/forms/src/Components/Concerns/CanBeValidated.php
Labels: bug

#15192 feature: Rate limit actions
  packages/actions/docs/07-advanced.md
  packages/actions/resources/lang/en/notifications.php
  packages/actions/src/Action.php
  packages/actions/src/Concerns/CanBeRateLimited.php
  packages/actions/src/Concerns/CanNotify.php
  packages/actions/src/Concerns/InteractsWithActions.php
  packages/panels/src/MultiFactorAuthentication/EmailCode/Actions/RemoveEmailCodeAuthenticationAction.php
  packages/panels/src/MultiFactorAuthentication/EmailCode/Actions/SetUpEmailCodeAuthenticationAction.php
  packages/panels/src/MultiFactorAuthentication/GoogleTwoFactor/Actions/RegenerateGoogleTwoFactorAuthenticationRecoveryCodesAction.php
  packages/panels/src/MultiFactorAuthentication/GoogleTwoFactor/Actions/RemoveGoogleTwoFactorAuthenticationAction.php
  packages/panels/src/MultiFactorAuthentication/GoogleTwoFactor/Actions/SetUpGoogleTwoFactorAuthenticationAction.php
  tests/src/Actions/RateLimitingTest.php
  tests/src/Fixtures/Pages/Actions.php
Labels: enhancement

#15209 Update Polish translation
  packages/actions/resources/lang/pl/import.php
  packages/forms/resources/lang/pl/components.php
  packages/forms/resources/lang/pl/validation.php
  packages/infolists/resources/lang/pl/components.php
  packages/panels/resources/lang/pl/layout.php
  packages/panels/resources/lang/pl/pages/dashboard.php
  packages/panels/resources/lang/pl/unsaved-changes-alert.php
  packages/spatie-laravel-settings-plugin/resources/lang/pl/pages/settings-page.php
  packages/spatie-laravel-translatable-plugin/resources/lang/pl/actions.php
  packages/support/resources/lang/pl/components/pagination.php
  packages/tables/resources/lang/pl/filters/query-builder.php
  packages/tables/resources/lang/pl/table.php
Labels: i18n

#15194 add livewire-rate-limiting version 2 for php 8.4 support
  composer.json
  packages/panels/composer.json
Labels: chore

#15187 fix(modal): incorrect heading margin
  packages/panels/dist/theme.css
  packages/support/resources/views/components/modal/index.blade.php
Labels: bug, ui
