Repository filamentphp/filament, pull requests merged in 2024-02, with the labels that each got.

#11196 add missing fa for import/export/components
  packages/actions/resources/lang/fa/export.php
  packages/actions/resources/lang/fa/import.php
  packages/forms/resources/lang/fa/components.php
Labels: i18n

#11148 Set table column width
  packages/tables/docs/03-columns/01-getting-started.md
  packages/tables/docs/03-columns/02-text.md
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Columns/Column.php
  packages/tables/src/Columns/Concerns/HasWidth.php
Labels: enhancement

#11164 Allow relationship filters using custom keys
  packages/tables/src/Filters/Concerns/HasRelationship.php
  packages/tables/src/Filters/SelectFilter.php
Labels: bug

#11096 Allow disabling of ->defaultSort()
  packages/tables/src/Concerns/CanSortRecords.php
Labels: bug

#11209 Add Zh_TW Action Translation
  packages/actions/resources/lang/zh_TW/export.php
  packages/actions/resources/lang/zh_TW/import.php
Labels: i18n

#11214 In ImageColumn's ring method: incorrect type string, should be int
  packages/tables/src/Columns/ImageColumn.php
Labels: bug

#11218 BP - add missing form translations for toggle and password fields
  packages/forms/resources/lang/fr/components.php
Labels: i18n

#11223 fix: Enabled options validation with group
  packages/forms/src/Components/Concerns/CanDisableOptions.php
Labels: bug

#11240 Update vi translations
  packages/actions/resources/lang/vi/export.php
  packages/forms/resources/lang/vi/components.php
  packages/infolists/resources/lang/vi/components.php
  packages/tables/resources/lang/vi/table.php
Labels: i18n

#11232 Add infolists zh_TW translation
  packages/infolists/resources/lang/zh_TW/components.php
Labels: i18n

#11248 Improve Turkish translation
  packages/actions/resources/lang/tr/create.php
  packages/forms/resources/lang/tr/components.php
Labels: i18n

#11233 Feat: Add the callback modify query using for the export native action to be able to filter the query
  packages/actions/src/Concerns/CanExportRecords.php
Labels: enhancement

#11252 Adds hook class for prose content
  packages/infolists/resources/views/components/text-entry.blade.php
Labels: enhancement

#11253 fix: EditProfile::getUrl()
  packages/panels/src/Pages/Auth/EditProfile.php
Labels: bug

#11257 Modal refactor: beta
  docs-assets/app/public/css/filament/filament/app.css
  packages/panels/dist/theme.css
  packages/support/resources/views/components/modal/index.blade.php
Labels: bug

#11259 feat: Make the ID of the record unique
  packages/actions/src/Exports/Jobs/PrepareCsvExport.php
Labels: bug

#11258 feature: Allow components to be cached
  packages/panels/docs/01-installation.md
  packages/panels/src/Commands/CacheComponentsCommand.php
  packages/panels/src/Commands/ClearCachedComponentsCommand.php
  packages/panels/src/FilamentServiceProvider.php
  packages/panels/src/Panel.php
  packages/panels/src/Panel/Concerns/HasComponents.php
  packages/panels/src/Panel/Concerns/HasId.php
  packages/support/config/filament.php
Labels: enhancement

#11271 Fix table grouping by BackedEnum
  packages/tables/src/Grouping/Group.php
Labels: bug

#11276 i18n: Missing Arabic translations
  packages/forms/resources/lang/ar/components.php
  packages/infolists/resources/lang/ar/components.php
  packages/tables/resources/lang/ar/table.php
Labels: i18n

#11275 Fix: Optional MorphToSelect does not set key column to null
  packages/forms/src/Components/Concerns/HasState.php
  packages/forms/src/Components/MorphToSelect.php
  packages/forms/src/Concerns/CanBeValidated.php
  packages/forms/src/Concerns/HasState.php
  tests/src/Forms/StateTest.php
Labels: bug

#11278 Pagination with links to the first and last pages
  packages/support/docs/03-icons.md
  packages/support/docs/09-blade-components/02-pagination.md
  packages/support/resources/lang/en/components/pagination.php
  packages/support/resources/views/components/pagination/index.blade.php
  packages/tables/docs/10-advanced.md
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Table/Concerns/CanPaginateRecords.php
Labels: enhancement

#11283 fix: Hidden link label
  packages/support/resources/views/components/link.blade.php
Labels: bug

#11288 Add zh_TW lang in database
  packages/notifications/resources/lang/zh_TW/database.php
Labels: i18n

#11290 Added missing german translation entries
  packages/actions/resources/lang/de/export.php
  packages/actions/resources/lang/de/import.php
  packages/forms/resources/lang/de/components.php
  packages/forms/resources/lang/de/validation.php
  packages/infolists/resources/lang/de/components.php
  packages/panels/resources/lang/de/layout.php
  packages/panels/resources/lang/de/pages/auth/login.php
  packages/panels/resources/lang/de/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/de/pages/auth/register.php
  packages/panels/resources/lang/de/pages/dashboard.php
  packages/support/resources/lang/de/components/pagination.php
  packages/tables/resources/lang/de/filters/query-builder.php
  packages/tables/resources/lang/de/table.php
Labels: i18n

#11292 Boost Octane performance further
  bootstrap/app.php
  packages/panels/src/Facades/Filament.php
  packages/panels/src/FilamentManager.php
  packages/panels/src/FilamentServiceProvider.php
  packages/panels/src/Navigation/NavigationManager.php
  packages/panels/src/Panel/Concerns/HasBreadcrumbs.php
  packages/panels/src/Panel/Concerns/HasNavigation.php
  packages/panels/src/Panel/Concerns/HasRoutes.php
  packages/panels/src/PanelRegistry.php
Labels: bug

#11303 Specify name for dispatched job batches within the Exporter & Importer classes
  packages/actions/docs/07-prebuilt-actions/08-import.md
  packages/actions/docs/07-prebuilt-actions/09-export.md
  packages/actions/src/Concerns/CanExportRecords.php
  packages/actions/src/Concerns/CanImportRecords.php
  packages/actions/src/Exports/Exporter.php
  packages/actions/src/Imports/Importer.php
Labels: enhancement

#11310 fix: Tenant profile getUrl()
  packages/panels/src/Pages/Tenancy/EditTenantProfile.php
Labels: bug

#11312 fix: Empty relationship results
  packages/infolists/src/Components/Concerns/HasState.php
  packages/support/src/Concerns/HasCellState.php
Labels: bug

#11132 Add supporting to initial audio or video in upload file field
  docs-assets/app/public/js/filament/forms/components/file-upload.js
  packages/forms/dist/components/file-upload.js
  packages/forms/resources/js/components/file-upload.js
Labels: bug

#11319 Added missing Malay translations
  packages/actions/resources/lang/ms/export.php
  packages/forms/resources/lang/ms/components.php
  packages/support/resources/lang/ms/components/pagination.php
  packages/tables/resources/lang/ms/table.php
Labels: i18n

#11321 Update Spanish pagination translations
  packages/support/resources/lang/es/components/pagination.php
Labels: i18n

#11322 Refine German translations for import and export action
  packages/actions/resources/lang/de/export.php
  packages/actions/resources/lang/de/import.php
Labels: i18n

#11336 Add `lineClamp()` API
  packages/forms/resources/lang/ms/components.php
  packages/infolists/docs/03-entries/02-text.md
  packages/infolists/resources/views/components/text-entry.blade.php
  packages/infolists/src/Components/TextEntry.php
  packages/support/src/Concerns/HasLineClamp.php
  packages/tables/docs/03-columns/02-text.md
  packages/tables/src/Columns/TextColumn.php
Labels: enhancement

#11334 added ressource route methods
  packages/panels/src/Resources/Resource.php
Labels: enhancement

#11317 Fix FileUpload `grid` layout
  docs-assets/app/public/css/filament/filament/app.css
  docs-assets/app/public/js/filament/forms/components/file-upload.js
  packages/forms/dist/components/file-upload.js
  packages/forms/resources/js/components/file-upload.js
  packages/forms/resources/views/components/file-upload.blade.php
  packages/forms/src/Components/FileUpload.php
Labels: bug

#11329 Save records with BelongsTo relations using the relation name without having to set fillable in the model
  packages/actions/src/CreateAction.php
  packages/actions/src/EditAction.php
  packages/forms/src/Components/Concerns/EntanglesStateWithSingularRelationship.php
  packages/forms/src/Components/Repeater.php
  packages/forms/src/Components/Select.php
  packages/panels/docs/02-getting-started.md
  packages/panels/docs/03-resources/11-security.md
  packages/panels/src/Pages/Auth/EditProfile.php
  packages/panels/src/Pages/Tenancy/EditTenantProfile.php
  packages/panels/src/Resources/Pages/CreateRecord.php
  packages/panels/src/Resources/Pages/EditRecord.php
  packages/spatie-laravel-translatable-plugin/src/Resources/Pages/CreateRecord/Concerns/Translatable.php
  packages/spatie-laravel-translatable-plugin/src/Resources/Pages/EditRecord/Concerns/Translatable.php
  packages/spatie-laravel-translatable-plugin/src/SpatieLaravelTranslatableContentDriver.php
  packages/tables/src/Actions/CreateAction.php
  packages/tables/src/Actions/EditAction.php
  packages/tables/src/Concerns/CanReorderRecords.php
Labels: bug

#11337 Allow MorphToSelect to be non-native
  packages/forms/docs/03-fields/03-select.md
  packages/forms/src/Components/Concerns/CanBeNative.php
  packages/forms/src/Components/DateTimePicker.php
  packages/forms/src/Components/MorphToSelect.php
  packages/forms/src/Components/Select.php
Labels: enhancement

#11343 Fix using view for page headings
  packages/panels/resources/views/components/header/index.blade.php
  packages/panels/resources/views/components/page/index.blade.php
Labels: bug

#11346 Use span instead of div for badges
  packages/support/resources/views/components/badge.blade.php
Labels: bug

#11330 Allow to inject current import & export column instance
  packages/actions/src/Exports/ExportColumn.php
  packages/actions/src/Imports/ImportColumn.php
Labels: bug

#11342 Proposal: Add helper command that fills out version numbers for github issues
  packages/panels/src/Commands/Aliases/MakeIssueCommand.php
  packages/panels/src/Commands/MakeIssueCommand.php
  packages/panels/src/FilamentServiceProvider.php
Labels: enhancement

#11017 Make entire repeater and builder item header collapsible
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/repeater/index.blade.php
Labels: enhancement

#11359 Add Czech translations for export functionality
  packages/actions/resources/lang/cs/export.php
Labels: i18n

#11360 Update `component-container.blade.php`: use `let` for block-scope variable assignment in `form-validation-error` listener
  packages/forms/resources/views/component-container.blade.php
Labels: bug

#11364 Update bug_report.yml
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: chore

#11348 Add a contributing page to the docs
  packages/support/docs/08-contributing.md
Labels: chore

#11368 Add Turkish Translations for Import/Export Action
  packages/actions/resources/lang/tr/export.php
  packages/actions/resources/lang/tr/import.php
Labels: i18n

#11366 Add Polish export/import translations
  packages/actions/resources/lang/pl/export.php
  packages/actions/resources/lang/pl/import.php
Labels: i18n

#11376 feature: Collapsed sidebar group dropdowns
  packages/panels/docs/06-navigation.md
  packages/panels/resources/views/components/layout/index.blade.php
  packages/panels/resources/views/components/page/sub-navigation/sidebar.blade.php
  packages/panels/resources/views/components/sidebar/group.blade.php
  packages/panels/resources/views/components/sidebar/index.blade.php
  packages/panels/resources/views/components/sidebar/item.blade.php
  packages/panels/resources/views/components/topbar/index.blade.php
  packages/panels/src/Navigation/NavigationGroup.php
Labels: enhancement

#11384 adding header to sidebar dropdown
  packages/panels/resources/views/components/sidebar/group.blade.php
Labels: enhancement

#11386 Add mask to TextInputColumn
  packages/tables/resources/views/columns/text-input-column.blade.php
  packages/tables/src/Columns/TextInputColumn.php
Labels: enhancement

#11400 Add Romanian translations for export action
  packages/actions/resources/lang/ro/export.php
Labels: i18n

#11402 Vertically center modal heading when it makes sense
  packages/support/resources/views/components/modal/index.blade.php
Labels: bug, ui

#11403 Update edit-profile.php italian translation
  packages/panels/resources/lang/it/pages/auth/edit-profile.php
Labels: i18n

#11420 Fix typo in modal sticky header docs
  packages/actions/docs/04-modals.md
Labels: documentation

#11383 Skip exporter columns selection form
  packages/actions/docs/07-prebuilt-actions/09-export.md
  packages/actions/src/Concerns/CanExportRecords.php
Labels: enhancement

#11423 Translated missing fields to Romanian
  packages/actions/resources/lang/ro/import.php
  packages/panels/resources/lang/ro/pages/dashboard.php
  packages/support/resources/lang/ro/components/pagination.php
  packages/tables/resources/lang/ro/table.php
Labels: i18n

#11468 Translate Export Action in French
  packages/actions/resources/lang/fr/export.php
Labels: i18n

#11478 Strip tags from getBrandName within title tag
  packages/panels/resources/views/components/layout/base.blade.php
Labels: bug

#11482 European Portuguese Translation
  packages/forms/resources/lang/pt_PT/components.php
  packages/support/resources/lang/pt_PT/components/pagination.php
  packages/tables/resources/lang/pt_PT/table.php
Labels: i18n

#11488 Fix importer: do not fill unmapped columns
  packages/actions/src/Imports/Importer.php
Labels: bug

#11497 Fix beforeFill() hook in EditRecord.php
  packages/panels/src/Resources/Pages/EditRecord.php
  packages/panels/src/Resources/Pages/ViewRecord.php
  packages/spatie-laravel-translatable-plugin/src/Resources/Pages/Concerns/HasTranslatableFormWithExistingRecordData.php
Labels: bug

#11443 Add iconColor attribute for Dropdown Blade components
  packages/support/docs/09-blade-components/02-dropdown.md
  packages/support/resources/views/components/dropdown/list/item.blade.php
Labels: enhancement

#11433 Fixed: Addressed $loop->iteration placement outside loops and correct…
  packages/infolists/resources/views/components/image-entry.blade.php
  packages/tables/resources/views/columns/image-column.blade.php
Labels: bug

#11463 Fix no sorting in ColumnGroup
  packages/tables/src/Columns/ColumnGroup.php
Labels: bug

#11516 Fix `cache-components` command on windows
  packages/panels/src/Panel/Concerns/HasComponents.php
Labels: bug

#11526 Update .stubs.php
  packages/forms/.stubs.php
Labels: bug

#11527 Fix: default theme mode not respected for pages before login
  packages/panels/resources/js/index.js
  packages/panels/resources/views/components/layout/base.blade.php
Labels: bug

#11539 Fix form docs custom layout link
  packages/forms/docs/04-layout/08-custom.md
Labels: documentation

#11544 Database transactions
  packages/actions/src/Concerns/CanUseDatabaseTransactions.php
  packages/actions/src/Concerns/InteractsWithActions.php
  packages/actions/src/CreateAction.php
  packages/actions/src/EditAction.php
  packages/actions/src/MountableAction.php
  packages/forms/src/Concerns/HasFormComponentActions.php
  packages/infolists/src/Concerns/InteractsWithInfolists.php
  packages/panels/src/Pages/Auth/EditProfile.php
  packages/panels/src/Pages/Auth/Register.php
  packages/panels/src/Pages/Tenancy/EditTenantProfile.php
  packages/panels/src/Pages/Tenancy/RegisterTenant.php
  packages/panels/src/Resources/Pages/CreateRecord.php
  packages/panels/src/Resources/Pages/EditRecord.php
  packages/spatie-laravel-settings-plugin/src/Pages/SettingsPage.php
  packages/support/src/Exceptions/Cancel.php
  packages/support/src/Exceptions/Halt.php
  packages/tables/src/Actions/CreateAction.php
  packages/tables/src/Actions/EditAction.php
  packages/tables/src/Concerns/CanReorderRecords.php
  packages/tables/src/Concerns/HasActions.php
  packages/tables/src/Concerns/HasBulkActions.php
Labels: enhancement

#11545 chore: Laravel Number:: formatting
  packages/actions/src/Concerns/CanExportRecords.php
  packages/actions/src/Concerns/CanImportRecords.php
  packages/infolists/docs/03-entries/02-text.md
  packages/infolists/src/Components/Concerns/CanFormatState.php
  packages/support/resources/views/components/pagination/index.blade.php
  packages/support/src/Enums/ArgumentValue.php
  packages/support/src/helpers.php
  packages/tables/docs/03-columns/02-text.md
  packages/tables/docs/07-summaries.md
  packages/tables/src/Columns/Concerns/CanFormatState.php
  packages/tables/src/Columns/Summarizers/Concerns/CanFormatState.php
  packages/tables/src/Filters/QueryBuilder/Constraints/NumberConstraint/Operators/EqualsOperator.php
  packages/tables/src/Filters/QueryBuilder/Constraints/NumberConstraint/Operators/IsMaxOperator.php
  packages/tables/src/Filters/QueryBuilder/Constraints/NumberConstraint/Operators/IsMinOperator.php
Labels: chore

#11429 Laravel 11: Remove Doctrine DBAL
  composer.json
  composer.lock
  packages/actions/docs/07-prebuilt-actions/08-import.md
  packages/actions/docs/07-prebuilt-actions/09-export.md
  packages/actions/src/Commands/Concerns/CanGenerateExporterColumns.php
  packages/actions/src/Commands/Concerns/CanGenerateImporterColumns.php
  packages/forms/docs/08-adding-a-form-to-a-livewire-component.md
  packages/forms/src/Commands/Concerns/CanGenerateForms.php
  packages/panels/docs/03-resources/01-getting-started.md
  packages/support/composer.json
  packages/support/src/Commands/Concerns/CanReadModelSchemas.php
  packages/tables/docs/11-adding-a-table-to-a-livewire-component.md
  packages/tables/src/Commands/Concerns/CanGenerateTables.php
Labels: enhancement

#11432 Add pivot attributes to Select and CheckboxList components
  composer.lock
  packages/forms/docs/03-fields/03-select.md
  packages/forms/docs/03-fields/06-checkbox-list.md
  packages/forms/src/Components/CheckboxList.php
  packages/forms/src/Components/Concerns/HasPivotData.php
  packages/forms/src/Components/Select.php
Labels: enhancement

#11410 Use new `hasActualContent` method on slots
  packages/support/src/helpers.php
Labels: enhancement

#11548 fix: Nested Spatie relationships
  packages/spatie-laravel-media-library-plugin/src/Infolists/Components/SpatieMediaLibraryImageEntry.php
  packages/spatie-laravel-media-library-plugin/src/Tables/Columns/SpatieMediaLibraryImageColumn.php
  packages/spatie-laravel-tags-plugin/src/Infolists/Components/SpatieTagsEntry.php
  packages/spatie-laravel-tags-plugin/src/Tables/Columns/SpatieTagsColumn.php
Labels: bug

#11444 modifiable select alias for Average, Count and Sum Summerizers
  packages/tables/src/Columns/Summarizers/Average.php
  packages/tables/src/Columns/Summarizers/Count.php
  packages/tables/src/Columns/Summarizers/Sum.php
Labels: enhancement

#11448 Feature: XLSX format header row styling
  packages/actions/docs/07-prebuilt-actions/09-export.md
  packages/actions/src/Exports/Exporter.php
  packages/actions/src/Exports/Jobs/CreateXlsxFile.php
Labels: enhancement

#11513 Group download middlewares within a filament.actions middleware group
  packages/actions/routes/web.php
  packages/actions/src/ActionsServiceProvider.php
Labels: enhancement

#11535 feat: docs Select@createOptionUsing section (03-select.md)
  packages/forms/docs/03-fields/03-select.md
Labels: documentation

#11549 Fixes the 'guessBelongsToRelationshipTitleColumnName' primary key logic
  packages/support/src/Commands/Concerns/CanReadModelSchemas.php
Labels: bug

#11540 English grammar corrections
  packages/panels/resources/lang/en/pages/auth/login.php
  packages/panels/resources/lang/en/pages/auth/password-reset/request-password-reset.php
Labels: i18n

#11558 Add ULID validation
  packages/forms/docs/05-validation.md
  packages/forms/src/Components/Concerns/CanBeValidated.php
Labels: enhancement

#11557 Fix using Table::$defaultCurrency in infolist
  packages/infolists/src/Components/Concerns/CanFormatState.php
Labels: bug

#11294 Panel Domain Routing
  packages/panels/docs/11-tenancy.md
  packages/panels/routes/web.php
  packages/panels/src/Panel/Concerns/HasTenancy.php
  tests/database/factories/DomainTeamFactory.php
  tests/database/migrations/create_domain_teams_table.php
  tests/src/DomainTenancyPanelProvider.php
  tests/src/Models/DomainTeam.php
  tests/src/Panels/Tenancy/ResolveTenantTest.php
  tests/src/TenancyPanelProvider.php
  tests/src/TestCase.php
Labels: enhancement

#11576 add missing french translation
  packages/infolists/resources/lang/fr/components.php
  packages/support/resources/lang/fr/components/pagination.php
Labels: i18n

#11588 Add missing pt_BR translation
  packages/actions/resources/lang/pt_BR/export.php
  packages/actions/resources/lang/pt_BR/import.php
  packages/infolists/resources/lang/pt_BR/components.php
  packages/support/resources/lang/pt_BR/components/pagination.php
  packages/tables/resources/lang/pt_BR/table.php
Labels: enhancement, i18n

#11594 Added Azerbaijani (AZ) translations for Import and Export
  packages/actions/resources/lang/az/attach.php
  packages/actions/resources/lang/az/create.php
  packages/actions/resources/lang/az/export.php
  packages/actions/resources/lang/az/import.php
Labels: i18n

#10972 Laravel 11
  .gitattributes
  .github/workflows/phpstan.yml
  .github/workflows/tests.yml
  composer.json
  composer.lock
  packages/actions/composer.json
  packages/actions/docs/07-prebuilt-actions/08-import.md
  packages/actions/docs/07-prebuilt-actions/09-export.md
  packages/actions/src/Commands/Concerns/CanGenerateExporterColumns.php
  packages/actions/src/Commands/Concerns/CanGenerateImporterColumns.php
  packages/forms/composer.json
  packages/forms/docs/08-adding-a-form-to-a-livewire-component.md
  packages/forms/src/Commands/Concerns/CanGenerateForms.php
  packages/infolists/composer.json
  packages/notifications/composer.json
  packages/panels/composer.json
  packages/panels/docs/01-installation.md
  packages/panels/docs/03-resources/01-getting-started.md
  packages/panels/docs/09-configuration.md
  packages/spatie-laravel-google-fonts-plugin/composer.json
  packages/spatie-laravel-media-library-plugin/composer.json
  packages/spatie-laravel-settings-plugin/composer.json
  packages/spatie-laravel-tags-plugin/composer.json
  packages/spatie-laravel-translatable-plugin/composer.json
  packages/support/composer.json
  packages/support/src/Commands/Concerns/CanGeneratePanels.php
  packages/support/src/Commands/Concerns/CanReadModelSchemas.php
  packages/tables/.stubs.php
  packages/tables/composer.json
  packages/tables/docs/11-adding-a-table-to-a-livewire-component.md
  packages/tables/src/Commands/Concerns/CanGenerateTables.php
  packages/upgrade/composer.json
  phpstan.neon.dist
  testbench.yaml
  tests/database/migrations/create_password_reset_tokens_table.php
  tests/database/migrations/create_users_table.php
  tests/src/TestCase.php
  tests/src/Upgrade/RectorTest.php
Labels: blocked, chore

#11604 getSchemaBuilder will return SchemaBuilder not Schema Facade
  packages/support/src/Commands/Concerns/CanReadModelSchemas.php
Labels: bug

#11605 Add action, tag and method options to MenuItem
  packages/panels/docs/06-navigation.md
  packages/panels/docs/11-tenancy.md
  packages/panels/resources/views/components/tenant-menu.blade.php
  packages/panels/resources/views/components/user-menu.blade.php
  packages/panels/src/Navigation/MenuItem.php
Labels: enhancement

#11581 Select filter placeholder
  packages/tables/docs/04-filters/02-select.md
  packages/tables/src/Filters/SelectFilter.php
Labels: enhancement

#11613 Wrap long words in section description
  packages/support/resources/views/components/section/description.blade.php
Labels: bug, ui

#11626 Update finnish translation
  packages/infolists/resources/lang/fi/components.php
  packages/support/resources/lang/fi/components/pagination.php
Labels: i18n
