Repository filamentphp/filament, pull requests merged in 2024-08, with the labels that each got.

#13767 fix: Broaden dependency of `filament/support` on dbal to allow for its version 4
  packages/support/composer.json
Labels: enhancement

#13782 Edit Arabic Translation
  packages/panels/resources/lang/ar/widgets/account-widget.php
  packages/panels/src/FilamentManager.php
  packages/panels/src/Panel/Concerns/CanGenerateResourceUrls.php
  packages/tables/resources/views/components/search-field.blade.php
  tests/src/Forms/FormsTest.php
  tests/src/Panels/Resources/ResourceTest.php
Labels: i18n

#13783 Fixed table actions in resources.
  packages/panels/src/Commands/MakePageCommand.php
  packages/panels/src/Commands/MakeRelationManagerCommand.php
  packages/panels/src/Commands/MakeResourceCommand.php
  packages/panels/src/FilamentManager.php
  packages/panels/src/Panel/Concerns/CanGenerateResourceUrls.php
  packages/panels/stubs/RelationManager.stub
  packages/panels/stubs/Resource.stub
  packages/panels/stubs/ResourceManageRelatedRecordsPage.stub
  packages/support/resources/views/components/modal/index.blade.php
  packages/tables/resources/views/components/search-field.blade.php
  tests/src/Panels/Resources/ResourceTest.php
Labels: bug

#13795 Updated the documentation in V4
  packages/actions/docs/02-overview.md
  packages/actions/docs/07-prebuilt-actions/01-create.md
  packages/actions/docs/07-prebuilt-actions/02-edit.md
  packages/actions/docs/07-prebuilt-actions/03-view.md
  packages/actions/docs/07-prebuilt-actions/04-delete.md
  packages/actions/docs/07-prebuilt-actions/05-replicate.md
  packages/actions/docs/07-prebuilt-actions/06-force-delete.md
  packages/actions/docs/07-prebuilt-actions/07-restore.md
  packages/actions/docs/07-prebuilt-actions/08-import.md
  packages/actions/docs/07-prebuilt-actions/09-export.md
Labels: documentation

#13796 Fixed Table stub action in V4
  packages/tables/stubs/Table.stub
Labels: bug

#13810 implement alignment in image-entry blade
  packages/infolists/resources/views/components/image-entry.blade.php
Labels: bug

#13841 Fix: Generating a slug from a title
  packages/forms/docs/07-advanced.md
Labels: documentation

#13839 fix: the breadcrumb item label of the current page should not be clickable
  packages/support/resources/views/components/breadcrumbs.blade.php
Labels: enhancement

#13859 Prevent text breaking out the grid
  packages/forms/resources/views/components/field-wrapper/helper-text.blade.php
  packages/infolists/resources/views/components/entry-wrapper/helper-text.blade.php
Labels: ui

#13748 Persist Textarea autosize
  docs-assets/app/public/js/filament/forms/components/textarea.js
  packages/forms/dist/components/textarea.js
  packages/forms/resources/js/components/textarea.js
  packages/forms/resources/views/components/textarea.blade.php
Labels: bug, high priority

#13814 Add better mimetype support for FileUpload component
  package-lock.json
  package.json
  packages/forms/dist/components/file-upload.js
  packages/forms/resources/js/components/file-upload.js
Labels: bug

#13864 Docs Update - Modify the modal blade component page
  packages/support/docs/09-blade-components/02-modal.md
Labels: documentation

#13875 Update action testing documentation to include testing modals
  packages/actions/docs/09-testing.md
Labels: documentation

#13880 Fix issue testing visible action with arguments
  packages/actions/.stubs.php
  packages/actions/src/Testing/TestsActions.php
  packages/forms/resources/js/components/textarea.js
  packages/forms/resources/views/components/textarea.blade.php
Labels: bug

#13902 Update email-verification-prompt.php
  packages/panels/resources/lang/fa/pages/auth/email-verification/email-verification-prompt.php
Labels: i18n

#13905 Use Tailwind `size-` instead of `w-`/`h-` combo
  docs-assets/app/routes/web.php
  packages/forms/dist/index.css
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/color-picker.blade.php
  packages/forms/resources/views/components/file-upload.blade.php
  packages/forms/resources/views/components/toggle.blade.php
  packages/infolists/resources/views/components/color-entry.blade.php
  packages/infolists/resources/views/components/icon-entry.blade.php
  packages/infolists/resources/views/components/text-entry.blade.php
  packages/notifications/resources/views/components/icon.blade.php
  packages/panels/dist/theme.css
  packages/panels/resources/views/components/sidebar/group.blade.php
  packages/panels/resources/views/components/sidebar/item.blade.php
  packages/panels/resources/views/components/tenant-menu.blade.php
  packages/panels/resources/views/components/theme-switcher/button.blade.php
  packages/panels/resources/views/components/topbar/item.blade.php
  packages/schema/resources/views/components/decorations/icon-decoration.blade.php
  packages/schema/resources/views/components/wizard.blade.php
  packages/support/resources/views/components/avatar.blade.php
  packages/support/resources/views/components/badge.blade.php
  packages/support/resources/views/components/breadcrumbs.blade.php
  packages/support/resources/views/components/button/index.blade.php
  packages/support/resources/views/components/dropdown/header.blade.php
  packages/support/resources/views/components/dropdown/list/item.blade.php
  packages/support/resources/views/components/icon-button.blade.php
  packages/support/resources/views/components/input/wrapper.blade.php
  packages/support/resources/views/components/link.blade.php
  packages/support/resources/views/components/modal/index.blade.php
  packages/support/resources/views/components/pagination/item.blade.php
  packages/support/resources/views/components/section/index.blade.php
  packages/support/resources/views/components/tabs/item.blade.php
  packages/tables/resources/views/columns/color-column.blade.php
  packages/tables/resources/views/columns/icon-column.blade.php
  packages/tables/resources/views/columns/summaries/icon-count.blade.php
  packages/tables/resources/views/columns/text-column.blade.php
  packages/tables/resources/views/columns/toggle-column.blade.php
  packages/tables/resources/views/components/empty-state/index.blade.php
  packages/tables/resources/views/components/filters/index.blade.php
  packages/tables/resources/views/components/header-cell.blade.php
  packages/tables/resources/views/components/reorder/indicator.blade.php
  packages/tables/resources/views/components/selection/indicator.blade.php
  packages/widgets/resources/views/stats-overview-widget/stat.blade.php
Labels: ui

#13914 feature: Required import mapping for new records only
  packages/actions/docs/07-prebuilt-actions/08-import.md
  packages/actions/resources/lang/en/import.php
  packages/actions/src/Imports/ImportColumn.php
  packages/actions/src/Imports/Importer.php
Labels: enhancement

#13921 fix async alpine not loading reliably in spa mode
  packages/forms/resources/views/components/color-picker.blade.php
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/resources/views/components/file-upload.blade.php
  packages/forms/resources/views/components/key-value.blade.php
  packages/forms/resources/views/components/markdown-editor.blade.php
  packages/forms/resources/views/components/rich-editor.blade.php
  packages/forms/resources/views/components/select.blade.php
  packages/forms/resources/views/components/tags-input.blade.php
  packages/forms/resources/views/components/textarea.blade.php
  packages/support/resources/views/components/modal/index.blade.php
Labels: bug

#13926 Added missing Italian translation for unsaved-changes-alert.php
  packages/panels/resources/lang/it/unsaved-changes-alert.php
Labels: i18n

#13938 Update Dutch translations
  packages/actions/resources/lang/nl/import.php
  packages/infolists/resources/lang/nl/components.php
  packages/panels/resources/lang/nl/unsaved-changes-alert.php
Labels: i18n

#13940 Remove useless null initialization
  packages/panels/src/FilamentManager.php
Labels: chore

#13942 fix: Header actions render hook alignment
  packages/panels/resources/views/components/header/index.blade.php
Labels: bug

#13949 Improve import/export job retry strategy
  packages/actions/docs/07-prebuilt-actions/08-import.md
  packages/actions/docs/07-prebuilt-actions/09-export.md
  packages/actions/docs/10-upgrade-guide.md
  packages/actions/src/Exports/Exporter.php
  packages/actions/src/Exports/Jobs/ExportCsv.php
  packages/actions/src/Imports/Importer.php
  packages/actions/src/Imports/Jobs/ImportCsv.php
Labels: enhancement

#13952 fix: File upload compact circle error messages
  docs-assets/app/public/js/filament/forms/components/date-time-picker.js
  docs-assets/app/public/js/filament/forms/components/file-upload.js
  docs-assets/app/public/js/filament/forms/components/rich-editor.js
  packages/forms/dist/components/file-upload.js
  packages/forms/dist/components/rich-editor.js
  packages/forms/resources/js/components/file-upload.js
  packages/forms/resources/views/components/file-upload.blade.php
Labels: bug

#13963 feature: JSON wildcard (*) table column state
  packages/support/src/Concerns/HasCellState.php
  tests/database/migrations/create_posts_table.php
  tests/src/Models/Post.php
  tests/src/Tables/ColumnTest.php
  tests/src/Tables/Fixtures/PostsTable.php
Labels: bug

#13954 fix(constraints): human-readable summary display
  packages/tables/src/Filters/QueryBuilder/Constraints/SelectConstraint/Operators/IsOperator.php
Labels: bug

#13974 fix(filters): correctly retrieve dot-notated filter state
  packages/tables/src/Concerns/HasFilters.php
Labels: bug

#13958 Prevent page from jumping to the top if the section is not collapsed
  packages/support/resources/views/components/section/index.blade.php
Labels: bug

#13980 Docs: Fix wrong class path on tenancy custom billing provider
  packages/panels/docs/11-tenancy.md
Labels: documentation

#13987 Ensure User is not null when getting default tenenat.
  packages/panels/src/Panel/Concerns/HasRoutes.php
Labels: bug

#14004 fix: Clearing bulk actions leaves checkboxes
  packages/tables/src/Table/Concerns/HasBulkActions.php
Labels: bug

#14024 fix: Always pass search to Select modifyQueryUsing function
  packages/forms/src/Components/Select.php
Labels: bug

#14014 Update breadcrumbs.blade.php
  packages/support/resources/views/components/breadcrumbs.blade.php
Labels: bug

#14019 Update [es] translations in actions import
  packages/actions/resources/lang/es/import.php
Labels: i18n

#14023 Mongolian translation is updated
  packages/actions/resources/lang/mn/export.php
  packages/actions/resources/lang/mn/import.php
  packages/forms/resources/lang/mn/components.php
  packages/forms/resources/lang/mn/validation.php
  packages/support/resources/lang/mn/components/pagination.php
  packages/tables/resources/lang/mn/filters/query-builder.php
  packages/tables/resources/lang/mn/table.php
Labels: i18n

#14018 Fix aria-label for sortable headers, add aria-sort on active sort
  packages/tables/resources/views/components/header-cell.blade.php
Labels: bug

#14049 fix: Bulk action object removal from cache array
  packages/tables/src/Table/Concerns/HasBulkActions.php
Labels: bug

#14028 Fix the missing Chinese translation of radio's Boolean method
  packages/forms/resources/lang/zh_CN/components.php
Labels: i18n

#14038 panels package - mongolian translations
  packages/panels/resources/lang/mn/global-search.php
  packages/panels/resources/lang/mn/layout.php
  packages/panels/resources/lang/mn/pages/auth/edit-profile.php
  packages/panels/resources/lang/mn/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/mn/pages/auth/login.php
  packages/panels/resources/lang/mn/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/mn/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/mn/pages/auth/register.php
  packages/panels/resources/lang/mn/pages/dashboard.php
  packages/panels/resources/lang/mn/pages/tenancy/edit-tenant-profile.php
  packages/panels/resources/lang/mn/resources/pages/create-record.php
  packages/panels/resources/lang/mn/resources/pages/edit-record.php
  packages/panels/resources/lang/mn/resources/pages/list-records.php
  packages/panels/resources/lang/mn/resources/pages/view-record.php
  packages/panels/resources/lang/mn/unsaved-changes-alert.php
  packages/panels/resources/lang/mn/widgets/account-widget.php
  packages/panels/resources/lang/mn/widgets/filament-info-widget.php
Labels: i18n

#14000 Add render hooks for layout containers
  docs/07-advanced/01-render-hooks.md
  packages/panels/resources/views/components/layout/index.blade.php
  packages/panels/resources/views/components/layout/simple.blade.php
  packages/panels/src/View/PanelsRenderHook.php
Labels: enhancement

#14053 Feature: Prune sensitive data from failed_import_rows data
  packages/actions/docs/07-prebuilt-actions/08-import.md
  packages/actions/src/Imports/ImportColumn.php
  packages/actions/src/Imports/Jobs/ImportCsv.php
Labels: enhancement

#14063 Enhanced default `focusedDate` logic in `DateTimePicker`
  docs-assets/app/public/js/filament/forms/components/date-time-picker.js
  packages/forms/dist/components/date-time-picker.js
  packages/forms/resources/js/components/date-time-picker.js
Labels: bug

#14088 Update header-cell.blade.php
  packages/tables/resources/views/components/header-cell.blade.php
Labels: bug

#14083 Improve type support for model related methods
  packages/actions/src/Commands/Concerns/CanGenerateExporterColumns.php
  packages/actions/src/Commands/Concerns/CanGenerateImporterColumns.php
  packages/actions/src/Concerns/InteractsWithActions.php
  packages/actions/src/Concerns/InteractsWithRecord.php
  packages/actions/src/Exports/Exporter.php
  packages/actions/src/Imports/Importer.php
  packages/forms/src/Commands/Concerns/CanGenerateForms.php
  packages/forms/src/Components/MorphToSelect/Type.php
  packages/forms/src/Components/Repeater.php
  packages/forms/src/Components/Select.php
  packages/forms/src/Concerns/InteractsWithForms.php
  packages/panels/src/Commands/MakeUserCommand.php
  packages/panels/src/FilamentManager.php
  packages/panels/src/Pages/Auth/Register.php
  packages/panels/src/Pages/Tenancy/RegisterTenant.php
  packages/panels/src/Panel/Concerns/HasComponents.php
  packages/panels/src/Panel/Concerns/HasTenancy.php
  packages/panels/src/Resources/Pages/Concerns/InteractsWithRecord.php
  packages/panels/src/Resources/Pages/CreateRecord.php
  packages/panels/src/Resources/Pages/ListRecords.php
  packages/panels/src/Resources/Resource.php
  packages/panels/src/helpers.php
  packages/schema/src/Components/Concerns/BelongsToModel.php
  packages/schema/src/Components/Concerns/EntanglesStateWithSingularRelationship.php
  packages/schema/src/Components/Concerns/HasActions.php
  packages/schema/src/Components/Contracts/CanEntangleWithSingularRelationships.php
  packages/schema/src/Concerns/BelongsToModel.php
  packages/spatie-laravel-tags-plugin/src/Forms/Components/SpatieTagsInput.php
  packages/spatie-laravel-translatable-plugin/src/SpatieLaravelTranslatableContentDriver.php
  packages/support/src/Commands/Concerns/CanReadModelSchemas.php
  packages/support/src/Contracts/TranslatableContentDriver.php
  packages/support/src/helpers.php
  packages/tables/src/Commands/Concerns/CanGenerateTables.php
  packages/tables/src/Table/Concerns/HasRecords.php
Labels: chore
