Repository filamentphp/filament, pull requests merged in 2024-10, with the labels that each got.

#14404 Added missed Ukrainian translations
  packages/actions/resources/lang/uk/import.php
  packages/forms/resources/lang/uk/components.php
Labels: i18n

#14396 Add missing translations for Russian
  packages/tables/resources/lang/ru/filters/query-builder.php
Labels: i18n

#14382 Fix typo in repeater testing docs
  packages/forms/docs/03-fields/12-repeater.md
Labels: documentation

#14405 Specify Tailwind variants position
  docs-assets/app/resources/css/app.css
  packages/actions/docs/01-installation.md
  packages/forms/docs/01-installation.md
  packages/infolists/docs/01-installation.md
  packages/notifications/docs/01-installation.md
  packages/panels/resources/css/index.css
  packages/support/stubs/scaffolding/resources/css/app.css
  packages/tables/docs/01-installation.md
  packages/widgets/docs/01-installation.md
Labels: bug

#14407 Extract base stylesheet
  packages/panels/resources/css/base.css
  packages/panels/resources/css/index.css
Labels: enhancement

#14350 Document automatic event dispatching for database notifications
  packages/notifications/docs/03-database-notifications.md
Labels: documentation

#14401 Display url when issue page can't be opened in browser
  packages/support/src/Commands/MakeIssueCommand.php
Labels: bug

#14411 Feature: XLSX Writer Options
  packages/actions/docs/06-prebuilt-actions/09-export.md
  packages/actions/src/Exports/Exporter.php
  packages/actions/src/Exports/Jobs/CreateXlsxFile.php
Labels: enhancement

#14432 Fixes/docs custom layout section corrections
  packages/forms/docs/04-layout/08-custom.md
  packages/infolists/docs/04-layout/07-custom.md
Labels: documentation

#14442 fix: Removal of unnecessary save
  packages/actions/src/Concerns/CanExportRecords.php
Labels: bug

#14457 Support for eloquent-power-joins v4
  packages/support/composer.json
  packages/support/src/Services/RelationshipJoiner.php
Labels: enhancement

#14441 Repeater - save relations when hidden
  packages/forms/src/Components/Repeater.php
Labels: bug

#14456 Fix: Add the bind value that is initialized in reorder()
  packages/actions/src/Exports/Jobs/PrepareCsvExport.php
Labels: bug

#14431 Add option to align add action on a repeater
  packages/forms/docs/03-fields/12-repeater.md
  packages/forms/resources/views/components/repeater/index.blade.php
  packages/forms/src/Components/Repeater.php
Labels: enhancement

#14416 Add disable grammarly
  packages/forms/docs/03-fields/10-rich-editor.md
  packages/forms/resources/views/components/rich-editor.blade.php
  packages/forms/src/Components/Concerns/CanDisableGrammarly.php
  packages/forms/src/Components/Field.php
Labels: enhancement

#14340 Fix parent component dehydrate state when hidden
  packages/forms/src/Components/Concerns/HasState.php
  tests/src/Forms/StateTest.php
Labels: bug

#14471 Fix: Restoring the process of temporarily saving to obtain the sequen…
  packages/actions/src/Concerns/CanExportRecords.php
Labels: bug

#14473 [Docs] Fix typo in 10-rich-editor.md
  packages/forms/docs/03-fields/10-rich-editor.md
Labels: documentation

#14495 Import error
  packages/panels/docs/03-resources/02-listing-records.md
Labels: documentation

#14145 Change plural to singular in getInverseRelationship in HasQuery
  packages/tables/src/Table/Concerns/HasQuery.php
Labels: bug

#14512 Georgian Translations
  packages/actions/resources/lang/ka/associate.php
  packages/actions/resources/lang/ka/attach.php
  packages/actions/resources/lang/ka/create.php
  packages/actions/resources/lang/ka/delete.php
  packages/actions/resources/lang/ka/detach.php
  packages/actions/resources/lang/ka/dissociate.php
  packages/actions/resources/lang/ka/edit.php
  packages/actions/resources/lang/ka/export.php
  packages/actions/resources/lang/ka/force-delete.php
  packages/actions/resources/lang/ka/group.php
  packages/actions/resources/lang/ka/import.php
  packages/actions/resources/lang/ka/modal.php
  packages/actions/resources/lang/ka/replicate.php
  packages/actions/resources/lang/ka/restore.php
  packages/actions/resources/lang/ka/view.php
  packages/forms/resources/lang/ka/components.php
  packages/forms/resources/lang/ka/validation.php
  packages/infolists/resources/lang/ka/components.php
  packages/notifications/resources/lang/ka/database.php
  packages/panels/resources/lang/ka/global-search.php
  packages/panels/resources/lang/ka/layout.php
  packages/panels/resources/lang/ka/pages/auth/edit-profile.php
  packages/panels/resources/lang/ka/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/ka/pages/auth/login.php
  packages/panels/resources/lang/ka/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/ka/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/ka/pages/auth/register.php
  packages/panels/resources/lang/ka/pages/dashboard.php
  packages/panels/resources/lang/ka/pages/tenancy/edit-tenant-profile.php
  packages/panels/resources/lang/ka/resources/pages/create-record.php
  packages/panels/resources/lang/ka/resources/pages/edit-record.php
  packages/panels/resources/lang/ka/resources/pages/list-records.php
  packages/panels/resources/lang/ka/resources/pages/view-record.php
  packages/panels/resources/lang/ka/unsaved-changes-alert.php
  packages/panels/resources/lang/ka/widgets/account-widget.php
  packages/panels/resources/lang/ka/widgets/filament-info-widget.php
  packages/spatie-laravel-settings-plugin/resources/lang/ka/pages/settings-page.php
  packages/spatie-laravel-translatable-plugin/resources/lang/ka/actions.php
  packages/support/resources/lang/ka/components/button.php
  packages/support/resources/lang/ka/components/copyable.php
  packages/support/resources/lang/ka/components/modal.php
  packages/support/resources/lang/ka/components/pagination.php
  packages/tables/resources/lang/ka/filters/query-builder.php
  packages/tables/resources/lang/ka/table.php
Labels: i18n

#14515 added closure to distinct()
  packages/forms/src/Components/Concerns/CanBeValidated.php
  packages/forms/src/Components/Concerns/CanFixIndistinctState.php
  packages/forms/src/Concerns/HasStateBindingModifiers.php
Labels: enhancement

#14585 Fix color facade DocBlock
  packages/support/src/Facades/FilamentColor.php
Labels: chore

#14568 Add note about user responsibility for deleting/managing export files
  packages/actions/docs/07-prebuilt-actions/09-export.md
Labels: documentation

#14586 Update DatabaseNotificationsSent.php
  packages/notifications/src/Events/DatabaseNotificationsSent.php
Labels: enhancement

#14165 Fix autofocus not working in wizard steps
  packages/forms/resources/views/components/wizard/step.blade.php
  packages/support/resources/views/components/input/wrapper.blade.php
Labels: bug

#14592 [Forms] Builder Component Block Preview(s) Fixed/Enhanced
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/src/Components/Concerns/HasPreview.php
Labels: bug

#14566 Add TOP and BOTTOM hooks on Sub Navigation
  packages/panels/resources/views/components/page/index.blade.php
  packages/panels/resources/views/components/page/sub-navigation/sidebar.blade.php
  packages/panels/src/View/PanelsRenderHook.php
  packages/support/docs/06-render-hooks.md
Labels: enhancement

#14558 Have next and previous functions disabled when their actions are disabled in the Wizard component
  packages/forms/resources/views/components/wizard.blade.php
Labels: bug

#14593 Make filterMediaUsing() available in SpatieMediaLibraryImageColumn and SpatieMediaLibraryImageEntry
  packages/spatie-laravel-media-library-plugin/README.md
  packages/spatie-laravel-media-library-plugin/src/Forms/Components/SpatieMediaLibraryFileUpload.php
  packages/spatie-laravel-media-library-plugin/src/Infolists/Components/SpatieMediaLibraryImageEntry.php
  packages/spatie-laravel-media-library-plugin/src/Support/Concerns/HasMediaFilter.php
  packages/spatie-laravel-media-library-plugin/src/Tables/Columns/SpatieMediaLibraryImageColumn.php
Labels: enhancement

#14597 Allow conditional control over lazy-loading database notifications
  packages/forms/resources/views/components/wizard.blade.php
  packages/panels/resources/views/components/layout/simple.blade.php
  packages/panels/resources/views/components/page/sub-navigation/sidebar.blade.php
  packages/panels/resources/views/components/topbar/index.blade.php
  packages/panels/src/Facades/Filament.php
  packages/panels/src/FilamentManager.php
  packages/panels/src/Panel/Concerns/HasNotifications.php
Labels: enhancement

#14303 Add aria label to action th
  packages/tables/resources/lang/en/table.php
  packages/tables/resources/views/index.blade.php
Labels: a11y

#14170 Adding table actions header cell new hook class
  packages/tables/resources/views/index.blade.php
Labels: enhancement

#13973 Fix oldFormState containing new values
  packages/forms/src/Concerns/InteractsWithForms.php
Labels: bug

#14605 Add `filament:about` command && add details about cached Blade icons and form components
  packages/support/src/Commands/AboutCommand.php
  packages/support/src/SupportServiceProvider.php
Labels: enhancement

#14614 Fix the missing repeater field alignement feature when using the simple layout
  packages/forms/resources/views/components/repeater/simple.blade.php
Labels: bug

#14612 Accept a closure for `$format` on `date()`, `dateTime()`, `time()`, `dateTooltip()`, `dateTimeTooltip()` and `timeTooltip()` methods
  packages/infolists/src/Components/Concerns/CanFormatState.php
  packages/tables/src/Columns/Concerns/CanFormatState.php
Labels: enhancement

#14615 Remove the trailing periods from the command descriptions
  packages/support/src/Commands/AssetsCommand.php
  packages/support/src/Commands/InstallCommand.php
Labels: chore

#14601 Add console command optimization in FilamentServiceProvider
  packages/panels/src/FilamentServiceProvider.php
Labels: enhancement

#14616 fix: Import/export null bugs
  packages/actions/src/Exports/Jobs/PrepareCsvExport.php
  packages/actions/src/Imports/Http/Controllers/DownloadImportFailureCsv.php
Labels: bug

#14620 Update European Portuguese Translation
  packages/actions/resources/lang/pt_PT/import.php
  packages/tables/resources/lang/pt_PT/table.php
Labels: i18n

#14629 Update 09-configuration.md
  packages/panels/docs/09-configuration.md
Labels: documentation

#14633 Update fi translation
  packages/actions/resources/lang/fi/import.php
  packages/forms/resources/lang/fi/components.php
  packages/tables/resources/lang/fi/table.php
Labels: i18n

#14645 Fix header padding for modal without footer
  packages/support/resources/views/components/modal/index.blade.php
Labels: bug, ui

#14644 feature: Improve tenancy through automatic global scoping
  docs/09-upgrade-guide.md
  packages/panels/docs/10-tenancy.md
  packages/panels/src/Facades/Filament.php
  packages/panels/src/FilamentManager.php
  packages/panels/src/Panel.php
  packages/panels/src/Panel/Concerns/HasTenancy.php
  packages/panels/src/Resources/Pages/CreateRecord.php
  packages/panels/src/Resources/Pages/ListRecords.php
  packages/panels/src/Resources/Resource.php
  packages/panels/src/Resources/Resource/Concerns/BelongsToTenant.php
  packages/spatie-laravel-translatable-plugin/src/Resources/Pages/CreateRecord/Concerns/Translatable.php
  tests/src/Models/Product.php
Labels: enhancement

#14661 4.x korean(한글) language support
  packages/actions/resources/lang/ko/import.php
  packages/forms/resources/lang/ko/components.php
  packages/tables/resources/lang/ko/table.php
Labels: i18n, awaiting next major version

#14654 4.x amharic(አማርኛ) language support
  packages/actions/resources/lang/am/associate.php
  packages/actions/resources/lang/am/attach.php
  packages/actions/resources/lang/am/create.php
  packages/actions/resources/lang/am/delete.php
  packages/actions/resources/lang/am/detach.php
  packages/actions/resources/lang/am/dissociate.php
  packages/actions/resources/lang/am/edit.php
  packages/actions/resources/lang/am/export.php
  packages/actions/resources/lang/am/force-delete.php
  packages/actions/resources/lang/am/group.php
  packages/actions/resources/lang/am/import.php
  packages/actions/resources/lang/am/modal.php
  packages/actions/resources/lang/am/replicate.php
  packages/actions/resources/lang/am/restore.php
  packages/actions/resources/lang/am/view.php
  packages/forms/resources/lang/am/components.php
  packages/forms/resources/lang/am/validation.php
  packages/infolists/resources/lang/am/components.php
  packages/notifications/resources/lang/am/database.php
  packages/panels/resources/lang/am/global-search.php
  packages/panels/resources/lang/am/layout.php
  packages/panels/resources/lang/am/pages/auth/edit-profile.php
  packages/panels/resources/lang/am/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/am/pages/auth/login.php
  packages/panels/resources/lang/am/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/am/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/am/pages/auth/register.php
  packages/panels/resources/lang/am/pages/dashboard.php
  packages/panels/resources/lang/am/pages/tenancy/edit-tenant-profile.php
  packages/panels/resources/lang/am/resources/pages/create-record.php
  packages/panels/resources/lang/am/resources/pages/edit-record.php
  packages/panels/resources/lang/am/resources/pages/list-records.php
  packages/panels/resources/lang/am/resources/pages/view-record.php
  packages/panels/resources/lang/am/unsaved-changes-alert.php
  packages/panels/resources/lang/am/widgets/account-widget.php
  packages/panels/resources/lang/am/widgets/filament-info-widget.php
  packages/schema/resources/lang/am/components.php
  packages/spatie-laravel-settings-plugin/resources/lang/am/pages/settings-page.php
  packages/spatie-laravel-translatable-plugin/resources/lang/am/actions.php
  packages/support/resources/lang/am/components/button.php
  packages/support/resources/lang/am/components/copyable.php
  packages/support/resources/lang/am/components/modal.php
  packages/support/resources/lang/am/components/pagination.php
  packages/tables/resources/lang/am/filters/query-builder.php
  packages/tables/resources/lang/am/table.php
  packages/widgets/resources/lang/am/chart.php
Labels: i18n, awaiting next major version

#14657 [WIP] Allow injecting $options into modifyQueryUsing()
  packages/actions/docs/07-prebuilt-actions/09-export.md
  packages/actions/src/Concerns/CanExportRecords.php
Labels: enhancement

#14672 feat : Action alignment system in Builder component
  packages/forms/docs/03-fields/13-builder.md
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/src/Components/Builder.php
Labels: enhancement

#14673 fix: Import/export count reliability
  packages/actions/src/Exports/Jobs/ExportCsv.php
  packages/actions/src/Exports/Jobs/PrepareCsvExport.php
  packages/actions/src/Imports/Jobs/ImportCsv.php
Labels: bug

#14678 Mitigate Carbon Month Overflow Bug on 31st of a month
  packages/tables/src/Filters/QueryBuilder/Constraints/DateConstraint/Operators/IsMonthOperator.php
Labels: bug
