Repository filamentphp/filament, pull requests merged in 2024-07, with the labels that each got.

#13399 Add infolists text entry date tooltip methods
  packages/infolists/src/Components/Concerns/CanFormatState.php
  packages/tables/src/Columns/Concerns/CanFormatState.php
Labels: enhancement

#13464 Fixing missing and bad translations in Czech
  packages/actions/resources/lang/cs/associate.php
  packages/forms/resources/lang/cs/components.php
  packages/infolists/resources/lang/cs/components.php
  packages/panels/resources/lang/cs/layout.php
  packages/panels/resources/lang/cs/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/cs/pages/auth/register.php
  packages/spatie-laravel-translatable-plugin/resources/lang/cs/actions.php
Labels: i18n

#13465 Fixing missing and bad translations in Slovak
  packages/forms/resources/lang/sk/components.php
  packages/panels/resources/lang/sk/layout.php
  packages/panels/resources/lang/sk/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/sk/pages/auth/register.php
  packages/tables/resources/lang/sk/filters/query-builder.php
Labels: i18n

#13474 Adding missing french translations
  packages/actions/resources/lang/fr/import.php
  packages/forms/resources/lang/fr/components.php
  packages/panels/resources/lang/fr/layout.php
  packages/panels/resources/lang/fr/unsaved-changes-alert.php
Labels: i18n

#13472 Fixing missing translations in Russian.
  packages/panels/resources/lang/ru/layout.php
  packages/panels/resources/lang/ru/pages/dashboard.php
  packages/panels/resources/lang/ru/unsaved-changes-alert.php
  packages/support/resources/lang/ru/components/pagination.php
  packages/tables/resources/lang/ru/table.php
Labels: i18n

#13471 fix: better handling of non-latin column names on import
  packages/actions/src/Concerns/CanImportRecords.php
Labels: bug

#13484 Update 05-actions.md
  packages/infolists/docs/05-actions.md
Labels: documentation

#13349 Cache getFlatComponents
  packages/schema/src/Concerns/HasComponents.php
Labels: enhancement

#13412 Add close notification event
  packages/notifications/docs/02-sending-notifications.md
  packages/notifications/resources/views/components/notification.blade.php
Labels: enhancement

#13519 fix: Testing grouped action visibility with grouped authorization
  packages/actions/src/Concerns/BelongsToGroup.php
  packages/tables/src/Table/Concerns/HasActions.php
  packages/tables/src/Testing/TestsActions.php
  tests/src/Tables/Actions/ActionTest.php
  tests/src/Tables/Fixtures/PostsTable.php
Labels: bug

#13486 Add possibility of closure to sidebarCollapsible methods
  packages/panels/src/Panel/Concerns/HasSidebar.php
Labels: enhancement

#13427 Add current state to the error messages on column test assertions
  packages/tables/src/Testing/TestsColumns.php
Labels: enhancement

#13497 Add defaultAction to docs
  packages/panels/docs/04-pages.md
Labels: documentation

#13508 Add table bulk select CSS selectors
  packages/tables/resources/views/components/selection/group-checkbox.blade.php
  packages/tables/resources/views/index.blade.php
Labels: enhancement

#13505 Fix ImportAction failed with Default Non-S3 Filesystem and Filament S3 Filesystem
  packages/actions/src/Concerns/CanImportRecords.php
Labels: bug

#13521 Fix evaluating labels in ternary filter
  packages/tables/src/Filters/TernaryFilter.php
Labels: bug

#13573 European Portuguese Translation
  packages/actions/resources/lang/pt_PT/import.php
  packages/forms/resources/lang/pt_PT/components.php
Labels: i18n

#13512 fix: allow view() to be used as icon
  packages/support/src/Concerns/HasIcon.php
Labels: bug

#13539 Add option to configure the default sort option label
  composer.lock
  packages/tables/docs/03-columns/01-getting-started.md
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Table/Concerns/CanSortRecords.php
Labels: enhancement

#13540 Add option to pass a closure as the sortable condition
  packages/tables/src/Columns/Concerns/CanBeSortable.php
Labels: enhancement

#13561 Docs Update: on Actions - Export Action
  packages/actions/docs/07-prebuilt-actions/09-export.md
Labels: documentation

#13563 Make Stat component macroable
  packages/widgets/src/StatsOverviewWidget/Stat.php
Labels: enhancement

#13574 Add section about cluster breadcrumb
  packages/panels/docs/10-clusters.md
Labels: documentation

#13526 Feat: ImportAction events
  packages/actions/src/Concerns/CanImportRecords.php
  packages/actions/src/Imports/Events/ImportChunkProcessed.php
  packages/actions/src/Imports/Events/ImportCompleted.php
  packages/actions/src/Imports/Events/ImportStarted.php
  packages/actions/src/Imports/Jobs/ImportCsv.php
  packages/tables/resources/views/index.blade.php
  packages/widgets/src/StatsOverviewWidget/Stat.php
Labels: enhancement

#13559 Allow table groups to accept a closure
  packages/tables/src/Table/Concerns/CanGroupRecords.php
Labels: enhancement

#13584 [4.x] Update vi translation
  packages/tables/resources/lang/vi/table.php
Labels: i18n

#13588 fix: allow to access default page for non-auth panel
  packages/panels/src/Panel/Concerns/HasRoutes.php
Labels: bug

#13593 Fix: avoid table polling while reordering
  packages/tables/resources/views/index.blade.php
Labels: bug

#13556 Override default number locale in Tables and Infolists
  packages/infolists/docs/03-entries/02-text.md
  packages/infolists/src/Components/Concerns/CanFormatState.php
  packages/infolists/src/Infolist.php
  packages/tables/docs/03-columns/02-text.md
  packages/tables/docs/07-summaries.md
  packages/tables/src/Columns/Concerns/CanFormatState.php
  packages/tables/src/Columns/Summarizers/Concerns/CanFormatState.php
  packages/tables/src/Table.php
Labels: bug

#13551 Fixed visibility of action buttons on form with deferred filters.
  packages/tables/src/Table/Concerns/HasFilters.php
Labels: bug

#13620 Fix array_reduce in new groups closure
  packages/tables/src/Table/Concerns/CanGroupRecords.php
Labels: bug

#13610 Update 09-file-upload.md
  packages/forms/docs/03-fields/09-file-upload.md
Labels: documentation

#13603 Fix nested Eager Loading for EntanglesStateWithSingularRelationship Components Concern
  packages/forms/src/Components/Concerns/EntanglesStateWithSingularRelationship.php
Labels: bug

#13567 Fix #13518
  packages/widgets/resources/js/components/stats-overview/stat/chart.js
Labels: bug

#13630 Fix: alpine errors when textarea is in modals
  packages/forms/resources/views/components/textarea.blade.php
Labels: bug

#13629 Add ide.json for Blade icon autocompletions with Laravel Idea
  ide.json
Labels: enhancement

#13624 Prevent resetting action record
  packages/actions/src/Concerns/CanOpenModal.php
  packages/actions/src/Concerns/InteractsWithRecord.php
  packages/actions/src/Contracts/HasRecord.php
Labels: bug

#13650 docs: Add an Explanation for Customizing Width of the Navigation
  packages/panels/docs/06-navigation.md
Labels: documentation

#13663 fix: fixed translation for e-mail in norwegian
  packages/panels/resources/lang/no/pages/auth/login.php
Labels: i18n

#13637 setRelation on the repeater component model after saving related data
  packages/forms/src/Components/Repeater.php
Labels: bug

#13677 fix: get correct primary key name from media class
  packages/spatie-laravel-media-library-plugin/src/Forms/Components/SpatieMediaLibraryFileUpload.php
Labels: bug

#13542 Fix: Make Select loadStateFromRelationshipsUsing() consider HasOne and HasMany relationships
  packages/forms/src/Components/Select.php
Labels: bug

#13665 Add font weight to filament::link component
  packages/support/docs/09-blade-components/02-link.md
  packages/support/resources/views/components/link.blade.php
  packages/support/src/Enums/FontWeight.php
Labels: enhancement

#13668 Fix replicate action not filling form data
  packages/actions/src/Concerns/CanReplicateRecords.php
  packages/widgets/resources/js/components/stats-overview/stat/chart.js
  tests/src/Tables/Actions/ActionTest.php
  tests/src/Tables/Fixtures/PostsTable.php
Labels: bug

#13680 Update 13-builder.md rename view path
  packages/forms/docs/03-fields/13-builder.md
Labels: documentation

#13653 Allowing $get() to get full array of current path
  packages/forms/docs/03-fields/12-repeater.md
  packages/forms/docs/03-fields/13-builder.md
  packages/forms/src/Components/Concerns/HasState.php
  packages/forms/src/Get.php
Labels: enhancement

#13634 Proposal: Add `filament:optimize` and `filament:optimize-clear` commands
  packages/panels/docs/01-installation.md
  packages/support/src/Commands/Concerns/CanCachePanelComponents.php
  packages/support/src/Commands/OptimizeClearCommand.php
  packages/support/src/Commands/OptimizeCommand.php
  packages/support/src/SupportServiceProvider.php
Labels: enhancement

#13679 Performance improvements for table checkboxes event listeners
  packages/tables/dist/components/table.js
  packages/tables/resources/js/components/table.js
Labels: enhancement

#13702 Add prefix and suffix to table summaries
  packages/tables/docs/07-summaries.md
  packages/tables/src/Columns/Summarizers/Concerns/CanFormatState.php
Labels: enhancement

#13705 accept `float` (decimal values) directly in `multipleOf()` rule helper
  packages/forms/src/Components/Concerns/CanBeValidated.php
Labels: bug

#13719 Update Spanish translations (import, actions modals)
  packages/actions/resources/lang/es/import.php
  packages/forms/resources/lang/es/components.php
Labels: i18n

#13707 Add Filament:generateResourceUrl() method
  packages/panels/src/Facades/Filament.php
  packages/panels/src/FilamentManager.php
  packages/panels/src/Panel.php
  packages/panels/src/Panel/Concerns/CanGenerateResourceUrls.php
  tests/src/Panels/Resources/ResourceTest.php
Labels: enhancement

#13735 fix: choicesjs toggle disable/enable
  packages/forms/resources/views/components/select.blade.php
Labels: bug

#13740 fix: nested modals scrolling issue
  package-lock.json
  package.json
  packages/support/resources/js/index.js
  packages/support/resources/views/components/modal/index.blade.php
Labels: bug

#13758 fix: Nullable select relationship
  packages/forms/src/Components/Select.php
Labels: bug

#13759 fixed typo in code sample
  packages/notifications/docs/02-sending-notifications.md
Labels: documentation

#13761 Update docs: Use closeModalByEscaping instead of closedByEscaping
  packages/actions/docs/04-modals.md
Labels: documentation
