Repository filamentphp/filament, pull requests merged in 2024-03, with the labels that each got.

#11638 Fix modal content padding
  packages/support/resources/views/components/modal/index.blade.php
Labels: bug, ui

#11635 Add size to action group
  packages/actions/resources/views/components/group.blade.php
Labels: bug

#11640 Opt in to database transactions
  packages/actions/src/CreateAction.php
  packages/actions/src/EditAction.php
  packages/panels/docs/09-configuration.md
  packages/panels/src/Pages/Auth/EditProfile.php
  packages/panels/src/Pages/Auth/Register.php
  packages/panels/src/Pages/Concerns/CanUseDatabaseTransactions.php
  packages/panels/src/Pages/Tenancy/EditTenantProfile.php
  packages/panels/src/Pages/Tenancy/RegisterTenant.php
  packages/panels/src/Panel.php
  packages/panels/src/Panel/Concerns/HasDatabaseTransactions.php
  packages/panels/src/Resources/Pages/CreateRecord.php
  packages/panels/src/Resources/Pages/EditRecord.php
  packages/spatie-laravel-settings-plugin/src/Pages/SettingsPage.php
  packages/tables/src/Actions/CreateAction.php
  packages/tables/src/Actions/EditAction.php
Labels: bug

#11642 Optionally call hooks, from getStateOnly and getStateExcept
  packages/forms/src/Concerns/HasState.php
Labels: enhancement

#11647 chart.js - Cannot read properties of undefined (reading destroy) on SPA Mode
  packages/widgets/resources/js/components/chart.js
Labels: bug

#11657 Support `Htmlable` navigation icons
  packages/panels/docs/03-resources/01-getting-started.md
  packages/panels/resources/views/components/page/sub-navigation/tabs.blade.php
  packages/panels/resources/views/components/sidebar/group.blade.php
  packages/panels/src/Navigation/NavigationItem.php
  packages/panels/src/Pages/Dashboard.php
  packages/panels/src/Pages/Page.php
  packages/panels/src/Resources/Pages/EditRecord.php
  packages/panels/src/Resources/Pages/ManageRelatedRecords.php
  packages/panels/src/Resources/Pages/ViewRecord.php
  packages/panels/src/Resources/Resource.php
  packages/support/resources/views/components/icon.blade.php
Labels: enhancement

#11658 Fix accepting heading and subheading slots
  packages/panels/resources/views/components/header/index.blade.php
  packages/panels/resources/views/components/page/index.blade.php
Labels: bug

#11659 Fix list bullets color
  packages/infolists/resources/views/components/text-entry.blade.php
  packages/tables/resources/views/columns/text-column.blade.php
Labels: bug, ui

#11524 Fix table overflow issue
  packages/tables/resources/views/index.blade.php
Labels: ui, high risk PR

#11661 filament/upgrade: Make rector rules compatible with required rector version
  composer.json
  composer.lock
  packages/upgrade/composer.json
  packages/upgrade/src/Rector/FixGetSetClosureTypesRector.php
  packages/upgrade/src/Rector/MoveImportedClassesRector.php
  packages/upgrade/src/Rector/SecondaryToGrayColorRector.php
  packages/upgrade/src/Rector/SimpleMethodChangesRector.php
  packages/upgrade/src/Rector/SimplePropertyChangesRector.php
  tests/src/Upgrade/RectorTest.php
Labels: bug

#11664 Add getDefaultName for Columns
  packages/tables/src/Columns/Column.php
  tests/src/Tables/ColumnTest.php
  tests/src/Tables/Fixtures/PostsTable.php
Labels: enhancement

#11695 Ability to set minHeight and maxHeight for markdown field
  packages/forms/dist/components/markdown-editor.js
  packages/forms/resources/js/components/markdown-editor.js
  packages/forms/resources/views/components/markdown-editor.blade.php
  packages/forms/src/Components/Concerns/HasMaxHeight.php
  packages/forms/src/Components/Concerns/HasMinHeight.php
  packages/forms/src/Components/MarkdownEditor.php
Labels: enhancement

#11692 Remove interactive styles from sidebar item without URL
  packages/panels/resources/views/components/sidebar/item.blade.php
Labels: bug, ui

#11698 fix: Sidebar scroll with collapsible dropdowns
  packages/panels/resources/views/components/layout/base.blade.php
  packages/panels/resources/views/components/layout/index.blade.php
  packages/panels/resources/views/components/sidebar/group.blade.php
  packages/panels/resources/views/components/sidebar/index.blade.php
Labels: bug

#11687 fix: icon position for action group in header actions
  packages/actions/resources/views/components/group.blade.php
Labels: bug

#11667 Refine applyGroupingToTableQuery to Control Eager Loading for isTableReordering
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Concerns/CanGroupRecords.php
Labels: bug

#11718 fix translation for bulk actions
  packages/tables/resources/lang/fa/table.php
Labels: i18n

#11712 Fix: "All" Pagination Bug with GROUP BY Clause in Table Query
  packages/tables/src/Concerns/CanPaginateRecords.php
Labels: bug

#11719 feature: Modify exporter query
  packages/actions/docs/07-prebuilt-actions/09-export.md
  packages/actions/src/Concerns/CanExportRecords.php
  packages/actions/src/Exports/Exporter.php
  packages/tables/src/Concerns/HasRecords.php
  packages/tables/src/Contracts/HasTable.php
Labels: bug, enhancement

#11720 feature: SPA mode URL exceptions
  packages/panels/docs/09-configuration.md
  packages/panels/src/Panel.php
  packages/panels/src/Panel/Concerns/HasSpaMode.php
  packages/support/src/Facades/FilamentView.php
  packages/support/src/View/ViewManager.php
  packages/support/src/helpers.php
Labels: enhancement

#11738 fix: Sanitized prefix/suffix Htmlable
  packages/infolists/docs/03-entries/02-text.md
  packages/infolists/src/Components/Concerns/CanFormatState.php
  packages/tables/docs/03-columns/02-text.md
  packages/tables/src/Columns/Concerns/CanFormatState.php
Labels: bug

#11737 Update 08-import.md
  packages/actions/docs/07-prebuilt-actions/08-import.md
Labels: documentation

#11741 sortablejs - group option support
  packages/support/resources/js/sortable.js
Labels: enhancement

#11749 Suggest resources when creating a page
  packages/panels/src/Commands/MakePageCommand.php
Labels: enhancement

#11759 Fix sidebar group icon exception
  packages/panels/resources/views/components/layout/index.blade.php
  packages/panels/resources/views/components/sidebar/group.blade.php
Labels: bug

#11742 Handle fallback url of media
  packages/spatie-laravel-media-library-plugin/src/Infolists/Components/SpatieMediaLibraryImageEntry.php
  packages/spatie-laravel-media-library-plugin/src/Tables/Columns/SpatieMediaLibraryImageColumn.php
Labels: bug

#11761 fix: SelectFilter recursive relationships
  packages/tables/src/Filters/Concerns/HasRelationship.php
  packages/tables/src/Filters/SelectFilter.php
Labels: bug

#11758 ImportAction Header Offset Customization
  packages/actions/docs/07-prebuilt-actions/08-import.md
  packages/actions/src/Concerns/CanImportRecords.php
Labels: enhancement

#11772 Add fi-input class on datepicker input
  packages/forms/resources/views/components/date-time-picker.blade.php
Labels: ui

#11766 Update 07-advanced.md
  packages/forms/docs/07-advanced.md
Labels: documentation

#11767 Update docs with missing HTML input type "integer" for TextInput
  packages/forms/docs/03-fields/02-text-input.md
Labels: documentation

#11770 Persist connection from model
  packages/tables/src/Columns/Summarizers/Summarizer.php
  packages/tables/src/Concerns/CanSummarizeRecords.php
Labels: documentation

#11763 Apply unsaved data changes alert on spatie settings page
  packages/spatie-laravel-settings-plugin/resources/views/pages/settings-page.blade.php
  packages/spatie-laravel-settings-plugin/src/Pages/SettingsPage.php
Labels: enhancement

#11769 Don't apply length constraints to numeric (decimal) input fields
  packages/forms/src/Components/Concerns/CanBeLengthConstrained.php
  packages/forms/src/Components/Concerns/CanBeValidated.php
  packages/forms/src/Components/Contracts/CanBeLengthConstrained.php
Labels: enhancement

#11773 fix: Cancel action respect history
  packages/panels/src/Pages/Auth/EditProfile.php
  packages/panels/src/Resources/Pages/CreateRecord.php
  packages/panels/src/Resources/Pages/EditRecord.php
Labels: bug

#11786 Protect properties and introduce getter
  packages/panels/resources/views/components/resources/relation-managers.blade.php
  packages/panels/src/Resources/RelationManagers/RelationManagerConfiguration.php
  packages/widgets/resources/views/components/widgets.blade.php
  packages/widgets/src/WidgetConfiguration.php
Labels: enhancement

#11795 fix: Reuse mounted action objects
  packages/actions/resources/views/components/modals.blade.php
  packages/actions/src/Concerns/CanOpenModal.php
  packages/actions/src/Concerns/InteractsWithActions.php
  packages/forms/src/Concerns/HasFormComponentActions.php
  packages/infolists/src/Concerns/InteractsWithInfolists.php
  packages/tables/src/Concerns/HasActions.php
  packages/tables/src/Concerns/HasBulkActions.php
Labels: bug

#11797 feature: Import row failure exception
  packages/actions/docs/07-prebuilt-actions/08-import.md
  packages/actions/src/Imports/Exceptions/RowImportFailedException.php
  packages/actions/src/Imports/Jobs/ImportCsv.php
Labels: enhancement

#11794 Stats Overview Docs - Clarify instructions
  packages/widgets/docs/02-stats-overview.md
Labels: documentation

#11796 Docs: CreateRecord expects a `create()` instead of `save()` in testing
  packages/forms/docs/09-testing.md
Labels: documentation

#11798 fix: BelongsTo foreign key overwriting
  packages/forms/src/Components/Select.php
Labels: bug

#11442 Add more CSS hook classes
  packages/tables/resources/views/components/actions/cell.blade.php
  packages/tables/resources/views/components/selection/cell.blade.php
  packages/widgets/resources/views/stats-overview-widget/stat.blade.php
Labels: enhancement

#11803 Improve wizard design responsiveness
  packages/forms/resources/views/components/wizard.blade.php
  packages/panels/dist/theme.css
Labels: bug, ui

#11807 Global search results: Only show a label prefix if the global search details specifies one
  packages/panels/resources/views/components/global-search/result.blade.php
  packages/widgets/resources/views/stats-overview-widget/stat.blade.php
Labels: enhancement

#11820 Add missing Catalan pagination translations
  packages/support/resources/lang/ca/components/pagination.php
Labels: i18n

#11817 Fix translation in created notification
  packages/panels/resources/lang/cs/resources/pages/create-record.php
Labels: i18n

#11816 Merge extra Attributes of ShowPasswordAction/HidePasswordAction
  packages/forms/src/Components/TextInput/Actions/HidePasswordAction.php
  packages/forms/src/Components/TextInput/Actions/ShowPasswordAction.php
Labels: bug

#11818 Add-extra-attributes-in-list-record-tabs
  packages/panels/docs/03-resources/02-listing-records.md
  packages/panels/resources/views/components/resources/tabs.blade.php
  packages/panels/src/Resources/Components/Tab.php
Labels: enhancement

#11823 Update 09-configuration.md
  packages/panels/docs/09-configuration.md
Labels: documentation

#11833 Fix RichEditor field state being changed inside of block builder when block is removed
  packages/forms/resources/views/components/rich-editor.blade.php
Labels: bug

#11834 TranslatableSpatieMediaLibraryFileUpload should first filter and then resize the collection
  packages/spatie-laravel-media-library-plugin/src/Forms/Components/SpatieMediaLibraryFileUpload.php
Labels: bug

#11843 Add missing BG translations
  packages/actions/resources/lang/bg/associate.php
  packages/actions/resources/lang/bg/attach.php
  packages/actions/resources/lang/bg/create.php
  packages/actions/resources/lang/bg/delete.php
  packages/actions/resources/lang/bg/detach.php
  packages/actions/resources/lang/bg/dissociate.php
  packages/actions/resources/lang/bg/edit.php
  packages/actions/resources/lang/bg/force-delete.php
  packages/actions/resources/lang/bg/group.php
  packages/actions/resources/lang/bg/modal.php
  packages/actions/resources/lang/bg/replicate.php
  packages/actions/resources/lang/bg/restore.php
  packages/actions/resources/lang/bg/view.php
  packages/forms/resources/lang/bg/components.php
  packages/infolists/resources/lang/bg/components.php
  packages/notifications/resources/lang/bg/database.php
  packages/panels/resources/lang/bg/global-search.php
  packages/panels/resources/lang/bg/layout.php
  packages/panels/resources/lang/bg/pages/auth/edit-profile.php
  packages/panels/resources/lang/bg/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/bg/pages/auth/login.php
  packages/panels/resources/lang/bg/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/bg/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/bg/pages/auth/register.php
  packages/panels/resources/lang/bg/pages/dashboard.php
  packages/panels/resources/lang/bg/pages/tenancy/edit-tenant-profile.php
  packages/panels/resources/lang/bg/resources/pages/create-record.php
  packages/panels/resources/lang/bg/resources/pages/edit-record.php
  packages/panels/resources/lang/bg/resources/pages/list-records.php
  packages/panels/resources/lang/bg/resources/pages/view-record.php
  packages/panels/resources/lang/bg/widgets/account-widget.php
  packages/panels/resources/lang/bg/widgets/filament-info-widget.php
  packages/support/resources/lang/bg/components/button.php
  packages/support/resources/lang/bg/components/copyable.php
  packages/support/resources/lang/bg/components/modal.php
  packages/support/resources/lang/bg/components/pagination.php
  packages/tables/resources/lang/bg/filters/query-builder.php
  packages/tables/resources/lang/bg/table.php
Labels: i18n

#11842 Check for mariadb in CanReadModelSchemas
  packages/support/src/Commands/Concerns/CanReadModelSchemas.php
Labels: enhancement

#11847 fix: Select label update when not preloaded
  packages/forms/dist/components/select.js
  packages/forms/resources/js/components/select.js
  packages/forms/src/Components/Select.php
Labels: bug

#11848 feature: Section save
  packages/forms/docs/04-layout/06-section.md
  packages/panels/docs/03-resources/04-editing-records.md
  packages/panels/src/Resources/Pages/EditRecord.php
Labels: enhancement

#11862 fix: Dynamic media collection
  packages/spatie-laravel-media-library-plugin/src/Forms/Components/SpatieMediaLibraryFileUpload.php
  packages/spatie-laravel-media-library-plugin/src/Infolists/Components/SpatieMediaLibraryImageEntry.php
  packages/spatie-laravel-media-library-plugin/src/Tables/Columns/SpatieMediaLibraryImageColumn.php
Labels: bug

#11863 feature: Allow all Spatie media
  packages/spatie-laravel-media-library-plugin/README.md
  packages/spatie-laravel-media-library-plugin/src/Infolists/Components/SpatieMediaLibraryImageEntry.php
  packages/spatie-laravel-media-library-plugin/src/SpatieLaravelMediaLibraryPlugin/Collections/AllMediaCollections.php
  packages/spatie-laravel-media-library-plugin/src/Tables/Columns/SpatieMediaLibraryImageColumn.php
Labels: enhancement

#11890 Cast $state to string before createFromFormat()
  packages/forms/src/Components/DateTimePicker.php
Labels: bug

#11869 Fix: getStartStep to accommodate for hidden components
  packages/forms/src/Components/Wizard.php
Labels: bug

#11899 fix: Actions inheriting props from groups
  packages/actions/src/ActionGroup.php
  packages/actions/src/Concerns/BelongsToGroup.php
  packages/actions/src/Concerns/BelongsToLivewire.php
  packages/actions/src/Concerns/CanBeHidden.php
  packages/actions/src/Concerns/InteractsWithRecord.php
  packages/actions/src/Contracts/HasLivewire.php
  packages/actions/src/StaticAction.php
  packages/tables/src/Actions/ActionGroup.php
  packages/tables/src/Actions/Concerns/BelongsToTable.php
  packages/tables/src/Actions/Contracts/HasTable.php
Labels: bug

#11865 Allow optionally hiding topbar on simple pages
  packages/panels/resources/views/components/layout/simple.blade.php
  packages/panels/src/Pages/SimplePage.php
Labels: enhancement

#11900 fix: JSON column sort/search
  packages/tables/src/Columns/Concerns/InteractsWithTableQuery.php
Labels: bug

#11907 feature: File upload nested recursive rules
  packages/forms/src/Components/BaseFileUpload.php
Labels: enhancement

#11920 Fixed toArray database notification
  packages/notifications/src/DatabaseNotification.php
Labels: enhancement

#11914 Feat: Add lifecyclehook events to actions
  packages/actions/src/Concerns/HasLifecycleHooks.php
  packages/actions/src/Events/ActionCalled.php
  packages/actions/src/Events/ActionCalling.php
Labels: enhancement

#11924 fix: Action group Livewire is null
  packages/actions/src/Action.php
  tests/src/Panels/Fixtures/Resources/PostResource/Pages/EditPost.php
Labels: bug

#11933 fix media collection variable name conflict
  packages/spatie-laravel-media-library-plugin/src/Infolists/Components/SpatieMediaLibraryImageEntry.php
  packages/spatie-laravel-media-library-plugin/src/Tables/Columns/SpatieMediaLibraryImageColumn.php
Labels: bug

#11937 fix: Morph Many associate
  packages/tables/src/Actions/AssociateAction.php
Labels: bug

#11938 Improve tenancy example in docs
  packages/panels/docs/11-tenancy.md
Labels: documentation

#11949 adding hook classes for sub navigation
  packages/panels/resources/views/components/page/sub-navigation/select.blade.php
  packages/panels/resources/views/components/page/sub-navigation/sidebar.blade.php
  packages/panels/resources/views/components/page/sub-navigation/tabs.blade.php
Labels: ui

#11954 Add missing de translations for relation edit modal
  packages/forms/resources/lang/de/components.php
Labels: i18n

#11947 Update 03-creating-records.md
  packages/panels/docs/03-resources/03-creating-records.md
Labels: documentation

#11955 fix: Table row action group with record-dependant hidden callback
  packages/panels/src/Resources/Pages/ListRecords.php
  packages/tables/src/Table/Concerns/HasActions.php
Labels: bug

#11961 Update Swedish translations
  packages/actions/resources/lang/sv/delete.php
  packages/actions/resources/lang/sv/export.php
  packages/actions/resources/lang/sv/import.php
  packages/forms/resources/lang/sv/components.php
  packages/forms/resources/lang/sv/validation.php
  packages/infolists/resources/lang/sv/components.php
  packages/panels/resources/lang/sv/pages/dashboard.php
  packages/support/resources/lang/sv/components/pagination.php
  packages/tables/resources/lang/sv/filters/query-builder.php
  packages/tables/resources/lang/sv/table.php
Labels: i18n

#11972 Allow symfony/html-sanitizer v7
  packages/support/composer.json
Labels: chore

#11979 Fix: Rich editor not displaying data when changing languages
  .github/ISSUE_TEMPLATE/bug_report.yml
  packages/forms/resources/views/components/rich-editor.blade.php
Labels: bug

#11970 Allow builder addAction to be hidden
  packages/forms/resources/views/components/builder.blade.php
Labels: enhancement

#11987 Pass target attribute to icon button when button label is hidden at breakpoint
  packages/support/resources/views/components/button/index.blade.php
Labels: bug

#12008 fix: Tenant domain slug attribute
  packages/panels/docs/11-tenancy.md
  packages/panels/src/Panel.php
Labels: bug

#11991 make IconColumn and IconEntry support collections
  packages/infolists/resources/views/components/color-entry.blade.php
  packages/infolists/resources/views/components/icon-entry.blade.php
  packages/infolists/resources/views/components/image-entry.blade.php
  packages/tables/resources/views/columns/color-column.blade.php
  packages/tables/resources/views/columns/icon-column.blade.php
  packages/tables/resources/views/columns/image-column.blade.php
Labels: enhancement

#12007 Native DatePicker: min and max HTML attribute shouldn't contain time
  packages/forms/resources/views/components/date-time-picker.blade.php
Labels: bug

#11857 Fix: scrollable tenant menu
  docs-assets/app/public/css/filament/filament/app.css
  docs-assets/app/public/js/filament/support/support.js
  packages/panels/dist/theme.css
  packages/panels/resources/views/components/tenant-menu.blade.php
  packages/support/resources/views/components/dropdown/index.blade.php
Labels: bug

#12014 Update vi translations
  packages/support/resources/lang/vi/components/pagination.php
Labels: i18n

#12011 Update 02-listing-records.md
  packages/panels/docs/03-resources/02-listing-records.md
Labels: documentation

#12013 Update korean translations
  packages/actions/resources/lang/ko/export.php
  packages/actions/resources/lang/ko/import.php
  packages/forms/resources/lang/ko/components.php
  packages/forms/resources/lang/ko/validation.php
  packages/infolists/resources/lang/ko/components.php
  packages/panels/resources/lang/ko/pages/dashboard.php
  packages/support/resources/lang/ko/components/pagination.php
  packages/tables/resources/lang/ko/filters/query-builder.php
  packages/tables/resources/lang/ko/table.php
Labels: i18n

#12010 Conditionally apply margin to notification contents
  packages/notifications/resources/views/notification.blade.php
Labels: bug, ui

#12025 Revert "Update 02-listing-records.md"
  packages/panels/docs/03-resources/02-listing-records.md
Labels: documentation

#12020 Add `handleRegistration()` method to register page
  packages/panels/src/Pages/Auth/Register.php
Labels: enhancement

#12033 Fix docs on how to change pagination page when testing
  packages/tables/docs/12-testing.md
Labels: documentation

#12041 fix: Notification action JS views
  packages/notifications/dist/index.js
  packages/notifications/resources/js/Notification.js
Labels: bug

#12046 Fix issue #12045 : Unsaved changes alert is triggered when none ascii characters are used.
  packages/panels/src/Pages/Concerns/HasUnsavedDataChangesAlert.php
Labels: bug

#12032 Handle array states and values in assertTableColumnStateSet
  packages/tables/src/Testing/TestsColumns.php
Labels: bug

#12052 fix: Group / summarizer date translations
  packages/tables/src/Columns/Summarizers/Range.php
  packages/tables/src/Grouping/Group.php
Labels: bug

#12054 Handle cases where Wizard Step is not found (hidden steps)
  packages/forms/resources/views/components/wizard.blade.php
Labels: bug

#12057 Minor fixes for Turkish language.
  packages/panels/resources/lang/tr/pages/auth/login.php
  packages/panels/resources/lang/tr/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/tr/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/tr/pages/auth/register.php
  packages/panels/resources/lang/tr/pages/tenancy/edit-tenant-profile.php
  packages/panels/resources/lang/tr/widgets/filament-info-widget.php
Labels: i18n

#12068 Update my (burmese) lang in login.php
  packages/panels/resources/lang/my/pages/auth/login.php
Labels: i18n

#12069 Update delete.php language file for Burmese language
  packages/actions/resources/lang/my/delete.php
Labels: i18n

#12075 Update Slovak translations
  packages/actions/resources/lang/sk/export.php
  packages/actions/resources/lang/sk/import.php
  packages/forms/resources/lang/sk/components.php
  packages/forms/resources/lang/sk/validation.php
  packages/infolists/resources/lang/sk/components.php
  packages/panels/resources/lang/sk/pages/dashboard.php
  packages/panels/resources/lang/sk/resources/pages/create-record.php
  packages/panels/resources/lang/sk/resources/pages/view-record.php
  packages/support/resources/lang/sk/components/pagination.php
  packages/tables/resources/lang/sk/table.php
Labels: i18n

#12077 Correct color count in docs (04-colors.md)
  packages/support/docs/04-colors.md
Labels: documentation

#12078 remove multiple dropdown arrows
  packages/forms/resources/views/components/select.blade.php
  packages/panels/dist/theme.css
Labels: bug, ui

#12098 removed unnecessary brackets
  packages/forms/docs/03-fields/18-toggle-buttons.md
Labels: documentation

#12097 fix: update testing docs with livewire plugin for pest
  packages/actions/docs/09-testing.md
  packages/forms/docs/09-testing.md
  packages/infolists/docs/08-testing.md
  packages/notifications/docs/06-testing.md
  packages/panels/docs/14-testing.md
  packages/tables/docs/12-testing.md
Labels: documentation

#12096 Enhance Table Row Reordering with Dragged Record ID Support
  packages/support/dist/index.js
  packages/tables/resources/views/components/table.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Concerns/CanReorderRecords.php
Labels: enhancement

#12095 BugFix: Import Action Look at File System Disk Driver for s3
  packages/actions/src/Concerns/CanImportRecords.php
Labels: bug

#12101 update filament.php, added forceTLS option to allow choosing between …
  packages/support/config/filament.php
Labels: enhancement

#12105 Fix Dragged Record ID Access in Table Reorder Event Handler
  packages/tables/resources/views/index.blade.php
Labels: bug
