Repository filamentphp/filament, pull requests merged in 2024-09, with the labels that each got.

#14124 Use assertEqualsCanonicalized() for summary testing
  packages/tables/docs/12-testing.md
  packages/tables/src/Testing/TestsSummaries.php
Labels: bug

#14101 Adding Page Sub Navigation Hooks
  packages/panels/resources/views/components/page/index.blade.php
  packages/panels/src/View/PanelsRenderHook.php
  packages/support/docs/06-render-hooks.md
Labels: enhancement

#14156 Update cancel button label to uppercase (Dutch language)
  packages/panels/resources/lang/nl/pages/auth/edit-profile.php
Labels: i18n

#14178 The toggleAllCheckboxes function should not check a disable checkbox
  packages/forms/resources/views/components/checkbox-list.blade.php
Labels: bug

#14200 fix: Unmounting actions dispatches close-modal when modal is already closed
  packages/actions/resources/views/components/modals.blade.php
  packages/actions/src/Concerns/InteractsWithActions.php
  packages/forms/src/Concerns/HasFormComponentActions.php
  packages/infolists/src/Concerns/InteractsWithInfolists.php
  packages/tables/src/Concerns/HasActions.php
Labels: bug

#14212 Disable reorderable when tagsinput is disabled
  packages/forms/resources/views/components/tags-input.blade.php
Labels: bug

#14220 fix: Parent modal not reopening after child modal is closed
  packages/forms/src/Concerns/HasFormComponentActions.php
Labels: bug

#14239 Upgrade alpine-lazy-load-assets to 1.3.0
  package-lock.json
  package.json
  packages/forms/dist/index.css
  packages/support/dist/index.css
  packages/support/dist/index.js
Labels: chore

#14255 Improve translation
  packages/panels/resources/lang/it/resources/pages/view-record.php
Labels: i18n

#14263 refactor(Tables): Add searchable functionality to SelectFilter
  packages/tables/src/Filters/SelectFilter.php
  tests/src/Tables/Fixtures/PostsTable.php
Labels: enhancement

#14187 fix creating resources in vendor when plugin uses cluster
  packages/panels/src/Commands/MakeClusterCommand.php
  packages/panels/src/Commands/MakePageCommand.php
  packages/panels/src/Commands/MakeRelationManagerCommand.php
  packages/panels/src/Commands/MakeResourceCommand.php
  packages/spatie-laravel-settings-plugin/src/Commands/MakeSettingsPageCommand.php
  packages/widgets/src/Commands/MakeWidgetCommand.php
Labels: bug

#14287 Update 02-text.md
  packages/tables/docs/03-columns/02-text.md
Labels: documentation

#14348 Update Spanish view action label translation
  packages/actions/resources/lang/es/view.php
Labels: i18n

#14366 docs: fix class typo
  packages/infolists/docs/04-layout/02-grid.md
Labels: documentation
