Repository filamentphp/filament, pull requests merged in 2024-04, with the labels that each got.

#12131 Translations: Nepali (ne)
  packages/actions/resources/lang/ne/global-search.php
  packages/actions/resources/lang/ne/layout.php
  packages/actions/resources/lang/ne/pages/auth/edit-profile.php
  packages/actions/resources/lang/ne/pages/auth/email-verification/email-verification-prompt.php
  packages/actions/resources/lang/ne/pages/auth/login.php
  packages/actions/resources/lang/ne/pages/auth/password-reset/request-password-reset.php
  packages/actions/resources/lang/ne/pages/auth/password-reset/reset-password.php
  packages/actions/resources/lang/ne/pages/auth/register.php
  packages/actions/resources/lang/ne/pages/dashboard.php
  packages/actions/resources/lang/ne/pages/tenancy/edit-tenant-profile.php
  packages/actions/resources/lang/ne/resources/pages/create-record.php
  packages/actions/resources/lang/ne/resources/pages/edit-record.php
  packages/actions/resources/lang/ne/resources/pages/list-records.php
  packages/actions/resources/lang/ne/resources/pages/view-record.php
  packages/actions/resources/lang/ne/widgets/account-widget.php
  packages/actions/resources/lang/ne/widgets/filament-info-widget.php
Labels: i18n

#12133 docs: Fix backticks to single quotes in docs
  packages/tables/docs/12-testing.md
Labels: documentation

#12104 Add sendEmailVerificationNotification method to EmailVerificationPrompt
  packages/panels/src/Pages/Auth/EmailVerification/EmailVerificationPrompt.php
Labels: enhancement

#12106 Add formId to actions
  packages/actions/resources/views/components/action.blade.php
  packages/actions/src/Concerns/CanSubmitForm.php
  packages/panels/docs/03-resources/03-creating-records.md
  packages/panels/docs/03-resources/04-editing-records.md
  packages/panels/resources/views/resources/pages/create-record.blade.php
  packages/panels/resources/views/resources/pages/edit-record.blade.php
  packages/support/resources/views/components/button/index.blade.php
  packages/support/resources/views/components/icon-button.blade.php
Labels: enhancement

#12120 Update Register.php
  packages/panels/src/Pages/Auth/Register.php
Labels: enhancement

#12128 Relation manager content tab improvements
  packages/panels/docs/03-resources/07-relation-managers.md
  packages/panels/resources/views/components/resources/relation-managers.blade.php
  packages/panels/resources/views/resources/pages/edit-record.blade.php
  packages/panels/resources/views/resources/pages/view-record.blade.php
  packages/panels/src/Resources/Pages/Concerns/HasRelationManagers.php
  packages/panels/src/Resources/Pages/ContentTabPosition.php
Labels: enhancement

#12143 fix: SelectFilter relationship qualified title attribute
  packages/tables/src/Filters/Concerns/HasRelationship.php
Labels: bug

#12147 doc: Modification of backquotes within the document.
  packages/tables/docs/03-columns/02-text.md
  packages/tables/docs/03-columns/05-color.md
  packages/tables/docs/12-testing.md
Labels: documentation

#12145 Change hasTopNavigation
  packages/panels/src/Panel/Concerns/HasTopNavigation.php
Labels: enhancement

#12144 Thai Translation of UI
  packages/actions/resources/lang/th/associate.php
  packages/actions/resources/lang/th/attach.php
  packages/actions/resources/lang/th/create.php
  packages/actions/resources/lang/th/delete.php
  packages/actions/resources/lang/th/detach.php
  packages/actions/resources/lang/th/dissociate.php
  packages/actions/resources/lang/th/edit.php
  packages/actions/resources/lang/th/export.php
  packages/actions/resources/lang/th/force-delete.php
  packages/actions/resources/lang/th/group.php
  packages/actions/resources/lang/th/import.php
  packages/actions/resources/lang/th/modal.php
  packages/actions/resources/lang/th/replicate.php
  packages/actions/resources/lang/th/restore.php
  packages/actions/resources/lang/th/view.php
  packages/forms/resources/lang/th/components.php
  packages/forms/resources/lang/th/validation.php
  packages/infolists/resources/lang/th/components.php
  packages/notifications/resources/lang/th/database.php
  packages/panels/resources/lang/th/global-search.php
  packages/panels/resources/lang/th/layout.php
  packages/panels/resources/lang/th/pages/auth/edit-profile.php
  packages/panels/resources/lang/th/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/th/pages/auth/login.php
  packages/panels/resources/lang/th/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/th/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/th/pages/auth/register.php
  packages/panels/resources/lang/th/pages/dashboard.php
  packages/panels/resources/lang/th/pages/tenancy/edit-tenant-profile.php
  packages/panels/resources/lang/th/resources/pages/create-record.php
  packages/panels/resources/lang/th/resources/pages/edit-record.php
  packages/panels/resources/lang/th/resources/pages/list-records.php
  packages/panels/resources/lang/th/resources/pages/view-record.php
  packages/panels/resources/lang/th/widgets/account-widget.php
  packages/panels/resources/lang/th/widgets/filament-info-widget.php
  packages/support/resources/lang/th/components/button.php
  packages/support/resources/lang/th/components/copyable.php
  packages/support/resources/lang/th/components/modal.php
  packages/support/resources/lang/th/components/pagination.php
  packages/tables/resources/lang/th/table.php
Labels: i18n

#12142 Remove warning about Livewire v3 release
  packages/actions/docs/01-installation.md
  packages/actions/docs/10-upgrade-guide.md
  packages/forms/docs/01-installation.md
  packages/forms/docs/10-upgrade-guide.md
  packages/infolists/docs/01-installation.md
  packages/notifications/docs/01-installation.md
  packages/notifications/docs/07-upgrade-guide.md
  packages/panels/docs/01-installation.md
  packages/panels/docs/15-upgrade-guide.md
  packages/tables/docs/01-installation.md
  packages/tables/docs/13-upgrade-guide.md
  packages/widgets/docs/01-installation.md
Labels: documentation

#12122 Fix long label in CheckboxList Component
  packages/forms/resources/views/components/checkbox-list.blade.php
Labels: bug, ui

#12163 Improve accuracy in docs (02-text-input.md)
  packages/forms/docs/03-fields/02-text-input.md
Labels: documentation

#12148 Add isFiltered property and getter
  packages/tables/src/Table/Concerns/HasFilters.php
Labels: enhancement

#12167 Fix quirk with beforeSave hook on EditRecord page
  packages/forms/src/Concerns/HasState.php
  packages/panels/src/Resources/Pages/EditRecord.php
Labels: bug

#12196 Add zh_CN Action Translation
  packages/actions/resources/lang/zh_CN/export.php
Labels: i18n

#12201 Fix typo in docs 10-clusters.md
  packages/panels/docs/10-clusters.md
Labels: documentation

#12204 feat: add Greek translations for auth features
  packages/panels/resources/lang/el/pages/auth/edit-profile.php
  packages/panels/resources/lang/el/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/el/pages/auth/login.php
  packages/panels/resources/lang/el/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/el/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/el/pages/auth/register.php
Labels: i18n

#12202 Rename tables.php to table.php
  packages/tables/resources/lang/el/table.php
Labels: i18n

#12203 feat: add Greek translations for support package
  packages/support/resources/lang/el/components/button.php
  packages/support/resources/lang/el/components/copyable.php
  packages/support/resources/lang/el/components/modal.php
  packages/support/resources/lang/el/components/pagination.php
Labels: i18n

#12197 Ensure Only Initial CSV File in Export Retains BOM
  packages/actions/src/Exports/Downloaders/CsvDownloader.php
Labels: bug

#12190 Fix: getComponents reset array keys after array_filter (Follow-up Fix of #11869)
  packages/forms/src/Concerns/HasComponents.php
Labels: bug

#12212 Fixed attribute reference in ukrainian translation
  packages/actions/resources/lang/uk/export.php
Labels: i18n

#12211 Fix docs assertions for `assertSelectColumnHasOptions` and `assertSelectColumnDoesNotHaveOptions`
  packages/tables/docs/12-testing.md
Labels: documentation

#12216 feat(i8n): update indonesian translation
  packages/panels/resources/lang/id/layout.php
  packages/support/resources/lang/id/components/pagination.php
Labels: i18n

#12221 Fix typos in enums docs
  packages/support/docs/07-enums.md
Labels: documentation

#12243 Update German table empty state heading translation
  packages/tables/resources/lang/de/table.php
Labels: i18n

#12251 Added missed Ukrainian translations
  packages/support/resources/lang/uk/components/pagination.php
  packages/tables/resources/lang/uk/filters/query-builder.php
  packages/tables/resources/lang/uk/table.php
Labels: i18n

#12260 European Portuguese Translation
  packages/panels/resources/lang/pt_PT/layout.php
Labels: i18n

#12261 Fix createOptionUsing with multiple() and no initial options
  packages/forms/src/Components/Select.php
Labels: bug

#12236 add render hook in bulk action indicator
  packages/support/docs/06-render-hooks.md
  packages/tables/resources/views/components/selection/indicator.blade.php
  packages/tables/src/View/TablesRenderHook.php
Labels: enhancement

#12038 Adding application/vnd.ms-excel to accepted file types for importing
  packages/actions/src/Concerns/CanImportRecords.php
Labels: bug

#12245 Update ImportColumn.php to support negative numerics
  packages/actions/src/Imports/ImportColumn.php
Labels: bug

#12268 Fix Arabic query builder translations
  packages/tables/resources/lang/ar/filters/query-builder.php
Labels: i18n

#12187 Style notifications based on status
  packages/notifications/resources/views/notification.blade.php
Labels: enhancement

#12191 Fix $persist breaking Alpine when Tabs are used in modals
  packages/forms/resources/views/components/tabs.blade.php
Labels: bug

#12186 Improve PostgreSQL Ordering Compatibility in PrepareCsvExport Job
  packages/actions/src/Exports/Jobs/PrepareCsvExport.php
Labels: bug

#12155 Add `extraModalWindowAttributes`
  packages/actions/docs/04-modals.md
  packages/actions/resources/views/components/modals.blade.php
  packages/actions/src/Concerns/HasExtraModalWindowAttributes.php
  packages/actions/src/MountableAction.php
  packages/support/resources/views/components/modal/index.blade.php
Labels: enhancement

#12283 Support saving without notification
  packages/panels/src/Resources/Pages/EditRecord.php
Labels: enhancement

#12286 chore/changing document retrieval failiures to 404
  packages/actions/src/Exports/Downloaders/CsvDownloader.php
  packages/actions/src/Exports/Downloaders/XlsxDownloader.php
Labels: bug

#12302 Detect vite.config.ts when creating new theme
  packages/panels/src/Commands/MakeThemeCommand.php
Labels: bug

#12339 fix: Modal alignment
  packages/actions/src/Concerns/CanOpenModal.php
Labels: bug

#12340 fix: Catalan translations - minor typo
  packages/infolists/resources/lang/ca/components.php
Labels: i18n

#12346 Updated norwegian translation
  packages/actions/resources/lang/no/export.php
  packages/actions/resources/lang/no/import.php
  packages/forms/resources/lang/no/components.php
  packages/forms/resources/lang/no/validation.php
  packages/infolists/resources/lang/no/components.php
  packages/panels/resources/lang/no/pages/dashboard.php
  packages/tables/resources/lang/no/filters/query-builder.php
  packages/tables/resources/lang/no/table.php
Labels: i18n

#12344 Feat: Add Catalan translations in file-upload component
  package-lock.json
  package.json
  packages/forms/dist/components/file-upload.js
  packages/forms/dist/index.css
  packages/forms/resources/js/components/file-upload.js
Labels: i18n

#12325 [Documentation] Fix DatabaseNotifications pollingInterval
  packages/notifications/docs/03-database-notifications.md
Labels: documentation

#12355 Fix for bug #11541
  packages/forms/resources/views/components/builder/block-picker.blade.php
Labels: bug

#12356 fix: Duplicate request to count records
  packages/tables/src/Concerns/CanPaginateRecords.php
Labels: bug

#12348 Fixed bug issue on TextArea with autosize after validation failed
  packages/forms/resources/views/components/textarea.blade.php
Labels: bug

#12308 Fixes bug when attaching a belongsToMany relation that has an orderByPivot
  packages/support/src/Services/RelationshipJoiner.php
Labels: bug

#12360 Add completed icon retrieval in wizard component
  packages/forms/resources/views/components/wizard.blade.php
Labels: bug

#12365 Minor fix in getting started panel docs
  packages/panels/docs/02-getting-started.md
Labels: documentation

#12366 Lithuanian translations update
  packages/actions/resources/lang/lt/export.php
  packages/actions/resources/lang/lt/import.php
  packages/forms/resources/lang/lt/components.php
  packages/forms/resources/lang/lt/validation.php
  packages/infolists/resources/lang/lt/components.php
  packages/panels/resources/lang/lt/layout.php
  packages/panels/resources/lang/lt/pages/dashboard.php
  packages/support/resources/lang/lt/components/pagination.php
  packages/tables/resources/lang/lt/table.php
Labels: i18n

#12382 Fix bug #12342
  packages/notifications/src/Livewire/DatabaseNotifications.php
Labels: bug

#12379 Fix: Select HasManyThrough relationship
  packages/forms/resources/lang/lt/components.php
  packages/forms/src/Components/Select.php
  packages/support/resources/views/components/button/index.blade.php
Labels: bug

#12372 Fixed repeater with translation bug #8328
  packages/spatie-laravel-translatable-plugin/src/Resources/Pages/EditRecord/Concerns/Translatable.php
  packages/spatie-laravel-translatable-plugin/src/Resources/Pages/ViewRecord/Concerns/Translatable.php
Labels: bug, high risk PR

#12391 Bump Livewire to 3.4.10
  composer.lock
  packages/support/composer.json
Labels: bug

#12389 Fix typo in Lithuanian export translation
  packages/actions/resources/lang/lt/export.php
Labels: i18n

#12405 removes highlighting when day is disabled
  packages/forms/resources/views/components/date-time-picker.blade.php
Labels: bug

#12398 Add usual search / naming to disable placeholder selection
  packages/tables/docs/04-filters/02-select.md
Labels: documentation

#12422 Update german request-password-reset.php
  packages/panels/resources/lang/de/pages/auth/password-reset/request-password-reset.php
Labels: i18n

#12423 Create german unsaved-changes-alert.php
  packages/panels/resources/lang/de/unsaved-changes-alert.php
Labels: i18n

#12424 Update german email-verification-prompt.php
  packages/panels/resources/lang/de/pages/auth/email-verification/email-verification-prompt.php
Labels: i18n

#12421 Update german components.php
  packages/forms/resources/lang/de/components.php
Labels: i18n

#12425 Update german layout.php
  packages/panels/resources/lang/de/layout.php
Labels: i18n

#12414 Allow Htmlable on Table actions column label
  packages/tables/src/Table.php
  packages/tables/src/Table/Concerns/HasActions.php
Labels: enhancement

#12433 Unsaved changes alert lithuanian translation
  packages/panels/resources/lang/lt/unsaved-changes-alert.php
Labels: i18n

#12400 Fix for bug #12392
  packages/forms/resources/js/components/markdown-editor.js
  packages/forms/resources/views/components/markdown-editor.blade.php
  packages/support/resources/views/components/button/index.blade.php
Labels: bug

#12435 update CS translation
  packages/panels/resources/lang/cs/pages/auth/login.php
Labels: i18n

#12437 Update Plugin Object Docs
  packages/support/docs/08-plugins/01-getting-started.md
Labels: documentation

#12438 Create korean unsaved-changes-alert.php
  packages/panels/resources/lang/ko/unsaved-changes-alert.php
Labels: i18n

#12439 Database notification docs
  packages/notifications/docs/03-database-notifications.md
Labels: documentation

#12444 CanLimitItemsLength trait for CheckboxList field
  packages/forms/src/Components/CheckboxList.php
Labels: enhancement

#12451 Fix placeholder line height
  packages/infolists/resources/views/components/entries/placeholder.blade.php
  packages/tables/resources/views/components/columns/placeholder.blade.php
Labels: bug, ui

#12470 Fix for bug #12115
  packages/tables/src/Actions/AssociateAction.php
Labels: bug

#12475 add missing Fa lang for table
  packages/tables/resources/lang/fa/table.php
Labels: i18n

#12480 translate spanish
  packages/panels/resources/lang/es/layout.php
  packages/panels/resources/lang/es/unsaved-changes-alert.php
Labels: i18n

#12488 Missing Translation - European Portuguese
  packages/panels/resources/lang/pt_PT/unsaved-changes-alert.php
Labels: i18n

#12503 Fix deadcode (duplicate) method canAccess()
  packages/panels/src/Pages/Page.php
Labels: chore

#12510 Support binding email verification notification
  packages/panels/src/Pages/Auth/EmailVerification/EmailVerificationPrompt.php
  packages/panels/src/Pages/Auth/Register.php
Labels: enhancement

#12513 Add missing SK translations
  packages/panels/resources/lang/sk/pages/auth/login.php
  packages/panels/resources/lang/sk/unsaved-changes-alert.php
Labels: i18n

#12514 Allow local links in rich editor
  packages/forms/resources/views/components/rich-editor.blade.php
Labels: bug

#12462 Allow each domains to have its own routes to avoid duplicate route registration
  packages/panels/routes/web.php
  packages/panels/src/Facades/Filament.php
  packages/panels/src/FilamentManager.php
  packages/panels/src/Panel/Concerns/HasRoutes.php
  packages/support/resources/views/components/button/index.blade.php
  tests/src/MultiDomainPanel.php
  tests/src/Panels/Routes/SingleAndMultiDomainTest.php
  tests/src/SingleDomainPanel.php
  tests/src/TestCase.php
Labels: bug

#12515 Add option to remove topbar from the profile page
  packages/panels/src/Pages/Auth/EditProfile.php
  packages/panels/src/Pages/Concerns/HasMaxWidth.php
  packages/panels/src/Pages/Concerns/HasTopbar.php
  packages/panels/src/Pages/SimplePage.php
Labels: enhancement

#12528 Added missing CS translation
  packages/forms/resources/lang/cs/components.php
  packages/panels/resources/lang/cs/unsaved-changes-alert.php
  packages/support/resources/lang/cs/components/pagination.php
  packages/tables/resources/lang/cs/table.php
Labels: i18n

#12540 euc-kr is a superset of iso-8859-1
  packages/actions/src/Concerns/CanImportRecords.php
Labels: bug

#12534 Documentation "notifications/sending-notifications": title & body attribute - Added HTML / Markdown examples
  packages/notifications/docs/02-sending-notifications.md
Labels: documentation

#12533 Closure support to forms method on CanBeValidated trait
  packages/forms/src/Components/Concerns/CanBeValidated.php
Labels: enhancement

#12546 Fix namespace typo \Filament\Forms\Components\Tabs\Tab::class
  packages/forms/resources/views/components/tabs/tab.blade.php
Labels: bug
