Repository filamentphp/filament, pull requests merged in 2024-06, with the labels that each got.

#13034 Rename extraFieldWrapperAttributes to extraEntryWrapperAttributes
  packages/infolists/docs/03-entries/01-getting-started.md
  packages/panels/resources/views/components/layout/base.blade.php
Labels: documentation

#13033 Update Albanian pagination translation
  packages/support/resources/lang/sq/components/pagination.php
Labels: i18n

#13052 Fix issue when Cluster large Submenu items makes content grid align items centered instead of start
  packages/panels/resources/views/components/page/index.blade.php
Labels: bug

#13040 The import or export notification header depends on getCompletedNotificationTitle function
  packages/actions/src/Concerns/CanImportRecords.php
  packages/actions/src/Exports/Exporter.php
  packages/actions/src/Exports/Jobs/ExportCompletion.php
  packages/actions/src/Imports/Importer.php
Labels: enhancement

#13043 Add documentation for publishing stubs
  packages/support/docs/09-stubs.md
Labels: documentation

#13072 Minor fixes on French translations
  packages/panels/resources/lang/fr/pages/auth/edit-profile.php
Labels: i18n

#13056 Auth classes rate limit notification method
  packages/panels/src/Pages/Auth/EmailVerification/EmailVerificationPrompt.php
  packages/panels/src/Pages/Auth/Login.php
  packages/panels/src/Pages/Auth/PasswordReset/RequestPasswordReset.php
  packages/panels/src/Pages/Auth/PasswordReset/ResetPassword.php
  packages/panels/src/Pages/Auth/Register.php
Labels: enhancement

#13078 Add `Support & Help` page to documenation
  packages/support/docs/10-support.md
Labels: documentation

#13038 Fix custom size CSS class
  packages/support/resources/views/components/button/index.blade.php
  packages/support/resources/views/components/link.blade.php
Labels: bug

#13088 fix: typo 'Complile' on 03-charts.md
  packages/widgets/docs/03-charts.md
Labels: documentation

#13082 fix: handle panel ID correctly in make:filament-resource command
  packages/panels/src/Commands/MakeClusterCommand.php
  packages/panels/src/Commands/MakePageCommand.php
  packages/panels/src/Commands/MakeRelationManagerCommand.php
  packages/panels/src/Commands/MakeResourceCommand.php
  packages/panels/src/Commands/MakeThemeCommand.php
  packages/panels/src/Facades/Filament.php
  packages/panels/src/FilamentManager.php
  packages/panels/src/PanelRegistry.php
  packages/spatie-laravel-settings-plugin/src/Commands/MakeSettingsPageCommand.php
  packages/widgets/src/Commands/MakeWidgetCommand.php
Labels: bug

#13099 feat: set locale on DateTimePicker field
  packages/forms/docs/03-fields/08-date-time-picker.md
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/src/Components/DateTimePicker.php
Labels: enhancement

#13101 fix: Teleport modal forms to avoid nesting issues
  packages/actions/resources/views/components/modals.blade.php
Labels: bug

#13111 change tabindex for login form
  packages/panels/src/Pages/Auth/Login.php
Labels: enhancement

#13102 Ignore textarea style height by default, not just on auto size
  packages/forms/resources/views/components/textarea.blade.php
Labels: bug

#13107 Fix getting infolist action in test methods
  packages/infolists/src/Testing/TestsActions.php
Labels: bug

#13142 Improve Malaysian translations
  packages/support/resources/lang/ms/components/pagination.php
  packages/tables/resources/lang/ms/table.php
Labels: i18n

#13041 Fix text wrapping for bulleted list
  packages/tables/resources/views/columns/text-column.blade.php
Labels: bug, ui

#13125 Prevent infolist entry grid blowout
  packages/infolists/resources/views/components/entry-wrapper/index.blade.php
Labels: ui

#12784 Support badge size for action components
  packages/panels/dist/theme.css
  packages/support/resources/views/components/button/index.blade.php
  packages/support/resources/views/components/icon-button.blade.php
  packages/support/resources/views/components/link.blade.php
Labels: enhancement

#13150 Prevent hidden wizard steps to be focusable
  packages/forms/resources/views/components/tabs/tab.blade.php
  packages/forms/resources/views/components/wizard/step.blade.php
  packages/infolists/resources/views/components/tabs/tab.blade.php
  packages/support/resources/views/components/section/index.blade.php
Labels: bug

#13154 Adding assertFormComponentExists() test method for forms
  packages/forms/.stubs.php
  packages/forms/docs/09-testing.md
  packages/forms/src/Concerns/HasComponents.php
  packages/forms/src/Testing/TestsForms.php
  tests/src/Forms/FormsTest.php
Labels: enhancement

#13130 Add missing class string type annotations
  packages/panels/src/Resources/Pages/Page.php
Labels: code quality

#12629 Support previews in builder
  packages/forms/docs/03-fields/13-builder.md
  packages/forms/resources/lang/en/components.php
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/src/Components/Builder.php
  packages/forms/src/Components/Builder/Block.php
  packages/forms/src/Components/Concerns/HasPreview.php
Labels: enhancement

#13165 Fix wrong type in docs
  packages/actions/docs/07-prebuilt-actions/08-import.md
Labels: documentation

#13167 docs: Removed extra parenthesis in modifyQueryUsing
  packages/panels/docs/11-tenancy.md
Labels: documentation

#13166 Add fallback default locale for format curreny
  packages/infolists/src/Components/Concerns/CanFormatState.php
  packages/tables/src/Columns/Concerns/CanFormatState.php
  packages/tables/src/Columns/Summarizers/Concerns/CanFormatState.php
Labels: bug

#13173 Update Dutch builder translations
  packages/forms/resources/lang/nl/components.php
Labels: i18n

#13175 feature: Disable validation for not dehydrated fields
  .phpunit.cache/test-results
  packages/forms/docs/05-validation.md
  packages/schema/src/Components/Concerns/HasState.php
  packages/schema/src/Concerns/CanBeValidated.php
  packages/schema/src/Concerns/HasState.php
  tests/src/Forms/ValidationTest.php
Labels: enhancement

#13178 Escape `$recordGroupTitle` when passed to Alpine in table view
  packages/tables/resources/views/index.blade.php
Labels: bug

#13186 Fix for bug introduced in #13074: Shift+Click to select records breaks spa mode
  docs-assets/app/public/css/filament/filament/app.css
  docs-assets/app/public/js/filament/tables/components/table.js
  packages/tables/dist/components/table.js
  packages/tables/resources/js/components/table.js
Labels: bug

#13194 Fixes for vulnerabilities
  docs-assets/app/package-lock.json
Labels: chore

#13191 Fix recursive validation attributes
  packages/forms/src/Components/Concerns/HasNestedRecursiveValidationRules.php
  packages/tables/resources/js/components/table.js
  packages/tables/resources/views/index.blade.php
Labels: bug

#13199 docs: Add info on programmatically triggering actions
  packages/actions/docs/06-adding-an-action-to-a-livewire-component.md
Labels: documentation

#13196 Add tooltip option to `->since()`
  packages/tables/src/Columns/Concerns/CanFormatState.php
Labels: enhancement

#13222 Force hint actions to justify end when label is hidden
  packages/forms/resources/views/components/field-wrapper/index.blade.php
Labels: bug

#13220 Support multiple boot using callbacks
  packages/panels/src/Panel.php
Labels: enhancement

#13219 3.x.component tests
  packages/forms/.stubs.php
  packages/forms/docs/09-testing.md
  packages/forms/src/Testing/TestsForms.php
  tests/src/Forms/FormsTest.php
Labels: enhancement

#13218 Feature/add icons to builder header
  packages/forms/docs/03-fields/13-builder.md
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/src/Components/Builder.php
Labels: enhancement

#13211 Fix textarea resizing preserving heights with/without autosize
  docs-assets/app/public/css/filament/filament/app.css
  docs-assets/app/public/js/filament/forms/components/textarea.js
  packages/forms/dist/components/textarea.js
  packages/forms/resources/js/components/textarea.js
  packages/forms/resources/views/components/textarea.blade.php
  packages/panels/dist/theme.css
Labels: bug

#13228 Improve export action arabic translation
  packages/actions/resources/lang/ar/export.php
Labels: i18n

#13229 Update date-time-picker.js to use advancedFormat plugin for more flexible date formatting
  packages/forms/dist/components/date-time-picker.js
  packages/forms/resources/js/components/date-time-picker.js
Labels: enhancement

#13233 Add missing AR translations
  packages/actions/resources/lang/ar/import.php
  packages/forms/resources/lang/ar/components.php
  packages/panels/resources/lang/ar/layout.php
  packages/panels/resources/lang/ar/unsaved-changes-alert.php
  packages/support/resources/lang/ar/components/pagination.php
Labels: i18n

#13241 Removes the empty dropdown panel
  packages/support/resources/views/components/dropdown/index.blade.php
Labels: ui

#13248 RichEditor: Fix value not clearing after Create & Create Another
  packages/forms/dist/components/rich-editor.js
  packages/forms/resources/js/components/rich-editor.js
Labels: bug

#13171 Allow multiple lines to be added to the import example file.
  packages/actions/docs/07-prebuilt-actions/08-import.md
  packages/actions/src/Concerns/CanImportRecords.php
  packages/actions/src/Imports/ImportColumn.php
Labels: enhancement

#13253 Remove duplicate title attribute from rich editor toolbar button
  packages/forms/resources/views/components/rich-editor.blade.php
Labels: bug

#13271 Validate options by default
  packages/forms/src/Components/CheckboxList.php
  packages/forms/src/Components/Concerns/CanBeValidated.php
  packages/forms/src/Components/Radio.php
  packages/forms/src/Components/Select.php
  packages/forms/src/Components/ToggleButtons.php
  packages/tables/src/Columns/SelectColumn.php
  tests/src/Forms/ValidationTest.php
Labels: enhancement

#13263 add missing keys in rich editor toolbar button
  packages/forms/resources/views/components/rich-editor.blade.php
Labels: enhancement

#13272 feature: Default sub navigation position control
  packages/panels/docs/03-resources/01-getting-started.md
  packages/panels/docs/04-pages.md
  packages/panels/docs/09-configuration.md
  packages/panels/docs/10-clusters.md
  packages/panels/src/Facades/Filament.php
  packages/panels/src/FilamentManager.php
  packages/panels/src/Pages/Concerns/HasSubNavigation.php
  packages/panels/src/Panel.php
  packages/panels/src/Panel/Concerns/HasSubNavigation.php
  packages/panels/src/Resources/Pages/Page.php
  packages/panels/src/Resources/Resource/Concerns/HasNavigation.php
  packages/upgrade/src/Rector/FixGetSetClosureTypesRector.php
  packages/upgrade/src/Rector/MoveImportedClassesRector.php
  packages/upgrade/src/Rector/SecondaryToGrayColorRector.php
  packages/upgrade/src/Rector/SimpleMethodChangesRector.php
  packages/upgrade/src/Rector/SimplePropertyChangesRector.php
  packages/upgrade/src/rector.php
Labels: enhancement

#13274 feature: Access parent action data and arguments
  packages/actions/docs/04-modals.md
  packages/actions/resources/views/action-modal.blade.php
  packages/actions/resources/views/components/modals.blade.php
  packages/actions/src/Action.php
  packages/actions/src/Concerns/HasArguments.php
  packages/actions/src/Concerns/HasForm.php
  packages/actions/src/Concerns/InteractsWithActions.php
  packages/actions/src/Testing/TestsActions.php
  packages/support/src/Partials/SupportPartials.php
  tests/src/Actions/ActionTest.php
  tests/src/Actions/Fixtures/Pages/Actions.php
Labels: enhancement

#13276 feature: Pagination mode config
  packages/tables/docs/10-advanced.md
  packages/tables/docs/13-upgrade-guide.md
  packages/tables/src/Concerns/CanPaginateRecords.php
  packages/tables/src/Enums/PaginationMode.php
  packages/tables/src/Table/Concerns/CanPaginateRecords.php
  packages/widgets/src/TableWidget.php
Labels: enhancement

#13277 preserveFormDataWhenCreatingAnother()
  packages/actions/docs/07-prebuilt-actions/01-create.md
  packages/panels/docs/03-resources/03-creating-records.md
  packages/panels/src/Resources/Pages/CreateRecord.php
  packages/schema/src/Concerns/HasState.php
  packages/upgrade/src/Rector/SimpleMethodChangesRector.php
  packages/widgets/src/TableWidget.php
  tests/src/Panels/Fixtures/Resources/PostResource/Pages/CreateAnotherPreservingDataPost.php
  tests/src/Panels/Resources/Pages/CreateRecordTest.php
Labels: enhancement

#13279 feature: hiddenJs() / visibleJs()
  bin/build.js
  packages/schema/dist/index.js
  packages/schema/resources/js/index.js
  packages/schema/resources/views/component-container.blade.php
  packages/schema/src/Components/Concerns/CanBeHidden.php
  packages/schema/src/SchemaServiceProvider.php
Labels: enhancement

#13283 feature: ChartWidget filters schema
  packages/panels/resources/views/pages/dashboard.blade.php
  packages/widgets/resources/lang/en/chart.php
  packages/widgets/resources/views/chart-widget.blade.php
  packages/widgets/src/ChartWidget.php
  packages/widgets/src/ChartWidget/Concerns/HasFiltersSchema.php
  packages/widgets/src/WidgetsServiceProvider.php
Labels: enhancement

#13281 fix incorrect user checking code inside of scope & observer docs
  packages/panels/docs/11-tenancy.md
Labels: documentation

#13285 Local Inter font
  bin/build.js
  package-lock.json
  package.json
  packages/panels/dist/fonts/inter/index.css
  packages/panels/dist/fonts/inter/index.js
  packages/panels/dist/fonts/inter/inter-cyrillic-ext-wght-normal-XKHXBTUO.woff2
  packages/panels/dist/fonts/inter/inter-cyrillic-wght-normal-R5CMSONN.woff2
  packages/panels/dist/fonts/inter/inter-greek-ext-wght-normal-ZEVLMORV.woff2
  packages/panels/dist/fonts/inter/inter-greek-wght-normal-AXVTPQD5.woff2
  packages/panels/dist/fonts/inter/inter-latin-ext-wght-normal-GZCIV3NH.woff2
  packages/panels/dist/fonts/inter/inter-latin-wght-normal-OPIJAQLS.woff2
  packages/panels/dist/fonts/inter/inter-vietnamese-wght-normal-TWG5UU7E.woff2
  packages/panels/resources/js/fonts/inter.js
  packages/panels/src/FilamentServiceProvider.php
  packages/panels/src/Panel/Concerns/HasFont.php
  packages/schema/dist/index.js
  packages/support/src/Assets/AssetManager.php
  packages/support/src/Assets/Css.php
  packages/support/src/Assets/Font.php
  packages/support/src/Commands/AssetsCommand.php
  packages/support/src/Facades/FilamentAsset.php
Labels: enhancement

#13297 Update vi translations
  packages/actions/resources/lang/vi/import.php
  packages/forms/resources/lang/vi/components.php
Labels: i18n

#13291 Add docs for setting the current panel in tests
  packages/panels/docs/14-testing.md
Labels: documentation

#13321 Don't lazy-load the GlobalSearch component
  packages/panels/resources/views/components/topbar/index.blade.php
Labels: enhancement

#13328 Broadcasting using the Panel builder - configuration & documentation
  packages/panels/docs/07-notifications.md
  packages/support/config/filament.php
Labels: documentation

#13338 Fix import in docs example
  packages/forms/docs/04-layout/01-getting-started.md
Labels: documentation

#13323 Add page end/start render hooks to simple page
  packages/panels/resources/views/components/page/simple.blade.php
  packages/panels/src/View/PanelsRenderHook.php
  packages/support/docs/06-render-hooks.md
Labels: enhancement

#13375 i18n: better french translations for table filters
  packages/tables/resources/lang/fr/filters/query-builder.php
Labels: i18n

#13377 feature: Custom mono and serif fonts
  packages/panels/dist/theme.css
  packages/panels/resources/views/components/layout/base.blade.php
  packages/panels/src/Facades/Filament.php
  packages/panels/src/FilamentManager.php
  packages/panels/src/Panel/Concerns/HasFont.php
  packages/panels/tailwind.config.preset.js
Labels: enhancement
