Repository filamentphp/filament, pull requests merged in 2024-01, with the labels that each got.

#10590 Fix: standardizes pt_br strings
  packages/panels/resources/lang/pt_BR/resources/pages/view-record.php
Labels: i18n, pending review

#10604 fix: Prevent duplicate TenantSet calls
  packages/panels/src/Facades/Filament.php
  packages/panels/src/FilamentManager.php
  packages/panels/src/Panel/Concerns/HasRoutes.php
Labels: bug

#10554 Fix refreshFormData with Enum
  packages/panels/src/Resources/Pages/EditRecord.php
  packages/panels/src/Resources/Pages/ViewRecord.php
Labels: bug, needs more info

#10614 Fix when linking from a panel with tenancy to one without
  packages/panels/src/Pages/Page.php
Labels: bug

#10598 Add `fi-sidebar-group-button` CSS hook class
  packages/panels/resources/views/components/sidebar/group.blade.php
Labels: chore

#10616 Explain how to join vertical nav items with a bar
  packages/panels/docs/06-navigation.md
Labels: documentation

#10557 Infolists: Add `KeyValueEntry` component
  docs-assets/app/app/Livewire/Infolists/EntriesDemo.php
  docs-assets/app/public/css/filament/filament/app.css
  docs-assets/app/public/js/filament/support/support.js
  docs-assets/screenshots/images/dark/infolists/entries/key-value/simple.jpg
  docs-assets/screenshots/images/light/infolists/entries/key-value/simple.jpg
  docs-assets/screenshots/schema.js
  package-lock.json
  package.json
  packages/infolists/docs/03-entries/01-getting-started.md
  packages/infolists/docs/03-entries/06-key-value.md
  packages/infolists/docs/03-entries/07-repeatable.md
  packages/infolists/docs/03-entries/08-custom.md
  packages/infolists/resources/lang/en/components.php
  packages/infolists/resources/views/components/key-value-entry.blade.php
  packages/infolists/src/Components/KeyValueEntry.php
  packages/panels/dist/theme.css
Labels: enhancement

#10636 fix: Table overflow scroll
  packages/tables/resources/views/components/header-cell.blade.php
Labels: bug

#10628 Update 07-relation-managers.md
  packages/forms/docs/07-advanced.md
  packages/panels/docs/03-resources/07-relation-managers.md
Labels: documentation

#10629 Add readOnly method documentation with security note
  packages/forms/docs/03-fields/02-text-input.md
  packages/forms/docs/03-fields/08-date-time-picker.md
  packages/forms/docs/03-fields/15-textarea.md
Labels: documentation, pending changes

#10639 Corrected link to docs for media library plugin
  packages/spatie-laravel-media-library-plugin/README.md
Labels: documentation

#10653 Update missing translation of the dashboard file to pt_BR.
  packages/panels/resources/lang/pt_BR/pages/dashboard.php
Labels: i18n

#10652 Fix syntax error with modal edit forms
  packages/panels/resources/views/components/page/index.blade.php
Labels: bug

#10680 Fixes installation docs
  packages/spatie-laravel-media-library-plugin/README.md
Labels: documentation

#10668 Updated validation testing documentation for AdminPanel
  packages/admin/docs/10-testing.md
Labels: documentation

#10659 Hide filter indicator bar
  packages/tables/docs/04-filters/06-layout.md
  packages/tables/src/Table/Concerns/HasFilterIndicators.php
Labels: enhancement

#10649 Update table column affix helpers to support Htmlables
  packages/infolists/src/Components/Concerns/CanFormatState.php
  packages/tables/src/Columns/Concerns/CanFormatState.php
Labels: enhancement

#10587 Support tags color in `TagsInput`
  packages/forms/docs/03-fields/14-tags-input.md
  packages/forms/resources/views/components/tags-input.blade.php
  packages/forms/src/Components/TagsInput.php
Labels: enhancement

#10662 Eager load grouped by relations
  packages/tables/src/Concerns/CanGroupRecords.php
  packages/tables/src/Grouping/Group.php
Labels: bug

#10623 Rework toggle buttons
  docs-assets/app/app/Livewire/Forms/FieldsDemo.php
  docs-assets/screenshots/images/dark/forms/fields/radio/button-group.jpg
  docs-assets/screenshots/images/dark/forms/fields/radio/buttons-inline-under-label.jpg
  docs-assets/screenshots/images/dark/forms/fields/radio/buttons.jpg
  docs-assets/screenshots/images/dark/forms/fields/radio/colors.jpg
  docs-assets/screenshots/images/dark/forms/fields/radio/icons.jpg
  docs-assets/screenshots/images/dark/forms/fields/toggle-buttons/boolean.jpg
  docs-assets/screenshots/images/dark/forms/fields/toggle-buttons/colors.jpg
  docs-assets/screenshots/images/dark/forms/fields/toggle-buttons/columns.jpg
  docs-assets/screenshots/images/dark/forms/fields/toggle-buttons/disabled-option.jpg
  docs-assets/screenshots/images/dark/forms/fields/toggle-buttons/grouped.jpg
  docs-assets/screenshots/images/dark/forms/fields/toggle-buttons/icons.jpg
  docs-assets/screenshots/images/dark/forms/fields/toggle-buttons/inline.jpg
  docs-assets/screenshots/images/dark/forms/fields/toggle-buttons/multiple.jpg
  docs-assets/screenshots/images/dark/forms/fields/toggle-buttons/rows.jpg
  docs-assets/screenshots/images/dark/forms/fields/toggle-buttons/simple.jpg
  docs-assets/screenshots/images/light/forms/fields/radio/button-group.jpg
  docs-assets/screenshots/images/light/forms/fields/radio/buttons-inline-under-label.jpg
  docs-assets/screenshots/images/light/forms/fields/radio/buttons.jpg
  docs-assets/screenshots/images/light/forms/fields/radio/colors.jpg
  docs-assets/screenshots/images/light/forms/fields/radio/icons.jpg
  docs-assets/screenshots/images/light/forms/fields/toggle-buttons/boolean.jpg
  docs-assets/screenshots/images/light/forms/fields/toggle-buttons/colors.jpg
  docs-assets/screenshots/images/light/forms/fields/toggle-buttons/columns.jpg
  docs-assets/screenshots/images/light/forms/fields/toggle-buttons/disabled-option.jpg
  docs-assets/screenshots/images/light/forms/fields/toggle-buttons/grouped.jpg
  docs-assets/screenshots/images/light/forms/fields/toggle-buttons/icons.jpg
  docs-assets/screenshots/images/light/forms/fields/toggle-buttons/inline.jpg
  docs-assets/screenshots/images/light/forms/fields/toggle-buttons/multiple.jpg
  docs-assets/screenshots/images/light/forms/fields/toggle-buttons/rows.jpg
  docs-assets/screenshots/images/light/forms/fields/toggle-buttons/simple.jpg
  docs-assets/screenshots/schema.js
  packages/forms/docs/03-fields/01-getting-started.md
  packages/forms/docs/03-fields/07-radio.md
  packages/forms/docs/03-fields/12-repeater.md
  packages/forms/docs/03-fields/18-toggle-buttons.md
  packages/forms/docs/03-fields/19-hidden.md
  packages/forms/docs/03-fields/20-custom.md
  packages/forms/resources/lang/en/components.php
  packages/forms/resources/lang/nl/components.php
  packages/forms/resources/views/components/radio.blade.php
  packages/forms/resources/views/components/toggle-buttons/grouped.blade.php
  packages/forms/resources/views/components/toggle-buttons/index.blade.php
  packages/forms/src/Components/Radio.php
  packages/forms/src/Components/ToggleButtons.php
  packages/support/docs/03-icons.md
Labels: enhancement

#10706 Update file-upload.css
  packages/forms/resources/css/components/file-upload.css
Labels: bug

#10713 fix: Stabilize slideover modal to prevent jitteriness on open
  packages/support/resources/views/components/modal/index.blade.php
Labels: bug

#10714 Docs for relation manager: Add missing "?"
  packages/panels/docs/03-resources/07-relation-managers.md
Labels: bug, documentation

#10728 fix translation
  packages/panels/resources/lang/el/pages/auth/login.php
Labels: i18n

#10729 Add custom class to database-notifications-trigger
  packages/panels/resources/views/components/topbar/database-notifications-trigger.blade.php
Labels: enhancement

#10727 Add filament register event
  packages/panels/src/Events/Auth/Registered.php
  packages/panels/src/Pages/Auth/Register.php
  tests/src/Panels/Auth/RegisterTest.php
Labels: enhancement

#10722 Updated documentation on filters
  packages/tables/docs/04-filters/05-custom.md
Labels: documentation

#10739 Fix `getUrl()` for empty panels
  packages/panels/src/Panel/Concerns/HasRoutes.php
Labels: bug

#10750 Update dashboard documentation to replace `canView` with `canAccess` to determine whether the dashboard is shown.
  packages/panels/docs/05-dashboard.md
Labels: documentation

#10752 Password reset render hooks
  packages/panels/resources/views/pages/auth/password-reset/request-password-reset.blade.php
  packages/panels/resources/views/pages/auth/password-reset/reset-password.blade.php
  packages/support/docs/06-render-hooks.md
Labels: enhancement

#10742 Added ability to customize default panel route slugs
  packages/panels/docs/08-users.md
  packages/panels/docs/10-tenancy.md
  packages/panels/routes/web.php
  packages/panels/src/Panel/Concerns/HasAuth.php
  packages/panels/src/Panel/Concerns/HasTenancy.php
  tests/src/Models/User.php
  tests/src/Panels/Auth/EmailVerification/EmailVerificationPromptTest.php
  tests/src/Panels/Auth/EmailVerification/EmailVerificationTest.php
  tests/src/Panels/Auth/LoginTest.php
  tests/src/Panels/Auth/PasswordReset/RequestPasswordResetTest.php
  tests/src/Panels/Auth/PasswordReset/ResetPasswordTest.php
  tests/src/Panels/Auth/RegisterTest.php
  tests/src/SlugsPanelProvider.php
  tests/src/TestCase.php
Labels: enhancement

#10762 fix: Add more CSV mime types
  packages/actions/src/Concerns/CanImportRecords.php
Labels: bug

#10764 fix: Simple repeater relationship
  packages/forms/src/Components/Concerns/EntanglesStateWithSingularRelationship.php
  packages/forms/src/Components/Repeater.php
  packages/forms/src/Concerns/HasState.php
  packages/panels/src/Events/Auth/Registered.php
Labels: bug

#10777 fix: Actions Blade component
  packages/actions/resources/views/components/actions.blade.php
  packages/forms/resources/views/components/actions.blade.php
  packages/infolists/resources/views/components/actions.blade.php
  packages/panels/resources/views/components/form/actions.blade.php
  packages/panels/resources/views/components/header/index.blade.php
  packages/support/resources/views/components/actions.blade.php
  packages/support/resources/views/components/section/index.blade.php
  packages/support/src/Components/ComponentManager.php
Labels: bug

#10781 Add German translation for text column actions collapse/expand list
  packages/tables/resources/lang/de/table.php
Labels: i18n

#10784 Uzbek language translations added
  packages/actions/resources/lang/uz/associate.php
  packages/actions/resources/lang/uz/attach.php
  packages/actions/resources/lang/uz/create.php
  packages/actions/resources/lang/uz/delete.php
  packages/actions/resources/lang/uz/detach.php
  packages/actions/resources/lang/uz/dissociate.php
  packages/actions/resources/lang/uz/edit.php
  packages/actions/resources/lang/uz/force-delete.php
  packages/actions/resources/lang/uz/group.php
  packages/actions/resources/lang/uz/modal.php
  packages/actions/resources/lang/uz/replicate.php
  packages/actions/resources/lang/uz/restore.php
  packages/actions/resources/lang/uz/view.php
  packages/forms/resources/lang/uz/components.php
  packages/infolists/resources/lang/uz/components.php
  packages/notifications/resources/lang/uz/database.php
  packages/panels/resources/lang/uz/global-search.php
  packages/panels/resources/lang/uz/layout.php
  packages/panels/resources/lang/uz/pages/auth/edit-profile.php
  packages/panels/resources/lang/uz/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/uz/pages/auth/login.php
  packages/panels/resources/lang/uz/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/uz/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/uz/pages/auth/register.php
  packages/panels/resources/lang/uz/pages/dashboard.php
  packages/panels/resources/lang/uz/pages/tenancy/edit-tenant-profile.php
  packages/panels/resources/lang/uz/resources/pages/create-record.php
  packages/panels/resources/lang/uz/resources/pages/edit-record.php
  packages/panels/resources/lang/uz/resources/pages/list-records.php
  packages/panels/resources/lang/uz/resources/pages/view-record.php
  packages/panels/resources/lang/uz/widgets/account-widget.php
  packages/panels/resources/lang/uz/widgets/filament-info-widget.php
  packages/spatie-laravel-settings-plugin/resources/lang/uz/pages/settings-page.php
  packages/spatie-laravel-translatable-plugin/resources/lang/uz/actions.php
  packages/support/resources/lang/uz/components/button.php
  packages/support/resources/lang/uz/components/copyable.php
  packages/support/resources/lang/uz/components/modal.php
  packages/support/resources/lang/uz/components/pagination.php
  packages/tables/resources/lang/uz/filters/query-builder.php
  packages/tables/resources/lang/uz/table.php
Labels: i18n

#10793 feature: Export action
  composer.json
  composer.lock
  docs-assets/app/public/css/filament/filament/app.css
  package-lock.json
  packages/actions/composer.json
  packages/actions/database/migrations/create_exports_table.php
  packages/actions/docs/02-overview.md
  packages/actions/docs/07-prebuilt-actions/08-import.md
  packages/actions/docs/07-prebuilt-actions/09-export.md
  packages/actions/resources/lang/en/export.php
  packages/actions/routes/web.php
  packages/actions/src/ActionsServiceProvider.php
  packages/actions/src/Commands/Aliases/MakeExporterCommand.php
  packages/actions/src/Commands/Concerns/CanGenerateExporterColumns.php
  packages/actions/src/Commands/Concerns/CanGenerateImporterColumns.php
  packages/actions/src/Commands/MakeExporterCommand.php
  packages/actions/src/Concerns/CanExportRecords.php
  packages/actions/src/ExportAction.php
  packages/actions/src/Exports/Concerns/CanFormatState.php
  packages/actions/src/Exports/Downloaders/Contracts/Downloader.php
  packages/actions/src/Exports/Downloaders/CsvDownloader.php
  packages/actions/src/Exports/Downloaders/XlsxDownloader.php
  packages/actions/src/Exports/Enums/DownloadFileFormat.php
  packages/actions/src/Exports/ExportColumn.php
  packages/actions/src/Exports/Exporter.php
  packages/actions/src/Exports/Http/Controllers/DownloadExport.php
  packages/actions/src/Exports/Jobs/CreateXlsxFile.php
  packages/actions/src/Exports/Jobs/ExportCompletion.php
  packages/actions/src/Exports/Jobs/ExportCsv.php
  packages/actions/src/Exports/Jobs/PrepareCsvExport.php
  packages/actions/src/Exports/Models/Export.php
  packages/actions/src/Imports/Importer.php
  packages/actions/src/Imports/Jobs/ImportCsv.php
  packages/actions/src/Imports/Models/Import.php
  packages/actions/stubs/Exporter.stub
  packages/forms/resources/views/components/split.blade.php
  packages/forms/src/Commands/Concerns/CanGenerateForms.php
  packages/forms/src/Components/Split.php
  packages/infolists/resources/views/components/split.blade.php
  packages/infolists/src/Components/Concerns/CanFormatState.php
  packages/infolists/src/Components/Split.php
  packages/panels/dist/theme.css
  packages/support/docs/03-icons.md
  packages/support/src/Concerns/CanAggregateRelatedModels.php
  packages/support/src/Concerns/HasCellState.php
  packages/tables/docs/03-columns/01-getting-started.md
  packages/tables/docs/03-columns/02-text.md
  packages/tables/docs/05-actions.md
  packages/tables/src/Actions/BulkAction.php
  packages/tables/src/Actions/Concerns/InteractsWithRecords.php
  packages/tables/src/Actions/ExportAction.php
  packages/tables/src/Actions/ExportBulkAction.php
  packages/tables/src/Columns/Column.php
  packages/tables/src/Columns/Concerns/CanFormatState.php
  packages/tables/src/Columns/Concerns/HasState.php
  packages/tables/src/Columns/Concerns/InteractsWithTableQuery.php
  packages/tables/src/Commands/Concerns/CanGenerateTables.php
  packages/tables/src/Concerns/HasBulkActions.php
  packages/tables/src/Contracts/HasTable.php
  packages/tables/src/Table/Concerns/HasBulkActions.php
Labels: enhancement

#10794 feature: Filter layout
  packages/tables/docs/04-filters/06-layout.md
  packages/tables/src/Concerns/HasFilters.php
  packages/tables/src/Table/Concerns/HasFilters.php
Labels: enhancement

#10796 feature: Form component action testing
  packages/actions/.stubs.php
  packages/forms/.stubs.php
  packages/forms/docs/09-testing.md
  packages/forms/src/FormsServiceProvider.php
  packages/forms/src/Testing/TestsComponentActions.php
  packages/tables/.stubs.php
  tests/resources/views/forms/fixtures/actions.blade.php
  tests/src/Actions/ActionTest.php
  tests/src/Actions/Fixtures/Pages/Actions.php
  tests/src/Forms/ActionTest.php
  tests/src/Forms/Fixtures/Actions.php
  tests/src/Tables/ActionTest.php
  tests/src/Tables/BulkActionTest.php
  tests/src/Tables/Fixtures/PostsTable.php
Labels: enhancement

#10797 feature: Infolist action testing
  packages/infolists/.stubs.php
  packages/infolists/docs/08-testing.md
  packages/infolists/src/InfolistsServiceProvider.php
  packages/infolists/src/Testing/TestsActions.php
  tests/resources/views/infolists/fixtures/actions.blade.php
  tests/src/Infolists/ActionTest.php
  tests/src/Infolists/Fixtures/Actions.php
Labels: enhancement

#10795 Addition of 'whereCustomProperties' to Spatie media library file upload
  packages/spatie-laravel-media-library-plugin/README.md
  packages/spatie-laravel-media-library-plugin/src/Forms/Components/SpatieMediaLibraryFileUpload.php
Labels: enhancement

#10799 Add panel css selector
  packages/panels/resources/views/components/layout/base.blade.php
  packages/panels/src/FilamentManager.php
Labels: enhancement

#10804 fix: Do not save field relationships when components are disabled
  packages/forms/src/Components/Concerns/BelongsToModel.php
  packages/forms/src/Concerns/BelongsToModel.php
Labels: bug

#10805 fix: afterStateUpdated() not executing for batched requests
  packages/forms/src/Components/Concerns/HasState.php
  tests/src/Forms/StateTest.php
Labels: bug

#10823 Add missing french translation
  packages/tables/resources/lang/fr/table.php
Labels: i18n

#10821 Fix export download links when in spa mode
  packages/actions/src/Exports/Jobs/ExportCompletion.php
Labels: bug

#10818 Update 09-export.md
  packages/actions/docs/07-prebuilt-actions/09-export.md
Labels: documentation

#10829 Add spanish translations for v3.2
  packages/actions/resources/lang/es/export.php
  packages/forms/resources/lang/es/components.php
  packages/infolists/resources/lang/es/components.php
  packages/tables/resources/lang/es/table.php
Labels: i18n

#10828 Bugfix; Uncaught TypeError scrollTo
  packages/panels/resources/views/components/layout/base.blade.php
Labels: bug

#10839 Update European Portuguese translation
  packages/actions/resources/lang/pt_PT/export.php
  packages/forms/resources/lang/pt_PT/components.php
  packages/infolists/resources/lang/pt_PT/components.php
  packages/tables/resources/lang/pt_PT/table.php
Labels: i18n

#10841 feat: add greek notification translations
  packages/notifications/resources/lang/el/database.php
Labels: i18n

#10843 Add Greek translation for tables
  packages/tables/resources/lang/el/filters/query-builder.php
  packages/tables/resources/lang/el/tables.php
Labels: i18n

#10850 Update `pt_BR` translations
  packages/forms/resources/lang/pt_BR/components.php
  packages/forms/resources/lang/pt_BR/validation.php
Labels: i18n

#10846 Fix export action example in docs
  packages/actions/docs/07-prebuilt-actions/09-export.md
Labels: documentation

#10858 Prevent white icon when button is "outlined".
  packages/support/resources/views/components/button/index.blade.php
Labels: bug, ui

#10876 Fixed bug in PrepareCsvExport for models with custom primary keys
  packages/actions/src/Exports/Jobs/PrepareCsvExport.php
Labels: bug

#10884 Add extraBodyAttributes for pages
  packages/panels/resources/views/components/layout/base.blade.php
  packages/panels/src/Pages/BasePage.php
Labels: enhancement

#10890 Fix: Ensure relationship existence before parsing relation value
  packages/spatie-laravel-media-library-plugin/src/Infolists/Components/SpatieMediaLibraryImageEntry.php
Labels: bug

#10899 Fix exporting relationship values
  packages/actions/src/Concerns/CanExportRecords.php
Labels: bug

#10901 fix: Remove deferred filters
  packages/tables/src/Concerns/HasFilters.php
Labels: bug

#10847 fix(exports) update prepare csv job to account for order by
  packages/actions/src/Exports/Jobs/PrepareCsvExport.php
Labels: bug

#10905 Added italian translation for export.php
  packages/actions/resources/lang/it/export.php
Labels: i18n

#10877 Import Unicode character fix
  packages/actions/src/Concerns/CanImportRecords.php
  packages/actions/src/Imports/Jobs/ImportCsv.php
Labels: bug

#10912 fix: components can be excluded from state dehydration if their parent component is
  packages/forms/src/Components/Concerns/HasState.php
  packages/forms/src/Concerns/HasState.php
  tests/src/Forms/StateTest.php
Labels: bug

#10911 CSV export formatted state
  packages/actions/src/Exports/Concerns/CanFormatState.php
  packages/actions/src/Exports/Exporter.php
Labels: bug

#10908 Update finnish translation
  packages/actions/resources/lang/fi/export.php
  packages/forms/resources/lang/fi/components.php
  packages/infolists/resources/lang/fi/components.php
  packages/tables/resources/lang/fi/table.php
Labels: i18n

#10913 fix: configureUsing() Octane
  packages/support/src/Components/ComponentManager.php
  packages/support/src/Concerns/Configurable.php
Labels: bug

#10918 i18n: Added missing danish translations
  packages/actions/resources/lang/da/associate.php
  packages/actions/resources/lang/da/attach.php
  packages/actions/resources/lang/da/create.php
  packages/actions/resources/lang/da/delete.php
  packages/actions/resources/lang/da/detach.php
  packages/actions/resources/lang/da/dissociate.php
  packages/actions/resources/lang/da/edit.php
  packages/actions/resources/lang/da/export.php
  packages/actions/resources/lang/da/force-delete.php
  packages/actions/resources/lang/da/group.php
  packages/actions/resources/lang/da/import.php
  packages/actions/resources/lang/da/modal.php
  packages/actions/resources/lang/da/replicate.php
  packages/actions/resources/lang/da/restore.php
  packages/actions/resources/lang/da/view.php
  packages/forms/resources/lang/da/components.php
  packages/forms/resources/lang/da/validation.php
  packages/infolists/resources/lang/da/components.php
  packages/panels/resources/lang/da/pages/auth/edit-profile.php
  packages/panels/resources/lang/da/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/da/pages/auth/login.php
  packages/panels/resources/lang/da/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/da/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/da/pages/auth/register.php
  packages/panels/resources/lang/da/pages/dashboard.php
  packages/panels/resources/lang/da/pages/tenancy/edit-tenant-profile.php
  packages/tables/resources/lang/da/filters/query-builder.php
  packages/tables/resources/lang/da/table.php
Labels: i18n

#10917 [doc] fix function name `middleware` instead of `tenantMiddleware`
  packages/panels/docs/09-configuration.md
Labels: documentation

#10922 Update Indonesian translations
  packages/actions/resources/lang/id/export.php
  packages/actions/resources/lang/id/import.php
  packages/forms/resources/lang/id/components.php
  packages/forms/resources/lang/id/validation.php
  packages/panels/resources/lang/id/pages/dashboard.php
  packages/tables/resources/lang/id/filters/query-builder.php
  packages/tables/resources/lang/id/table.php
Labels: i18n

#10869 i18: Uzbek language translations changed
  packages/actions/resources/lang/uz/associate.php
  packages/actions/resources/lang/uz/attach.php
  packages/actions/resources/lang/uz/create.php
  packages/actions/resources/lang/uz/delete.php
  packages/actions/resources/lang/uz/detach.php
  packages/actions/resources/lang/uz/dissociate.php
  packages/actions/resources/lang/uz/edit.php
  packages/actions/resources/lang/uz/force-delete.php
  packages/actions/resources/lang/uz/modal.php
  packages/actions/resources/lang/uz/replicate.php
  packages/actions/resources/lang/uz/restore.php
  packages/actions/resources/lang/uz/view.php
  packages/forms/resources/lang/uz/components.php
  packages/forms/resources/lang/uz/validation.php
  packages/infolists/resources/lang/uz/components.php
  packages/panels/resources/lang/uz/pages/auth/edit-profile.php
  packages/panels/resources/lang/uz/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/uz/pages/auth/login.php
  packages/panels/resources/lang/uz/pages/auth/register.php
  packages/panels/resources/lang/uz/pages/dashboard.php
  packages/panels/resources/lang/uz/resources/pages/create-record.php
  packages/panels/resources/lang/uz/resources/pages/edit-record.php
  packages/panels/resources/lang/uz/resources/pages/view-record.php
  packages/support/resources/lang/uz/components/pagination.php
  packages/tables/resources/lang/uz/table.php
Labels: i18n

#10820 add `extraAttributes` in Navigation Group
  packages/panels/docs/06-navigation.md
  packages/panels/resources/views/components/page/sub-navigation/sidebar.blade.php
  packages/panels/resources/views/components/sidebar/index.blade.php
  packages/panels/resources/views/components/topbar/index.blade.php
  packages/panels/src/Navigation/NavigationGroup.php
  packages/support/src/Concerns/HasExtraSidebarAttributes.php
  packages/support/src/Concerns/HasExtraTopbarAttributes.php
Labels: enhancement

#10873 Add "drag end" option to color picker
  docs-assets/app/public/js/filament/forms/components/color-picker.js
  packages/forms/dist/components/color-picker.js
  packages/forms/resources/js/components/color-picker.js
  packages/forms/resources/views/components/color-picker.blade.php
Labels: enhancement

#10875 Support Alpine Click Handler via modifier
  packages/actions/src/StaticAction.php
  packages/forms/src/Components/TextInput/Actions/HidePasswordAction.php
  packages/forms/src/Components/TextInput/Actions/ShowPasswordAction.php
  packages/notifications/src/Actions/Action.php
  packages/tables/src/Actions/Action.php
  packages/tables/src/Actions/BulkAction.php
Labels: enhancement

#10935 Add `km` translation
  packages/actions/resources/lang/km/export.php
  packages/actions/resources/lang/km/import.php
  packages/forms/resources/lang/km/components.php
  packages/forms/resources/lang/km/validation.php
  packages/infolists/resources/lang/km/components.php
  packages/panels/resources/lang/km/pages/dashboard.php
  packages/panels/resources/lang/km/pages/tenancy/edit-tenant-profile.php
  packages/tables/resources/lang/km/filters/query-builder.php
  packages/tables/resources/lang/km/table.php
Labels: i18n

#10928 Update 09-export.md
  packages/actions/docs/07-prebuilt-actions/09-export.md
Labels: documentation

#10934 fix collapsing groups on sub navigation pages
  packages/panels/resources/views/components/page/sub-navigation/sidebar.blade.php
  packages/panels/resources/views/components/sidebar/group.blade.php
Labels: bug

#10941 This change prevents the stretching collapsed elements
  packages/forms/resources/views/components/repeater/index.blade.php
Labels: bug

#10946 fix: Livewire component key
  packages/forms/docs/07-advanced.md
  packages/forms/resources/views/components/livewire.blade.php
  packages/infolists/docs/06-advanced.md
  packages/infolists/resources/views/components/livewire.blade.php
Labels: bug

#10947 fix: configureUsing() in boot() on Octane
  packages/support/src/Components/ComponentManager.php
  packages/support/src/Components/Contracts/ScopedComponentManager.php
  packages/support/src/Concerns/Configurable.php
  packages/support/src/SupportServiceProvider.php
Labels: bug

#10929 Allow markAsRequired() to be used independently of required() to denote a required field.
  packages/forms/docs/03-fields/01-getting-started.md
  packages/forms/resources/views/components/field-wrapper/label.blade.php
Labels: bug

#10950 fix search case sensitive with json column in spatie translatable
  packages/spatie-laravel-translatable-plugin/src/SpatieLaravelTranslatableContentDriver.php
  packages/support/src/helpers.php
  packages/tables/src/Columns/Concerns/InteractsWithTableQuery.php
Labels: bug

#10951 fix: Tags input state lost
  packages/forms/resources/views/components/tags-input.blade.php
Labels: bug

#10952 fix: Table root undefined
  docs-assets/app/public/js/filament/tables/components/table.js
  packages/tables/dist/components/table.js
  packages/tables/resources/js/components/table.js
Labels: bug

#10954 feature: Plugin assets
  packages/panels/docs/09-configuration.md
  packages/panels/src/Panel.php
  packages/panels/src/Panel/Concerns/HasAssets.php
  packages/support/docs/08-plugins/02-build-a-panel-plugin.md
Labels: enhancement

#10961 Bugfix panel assets
  packages/panels/src/Panel/Concerns/HasAssets.php
Labels: bug

#10957 fix: isMarkedAsRequired should be false by default
  packages/forms/resources/views/components/field-wrapper/index.blade.php
  packages/forms/resources/views/components/field-wrapper/label.blade.php
  packages/forms/src/Components/Concerns/CanBeMarkedAsRequired.php
Labels: bug

#10958 Fix: Update 18-toggle-buttons.md
  packages/forms/docs/03-fields/18-toggle-buttons.md
Labels: documentation

#10963 feature: Choose export formats
  packages/actions/docs/07-prebuilt-actions/09-export.md
  packages/actions/src/Concerns/CanExportRecords.php
  packages/actions/src/Concerns/CanImportRecords.php
  packages/actions/src/Exports/Enums/DownloadFileFormat.php
  packages/actions/src/Exports/Enums/ExportFormat.php
  packages/actions/src/Exports/Exporter.php
  packages/actions/src/Exports/Http/Controllers/DownloadExport.php
  packages/actions/src/Exports/Jobs/ExportCompletion.php
Labels: enhancement

#10965 fix: File upload size validation
  packages/forms/resources/views/components/file-upload.blade.php
Labels: bug

#10969 fix: Nested modal scroll locking
  docs-assets/app/public/js/filament/support/support.js
  package-lock.json
  package.json
  packages/support/dist/index.js
  packages/support/resources/js/index.js
  packages/support/resources/views/components/modal/index.blade.php
Labels: bug

#10970 Bugfix: Check if resource is scoped to tenant when using spatie/laravel-translatable plugin
  packages/spatie-laravel-translatable-plugin/src/Resources/Pages/CreateRecord/Concerns/Translatable.php
Labels: bug

#10978 Adding missing callables to grouped ToggleButtons
  packages/forms/resources/views/components/toggle-buttons/grouped.blade.php
Labels: bug

#10982 fix: Markdown Editor initialization in modal
  packages/forms/resources/views/components/markdown-editor.blade.php
Labels: bug

#10987 fix: Manage related records form model
  packages/panels/src/Resources/Pages/ManageRelatedRecords.php
Labels: bug

#10988 fix: Max files
  composer.lock
  docs-assets/app/public/js/filament/forms/components/file-upload.js
  packages/forms/dist/components/file-upload.js
  packages/forms/resources/js/components/file-upload.js
  packages/forms/resources/views/components/file-upload.blade.php
Labels: bug

#11001 Fix docs dropdown changing color
  packages/support/docs/09-blade-components/02-dropdown.md
Labels: documentation

#10990 Unpin fixed league/csv version
  composer.json
Labels: chore

#11023 Hide Microsoft Edge password reveal control
  packages/forms/resources/views/components/text-input.blade.php
  packages/panels/dist/theme.css
Labels: bug, ui

#11025 Dont render input wrapper focus state when action is focused
  packages/actions/resources/views/components/action.blade.php
  packages/panels/dist/theme.css
  packages/support/resources/views/components/input/wrapper.blade.php
Labels: bug, ui

#11024 Mark current top navigation dropdown item as active
  packages/panels/resources/views/components/topbar/index.blade.php
Labels: bug

#11035 fix uk translations for form in components.php
  packages/forms/resources/lang/uk/components.php
Labels: i18n

#11053 Fix modal height on mobile
  packages/panels/dist/theme.css
  packages/support/resources/views/components/modal/index.blade.php
Labels: bug, ui, high priority

#11074 Fix/romanian translations
  packages/forms/resources/lang/ro/components.php
  packages/forms/resources/lang/ro/validation.php
Labels: i18n

#11069 Fix Italian translation for filters trashed label in table.php
  packages/tables/resources/lang/it/table.php
Labels: i18n

#11045 Add Greek actions translations
  packages/actions/resources/lang/el/associate.php
  packages/actions/resources/lang/el/attach.php
  packages/actions/resources/lang/el/create.php
  packages/actions/resources/lang/el/delete.php
  packages/actions/resources/lang/el/detach.php
  packages/actions/resources/lang/el/dissociate.php
  packages/actions/resources/lang/el/edit.php
  packages/actions/resources/lang/el/export.php
  packages/actions/resources/lang/el/force-delete.php
  packages/actions/resources/lang/el/group.php
  packages/actions/resources/lang/el/import.php
  packages/actions/resources/lang/el/modal.php
  packages/actions/resources/lang/el/replicate.php
  packages/actions/resources/lang/el/restore.php
  packages/actions/resources/lang/el/view.php
Labels: i18n

#11040 Add `ar` translations for export action
  packages/actions/resources/lang/ar/export.php
Labels: i18n

#11037 Forms/MarkdownEditor: Fix editing bug when updating state via server
  packages/forms/dist/components/markdown-editor.js
  packages/forms/resources/js/components/markdown-editor.js
Labels: bug

#11070 Adding custom tooltips to navigation badges
  packages/panels/docs/06-navigation.md
  packages/panels/resources/views/components/sidebar/group.blade.php
  packages/panels/resources/views/components/sidebar/item.blade.php
  packages/panels/resources/views/components/topbar/index.blade.php
  packages/panels/resources/views/components/topbar/item.blade.php
  packages/panels/src/Navigation/NavigationItem.php
  packages/panels/src/Resources/Resource.php
  packages/support/resources/views/components/dropdown/list/item.blade.php
Labels: enhancement

#11076 Enabling Badge Color for Relational Managers
  packages/panels/docs/03-resources/07-relation-managers.md
  packages/panels/resources/views/components/resources/relation-managers.blade.php
  packages/panels/src/Resources/RelationManagers/RelationGroup.php
  packages/panels/src/Resources/RelationManagers/RelationManager.php
  packages/support/resources/views/components/tabs/item.blade.php
Labels: enhancement

#11091 Fix: legacy isUploadingFile
  packages/support/resources/views/components/button/index.blade.php
Labels: bug

#11101 Update Catalan translations
  packages/actions/resources/lang/ca/export.php
Labels: i18n

#11094 Fix: do not lazy load brand logo
  packages/panels/resources/views/components/logo.blade.php
Labels: bug

#11102 Update CanFormatState.php using consistent return values with null de…
  packages/tables/src/Columns/Summarizers/Concerns/CanFormatState.php
Labels: bug

#11106 fix: Select all current page
  packages/tables/src/Concerns/HasBulkActions.php
Labels: bug

#11108 fix: Custom export order
  packages/actions/src/Exports/Jobs/PrepareCsvExport.php
Labels: bug

#11086 Explain the naming convention and function calls for Actions in LW Co…
  packages/actions/docs/06-adding-an-action-to-a-livewire-component.md
Labels: documentation

#11092 Adds the globalSearchDebounce method.
  packages/panels/docs/03-resources/08-global-search.md
  packages/panels/resources/views/components/global-search/field.blade.php
  packages/panels/src/Facades/Filament.php
  packages/panels/src/FilamentManager.php
  packages/panels/src/Panel/Concerns/HasGlobalSearch.php
Labels: enhancement

#11100 feat: allow to prevent next step on wizard component
  packages/forms/docs/04-layout/05-wizard.md
  packages/forms/src/Components/Wizard.php
Labels: enhancement

#11113 Fixing BelongsToThrough Error
  packages/forms/src/Components/Select.php
Labels: bug

#11117 i18n: missing translation of the query-builder file to pt_BR.
  packages/tables/resources/lang/pt_BR/filters/query-builder.php
Labels: i18n

#11119 feature: Scope render hooks on auth pages
  packages/panels/resources/views/components/layout/base.blade.php
  packages/panels/resources/views/components/layout/index.blade.php
  packages/panels/resources/views/components/layout/simple.blade.php
  packages/panels/resources/views/pages/auth/login.blade.php
  packages/panels/resources/views/pages/auth/password-reset/request-password-reset.blade.php
  packages/panels/resources/views/pages/auth/password-reset/reset-password.blade.php
  packages/panels/resources/views/pages/auth/register.blade.php
Labels: enhancement

#11121 Allow profile page to have sidebar
  packages/panels/docs/08-users.md
  packages/panels/resources/views/pages/auth/edit-profile.blade.php
  packages/panels/src/Facades/Filament.php
  packages/panels/src/FilamentManager.php
  packages/panels/src/Pages/Auth/EditProfile.php
  packages/panels/src/Pages/BasePage.php
  packages/panels/src/Pages/Page.php
  packages/panels/src/Panel/Concerns/HasAuth.php
Labels: enhancement

#11120 Graceful handling of deleted export dirs
  packages/actions/src/Exports/Downloaders/CsvDownloader.php
  packages/actions/src/Exports/Downloaders/XlsxDownloader.php
Labels: bug

#11124 Fix - Close results container in spa mode
  packages/panels/resources/views/components/global-search/results-container.blade.php
  packages/panels/resources/views/pages/auth/edit-profile.blade.php
  packages/panels/src/Pages/Auth/EditProfile.php
Labels: bug

#11134 Fix text input inline label alignment
  packages/forms/resources/views/components/text-input.blade.php
Labels: bug, ui

#11129 fix: Handle Empty State for KeyValueEntry
  packages/infolists/docs/03-entries/06-key-value.md
  packages/infolists/resources/lang/ca/components.php
  packages/infolists/resources/lang/da/components.php
  packages/infolists/resources/lang/en/components.php
  packages/infolists/resources/lang/es/components.php
  packages/infolists/resources/lang/km/components.php
  packages/infolists/resources/lang/nl/components.php
  packages/infolists/resources/lang/pt_PT/components.php
  packages/infolists/resources/lang/uz/components.php
  packages/infolists/resources/views/components/key-value-entry.blade.php
  packages/infolists/src/Components/KeyValueEntry.php
Labels: enhancement

#11122 Spatie media relationship fixes
  packages/actions/src/Exports/ExportColumn.php
  packages/spatie-laravel-media-library-plugin/src/Infolists/Components/SpatieMediaLibraryImageEntry.php
  packages/spatie-laravel-media-library-plugin/src/Tables/Columns/SpatieMediaLibraryImageColumn.php
  packages/spatie-laravel-tags-plugin/src/Infolists/Components/SpatieTagsEntry.php
  packages/spatie-laravel-tags-plugin/src/Tables/Columns/SpatieTagsColumn.php
  packages/support/src/Concerns/HasCellState.php
  packages/tables/src/Columns/Concerns/InteractsWithTableQuery.php
  packages/tables/src/Columns/Summarizers/Summarizer.php
Labels: bug

#11097 Fix vertical centering of logo
  packages/panels/resources/views/components/logo.blade.php
Labels: bug, ui

#11150 Fix Italian translation for filters in query builder
  packages/tables/resources/lang/it/filters/query-builder.php
Labels: i18n

#11156 Updated the hungarian translations
  packages/actions/resources/lang/hu/export.php
  packages/forms/resources/lang/hu/components.php
  packages/infolists/resources/lang/hu/components.php
  packages/tables/resources/lang/hu/table.php
Labels: i18n

#11158 Add ru/ua translate import/export action
  packages/actions/resources/lang/ru/export.php
  packages/actions/resources/lang/ru/import.php
  packages/actions/resources/lang/uk/export.php
  packages/actions/resources/lang/uk/import.php
Labels: i18n

#11159 Ru/ua infolist and forms update language
  packages/forms/resources/lang/ru/components.php
  packages/forms/resources/lang/ru/validation.php
  packages/forms/resources/lang/uk/components.php
  packages/forms/resources/lang/uk/validation.php
  packages/infolists/resources/lang/ru/components.php
  packages/infolists/resources/lang/uk/components.php
Labels: i18n

#11067 feat: Allow columns to be omitted from exports by default.
  packages/actions/docs/07-prebuilt-actions/09-export.md
  packages/actions/src/Concerns/CanExportRecords.php
  packages/actions/src/Exports/ExportColumn.php
Labels: enhancement

#11154 feat: tags-input-affixes
  packages/forms/resources/views/components/tags-input.blade.php
  packages/forms/src/Components/TagsInput.php
Labels: enhancement

#11178 Prevent EOF warnings
  packages/forms/resources/lang/ca/components.php
Labels: bug

#11177 Remove reset-password.php text from reset-password.php
  packages/panels/resources/lang/uk/pages/auth/password-reset/reset-password.php
Labels: bug

#11180 Fix dissociate for Bosnian
  packages/actions/resources/lang/bs/dissociate.php
Labels: i18n

#11181 Streamlined zn_CH translations
  packages/actions/resources/lang/zh_CN/import.php
Labels: i18n

#11192 feature: Customize import/export auth
  packages/actions/docs/07-prebuilt-actions/08-import.md
  packages/actions/docs/07-prebuilt-actions/09-export.md
  packages/actions/src/Exports/Http/Controllers/DownloadExport.php
  packages/actions/src/Imports/Http/Controllers/DownloadImportFailureCsv.php
Labels: enhancement

#11182 Streamlined french components
  packages/forms/resources/lang/fr/components.php
Labels: i18n

#11183 Streamline mn components.php
  packages/forms/resources/lang/mn/components.php
Labels: enhancement

#11185 Update edit-profile.php
  packages/panels/resources/lang/sq/pages/auth/edit-profile.php
Labels: i18n

#11186 Update edit-record.php
  packages/panels/resources/lang/zh_CN/resources/pages/edit-record.php
Labels: i18n
