Repository filamentphp/filament, pull requests merged in 2025-08, with the labels that each got.

#17144 Update deprecated method in 02-action.md
  docs/12-components/02-action.md
Labels: documentation

#17155 fix: Enum validation while testing
  packages/forms/src/Components/Concerns/CanBeValidated.php
  packages/schemas/src/Components/Concerns/HasState.php
Labels: bug

#17156 fix: Flex layout component JS
  packages/panels/dist/theme.css
  packages/schemas/resources/css/components/flex.css
  packages/schemas/resources/views/components/flex.blade.php
  packages/schemas/src/Schema.php
Labels: bug

#17134 Ignore current record in unique rule during replicate operation
  packages/actions/src/ReplicateAction.php
Labels: bug

#17157 [BREAKING CHANGE IN BETA]: Require Phiki to be installed manually
  docs-assets/app/composer.json
  docs-assets/app/composer.lock
  packages/infolists/composer.json
  packages/infolists/docs/06-code-entry.md
Labels: chore

#17163 fix: closure evaluation of `hintActions()`
  packages/forms/src/Components/Concerns/HasHint.php
  packages/infolists/src/Components/Concerns/HasHint.php
Labels: bug

#17112 Allow direct editing per type in morphtoselect
  packages/forms/docs/03-select.md
  packages/forms/src/Components/MorphToSelect.php
  packages/forms/src/Components/MorphToSelect/Type.php
Labels: enhancement

#17158 fix: default state for simple `Repeater` fields
  packages/forms/src/Components/Repeater.php
  tests/src/Forms/Components/RepeaterTest.php
Labels: bug

#17160 V4 add filter indicator renderhook
  docs/09-advanced/01-render-hooks.md
  packages/support/src/View/ViewManager.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/View/TablesRenderHook.php
  tests/src/Support/RenderHooksTest.php
Labels: enhancement

#17172 Consolidate table sorting into one property
  packages/panels/src/Pages/Concerns/ExposesTableToWidgets.php
  packages/panels/src/Resources/Pages/ListRecords.php
  packages/panels/src/Resources/Pages/ManageRelatedRecords.php
  packages/panels/src/Widgets/Concerns/InteractsWithPageTable.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Concerns/CanSortRecords.php
  packages/tables/src/Concerns/InteractsWithTable.php
Labels: chore

#17181 feature: Reorder tables in descending order
  packages/tables/docs/01-overview.md
  packages/tables/src/Concerns/CanReorderRecords.php
  packages/tables/src/Concerns/CanSortRecords.php
  packages/tables/src/Table/Concerns/CanReorderRecords.php
Labels: enhancement

#17182 fix: `postToUrl()` on all action types
  packages/actions/src/Action.php
  packages/support/src/View/Concerns/CanGenerateBadgeHtml.php
  packages/support/src/View/Concerns/CanGenerateButtonHtml.php
  packages/support/src/View/Concerns/CanGenerateDropdownItemHtml.php
  packages/support/src/View/Concerns/CanGenerateIconButtonHtml.php
  packages/support/src/View/Concerns/CanGenerateLinkHtml.php
Labels: bug

#17185 fix: Restore tab from query string
  packages/schemas/dist/components/tabs.js
  packages/schemas/resources/js/components/tabs.js
Labels: bug

#17186 fix: Allow top navigation items to wrap
  packages/panels/dist/theme.css
  packages/panels/resources/css/components/topbar.css
Labels: bug

#17194 [v4] Docs: Widget filters
  packages/infolists/docs/06-code-entry.md
  packages/widgets/docs/03-charts.md
Labels: documentation

#17196 fix: EditAction gray color in ActionGroup
  packages/tables/src/Actions/EditAction.php
Labels: bug

#17214 [4.x] Avoid loop when using EditAction in EditRecord page
  packages/panels/src/Resources/Pages/Page.php
Labels: bug

#17215 add missing Dutch translation: request-password-reset.notifications.sent.body
  packages/panels/resources/lang/nl/pages/auth/password-reset/request-password-reset.php
Labels: i18n

#17211 [4.x] Adds `copyable` to TextInput with CopyAction.
  packages/forms/docs/02-text-input.md
  packages/forms/resources/lang/en/components.php
  packages/forms/src/Components/TextInput.php
  packages/forms/src/Components/TextInput/Actions/CopyAction.php
  packages/forms/src/View/FormsIconAlias.php
Labels: enhancement

#17230 Fix render HTML on option label in modal table select
  packages/forms/src/Components/ModalTableSelect.php
Labels: bug

#17232 CKB language correction
  packages/panels/resources/lang/ckb/auth/http/controllers/block-email-change-verification-controller.php
  packages/panels/resources/lang/ckb/auth/http/controllers/email-change-verification-controller.php
  packages/panels/resources/lang/ckb/auth/multi-factor/app/actions/disable.php
  packages/panels/resources/lang/ckb/auth/multi-factor/app/actions/regenerate-recovery-codes.php
  packages/panels/resources/lang/ckb/auth/multi-factor/app/actions/set-up.php
  packages/panels/resources/lang/ckb/auth/multi-factor/app/provider.php
  packages/panels/resources/lang/ckb/auth/multi-factor/email/actions/disable.php
  packages/panels/resources/lang/ckb/auth/multi-factor/email/actions/set-up.php
  packages/panels/resources/lang/ckb/auth/multi-factor/email/notifications/verify-email-authentication.php
  packages/panels/resources/lang/ckb/auth/multi-factor/email/provider.php
  packages/panels/resources/lang/ckb/auth/multi-factor/pages/set-up-required-multi-factor-authentication.php
  packages/panels/resources/lang/ckb/auth/multi-factor/recovery-codes-modal-content.php
  packages/panels/resources/lang/ckb/auth/notifications/notice-of-email-change-request.php
  packages/panels/resources/lang/ckb/auth/pages/edit-profile.php
  packages/panels/resources/lang/ckb/auth/pages/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/ckb/auth/pages/login.php
  packages/panels/resources/lang/ckb/auth/pages/password-reset/request-password-reset.php
  packages/panels/resources/lang/ckb/auth/pages/password-reset/reset-password.php
  packages/panels/resources/lang/ckb/auth/pages/register.php
  packages/panels/resources/lang/ckb/resources/pages/create-record.php
  packages/panels/resources/lang/ckb/resources/pages/edit-record.php
  packages/spatie-laravel-settings-plugin/resources/lang/ckb/pages/settings-page.php
  packages/support/resources/lang/ckb/components/button.php
  packages/support/resources/lang/ckb/components/copyable.php
  packages/support/resources/lang/ckb/components/pagination.php
  packages/tables/resources/lang/ckb/table.php
Labels: i18n

#17223 Add false to boolean icon allowing default icon to be disabled
  packages/infolists/src/Components/IconEntry.php
  packages/tables/src/Columns/IconColumn.php
Labels: enhancement

#17241 Update Spanish translations
  packages/forms/resources/lang/es/components.php
  packages/tables/resources/lang/es/table.php
Labels: i18n

#17244 chore(i18n): add missing translation
  packages/panels/resources/lang/id/pages/auth/password-reset/request-password-reset.php
Labels: i18n

#17243 fix hint label color in dark mode
  packages/forms/resources/views/components/field-wrapper/hint.blade.php
  packages/infolists/resources/views/components/entry-wrapper/hint.blade.php
Labels: a11y

#17248 Add missing SK & CZ translations
  packages/forms/resources/lang/cs/components.php
  packages/forms/resources/lang/sk/components.php
  packages/panels/resources/lang/cs/resources/pages/edit-record.php
  packages/panels/resources/lang/cs/resources/pages/manage-related-records.php
  packages/panels/resources/lang/cs/resources/pages/view-record.php
  packages/panels/resources/lang/sk/resources/pages/edit-record.php
  packages/panels/resources/lang/sk/resources/pages/manage-related-records.php
  packages/panels/resources/lang/sk/resources/pages/view-record.php
  packages/tables/resources/lang/cs/table.php
  packages/tables/resources/lang/sk/table.php
Labels: i18n

#17251 Fix dropdowns inside of modals
  packages/panels/dist/theme.css
  packages/support/resources/css/components/modal.css
  packages/support/resources/views/components/modal/index.blade.php
Labels: bug

#17258 Update change
  packages/panels/resources/lang/de/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/id/pages/auth/password-reset/request-password-reset.php
Labels: chore

#17263 Update finnish translation
  packages/actions/resources/lang/fi/delete.php
  packages/actions/resources/lang/fi/export.php
  packages/actions/resources/lang/fi/force-delete.php
  packages/actions/resources/lang/fi/notifications.php
  packages/actions/resources/lang/fi/restore.php
  packages/forms/resources/lang/fi/components.php
  packages/panels/resources/lang/fi/auth/http/controllers/block-email-change-verification-controller.php
  packages/panels/resources/lang/fi/auth/http/controllers/email-change-verification-controller.php
  packages/panels/resources/lang/fi/auth/multi-factor/app/actions/disable.php
  packages/panels/resources/lang/fi/auth/multi-factor/app/actions/regenerate-recovery-codes.php
  packages/panels/resources/lang/fi/auth/multi-factor/app/actions/set-up.php
  packages/panels/resources/lang/fi/auth/multi-factor/app/provider.php
  packages/panels/resources/lang/fi/auth/multi-factor/email/actions/disable.php
  packages/panels/resources/lang/fi/auth/multi-factor/email/actions/set-up.php
  packages/panels/resources/lang/fi/auth/multi-factor/email/notifications/verify-email-authentication.php
  packages/panels/resources/lang/fi/auth/multi-factor/email/provider.php
  packages/panels/resources/lang/fi/auth/multi-factor/pages/set-up-required-multi-factor-authentication.php
  packages/panels/resources/lang/fi/auth/multi-factor/recovery-codes-modal-content.php
  packages/panels/resources/lang/fi/auth/notifications/notice-of-email-change-request.php
  packages/panels/resources/lang/fi/auth/pages/edit-profile.php
  packages/panels/resources/lang/fi/auth/pages/login.php
  packages/panels/resources/lang/fi/error-notifications.php
  packages/panels/resources/lang/fi/resources/pages/edit-record.php
  packages/panels/resources/lang/fi/resources/pages/manage-related-records.php
  packages/panels/resources/lang/fi/resources/pages/view-record.php
  packages/tables/resources/lang/fi/table.php
Labels: i18n

#17267 fix: Nullable intersection types
  packages/schemas/src/Concerns/BelongsToLivewire.php
  packages/schemas/src/Schema.php
Labels: bug

#17264 Add missing documentation
  packages/forms/docs/01-overview.md
  packages/infolists/docs/01-overview.md
Labels: documentation

#17272 Fix updating table grouping
  packages/tables/resources/views/index.blade.php
Labels: bug

#17273 v4 stable docs & new upgrade directory structure command
  docs/01-introduction/02-installation.md
  docs/14-upgrade-guide.md
  packages/upgrade/composer.json
  packages/upgrade/src/Commands/UpgradeDirectoryStructureToV4Command.php
  packages/upgrade/src/UpgradeServiceProvider.php
  phpstan.neon.dist
Labels: documentation, enhancement

#17274 fix: Remove redundant column prefixing in table summaries
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Concerns/CanSummarizeRecords.php
  packages/upgrade/src/Commands/UpgradeDirectoryStructureToV4Command.php
Labels: bug

#17278 update Indonesian translation
  packages/forms/resources/lang/id/components.php
  packages/panels/resources/lang/id/resources/pages/edit-record.php
  packages/panels/resources/lang/id/resources/pages/manage-related-records.php
  packages/panels/resources/lang/id/resources/pages/view-record.php
  packages/support/resources/lang/id/components/copyable.php
  packages/tables/resources/lang/id/table.php
Labels: i18n

#17283 fix: add Spanish translation for restored_none.title
  packages/actions/resources/lang/es/restore.php
Labels: i18n

#17296 fix: added panel render hooks even if user menu has profile header
  packages/panels/resources/views/components/user-menu.blade.php
Labels: bug

#17306 Resolve `BroadcastNotification` from container and forward configuration
  packages/notifications/src/BroadcastNotification.php
  packages/notifications/src/Notification.php
Labels: bug

#17322 Fix selection indicator not showing in table with rows
  packages/actions/resources/lang/it/delete.php
  packages/actions/resources/lang/it/restore.php
  packages/panels/dist/theme.css
  packages/tables/resources/css/row.css
Labels: bug

#17315 Use the correct `Action` class in `repeater.simple.blade`
  packages/forms/resources/views/components/repeater/simple.blade.php
Labels: bug

#17328 fix: Relationship columns generated with `numeric()`
  packages/infolists/src/Commands/FileGenerators/Concerns/CanGenerateModelInfolists.php
  packages/tables/src/Commands/FileGenerators/Concerns/CanGenerateModelTables.php
  tests/.pest/snapshots/src/Panels/Commands/Legacy/LegacyMakeResourceCommandTest/it_can_generate_the_form_and_table_of_a_resource_class.snap
  tests/.pest/snapshots/src/Panels/Commands/MakeResourceCommandTest/it_can_generate_the_form__infolist__and_table_content_embedded_in_a_resource_class.snap
  tests/.pest/snapshots/src/Panels/Commands/MakeResourceCommandTest/it_can_generate_the_resource_infolist_content.snap
  tests/.pest/snapshots/src/Panels/Commands/MakeResourceCommandTest/it_can_generate_the_resource_table_content.snap
  tests/.pest/snapshots/src/Tables/Commands/MakeLivewireTableCommandTest/it_can_generate_a_Livewire_table_component_with_generated_columns.snap
Labels: bug

#17343 Update 03-icon.md
  packages/tables/docs/02-columns/03-icon.md
Labels: documentation

#17335 Update turkish translations
  packages/forms/resources/lang/tr/components.php
  packages/panels/resources/lang/tr/auth/multi-factor/email/actions/disable.php
  packages/panels/resources/lang/tr/auth/multi-factor/email/actions/set-up.php
  packages/panels/resources/lang/tr/auth/multi-factor/email/notifications/verify-email-authentication.php
  packages/panels/resources/lang/tr/auth/multi-factor/email/provider.php
  packages/panels/resources/lang/tr/auth/multi-factor/pages/set-up-required-multi-factor-authentication.php
  packages/panels/resources/lang/tr/auth/multi-factor/recovery-codes-modal-content.php
  packages/panels/resources/lang/tr/resources/pages/edit-record.php
  packages/panels/resources/lang/tr/resources/pages/manage-related-records.php
  packages/panels/resources/lang/tr/resources/pages/view-record.php
  packages/tables/resources/lang/tr/table.php
Labels: i18n

#17398 [4.x] Add missing `lus` translations
  packages/actions/resources/lang/lus/attach.php
  packages/actions/resources/lang/lus/create.php
  packages/actions/resources/lang/lus/delete.php
  packages/actions/resources/lang/lus/detach.php
  packages/actions/resources/lang/lus/edit.php
  packages/actions/resources/lang/lus/export.php
  packages/actions/resources/lang/lus/import.php
  packages/forms/resources/lang/lus/components.php
  packages/panels/resources/lang/lus/global-search.php
  packages/panels/resources/lang/lus/resources/pages/create-record.php
  packages/panels/resources/lang/lus/resources/pages/edit-record.php
  packages/panels/resources/lang/lus/unsaved-changes-alert.php
  packages/panels/resources/lang/lus/widgets/account-widget.php
  packages/support/resources/lang/lus/components/pagination.php
  packages/tables/resources/lang/lus/table.php
Labels: i18n

#17405 [4.x] fix js($get): return containerPathCopy when path is empty
  packages/schemas/dist/index.js
  packages/schemas/resources/js/index.js
Labels: bug

#17421 [4.x] Fix typo in Icon column docs
  packages/tables/docs/02-columns/03-icon.md
Labels: documentation

#17428 Missing v4 Swedish translations
  packages/actions/resources/lang/sv/delete.php
  packages/actions/resources/lang/sv/force-delete.php
  packages/actions/resources/lang/sv/notifications.php
  packages/actions/resources/lang/sv/restore.php
  packages/forms/resources/lang/sv/components.php
  packages/panels/resources/lang/sv/auth/http/controllers/block-email-change-verification-controller.php
  packages/panels/resources/lang/sv/auth/http/controllers/email-change-verification-controller.php
  packages/panels/resources/lang/sv/auth/multi-factor/app/actions/disable.php
  packages/panels/resources/lang/sv/auth/multi-factor/app/actions/regenerate-recovery-codes.php
  packages/panels/resources/lang/sv/auth/multi-factor/app/actions/set-up.php
  packages/panels/resources/lang/sv/auth/multi-factor/app/provider.php
  packages/panels/resources/lang/sv/auth/multi-factor/email/actions/disable.php
  packages/panels/resources/lang/sv/auth/multi-factor/email/actions/set-up.php
  packages/panels/resources/lang/sv/auth/multi-factor/email/notifications/verify-email-authentication.php
  packages/panels/resources/lang/sv/auth/multi-factor/email/provider.php
  packages/panels/resources/lang/sv/auth/multi-factor/pages/set-up-required-multi-factor-authentication.php
  packages/panels/resources/lang/sv/auth/multi-factor/recovery-codes-modal-content.php
  packages/panels/resources/lang/sv/auth/notifications/notice-of-email-change-request.php
  packages/panels/resources/lang/sv/auth/pages/edit-profile.php
  packages/panels/resources/lang/sv/auth/pages/login.php
  packages/panels/resources/lang/sv/error-notifications.php
  packages/panels/resources/lang/sv/resources/pages/edit-record.php
  packages/panels/resources/lang/sv/resources/pages/manage-related-records.php
  packages/panels/resources/lang/sv/resources/pages/view-record.php
  packages/tables/resources/lang/sv/table.php
  packages/widgets/resources/lang/sv/chart.php
Labels: i18n

#17408 [4.x] fix(forms): escape placeholder attributes so quotes render correctly
  packages/forms/resources/views/components/color-picker.blade.php
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/resources/views/components/one-time-code-input.blade.php
  packages/forms/resources/views/components/tags-input.blade.php
  packages/forms/resources/views/components/text-input.blade.php
  packages/forms/resources/views/components/textarea.blade.php
Labels: bug

#17418 [3.x] fix(forms): escape placeholder attributes so quotes render correctly
  packages/forms/resources/views/components/color-picker.blade.php
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/resources/views/components/text-input.blade.php
  packages/forms/resources/views/components/textarea.blade.php
Labels: bug

#17425 Documentation: Rich content attribute must be nullable in database.
  packages/spatie-laravel-media-library-plugin/README.md
Labels: documentation

#17444 Fixed misleading documentation for defaultSort()
  packages/actions/resources/lang/sv/notifications.php
  packages/panels/resources/lang/sv/auth/http/controllers/block-email-change-verification-controller.php
  packages/panels/resources/lang/sv/auth/http/controllers/email-change-verification-controller.php
  packages/panels/resources/lang/sv/auth/multi-factor/app/actions/disable.php
  packages/panels/resources/lang/sv/auth/multi-factor/app/actions/regenerate-recovery-codes.php
  packages/panels/resources/lang/sv/auth/multi-factor/app/actions/set-up.php
  packages/panels/resources/lang/sv/auth/multi-factor/app/provider.php
  packages/panels/resources/lang/sv/auth/multi-factor/email/actions/disable.php
  packages/panels/resources/lang/sv/auth/multi-factor/email/actions/set-up.php
  packages/panels/resources/lang/sv/auth/multi-factor/email/notifications/verify-email-authentication.php
  packages/panels/resources/lang/sv/auth/multi-factor/email/provider.php
  packages/panels/resources/lang/sv/auth/multi-factor/pages/set-up-required-multi-factor-authentication.php
  packages/panels/resources/lang/sv/auth/multi-factor/recovery-codes-modal-content.php
  packages/panels/resources/lang/sv/auth/notifications/notice-of-email-change-request.php
  packages/panels/resources/lang/sv/error-notifications.php
  packages/panels/resources/lang/sv/resources/pages/manage-related-records.php
  packages/tables/docs/02-columns/01-overview.md
  packages/widgets/resources/lang/sv/chart.php
Labels: documentation

#17434 [4.x] Fix: Save multiple files at once in the Rich Editor with spatie-laravel-media-library-plugin
  packages/spatie-laravel-media-library-plugin/src/Forms/Components/RichEditor/FileAttachmentProviders/SpatieMediaLibraryFileAttachmentProvider.php
Labels: bug

#17450 fix: Default image URLs
  packages/infolists/src/Components/ImageEntry.php
  packages/tables/src/Columns/ImageColumn.php
Labels: bug

#17443 Hide blank column labels in the column manager
  packages/tables/resources/views/components/column-manager.blade.php
  packages/tables/src/Columns/Concerns/CanBeToggled.php
  packages/tables/src/Concerns/HasColumnManager.php
Labels: bug

#17469 [v4] Fix (docs): Correction in documentation of Modals
  packages/actions/docs/02-modals.md
Labels: documentation

#17334 [4.x] feat: make `afterStateUpdatedJs` work on table repeater
  packages/forms/resources/views/components/repeater/table.blade.php
Labels: bug

#17509 fix: Removing table filters from sections
  packages/forms/src/Components/Concerns/CanFixIndistinctState.php
  packages/schemas/src/Components/Utilities/Get.php
  packages/schemas/src/Components/Utilities/Set.php
  packages/schemas/src/Concerns/HasComponents.php
  packages/tables/src/Concerns/HasFilters.php
Labels: bug

#17481 fix: Cast ModalTableSelect HasMany state to strings to fix selection
  packages/forms/src/Components/ModalTableSelect.php
Labels: bug

#17484 [4.x] Fix SelectColumn crash when using objects as state values
  packages/tables/src/Columns/SelectColumn.php
Labels: bug

#17556 Docs: Fix link to "optimizing local development"
  docs/13-deployment.md
Labels: documentation

#17575 [4.x] Fix(docs) broken authorization link on users overview page
  docs/07-users/01-overview.md
Labels: documentation

#17572 feat: support Model instances in getRecords
  packages/tables/src/Concerns/HasRecords.php
Labels: bug

#17508 [4.x] Chore: fix fenced code block styling in rich edtior
  packages/panels/dist/theme.css
  packages/support/resources/css/utilities.css
Labels: enhancement, ux
