Repository filamentphp/filament, pull requests merged in 2025-03, with the labels that each got.

#15740 Use `replaceState` instead of `pushState` for `forms` and `infolists` tab updates
  packages/forms/resources/views/components/tabs.blade.php
  packages/infolists/resources/views/components/tabs.blade.php
Labels: bug

#15734 Refine navigation item and group filtering logic.
  packages/panels/src/Navigation/NavigationManager.php
Labels: bug

#15759 Enhancement: Add Closure support to HasTopbar trait
  packages/panels/src/Panel/Concerns/HasTopbar.php
Labels: enhancement

#15594 Fix conditionally hiding summaries
  packages/tables/resources/views/components/summary/row.blade.php
  packages/tables/src/Columns/Concerns/CanBeSummarized.php
Labels: bug

#15756 Update pt_BR auth translations
  packages/panels/resources/lang/pt_BR/pages/auth/login.php
  packages/panels/resources/lang/pt_BR/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/pt_BR/pages/auth/register.php
Labels: i18n

#15780 Tweak theming process to work with Tailwind v4 installations
  packages/panels/src/Commands/MakeThemeCommand.php
  packages/panels/stubs/ThemeCssTailwind4.stub
Labels: bug

#15771 Add information about incrementing id for pivot BelongsToMany repeater
  packages/forms/docs/03-fields/12-repeater.md
Labels: documentation

#15777 Add data attribute for modal id to modal windows
  packages/support/resources/views/components/modal/index.blade.php
Labels: enhancement

#15785 Filament session key improvement
  packages/panels/src/Pages/Dashboard/Concerns/HasFilters.php
  packages/tables/src/Concerns/CanPaginateRecords.php
  packages/tables/src/Concerns/CanSearchRecords.php
  packages/tables/src/Concerns/CanSortRecords.php
  packages/tables/src/Concerns/CanToggleColumns.php
  packages/tables/src/Concerns/HasFilters.php
Labels: bug

#15786 Update 01-installation.md
  packages/actions/docs/01-installation.md
  packages/forms/docs/01-installation.md
  packages/infolists/docs/01-installation.md
  packages/notifications/docs/01-installation.md
  packages/panels/docs/01-installation.md
  packages/tables/docs/01-installation.md
  packages/widgets/docs/01-installation.md
Labels: documentation

#15792 fix: handle a possible issue from output buffer
  packages/actions/src/Exports/Downloaders/XlsxDownloader.php
Labels: bug

#15817 Modify panel default() method to accept closure
  packages/panels/src/Panel.php
Labels: enhancement

#15818 Alias `filament:install` to `install:filament`
  packages/support/src/Commands/InstallCommand.php
Labels: enhancement

#15650 fix: incorrect loaded state with HasOneOrMany select
  packages/forms/src/Components/Select.php
Labels: bug

#15841 [4.x] Add decimalPlaces argument to component money function
  packages/infolists/src/Components/Concerns/CanFormatState.php
  packages/schemas/docs/03-infolists/02-text.md
  packages/tables/docs/02-columns/02-text.md
  packages/tables/docs/06-summaries.md
  packages/tables/src/Columns/Concerns/CanFormatState.php
  packages/tables/src/Columns/Summarizers/Concerns/CanFormatState.php
Labels: enhancement

#15842 Fixed: PHP syntax error in CreateAction
  packages/tables/src/Actions/CreateAction.php
Labels: bug

#15840 Docs V4 - Installation/Individual components/Configuring styles section
  docs/01-introduction/02-installation.md
Labels: documentation

#15883 Wrap the exception handler around getVisibility()
  packages/forms/src/Components/Concerns/HasFileAttachments.php
Labels: bug

#15903 Fix broken XLSX exports
  packages/actions/src/Exports/Downloaders/XlsxDownloader.php
Labels: bug

#15897 Docs V4 - Tabs
  docs-assets/app/app/Livewire/Schemas/LayoutDemo.php
  docs-assets/screenshots/schema.js
  packages/schemas/docs/04-tabs.md
Labels: documentation

#15900 Docs v4 - Wizard
  packages/schemas/docs/05-wizards.md
Labels: documentation

#15891 fix: $defaultImageUrl not loading when getImageUrl() is null
  packages/infolists/resources/views/components/image-entry.blade.php
  packages/tables/resources/views/columns/image-column.blade.php
Labels: bug

#15889 Prevent catching side-effects of database transactions being committed
  packages/actions/src/Concerns/InteractsWithActions.php
  packages/forms/src/Concerns/HasFormComponentActions.php
  packages/infolists/src/Concerns/InteractsWithInfolists.php
  packages/panels/src/Pages/Auth/EditProfile.php
  packages/panels/src/Pages/Tenancy/EditTenantProfile.php
  packages/panels/src/Pages/Tenancy/RegisterTenant.php
  packages/panels/src/Resources/Pages/CreateRecord.php
  packages/panels/src/Resources/Pages/EditRecord.php
  packages/spatie-laravel-settings-plugin/src/Pages/SettingsPage.php
  packages/tables/src/Concerns/HasActions.php
  packages/tables/src/Concerns/HasBulkActions.php
  tests/src/Panels/Fixtures/Resources/PostResource.php
  tests/src/Panels/Fixtures/Resources/PostResource/Pages/EditPost.php
  tests/src/Panels/Resources/Pages/EditRecordTest.php
  tests/src/Panels/Resources/Pages/ListRecordsTest.php
Labels: bug

#15915 [2.x]: Upgrade DOMPurify
  package-lock.json
  package.json
  packages/admin/dist/app.css
  packages/admin/dist/app.css.map
  packages/admin/dist/app.js
  packages/admin/dist/app.js.map
  packages/admin/dist/echo.js
  packages/admin/dist/echo.js.map
  packages/admin/dist/mix-manifest.json
  packages/forms/dist/module.esm.css
  packages/forms/dist/module.esm.js
  packages/notifications/dist/module.esm.js
Labels: dependencies

#15920 Add support for page-specific relation managers with policy enforcement
  packages/panels/docs/03-resources/05-viewing-records.md
  packages/panels/src/Resources/Pages/Concerns/HasRelationManagers.php
Labels: enhancement

#15942 Fix: Add thousands separators to table selection indicators
  packages/tables/resources/views/components/selection/indicator.blade.php
Labels: ux

#15951 Fix: Exporting excel files not working in Laravel Vapor environments
  packages/actions/src/Exports/Downloaders/XlsxDownloader.php
Labels: bug

#15962 fix: Add missing Filepond translations to support more locales in File Upload
  packages/forms/dist/components/file-upload.js
  packages/forms/resources/js/components/file-upload.js
Labels: i18n

#15963 Allow closure for default avatar provider
  packages/panels/src/Panel/Concerns/HasAvatars.php
Labels: enhancement
