Repository filamentphp/filament, pull requests merged in 2025-01, with the labels that each got.

#15219 Fixed Docs: Updated the URL
  packages/forms/docs/03-fields/15-textarea.md
Labels: documentation

#15217 Added TimePicker and time method with generate argument
  packages/forms/src/Commands/FileGenerators/Concerns/CanGenerateModelForms.php
  packages/tables/src/Commands/FileGenerators/Concerns/CanGenerateModelTables.php
Labels: enhancement, awaiting next major version

#15181 Fix: Add conditions to DISTINCT and modify reorder conditions in PostgreSQL
  packages/actions/src/Exports/Jobs/PrepareCsvExport.php
Labels: bug

#15238 fix: add Form and Table to prevent collision while creating a resource
  packages/panels/src/Commands/MakeResourceCommand.php
Labels: bug

#15223 hide zero notification badge
  packages/panels/resources/views/components/topbar/database-notifications-trigger.blade.php
Labels: ux

#15224 bump/remove league csv BOM deprecate notice
  composer.json
  packages/actions/composer.json
  packages/actions/src/Concerns/CanImportRecords.php
  packages/actions/src/Exports/Jobs/PrepareCsvExport.php
  packages/actions/src/Imports/Http/Controllers/DownloadImportFailureCsv.php
Labels: bug

#15235 fix: add maxlenght 1000 to global search & table search 3.x
  packages/panels/resources/views/components/global-search/field.blade.php
  packages/tables/resources/views/components/search-field.blade.php
Labels: enhancement

#15268 Prevent min width on not individually searchable table columns
  packages/tables/resources/views/index.blade.php
Labels: bug

#15266 Improve `Tabs` label experience.
  packages/support/resources/views/components/tabs/item.blade.php
Labels: ui

#15293 Sushi Compatible Summarizers
  packages/support/resources/views/components/tabs/item.blade.php
  packages/tables/src/Columns/Summarizers/Summarizer.php
  packages/tables/src/Concerns/CanSummarizeRecords.php
Labels: bug

#15290 Allow multiple disable option conditions
  packages/forms/src/Components/Concerns/CanDisableOptions.php
Labels: enhancement

#15267 Fix forced lower case search for json field
  packages/support/src/helpers.php
Labels: bug

#15274 bug: Fix type error in Asset
  packages/support/src/Assets/Asset.php
Labels: bug

#15300 [Docs] Added docs for `disableOptionWhen` second argument
  packages/forms/docs/03-fields/12-repeater.md
Labels: documentation

#15304 chore: add missing Croatian translations and update some
  packages/actions/resources/lang/hr/attach.php
  packages/actions/resources/lang/hr/create.php
  packages/actions/resources/lang/hr/delete.php
  packages/actions/resources/lang/hr/export.php
  packages/actions/resources/lang/hr/force-delete.php
  packages/actions/resources/lang/hr/import.php
  packages/actions/resources/lang/hr/modal.php
  packages/forms/resources/lang/hr/components.php
  packages/forms/resources/lang/hr/validation.php
  packages/infolists/resources/lang/hr/components.php
  packages/notifications/resources/lang/hr/database.php
  packages/panels/resources/lang/hr/layout.php
  packages/panels/resources/lang/hr/pages/auth/edit-profile.php
  packages/panels/resources/lang/hr/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/hr/pages/auth/login.php
  packages/panels/resources/lang/hr/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/hr/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/hr/pages/auth/register.php
  packages/panels/resources/lang/hr/pages/dashboard.php
  packages/panels/resources/lang/hr/resources/pages/create-record.php
  packages/panels/resources/lang/hr/resources/pages/list-records.php
  packages/panels/resources/lang/hr/unsaved-changes-alert.php
  packages/support/resources/lang/hr/components/pagination.php
  packages/tables/resources/lang/hr/filters/query-builder.php
  packages/tables/resources/lang/hr/table.php
Labels: i18n

#15310 New: Add `assertTableFilterHidden` and `assertTableFilterVisible` test methods
  packages/tables/.stubs.php
  packages/tables/docs/12-testing.md
  packages/tables/src/Table/Concerns/HasFilters.php
  packages/tables/src/Testing/TestsFilters.php
  tests/src/Tables/Filters/FilterTest.php
  tests/src/Tables/Fixtures/PostsTable.php
Labels: enhancement

#15315 remove gridColor option overide chart.js
  packages/widgets/dist/components/chart.js
  packages/widgets/resources/js/components/chart.js
Labels: bug

#15319 Fix: Add expanded close tag option in datalist (bug in Chrome)
  packages/forms/resources/views/components/text-input.blade.php
Labels: bug

#15360 fix: Notification animation scrolling whole page
  packages/notifications/dist/index.js
  packages/notifications/resources/js/components/notification.js
Labels: bug

#15398 Dynamic heading levels
  packages/actions/src/Concerns/InteractsWithActions.php
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/repeater/index.blade.php
  packages/forms/src/Components/Builder.php
  packages/forms/src/Components/Repeater.php
  packages/schemas/resources/views/components/section.blade.php
  packages/schemas/src/Components/Component.php
  packages/schemas/src/Components/Concerns/HasHeadings.php
  packages/schemas/src/Components/Section.php
  packages/schemas/src/Concerns/HasHeadings.php
  packages/schemas/src/Schema.php
  packages/support/resources/views/components/section/heading.blade.php
  packages/support/resources/views/components/section/index.blade.php
  packages/tables/resources/views/components/filters.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Table.php
  packages/tables/src/Table/Concerns/HasHeadings.php
Labels: enhancement

#15261 Fix: `RelationshipJoiner` raw & sub-query orders
  packages/support/src/Services/RelationshipJoiner.php
  tests/database/migrations/create_team_user_table.php
  tests/src/Models/User.php
  tests/src/Support/Services/RelationshipJoinerTest.php
Labels: bug

#15340 Prevent stacked, editable table columns to trigger wrapping a.href
  packages/tables/resources/views/columns/checkbox-column.blade.php
  packages/tables/resources/views/columns/select-column.blade.php
  packages/tables/resources/views/columns/text-input-column.blade.php
  packages/tables/resources/views/columns/toggle-column.blade.php
Labels: bug

#15346 Fix: key-value form component initial rows/state synchronization
  packages/forms/dist/components/key-value.js
  packages/forms/resources/js/components/key-value.js
Labels: bug

#15354 Fix: Prevent column groups table row from appearing if all columns in every group are (toggled) hidden
  packages/tables/src/Table/Concerns/HasColumns.php
Labels: bug

#15376 Fix str_getcsv(): the $escape parameter must be provided as its default value will change after updating to PHP 8.4
  packages/support/src/Commands/Concerns/CanReadModelSchemas.php
  packages/tables/src/Concerns/CanSearchRecords.php
Labels: bug

#15399 Update all Armenian language files
  packages/actions/resources/lang/hy/delete.php
  packages/actions/resources/lang/hy/detach.php
  packages/actions/resources/lang/hy/dissociate.php
  packages/actions/resources/lang/hy/export.php
  packages/actions/resources/lang/hy/force-delete.php
  packages/actions/resources/lang/hy/import.php
  packages/actions/resources/lang/hy/modal.php
  packages/actions/resources/lang/hy/restore.php
  packages/actions/resources/lang/hy/view.php
  packages/filament/resources/lang/hy/global-search.php
  packages/filament/resources/lang/hy/layout.php
  packages/filament/resources/lang/hy/pages/auth/edit-profile.php
  packages/filament/resources/lang/hy/pages/auth/email-verification/email-verification-prompt.php
  packages/filament/resources/lang/hy/pages/auth/login.php
  packages/filament/resources/lang/hy/pages/auth/password-reset/request-password-reset.php
  packages/filament/resources/lang/hy/pages/auth/password-reset/reset-password.php
  packages/filament/resources/lang/hy/pages/auth/register.php
  packages/filament/resources/lang/hy/pages/dashboard.php
  packages/filament/resources/lang/hy/pages/tenancy/edit-tenant-profile.php
  packages/filament/resources/lang/hy/resources/pages/create-record.php
  packages/filament/resources/lang/hy/resources/pages/edit-record.php
  packages/filament/resources/lang/hy/resources/pages/list-records.php
  packages/filament/resources/lang/hy/resources/pages/view-record.php
  packages/filament/resources/lang/hy/unsaved-changes-alert.php
  packages/filament/resources/lang/hy/widgets/account-widget.php
  packages/filament/resources/lang/hy/widgets/filament-info-widget.php
  packages/forms/resources/lang/hy/components.php
  packages/forms/resources/lang/hy/validation.php
  packages/infolists/resources/lang/hy/components.php
  packages/notifications/resources/lang/hy/database.php
  packages/support/resources/lang/hy/components/copyable.php
  packages/support/resources/lang/hy/components/modal.php
  packages/support/resources/lang/hy/components/pagination.php
  packages/tables/resources/lang/hy/filters/query-builder.php
  packages/tables/resources/lang/hy/table.php
Labels: i18n

#15401 Update Dutch translations
  packages/forms/resources/lang/nl/components.php
  packages/tables/resources/lang/nl/table.php
Labels: i18n

#15196 Allow closure based table `Group` labels
  packages/tables/src/Grouping/Concerns/BelongsToTable.php
  packages/tables/src/Grouping/Group.php
  packages/tables/src/Table/Concerns/CanGroupRecords.php
  tests/src/Tables/Fixtures/PostsTable.php
  tests/src/Tables/GroupingTest.php
  tests/src/TestCase.php
Labels: enhancement

#15407 Fix summarizer connection resolver on non-default connections
  packages/tables/src/Columns/Summarizers/Summarizer.php
  packages/tables/src/Concerns/CanSummarizeRecords.php
Labels: bug

#15418 docs: update installation docs to mention testing
  packages/panels/docs/01-installation.md
Labels: documentation

#15475 Rename max width enum
  docs/09-upgrade-guide.md
  packages/actions/docs/03-modals.md
  packages/actions/docs/04-grouping-actions.md
  packages/actions/src/ActionGroup.php
  packages/actions/src/AssociateAction.php
  packages/actions/src/AttachAction.php
  packages/actions/src/Concerns/CanOpenModal.php
  packages/actions/src/Concerns/HasDropdown.php
  packages/forms/src/Components/Builder.php
  packages/panels/docs/03-pages.md
  packages/panels/docs/08-configuration.md
  packages/panels/resources/views/components/layout/index.blade.php
  packages/panels/resources/views/components/layout/simple.blade.php
  packages/panels/src/Auth/MultiFactor/EmailCode/Actions/DisableEmailCodeAuthenticationAction.php
  packages/panels/src/Auth/MultiFactor/EmailCode/Actions/SetUpEmailCodeAuthenticationAction.php
  packages/panels/src/Auth/MultiFactor/GoogleTwoFactor/Actions/DisableGoogleTwoFactorAuthenticationAction.php
  packages/panels/src/Auth/MultiFactor/GoogleTwoFactor/Actions/RegenerateGoogleTwoFactorAuthenticationRecoveryCodesAction.php
  packages/panels/src/Auth/MultiFactor/GoogleTwoFactor/Actions/SetUpGoogleTwoFactorAuthenticationAction.php
  packages/panels/src/Facades/Filament.php
  packages/panels/src/FilamentManager.php
  packages/panels/src/Pages/BasePage.php
  packages/panels/src/Pages/Concerns/HasMaxWidth.php
  packages/panels/src/Panel/Concerns/HasMaxContentWidth.php
  packages/schemas/resources/views/schema.blade.php
  packages/schemas/src/Components/Concerns/HasMaxWidth.php
  packages/support/resources/views/components/dropdown/index.blade.php
  packages/support/resources/views/components/modal/index.blade.php
  packages/support/src/Enums/Width.php
  packages/tables/docs/03-filters/06-layout.md
  packages/tables/src/Table/Concerns/CanToggleColumns.php
  packages/tables/src/Table/Concerns/HasFilters.php
  packages/upgrade/bin/filament-v4
  packages/upgrade/src/rector.php
Labels: enhancement

#15446 Fix: QueryBuilder's TextConstraint for Postgres
  packages/tables/src/Filters/QueryBuilder/Constraints/TextConstraint/Operators/ContainsOperator.php
  packages/tables/src/Filters/QueryBuilder/Constraints/TextConstraint/Operators/EndsWithOperator.php
  packages/tables/src/Filters/QueryBuilder/Constraints/TextConstraint/Operators/EqualsOperator.php
  packages/tables/src/Filters/QueryBuilder/Constraints/TextConstraint/Operators/StartsWithOperator.php
Labels: bug

#15462 Add override possibility to page aware widgets
  packages/panels/src/Widgets/Concerns/InteractsWithPageTable.php
Labels: enhancement

#15480 Add missing Persian translation for filters/query-builder.php
  packages/tables/resources/lang/fa/filters/query-builder.php
Labels: i18n

#15479 Fix: pin tailwindcss to version 3 in artisan command `make:filament-theme`
  packages/actions/docs/01-installation.md
  packages/forms/docs/01-installation.md
  packages/infolists/docs/01-installation.md
  packages/notifications/docs/01-installation.md
  packages/panels/src/Commands/MakeThemeCommand.php
  packages/tables/docs/01-installation.md
  packages/widgets/docs/01-installation.md
Labels: enhancement
