Repository filamentphp/filament, pull requests merged in 2025-09, with the labels that each got.

#17591 fix: Pagination return types
  packages/tables/src/Concerns/CanPaginateRecords.php
  packages/tables/src/Concerns/HasRecords.php
  packages/tables/src/Contracts/HasTable.php
Labels: bug

#17588 Skip rendering Livewire component on certain test methods
  packages/forms/resources/views/components/rich-editor.blade.php
  packages/schemas/src/Concerns/InteractsWithSchemas.php
Labels: bug

#17593 fix: Persistent middleware registration while caching routes
  packages/panels/src/FilamentServiceProvider.php
Labels: bug

#17547 Allow null as title
  packages/tables/src/Grouping/Group.php
Labels: bug, pending changes

#17596 Rich editor content toText() renderer
  packages/forms/src/Components/RichEditor/RichContentRenderer.php
Labels: enhancement

#17604 Fix(Form/Repeater): update event handling for sortable items to prevent unnecessary reordering
  packages/forms/resources/views/components/repeater/index.blade.php
  packages/forms/resources/views/components/repeater/simple.blade.php
  packages/forms/resources/views/components/repeater/table.blade.php
Labels: bug

#17612 fix: Select column validation
  packages/support/src/Concerns/HasCellState.php
  packages/tables/src/Columns/Concerns/CanBeValidated.php
Labels: bug

#17614 [4.x] Fix mounting action from method with union return type
  packages/actions/src/Concerns/InteractsWithActions.php
Labels: bug

#17616 fix: Database notification actions after v4 upgrade
  packages/actions/src/Action.php
  packages/notifications/dist/index.js
  packages/notifications/resources/css/database-notifications.css
  packages/notifications/resources/js/Notification.js
  packages/panels/dist/theme.css
Labels: bug

#17602 Fix placeholder alignment
  packages/tables/src/Columns/ColorColumn.php
  packages/tables/src/Columns/IconColumn.php
  packages/tables/src/Columns/ImageColumn.php
  packages/tables/src/Columns/TextColumn.php
Labels: bug

#17621 [4.x] Explicitly cast Phiki result to string
  composer.json
  composer.lock
  docs-assets/app/composer.json
  packages/infolists/src/Components/CodeEntry.php
Labels: bug

#17634 Fix deprecated reference
  packages/actions/docs/05-edit.md
Labels: documentation

#17641 Add missing German translations
  packages/panels/resources/lang/de/auth/pages/edit-profile.php
  packages/panels/resources/lang/de/auth/pages/password-reset/request-password-reset.php
  packages/panels/resources/lang/de/auth/pages/password-reset/reset-password.php
  packages/panels/resources/lang/de/resources/pages/edit-record.php
  packages/panels/resources/lang/de/resources/pages/manage-related-records.php
  packages/panels/resources/lang/de/resources/pages/view-record.php
Labels: i18n

#17644 Fix: select column cleanup
  packages/tables/dist/components/columns/select.js
  packages/tables/resources/js/components/columns/select.js
Labels: bug

#17647 Translate missing slugs for Dutch (nl)
  packages/actions/resources/lang/nl/delete.php
  packages/actions/resources/lang/nl/force-delete.php
  packages/actions/resources/lang/nl/notifications.php
  packages/actions/resources/lang/nl/restore.php
  packages/forms/resources/lang/nl/components.php
  packages/panels/resources/lang/nl/auth/http/controllers/block-email-change-verification-controller.php
  packages/panels/resources/lang/nl/auth/http/controllers/email-change-verification-controller.php
  packages/panels/resources/lang/nl/auth/notifications/notice-of-email-change-request.php
  packages/panels/resources/lang/nl/auth/pages/edit-profile.php
  packages/panels/resources/lang/nl/auth/pages/login.php
  packages/panels/resources/lang/nl/error-notifications.php
  packages/panels/resources/lang/nl/resources/pages/edit-record.php
  packages/panels/resources/lang/nl/resources/pages/manage-related-records.php
  packages/panels/resources/lang/nl/resources/pages/view-record.php
  packages/tables/resources/lang/nl/table.php
  packages/widgets/resources/lang/nl/chart.php
Labels: i18n

#17645 Add missing TH table column manager translations.
  packages/tables/resources/lang/th/table.php
Labels: i18n

#17642 Fix: update draggable index handling in sortable components
  packages/forms/resources/css/components/builder.css
  packages/forms/resources/css/components/repeater.css
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/repeater/index.blade.php
  packages/forms/resources/views/components/repeater/simple.blade.php
  packages/forms/resources/views/components/repeater/table.blade.php
  packages/panels/dist/theme.css
  packages/schemas/src/Concerns/HasComponents.php
  packages/support/dist/index.js
  packages/support/resources/js/sortable.js
Labels: bug

#17651 fix: Rich editor local image uploads
  packages/forms/dist/components/rich-editor.js
  packages/forms/resources/css/components/rich-editor.css
  packages/forms/resources/js/components/rich-editor/extension-local-files.js
  packages/forms/resources/lang/en/components.php
  packages/forms/resources/views/components/rich-editor.blade.php
  packages/panels/dist/theme.css
  packages/tables/resources/css/container.css
Labels: bug

#17622 Fix: drag prevention ineffective in `repeater` component during requests
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/repeater/index.blade.php
  packages/forms/resources/views/components/repeater/simple.blade.php
  packages/forms/resources/views/components/repeater/table.blade.php
Labels: bug

#17631 Add zh_HK translations by duplicating zh_TW
  packages/actions/resources/lang/zh_HK/associate.php
  packages/actions/resources/lang/zh_HK/attach.php
  packages/actions/resources/lang/zh_HK/create.php
  packages/actions/resources/lang/zh_HK/delete.php
  packages/actions/resources/lang/zh_HK/detach.php
  packages/actions/resources/lang/zh_HK/dissociate.php
  packages/actions/resources/lang/zh_HK/edit.php
  packages/actions/resources/lang/zh_HK/export.php
  packages/actions/resources/lang/zh_HK/force-delete.php
  packages/actions/resources/lang/zh_HK/group.php
  packages/actions/resources/lang/zh_HK/import.php
  packages/actions/resources/lang/zh_HK/modal.php
  packages/actions/resources/lang/zh_HK/replicate.php
  packages/actions/resources/lang/zh_HK/restore.php
  packages/actions/resources/lang/zh_HK/view.php
  packages/forms/dist/components/date-time-picker.js
  packages/forms/resources/js/components/date-time-picker.js
  packages/forms/resources/lang/zh_HK/components.php
  packages/infolists/resources/lang/zh_HK/components.php
  packages/notifications/resources/lang/zh_HK/database.php
  packages/panels/resources/lang/zh_HK/auth/pages/login.php
  packages/panels/resources/lang/zh_HK/global-search.php
  packages/panels/resources/lang/zh_HK/layout.php
  packages/panels/resources/lang/zh_HK/pages/dashboard.php
  packages/panels/resources/lang/zh_HK/resources/pages/create-record.php
  packages/panels/resources/lang/zh_HK/resources/pages/edit-record.php
  packages/panels/resources/lang/zh_HK/resources/pages/list-records.php
  packages/panels/resources/lang/zh_HK/resources/pages/view-record.php
  packages/panels/resources/lang/zh_HK/widgets/account-widget.php
  packages/panels/resources/lang/zh_HK/widgets/filament-info-widget.php
  packages/schemas/resources/lang/zh_HK/components.php
  packages/spatie-laravel-settings-plugin/resources/lang/zh_HK/pages/settings-page.php
  packages/support/resources/lang/zh_HK/components/button.php
  packages/support/resources/lang/zh_HK/components/copyable.php
  packages/support/resources/lang/zh_HK/components/modal.php
  packages/support/resources/lang/zh_HK/components/pagination.php
  packages/tables/resources/lang/zh_HK/filters/query-builder.php
  packages/tables/resources/lang/zh_HK/table.php
Labels: i18n

#17652 fix: Select placeholder text color
  packages/forms/dist/components/select.js
  packages/panels/dist/theme.css
  packages/support/resources/css/components/input/select.css
  packages/support/resources/js/utilities/select.js
  packages/tables/dist/components/columns/select.js
Labels: bug

#17655 Use the correct name for the logout button icon
  packages/panels/resources/views/widgets/account-widget.blade.php
  packages/panels/src/Panel/Concerns/HasUserMenu.php
Labels: bug

#17657 fix: wrong link
  packages/infolists/docs/01-overview.md
Labels: documentation

#17675 Add SK/CZ translation
  packages/forms/resources/lang/cs/components.php
  packages/forms/resources/lang/sk/components.php
Labels: i18n

#17682 fix: Improve infolist & relation manager generation commands
  packages/forms/src/Commands/FileGenerators/Concerns/CanGenerateModelForms.php
  packages/infolists/src/Commands/FileGenerators/Concerns/CanGenerateModelInfolists.php
  packages/panels/src/Commands/MakePageCommand.php
  packages/panels/src/Commands/MakeRelationManagerCommand.php
  tests/.pest/snapshots/src/Panels/Commands/MakeResourceCommandTest/it_can_generate_the_form__infolist__and_table_content_embedded_in_a_resource_class.snap
  tests/.pest/snapshots/src/Panels/Commands/MakeResourceCommandTest/it_can_generate_the_resource_infolist_content.snap
Labels: enhancement

#17535 fix: live debounce logic for rich editor
  packages/forms/dist/components/rich-editor.js
  packages/forms/resources/js/components/rich-editor.js
Labels: bug

#17597 Fix: Preserve existing dropdown placement in nested ActionGroups
  packages/actions/src/ActionGroup.php
  packages/actions/src/Concerns/HasDropdown.php
Labels: bug

#17564 fix(support): accept BackedEnum/TextSize for badge size to prevent Ty…
  packages/schemas/resources/views/components/text.blade.php
  packages/schemas/src/Components/Text.php
Labels: bug

#17646 Fix: Adjust layout height handling and add topbar class
  packages/panels/dist/theme.css
  packages/panels/resources/css/components/layout.css
  packages/panels/resources/views/components/layout/index.blade.php
Labels: bug

#17684 fix: Tabs custom persistence ID
  packages/schemas/resources/views/components/tabs.blade.php
Labels: bug

#17680 fix: duplicated `notification`
  packages/notifications/dist/index.js
  packages/notifications/resources/js/components/notification.js
Labels: bug

#17672 fix: improve value formatting in `slider` component for better precision handling
  packages/forms/dist/components/slider.js
  packages/forms/resources/js/components/slider.js
Labels: bug

#17693 fix: Vite theme compilation warnings
  packages/panels/dist/theme.css
  packages/support/resources/css/components/input/select.css
  packages/tables/resources/css/content.css
Labels: bug

#17712 Fix: QR code generation for MFA when bacon QR is installed but imagick is not
  packages/panels/src/Auth/MultiFactor/App/AppAuthentication.php
Labels: bug

#17715 typo: Correct sentence in custom colums docs
  packages/tables/docs/02-columns/10-custom-columns.md
Labels: documentation

#17721 enable zh_HK for file-upload.js
  package-lock.json
  packages/forms/dist/components/code-editor.js
  packages/forms/dist/components/date-time-picker.js
  packages/forms/dist/components/file-upload.js
  packages/forms/dist/components/markdown-editor.js
  packages/forms/dist/components/rich-editor.js
  packages/forms/dist/components/select.js
  packages/forms/dist/components/slider.js
  packages/forms/resources/js/components/file-upload.js
  packages/panels/dist/echo.js
  packages/panels/dist/index.js
  packages/panels/dist/theme.css
  packages/support/dist/index.js
  packages/tables/dist/components/columns/select.js
  packages/widgets/dist/components/chart.js
  packages/widgets/dist/components/stats-overview/stat/chart.js
Labels: i18n

#17716 Add support for Htmlable to TableColumn
  packages/forms/src/Components/Repeater/TableColumn.php
Labels: enhancement

#17773 Updated Spanish translation - `form.components.php`
  packages/forms/resources/lang/es/components.php
Labels: i18n

#17783 fix: Partially rendering hidden schema components
  packages/schemas/src/Components/Component.php
  packages/schemas/src/Components/Concerns/CanPartiallyRender.php
  packages/schemas/src/Components/Concerns/HasState.php
  packages/schemas/src/Schema.php
Labels: bug

#17785 Use "state snapshot" for repeaters and builders
  packages/forms/src/Components/Builder.php
  packages/forms/src/Components/Repeater.php
  packages/schemas/src/Concerns/HasState.php
  packages/tables/src/Filters/QueryBuilder/Forms/Components/RuleBuilder.php
Labels: bug

#17516 fix: remove sidebar collapse button rotation logic
  packages/panels/resources/views/components/sidebar/index.blade.php
Labels: bug

#17786 fix: Table header action record
  packages/actions/src/Action.php
Labels: bug

#17774 fix: Allow `RichEditor` to work without registering rich content attributes
  packages/forms/src/Components/RichEditor.php
  packages/forms/src/Components/RichEditor/Actions/CustomBlockAction.php
  packages/forms/src/Components/RichEditor/Models/Concerns/InteractsWithRichContent.php
Labels: bug

#17587 Added more details the reordering records section
  packages/tables/docs/01-overview.md
Labels: documentation

#17789 fix: Cast empty string state to null earlier
  packages/schemas/src/Components/Concerns/HasState.php
  packages/schemas/src/Concerns/HasState.php
Labels: bug

#17752 Dont flip filter and column manager dropdowns
  packages/tables/resources/views/index.blade.php
Labels: ux

#17386 [4.x] Fix(docs): Add missing form class to singular resources example
  docs/03-resources/09-singular.md
Labels: documentation

#17792 fix: Testing action arguments
  packages/actions/src/Concerns/InteractsWithActions.php
  packages/panels/src/Auth/MultiFactor/App/Actions/SetUpAppAuthenticationAction.php
  tests/src/Forms/Components/RepeaterTest.php
Labels: bug

#17796 fix: Fused group with default columns
  packages/panels/dist/theme.css
  packages/schemas/resources/css/components/fused-group.css
  packages/support/src/SupportServiceProvider.php
Labels: bug

#17797 fix: Default action group dropdown placement before table columns
  packages/tables/src/Table/Concerns/HasRecordActions.php
Labels: bug

#17801 fix: add missing Ukrainian translation key
  packages/tables/resources/lang/uk/table.php
Labels: i18n

#17810 fix: State casting issues
  packages/forms/src/Components/CheckboxList.php
  packages/forms/src/Components/ModalTableSelect.php
  packages/forms/src/Components/Radio.php
  packages/forms/src/Components/Select.php
  packages/forms/src/Components/TableSelect.php
  packages/forms/src/Components/ToggleButtons.php
Labels: bug

#17813 fix: String state cast enum support
  packages/schemas/src/Components/StateCasts/StringArrayStateCast.php
  packages/schemas/src/Components/StateCasts/StringStateCast.php
Labels: bug

#17729 [3.x] Add repeater item numbers
  packages/forms/docs/03-fields/12-repeater.md
  packages/forms/resources/views/components/repeater/index.blade.php
  packages/forms/src/Components/Repeater.php
Labels: enhancement

#17812 [4.x] Add repeater item numbers
  packages/forms/resources/views/components/repeater/index.blade.php
Labels: enhancement

#17826 fix: Deferred query builder
  packages/forms/src/Components/Builder.php
  packages/forms/src/Components/Repeater.php
  packages/tables/src/Concerns/HasFilters.php
  packages/tables/src/Contracts/HasTable.php
  packages/tables/src/Filters/Concerns/BelongsToTable.php
  packages/tables/src/Filters/QueryBuilder.php
  packages/tables/src/Filters/QueryBuilder/Forms/Components/RuleBuilder.php
Labels: bug

#17834 fix: Merge action arguments without overwriting
  packages/actions/src/Concerns/InteractsWithActions.php
  packages/actions/src/Testing/TestsActions.php
Labels: bug

#17835 Allow html in table grouping label and title
  packages/tables/src/Grouping/Group.php
Labels: enhancement

#17830 fix: handle 'as' alias in orderBy correctly in Select component
  packages/forms/src/Components/CheckboxList.php
  packages/forms/src/Components/Select.php
  packages/tables/src/Columns/SelectColumn.php
  packages/tables/src/Filters/SelectFilter.php
Labels: bug

#17829 Make TextInput type range, visible
  packages/panels/dist/fonts/inter/inter-cyrillic-ext-wght-normal-IYF56FF6.woff2
  packages/panels/dist/fonts/inter/inter-cyrillic-wght-normal-JEOLYBOO.woff2
  packages/panels/dist/fonts/inter/inter-greek-ext-wght-normal-EOVOK2B5.woff2
  packages/panels/dist/fonts/inter/inter-greek-wght-normal-IRE366VL.woff2
  packages/panels/dist/theme.css
  packages/support/resources/css/components/input/index.css
Labels: bug, ui

#17440 Mime type and file size validation
  packages/forms/dist/components/file-upload.js
  packages/forms/dist/components/rich-editor.js
  packages/forms/docs/10-rich-editor.md
  packages/forms/docs/11-markdown-editor.md
  packages/forms/resources/css/components/rich-editor.css
  packages/forms/resources/js/components/file-upload.js
  packages/forms/resources/js/components/rich-editor.js
  packages/forms/resources/js/components/rich-editor/extension-local-files.js
  packages/forms/resources/js/components/rich-editor/extensions.js
  packages/forms/resources/lang/en/components.php
  packages/forms/resources/views/components/markdown-editor.blade.php
  packages/forms/resources/views/components/rich-editor.blade.php
  packages/forms/src/Components/Concerns/HasFileAttachments.php
  packages/forms/src/Components/RichEditor/Actions/AttachFilesAction.php
  packages/panels/dist/theme.css
  packages/tables/src/Grouping/Group.php
Labels: enhancement

#17850 Update missing spanish translations
  packages/forms/resources/lang/es/components.php
Labels: i18n

#17853 Fix: Use getAuthPasswordName() and getRememberTokenName() instead of hardcoded field names
  packages/panels/src/Auth/Pages/PasswordReset/ResetPassword.php
Labels: bug

#17355 Add action render hooks
  docs/09-advanced/01-render-hooks.md
  packages/actions/resources/views/action-modal.blade.php
  packages/actions/src/View/ActionsRenderHook.php
  packages/support/src/Facades/FilamentView.php
Labels: enhancement

#17825 fix: unset contain property for modals with file upload editor
  packages/actions/src/ActionGroup.php
  packages/actions/src/Concerns/HasDropdown.php
  packages/forms/resources/views/components/file-upload.blade.php
  packages/panels/dist/theme.css
  packages/support/resources/css/components/modal.css
  packages/support/resources/views/components/modal/index.blade.php
  packages/tables/src/Table/Concerns/HasRecordActions.php
Labels: bug

#17419 feat(tables): add scrollToTop() to auto-scroll after pagination
  packages/tables/dist/index.js
  packages/tables/resources/js/components/table.js
  packages/tables/src/Concerns/HasBulkActions.php
  packages/tables/src/Concerns/InteractsWithTable.php
  packages/tables/src/Table/Concerns/CanPaginateRecords.php
Labels: enhancement

#17426 [4.x] feat: Added three new functions to SpatieMediaLibraryFileAttachmentProvider to customize media and their attributes
  packages/spatie-laravel-media-library-plugin/README.md
  packages/spatie-laravel-media-library-plugin/src/Forms/Components/RichEditor/FileAttachmentProviders/SpatieMediaLibraryFileAttachmentProvider.php
Labels: enhancement

#17437 [4.x] Feat: Add RawHtmlMergeTagExtension for rendering unescaped HTML merge tags in rich editor
  packages/forms/docs/10-rich-editor.md
  packages/forms/src/Components/RichEditor/RichContentRenderer.php
  packages/forms/src/Components/RichEditor/TipTapExtensions/RawHtmlMergeTagExtension.php
  tests/src/Forms/Components/RichEditor/RawHtmlMergeTagExtensionTest.php
  tests/src/Forms/Components/RichEditor/RichContentRendererTest.php
Labels: enhancement

#17548 feat(auth): add autocomplete attributes to form inputs
  packages/panels/src/Auth/Pages/EditProfile.php
  packages/panels/src/Auth/Pages/PasswordReset/ResetPassword.php
Labels: enhancement

#17860 [4.x] Fix: Live updating non native DateTimePicker Component on hasDate, hasTime, and hasSeconds
  packages/forms/resources/views/components/date-time-picker.blade.php
Labels: bug

#17861 fix: Relative user avatar URLs
  packages/panels/src/FilamentManager.php
Labels: bug

#17863 fix: vertical overflow issue,remove unnecessary relative positioning from builder item content
  packages/forms/resources/css/components/builder.css
  packages/panels/dist/theme.css
Labels: bug

#17457 [4.x] Update rich text editor to support merge tags with labels
  packages/forms/dist/components/rich-editor.js
  packages/forms/docs/10-rich-editor.md
  packages/forms/resources/js/components/rich-editor/extension-merge-tag.js
  packages/forms/resources/js/components/rich-editor/extensions.js
  packages/forms/resources/js/components/rich-editor/merge-tag-suggestion.js
  packages/forms/resources/views/components/rich-editor.blade.php
  packages/forms/src/Components/RichEditor.php
  packages/forms/src/Components/RichEditor/RichContentAttribute.php
Labels: enhancement

#17578 feat: add global registration for Chart.js plugins and update documen…
  packages/widgets/dist/components/chart.js
  packages/widgets/docs/03-charts.md
  packages/widgets/resources/js/components/chart.js
Labels: enhancement

#17868 Markdown editor should sanitize HTML after parsing markdown
  packages/forms/resources/views/components/markdown-editor.blade.php
Labels: bug

#17874 Fix keyboard navigation issues with markdown editors
  packages/forms/dist/components/markdown-editor.js
  packages/forms/resources/js/components/markdown-editor/EasyMDE.js
Labels: bug

#17875 [4.x] Add key to form actions content component for use with testing
  packages/panels/src/Auth/Pages/EditProfile.php
  packages/panels/src/Auth/Pages/Login.php
  packages/panels/src/Auth/Pages/PasswordReset/RequestPasswordReset.php
  packages/panels/src/Auth/Pages/PasswordReset/ResetPassword.php
  packages/panels/src/Auth/Pages/Register.php
  packages/panels/src/Pages/Tenancy/EditTenantProfile.php
  packages/panels/src/Pages/Tenancy/RegisterTenant.php
  packages/panels/src/Resources/Pages/CreateRecord.php
  packages/panels/src/Resources/Pages/EditRecord.php
  packages/spatie-laravel-settings-plugin/src/Pages/SettingsPage.php
Labels: enhancement

#17862 Force render to bypass partial rendering
  packages/actions/src/Concerns/InteractsWithActions.php
  packages/actions/src/CreateAction.php
  packages/support/src/Livewire/Partials/PartialsComponentHook.php
  tests/src/Fixtures/Models/Department.php
  tests/src/Fixtures/Resources/Departments/Schemas/DepartmentForm.php
  tests/src/Fixtures/Resources/Tickets/RelationManagers/DepartmentsRelationManager.php
  tests/src/Panels/Resources/RelationManagerTest.php
Labels: enhancement

#17661 [4.x] Feat: rich editor grid extension
  package-lock.json
  packages/forms/dist/components/rich-editor.js
  packages/forms/docs/10-rich-editor.md
  packages/forms/resources/css/components/rich-editor.css
  packages/forms/resources/js/components/rich-editor/extension-grid-column.js
  packages/forms/resources/js/components/rich-editor/extension-grid.js
  packages/forms/resources/js/components/rich-editor/extensions.js
  packages/forms/resources/lang/en/components.php
  packages/forms/src/Components/RichEditor.php
  packages/forms/src/Components/RichEditor/Actions/GridAction.php
  packages/forms/src/Components/RichEditor/RichContentRenderer.php
  packages/forms/src/Components/RichEditor/RichEditorTool.php
  packages/forms/src/Components/RichEditor/TipTapExtensions/DetailsContentExtension.php
  packages/forms/src/Components/RichEditor/TipTapExtensions/GridColumnExtension.php
  packages/forms/src/Components/RichEditor/TipTapExtensions/GridExtension.php
  packages/forms/src/Components/RichEditor/TipTapExtensions/LeadExtension.php
  packages/panels/dist/theme.css
  packages/support/resources/css/utilities.css
  packages/support/resources/svg/o-columns-delete.svg
  packages/support/resources/svg/o-columns.svg
  packages/support/src/SupportServiceProvider.php
Labels: enhancement

#17883 fix: typo in 02-installation.md
  docs/01-introduction/02-installation.md
Labels: documentation

#17888 Rich editor text color
  packages/forms/dist/components/rich-editor.js
  packages/forms/docs/10-rich-editor.md
  packages/forms/resources/css/components/rich-editor.css
  packages/forms/resources/js/components/rich-editor.js
  packages/forms/resources/js/components/rich-editor/extension-text-color.js
  packages/forms/resources/js/components/rich-editor/extensions.js
  packages/forms/resources/lang/en/components.php
  packages/forms/resources/views/components/rich-editor.blade.php
  packages/forms/src/Components/RichEditor.php
  packages/forms/src/Components/RichEditor/Actions/TextColorAction.php
  packages/forms/src/Components/RichEditor/RichContentAttribute.php
  packages/forms/src/Components/RichEditor/RichContentRenderer.php
  packages/forms/src/Components/RichEditor/TextColor.php
  packages/forms/src/Components/RichEditor/TipTapExtensions/TextColorExtension.php
  packages/panels/dist/theme.css
  packages/support/resources/css/utilities.css
  packages/support/src/SupportServiceProvider.php
Labels: enhancement

#17898 fix: Avatar data URIs
  packages/panels/src/FilamentManager.php
Labels: bug

#17687 [4.x] feat: ModalTableSelect badge() and badgeColor()
  packages/forms/docs/03-select.md
  packages/forms/resources/views/components/modal-table-select.blade.php
  packages/forms/src/Components/ModalTableSelect.php
Labels: enhancement

#17756 feat: add affix support to TextInputColumn
  packages/tables/docs/02-columns/08-text-input.md
  packages/tables/src/Columns/TextInputColumn.php
Labels: enhancement

#17902 fix: Option keys starting with 0
  packages/schemas/src/Components/StateCasts/OptionStateCast.php
  packages/schemas/src/Components/StateCasts/OptionsArrayStateCast.php
Labels: bug

#17709 fix interactive table column event bubbling and wire:navigate nested clicks
  packages/support/src/helpers.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Columns/CheckboxColumn.php
  packages/tables/src/Columns/Column.php
  packages/tables/src/Columns/TextInputColumn.php
  packages/tables/src/Columns/ToggleColumn.php
  tests/src/Support/SpaModeTest.php
Labels: bug

#17929 docs: fix typo
  packages/actions/docs/11-import.md
Labels: bug

#17930 fix: Do not fetch option labels for blank state
  packages/forms/src/Components/ModalTableSelect.php
  packages/forms/src/Components/Select.php
  packages/tables/src/Columns/SelectColumn.php
Labels: bug

#17932 feature: Empty state
  docs-assets/app/app/Livewire/Schemas/LayoutDemo.php
  docs-assets/screenshots/images/dark/schemas/layout/empty-state/simple.jpg
  docs-assets/screenshots/images/light/schemas/layout/empty-state/simple.jpg
  docs-assets/screenshots/schema.js
  docs/12-components/01-overview.md
  docs/12-components/03-empty-state.md
  packages/panels/dist/theme.css
  packages/schemas/docs/01-overview.md
  packages/schemas/docs/02-layouts.md
  packages/schemas/docs/06-empty-states.md
  packages/schemas/docs/07-primes.md
  packages/schemas/docs/08-custom-components.md
  packages/schemas/resources/views/components/empty-state.blade.php
  packages/schemas/src/Components/EmptyState.php
  packages/support/resources/css/components/empty-state.css
  packages/support/resources/css/index.css
  packages/support/resources/views/components/empty-state.blade.php
Labels: enhancement

#17934 [3.x] Backport: Fix: keyboard navigation issues with markdown editors
  packages/forms/dist/components/markdown-editor.js
  packages/forms/resources/js/components/markdown-editor/EasyMDE.js
Labels: bug

#17937 fix: exception when using hasBlockPreviews in Builder component
  packages/forms/src/Components/Builder.php
  packages/tables/src/Columns/TextColumn.php
Labels: bug

#17946 fix: Flex JS visibility
  packages/schemas/resources/views/components/flex.blade.php
Labels: bug

#17920 feat: add support for default collapsed grouping in table records.
  packages/tables/dist/index.js
  packages/tables/docs/07-grouping.md
  packages/tables/resources/js/components/table.js
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Table/Concerns/CanGroupRecords.php
Labels: enhancement

#17954 Restore hint icon color functionality
  packages/forms/src/Components/Concerns/HasHint.php
  packages/infolists/src/Components/Concerns/HasHint.php
Labels: bug

#17956 fix: error when only resources are configured for multi-tenancy and the authenticated user has no tenant
  packages/panels/src/Panel/Concerns/HasRoutes.php
Labels: bug

#17959 Added missing French translations
  packages/panels/resources/lang/fr/resources/pages/edit-record.php
  packages/panels/resources/lang/fr/resources/pages/manage-related-records.php
  packages/panels/resources/lang/fr/resources/pages/view-record.php
Labels: i18n

#17968 Move navigation loading inside of conditional for top navigation
  packages/panels/resources/views/livewire/topbar.blade.php
  packages/support/resources/views/components/pagination/item.blade.php
Labels: bug

#17979 Update request-password-reset.php
  packages/panels/resources/lang/lv/pages/auth/password-reset/request-password-reset.php
Labels: i18n

#17971 History state fix
  packages/panels/dist/index.js
  packages/panels/resources/js/history-state.js
Labels: bug

#18003 fix: resources overview docs typo
  docs/03-resources/01-overview.md
Labels: documentation
