Repository filamentphp/filament, pull requests merged in 2025-05, with the labels that each got.

#16192 Code editor
  bin/build.js
  composer.json
  composer.lock
  docs-assets/app/app/Livewire/Forms/FieldsDemo.php
  docs-assets/app/app/Livewire/Infolists/EntriesDemo.php
  docs-assets/app/composer.lock
  docs-assets/screenshots/images/dark/forms/fields/code-editor/simple.jpg
  docs-assets/screenshots/images/dark/infolists/entries/code/dracula.jpg
  docs-assets/screenshots/images/dark/infolists/entries/code/simple.jpg
  docs-assets/screenshots/images/light/forms/fields/code-editor/simple.jpg
  docs-assets/screenshots/images/light/infolists/entries/code/dracula.jpg
  docs-assets/screenshots/images/light/infolists/entries/code/simple.jpg
  docs-assets/screenshots/schema.js
  package-lock.json
  package.json
  packages/forms/dist/components/code-editor.js
  packages/forms/dist/components/rich-editor.js
  packages/forms/docs/01-overview.md
  packages/forms/docs/20-code-editor.md
  packages/forms/docs/21-hidden.md
  packages/forms/docs/22-custom-fields.md
  packages/forms/docs/23-validation.md
  packages/forms/resources/css/components/code-editor.css
  packages/forms/resources/css/index.css
  packages/forms/resources/js/components/code-editor.js
  packages/forms/resources/views/components/code-editor.blade.php
  packages/forms/src/Components/CodeEditor.php
  packages/forms/src/FormsServiceProvider.php
  packages/infolists/composer.json
  packages/infolists/docs/01-overview.md
  packages/infolists/docs/05-color-entry.md
  packages/infolists/docs/06-code-entry.md
  packages/infolists/docs/07-key-value-entry.md
  packages/infolists/docs/08-repeatable-entry.md
  packages/infolists/docs/09-custom-entries.md
  packages/infolists/resources/css/components/code.css
  packages/infolists/resources/css/index.css
  packages/infolists/src/Components/CodeEntry.php
  packages/panels/dist/theme.css
  packages/schemas/docs/01-overview.md
  packages/support/resources/css/components/input/wrapper.css
Labels: enhancement

#16191 Fix top bar persistence issues
  packages/panels/resources/views/livewire/topbar.blade.php
Labels: bug

#16187 Update 03-tenancy.md
  docs/07-users/03-tenancy.md
Labels: documentation

#16190 Include another package in filament:about command
  packages/support/src/SupportServiceProvider.php
Labels: bug

#16193 Backport topbar fix to 3.x
  packages/panels/resources/views/components/topbar/index.blade.php
Labels: bug

#16196 fix: prevent error when calling non-existent getTagClassName method
  packages/spatie-laravel-tags-plugin/src/Forms/Components/SpatieTagsInput.php
Labels: bug

#16194 Add `->userMenu()` for disabling user menu
  docs/06-navigation/03-user-menu.md
  packages/panels/resources/views/components/layout/simple.blade.php
  packages/panels/resources/views/livewire/topbar.blade.php
  packages/panels/src/Facades/Filament.php
  packages/panels/src/FilamentManager.php
  packages/panels/src/Panel/Concerns/HasUserMenu.php
Labels: enhancement

#16208 fix(dependencies): match `composer.lock` laravel version with `composer.json`
  composer.lock
  docs-assets/app/composer.lock
Labels: bug

#16223 Update translatable link
  docs/14-upgrade-guide.md
  packages/forms/src/Components/Builder/Block.php
  packages/forms/src/Components/MorphToSelect.php
Labels: documentation

#16228 Update 04-delete.md - Redirecting after deleting
  packages/actions/docs/07-prebuilt-actions/04-delete.md
Labels: documentation

#16232 Add size param to Blade icon
  packages/support/resources/views/components/icon.blade.php
Labels: enhancement

#16224 Fix static data table action exception
  packages/forms/src/Components/Select.php
  packages/schemas/src/Components/Concerns/HasActions.php
Labels: bug

#16230 Gate password reset process with canAccessPanel logic
  packages/panels/resources/lang/en/pages/auth/password-reset/request-password-reset.php
  packages/panels/src/Pages/Auth/PasswordReset/RequestPasswordReset.php
  packages/panels/src/Pages/Auth/PasswordReset/ResetPassword.php
  tests/src/Panels/Auth/PasswordReset/RequestPasswordResetTest.php
  tests/src/Panels/Auth/PasswordReset/ResetPasswordTest.php
Labels: bug

#16238 Docs V4 - Table - external api actions
  packages/actions/docs/02-modals.md
  packages/tables/docs/09-static-data.md
Labels: documentation

#16130 feat: support Redirector type in Logout response
  packages/panels/src/Http/Responses/Auth/LogoutResponse.php
Labels: bug

#16246 bugfix: Tenant menu icon blade component needs to use alias instead of icon-alias
  packages/panels/resources/views/components/tenant-menu.blade.php
Labels: bug

#16255 v4 Add destroy method to slider.js (fix SPA mode duplication issue)
  packages/forms/dist/components/slider.js
  packages/forms/resources/js/components/slider.js
Labels: bug

#16265 Add missing `$record` to the `.stubs.php` for table testing
  packages/tables/.stubs.php
Labels: bug

#16264 Docs: fix examples for testing table helpers
  packages/tables/docs/12-testing.md
Labels: documentation

#16271 Disable step button if previous action is disabled
  packages/forms/resources/views/components/wizard.blade.php
Labels: bug

#16274 Fix: total rows calculation for group by in CanExportRecords trait
  packages/actions/src/Concerns/CanExportRecords.php
Labels: bug

#16279 Table repeater
  docs-assets/app/app/Livewire/Forms/FieldsDemo.php
  docs-assets/app/public/js/filament/forms/components/slider.js
  docs-assets/screenshots/images/dark/forms/fields/repeater/table.jpg
  docs-assets/screenshots/images/light/forms/fields/repeater/table.jpg
  docs-assets/screenshots/schema.js
  packages/forms/docs/12-repeater.md
  packages/forms/resources/css/components/repeater.css
  packages/forms/resources/views/components/repeater/simple.blade.php
  packages/forms/resources/views/components/repeater/table.blade.php
  packages/forms/src/Components/Repeater.php
  packages/forms/src/Components/Repeater/TableColumn.php
  packages/panels/dist/theme.css
  packages/schemas/resources/views/components/wizard.blade.php
  packages/support/src/Concerns/CanWrapHeader.php
  packages/support/src/Concerns/HasWidth.php
  packages/tables/src/Columns/Column.php
  packages/tables/src/Columns/ColumnGroup.php
Labels: enhancement

#16262 fix(infolists): avoid unnecessary spacing when no label content is used
  packages/forms/resources/views/components/field-wrapper.blade.php
  packages/infolists/src/Components/Entry.php
Labels: bug

#16296 Added missing spanish translation.
  packages/panels/resources/lang/es/pages/auth/password-reset/request-password-reset.php
Labels: i18n

#16295 Hidden fields incorrectly dehydrated in Section with state path
  packages/forms/src/Components/Concerns/HasState.php
  packages/forms/src/Concerns/HasState.php
  tests/src/Forms/StateTest.php
Labels: bug

#16300 Add Greek (el) locale to date picker component
  packages/forms/resources/js/components/date-time-picker.js
  packages/forms/resources/lang/el/components.php
  packages/forms/resources/lang/el/validation.php
Labels: i18n

#16254 feat: ability to evaluate Closures in `viewData()`
  packages/notifications/src/Notification.php
  packages/support/src/Components/ViewComponent.php
  tests/src/Forms/Components/ViewTest.php
Labels: enhancement

#16293 Correct discover_app_classes for Windows paths
  packages/support/src/helpers.php
Labels: bug

#16247 Optional HTML validation messages
  packages/forms/docs/23-validation.md
  packages/forms/resources/views/components/field-wrapper.blade.php
  packages/forms/src/Components/Concerns/CanBeValidated.php
Labels: enhancement

#16308 Required fieldset
  packages/forms/resources/views/components/fieldset.blade.php
  packages/forms/src/Components/Fieldset.php
  packages/forms/src/Components/MorphToSelect.php
  packages/support/resources/views/components/fieldset.blade.php
Labels: enhancement

#16310 chore: improved docs a bit
  packages/forms/docs/08-adding-a-form-to-a-livewire-component.md
Labels: documentation

#16315 Update vi translations
  packages/forms/resources/lang/vi/components.php
  packages/panels/resources/lang/vi/pages/auth/password-reset/request-password-reset.php
Labels: i18n

#16316 Modal table select
  bin/build.js
  packages/forms/docs/03-select.md
  packages/forms/resources/css/components/modal-table-select.css
  packages/forms/resources/css/index.css
  packages/forms/resources/lang/en/components.php
  packages/forms/resources/views/components/livewire-field.blade.php
  packages/forms/resources/views/components/modal-table-select.blade.php
  packages/forms/resources/views/components/table-select.blade.php
  packages/forms/src/Components/LivewireField.php
  packages/forms/src/Components/ModalTableSelect.php
  packages/forms/src/Components/TableSelect.php
  packages/forms/src/Components/TableSelect/Livewire/TableSelectLivewireComponent.php
  packages/forms/src/FormsServiceProvider.php
  packages/panels/dist/theme.css
  packages/support/src/View/Components/BadgeComponent.php
  packages/tables/dist/components/table.js
  packages/tables/dist/index.js
  packages/tables/resources/js/components/table.js
  packages/tables/resources/js/index.js
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Concerns/CanSortRecords.php
  packages/tables/src/Table/Concerns/HasBulkActions.php
  packages/tables/src/TablesServiceProvider.php
  tests/.pest/snapshots/src/Support/ColorTest/it_generates_component_classes_with_data_set__dataset__badge______primary______Filament_Support_View_Compone___ponent____primary__.snap
  tests/.pest/snapshots/src/Support/ColorTest/it_generates_component_classes_with_data_set__dataset__badge______success______Filament_Support_View_Compone___ponent____success__.snap
  tests/.pest/snapshots/src/Support/ColorTest/it_generates_component_classes_with_data_set__dataset__badge______warning______Filament_Support_View_Compone___ponent____warning__.snap
Labels: enhancement

#16318 Global timezone config
  packages/forms/docs/08-date-time-picker.md
  packages/forms/src/Components/DateTimePicker.php
  packages/infolists/docs/02-text-entry.md
  packages/infolists/src/Components/Concerns/CanFormatState.php
  packages/support/src/Facades/FilamentTimezone.php
  packages/support/src/TimezoneManager.php
  packages/tables/docs/02-columns/02-text.md
  packages/tables/src/Columns/Concerns/CanFormatState.php
Labels: enhancement

#16317 add missing type variables for eloquent-builder
  packages/actions/src/Exports/Exporter.php
  packages/schemas/src/Components/Tabs/Tab.php
  packages/spatie-laravel-media-library-plugin/src/Tables/Columns/SpatieMediaLibraryImageColumn.php
  packages/spatie-laravel-tags-plugin/src/Tables/Columns/SpatieTagsColumn.php
  packages/support/src/Contracts/TranslatableContentDriver.php
  packages/tables/src/Filters/QueryBuilder.php
  packages/tables/src/Filters/QueryBuilder/Constraints/BooleanConstraint/Operators/IsTrueOperator.php
  packages/tables/src/Filters/SelectFilter.php
Labels: chore

#16327 Select empty option
  packages/forms/src/Components/Select.php
  packages/tables/docs/03-filters/02-select.md
  packages/tables/resources/lang/en/table.php
  packages/tables/src/Filters/Concerns/HasRelationship.php
  packages/tables/src/Filters/SelectFilter.php
Labels: enhancement

#16332 feat: Resource redirect config
  docs/03-resources/03-creating-records.md
  docs/03-resources/04-editing-records.md
  packages/panels/src/Facades/Filament.php
  packages/panels/src/FilamentManager.php
  packages/panels/src/Panel/Concerns/HasComponents.php
  packages/panels/src/Resources/Pages/CreateRecord.php
  packages/panels/src/Resources/Pages/EditRecord.php
Labels: enhancement

#16333 feature: Error notifications
  docs/05-panel-configuration.md
  packages/panels/resources/lang/en/error-notifications.php
  packages/panels/resources/views/components/page/index.blade.php
  packages/panels/src/Facades/Filament.php
  packages/panels/src/FilamentManager.php
  packages/panels/src/Pages/Concerns/HasErrorNotifications.php
  packages/panels/src/Pages/Page.php
  packages/panels/src/Panel.php
  packages/panels/src/Panel/Concerns/HasErrorNotifications.php
Labels: enhancement

#16338 feat(ChartWidget): add collapsible property
  packages/widgets/docs/03-charts.md
  packages/widgets/resources/views/chart-widget.blade.php
  packages/widgets/src/ChartWidget.php
Labels: enhancement

#16340 fix: State dehydration with non-unique fields
  packages/forms/src/Components/Concerns/HasState.php
  packages/forms/src/Concerns/HasState.php
  tests/src/Forms/StateTest.php
Labels: bug

#16348 Text entry relationship aggregation
  packages/infolists/docs/02-text-entry.md
  packages/infolists/src/Components/TextEntry.php
Labels: enhancement

#16324 Fix Select relationship field generating empty Rule::in() when using JSON key in title (e.g., 'name->en')
  packages/forms/src/Components/Select.php
Labels: bug

#16353 4.x - allowPaste opton for FileUpload restored
  package-lock.json
  package.json
  packages/forms/docs/09-file-upload.md
  packages/forms/resources/js/components/file-upload.js
  packages/forms/resources/views/components/file-upload.blade.php
  packages/forms/src/Components/BaseFileUpload.php
Labels: enhancement

#16350 remove duplicate style conditionals
  packages/infolists/resources/views/components/image-entry.blade.php
  packages/tables/resources/views/columns/image-column.blade.php
Labels: bug

#16359 Update missing translations in forms/resources/lang/fr/components.php
  packages/forms/resources/lang/fr/components.php
Labels: i18n

#16367 Adding limit when searchable is true for Select Form Field
  packages/forms/src/Components/Select.php
Labels: bug
