Repository filamentphp/filament, pull requests merged in 2025-10, with the labels that each got.

#18027 Update spanish translations for filament 4.1
  packages/forms/resources/lang/es/components.php
Labels: i18n

#18042 Add missing Japanese translations for Profile page
  packages/panels/resources/lang/ja/auth/pages/edit-profile.php
Labels: i18n

#18024 [4.x] Fix native DateTimePicker format handling for date-time without seconds
  packages/forms/src/Components/DateTimePicker.php
  tests/src/Forms/Components/DateTimePickerTest.php
Labels: bug

#18011 Fix spa cmd click to open in new window
  packages/support/src/helpers.php
  tests/src/Support/SpaModeTest.php
Labels: bug

#18052 fix: Model methods clashing with attribute names
  packages/support/src/Concerns/HasCellState.php
Labels: bug

#18055 fix: Action badge background leakage
  packages/panels/dist/theme.css
  packages/support/resources/css/components/button.css
  packages/support/resources/css/components/icon-button.css
  packages/support/resources/css/components/link.css
Labels: bug

#18058 fix: Nested relationship sorting
  packages/tables/src/Columns/Concerns/InteractsWithTableQuery.php
  packages/tables/src/Grouping/Group.php
Labels: bug

#18056 [Testing] Fix enum handling in table column state assertions
  packages/tables/src/Testing/TestsColumns.php
Labels: bug

#18061 fix: Relative validation state paths
  packages/forms/src/Components/Concerns/CanBeValidated.php
Labels: bug

#18062 fix: Prose responsive grid
  packages/panels/dist/theme.css
  packages/support/resources/css/utilities.css
Labels: bug

#18063 fix: Passing record to table column view
  packages/support/src/Components/ViewComponent.php
Labels: bug

#18067 fix: Cast state after loading from relationships
  packages/schemas/src/Components/Concerns/BelongsToModel.php
Labels: bug

#18069 fix: Rendering fast select state updates
  packages/forms/dist/components/select.js
  packages/support/resources/js/utilities/select.js
  packages/tables/dist/components/columns/select.js
Labels: bug

#18070 fix: Repeatable entry action record
  packages/actions/src/Concerns/CanBeMounted.php
Labels: bug

#18022 Fix/modal behaviour on close
  packages/support/dist/index.js
  packages/support/resources/js/components/modal.js
  packages/support/resources/views/components/modal/index.blade.php
Labels: bug

#18000 Allow select to be searched without opening dropdown manually
  packages/forms/dist/components/select.js
  packages/support/resources/js/utilities/select.js
  packages/tables/dist/components/columns/select.js
Labels: bug

#18049 Fix/rich editor plugins merge
  packages/forms/dist/components/rich-editor.js
  packages/forms/resources/js/components/rich-editor/extensions.js
Labels: bug

#18072 fix: Wire navigate key bindings
  package-lock.json
  package.json
  packages/panels/dist/index.js
Labels: bug in dependency

#18073 fix: Table row sortable animations
  packages/panels/dist/theme.css
  packages/tables/resources/css/row.css
Labels: bug

#18075 fix: Table toolbar button disabled styling flickers
  packages/panels/dist/theme.css
  packages/support/resources/css/components/badge.css
  packages/support/resources/css/components/button.css
  packages/support/resources/css/components/icon-button.css
  packages/support/resources/css/components/link.css
  packages/tables/src/Table/Concerns/CanGroupRecords.php
  packages/tables/src/Table/Concerns/CanReorderRecords.php
  packages/tables/src/Table/Concerns/HasColumnManager.php
  packages/tables/src/Table/Concerns/HasFilters.php
Labels: bug

#17966 fix(panels/auth): guard EmailVerificationPrompt for guests (redirect or 403)
  packages/panels/src/Auth/Pages/EmailVerification/EmailVerificationPrompt.php
  packages/panels/src/Widgets/AccountWidget.php
  tests/src/Panels/Auth/EmailVerification/EmailVerificationPromptTest.php
Labels: bug

#18077 Fix(TenantDropdown): Tenant dropdown now shows correctly on Safari
  packages/panels/resources/views/components/tenant-menu.blade.php
  packages/panels/resources/views/livewire/topbar.blade.php
Labels: bug

#18076 feat: add onlyAllowGroupSelection() method for group-only bulk selection
  packages/tables/dist/index.js
  packages/tables/docs/04-actions.md
  packages/tables/resources/js/components/table.js
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Table/Concerns/HasBulkActions.php
Labels: enhancement

#18080 feature: Define schema actions in closure
  packages/schemas/src/Components/Actions.php
Labels: enhancement

#18081 feature: Disable builder repeater item headers
  packages/forms/resources/css/components/builder.css
  packages/forms/resources/css/components/repeater.css
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/repeater/index.blade.php
  packages/forms/src/Components/Builder.php
  packages/forms/src/Components/Repeater.php
  packages/panels/dist/theme.css
Labels: enhancement

#18085 fix: Actions inside components without inheritable keys
  packages/schemas/src/Components/Concerns/EntanglesStateWithSingularRelationship.php
  packages/schemas/src/Components/Concerns/HasKey.php
Labels: bug

#18088 fix: Checkbox column click
  packages/tables/src/Columns/CheckboxColumn.php
Labels: bug

#18079 Adjust the input CSS for responsive text sizes on mobile devices
  packages/forms/resources/css/components/textarea.css
  packages/panels/dist/theme.css
  packages/support/resources/css/components/input/index.css
  packages/support/resources/css/components/input/select.css
Labels: ui

#18094 Adding remaining pt_BR translations
  packages/forms/resources/lang/pt_BR/components.php
  packages/panels/resources/lang/pt_BR/layout.php
  translators.csv
Labels: i18n

#18095 Added missing Dutch translations for the tenant menu search
  packages/panels/resources/lang/nl/layout.php
Labels: i18n

#18101 [4.x] Fix: DetailsContentExtension.php parseHTML error
  packages/forms/src/Components/RichEditor/TipTapExtensions/DetailsContentExtension.php
Labels: bug

#18113 fix: Sorting and grouping relationships with null values
  packages/tables/src/Columns/Concerns/InteractsWithTableQuery.php
  packages/tables/src/Concerns/HasBulkActions.php
  packages/tables/src/Grouping/Group.php
Labels: bug

#18091 Dispatch events during record lifecycle (`Created`, `Creating`, `Saved`, `Saving`) and add related tests.
  packages/actions/src/Concerns/InteractsWithActions.php
  packages/panels/src/Resources/Events/RecordCreated.php
  packages/panels/src/Resources/Events/RecordSaved.php
  packages/panels/src/Resources/Events/RecordUpdated.php
  packages/panels/src/Resources/Pages/Concerns/InteractsWithRecord.php
  packages/panels/src/Resources/Pages/CreateRecord.php
  packages/panels/src/Resources/Pages/EditRecord.php
  packages/panels/src/Resources/Pages/Page.php
  tests/src/Panels/Resources/Pages/CreateRecordTest.php
  tests/src/Panels/Resources/Pages/EditRecordTest.php
Labels: enhancement

#18115 Hide hamburger icon when not needed
  packages/panels/resources/views/components/layout/index.blade.php
Labels: bug

#18121 fix: Dropdown and select positioning and z-index issues
  packages/forms/dist/components/select.js
  packages/forms/resources/views/components/repeater/table.blade.php
  packages/panels/dist/theme.css
  packages/support/resources/css/components/dropdown/index.css
  packages/support/resources/js/utilities/select.js
  packages/tables/dist/components/columns/select.js
  packages/tables/resources/views/index.blade.php
Labels: bug

#18123 fix: Charts with max height set should not have an aspect ratio
  packages/panels/dist/theme.css
  packages/widgets/resources/css/chart-widget.css
  packages/widgets/resources/views/chart-widget.blade.php
Labels: bug

#18127 Add missing SQL language for code-editor
  package-lock.json
  package.json
  packages/forms/dist/components/code-editor.js
  packages/forms/docs/20-code-editor.md
  packages/forms/resources/js/components/code-editor.js
  packages/forms/src/Components/CodeEditor/Enums/Language.php
Labels: enhancement
