Repository filamentphp/filament, pull requests merged in 2025-02, with the labels that each got.

#15493 Hide Wizard Action buttons using x-bind:class instead of x-show so it…
  packages/forms/resources/views/components/wizard.blade.php
Labels: bug

#15506 Refactor badge slots
  packages/support/resources/views/components/button/index.blade.php
  packages/support/resources/views/components/dropdown/list/item.blade.php
  packages/support/resources/views/components/icon-button.blade.php
  packages/support/resources/views/components/link.blade.php
  packages/support/resources/views/components/tabs/item.blade.php
Labels: enhancement

#14996 fix: allow `MaxWidth` enum instance
  packages/panels/src/Pages/Concerns/HasMaxWidth.php
  packages/upgrade/bin/filament-v4
  packages/upgrade/src/Rector/SimplePropertyChangesRector.php
Labels: enhancement, awaiting next major version

#14157 Database Notifications - Customizable "Mark All as Read" Action
  packages/notifications/resources/views/components/database/modal/actions.blade.php
  packages/notifications/resources/views/components/database/modal/index.blade.php
  packages/notifications/resources/views/database-notifications.blade.php
  packages/notifications/src/Livewire/DatabaseNotifications.php
  packages/panels/src/Panel/Concerns/HasComponents.php
  packages/panels/src/Panel/Concerns/HasNotifications.php
Labels: enhancement, awaiting next major version

#14185 Add Trix Toolbar Button Subscript & Superscript
  packages/forms/docs/02-fields/10-rich-editor.md
  packages/forms/resources/js/components/rich-editor.js
  packages/forms/resources/lang/en/components.php
  packages/forms/resources/views/components/rich-editor.blade.php
  packages/forms/src/Components/RichEditor.php
Labels: enhancement, awaiting next major version

#14276 Add feature to show date with iso format in Table & Infolist
  packages/infolists/docs/02-entries/02-text.md
  packages/infolists/src/Components/Concerns/CanFormatState.php
  packages/schemas/src/Schema.php
  packages/tables/docs/02-columns/02-text.md
  packages/tables/src/Columns/Concerns/CanFormatState.php
  packages/tables/src/Table.php
Labels: enhancement, awaiting next major version

#14419 Added markdown extensions support
  packages/forms/resources/views/components/markdown-editor.blade.php
  packages/forms/src/Components/MarkdownEditor.php
  packages/infolists/src/Components/Concerns/CanFormatState.php
  packages/support/src/Concerns/CanConfigureCommonMark.php
  packages/tables/src/Columns/Concerns/CanFormatState.php
  packages/tables/src/Columns/Summarizers/Concerns/CanFormatState.php
Labels: enhancement, awaiting next major version

#15109 Panels navigation documentation
  docs-assets/app/app/Livewire/Panels/Navigation/ActiveIcon.php
  docs-assets/app/app/Livewire/Panels/Navigation/Badge.php
  docs-assets/app/app/Livewire/Panels/Navigation/BadgeColor.php
  docs-assets/app/app/Livewire/Panels/Navigation/BadgeTooltip.php
  docs-assets/app/app/Livewire/Panels/Navigation/ChangeIcon.php
  docs-assets/app/app/Livewire/Panels/Navigation/CustomItems.php
  docs-assets/app/app/Livewire/Panels/Navigation/DisabledNavigation.php
  docs-assets/app/app/Livewire/Panels/Navigation/Group.php
  docs-assets/app/app/Livewire/Panels/Navigation/GroupCollapsible.php
  docs-assets/app/app/Livewire/Panels/Navigation/GroupNotCollapsible.php
  docs-assets/app/app/Livewire/Panels/Navigation/SidebarCollapsibleOnDesktop.php
  docs-assets/app/app/Livewire/Panels/Navigation/SidebarFullyCollapsibleOnDesktop.php
  docs-assets/app/app/Livewire/Panels/Navigation/SortItems.php
  docs-assets/app/app/Livewire/Panels/Navigation/TopNavigation.php
  docs-assets/app/app/Livewire/Panels/Navigation/UserMenuCustomization.php
  docs-assets/app/database/factories/PostFactory.php
  docs-assets/app/database/factories/UserFactory.php
  docs-assets/app/resources/views/livewire/actions.blade.php
  docs-assets/app/resources/views/livewire/panels/navigation/empty.blade.php
  docs-assets/app/routes/web.php
  docs-assets/screenshots/images/dark/panels/navigation/active-icon.jpg
  docs-assets/screenshots/images/dark/panels/navigation/badge-color.jpg
  docs-assets/screenshots/images/dark/panels/navigation/badge-tooltip.jpg
  docs-assets/screenshots/images/dark/panels/navigation/badge.jpg
  docs-assets/screenshots/images/dark/panels/navigation/change-icon.jpg
  docs-assets/screenshots/images/dark/panels/navigation/custom-items.jpg
  docs-assets/screenshots/images/dark/panels/navigation/disabled-navigation.jpg
  docs-assets/screenshots/images/dark/panels/navigation/group-collapsible.jpg
  docs-assets/screenshots/images/dark/panels/navigation/group-not-collapsible.jpg
  docs-assets/screenshots/images/dark/panels/navigation/group.jpg
  docs-assets/screenshots/images/dark/panels/navigation/sidebar-collapsible-on-desktop.jpg
  docs-assets/screenshots/images/dark/panels/navigation/sidebar-fully-collapsible-on-desktop.jpg
  docs-assets/screenshots/images/dark/panels/navigation/sort-items.jpg
  docs-assets/screenshots/images/dark/panels/navigation/top-navigation.jpg
  docs-assets/screenshots/images/light/panels/navigation/active-icon.jpg
  docs-assets/screenshots/images/light/panels/navigation/badge-color.jpg
  docs-assets/screenshots/images/light/panels/navigation/badge-tooltip.jpg
  docs-assets/screenshots/images/light/panels/navigation/badge.jpg
  docs-assets/screenshots/images/light/panels/navigation/change-icon.jpg
  docs-assets/screenshots/images/light/panels/navigation/custom-items.jpg
  docs-assets/screenshots/images/light/panels/navigation/disabled-navigation.jpg
  docs-assets/screenshots/images/light/panels/navigation/group-collapsible.jpg
  docs-assets/screenshots/images/light/panels/navigation/group-not-collapsible.jpg
  docs-assets/screenshots/images/light/panels/navigation/group.jpg
  docs-assets/screenshots/images/light/panels/navigation/sidebar-collapsible-on-desktop.jpg
  docs-assets/screenshots/images/light/panels/navigation/sidebar-fully-collapsible-on-desktop.jpg
  docs-assets/screenshots/images/light/panels/navigation/sort-items.jpg
  docs-assets/screenshots/images/light/panels/navigation/top-navigation.jpg
  docs-assets/screenshots/schema.js
  docs-assets/screenshots/script.js
  packages/panels/docs/06-navigation.md
Labels: documentation

#15139 Resolve exception for search on json columns on a relationship
  packages/actions/src/Exports/ExportColumn.php
  packages/spatie-laravel-media-library-plugin/src/Tables/Columns/SpatieMediaLibraryImageColumn.php
  packages/spatie-laravel-tags-plugin/src/Tables/Columns/SpatieTagsColumn.php
  packages/support/src/Concerns/HasCellState.php
  packages/tables/src/Columns/Concerns/CanBeSearchable.php
  packages/tables/src/Columns/Concerns/CanBeSortable.php
  packages/tables/src/Columns/Concerns/CanUpdateState.php
  packages/tables/src/Columns/Concerns/InteractsWithTableQuery.php
  packages/tables/src/Columns/Summarizers/Summarizer.php
  packages/tables/src/Concerns/CanSummarizeRecords.php
  tests/.pest/snapshots/src/Panels/Commands/Legacy/LegacyMakeResourceCommandTest/it_can_generate_the_form_and_table_of_a_resource_class.snap
  tests/.pest/snapshots/src/Panels/Commands/MakeResourceCommandTest/it_can_generate_the_form_and_table_content_embedded_in_a_resource_class.snap
  tests/.pest/snapshots/src/Panels/Commands/MakeResourceCommandTest/it_can_generate_the_resource_form_content.snap
  tests/database/migrations/create_posts_table.php
  tests/database/migrations/modify_users_table.php
  tests/src/Fixtures/Livewire/PostsTable.php
  tests/src/Fixtures/Models/Post.php
  tests/src/Fixtures/Models/User.php
  tests/src/Tables/ColumnTest.php
Labels: bug, awaiting next major version

#15218 Select field on enum type when using generate
  packages/forms/src/Commands/FileGenerators/Concerns/CanGenerateModelForms.php
  packages/support/src/Commands/Concerns/CanReadModelSchemas.php
  tests/.pest/snapshots/src/Panels/Commands/Legacy/LegacyMakeResourceCommandTest/it_can_generate_the_form_and_table_of_a_resource_class.snap
  tests/.pest/snapshots/src/Panels/Commands/MakeResourceCommandTest/it_can_generate_the_form_and_table_content_embedded_in_a_resource_class.snap
  tests/.pest/snapshots/src/Panels/Commands/MakeResourceCommandTest/it_can_generate_the_resource_form_content.snap
  tests/.pest/snapshots/src/Panels/Commands/MakeResourceCommandTest/it_can_generate_the_resource_table_content.snap
  tests/database/migrations/create_posts_table.php
  tests/src/Fixtures/Models/Post.php
Labels: enhancement, awaiting next major version

#15510 Update attribute for csv filename
  packages/actions/resources/lang/it/import.php
Labels: i18n

#15522 Container queries
  docs-assets/app/public/css/filament/support/support.css
  docs-assets/app/public/js/filament/support/support.js
  packages/actions/resources/views/action-modal.blade.php
  packages/actions/resources/views/components/modals.blade.php
  packages/schemas/resources/views/schema.blade.php
  packages/schemas/src/Components/Component.php
  packages/schemas/src/Components/Concerns/CanBeGridContainer.php
  packages/support/dist/index.css
  packages/support/dist/index.js
  packages/support/resources/css/components/grid.css
  packages/support/resources/css/components/modal.css
  packages/support/resources/css/components/pagination.css
  packages/support/resources/css/components/tables/container.css
  packages/support/resources/js/components/modal.js
  packages/support/resources/js/index.js
  packages/support/src/SupportServiceProvider.php
  packages/widgets/src/StatsOverviewWidget.php
Labels: enhancement

#15514 Fix refreshFormData to update the data correctly using form->fill
  packages/panels/src/Resources/Pages/EditRecord.php
  packages/panels/src/Resources/Pages/ViewRecord.php
Labels: bug

#15542 filament() helper return types
  packages/panels/src/global_helpers.php
Labels: enhancement

#15530 Make ToggleButtons can display only icons
  packages/forms/docs/03-fields/18-toggle-buttons.md
  packages/forms/resources/views/components/toggle-buttons/grouped.blade.php
  packages/forms/resources/views/components/toggle-buttons/index.blade.php
  packages/forms/src/Components/ToggleButtons.php
Labels: enhancement

#15553 Conditionally set title attribute based on tooltip of icon button
  packages/support/resources/views/components/icon-button.blade.php
Labels: ui

#15554 TipTap rich editor
  composer.json
  composer.lock
  docs-assets/app/public/css/filament/filament/app.css
  docs-assets/app/public/css/filament/forms/forms.css
  docs-assets/app/public/css/filament/support/support.css
  docs-assets/app/public/js/filament/forms/components/rich-editor.js
  docs-assets/app/public/js/filament/support/support.js
  package-lock.json
  package.json
  packages/forms/composer.json
  packages/forms/dist/components/rich-editor.js
  packages/forms/dist/index.css
  packages/forms/resources/css/components/rich-editor.css
  packages/forms/resources/js/components/rich-editor.js
  packages/forms/resources/js/components/rich-editor/extension-image.js
  packages/forms/resources/js/components/rich-editor/extension-local-files.js
  packages/forms/resources/js/components/rich-editor/extensions.js
  packages/forms/resources/views/components/rich-editor.blade.php
  packages/forms/resources/views/components/rich-editor/toolbar/button.blade.php
  packages/forms/src/Components/Concerns/HasFileAttachments.php
  packages/forms/src/Components/Contracts/HasFileAttachments.php
  packages/forms/src/Components/RichEditor.php
  packages/forms/src/Components/RichEditor/Actions/AttachFilesAction.php
  packages/forms/src/Components/RichEditor/Actions/LinkAction.php
  packages/forms/src/Components/RichEditor/EditorCommand.php
  packages/forms/src/Components/RichEditor/StateCasts/RichEditorStateCast.php
  packages/forms/src/Components/RichEditor/TipTapExtensions/Image.php
  packages/forms/src/Concerns/InteractsWithForms.php
  packages/panels/dist/theme.css
  packages/schemas/src/Concerns/InteractsWithSchemas.php
  packages/support/dist/index.css
  packages/support/dist/index.js
  packages/support/resources/css/components/input/wrapper.css
  packages/support/resources/js/index.js
Labels: enhancement

#15556 Improve `refreshFormData()` behaviour
  packages/panels/src/Resources/Pages/EditRecord.php
  packages/panels/src/Resources/Pages/ViewRecord.php
  packages/schemas/src/Components/Concerns/HasState.php
  packages/schemas/src/Concerns/HasState.php
  tests/src/Forms/StateTest.php
Labels: bug

#15560 Add notes about incompatibility with Tailwind v4
  packages/actions/docs/01-installation.md
  packages/forms/docs/01-installation.md
  packages/infolists/docs/01-installation.md
  packages/notifications/docs/01-installation.md
  packages/panels/docs/12-themes.md
  packages/panels/src/Commands/MakeThemeCommand.php
  packages/panels/stubs/ThemeCss.stub
  packages/support/src/Commands/InstallCommand.php
  packages/tables/docs/01-installation.md
  packages/widgets/docs/01-installation.md
Labels: documentation, enhancement

#15566 Update Armenian Translation
  packages/forms/resources/lang/hy/components.php
Labels: i18n

#15618 Fix save action type
  packages/panels/docs/03-resources/04-editing-records.md
Labels: documentation

#15614 Add ability to hook into a clone
  packages/actions/src/AssociateAction.php
  packages/panels/docs/02-resources/04-editing-records.md
  packages/schemas/src/Components/Concerns/Cloneable.php
  packages/schemas/src/Concerns/Cloneable.php
  packages/tables/src/Columns/IconColumn.php
  packages/tables/src/Columns/ImageColumn.php
  packages/upgrade/src/Rector/RenameSchemaParamToMatchTypeRector.php
  tests/src/Schemas/ComponentTest.php
Labels: enhancement, awaiting next major version

#15597 Fix invalid file streams used when importing
  packages/actions/src/Concerns/CanImportRecords.php
Labels: bug

#15439 Fix: Allow to override ExportFormat with custom enum instance
  packages/actions/src/Concerns/CanExportRecords.php
  packages/actions/src/Exports/Enums/Contracts/ExportFormat.php
  packages/actions/src/Exports/Enums/ExportFormat.php
  packages/actions/src/Exports/Exporter.php
  packages/actions/src/Exports/Http/Controllers/DownloadExport.php
  packages/actions/src/Exports/Jobs/ExportCompletion.php
Labels: enhancement

#15629 fix: Theme variable in global scope
  packages/panels/resources/views/components/layout/base.blade.php
Labels: bug

#15643 fix: screenshots schemas folder name
  docs-assets/screenshots/images/dark/schemas/layout/actions/independent/full-width.jpg
  docs-assets/screenshots/images/dark/schemas/layout/actions/independent/horizontally-aligned-center.jpg
  docs-assets/screenshots/images/dark/schemas/layout/actions/independent/simple.jpg
  docs-assets/screenshots/images/dark/schemas/layout/actions/independent/vertically-aligned-end.jpg
  docs-assets/screenshots/images/dark/schemas/layout/card/simple.jpg
  docs-assets/screenshots/images/dark/schemas/layout/fieldset/simple.jpg
  docs-assets/screenshots/images/dark/schemas/layout/section/aside.jpg
  docs-assets/screenshots/images/dark/schemas/layout/section/collapsed.jpg
  docs-assets/screenshots/images/dark/schemas/layout/section/compact.jpg
  docs-assets/screenshots/images/dark/schemas/layout/section/footer/actions.jpg
  docs-assets/screenshots/images/dark/schemas/layout/section/header/actions.jpg
  docs-assets/screenshots/images/dark/schemas/layout/section/icons.jpg
  docs-assets/screenshots/images/dark/schemas/layout/section/simple.jpg
  docs-assets/screenshots/images/dark/schemas/layout/section/without-header.jpg
  docs-assets/screenshots/images/dark/schemas/layout/split/simple.jpg
  docs-assets/screenshots/images/dark/schemas/layout/tabs/badges.jpg
  docs-assets/screenshots/images/dark/schemas/layout/tabs/icons-after.jpg
  docs-assets/screenshots/images/dark/schemas/layout/tabs/icons.jpg
  docs-assets/screenshots/images/dark/schemas/layout/tabs/simple.jpg
  docs-assets/screenshots/images/dark/schemas/layout/wizard/completed-icons.jpg
  docs-assets/screenshots/images/dark/schemas/layout/wizard/descriptions.jpg
  docs-assets/screenshots/images/dark/schemas/layout/wizard/icons.jpg
  docs-assets/screenshots/images/dark/schemas/layout/wizard/simple.jpg
  docs-assets/screenshots/images/light/schemas/layout/actions/independent/full-width.jpg
  docs-assets/screenshots/images/light/schemas/layout/actions/independent/horizontally-aligned-center.jpg
  docs-assets/screenshots/images/light/schemas/layout/actions/independent/simple.jpg
  docs-assets/screenshots/images/light/schemas/layout/actions/independent/vertically-aligned-end.jpg
  docs-assets/screenshots/images/light/schemas/layout/card/simple.jpg
  docs-assets/screenshots/images/light/schemas/layout/fieldset/simple.jpg
  docs-assets/screenshots/images/light/schemas/layout/section/aside.jpg
  docs-assets/screenshots/images/light/schemas/layout/section/collapsed.jpg
  docs-assets/screenshots/images/light/schemas/layout/section/compact.jpg
  docs-assets/screenshots/images/light/schemas/layout/section/footer/actions.jpg
  docs-assets/screenshots/images/light/schemas/layout/section/header/actions.jpg
  docs-assets/screenshots/images/light/schemas/layout/section/icons.jpg
  docs-assets/screenshots/images/light/schemas/layout/section/simple.jpg
  docs-assets/screenshots/images/light/schemas/layout/section/without-header.jpg
  docs-assets/screenshots/images/light/schemas/layout/split/simple.jpg
  docs-assets/screenshots/images/light/schemas/layout/tabs/badges.jpg
  docs-assets/screenshots/images/light/schemas/layout/tabs/icons-after.jpg
  docs-assets/screenshots/images/light/schemas/layout/tabs/icons.jpg
  docs-assets/screenshots/images/light/schemas/layout/tabs/simple.jpg
  docs-assets/screenshots/images/light/schemas/layout/wizard/completed-icons.jpg
  docs-assets/screenshots/images/light/schemas/layout/wizard/descriptions.jpg
  docs-assets/screenshots/images/light/schemas/layout/wizard/icons.jpg
  docs-assets/screenshots/images/light/schemas/layout/wizard/simple.jpg
Labels: bug

#15633 Update Swedish translations
  packages/actions/resources/lang/sv/import.php
  packages/forms/resources/lang/sv/components.php
  packages/tables/resources/lang/sv/table.php
Labels: i18n

#15651 fix: Document body not loaded
  packages/support/dist/index.js
  packages/support/resources/js/index.js
Labels: bug

#15641 refactor: Choices input padding when close button present
  packages/forms/dist/index.css
  packages/forms/resources/css/components/select.css
Labels: ui

#15659 Ability to opt out of `<form>` elements
  packages/panels/src/Resources/Pages/Concerns/HasWizard.php
  packages/panels/src/Resources/Pages/CreateRecord.php
  packages/panels/src/Resources/Pages/EditRecord.php
  packages/panels/src/Resources/Pages/ListRecords.php
  packages/panels/src/Resources/Pages/ManageRelatedRecords.php
  packages/panels/src/Resources/RelationManagers/RelationManager.php
  packages/schemas/src/Components/EmbeddedTable.php
  packages/spatie-laravel-settings-plugin/src/Pages/SettingsPage.php
Labels: enhancement

#15662 fix: Exporter not caching export columns
  packages/actions/src/Exports/Exporter.php
Labels: bug

#15691 Update [bs] translation in table.php
  packages/tables/resources/lang/bs/table.php
Labels: i18n

#15695 Laravel 12 support
  composer.json
  composer.lock
  packages/actions/composer.json
  packages/forms/composer.json
  packages/infolists/composer.json
  packages/notifications/composer.json
  packages/panels/composer.json
  packages/spatie-laravel-google-fonts-plugin/composer.json
  packages/spatie-laravel-media-library-plugin/composer.json
  packages/spatie-laravel-settings-plugin/composer.json
  packages/spatie-laravel-tags-plugin/composer.json
  packages/spatie-laravel-translatable-plugin/composer.json
  packages/support/composer.json
  packages/tables/composer.json
Labels: chore

#15616 Add MIME type mapping support to file upload component
  packages/forms/docs/03-fields/09-file-upload.md
  packages/forms/resources/js/components/file-upload.js
  packages/forms/resources/views/components/file-upload.blade.php
  packages/forms/src/Components/FileUpload.php
Labels: bug

#15708 Add new Laravel version to CI
  .github/workflows/phpstan.yml
  .github/workflows/tests.yml
  composer.json
  composer.lock
  phpstan-baseline.neon
  phpstan.neon.dist
  tests/src/Forms/ValidationTest.php
Labels: chore

#15711 Add Input Validation When Creating Panel
  packages/support/src/Commands/Concerns/CanGeneratePanels.php
Labels: bug

#15738 Fix incorrect spelling of 'BMW' in text input docs
  packages/forms/docs/03-fields/02-text-input.md
Labels: documentation
