Repository filamentphp/filament, pull requests merged in 2025-04, with the labels that each got.

#15985 Fix typo configuration
  packages/notifications/src/Notification.php
Labels: bug

#15986 Fix league/csv deprecation
  packages/actions/src/Concerns/CanImportRecords.php
  packages/actions/src/Exports/Downloaders/XlsxDownloader.php
  packages/actions/src/Exports/Jobs/CreateXlsxFile.php
Labels: bug

#15866 Add optional navigate param to action redirect
  packages/actions/src/Concerns/CanRedirect.php
  packages/panels/src/Pages/Auth/EditProfile.php
  packages/panels/src/Pages/Tenancy/EditTenantProfile.php
  packages/panels/src/Pages/Tenancy/RegisterTenant.php
  packages/panels/src/Resources/Pages/CreateRecord.php
  packages/panels/src/Resources/Pages/EditRecord.php
  packages/spatie-laravel-settings-plugin/src/Pages/SettingsPage.php
Labels: enhancement

#15947 Fix: Better detection of encoding for .csv files
  packages/actions/src/Concerns/CanImportRecords.php
Labels: bug

#15924 Cache cell state to prevent multiple execution of the closure in `state()/getStateUsing()`
  packages/support/src/Concerns/HasCellState.php
Labels: bug

#15888 Add missing focus state highlighting in Toggle component
  packages/forms/resources/views/components/toggle.blade.php
  packages/tables/resources/views/columns/toggle-column.blade.php
Labels: ui

#15999 Docs V4 - Fix the links in the Form fields section
  packages/forms/docs/02-text-input.md
  packages/forms/docs/03-select.md
  packages/forms/docs/04-checkbox.md
  packages/forms/docs/05-toggle.md
  packages/forms/docs/08-date-time-picker.md
  packages/forms/docs/09-file-upload.md
  packages/forms/docs/12-repeater.md
  packages/forms/docs/13-builder.md
  packages/forms/docs/15-textarea.md
  packages/forms/docs/18-toggle-buttons.md
Labels: documentation

#16008 Clear cache before cell-state assertions to support changing state during tests
  packages/actions/resources/lang/my/export.php
  packages/actions/resources/lang/my/force-delete.php
  packages/actions/resources/lang/my/group.php
  packages/actions/resources/lang/my/import.php
  packages/actions/resources/lang/my/replicate.php
  packages/actions/resources/lang/my/restore.php
  packages/actions/resources/lang/my/view.php
  packages/forms/resources/lang/my/components.php
  packages/forms/resources/lang/my/validation.php
  packages/infolists/resources/lang/my/components.php
  packages/panels/resources/lang/my/layout.php
  packages/panels/resources/lang/my/pages/auth/edit-profile.php
  packages/panels/resources/lang/my/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/my/pages/auth/login.php
  packages/panels/resources/lang/my/pages/auth/password-reset/request-password-reset.php
  packages/panels/resources/lang/my/pages/auth/password-reset/reset-password.php
  packages/panels/resources/lang/my/pages/auth/register.php
  packages/panels/resources/lang/my/pages/dashboard.php
  packages/panels/resources/lang/my/pages/tenancy/edit-tenant-profile.php
  packages/panels/resources/lang/my/resources/pages/edit-record.php
  packages/panels/resources/lang/my/resources/pages/view-record.php
  packages/panels/resources/lang/my/unsaved-changes-alert.php
  packages/spatie-laravel-media-library-plugin/src/Tables/Columns/SpatieMediaLibraryImageColumn.php
  packages/spatie-laravel-tags-plugin/src/Tables/Columns/SpatieTagsColumn.php
  packages/support/src/Concerns/HasCellState.php
  packages/tables/src/Testing/TestsColumns.php
Labels: bug

#16013 Do not cache cell state if the record has no key
  packages/support/src/Concerns/HasCellState.php
Labels: bug

#16018 Navigation group enums
  packages/actions/src/DetachBulkAction.php
  packages/panels/src/Navigation/NavigationGroup.php
  packages/panels/src/Navigation/NavigationItem.php
  packages/panels/src/Navigation/NavigationManager.php
  packages/panels/src/Pages/Concerns/HasSubNavigation.php
  packages/panels/src/Pages/Page.php
  packages/panels/src/Panel/Concerns/HasNavigation.php
  packages/panels/src/Resources/Resource/Concerns/HasNavigation.php
  packages/support/src/Concerns/HasCellState.php
  packages/support/src/Contracts/Collapsible.php
  packages/support/src/Contracts/HasColor.php
  packages/upgrade/src/Rector/SimpleMethodChangesRector.php
  packages/upgrade/src/Rector/SimplePropertyChangesRector.php
  tests/src/Fixtures/Resources/PostCategories/PostCategoryResource.php
  tests/src/Fixtures/Resources/Posts/PostResource.php
  tests/src/Fixtures/Resources/Shop/Products/ProductResource.php
Labels: enhancement

#15994 Ability to check if macro exists
  packages/support/src/Concerns/Macroable.php
  tests/src/Support/MacroableTest.php
Labels: enhancement

#16021 Slovenian language files for Action package, fix table selected count translation
  packages/actions/resources/lang/sl/associate.php
  packages/actions/resources/lang/sl/attach.php
  packages/actions/resources/lang/sl/create.php
  packages/actions/resources/lang/sl/delete.php
  packages/actions/resources/lang/sl/detach.php
  packages/actions/resources/lang/sl/dissociate.php
  packages/actions/resources/lang/sl/edit.php
  packages/actions/resources/lang/sl/export.php
  packages/actions/resources/lang/sl/force-delete.php
  packages/actions/resources/lang/sl/group.php
  packages/actions/resources/lang/sl/import.php
  packages/actions/resources/lang/sl/modal.php
  packages/actions/resources/lang/sl/replicate.php
  packages/actions/resources/lang/sl/restore.php
  packages/actions/resources/lang/sl/view.php
  packages/tables/resources/lang/sl/table.php
Labels: i18n

#16028 feature: `ActionGroup` `buttonGroup()`
  packages/actions/src/ActionGroup.php
Labels: enhancement

#16043 Add Operation Enum Support to Forms::hiddenOn()
  docs/03-resources/01-overview.md
  packages/schemas/src/Components/Concerns/CanBeHidden.php
  packages/support/src/Enums/Operation.php
  tests/src/Forms/HiddenComponentsTest.php
Labels: enhancement

#16050 Update bug_report.yml - change reproduction issue repo link
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: chore

#16044 Wrapped fieldname to solve SQL Error when sorting
  packages/tables/src/Concerns/CanReorderRecords.php
Labels: bug

#16057 Docs V4 - Table - external api examples
  packages/tables/docs/09-static-data.md
Labels: documentation

#16065 fix(spa): unsaved data changes alert
  packages/panels/resources/views/components/page/unsaved-data-changes-alert.blade.php
Labels: bug

#16068 Fix "isLimited is not defined" error in TextColumn expandableLimitedList functionlity.
  packages/support/resources/views/components/link.blade.php
  packages/tables/resources/views/columns/text-column.blade.php
Labels: bug

#16081 fix: Query builder actions memory issue
  packages/forms/src/Concerns/CanBeValidated.php
  packages/forms/src/Concerns/InteractsWithForms.php
  packages/forms/src/Contracts/HasForms.php
Labels: bug

#16083 fix: Saving relationships within layout relationships, and `MorphTo` layout relationships
  packages/forms/docs/01-overview.md
  packages/schemas/src/Components/Concerns/EntanglesStateWithSingularRelationship.php
Labels: bug

#16084 fix: Reordering grammar object
  packages/tables/src/Concerns/CanReorderRecords.php
Labels: bug

#16087 fix: Repeater and builder item overflow breaking select dropdown
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/repeater/index.blade.php
Labels: bug

#16088 fix: Saving layout components with the same relationship multiple times
  packages/schemas/src/Components/Concerns/BelongsToContainer.php
  packages/schemas/src/Components/Concerns/EntanglesStateWithSingularRelationship.php
  packages/schemas/src/Components/Contracts/CanEntangleWithSingularRelationships.php
Labels: bug

#16098 fix: TextInputColumn with date type
  packages/tables/resources/views/columns/text-input-column.blade.php
Labels: bug

#16096 i18n: Implement/Improve Indonesian Translations in Multiple Packages
  packages/actions/resources/lang/id/create.php
  packages/actions/resources/lang/id/restore.php
  packages/forms/resources/lang/id/components.php
  packages/infolists/resources/lang/id/components.php
  packages/support/resources/lang/id/components/pagination.php
Labels: i18n

#16117 Docs: update unique validation parameter name
  packages/forms/docs/05-validation.md
Labels: documentation

#16120 docs: Fix empty make method for user menu example
  docs/06-navigation/03-user-menu.md
Labels: documentation

#16124 Add globbing to theme stub
  packages/panels/src/Commands/MakeThemeCommand.php
  packages/panels/stubs/ThemeCss.stub
Labels: bug

#16100 Fix: change color() in all actions to defaultColor() where required, so that it can be overidden
  packages/actions/src/Concerns/CanExportRecords.php
  packages/actions/src/Concerns/CanImportRecords.php
  packages/actions/src/DeleteAction.php
  packages/actions/src/ForceDeleteAction.php
  packages/actions/src/RestoreAction.php
  packages/actions/src/ViewAction.php
  packages/forms/src/Components/TextInput/Actions/HidePasswordAction.php
  packages/forms/src/Components/TextInput/Actions/ShowPasswordAction.php
  packages/tables/src/Actions/AssociateAction.php
  packages/tables/src/Actions/AttachAction.php
  packages/tables/src/Actions/BulkActionGroup.php
  packages/tables/src/Actions/DeleteAction.php
  packages/tables/src/Actions/DeleteBulkAction.php
  packages/tables/src/Actions/DetachAction.php
  packages/tables/src/Actions/DetachBulkAction.php
  packages/tables/src/Actions/DissociateAction.php
  packages/tables/src/Actions/DissociateBulkAction.php
  packages/tables/src/Actions/ForceDeleteAction.php
  packages/tables/src/Actions/ForceDeleteBulkAction.php
  packages/tables/src/Actions/RestoreAction.php
  packages/tables/src/Actions/RestoreBulkAction.php
  packages/tables/src/Actions/ViewAction.php
Labels: bug

#16144 Capture the "TAB" key only when the user has selected text.
  packages/forms/dist/components/markdown-editor.js
  packages/forms/resources/js/components/markdown-editor/EasyMDE.js
Labels: bug

#16159 Update 04-clusters.md
  docs/06-navigation/04-clusters.md
Labels: documentation

#16161 fix: Icon summaries cached state
  packages/tables/src/Columns/Summarizers/Count.php
Labels: bug

#16114 Query builder german translations
  packages/tables/resources/lang/de/filters/query-builder.php
Labels: i18n

#16164 Allow closure for MFA providers
  packages/panels/src/Panel/Concerns/HasAuth.php
Labels: enhancement

#16152 Fix make theme command to work with Tailwind CSS alias
  packages/panels/src/Commands/MakeThemeCommand.php
Labels: bug

#16172 Revert cached state
  packages/spatie-laravel-media-library-plugin/src/Tables/Columns/SpatieMediaLibraryImageColumn.php
  packages/spatie-laravel-tags-plugin/src/Tables/Columns/SpatieTagsColumn.php
  packages/support/src/Concerns/HasCellState.php
  packages/tables/src/Columns/Summarizers/Count.php
  packages/tables/src/Testing/TestsColumns.php
Labels: bug

#16175 Inverse bulk selection and more efficient processing
  docs/03-resources/07-managing-relationships.md
  packages/actions/docs/07-delete.md
  packages/actions/docs/09-force-delete.md
  packages/actions/docs/10-restore.md
  packages/actions/src/Action.php
  packages/actions/src/BulkAction.php
  packages/actions/src/Concerns/CanExportRecords.php
  packages/actions/src/Concerns/CanFetchSelectedRecords.php
  packages/actions/src/Concerns/InteractsWithSelectedRecords.php
  packages/actions/src/DeleteBulkAction.php
  packages/actions/src/DetachBulkAction.php
  packages/actions/src/DissociateBulkAction.php
  packages/actions/src/ForceDeleteBulkAction.php
  packages/actions/src/RestoreBulkAction.php
  packages/tables/dist/components/table.js
  packages/tables/docs/04-actions.md
  packages/tables/docs/09-static-data.md
  packages/tables/resources/js/components/table.js
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Concerns/HasBulkActions.php
  packages/tables/src/Contracts/HasTable.php
Labels: enhancement

#16179 feat: allow custom credential extraction and notification customization for password reset
  packages/panels/src/Pages/Auth/PasswordReset/RequestPasswordReset.php
  packages/panels/src/Pages/Auth/PasswordReset/ResetPassword.php
Labels: enhancement
