Repository filamentphp/filament, pull requests merged in 2025-07, with the labels that each got.

#16753 feature: App asset version
  packages/support/src/Assets/Asset.php
  packages/support/src/Assets/AssetManager.php
  packages/support/src/Facades/FilamentAsset.php
Labels: enhancement

#16755 [4.x] Feat: Rich editor clear formatting extension
  packages/forms/dist/index.css
  packages/forms/docs/10-rich-editor.md
  packages/forms/resources/lang/en/components.php
  packages/forms/src/Components/RichEditor.php
  packages/support/resources/svg/s-clear-formatting.svg
Labels: enhancement

#16791 fix: Badge actions in tables
  packages/panels/dist/theme.css
  packages/tables/resources/css/actions.css
Labels: bug

#16796 Update spanish translations - Fix typo and change for consistency
  packages/forms/resources/lang/es/components.php
Labels: i18n

#16797 Update missing Khmer translations - action import forms component and…
  packages/actions/resources/lang/km/import.php
  packages/forms/resources/lang/km/components.php
  packages/tables/resources/lang/km/table.php
Labels: i18n

#16799 Update missing Khmer translations - action import, forms component, and table column
  packages/actions/resources/lang/km/import.php
  packages/forms/resources/lang/km/components.php
  packages/tables/resources/lang/km/table.php
Labels: i18n

#16809 Update Czech and Slovak translations.
  packages/forms/resources/lang/cs/components.php
  packages/forms/resources/lang/sk/components.php
Labels: i18n

#16813 fix: Spatie Media Library single reorderable
  packages/spatie-laravel-media-library-plugin/src/Forms/Components/SpatieMediaLibraryFileUpload.php
Labels: bug

#16746 [4.x] Feat: Add support for Details extension to Rich Editor
  package-lock.json
  package.json
  packages/forms/dist/components/rich-editor.js
  packages/forms/docs/10-rich-editor.md
  packages/forms/resources/css/components/rich-editor.css
  packages/forms/resources/js/components/rich-editor/extensions.js
  packages/forms/resources/lang/en/components.php
  packages/forms/src/Components/RichEditor.php
  packages/forms/src/Components/RichEditor/RichContentRenderer.php
  packages/forms/src/Components/RichEditor/TipTapExtensions/DetailsContentExtension.php
  packages/forms/src/Components/RichEditor/TipTapExtensions/DetailsExtension.php
  packages/forms/src/Components/RichEditor/TipTapExtensions/DetailsSummaryExtension.php
  packages/panels/dist/theme.css
  packages/support/resources/svg/o-details.svg
Labels: enhancement, pending changes

#16767 fix: wrap user menu into flex container
  packages/panels/resources/css/components/user-menu.css
  packages/panels/resources/views/components/user-menu.blade.php
Labels: enhancement

#16782 Add extra attributes to builder block's
  packages/forms/resources/views/components/builder.blade.php
Labels: enhancement

#16784 [4.x] Support HTML output for option labels in ModalTableSelect
  packages/forms/src/Components/ModalTableSelect.php
Labels: enhancement

#16830 [4.x] Fix form builder
  packages/forms/resources/views/components/builder.blade.php
  tests/src/Forms/Components/BuilderTest.php
Labels: bug

#16819 Fix cleanup for mountedTableActionsArguments
  packages/tables/src/Concerns/HasActions.php
Labels: bug

#16839 fix: untranslated Vietnamese strings in 4.x
  packages/actions/resources/lang/vi/import.php
  packages/tables/resources/lang/vi/table.php
Labels: i18n

#16831 [4] Replace Legacy Tailwind CSS v3 screen function
  packages/forms/resources/css/components/file-upload.css
  packages/panels/dist/theme.css
Labels: bug

#16826 Add attribute for in label
  packages/forms/resources/views/components/field-wrapper.blade.php
Labels: bug, a11y

#16639 Fix accessibility issue
  packages/forms/resources/views/components/field-wrapper/index.blade.php
  packages/forms/resources/views/components/field-wrapper/label.blade.php
  packages/forms/resources/views/components/file-upload.blade.php
  packages/forms/resources/views/components/markdown-editor.blade.php
Labels: a11y

#16843 Add missing SK & CZ translation
  packages/forms/resources/lang/cs/components.php
  packages/forms/resources/lang/sk/components.php
Labels: i18n

#16621 fix(tables): wrap summarizer columns
  packages/tables/src/Columns/Summarizers/Average.php
  packages/tables/src/Columns/Summarizers/Count.php
  packages/tables/src/Columns/Summarizers/Range.php
  packages/tables/src/Columns/Summarizers/Sum.php
Labels: bug

#16765 feat: add before/after logo render hooks
  docs/09-advanced/01-render-hooks.md
  packages/panels/resources/views/livewire/sidebar.blade.php
  packages/panels/resources/views/livewire/topbar.blade.php
  packages/panels/src/View/PanelsRenderHook.php
Labels: enhancement

#16851 Add `extraAttributes` to tables
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Table.php
Labels: enhancement

#16845 V4 fix reorderable columns
  packages/tables/resources/lang/en/table.php
  packages/tables/resources/lang/es/table.php
  packages/tables/resources/views/components/column-manager.blade.php
  packages/tables/src/Concerns/HasColumnManager.php
Labels: bug

#16856 [4.x] Feat: make RichContentRenderer Macroable
  packages/forms/src/Components/RichEditor/RichContentRenderer.php
Labels: enhancement

#16865 Fix SQL syntax error during global search when using : in table names #16864
  packages/support/src/helpers.php
  tests/src/Support/helpersTest.php
Labels: bug

#16877 [4.x] Avoid infinite loop from JS update from Laravel framework 56159
  packages/notifications/src/Notification.php
Labels: bug

#16872 Update Indonesian langauge
  packages/actions/resources/lang/id/delete.php
  packages/actions/resources/lang/id/force-delete.php
  packages/actions/resources/lang/id/notifications.php
  packages/actions/resources/lang/id/restore.php
  packages/forms/resources/lang/id/components.php
  packages/panels/resources/lang/id/auth/http/controllers/block-email-change-verification-controller.php
  packages/panels/resources/lang/id/auth/http/controllers/email-change-verification-controller.php
  packages/panels/resources/lang/id/auth/multi-factor/app/actions/disable.php
  packages/panels/resources/lang/id/auth/multi-factor/app/actions/regenerate-recovery-codes.php
  packages/panels/resources/lang/id/auth/multi-factor/app/actions/set-up.php
  packages/panels/resources/lang/id/auth/multi-factor/app/provider.php
  packages/panels/resources/lang/id/auth/multi-factor/email/actions/disable.php
  packages/panels/resources/lang/id/auth/multi-factor/email/actions/set-up.php
  packages/panels/resources/lang/id/auth/multi-factor/email/notifications/verify-email-authentication.php
  packages/panels/resources/lang/id/auth/multi-factor/email/provider.php
  packages/panels/resources/lang/id/auth/multi-factor/pages/set-up-required-multi-factor-authentication.php
  packages/panels/resources/lang/id/auth/multi-factor/recovery-codes-modal-content.php
  packages/panels/resources/lang/id/auth/notifications/notice-of-email-change-request.php
  packages/panels/resources/lang/id/auth/pages/edit-profile.php
  packages/panels/resources/lang/id/auth/pages/login.php
  packages/panels/resources/lang/id/auth/pages/password-reset/request-password-reset.php
  packages/panels/resources/lang/id/error-notifications.php
  packages/tables/resources/lang/id/table.php
  packages/widgets/resources/lang/id/chart.php
  tests/src/Support/helpersTest.php
  translators.csv
Labels: i18n

#16875 :recycle: require confirmation before setting label in actions
  packages/actions/src/DeleteAction.php
  packages/actions/src/ForceDeleteAction.php
  packages/actions/src/RestoreAction.php
  packages/tables/src/Actions/DeleteAction.php
  packages/tables/src/Actions/DeleteBulkAction.php
  packages/tables/src/Actions/DetachAction.php
  packages/tables/src/Actions/DetachBulkAction.php
  packages/tables/src/Actions/DissociateAction.php
  packages/tables/src/Actions/DissociateBulkAction.php
  packages/tables/src/Actions/ForceDeleteAction.php
  packages/tables/src/Actions/ForceDeleteBulkAction.php
  packages/tables/src/Actions/RestoreAction.php
  packages/tables/src/Actions/RestoreBulkAction.php
Labels: bug

#16881 fix: Fused group validation
  packages/forms/resources/views/components/field-wrapper.blade.php
  packages/schemas/resources/views/components/fused-group.blade.php
Labels: bug

#16871 Update InteractsWithToolbarButtons.php
  packages/forms/src/Components/Concerns/InteractsWithToolbarButtons.php
Labels: bug

#16786 [4.x] Add generator for Rich Editor custom blocks
  packages/forms/docs/10-rich-editor.md
  packages/forms/src/Commands/FileGenerators/RichContentCustomBlockClassGenerator.php
  packages/forms/src/Commands/MakeRichContentCustomBlockCommand.php
  packages/forms/src/FormsServiceProvider.php
  packages/forms/stubs/RichContentCustomBlockPreviewView.stub
  packages/forms/stubs/RichContentCustomBlockView.stub
Labels: enhancement

#16885 Add page content render hooks
  docs/09-advanced/01-render-hooks.md
  packages/panels/resources/views/components/page/index.blade.php
  packages/panels/src/Pages/Page.php
  packages/panels/src/View/PanelsRenderHook.php
Labels: enhancement

#16891 fix: Dynamically disable JS inputs
  packages/forms/dist/components/slider.js
  packages/forms/resources/js/components/slider.js
  packages/forms/resources/views/components/code-editor.blade.php
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/resources/views/components/file-upload.blade.php
  packages/forms/resources/views/components/key-value.blade.php
  packages/forms/resources/views/components/rich-editor.blade.php
  packages/forms/resources/views/components/select.blade.php
  packages/forms/resources/views/components/slider.blade.php
Labels: bug

#16902 [4.x] Add missing Russian (ru) translations
  packages/actions/resources/lang/ru/delete.php
  packages/actions/resources/lang/ru/force-delete.php
  packages/actions/resources/lang/ru/import.php
  packages/actions/resources/lang/ru/notifications.php
  packages/actions/resources/lang/ru/restore.php
  packages/forms/resources/lang/ru/components.php
  packages/panels/resources/lang/ru/auth/http/controllers/block-email-change-verification-controller.php
  packages/panels/resources/lang/ru/auth/http/controllers/email-change-verification-controller.php
  packages/panels/resources/lang/ru/auth/multi-factor/app/actions/disable.php
  packages/panels/resources/lang/ru/auth/multi-factor/app/actions/regenerate-recovery-codes.php
  packages/panels/resources/lang/ru/auth/multi-factor/app/actions/set-up.php
  packages/panels/resources/lang/ru/auth/multi-factor/app/provider.php
  packages/panels/resources/lang/ru/auth/multi-factor/email/actions/disable.php
  packages/panels/resources/lang/ru/auth/multi-factor/email/actions/set-up.php
  packages/panels/resources/lang/ru/auth/multi-factor/email/notifications/verify-email-authentication.php
  packages/panels/resources/lang/ru/auth/multi-factor/email/provider.php
  packages/panels/resources/lang/ru/auth/multi-factor/pages/set-up-required-multi-factor-authentication.php
  packages/panels/resources/lang/ru/auth/multi-factor/recovery-codes-modal-content.php
  packages/panels/resources/lang/ru/auth/notifications/notice-of-email-change-request.php
  packages/panels/resources/lang/ru/auth/pages/edit-profile.php
  packages/panels/resources/lang/ru/auth/pages/login.php
  packages/panels/resources/lang/ru/auth/pages/password-reset/request-password-reset.php
  packages/panels/resources/lang/ru/error-notifications.php
  packages/tables/resources/lang/ru/table.php
  packages/widgets/resources/lang/ru/chart.php
Labels: i18n

#16907 [4.x] Update missing polish translations
  packages/actions/resources/lang/pl/delete.php
  packages/actions/resources/lang/pl/force-delete.php
  packages/actions/resources/lang/pl/notifications.php
  packages/actions/resources/lang/pl/restore.php
  packages/forms/resources/lang/pl/components.php
  packages/panels/resources/lang/pl/auth/http/controllers/block-email-change-verification-controller.php
  packages/panels/resources/lang/pl/auth/http/controllers/email-change-verification-controller.php
  packages/panels/resources/lang/pl/auth/multi-factor/app/actions/disable.php
  packages/panels/resources/lang/pl/auth/multi-factor/app/actions/regenerate-recovery-codes.php
  packages/panels/resources/lang/pl/auth/multi-factor/app/actions/set-up.php
  packages/panels/resources/lang/pl/auth/multi-factor/app/provider.php
  packages/panels/resources/lang/pl/auth/multi-factor/email/actions/disable.php
  packages/panels/resources/lang/pl/auth/multi-factor/email/actions/set-up.php
  packages/panels/resources/lang/pl/auth/multi-factor/email/notifications/verify-email-authentication.php
  packages/panels/resources/lang/pl/auth/multi-factor/email/provider.php
  packages/panels/resources/lang/pl/auth/multi-factor/pages/set-up-required-multi-factor-authentication.php
  packages/panels/resources/lang/pl/auth/multi-factor/recovery-codes-modal-content.php
  packages/panels/resources/lang/pl/auth/notifications/notice-of-email-change-request.php
  packages/panels/resources/lang/pl/auth/pages/edit-profile.php
  packages/panels/resources/lang/pl/auth/pages/login.php
  packages/panels/resources/lang/pl/auth/pages/password-reset/request-password-reset.php
  packages/panels/resources/lang/pl/error-notifications.php
  packages/tables/resources/lang/pl/table.php
Labels: i18n

#16908 Handle Postgres nested JSON searches
  packages/support/src/helpers.php
  tests/src/Support/helpersTest.php
Labels: bug

#16910 Updated the Create Action to no longer enable double clicking during creation and therefore creating duplicate records
  packages/panels/src/Resources/Pages/CreateRecord.php
Labels: bug

#16918 Add missing CZ and SK translation
  packages/tables/resources/lang/cs/table.php
  packages/tables/resources/lang/sk/table.php
Labels: i18n

#16706 feat: add `->trim()` method to `TextInput`, `Textarea` and `TagsInput`
  packages/forms/docs/02-text-input.md
  packages/forms/docs/14-tags-input.md
  packages/forms/docs/15-textarea.md
  packages/forms/src/Components/TagsInput.php
  packages/forms/src/Components/TextInput.php
  packages/forms/src/Components/Textarea.php
  packages/schemas/src/Components/Concerns/CanStripCharactersFromState.php
  packages/schemas/src/Components/Concerns/CanTrimState.php
  packages/schemas/src/Components/Concerns/HasState.php
  tests/src/Forms/Components/TagsInputTest.php
  tests/src/Forms/Components/TextInputTest.php
  tests/src/Forms/Components/TextareaTest.php
Labels: enhancement

#16921 fix: Global search soft deleted models
  docs/03-resources/06-deleting-records.md
  packages/panels/src/Commands/FileGenerators/Resources/ResourceClassGenerator.php
  packages/panels/src/Resources/Resource/Concerns/HasRoutes.php
  tests/.pest/snapshots/src/Panels/Commands/Legacy/LegacyMakeResourceCommandTest/it_can_generate_a_resource_class_with_soft_deletes.snap
  tests/.pest/snapshots/src/Panels/Commands/MakeResourceCommandTest/it_can_generate_a_resource_class_with_soft_deletes.snap
Labels: bug

#16925 fix: fixed bug where rounded corners where applied to all pagination items
  packages/forms/dist/index.css
  packages/panels/dist/theme.css
  packages/support/resources/css/components/pagination.css
Labels: bug

#16932 Add `refresh-page` event / listener
  packages/panels/src/Pages/BasePage.php
Labels: enhancement

#16931 [v4] Add an inline code tool to Rich Editor
  packages/forms/docs/10-rich-editor.md
  packages/forms/resources/lang/en/components.php
  packages/forms/src/Components/RichEditor.php
  packages/support/resources/svg/o-code-block.svg
  packages/support/resources/svg/o-code.svg
Labels: enhancement

#16959 [4.x] Add missing French (fr) translations
  packages/actions/resources/lang/fr/delete.php
  packages/actions/resources/lang/fr/force-delete.php
  packages/actions/resources/lang/fr/import.php
  packages/actions/resources/lang/fr/notifications.php
  packages/actions/resources/lang/fr/restore.php
  packages/forms/resources/lang/fr/components.php
  packages/panels/resources/lang/fr/auth/http/controllers/block-email-change-verification-controller.php
  packages/panels/resources/lang/fr/auth/http/controllers/email-change-verification-controller.php
  packages/panels/resources/lang/fr/auth/multi-factor/app/actions/disable.php
  packages/panels/resources/lang/fr/auth/multi-factor/app/actions/regenerate-recovery-codes.php
  packages/panels/resources/lang/fr/auth/multi-factor/app/actions/set-up.php
  packages/panels/resources/lang/fr/auth/multi-factor/app/provider.php
  packages/panels/resources/lang/fr/auth/multi-factor/email/actions/disable.php
  packages/panels/resources/lang/fr/auth/multi-factor/email/actions/set-up.php
  packages/panels/resources/lang/fr/auth/multi-factor/email/notifications/verify-email-authentication.php
  packages/panels/resources/lang/fr/auth/multi-factor/email/provider.php
  packages/panels/resources/lang/fr/auth/multi-factor/pages/set-up-required-multi-factor-authentication.php
  packages/panels/resources/lang/fr/auth/multi-factor/recovery-codes-modal-content.php
  packages/panels/resources/lang/fr/auth/notifications/notice-of-email-change-request.php
  packages/panels/resources/lang/fr/auth/pages/edit-profile.php
  packages/panels/resources/lang/fr/auth/pages/login.php
  packages/panels/resources/lang/fr/auth/pages/password-reset/request-password-reset.php
  packages/panels/resources/lang/fr/error-notifications.php
  packages/tables/resources/lang/fr/filters/query-builder.php
  packages/tables/resources/lang/fr/table.php
  packages/widgets/resources/lang/fr/chart.php
Labels: i18n

#16969 Translate ckb
  packages/actions/resources/lang/ckb/attach.php
  packages/actions/resources/lang/ckb/create.php
  packages/actions/resources/lang/ckb/delete.php
  packages/actions/resources/lang/ckb/detach.php
  packages/actions/resources/lang/ckb/dissociate.php
  packages/actions/resources/lang/ckb/edit.php
  packages/actions/resources/lang/ckb/force-delete.php
  packages/actions/resources/lang/ckb/import.php
  packages/actions/resources/lang/ckb/modal.php
  packages/actions/resources/lang/ckb/restore.php
  packages/forms/resources/lang/ckb/components.php
  packages/forms/resources/lang/ckb/validation.php
  packages/infolists/resources/lang/ckb/components.php
  packages/notifications/resources/lang/ckb/database.php
  packages/panels/resources/lang/ckb/error-notifications.php
  packages/panels/resources/lang/ckb/pages/dashboard.php
  packages/panels/resources/lang/ckb/pages/tenancy/edit-tenant-profile.php
  packages/panels/resources/lang/ckb/resources/pages/create-record.php
  packages/panels/resources/lang/ckb/unsaved-changes-alert.php
  packages/panels/resources/lang/ckb/widgets/filament-info-widget.php
  packages/schemas/resources/lang/ckb/components.php
  packages/tables/resources/lang/ckb/filters/query-builder.php
  packages/widgets/resources/lang/ckb/chart.php
Labels: i18n

#16975 [v3] Add support for disabled checkboxes when bulkToggleable
  packages/forms/resources/views/components/checkbox-list.blade.php
Labels: bug

#16979 Fix typo in date-time-picker.blade.php
  packages/forms/resources/views/components/date-time-picker.blade.php
Labels: bug

#16989 Add Illuminate\Support\HtmlString support as state to RichEditor component
  packages/forms/src/Components/RichEditor/StateCasts/RichEditorStateCast.php
Labels: bug, pending changes

#16997 Update slider.blade.php
  packages/forms/resources/views/components/slider.blade.php
Labels: bug

#16998 Update "Replacing the default icons" docs to use enums instead of strings
  docs/08-styling/04-icons.md
Labels: documentation

#16984 Suggestion: Allow empty string as placeholder for select
  packages/forms/dist/components/select.js
  packages/forms/resources/js/components/select.js
Labels: bug

#17002 Add 'resource-namespace' option to MakeResourceCommand for customizab…
  packages/panels/src/Commands/MakePageCommand.php
  packages/panels/src/Commands/MakeRelationManagerCommand.php
  packages/panels/src/Commands/MakeResourceCommand.php
  packages/support/src/Commands/Concerns/HasResourcesLocation.php
  packages/widgets/src/Commands/MakeWidgetCommand.php
Labels: enhancement

#16993 Fix Rich editor layout content shift
  packages/forms/resources/css/components/rich-editor.css
  packages/forms/resources/views/components/rich-editor.blade.php
  packages/panels/dist/theme.css
Labels: bug

#17016 Update HtmlString to Htmlable contract in rich editor state cast
  packages/forms/src/Components/RichEditor/StateCasts/RichEditorStateCast.php
Labels: bug

#17008 [4.x] Add dutch 2fa translations
  packages/panels/resources/lang/nl/auth/multi-factor/app/actions/disable.php
  packages/panels/resources/lang/nl/auth/multi-factor/app/actions/regenerate-recovery-codes.php
  packages/panels/resources/lang/nl/auth/multi-factor/app/actions/set-up.php
  packages/panels/resources/lang/nl/auth/multi-factor/app/provider.php
  packages/panels/resources/lang/nl/auth/multi-factor/email/actions/disable.php
  packages/panels/resources/lang/nl/auth/multi-factor/email/actions/set-up.php
  packages/panels/resources/lang/nl/auth/multi-factor/email/notifications/verify-email-authentication.php
  packages/panels/resources/lang/nl/auth/multi-factor/email/provider.php
  packages/panels/resources/lang/nl/auth/multi-factor/pages/set-up-required-multi-factor-authentication.php
  packages/panels/resources/lang/nl/auth/multi-factor/recovery-codes-modal-content.php
Labels: i18n

#17020 chore: replace h/w utility classes with size shorthand
  packages/forms/resources/css/components/file-upload.css
  packages/forms/resources/css/components/markdown-editor.css
Labels: chore

#17013 Add missing arabic translations - Passowrd reset notifcation
  packages/panels/resources/lang/ar/pages/auth/password-reset/request-password-reset.php
Labels: i18n

#17030 chore: update documentation link
  packages/forms/docs/03-fields/02-text-input.md
Labels: documentation

#17031 Update Kurdish translations for image editing actions and UI components
  packages/forms/resources/lang/ckb/components.php
Labels: i18n

#16957 Add `OverlayScrollbars` for prettier scrollbars
  package-lock.json
  package.json
  packages/panels/dist/theme.css
  packages/panels/resources/css/components/sidebar.css
  packages/panels/resources/views/livewire/sidebar.blade.php
  packages/support/dist/index.css
  packages/support/dist/index.js
  packages/support/resources/css/components/scrollbar.css
  packages/support/resources/css/index.css
  packages/support/resources/js/index.js
  packages/support/resources/js/scrollbars.js
  packages/tables/resources/views/index.blade.php
Labels: enhancement

#16973 [v4] Docs: optimize local dev
  docs/01-introduction/03-optimizing-local-development.md
  docs/01-introduction/04-help.md
  docs/01-introduction/05-version-support-policy.md
  docs/01-introduction/06-contributing.md
  docs/13-deployment.md
Labels: documentation

#17021 feat(4.x): spa prefetching
  docs/05-panel-configuration.md
  packages/panels/src/Panel.php
  packages/panels/src/Panel/Concerns/HasSpaMode.php
  packages/support/src/Facades/FilamentView.php
  packages/support/src/View/ViewManager.php
  packages/support/src/helpers.php
  tests/src/Support/SpaModeTest.php
Labels: enhancement

#17033 [v4] Fix: Section collapse icon does not rotate when collapsed
  packages/panels/dist/theme.css
  packages/support/resources/css/components/section.css
Labels: bug

#17038 [v4] Add more languages to code mirror code editor
  package-lock.json
  package.json
  packages/forms/dist/components/code-editor.js
  packages/forms/docs/20-code-editor.md
  packages/forms/resources/js/components/code-editor.js
  packages/forms/src/Components/CodeEditor/Enums/Language.php
Labels: enhancement

#17039 [4.x] Fix French (fr) translations
  packages/actions/resources/lang/fr/edit.php
  packages/panels/resources/lang/fr/auth/pages/edit-profile.php
  packages/panels/resources/lang/fr/pages/tenancy/edit-tenant-profile.php
  packages/panels/resources/lang/fr/resources/pages/edit-record.php
  packages/spatie-laravel-settings-plugin/resources/lang/fr/pages/settings-page.php
Labels: i18n

#16745 [v4 feature]: add option to limit the number of selectable records in a table
  packages/forms/resources/views/components/table-select.blade.php
  packages/forms/src/Components/ModalTableSelect.php
  packages/forms/src/Components/TableSelect.php
  packages/forms/src/Components/TableSelect/Livewire/TableSelectLivewireComponent.php
  packages/tables/dist/index.js
  packages/tables/docs/04-actions.md
  packages/tables/resources/js/components/table.js
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Concerns/HasBulkActions.php
  packages/tables/src/Table/Concerns/HasBulkActions.php
Labels: enhancement

#17029 implemented getLengthValidationRules on rich editor
  packages/forms/src/Components/RichEditor.php
Labels: bug

#17003 feat: ability to set `->defaultFocusedDate()` when opening empty `DateTimePicker`
  packages/forms/dist/components/date-time-picker.js
  packages/forms/docs/03-fields/08-date-time-picker.md
  packages/forms/resources/js/components/date-time-picker.js
  packages/forms/resources/views/components/date-time-picker.blade.php
  packages/forms/src/Components/DateTimePicker.php
  packages/panels/dist/theme.css
Labels: enhancement

#17052 fix: disabled `ToggleColumn` state
  packages/support/resources/css/components/toggle.css
  packages/tables/src/Columns/ToggleColumn.php
Labels: bug

#17058 Fix nav slideover auto-collapse not working after SPA navigation
  packages/panels/dist/index.js
  packages/panels/resources/js/stores/sidebar.js
Labels: bug

#17060 Fix ModalTableSelect issue in Repeater context
  packages/forms/src/Components/ModalTableSelect.php
Labels: bug

#17063 fix: Markdown editor file uploads
  packages/forms/resources/views/components/markdown-editor.blade.php
Labels: bug

#17100 Update HasSchema.php
  packages/tables/src/Filters/Concerns/HasSchema.php
Labels: bug

#17095 [v3] Fix loading indicator appearing in table after group deselection
  packages/tables/dist/components/table.js
  packages/tables/resources/js/components/table.js
Labels: bug

#17078 fix: defer evaluating edit option form data
  packages/forms/src/Components/Select.php
Labels: bug

#17065 [v4] Add missing evaluate to `isMultiFactorAuthenticationRequired()`
  packages/panels/src/Panel/Concerns/HasAuth.php
Labels: bug, pending review

#17069 Add Closure to $defaultGroup to Filament\Tables\Table\Concerns\CanGroupRecords.php
  packages/tables/src/Table/Concerns/CanGroupRecords.php
Labels: enhancement

#17080 fix: Support HasEmbeddedView components for partialRendering
  packages/schemas/src/Components/Concerns/CanPartiallyRender.php
Labels: bug

#17110 fix: convert `defaultFocusedDate()` to correct timezone
  packages/forms/src/Components/DateTimePicker.php
Labels: bug

#17116 fix: FileUpload max files frontend validation message
  packages/forms/dist/components/file-upload.js
  packages/forms/resources/js/components/file-upload.js
  packages/forms/resources/views/components/file-upload.blade.php
Labels: bug

#17117 fix: Action group styling
  packages/actions/src/ActionGroup.php
  packages/panels/dist/theme.css
  packages/support/resources/css/components/dropdown/list/item.css
Labels: bug

#17122 fix: Rich editor custom block nested modal action
  packages/actions/src/Concerns/InteractsWithActions.php
Labels: bug

#17123 fix: Rich editor image alignment
  packages/forms/dist/components/rich-editor.js
  packages/forms/resources/css/components/rich-editor.css
  packages/forms/resources/js/components/rich-editor/extensions.js
  packages/panels/dist/theme.css
Labels: bug

#17124 fix: Dynamic viewport height
  packages/panels/dist/theme.css
  packages/panels/resources/css/components/layout.css
  packages/panels/resources/css/components/sidebar.css
Labels: bug

#17136 fix: Infolist entry relationships in forms with state paths
  packages/schemas/src/Components/Concerns/CanGetStateFromRelationships.php
  packages/schemas/src/Components/Concerns/HasState.php
Labels: bug

#16981 Schema internal caching
  packages/schemas/src/Components/Concerns/BelongsToContainer.php
  packages/schemas/src/Components/Concerns/CanBeHidden.php
  packages/schemas/src/Concerns/HasComponents.php
  packages/schemas/src/Concerns/HasState.php
Labels: bug
