Repository filamentphp/filament, pull requests merged in 2025-06, with the labels that each got.

#16397 Update finnish translation
  packages/forms/resources/lang/fi/components.php
  packages/panels/resources/lang/fi/global-search.php
  packages/panels/resources/lang/fi/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/fi/pages/auth/password-reset/request-password-reset.php
  packages/tables/resources/lang/fi/table.php
Labels: i18n

#16400 docs: add missing schema import
  docs/12-components/02-form.md
Labels: documentation

#16409 Honor actions alignment for table actions with content grid
  packages/tables/resources/views/index.blade.php
Labels: bug

#16417 feat: zh_TW translations
  packages/support/resources/lang/zh_TW/components/copyable.php
  packages/support/resources/lang/zh_TW/components/modal.php
  packages/support/resources/lang/zh_TW/components/pagination.php
Labels: i18n

#16399 Documented persistsFiltersInSession() function
  packages/panels/docs/05-dashboard.md
Labels: documentation

#16368 feat(i18n): add custom-blocks pt/es translation & sync other keys in Rich Editor
  packages/forms/resources/lang/es/components.php
  packages/forms/resources/lang/pt/components.php
  packages/forms/resources/lang/pt_BR/components.php
Labels: i18n

#16378 Add missing pt_BR translation in request-password-reset.
  packages/panels/resources/lang/pt_BR/pages/auth/password-reset/request-password-reset.php
Labels: i18n

#16355 feat: provide `Panel $panel` to static route-related methods
  packages/panels/src/Auth/Pages/EditProfile.php
  packages/panels/src/Clusters/Cluster.php
  packages/panels/src/Pages/Concerns/HasRoutes.php
  packages/panels/src/Pages/Dashboard.php
  packages/panels/src/Pages/Page.php
  packages/panels/src/Pages/Tenancy/EditTenantProfile.php
  packages/panels/src/Pages/Tenancy/RegisterTenant.php
  packages/panels/src/Resources/Pages/CreateRecord.php
  packages/panels/src/Resources/Pages/EditRecord.php
  packages/panels/src/Resources/Pages/ListRecords.php
  packages/panels/src/Resources/Pages/ManageRelatedRecords.php
  packages/panels/src/Resources/Pages/Page.php
  packages/panels/src/Resources/Pages/ViewRecord.php
  packages/panels/src/Resources/Resource/Concerns/CanGenerateUrls.php
  packages/panels/src/Resources/Resource/Concerns/HasRoutes.php
  packages/upgrade/src/Rector/AddPanelParamToRouteMethodsRector.php
  packages/upgrade/src/Rector/ReplaceStringPanelParamWithPanelParamRector.php
  packages/upgrade/src/Rector/SimpleMethodChangesRector.php
  packages/upgrade/src/rector.php
Labels: enhancement

#16387 Update Swedish translations
  packages/panels/resources/lang/sv/pages/auth/email-verification/email-verification-prompt.php
  packages/panels/resources/lang/sv/pages/auth/password-reset/request-password-reset.php
Labels: i18n, pending review

#16390 fix/key-value component
  packages/forms/dist/components/key-value.js
  packages/forms/resources/js/components/key-value.js
Labels: bug

#16430 [v4] Aligned `headerEnd` Slot in `chart-widget.blade.php` with `section`'s blade slot naming
  packages/widgets/resources/views/chart-widget.blade.php
Labels: bug

#14975 Feature: Uncontained Fieldset
  docs-assets/app/app/Livewire/Schemas/LayoutDemo.php
  docs-assets/screenshots/images/dark/schemas/layout/fieldset/not-contained.jpg
  docs-assets/screenshots/images/light/schemas/layout/fieldset/not-contained.jpg
  docs-assets/screenshots/schema.js
  packages/panels/dist/theme.css
  packages/schemas/docs/02-layouts.md
  packages/schemas/resources/views/components/fieldset.blade.php
  packages/schemas/src/Components/Fieldset.php
  packages/support/resources/css/components/fieldset.css
  packages/support/resources/views/components/fieldset.blade.php
Labels: enhancement

#16433 fix(rector): method rename
  packages/upgrade/src/Rector/SimpleMethodChangesRector.php
Labels: bug

#16438 Fix typo in documentation
  packages/forms/docs/07-advanced.md
Labels: documentation

#16439 fix(docs): missing semicolon in code block
  docs/06-navigation/03-user-menu.md
Labels: documentation

#16441 fix(docs): typo in language of code block
  docs/14-upgrade-guide.md
Labels: documentation

#16444 fix: Select column enum
  packages/tables/src/Columns/SelectColumn.php
Labels: bug

#16419 Hidden fields in Section incorrectly dehydrated in Section with state path
  packages/forms/src/Components/Concerns/HasState.php
  tests/src/Forms/StateTest.php
Labels: bug

#16093 fix(repeater): bubble afterStateUpdated to parents
  packages/forms/src/Components/Concerns/HasState.php
  packages/forms/src/Concerns/HasState.php
Labels: bug

#16448 Fix unique() typo 14-upgrade-guide.md
  docs/14-upgrade-guide.md
Labels: documentation

#16456 Update upgrade guide to reflect namespace changes for Filament components
  docs/14-upgrade-guide.md
Labels: documentation

#16458 Recompile date-time-picker.js
  packages/forms/dist/components/date-time-picker.js
Labels: bug

#16460 [v4] docs: Use lowercase L in `Infolist`
  docs/03-resources/13-code-quality-tips.md
Labels: documentation

#16462 Docs: v4 Installation on Windows
  docs/01-introduction/02-installation.md
  docs/14-upgrade-guide.md
  packages/upgrade/bin/filament-v4
Labels: documentation

#16464 fix: Error handling for dropdown without menu items
  packages/support/resources/views/components/dropdown/index.blade.php
Labels: bug

#16467 Update spanish translations auth multifactor
  packages/panels/resources/lang/es/auth/multi-factor/app/provider.php
  packages/panels/resources/lang/es/auth/multi-factor/email/provider.php
Labels: i18n

#16476 Malay translations
  packages/actions/resources/lang/ms/delete.php
  packages/actions/resources/lang/ms/force-delete.php
  packages/actions/resources/lang/ms/restore.php
  packages/forms/resources/lang/ms/components.php
  packages/panels/resources/lang/ms/auth/pages/edit-profile.php
  packages/panels/resources/lang/ms/auth/pages/login.php
  packages/panels/resources/lang/ms/auth/pages/password-reset/request-password-reset.php
  packages/tables/resources/lang/ms/table.php
Labels: i18n

#16483 Table repeater not counting Hidden as actual column
  packages/forms/resources/views/components/repeater/table.blade.php
Labels: bug

#16488 fix: Grammarly diffing issues
  packages/forms/resources/views/components/textarea.blade.php
  packages/forms/src/Components/Textarea.php
  packages/support/resources/views/components/modal/index.blade.php
Labels: bug

#16491 fix: Windows import file validation
  packages/actions/src/Concerns/CanImportRecords.php
Labels: bug

#16522 Malay translations for MFA and email verifications
  packages/actions/resources/lang/ms/notifications.php
  packages/panels/resources/lang/ms/auth/http/controllers/block-email-change-verification-controller.php
  packages/panels/resources/lang/ms/auth/http/controllers/email-change-verification-controller.php
  packages/panels/resources/lang/ms/auth/multi-factor/app/actions/disable.php
  packages/panels/resources/lang/ms/auth/multi-factor/app/actions/regenerate-recovery-codes.php
  packages/panels/resources/lang/ms/auth/multi-factor/app/actions/set-up.php
  packages/panels/resources/lang/ms/auth/multi-factor/app/provider.php
  packages/panels/resources/lang/ms/auth/multi-factor/email/actions/disable.php
  packages/panels/resources/lang/ms/auth/multi-factor/email/actions/set-up.php
  packages/panels/resources/lang/ms/auth/multi-factor/email/notifications/verify-email-authentication.php
  packages/panels/resources/lang/ms/auth/multi-factor/email/provider.php
  packages/panels/resources/lang/ms/auth/multi-factor/pages/set-up-required-multi-factor-authentication.php
  packages/panels/resources/lang/ms/auth/multi-factor/recovery-codes-modal-content.php
  packages/panels/resources/lang/ms/auth/notifications/notice-of-email-change-request.php
  packages/panels/resources/lang/ms/error-notifications.php
Labels: i18n

#16533 Fix CSS Cascade Bug for Nested Sections
  packages/panels/dist/theme.css
  packages/support/resources/css/components/section.css
  packages/support/resources/views/components/section/index.blade.php
Labels: bug

#16538 Fix phantom blank option in Select component when default state exists
  packages/forms/dist/components/select.js
  packages/forms/resources/js/components/select.js
Labels: bug

#16535 Fix TOTP code expiration time documentation
  docs/07-users/02-multi-factor-authentication.md
Labels: documentation

#16545 Minor bugfix: Fixes NavigationItem's url parameter to not reset the shouldOpenUrlInNewTab flag
  packages/panels/src/Navigation/NavigationItem.php
Labels: bug

#16553 fix for html labels on table columns
  packages/tables/src/Concerns/HasColumnManager.php
Labels: bug

#16557 Update Huingarian translations
  packages/actions/resources/lang/hu/delete.php
  packages/actions/resources/lang/hu/force-delete.php
  packages/actions/resources/lang/hu/notifications.php
  packages/actions/resources/lang/hu/restore.php
  packages/forms/resources/lang/hu/components.php
  packages/panels/resources/lang/hu/auth/http/controllers/block-email-change-verification-controller.php
  packages/panels/resources/lang/hu/auth/http/controllers/email-change-verification-controller.php
  packages/panels/resources/lang/hu/auth/multi-factor/app/actions/disable.php
  packages/panels/resources/lang/hu/auth/multi-factor/app/actions/regenerate-recovery-codes.php
  packages/panels/resources/lang/hu/auth/multi-factor/app/actions/set-up.php
  packages/panels/resources/lang/hu/auth/multi-factor/app/provider.php
  packages/panels/resources/lang/hu/auth/multi-factor/email/actions/disable.php
  packages/panels/resources/lang/hu/auth/multi-factor/email/actions/set-up.php
  packages/panels/resources/lang/hu/auth/multi-factor/email/notifications/verify-email-authentication.php
  packages/panels/resources/lang/hu/auth/multi-factor/email/provider.php
  packages/panels/resources/lang/hu/auth/multi-factor/pages/set-up-required-multi-factor-authentication.php
  packages/panels/resources/lang/hu/auth/multi-factor/recovery-codes-modal-content.php
  packages/panels/resources/lang/hu/auth/notifications/notice-of-email-change-request.php
  packages/panels/resources/lang/hu/auth/pages/edit-profile.php
  packages/panels/resources/lang/hu/auth/pages/login.php
  packages/panels/resources/lang/hu/auth/pages/password-reset/request-password-reset.php
  packages/panels/resources/lang/hu/error-notifications.php
  packages/tables/resources/lang/hu/table.php
  packages/widgets/resources/lang/hu/chart.php
Labels: i18n

#16570 [v4] Docs - fix code block
  packages/actions/resources/lang/hu/force-delete.php
  packages/panels/resources/lang/hu/auth/pages/password-reset/request-password-reset.php
  packages/tables/docs/02-columns/01-overview.md
Labels: documentation

#16576 docs: Remove incomplete title
  docs/10-testing/04-testing-schemas.md
Labels: documentation

#16585 feat(panels): add render hooks for CONTENT_BEFORE and CONTENT_AFTER
  packages/panels/resources/views/components/layout/index.blade.php
  packages/panels/src/View/PanelsRenderHook.php
  packages/support/docs/06-render-hooks.md
Labels: enhancement

#16623 fix: Collapsed builder/repeater state being overwritten
  packages/forms/resources/views/components/builder.blade.php
  packages/forms/resources/views/components/repeater/index.blade.php
Labels: bug

#16626 fix: Query builder reset issue
  packages/tables/src/Concerns/HasFilters.php
Labels: bug

#16630 Fix: Export Data Contamination from Database ID Reuse
  packages/actions/src/Concerns/CanExportRecords.php
  packages/actions/src/Exports/Models/Export.php
Labels: bug

#16622 Fix: Mount actions on preview blocks
  packages/forms/resources/views/components/builder.blade.php
Labels: bug

#16628 refactor: extract Action context generation to method
  packages/actions/src/Action.php
Labels: enhancement

#16638 fix: Select dropdown positioning
  packages/forms/dist/components/select.js
  packages/forms/resources/css/components/select.css
  packages/forms/resources/js/components/select.js
  packages/panels/dist/theme.css
Labels: bug

#16640 fix: Pivot model casts during edit
  packages/tables/src/Actions/EditAction.php
Labels: bug

#16643 Add search param to query modification function on attach/associate actions
  packages/tables/src/Actions/AssociateAction.php
  packages/tables/src/Actions/AttachAction.php
Labels: enhancement

#16644 fix: Testing wizard `startOnStep()`
  packages/forms/src/Components/Wizard.php
Labels: bug

#16645 fix: Get grouped enabled options
  packages/forms/src/Components/Concerns/CanDisableOptions.php
Labels: bug

#16646 Fix: sortable error on builder component
  packages/forms/resources/views/components/builder.blade.php
Labels: bug

#16647 Collapse sidebar by default
  packages/panels/dist/index.js
  packages/panels/resources/js/stores/sidebar.js
Labels: bug

#16649 fix: Focused date time input
  packages/forms/dist/components/date-time-picker.js
  packages/forms/resources/js/components/date-time-picker.js
Labels: bug

#16650 fix: Markdown sanitization
  packages/infolists/src/Components/Concerns/CanFormatState.php
  packages/tables/src/Columns/Concerns/CanFormatState.php
  packages/tables/src/Columns/Summarizers/Concerns/CanFormatState.php
Labels: bug

#16651 fix: Hidden summaries
  packages/tables/resources/views/components/summary/index.blade.php
  packages/tables/resources/views/components/summary/row.blade.php
  packages/tables/resources/views/index.blade.php
  packages/tables/src/Columns/Concerns/CanBeSummarized.php
  packages/tables/src/Columns/Summarizers/Concerns/CanBeHidden.php
  packages/tables/src/Concerns/CanSummarizeRecords.php
  packages/tables/src/Table/Concerns/CanSummarizeRecords.php
  packages/tables/src/Table/Concerns/HasColumns.php
Labels: bug

#16654 fix: Builder label truncation
  packages/forms/resources/views/components/builder.blade.php
Labels: bug

#16657 fix: Date/time picker focused month/year
  packages/forms/dist/components/date-time-picker.js
  packages/forms/resources/js/components/date-time-picker.js
Labels: bug

#16670 fix: Don't get option labels without state
  packages/actions/src/Concerns/InteractsWithRecord.php
  packages/forms/resources/views/components/select.blade.php
Labels: bug

#16671 fix: Allow summary queries to be null
  packages/tables/src/Concerns/CanSummarizeRecords.php
  packages/tables/src/Contracts/HasTable.php
Labels: bug

#16680 Fix missing static in RichEditor docs
  packages/forms/docs/10-rich-editor.md
Labels: documentation

#16629 [4.x] Feat: additional rich editor extensions
  package-lock.json
  package.json
  packages/forms/dist/components/code-editor.js
  packages/forms/dist/components/file-upload.js
  packages/forms/dist/components/rich-editor.js
  packages/forms/dist/components/select.js
  packages/forms/docs/10-rich-editor.md
  packages/forms/resources/js/components/rich-editor/extension-lead.js
  packages/forms/resources/js/components/rich-editor/extension-small.js
  packages/forms/resources/js/components/rich-editor/extensions.js
  packages/forms/resources/lang/en/components.php
  packages/forms/src/Components/RichEditor.php
  packages/forms/src/Components/RichEditor/RichContentRenderer.php
  packages/forms/src/Components/RichEditor/TipTapExtensions/LeadExtension.php
  packages/forms/src/Components/RichEditor/TipTapExtensions/SmallExtension.php
  packages/panels/dist/fonts/inter/index.css
  packages/panels/dist/fonts/inter/inter-latin-ext-wght-normal-HA22NDSG.woff2
  packages/panels/dist/fonts/inter/inter-latin-wght-normal-NRMW37G5.woff2
  packages/panels/dist/theme.css
  packages/support/resources/css/utilities.css
  packages/support/resources/svg/s-align-center.svg
  packages/support/resources/svg/s-align-end.svg
  packages/support/resources/svg/s-align-justify.svg
  packages/support/resources/svg/s-align-start.svg
  packages/support/resources/svg/s-highlight.svg
  packages/support/resources/svg/s-lead.svg
  packages/support/resources/svg/s-small.svg
  packages/widgets/dist/components/chart.js
  packages/widgets/dist/components/stats-overview/stat/chart.js
Labels: enhancement

#16635 feat: add columnOrder() method
  packages/panels/dist/theme.css
  packages/schemas/docs/02-layouts.md
  packages/schemas/src/Components/Component.php
  packages/schemas/src/Components/Tabs/Tab.php
  packages/schemas/src/Components/Wizard/Step.php
  packages/schemas/src/Concerns/HasColumns.php
  packages/schemas/src/Schema.php
  packages/support/resources/css/components/grid.css
  packages/support/src/Concerns/CanOrderColumns.php
  packages/support/src/Concerns/CanSpanColumns.php
  packages/support/src/SupportServiceProvider.php
  tests/src/Forms/GridTest.php
Labels: enhancement

#16702 fix: Relation manager creation command
  packages/panels/src/Commands/MakeRelationManagerCommand.php
Labels: bug

#16707 Update missing spanish translations
  packages/forms/resources/lang/es/components.php
Labels: i18n

#16708 fix: Wizard without state path
  packages/schemas/src/Components/Concerns/HasState.php
Labels: bug

#16711 fix: Nested action schema output multiple times
  packages/actions/src/Concerns/InteractsWithActions.php
Labels: bug

#16712 fix: Spatie media library rich content rendering
  packages/forms/src/Components/RichEditor/RichContentRenderer.php
  packages/spatie-laravel-media-library-plugin/src/Forms/Components/RichEditor/FileAttachmentProviders/SpatieMediaLibraryFileAttachmentProvider.php
Labels: bug

#16723 doc: fix & enhance `columnOrder()` method examples to Schemas layouts
  packages/schemas/docs/02-layouts.md
Labels: documentation

#16726 fix: throw `NoDefaultPanelSetException`
  packages/panels/src/PanelRegistry.php
  packages/spatie-laravel-media-library-plugin/src/Forms/Components/RichEditor/FileAttachmentProviders/SpatieMediaLibraryFileAttachmentProvider.php
Labels: bug

#16731 feat(i18n): update serbian translations
  packages/actions/resources/lang/sr_Cyrl/edit.php
  packages/actions/resources/lang/sr_Latn/edit.php
  packages/forms/resources/lang/sr_Cyrl/components.php
  packages/forms/resources/lang/sr_Latn/components.php
Labels: i18n

#16737 feat: Rollback database transaction when halting from page
  packages/panels/src/Pages/BasePage.php
Labels: enhancement

#16739 Fix select.js component cleanup
  packages/forms/dist/components/select.js
  packages/forms/resources/js/components/select.js
Labels: bug

#16676 [4.x] Feat: Rich editor table extensions
  docs-assets/screenshots/images/dark/forms/fields/rich-editor/simple.jpg
  docs-assets/screenshots/images/light/forms/fields/rich-editor/simple.jpg
  package-lock.json
  package.json
  packages/forms/dist/components/rich-editor.js
  packages/forms/docs/10-rich-editor.md
  packages/forms/resources/css/components/rich-editor.css
  packages/forms/resources/js/components/rich-editor.js
  packages/forms/resources/js/components/rich-editor/extensions.js
  packages/forms/resources/lang/en/components.php
  packages/forms/resources/views/components/rich-editor.blade.php
  packages/forms/src/Components/RichEditor.php
  packages/forms/src/Components/RichEditor/RichContentRenderer.php
  packages/forms/src/Components/RichEditor/RichEditorTool.php
  packages/panels/dist/theme.css
  packages/support/resources/svg/s-table-add-column-after.svg
  packages/support/resources/svg/s-table-add-column-before.svg
  packages/support/resources/svg/s-table-add-row-after.svg
  packages/support/resources/svg/s-table-add-row-before.svg
  packages/support/resources/svg/s-table-delete-column.svg
  packages/support/resources/svg/s-table-delete-row.svg
  packages/support/resources/svg/s-table-delete.svg
  packages/support/resources/svg/s-table-merge-cells.svg
  packages/support/resources/svg/s-table-split-cell.svg
  packages/support/resources/svg/s-table-toggle-header-row.svg
  packages/support/resources/svg/s-table.svg
Labels: enhancement
